---
title: "USMR 2021-2022 Coursework"
author: "`r params$examnumber`"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
  pdf_document: default
params:
  examnumber:"B195653"
---

<!-- We have provided a template below with headings/sub-headings for each question/sub-question. This is just a template. Feel free to add or delete code-chunks if desired.  -->
<!-- Beneath here is some code which will set everything up for you.  Anything that is needed to run your code should be explicitly set up below -->


```{r setup, include=FALSE}
# this line will mean that when you compile/knit your document, 
# the code will not show, but the output (e.g., plots) will!
knitr::opts_chunk$set(echo = FALSE)
# this line means all numeric output gets rounded to 3 dp
options(digits=3)
# load any other packages that you require here:
library(tidyverse)
library(pander)
library(broom)
library(psych)
# This will read in your own personal data:
source("https://uoepsy.github.io/data/usmr_2122_data.R")
```

# Question 0
<!-- If you have run the R code above this point (you can do this now by pressing Ctrl-Shift-Alt-P, or running the chunk above) then your data will be in a dataframe called `couchto5k`. -->


```{r cleaning, include = FALSE}
# Neither output nor code from this chunk will be shown in the compiled document. 
couchto5k$missing <- NA
couchto5k[couchto5k == "autunm"]<-"autumn"
couchto5k$missing[couchto5k$age>100]<-"crazy age"
couchto5k$missing[couchto5k$selfmot<0]<-"crazy selfmot"
couchto5k$missing[couchto5k$week_stopped>9]<-"crazy week_stopped"
mtab<-table(couchto5k$missing)


couchto5k<-couchto5k %>% filter(is.na(missing))
total<-count(couchto5k)
```


The data were inspected and missing or unlikely values were removed, resulting in 'r total' observations for analysis. Table q gives a summary of removed data.
```{r descriptives}
# Code will not be shown from this chunk (because we set echo = FALSE in the very first chunk)
# the output from this code will be shown. 
mtab %>% pander(caption="Table 1:Summary of missing values.")
summary(couchto5k)
describe(couchto5k)
```

# Question 1 

## Question 1a

```{r q1a}
barplot(table(couchto5k$week_stopped))
hist(couchto5k$week_stopped,freq = F)
w<-cut(couchto5k$week_stopped,breaks = c(-Inf,4,8,Inf),labels = c("stopped before w5","stopped after w5","completed"))
chiTab<- table(w)
table(w)
chisq.test(chiTab, p=c(0.45,0.45,0.1))
```

## Question 1b

```{r q1b}
w<-cut(couchto5k$week_stopped,breaks = c(-Inf,4,8,Inf),labels = c("stopped before w5","stopped after w5","completed"))
cw<-cbind(couchto5k$city,w)
chisq.test(couchto5k$city,w)
```

## Question 1c

```{r q1c}
ca<-couchto5k[,c(2,8)]
ggplot(data = ca, aes(x = age, y = city)) + geom_boxplot()
shapiro.test(ca$age[ca$city == "Edinburgh"])
shapiro.test(ca$age[ca$city == "Glasgow"])
with(ca,var.test(age~city))
with(ca, t.test(ca$age~ca$city,alternative = "greater"))
```

# Question 2

## Question 2a

```{r q2a}
couchto5kmodel<-couchto5k[,c(6,7)]
couchto5kmodel1<-lm(happiness ~ season,data = couchto5kmodel)
couchto5kmodel1
plot(couchto5kmodel1,1:4)
summary(couchto5kmodel1)

```

## Question 2b

```{r q2b}
couchto5kmodel2<-lm(happiness ~ season+age,data = couchto5k)
summary(couchto5kmodel2)
plot(couchto5kmodel2,1:4)
```

## Question 2c

```{r q2c}
couchto5kmodel1<-lm(happiness ~ season,data = couchto5kmodel)
couchto5kmodel2<-lm(happiness ~ season+age,data = couchto5k)
anova(couchto5kmodel1,couchto5kmodel2)
```

# Question 3

## Question 3a

```{r q3a}
couchto5k <- couchto5k %>%
  mutate(completed=ifelse(week_stopped =="9","1","0"))
couchto5kmodel3a<-lm(happiness ~ season + completed, couchto5k)
summary(couchto5kmodel3a)
plot(couchto5kmodel3a,1:4)
confint(couchto5kmodel3a)
```

## Question 3b

```{r q3b}
couchto5kmodel3b <- lm(happiness ~ season + completed + health, couchto5k)
summary(couchto5kmodel3b)
plot(couchto5kmodel3b)
confint(couchto5kmodel3b)
```

## Question 3c

```{r q3c}
couchto5kmodel3c <- lm(happiness ~ season + completed + health + completed : health, couchto5k)
summary(couchto5kmodel3c)
plot(couchto5kmodel3c)
confint(couchto5kmodel3c)
```

## Question 3d


# Question 4

```{r q4}
couchto5k4a <- couchto5k[couchto5k$week_stopped == 9,]
dia1 <- couchto5k4a %>% group_by(season) %>%
  summarise(mean_se(happiness)) 
dia1%>% ggplot(aes(x=season, y=y, color = season, ymin=ymin, ymax=ymax)) + geom_bar(stat = "identity") + geom_errorbar(width =.2) + ylab("Average happiness ratings") + xlab("season")

dia2 <- couchto5k4a %>% group_by(city) %>%
  summarise(mean_se(happiness)) 
dia2%>% ggplot(aes(x=city, y=y, color = city, ymin=ymin, ymax=ymax)) + geom_bar(stat = "identity") + geom_errorbar(width =.2) + ylab("Average happiness ratings") + xlab("city")
 
```


# Question 5

## Question 5a

```{r q5a}
couchto5k$completed <- as.numeric(couchto5k$completed)
dropmodel <- glm(completed ~ accountability + selfmot + happiness, data = couchto5k, family = "binomial")
summary(dropmodel)
coef(dropmodel)
exp(coef(dropmodel))
```

## Question 5b

```{r q5b}
exp(coef(dropmodel))
```

## Question 5c

```{r q5c}
quitmodel <- glm(completed ~ selfmot, data = couchto5k, family = "binomial")
summary(quitmodel)

ggplot(data = couchto5k, aes(x = selfmot, y = completed)) +
  ylab("predicted probability of quitting") +
  geom_jitter( size = 3,width = 0, height = .2, alpha =.1) +
  geom_smooth(method = "glm", method.args = list(family = binomial)) +
  scale_y_continuous(breaks = seq(0,1,by = .2)) 
```










