---
title: "USMR 2021-2022 Coursework"
author: "`r params$examnumber`"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
  pdf_document: default
params:
  examnumber: B199270
---

<!-- We have provided a template below with headings/sub-headings for each question/sub-question. This is just a template. Feel free to add or delete code-chunks if desired.  -->
<!-- Beneath here is some code which will set everything up for you.  Anything that is needed to run your code should be explicitly set up below -->

```{r setup, include=FALSE}
# this line will mean that when you compile/knit your document, 
# the code will not show, but the output (e.g., plots) will!
knitr::opts_chunk$set(echo = FALSE)
# this line means all numeric output gets rounded to 3 dp
options(digits=3)
# load any other packages that you require here:
library(tidyverse)
library(sjPlot)
# This will read in your own personal data:
source("https://uoepsy.github.io/data/usmr_2122_data.R")
```

# Question 0
<!-- If you have run the R code above this point (you can do this now by pressing Ctrl-Shift-Alt-P, or running the chunk above) then your data will be in a dataframe called `couchto5k`. -->


```{r cleaning, include = FALSE}
# Neither output nor code from this chunk will be shown in the compiled document. 
# The couchto5k data has eight variables: age, accountability, self-motivation, health, happiness, season, city and week_stopped, and content of each is prescribed in data dictionary. The accountability variable is the sum of five questions, each scored 1-7, so the variable ranges from 5-35. For the same reason, self-motivation has the same range from 5-35 as well. Health and happiness has a scale of 0-100. Week_stopped ranges from 1-9, because couchto5k is a nine-week programme. The variable season should has season names as categorical factors, and the variable city has Edinburgh and Glasgow as categorical factors.
# According to the restrictions above, we now look at the distribution of each to find impossible values that go beyond prescriptions. To visualize the distribution, histograms are created for numeric variables that include age, accountability, self-motivation, health, happiness and week_stopped. The histograms show that some participants have unusual ages of 100 and 123, impossible self-motivation that are lower than 5, or stopped in impossible weeks later than 9. Tables are created for categorical variables that are season and city. Tables show that some participants joined the programme in an impossible season "autunm". 
hist(couchto5k$age)
hist(couchto5k$accountability)
hist(couchto5k$selfmot)
hist(couchto5k$health)
hist(couchto5k$happiness)
table(couchto5k$season)
table(couchto5k$city)
hist(couchto5k$week_stopped)
# These impossible values are handled differently. I set self-motivation that are lower than 5 and impossible weeks later than 9 as NAs. The season "autunm" is likely to be typos, so I change these into "autumn". Any age older than 109 is set as NA as well, because the Internet says that the oldest person ever in Scotland is 109 years in age. 
couchto5k <- 
  couchto5k %>% 
  mutate(
    age = ifelse(age>109, NA, age),
    selfmot = ifelse(selfmot<5, NA, selfmot),
    season = ifelse(season == "autunm", "autumn", season),
    week_stopped = ifelse(week_stopped>9, NA, week_stopped)
  )
# Apart from excluding or changing impossible values, I also decide to exclude numeric outliers that are three standard deviations away from the means since they may distort later statistical analysis. 
outliers <- function(obs, x = 3){
  abs(obs - mean(obs, na.rm=TRUE)) > (x * sd(obs, na.rm=TRUE))
}
# Only an age of 100 is identified as an outlier, excluded and set as NA. 
couchto5k$age[outliers(couchto5k$age)]<- NA
couchto5k$accountability[outliers(couchto5k$accountability)]<- NA
couchto5k$selfmot[outliers(couchto5k$selfmot)]<- NA
couchto5k$health[outliers(couchto5k$health)]<- NA
couchto5k$happiness[outliers(couchto5k$happiness)]<- NA
couchto5k$week_stopped[outliers(couchto5k$week_stopped)]<- NA
```

```{r descriptives}
# Code will not be shown from this chunk (because we set echo = FALSE in the very first chunk)
# the output from this code will be shown. 
# The Shapiro-Wilk normality tests and density plots are used for all numeric variables to determine whether they are normally distributed. A variable counts as normal distributed on the condition that it passes the test or display normal distribution in its density plot. 
# The normality tests are used for the six variables. Among them, age(p = 2e-04 < 0.05), self_motivation (p = 0.049 < 0.05), happiness(p = 6e-05 < 0.05), and week_stopped (p = 1e-12 < 0.05) have low probability of obtaining results at least as extreme as the results actually observed, under the assumption that the null hypothesis is correct (alpha = 0.05). So they pass the test and are determined to be normally distributed variables. 
shapiro.test(couchto5k$age)
shapiro.test(couchto5k$accountability)
shapiro.test(couchto5k$selfmot)$p.value
shapiro.test(couchto5k$health)
shapiro.test(couchto5k$happiness)
shapiro.test(couchto5k$week_stopped)
# Accountability and health have a high probability of observing such result under the null hypothesis, but their density plots display normal distributions. 
ggplot(data = couchto5k, aes(x = accountability)) +
  geom_density() +
  labs(x = "accountability")
ggplot(data = couchto5k, aes(x = health)) +
  geom_density() +
  labs(x = "health")
# In summary, the data features a fitness programme. After outlier exclusion they have a length of 123 participants. They are measured in six numeric dimensions and two categorical dimensions. 71.5% of them start the programme in Edinburgh (88/123), and 28.5% in Glasgow (35/123). About half of them start in spring (61/123), about one third in summer (36/123), and the rest in autumn and winter. All six numeric variables in data are normally distributed. Their ages range from a minimum of 18 and a maximum of 60 with a mean of 38.3 and a median of 38.0; their accountability scores range from a minimum of 9 and a maximum of 34 with a mean of 20 and a median of 20; their self-motivation scores range from a minimum of 9 and a maximum of 23 with a mean of 15.2 and a median of 15; their health measures range from a minimum of 37 and a maximum of 85 with a mean of 56.9 and a median of 56.0; their happiness scales range from a minimum of 0 and a maximum of 100 with a mean of 47.7 and a median of 47.0; The weeks they stopped the programme in range from a minimum of 1 and a maximum of 9 with a mean of 6.07 and a median of 8. 
summary(couchto5k)
table(couchto5k$season)
table(couchto5k$city)
```

# Question 1 

## Question 1a

```{r q1a}
# A new variable abandonpoint is created to map the three abandon phases in question. 
couchto5k <- 
  couchto5k %>% 
  mutate(
    abandonpoint = week_stopped
  )
# Abandonpoint categorizes week_stopped. Note that the nationwide survey sets the halfway point in week 5 as the first dividing point, while our data do not discriminate the first and second halves of weeks. So we choose the end of week 5 to match the first point in nationalwide survey. Weeks no later than the fifth are labelled as phase1, phase2 contains all weeks that are later than 5 but earlier than 9, and week 9 is labelled as phase 3, which marks the programme completion. 
couchto5k$abandonpoint <- cut(couchto5k$abandonpoint, breaks = c(-Inf,5,8,Inf), labels = c("phase1","phase2","phase3"))
# A chi-square test is used for the abandonpoints in previous and current surveys to determine whether the current data is in line with the previous ones. The previous data has a abandon probability of phase1:phase2:phase3 = .45:.1:.45. 
chisq.test(table(couchto5k$abandonpoint), p = c(.45,.1,.45))
# In conclusion, the proportions of participants abandoning the programme in three phases in this data is consistent with nationwide survey since the difference between the two sets of data is not statistically significant. The chi-square test shows that there is a low chi-square value and a high probability of obtaining a chi-square as large or larger than this and yet the data will still support the nationwide survey (chi-squared = 0.5, df = 2, p = 0.8 > 0.05).
```

## Question 1b

```{r q1b}
attritionbycity <- table(couchto5k$city, couchto5k$abandonpoint)
plot(attritionbycity)
# A chi-square test is used for the patterns of attrition rates by the two cities to determine whether Edinburgh and Glasgow have different patterns of attrition rates. 
chisq.test(attritionbycity)
# In conclusion, patterns of attrition rates do not differ by city since the difference between those of Edinburgh and Glasgow is not statistically significant. The chi-square test shows that there is a low chi-square value and a high probability of obtaining a chi-square as large or larger than this and yet the Glasgow attrition rate pattern would still support the Edinburgh's (chi-squared = 0.4, df = 2, p = 0.8 > 0.05).
```

## Question 1c

```{r q1c}
# We would use a t-test for the participants' ages by city to determine whether the average ages differ by Edinburgh and Glasgow, on the condition that the ages of each city are normal distributions. 
# Participants' ages by city is visualized in the box plots below. 
ggplot(data = couchto5k, aes(x = age, y = city)) +
  geom_boxplot()
# First, a Shapiro-Wilk normality test is used for Edinburgh participants' ages to determine whether it is a normal distribution. The test result shows a low p value which is a strong evidence in favor of Edinburgh ages being a normal distribution (p = 0.001 < 0.05). 
shapiro.test(couchto5k$age[couchto5k$city=="Edinburgh"])
# Second, the same test is used for Glasgow participants' ages. The test result shows a high probability (p = 0.1 > 0.05). So the result is not significantly evident that Glasgow participants have normally distributed ages. 
shapiro.test(couchto5k$age[couchto5k$city=="Glasgow"])
# So we look at its density plot and find that it displays a normal distribution. 
e <- data.frame(couchto5k$age[couchto5k$city == "Glasgow"])
ggplot(data = e, aes(x = couchto5k$age[couchto5k$city == "Glasgow"])) +
  geom_density()
# The participants' age in both cities are normal distributions, so a t-test can be used to determine whether average age differs by city. 
with(couchto5k, t.test(age ~ city, alternative = "two.sided"))
# In conclusion, the average ages of participants who commenced the programme differ by city, and the difference is statistically significant. There is a low possibility of observing the a difference between mean ages larger than the current one with the assumption that the difference is equal to zero (p = 0.002 < 0.05). 
```

# Question 2

## Question 2a

```{r q2a}
# A simple linear model is built for the relationship between happiness and the four seasons to determine whether happiness is affected by season. 
model2a <- lm(happiness ~ factor(season), data = couchto5k)
summary(model2a)
# The model is plotted as below.
plot_model(model2a, type = "pred",  terms=c("season"), show.data=TRUE)
# In conclusion, there is a significant linear relationship between happiness and season (p = 0.0024 < 0.05), but only in spring are participants’ happiness ratings significantly affected by the season they were interviewed (p = 0.00633 < 0.05).
```

## Question 2b

```{r q2b}
# We build a multiple linear regression model in which season and age predicts happiness to determine whether age, in addition to season, affects happiness. 
model2b <- lm(happiness ~ factor(season) + age, data = couchto5k)
summary(model2b)
# The model is plotted as below.
plot_model(model2b, type = "pred",  terms=c("season", "age"), show.data=TRUE)
# The graph below plots the relationship between happiness rates and age in four respective seasons. 
b <- couchto5k %>% ggplot(aes(x = age, y = happiness)) +
  xlab("age") + ylab("happiness") + 
  geom_point(size = 3) +
  geom_smooth(method = "lm") +
  facet_wrap(~season)
b
# In conclusion, age does not significantly affect happiness (p = 0.369 > 0.05).
```

## Question 2c

```{r q2c}
# We pick a multiple linear regression model, because happiness rates possibly have more than one predictor, such as health, season and their interactions, etc. In this current model, happiness have three predictors that are health, season and their interaction. 
model <- lm(happiness ~ health + season + health:season, data = couchto5k)
# The model is plotted as below.
plot_model(model, type = "pred",  terms=c("health", "season"), show.data=TRUE)
# An ANOVA analysis is used to assess the three predictors in the model, and the results show that this model fits our data. 
anova(model)
summary(model)
# In conclusion, the relationship between happiness and its predictors fits into a multiple regression model, and the fit is statistically significant (p = 9.43e-05 < 0.05). 
```

# Question 3

## Question 3a

```{r q3a}
# A new column called completion is created for whether or not participants completed the programme. Participants whose week_stopped is 9 are marked "yes" in this column, while those with week_stopped less than 9 are marked "no". 
couchto5k <- 
  couchto5k %>% 
  mutate(
    completion = week_stopped
  )
couchto5k$completion[couchto5k$completion == 9] <- "yes"
couchto5k$completion[couchto5k$completion < 9] <- "no"
# The variable completion is added into the linear model in Question 2c. Now the model has completion, health, season and the interaction between health and season as four predictors to happiness rates. 
model3a <- lm(happiness ~ completion + health + season + health:season, data = couchto5k)
summary(model3a)
# The plot below shows the relationship between completion and happiness in this new model. 
a <- ggplot(data = subset(couchto5k, !is.na(completion)), aes(x = factor(completion), y = happiness)) +
  xlab("completion") + ylab("happiness") + 
  geom_point(size = 3) +
  geom_smooth(method = "lm")
a
# In conclusion, participants’ happiness ratings are affected by whether or not they completed the programme in addition to health, season and their interaction, the effect is statistically significant (p = 1.64e-05 < 0.05). Completion of the programme will give happiness rates an increase of 15.807 (p = 0.015 < 0.05).
```

## Question 3b

```{r q3b}
# The model built in question 3a has already included health as predictor. The plot below displays the relationship between health and happiness in this model. 
summary(lm(happiness ~ completion + health + season + health:season, data = couchto5k))
c <- ggplot(data = subset(couchto5k), aes(x = health, y = happiness)) +
  xlab("health") + ylab("happiness") + 
  geom_point(size = 3) +
  geom_smooth(method = "lm")
c
# It can be concluded that the model does not show that happiness is additionally affected by the “health metric”, and the effect is not statistically significant (p = 0.621 >0.05).
```

## Question 3c

```{r q3c}
# The variable, the interaction between health and completion, is added into the linear model in Question 3b. Now the model has completion, health, season, the interactions between health and completion, and between health and season as five predictors to happiness rates. The interaction between health and completion does not affect happiness.
model1 <- lm(happiness ~ completion + health + season + health:completion + health:season, data = couchto5k)
summary(model1)
# The plot below displays the model. 
plot_model(model1, type = "pred",  terms=c("health","completion"), show.data=TRUE)
# We update the model and get its final version by eliminating insignificant predictors except health that are season and the interaction between season and health. 
modelfinal <- update(model1, ~ . -season -health:season)
# The plot below displays the final model. 
plot_model(model1, type = "pred",  terms=c("health","completion"), show.data=TRUE)
summary(modelfinal)
# In conclusion, the happiness of participants who got further along the programme is more affected by the health metric than that of those who stopped earlier, and the effect is statistically significant (p = 0.00113 < 0.05). 
```

## Question 3d


# Question 4

```{r q4}
newcouchto5k <- (couchto5k %>% filter(couchto5k$completion == "yes"))
# This plot displays the average happiness ratings grouped by season and city.
newcouchto5k %>% 
  ggplot(aes(x = city, y = happiness, fill = factor(season))) + 
  geom_boxplot()
```


# Question 5

## Question 5a

```{r q5a}
# change completion to numeric variable to fit into generalized linear model
couchto5k$completion[couchto5k$completion == "yes"] <- 0
couchto5k$completion[couchto5k$completion == "no"] <- 1
couchto5k$completion <- as.numeric(couchto5k$completion)
# A generalized linear model is created to predict the likelihood of dropping out. In this model, completion is predicted by accountability, self-motivation, age, happiness and health. 
dropoutmodel <- glm(completion ~ accountability + selfmot + age + happiness + health, data = couchto5k, family = "binomial")
# The model is plotted as below. 
plot_model(dropoutmodel, type = "pred",  terms=c("selfmot"), show.data=TRUE)
# We run a model test. From the results we see self motivation, age and health are statistically significant predictors, but we keep only the most significant one, self motivation. 
drop1(dropoutmodel, test = "F")
# So we update the model by excluding the relatively insignificant predictors. 
dropoutmodel <- update(dropoutmodel, ~ . -happiness -age -health -accountability)
drop1(dropoutmodel, test = "F")
# This plot display the final model that predicts the likelihood of drop out. 
plot_model(dropoutmodel, type = "pred",  terms=c("selfmot"), show.data=TRUE)
```

## Question 5b

```{r q5b}
#The odds of dropping out for someone whose self-motivation is 5 is 20.638:1. For every more self-motivation score someone has, the odds of dropping out decreases by 0.823.
exp(coef(dropoutmodel))
```

## Question 5c

```{r q5c}
#  This graphy displays the probability of quitting as a function of how self motivated participants were. 
dropoutmodel %>% ggplot(aes(x = selfmot, y = completion)) +
  ylab("p(DROPOUT)") +
  geom_jitter(size=3, width=0, height=.2, alpha=1) +
  geom_smooth(method="glm", method.args=list(family=binomial)) +
  scale_y_continuous(breaks=seq(0,1,by=.2))
```










