---
title: "USMR 2021-2022 Coursework"
author: "`r params$examnumber`"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
  pdf_document: default
params:
  examnumber: "B202343"
---

<!-- We have provided a template below with headings/sub-headings for each question/sub-question. This is just a template. Feel free to add or delete code-chunks if desired.  -->
<!-- Beneath here is some code which will set everything up for you.  Anything that is needed to run your code should be explicitly set up below -->

```{r setup, include=FALSE}
# this line will mean that when you compile/knit your document, 
# the code will not show, but the output (e.g., plots) will!
knitr::opts_chunk$set(echo = FALSE)
# this line means all numeric output gets rounded to 3 dp
options(digits=3)
# load any other packages that you require here:
library(tidyverse)
# This will read in your own personal data:
source("https://uoepsy.github.io/data/usmr_2122_data.R")
```

# Question 0
<!-- If you have run the R code above this point (you can do this now by pressing Ctrl-Shift-Alt-P, or running the chunk above) then your data will be in a dataframe called `couchto5k`. -->


```{r cleaning, include = FALSE}
# Neither output nor code from this chunk will be shown in the compiled document. 
#take an overview of the whole dataset 
summary(couchto5k)
#check the categorical variable and encode it
summary(as.factor(couchto5k$season))
couchto5k[couchto5k == "autunm"]<-"autumn"
#clean the unlikely data
couchto5k$missing <- NA
couchto5k$missing[couchto5k$age>100]<-"crazy age"
couchto5k$missing[couchto5k$selfmot<0]<-"crazy selfmot"
couchto5k$missing[couchto5k$week_stopped>9]<-"crazy week_stopped"
mtab<-table(couchto5k$missing)
couchto5k<-couchto5k%>%filter(is.na(missing))
total<-count(couchto5k)



```

```{r descriptives,results="asis"}
# Code will not be shown from this chunk (because we set echo = FALSE in the very first chunk)
# the output from this code will be shown. 
#show the results of removed data
library(pander)
mtab %>% pander(caption="Table 1: Summary of unlikely values.")

#visualize the data for each variable
ggplot(data = couchto5k, aes(x = week_stopped)) +
    geom_bar() +
    labs(x = "- week_stopped -")
ggplot(data = couchto5k, aes(x = season)) +
    geom_bar() +
    labs(x = "- season -")
plot(density(couchto5k$age))
plot(density(couchto5k$accountability))
plot(density(couchto5k$selfmot))
plot(density(couchto5k$health))
plot(density(couchto5k$happiness))

```

# Question 1 

## Question 1a
```{r q1a}
#Plot the distribution and get an initial overview of different stopped week 
ggplot(data = couchto5k, aes(x = week_stopped)) +
    geom_bar() +
    labs(x = "- week_stopped -")
#show the observed proportions of our sample with each stopped week
prop.table(table(couchto5k$week_stopped))
#setting up a new variable named spweek to divide the stopped weekend into 3 categories: before week5, stopped after week5 and completed.
couchto5k$spweek<-NA
couchto5k$spweek[couchto5k$week_stopped<5]<-"before week5"
couchto5k$spweek[couchto5k$week_stopped>=5 & couchto5k$week_stopped<9] <-"stopped after week5"
couchto5k$spweek[couchto5k$week_stopped==9]<-"completed"
#the table of three categories
chiTab<- table(couchto5k$spweek)
chiTab
#conduct the chisq.test
result1<-chisq.test(chiTab, p=c(0.45,0.1,0.45))
result1
#pull out the p value
chisq.test(chiTab, p=c(0.45,0.1,0.45))$p.value

```

```{r q1a. result1}
#result report
result1 %>% pander(caption="Table 2:chi-square test result")
```

## Question 1b
```{r q1b}
#use mosaic plot to visualize data
t<-couchto5k %>%
  select(spweek,city) %>%
  table()
t
plot(t)
#create the table of columns
mytable<-xtabs(~spweek+city,data=couchto5k)
mytable
#Carrying out a chi-square test of independence
result2<-chisq.test(mytable)
result2 %>% pander(caption="Table 3:chi-square test result")

```

## Question 1c
```{r q1c}
#assumption check: whether the observed sample has been drawn at random from the population of interest.
plot(density(couchto5k$age))
qqnorm(couchto5k$age)
ggplot(data=couchto5k,aes(x=age,y=city))+
  geom_boxplot()
#assumption check
shapiro.test(couchto5k$age[couchto5k$city=="Edinburgh"])
shapiro.test(couchto5k$age[couchto5k$city=="Glasgow"])
with(couchto5k,var.test(age~city))
#conduct t-est
with(couchto5k, t.test(age~city, alternative = "greater"))
result3<-t.test(couchto5k$age~couchto5k$city,alternative="greater")
result3 %>% pander(caption="Table 4:t test result")
```

# Question 2

## Question 2a
```{r q2a}
#exploring the data
p2a<-ggplot(data = couchto5k, aes(x = happiness)) +
  geom_density() +
  geom_boxplot(width = 1/100) +
  labs(x = "happiness", 
       y = "Probability density")
#fitting a linear model with season
mod1 <- lm(happiness ~ season, data=couchto5k)
summary(mod1)
#show the default contrast coding in R
contrasts(as.factor(couchto5k$season))
#more detail for assumption check: model diagnostics
plot(mod1,1:4)
#show the result
mod1 %>% pander(caption="Table 5: The relationship between season and happiness.")
```

## Question 2b
```{r q2b}
#exploring the data
ggplot(data = couchto5k, aes(x = age)) +
  geom_density() +
  geom_boxplot(width = 1/300) +
  labs(x = "age", 
       y = "Probability density")
#visualize the relationship between age and rating of happiness among the participants in the sample.
p2b<-couchto5k %>%
  ggplot(aes(x=age,y=happiness))+
  geom_point(size=3)+
  ylab("age")+
  xlab("happiness")
p2b
#fitting a linear model with age for actual effect size
mod2<-lm(happiness~age,data=couchto5k)
summary(mod2)
#more detail for assumption check: model diagnostics
plot(mod2,1:4)
#show the result
mod2 %>% pander(caption="Table 6: The relationship between age and happiness.")

```


## Question 2c
```{r q2c}
#fitting a linear model with season and age
mod3<-lm(happiness ~ season+age,data=couchto5k)
summary(mod3)
mod3 %>% pander(caption="Table 6: The relationship between season, age and happiness.")
#compare models
anova(mod3)
anova(mod3) %>% pander(caption="Table 7: Model comparison.")
```

# Question 3

## Question 3a
```{r q3a}
#quantifying the nominal predictor
couchto5k<-couchto5k %>%
  mutate(completion=ifelse(week_stopped == "9","1","0"))
#show the category result
couchto5k
#visualize the relationship
ggplot(couchto5k,aes(x=completion,y=happiness))+
  geom_jitter()+
  geom_smooth(method ='1m')
ggplot(couchto5k,aes(x=season, y = happiness)) +
  geom_point(alpha = 0.5) +
  labs(x = "season", y = "rating on happiness(range 0-100)")
#arrange plots
library(patchwork)
happiness_plot <- 
  ggplot(data = couchto5k, aes(x = happiness)) +
  geom_density() +
  geom_boxplot(width = 1/250) +
  labs(x = "rating on happiness (range 0-100)", y = "Probability\ndensity")
completion_plot <- 
  ggplot(data = couchto5k, aes(x = completion)) +
  geom_bar() +
  labs(x = "completion (week)", y = "Probability\ndensity")
season_plot <- 
  ggplot(data = couchto5k, aes(x = season)) +
  geom_density() +
  geom_boxplot(width = 1/150) +
  labs(x = "season", y = "Probability\ndensity")
# the "patchwork" library allows us to arrange multiple plots
happiness_plot / completion_plot / season_plot
#build a new linear model
mod4<-lm(happiness~season+completion, couchto5k)
summary(mod4)
coef(mod4)
#show the results
mod4 %>% pander(caption="Table 8: The relationship between programme completion and happiness.")
#model comparison
anova(mod4)%>%pander(caption="Table 9: Incremental F-test for programme completion")


```

## Question 3b
```{r q3b}
#visualise a marginal distribution
health_plot <- 
  ggplot(data = couchto5k, aes(x = health)) +
  geom_density() +
  geom_boxplot(width = 1/250) +
  labs(x = "health (range 0-100)", y = "Probability\ndensity")
health_plot
#visualize the relationship between health and happiness
ggplot(couchto5k,aes(x=health,y=happiness))+
  geom_jitter()+
  geom_smooth(method ='1m')
#actual effect size
mod5<-lm(happiness~season+health,data=couchto5k)
summary(mod5)
#model diagnostics
plot(mod5,1:4)
#show the results
mod5 %>% pander(caption="Table 10: The relationship between season, health and happiness")
#model comparison
anova(mod5)
anova(mod5)%>%pander(caption="Table 11: Incremental F-test for health")
```


## Question 3c
```{r q3c figure1, fig.asp=.6,fig.cap="Figure 1: the interaction effect between acting healthily and happiness.",message=FALSE}

#review the distribution and get an initial overview of different stopped week 
ggplot(data = couchto5k, aes(x = week_stopped)) +
    geom_bar() +
    labs(x = "- week_stopped -")
#divide the week_stopped into two categories: stop earlier, go further)
couchto5k$acting<-NA
couchto5k$acting[couchto5k$week_stopped<=5]<-"stop earlier"
couchto5k$acting[couchto5k$week_stopped>5]<-"go further"
#visualize the interaction relationship
couchto5k %>% ggplot(
  aes(x=health,y=happiness,colour=acting))+
  xlab("health")+
  ylab("happiness")+
  geom_point(size=3)+
  geom_smooth(method="lm")
```

```{r q3c}
#check the interaction effect size
mod6<-lm(happiness~season+acting*health,data=couchto5k)
summary(mod6)
#show the results
mod6 %>% pander(caption="Table 12: The relationship between season, acting and happiness")
 
```


## Question 3d
no code.

# Question 4
```{r q4 figure2, fig.asp=.6,fig.cap="Figure 2: the average happiness in different cities.",message=FALSE}
couchsubset<-couchto5k[couchto5k$completion==1,]
p41<-couchsubset %>% group_by(city)%>%
  summarise(mean_se(happiness))

p41 %>% ggplot(aes(x=city,y=y,ymin=ymin,ymax=ymax))+
  geom_bar(stat="identity")+
  geom_errorbar(width=.2)+
  ylab("Mean of happiness")+
  xlab("city")
```

```{r q4 figure3, fig.asp=.6, fig.cap="Figure 3:the average happiness in four season",message=FALSE}

p42<-couchsubset %>% group_by(season)%>%
  summarise(mean_se(happiness))

p42%>% ggplot(aes(x=season,y=y,ymin=ymin,ymax=ymax))+
  geom_bar(stat="identity")+
  geom_errorbar(width=0.2)+
  ylab("mean of happiness")+
  xlab("season")

```


# Question 5

## Question 5a
```{r q5a figure4, fig.asp=.6, fig.cap="Figure 4:visulaized relationship between selfmot/accountability and dropout",message=FALSE}
#divide the stopped week into two categories
couchto5k<-couchto5k %>%
  mutate(dropout=ifelse(week_stopped == 9,0,1))
#plot the relationship between the selfmot and dropout 
q41<-ggplot(couchto5k, aes(x=selfmot, y=dropout))+
  geom_point()+
  geom_smooth(method="lm")
#plot the relationship between the accountability and dropout
q42<-ggplot(couchto5k, aes(x=accountability, y=dropout))+
  geom_point()+
  geom_smooth(method="lm")
library(patchwork)
q41+q42

#fitting a generalized linear model
mod7<-glm(dropout~accountability+selfmot,data=couchto5k,family="binomial")
summary(mod7)



```

## Question 5b
```{r q5b}
summary(mod7)$coefficients
#convert to odds
exp(coef(mod7))
#show the results
mod7 %>% pander(caption="Table 13: The relationship between accountability, selfmot and happiness")
exp(coef(mod7)) %>% pander(caption:"Table 14: translate the log-odds into odds")



```

## Question 5c
```{r q5c figure5, fig.asp=.6, fig.cap="Figure 5:the relationship between self motivation and the probability of quitting",message=FALSE}
#fitting a new generalized linear model
mod8<-glm(dropout~selfmot,family="binomial",couchto5k)
#show the results
summary(mod8)
#visualize results
couchto5k %>% ggplot(aes(x=selfmot, y=dropout))+
  ylab("Probability of quitting")+
  xlab("Self-motivation")+
  geom_jitter(size=3,width=0,height=0.2,alpha=0.1)+
  geom_smooth(method="glm",method.args=list(family=binomial))+
  scale_y_continuous(breaks=seq(0,1,by=0.2))+
  scale_x_continuous(breaks=seq(5,35,by=5))
  
  
```










