{
  "hash": "aea4aaf59a1a12c93a3177b892a649c9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercises: Covariance, Correlation & Linear Regression\"\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n# Covariance & Correlation  \n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nGo to [http://guessthecorrelation.com/](http://guessthecorrelation.com/){target=\"_blank\"} and play the \"guess the correlation\" game for a little while to get an idea of what different strengths and directions of $r$ can look like.\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n## Sleepy time  \n\n:::frame\n__Data: Sleep levels and daytime functioning__  \n\nA researcher is interested in the relationship between hours slept per night and self-rated effects of sleep on daytime functioning. She recruited 50 healthy adults, and collected data on the Total Sleep Time (TST) over the course of a seven day period via sleep-tracking devices.  \nAt the end of the seven day period, participants completed a Daytime Functioning (DTF) questionnaire. This involved participants rating their agreement with ten statements (see @tbl-sleepitems). Agreement was measured on a scale from 1-5. An overall score of daytime functioning can be calculated by:  \n\n1. reversing the scores for items 4,5 and 6 (because those items reflect agreement with _positive_ statements, whereas the other ones are agreement with _negative_ statement);\n2. summing the scores on each item; and \n3. subtracting the sum score from 50 (the max possible score). This will make higher scores reflect better perceived daytime functioning.  \n\nThe data is available at [https://uoepsy.github.io/data/sleepdtf.csv](https://uoepsy.github.io/data/sleepdtf.csv){target=\"_blank\"}. \n  \n\n\n\n::: {#tbl-sleepitems .cell layout-align=\"center\" tbl-cap='Daytime Functioning Questionnaire'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rhalowgmgj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rhalowgmgj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rhalowgmgj thead, #rhalowgmgj tbody, #rhalowgmgj tfoot, #rhalowgmgj tr, #rhalowgmgj td, #rhalowgmgj th {\n  border-style: none;\n}\n\n#rhalowgmgj p {\n  margin: 0;\n  padding: 0;\n}\n\n#rhalowgmgj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rhalowgmgj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rhalowgmgj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rhalowgmgj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rhalowgmgj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rhalowgmgj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rhalowgmgj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rhalowgmgj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rhalowgmgj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rhalowgmgj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rhalowgmgj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rhalowgmgj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rhalowgmgj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rhalowgmgj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rhalowgmgj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhalowgmgj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rhalowgmgj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rhalowgmgj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rhalowgmgj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhalowgmgj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rhalowgmgj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhalowgmgj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rhalowgmgj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhalowgmgj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rhalowgmgj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhalowgmgj .gt_left {\n  text-align: left;\n}\n\n#rhalowgmgj .gt_center {\n  text-align: center;\n}\n\n#rhalowgmgj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rhalowgmgj .gt_font_normal {\n  font-weight: normal;\n}\n\n#rhalowgmgj .gt_font_bold {\n  font-weight: bold;\n}\n\n#rhalowgmgj .gt_font_italic {\n  font-style: italic;\n}\n\n#rhalowgmgj .gt_super {\n  font-size: 65%;\n}\n\n#rhalowgmgj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rhalowgmgj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rhalowgmgj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rhalowgmgj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rhalowgmgj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rhalowgmgj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rhalowgmgj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rhalowgmgj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rhalowgmgj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Item\">Item</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Statement\">Statement</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Item\" class=\"gt_row gt_left\">Item_1</td>\n<td headers=\"Statement\" class=\"gt_row gt_left\">I often felt an inability to concentrate</td></tr>\n    <tr><td headers=\"Item\" class=\"gt_row gt_left\">Item_2</td>\n<td headers=\"Statement\" class=\"gt_row gt_left\">I frequently forgot things</td></tr>\n    <tr><td headers=\"Item\" class=\"gt_row gt_left\">Item_3</td>\n<td headers=\"Statement\" class=\"gt_row gt_left\">I found thinking clearly required a lot of effort</td></tr>\n    <tr><td headers=\"Item\" class=\"gt_row gt_left\">Item_4</td>\n<td headers=\"Statement\" class=\"gt_row gt_left\">I often felt happy</td></tr>\n    <tr><td headers=\"Item\" class=\"gt_row gt_left\">Item_5</td>\n<td headers=\"Statement\" class=\"gt_row gt_left\">I had lots of energy</td></tr>\n    <tr><td headers=\"Item\" class=\"gt_row gt_left\">Item_6</td>\n<td headers=\"Statement\" class=\"gt_row gt_left\">I worked efficiently</td></tr>\n    <tr><td headers=\"Item\" class=\"gt_row gt_left\">Item_7</td>\n<td headers=\"Statement\" class=\"gt_row gt_left\">I often felt irritable</td></tr>\n    <tr><td headers=\"Item\" class=\"gt_row gt_left\">Item_8</td>\n<td headers=\"Statement\" class=\"gt_row gt_left\">I often felt stressed</td></tr>\n    <tr><td headers=\"Item\" class=\"gt_row gt_left\">Item_9</td>\n<td headers=\"Statement\" class=\"gt_row gt_left\">I often felt sleepy</td></tr>\n    <tr><td headers=\"Item\" class=\"gt_row gt_left\">Item_10</td>\n<td headers=\"Statement\" class=\"gt_row gt_left\">I often felt fatigued</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\nLoad the required libraries (probably just __tidyverse__ for now), and read in the data.  \nCalculate the overall daytime functioning score, following the criteria outlined above, and make this a new column in your dataset.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \nTo reverse items 4, 5 and 6, we we need to make all the scores of 1 become 5, scores of 2 become 4, and so on... What number satisfies all of these equations: `? - 5 = 1`, `? - 4 = 2`, `? - 3 = 3`?  \n  \nTo quickly sum across rows, you might find the `rowSums()` function useful (you don't have to use it though)  \nIf my items were in columns between 4 to 15:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndataframe$sumscore = rowSums(dataframe[, 4:15])\n```\n:::\n\n\n\n\n:::\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-1' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-1', 'sol-start-1')\">  Solution Part 1 - Reversing Items</button></div><div class=\"solution-body\" id = \"sol-body-1\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsleepdtf <- read_csv(\"https://uoepsy.github.io/data/sleepdtf.csv\")\nsummary(sleepdtf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      TST             item_1         item_2         item_3         item_4    \n Min.   : 4.900   Min.   :1.00   Min.   :1.00   Min.   :1.00   Min.   :1.00  \n 1st Qu.: 7.225   1st Qu.:1.00   1st Qu.:2.00   1st Qu.:1.25   1st Qu.:1.00  \n Median : 7.900   Median :1.00   Median :2.00   Median :2.00   Median :1.00  \n Mean   : 8.004   Mean   :1.58   Mean   :2.46   Mean   :2.38   Mean   :1.26  \n 3rd Qu.: 9.025   3rd Qu.:2.00   3rd Qu.:3.00   3rd Qu.:3.00   3rd Qu.:1.00  \n Max.   :11.200   Max.   :3.00   Max.   :5.00   Max.   :5.00   Max.   :3.00  \n     item_5         item_6         item_7         item_8        item_9    \n Min.   :1.00   Min.   :1.00   Min.   :1.00   Min.   :1.0   Min.   :1.00  \n 1st Qu.:2.00   1st Qu.:2.00   1st Qu.:1.00   1st Qu.:2.0   1st Qu.:2.00  \n Median :2.00   Median :3.00   Median :2.00   Median :2.5   Median :3.00  \n Mean   :2.36   Mean   :2.78   Mean   :2.04   Mean   :2.5   Mean   :2.96  \n 3rd Qu.:3.00   3rd Qu.:4.00   3rd Qu.:3.00   3rd Qu.:3.0   3rd Qu.:4.00  \n Max.   :4.00   Max.   :5.00   Max.   :4.00   Max.   :4.0   Max.   :5.00  \n    item_10    \n Min.   :1.00  \n 1st Qu.:2.00  \n Median :3.00  \n Mean   :2.54  \n 3rd Qu.:3.00  \n Max.   :5.00  \n```\n\n\n:::\n:::\n\n\n\n\nTo reverse the items, we can simply do 6 minus the score: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsleepdtf <- \n  sleepdtf |> mutate(\n    item_4=6-item_4,\n    item_5=6-item_5,\n    item_6=6-item_6\n  ) \n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution Part 2 - Creating a scale score</button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\nNow we can use `rowSums()`, and subtract the sum scores from from 50 (the max score):  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsleepdtf$dtf = 50-rowSums(sleepdtf[, 2:11])\n```\n:::\n\n\n\n\nAn alternative way to do this would be: \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsleepdtf |> \n  mutate(\n    dtf = 50 - (item_1 + item_2 + item_3 + item_4 + item_5 + item_6 + item_7 + item_8 + item_9 + item_10)\n  )\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nCalculate the correlation between the total sleep time (`TST`) and the overall daytime functioning score calculated in the previous question.  \nConduct a test to establish the probability of observing a correlation this strong in a sample of this size assuming the true correlation to be 0.  \n\nWrite a sentence or two summarising the results. \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \nYou can do this all with one function, see [5A #correlation-test](05a_covcor.html#correlation-tests){target=\"_blank\"}.  \n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(sleepdtf$TST, sleepdtf$dtf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  sleepdtf$TST and sleepdtf$dtf\nt = 6.244, df = 48, p-value = 1.062e-07\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.4807039 0.7989417\nsample estimates:\n      cor \n0.6694741 \n```\n\n\n:::\n:::\n\n\n\n\n:::int\nThere was a strong positive correlation between total sleep time and self-reported daytime functioning score ($r$ = 0.67, $t(48)$ = 6.24, $p < .001$) in the current sample. As total sleep time increased, levels of self-reported daytime functioning increased. \n:::\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 4 (open-ended)</div><div class='question-body'>\n\n\nThink about this relationship in terms of _causation_.  \n<br>\nClaim: _Less sleep causes poorer daytime functioning._  \n<br>\nWhy might it be inappropriate to make the claim above based on these data alone? Think about what sort of study could provide stronger evidence for such a claim.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Things to think about:  \n\n+ comparison groups.   \n+ random allocation.  \n+ measures of daytime functioning.   \n+ measures of sleep time.  \n+ other (unmeasured) explanatory variables.  \n\n:::\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Attendance and Attainment\n\n:::frame\n__Data: Education SIMD Indicators__  \n\nThe Scottish Government regularly collates data across a wide range of societal, geographic, and health indicators for every \"datazone\" (small area) in Scotland.  \n\nThe dataset at [https://uoepsy.github.io/data/simd20_educ.csv](https://uoepsy.github.io/data/simd20_educ.csv){target=\"_blank\"} contains some of the education indicators (see @tbl-simd).  \n\n\n\n\n::: {#tbl-simd .cell layout-align=\"center\" tbl-cap='Education indicators from the 2020 SIMD data'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"voaqjfxten\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#voaqjfxten table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#voaqjfxten thead, #voaqjfxten tbody, #voaqjfxten tfoot, #voaqjfxten tr, #voaqjfxten td, #voaqjfxten th {\n  border-style: none;\n}\n\n#voaqjfxten p {\n  margin: 0;\n  padding: 0;\n}\n\n#voaqjfxten .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#voaqjfxten .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#voaqjfxten .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#voaqjfxten .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#voaqjfxten .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#voaqjfxten .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#voaqjfxten .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#voaqjfxten .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#voaqjfxten .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#voaqjfxten .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#voaqjfxten .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#voaqjfxten .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#voaqjfxten .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#voaqjfxten .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#voaqjfxten .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#voaqjfxten .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#voaqjfxten .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#voaqjfxten .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#voaqjfxten .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#voaqjfxten .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#voaqjfxten .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#voaqjfxten .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#voaqjfxten .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#voaqjfxten .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#voaqjfxten .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#voaqjfxten .gt_left {\n  text-align: left;\n}\n\n#voaqjfxten .gt_center {\n  text-align: center;\n}\n\n#voaqjfxten .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#voaqjfxten .gt_font_normal {\n  font-weight: normal;\n}\n\n#voaqjfxten .gt_font_bold {\n  font-weight: bold;\n}\n\n#voaqjfxten .gt_font_italic {\n  font-style: italic;\n}\n\n#voaqjfxten .gt_super {\n  font-size: 65%;\n}\n\n#voaqjfxten .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#voaqjfxten .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#voaqjfxten .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#voaqjfxten .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#voaqjfxten .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#voaqjfxten .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#voaqjfxten .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#voaqjfxten .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#voaqjfxten div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">intermediate_zone</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Areas of scotland containing populations of between 2.5k-6k household residents</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">attendance</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Average School pupil attendance</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">attainment</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Average attainment score of School leavers (based on Scottish Credit and Qualifications Framework (SCQF))</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">university</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Proportion of 17-21 year olds entering university</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\nConduct a test of whether there is a correlation between school attendance and school attainment in Scotland.  \n\nPresent and write up the results.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \n\nThe readings have _not_ included an example write-up for you to follow. Try to follow the logic of those for t-tests and $\\chi^2$-tests. \n\n  - describe the relevant data\n  - explain what test was conducted and why\n  - present the relevant statistic, degrees of freedom (if applicable), statement on p-value, etc. \n  - state the conclusion.  \n \nBe careful figuring out how many observations your test is conducted on. `cor.test()` includes only the _complete_ observations. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimd <- read_csv(\"https://uoepsy.github.io/data/simd20_educ.csv\")\n```\n:::\n\n\n\n\nHere are the means of the two variables. We should remember that these calculations will include some observations which have missing data on the other variable.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimd |> \n  summarise(\n    m_attendance = mean(attendance, na.rm = TRUE),\n    m_attainment = mean(attainment, na.rm = TRUE)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  m_attendance m_attainment\n         <dbl>        <dbl>\n1        0.811         5.53\n```\n\n\n:::\n:::\n\n\n\nInstead, to match with our analysis, we might be inclined to filter our data to complete data:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimd_comp <- simd |> \n  filter(!is.na(attendance) & !is.na(attainment))\n\nsimd_comp |>\n  summarise(\n    m_attendance = mean(attendance),\n    m_attainment = mean(attainment),\n    sd_attendance = sd(attendance),\n    sd_attainment = sd(attainment)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  m_attendance m_attainment sd_attendance sd_attainment\n         <dbl>        <dbl>         <dbl>         <dbl>\n1        0.811         5.53        0.0696         0.386\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(simd_comp$attendance, simd_comp$attainment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  simd_comp$attendance and simd_comp$attainment\nt = 51.495, df = 1242, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.8066637 0.8421951\nsample estimates:\n      cor \n0.8252442 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n:::int\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\nA correlation test was conducted to assess whether there is a relationship between an area's average school attendance, and its average school attainment level. A total of 1244 geographical areas were included in the analysis, with a mean school attendance of 0.81 (SD = 0.07) and a mean school attainment score of 5.53 (SD = 0.39).  \nThere was a strong positive correlation between a geographical area's level of school attendance and its school attainment ($r$ = 0.83, $t(1242)$ = 51.5, $p < 0.001$). We therefore reject the null hypothesis that there is no correlation between an area's school attendance and attainment. @fig-simdplot provides a visualisation of the relationship.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(simd_comp, aes(x=attendance, y=attainment)) + \n  geom_point() + \n  labs(x = \"School attendance\",\n       y = \"School attainment\")\n```\n\n::: {.cell-output-display}\n![Positive relationship between geographical areas' level of school attendance and school attainment](05_ex_files/figure-html/fig-simdplot-1.png){#fig-simdplot fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n#### Optional: some extra plotting bits  \n\nSometimes we may want to highlight certain parts of a plot. We can do that using the __gghighlight__ package, and giving it a set of conditions (like we do for `filter()`) in order for it to decide which points to highlight.  \nYou can see an example below.  \nWe have also created the title by referring to the `cor()` function, and 'paste'ing it together to \"r = \" \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(gghighlight)\n\nggplot(simd_comp, aes(x=attendance, y=attainment)) + \n  geom_point() + \n  gghighlight( (attainment>6 & attendance<.75) | \n               attendance > .95 | \n               (attendance > .82 & attainment<5),\n               label_key = intermediate_zone) + \n  labs(x = \"School attendance\",\n       y = \"School attainment\",\n       title = paste0(\"r = \",\n                       round(\n                         cor(simd_comp$attendance,\n                                  simd_comp$attainment),\n                         2)\n                       ))\n```\n\n::: {.cell-output-display}\n![](05_ex_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n\n\n<!-- ## Optional Extras: Functions & Models -->\n\n<!-- \n\n<div class='question-begin'>Optional Extra 1</div><div class='question-body'>\n\n -->\n<!-- The Scottish National Gallery kindly provided us with measurements of side and perimeter (in metres) for a sample of 10 square paintings. -->\n\n<!-- The data are provided below:   -->\n<!-- _Note: this is a way of creating a \"tibble\" (a dataframe in 'tidyverse-style' language) in R, rather than reading one in from an external file._   -->\n<!-- ```{r eval=FALSE} -->\n<!-- sng <- tibble( -->\n<!--   side = c(1.3, 0.75, 2, 0.5, 0.3, 1.1, 2.3, 0.85, 1.1, 0.2), -->\n<!--   perimeter = c(5.2, 3.0, 8.0, 2.0, 1.2, 4.4, 9.2, 3.4, 4.4, 0.8) -->\n<!-- ) -->\n<!-- ``` -->\n\n<!-- Plot the data from the Scottish National Gallery using `ggplot()`, with the side measurements of the paintings on the x-axis, and the perimeter measurements on the y-axis.   -->\n\n<!-- We know that there is a mathematical model for the relationship between the side-length and perimeter of squares: $perimeter = 4 \\times \\ side$.   -->\n\n<!-- Try adding the following line to your plot: -->\n<!-- ```{r eval=FALSE} -->\n<!--   stat_function(fun = ~.x * 4) -->\n<!-- ``` -->\n<!-- \n\n</div><p class=\"question-end\"></p>\n\n -->\n<!-- \n\n<div style=\"display:none;\">\n\n -->\n<!-- ```{r} -->\n<!-- #| label: fig-squares-scatterplot -->\n<!-- #| fig.cap: 'The exact relationship between side and perimeter of squares.' -->\n<!-- sng <- tibble( -->\n<!--   side = c(1.3, 0.75, 2, 0.5, 0.3, 1.1, 2.3, 0.85, 1.1, 0.2), -->\n<!--   perimeter = c(5.2, 3.0, 8.0, 2.0, 1.2, 4.4, 9.2, 3.4, 4.4, 0.8) -->\n<!-- ) -->\n\n<!-- ggplot(data = sng, aes(x = side, y = perimeter)) + -->\n<!--   geom_point(colour = 'black', alpha = 0.5, size = 3) + -->\n<!--   labs(x = 'Side (m)', y = 'Perimeter (m)')+ -->\n<!--   stat_function(fun = ~.x * 4) -->\n<!-- ``` -->\n\n<!-- The above plot shows perfect agreement between the observed data and the model. -->\n<!-- \n\n</div><p class=\"solution-end\"></p>\n\n -->\n\n<!-- \n\n<div class='question-begin'>Optional Extra 2</div><div class='question-body'>\n\n -->\n<!-- Use our mathematical model to predict the perimeter of a painting with a side of 1.5 metres.   -->\n\n<!-- ::: {.callout-tip collapse=\"true\"} -->\n<!-- #### Hints   -->\n<!-- We don't have a painting with a side of 1.5 metres within the random sample of paintings from the Scottish National Gallery, but we can work out the perimeter of an hypothetical square painting with 1.5m sides, using our model - either using the plot from the previous question, or calculating it algebraically.   -->\n<!-- ::: -->\n\n<!-- \n\n</div><p class=\"question-end\"></p>\n\n -->\n<!-- \n\n<div style=\"display:none;\">\n\n -->\n<!-- **Visual approach** -->\n\n<!-- ```{r echo=FALSE} -->\n<!-- ggplot(data = sng, aes(x = side, y = perimeter)) + -->\n<!--   geom_point(colour = 'black', alpha = 0.5, size = 3) + -->\n<!--   labs(x = 'Side (m)', y = 'Perimeter (m)')+ -->\n<!--   stat_function(fun = ~.x * 4) + -->\n<!--   geom_segment(aes(x = 1.5, xend = 1.5, y = 0, yend = 4 * 1.5), linetype = 2,  -->\n<!--                colour = 'red', arrow = arrow(length = unit(0.5, \"cm\"))) + -->\n<!--   geom_segment(aes(x = 1.5, xend = 0 , y = 4 * 1.5, yend = 4 * 1.5), linetype = 2,  -->\n<!--                colour = 'red', arrow = arrow(length = unit(0.5, \"cm\"))) + -->\n<!--   labs(x = 'Side (m)', y = 'Perimeter (m)') -->\n<!-- ``` -->\n\n<!-- Sometimes we can directly read a predicted value from the graph of the functional relationship. -->\n\n<!-- Consider the plot created in the previous question. First, we need to check where x = 1.5. Then, we draw a vertical dashed line until it meets the blue line. The y value corresponding to x = 1.5 can be read off the y-axis. -->\n\n<!-- However, in this case it is not that easy to read it from the drawing... Let's try the next approach. -->\n\n<!-- <br> -->\n<!-- **Algebraic approach** -->\n\n<!-- You can substitute the x value in the formula and calculate the corresponding y value. -->\n<!-- $$ -->\n<!-- \\begin{align} -->\n<!-- perimeter &= 4 \\times \\ side \\\\ -->\n<!-- &= 4 \\times \\ (1.5) \\\\ -->\n<!-- &= 6 -->\n<!-- \\end{align} -->\n<!-- $$ -->\n\n<!-- <br> -->\n\n<!-- :::int -->\n<!-- The predicted perimeter of squared paintings having a 1.5m side is 6m. -->\n<!-- ::: -->\n\n<!-- **NOTE**: Don't forget to always include the measurement units when reporting/writing-up results! -->\n\n<!-- \n\n</div><p class=\"solution-end\"></p>\n\n -->\n\n<!-- :::frame -->\n<!-- __Data: HandHeight__ -->\n\n<!-- This dataset, from Jessican M Utts and Robert F Heckard. 2015. _Mind on Statistics_ (Cengage Learning)., records the height and handspan reported by a random sample of 167 students as part of a class survey.   -->\n\n<!-- The variables are: -->\n\n<!-- - `height`, measured in inches -->\n<!-- - `handspan`, measured in centimetres -->\n\n<!-- The data are available at [https://uoepsy.github.io/data/handheight.csv](https://uoepsy.github.io/data/handheight.csv){target=\"_blank\"} -->\n\n<!-- ::: -->\n\n<!-- \n\n<div class='question-begin'>Optional Extra 3</div><div class='question-body'>\n\n -->\n<!-- Consider the relationship between height (in inches) and handspan (in cm).   -->\n\n<!-- Read the handheight data into R, and investigate (visually) how handspan varies as a function of height for the students in the sample. -->\n\n<!-- Do you notice any outliers or points that do not fit with the pattern in the rest of the data?  -->\n\n<!-- Comment on any main differences you notice between this relationship and the relationship between sides and perimeter of squares. -->\n<!-- \n\n</div><p class=\"question-end\"></p>\n\n -->\n<!-- \n\n<div style=\"display:none;\">\n\n -->\n<!-- The `handheight` data set contains two variables, height and handspan, which are both numeric and continuous. We display the relationship between two numeric variables with a scatterplot.   -->\n\n<!-- We can also add marginal boxplots for each variable using the package `ggExtra`. Before using the package, make sure you have it installed via `install.packages('ggExtra')`. -->\n\n<!-- ```{r} -->\n<!-- #| label: fig-handheight-scatterplot -->\n<!-- #| fig.cap: 'The statistical relationship between height and handspan.' -->\n<!-- handheight <- read_csv(file = 'https://uoepsy.github.io/data/handheight.csv') -->\n\n<!-- library(ggExtra) -->\n\n<!-- plt <- ggplot(handheight, aes(x = height, y = handspan)) + -->\n<!--   geom_point(size = 3, alpha = 0.5) + -->\n<!--   labs(x = 'Height (in.)', y = 'Handspan (cm)') -->\n\n<!-- ggMarginal(plt, type = 'boxplot') -->\n<!-- ``` -->\n\n<!-- Outliers are extreme observations that do not seem to fit with the rest of the data. This could either be: -->\n\n<!-- - *marginally* along one axis: points that have an unusual (too high or too low) x-coordinate or y-coordinate; -->\n<!-- - *jointly*: observations that do not fit with the rest of the point cloud. -->\n\n<!-- The boxplots in fig-handheight-scatterplot do not highlight any outliers in the marginal distributions of height and handspan. -->\n<!-- Furthermore, from the scatterplot we do not notice any extreme observations or points that do not fit with the rest of the point cloud. -->\n\n<!-- We notice a moderate, positive (that is, increasing) linear relationship between height and handspan. -->\n\n<!-- Recall @fig-squares-scatterplot, displaying the relationship between side and perimeters of squares. -->\n<!-- In the plot we notice two points on top of each other, reflecting the fact that two squares having the same side will always have the same perimeter. -->\n<!-- In fact, the data from the Scottish National Gallery include two squared paintings with a side of 1.1m, both having a measured perimeter of 4.4m. -->\n\n<!-- fig-handheight-scatterplot, instead, displays the relationship between height and handspan of a sample of students. The first thing that grabs our attention is the fact that students having the same height do not necessarily have the same handspan. Rather, we clearly see a variety of handspan values for students all having a height of, for example, 70in. To be more precise, the seven students who are 70 in. tall all have differing handspans. -->\n<!-- \n\n</div><p class=\"solution-end\"></p>\n\n -->\n\n<!-- \n\n<div class='question-begin'>Optional Extra 4</div><div class='question-body'>\n\n -->\n<!-- Hopefully, as part of the previous question, you created a scatterplot of handspans against heights. If not, make one now.   -->\n\n<!-- Try adding the following line of code to the scatterplot. It will add a best-fit line describing how handspan varies as a function of height. -->\n<!-- For the moment, the argument `se = FALSE` tells R to not display uncertainty bands. -->\n<!-- ```{r} -->\n<!-- #| eval: false -->\n<!-- geom_smooth(method = lm, se = FALSE) -->\n<!-- ``` -->\n\n<!-- Think about the differences you notice with between this and the figure you made showing the side-lengths and perimeters of paintings.   -->\n<!-- \n\n</div><p class=\"question-end\"></p>\n\n -->\n<!-- \n\n<div style=\"display:none;\">\n\n -->\n<!-- ```{r} -->\n<!-- #| label: fig-handheight-fitted-model -->\n<!-- #| fig-cap: 'The best-fit line.' -->\n<!-- ggplot(handheight, aes(x = height, y = handspan)) + -->\n<!--   geom_point(size = 3, alpha = 0.5) + -->\n<!--   geom_smooth(method = lm, se = FALSE) + -->\n<!--   labs(x = 'Height (in.)', y = 'Handspan (cm)') -->\n<!-- ``` -->\n\n<!-- The line representing the relationship between side and perimeter of squares (@fig-squares-scatterplot) is able to predict the actual perimeter value from the measurement of the side of a square. This is possible because the relationship between side and perimeter is an **exact** one. That is, any squares having the same side will have the same perimeter, and there will be no variation in those values. -->\n\n<!-- The line that best fits the relationship between height and handspan (@fig-handheight-fitted-model) is only able to predict the **average** handspan for a given value of height. This is because there will be a distribution of handspans at each value of height. The line will fit the trend/pattern in the values, but there will be individual-to-individual variability that we must accept around that average pattern. -->\n<!-- \n\n</div><p class=\"solution-end\"></p>\n\n -->\n\n\n<!-- :::statbox -->\n<!-- Relationships such as that between height and handspan show deviations from an \"average pattern\". To model this, we need need to create a model that allows for deviations from the linear relationship. This is called a _statistical_ model.   -->\n\n<!-- A statistical model includes **both** a deterministic function and a random error term: -->\n<!-- $$ -->\n<!-- Handspan = \\beta_0 + \\beta_1 \\ Height + \\epsilon -->\n<!-- $$ -->\n<!-- or, in short, -->\n<!-- $$ -->\n<!-- y = \\underbrace{\\beta_0 + \\beta_1 \\ x}_{f(x)} + \\underbrace{\\epsilon}_{\\text{random error}} -->\n<!-- $$ -->\n\n<!-- The deterministic function $f(x)$ need not be linear if the scatterplot displays signs of nonlinearity, but in this course we focus primarily on linear relationships.    -->\n\n<!-- In the equation above, the terms $\\beta_0$ and $\\beta_1$ are numbers specifying where the line going through the data meets the y-axis and its slope (rate of increase/decrease).  -->\n<!-- ::: -->\n\n<!-- \n\n<div class='question-begin'>Optional Extra 5</div><div class='question-body'>\n\n -->\n<!-- ```{r eval=FALSE, echo=FALSE} -->\n<!-- mdl <- lm(handspan ~ 1 + height, data = handheight) -->\n<!-- equatiomatic::extract_eq(mdl, ital_vars = TRUE, use_coefs = TRUE) -->\n<!-- ``` -->\n<!-- The line of best-fit is given by:^[Yes, the error term is gone. This is because the line of best-fit gives you the prediction of the average handspan for a given height, and not the individual handspan of a person, which will almost surely be different from the prediction of the line.] -->\n<!-- $$ -->\n<!-- \\widehat{Handspan} = -3 + 0.35 \\ Height -->\n<!-- $$ -->\n\n<!-- What is your best guess for the handspan of a student who is 73in tall? -->\n\n<!-- And for students who are 5in? -->\n<!-- \n\n</div><p class=\"question-end\"></p>\n\n -->\n<!-- \n\n<div style=\"display:none;\">\n\n -->\n<!-- The predicted average handspan for students who are 73in tall is $-3 + 0.35 * 73 = 22.55$cm. -->\n\n<!-- The predicted average handspan for students who are 5in tall is $-3 + 0.35 * 5 = -1.25$cm.  -->\n<!-- But wait, handspan can not be negative... This does not make any sense! -->\n<!-- That's right, we went too far off the range of the available data on heights, which were between 57in and 78in. We extrapolated. This is very dangerous... -->\n\n<!-- ```{r} -->\n<!-- #| label: fig-xkcd2 -->\n<!-- #| echo: false -->\n<!-- #| fig.cap: 'Source: Randall Munroe, xkcd.com' -->\n<!-- knitr::include_graphics('https://imgs.xkcd.com/comics/extrapolating.png') -->\n<!-- ``` -->\n<!-- \n\n</div><p class=\"solution-end\"></p>\n\n -->\n\n\n# Simple Linear Regression\n\n\n\n\n\n\n\n\n\n\n\n\n## Monkey Exploration \n\n:::frame\n__Data: monkeyexplorers.csv__  \n\nArcher, Winther & Gandolfi (2024)^[Not a real study!] have conducted a study on monkeys! They were interested in whether younger monkeys tend to be more inquisitive about new things than older monkeys do. They sampled 108 monkeys ranging from 1 to 24 years old. Each monkey was given a novel object, the researchers recorded the time (in minutes) that each monkey spent exploring the object. \n\nFor this week, we're going to be investigating the research question:  \n\n> Do older monkeys spend more/less time exploring novel objects?  \n\nThe data is available at [https://uoepsy.github.io/data/monkeyexplorers.csv](https://uoepsy.github.io/data/monkeyexplorers.csv){target=\"_blank\"} and contains the variables described in @tbl-monkeydicts\n\n\n\n::: {#tbl-monkeydicts .cell layout-align=\"center\" tbl-cap='Data dictionary for monkeyexplorers.csv'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"cntxcbbvle\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#cntxcbbvle table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#cntxcbbvle thead, #cntxcbbvle tbody, #cntxcbbvle tfoot, #cntxcbbvle tr, #cntxcbbvle td, #cntxcbbvle th {\n  border-style: none;\n}\n\n#cntxcbbvle p {\n  margin: 0;\n  padding: 0;\n}\n\n#cntxcbbvle .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#cntxcbbvle .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#cntxcbbvle .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#cntxcbbvle .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#cntxcbbvle .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#cntxcbbvle .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#cntxcbbvle .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#cntxcbbvle .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#cntxcbbvle .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#cntxcbbvle .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#cntxcbbvle .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#cntxcbbvle .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#cntxcbbvle .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#cntxcbbvle .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#cntxcbbvle .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cntxcbbvle .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#cntxcbbvle .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#cntxcbbvle .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#cntxcbbvle .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cntxcbbvle .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#cntxcbbvle .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cntxcbbvle .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#cntxcbbvle .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cntxcbbvle .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cntxcbbvle .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cntxcbbvle .gt_left {\n  text-align: left;\n}\n\n#cntxcbbvle .gt_center {\n  text-align: center;\n}\n\n#cntxcbbvle .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#cntxcbbvle .gt_font_normal {\n  font-weight: normal;\n}\n\n#cntxcbbvle .gt_font_bold {\n  font-weight: bold;\n}\n\n#cntxcbbvle .gt_font_italic {\n  font-style: italic;\n}\n\n#cntxcbbvle .gt_super {\n  font-size: 65%;\n}\n\n#cntxcbbvle .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#cntxcbbvle .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#cntxcbbvle .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#cntxcbbvle .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#cntxcbbvle .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#cntxcbbvle .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#cntxcbbvle .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#cntxcbbvle .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#cntxcbbvle div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Monkey Name</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age of monkey in years</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">exploration_time</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Time (in minutes) spent exploring the object</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n:::\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n  \nFor this week, we're going to be investigating the following research question:  \n\n> Do older monkeys spend more/less time exploring novel objects?  \n\nRead in the data to your R session, then visualise and describe the *marginal distributions* of those variables which are of interest to us. These are the distribution of each variable (time spent exploring, and monkey age) *without* reference to the values of the other variables.\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- You could use, for example, `geom_density()` for a density plot or `geom_histogram()` for a histogram.\n- Look at the shape, center and spread of the distribution. Is it symmetric or skewed? Is it unimodal or bimodal? \n- Do you notice any extreme observations?\n\n:::\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonkeyexp <- read_csv(\"https://uoepsy.github.io/data/monkeyexplorers.csv\")\nhead(monkeyexp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  name            age exploration_time\n  <chr>         <dbl>            <dbl>\n1 Ed Sheeran        8             13.1\n2 Vince Gill       17              6.8\n3 Jewel            13             12.8\n4 Jaden Smith      18              8.9\n5 Reba McEntire    16              1.1\n6 Metallica        13              5.7\n```\n\n\n:::\n:::\n\n\n\n\n\nWe can plot the marginal distribution of these two continuous variables as density curves, and add a boxplot underneath to check for the presence of outliers. The `width` of the geom_boxplot() is always quite wide, so I want to make it narrower so that we can see it at the same time as the density plot. Deciding on the exact value for the width here is just trial and error:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(patchwork)\n# the patchwork library allows us to combine plots together\nggplot(data = monkeyexp, aes(x = age)) +\n  geom_density() +\n  geom_boxplot(width = 1/300) +\n  labs(x = \"Age (in years)\", \n       y = \"Probability density\") +\n\nggplot(data = monkeyexp, aes(x = exploration_time)) +\n  geom_density() +\n  geom_boxplot(width = 1/175) +\n  labs(x = \"Time spent exploring a\\n novel object (in minutes)\", \n       y = \"Probability density\")\n```\n\n::: {.cell-output-display}\n![Density plot and boxplot of monkey's age and their time spent exploring novel objects](05_ex_files/figure-html/fig-agetimeplot-1.png){#fig-agetimeplot fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nThe plots suggests that the distributions of monkeys' ages and the time they spend exploring novel objects are both unimodal. Most of the monkeys are between roughly 8 and 18 years old, and most of them spent between 7 and 12 minutes exploring the objects. The boxplots suggest an outlier in the distribution of exploration-times, with one monkeys spending more than $1.5 \\times IQR$ beyond the 3rd quartile.  \n\nTo further summarize a distribution, it is typical to compute and report numerical summary statistics such as the mean and standard deviation.  \n\nAs we have seen, in earlier weeks, one way to compute these values is to use the `summarise()/summarize()` function from the `tidyverse` library:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonkeyexp |> \n  summarize(\n    mean_age = mean(age), \n    sd_age = sd(age),\n    mean_exptime = mean(exploration_time),\n    sd_exptime = sd(exploration_time)\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  mean_age sd_age mean_exptime sd_exptime\n     <dbl>  <dbl>        <dbl>      <dbl>\n1     13.5   5.92         9.40       4.50\n```\n\n\n:::\n:::\n\n\n\n\n:::int\nThe marginal distribution of age is unimodal with a mean of 13.5 years, and a standard deviation of 5.9.  \nThe marginal distribution of time-spent-exploring is unimodal with a mean\nof 9.4 years, and a standard deviation of 4.5.   \n:::\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n  \nAfter we've looked at the marginal distributions of the variables of interest in the analysis, we typically move on to examining *relationships* between the variables.  \n  \nVisualise and describe the relationship between age and exploration-time among the monkeys in the sample.  \n\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\nThink about:  \n\n- *Direction* of association\n- *Form* of association (can it be summarised well with a straight line?)  \n- *Strength* of association (how closely do points fall to a recognizable pattern such as a line?)\n- *Unusual observations* that do not fit the pattern of the rest of the observations and which are worth examining in more detail.  \n:::\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\nBecause we are investigating how time-spent-exploring varies with monkeys' ages, the exploration-time here is the dependent variable (on the y-axis), and age is the independent variable (on the x-axis).\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = monkeyexp, aes(x = age, y = exploration_time)) +\n  geom_point(alpha = 0.5) +\n  labs(x = \"Age (in years)\", \n       y = \"Time spent exploring a\\n novel object (in minutes)\")\n```\n\n::: {.cell-output-display}\n![The relationship between monkeys' age and time-spent-exploring.](05_ex_files/figure-html/fig-monkeyage-scatterplot-1.png){#fig-monkeyage-scatterplot fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nThere appears to be a moderate negative linear relationship between age and exploration time in these monkeys. Older monkeys appear to spend less time, on average, exploring a novel object. The scatterplot does highlight that there is one one young monkey who is behaving a bit weirdly, and spent quite a long time exploring the object!  \n\nTo comment numerically on the strength of the linear association we might compute the correlation coefficient that we were introduced to in [5A: Covariance & Correlation](05a_covcor.html)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonkeyexp |>\n  select(age, exploration_time) |>\n  cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        age exploration_time\nage               1.0000000       -0.2885495\nexploration_time -0.2885495        1.0000000\n```\n\n\n:::\n:::\n\n\n\n\nthat is, $r_{\\text{age, exploration-time}} = -0.29$\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\nUsing the `lm()` function, fit a linear model to the sample data, in which time that monkeys spend exploring novel objects is explained by age. Assign it to a name to store it in your environment.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\nYou can see how to fit linear models in R using `lm()` in [5B #fitting-linear-models-in-r](05b_slr.html#fitting-linear-models-in-r){target=\"_blank\"}\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\nAs the variables are in the `monkeyexp` dataframe, we would write:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel1 <- lm(exploration_time ~ 1 + age, data = monkeyexp)\n```\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\nInterpret the estimated intercept and slope in the context of the question of interest.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\nWe saw how to extract lots of information on our model using `summary()` (see [5B #model-summary](05b_slr.html#model-summary){target=\"_blank\"}), but there are lots of other functions too.  \n\nIf we called our linear model object \"model1\" in the environment, then we can use:  \n\n- type `model1`, i.e. simply invoke the name of the fitted model;\n- type `model1$coefficients`;\n- use the `coef(model1)` function;\n- use the `coefficients(model1)` function;\n- use the `summary(model1)$coefficients` to extract just that part of the summary.\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         age \n   12.36253    -0.21897 \n```\n\n\n:::\n:::\n\n\n\nFrom this, we get that the fitted line is:\n$$\n\\widehat{\\text{ExplorationTime}} = 12.36 - 0.22 \\cdot \\text{Age} \\\\\n$$\n\nWe can interpret the estimated intercept as:\n\n:::int\nThe estimated average time spent exploring novel objects for a monkey of age zero is 12.36 minutes.\n:::\n\nFor the estimated slope we get:\n\n:::int\nA one year increase in age is associated with an estimated decrease of -0.22 minutes (or -13 seconds) that a monkey will spend exploring a novel object.  \n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\nTest the hypothesis that the population slope is zero --- that is, that there is no linear association between exploration time and age in the population.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\nYou don't need to *do* anything for this, you can find all the necessary information in `summary()` of your model.  \nSee [5B #inference-for-regression-coefficients](05b_slr.html#inference-for-regression-coefficients){target=\"_blank\"}.\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\nThe information is already contained in the row corresponding to the variable \"age\" in the output of `summary()`, which reports the t-statistic under `t value` and the p-value under `Pr(>|t|)`:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = exploration_time ~ 1 + age, data = monkeyexp)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.3056  -2.3461   0.3841   2.1936  21.8323 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 12.36253    1.04263  11.857  < 2e-16 ***\nage         -0.21897    0.07057  -3.103  0.00246 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.324 on 106 degrees of freedom\nMultiple R-squared:  0.08326,\tAdjusted R-squared:  0.07461 \nF-statistic: 9.627 on 1 and 106 DF,  p-value: 0.002458\n```\n\n\n:::\n:::\n\n\n\n\nRecall that very small p-values such as the one for the intercept `2e-16` in the `Pr(>|t|)` column simply means $2 \\times 10^{-16}$, or 0.0000000000000002. Conventions such as the APA guidelines give rules on how to report these numbers (see, e.g. [APA's number and stats guide](https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf){target=\"_blank\"}). For the p-values in this summary (the one for the intercept and the one for the slope) we could report them as \"<.001\" and \"0.003\" respectively.  \n\n:::int\nA significant association was found between age (in years) and time spent exploring novel objects, with exploration time decreasing on average by -0.22 minutes (or -13 seconds) for every additional year of age ($b = -0.22$, $SE = 0.071$, $t(106)=-3.103$, $p=.003$). \n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<!-- \n\n<div class='question-begin'>Question 11</div><div class='question-body'>\n\n -->\n<!-- What is the proportion of the total variability in exploration-times explained by the linear relationship with monkeys' ages? -->\n\n<!-- ::: {.callout-tip collapse=\"true\"} -->\n<!-- #### Hints -->\n\n<!-- - The question asks to compute the value of $R^2$, but you might be able to find it already computed somewhere (so much stuff is already in `summary()` of the model. -->\n<!-- - See [5B #r2](05b_slr.html#r2){target=\"_blank\"} if you're unsure about what $R^2$ is.     -->\n\n<!-- ::: -->\n\n<!-- \n\n</div><p class=\"question-end\"></p>\n\n -->\n<!-- \n\n<div style=\"display:none;\">\n\n -->\n<!-- For the moment, ignore \"Adjusted R-squared\". We will come back to this later on.  -->\n<!-- ```{r} -->\n<!-- summary(model1) -->\n<!-- ``` -->\n\n<!-- :::int -->\n<!-- Approximately 17\\% of the total variability in time spend exploring novel objects is explained by the linear association with age. -->\n<!-- ::: -->\n\n<!-- \n\n</div><p class=\"solution-end\"></p>\n\n -->\n\n<!-- \n\n<div class='question-begin'>Question 12</div><div class='question-body'>\n\n -->\n<!-- Look at the output of `summary()` of your model. Identify the relevant information to conduct an F-test against the null hypothesis that the model is ineffective at predicting exploration time using age.   -->\n\n<!-- ::: {.callout-tip collapse=\"true\"} -->\n<!-- #### Hints -->\n<!-- [5B #the-f-statistic](05b_slr.html#the-f-statistic){target=\"_blank\"} will help.   -->\n<!-- ::: -->\n\n<!-- \n\n</div><p class=\"question-end\"></p>\n\n -->\n<!-- \n\n<div style=\"display:none;\">\n\n -->\n<!-- ```{r} -->\n<!-- summary(model1) -->\n<!-- ``` -->\n\n<!-- From the `summary(model1`), the relevant row is just below the $R^2$, where it states:  -->\n\n<!-- ``` -->\n<!-- F-statistic: 21.59 on 1 and 106 DF,  p-value: 9.755e-06 -->\n<!-- ``` -->\n\n<!-- :::int -->\n<!-- The overall test of model utility was significant $F(1, 106) = 21.59, p < .001$, indicating evidence against the null hypothesis that the model is ineffective (that age is not a useful predictor of time spent exploring novel objects).  -->\n<!-- ::: -->\n\n<!-- \n\n</div><p class=\"solution-end\"></p>\n\n -->\n\n\n\n\n<div class='question-begin'>Question 13</div><div class='question-body'>\n\n\nCreate a visualisation of the estimated association between age and exploration time.   \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\nFor our simple regression model, there is a really easy way to do this with `geom_smooth()`.  Check [5B #example](05b_slr.html#example){target=\"_blank\"}, which shows an example.\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = monkeyexp, aes(x = age, y = exploration_time)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method=lm) +\n  labs(x = \"Age (in years)\", \n       y = \"Time spent exploring a\\n novel object (in minutes)\")\n```\n\n::: {.cell-output-display}\n![](05_ex_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 14 - Optional</div><div class='question-body'>\n\n\nConsider the following:  \n\n1. In fitting a linear regression model, we make the assumption that the errors around the line are normally distributed around zero (this is the $\\epsilon \\sim N(0, \\sigma)$ bit.)  \n2. About 95\\% of values from a normal distribution fall within two standard deviations of the centre.  \n\nWe can obtain the estimated standard deviation of the errors ($\\hat \\sigma$) from the fitted model using `sigma()` and giving it the name of our model.  \nWhat does this tell us?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\nSee [5B #the-error](05b_slr.html#the-error){target=\"_blank\"}.\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\nThe estimated standard deviation of the errors can be obtained by:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.324399\n```\n\n\n:::\n:::\n\n\n\n\nFor any particular age, the time monkeys spend exploring novel objects is estimated as being distributed above and below the regression line with a standard deviation of $\\hat \\sigma = 4.32$. \nSince $1.96 \\hat \\sigma = 1.96 \\times 4.32 = \\text{approx} 8.6$, we would expect most (about 95\\%) of the monkeys' exploration times to be within about 8.6 minutes from the regression line.\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 15 - Optional</div><div class='question-body'>\n\n\nCompute the model-predicted exploration-time for a monkey that is 1 year old.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\nGiven that you know the intercept and slope, you can calculate this algebraically. However, try to also use the `predict()` function (see [5B #model-predictions](05b_slr.html#model-predictions){target=\"_blank}). \n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\nUsing `predict()`, we need to give it our model, plus some new data which contains a monkey that has `1` in the `age` column.  First we make a new dataframe with an age variable, with one entry which has the value 1, and then we give that to `predict()`:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nage_query <- data.frame(age = c(1))\npredict(model1, newdata = age_query)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n12.14356 \n```\n\n\n:::\n:::\n\n\n\n\nGiven that our fitted model takes the form: \n\n$$\n\\widehat{\\text{ExplorationTime}} = 12.36 - 0.22 \\cdot \\text{Age}\n$$\n\nWe are asking what the predicted exploration time is for a monkey with 1 year of age. So we can substitute in \"1\" for the Age variable:\n$$\n\\begin{align}\n\\text{ExplorationTime} &= 12.36 - 0.22 \\cdot \\text{Age} \\\\\n\\text{ExplorationTime} &= 12.36 - 0.22 \\cdot 1 \\\\\n\\text{ExplorationTime} &= 12.36 - 0.22\\\\\n\\text{ExplorationTime} &= 12.14\\\\\n\\end{align}\n$$\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n### Influential Monkeys\n\n\n\n\n<div class='question-begin'>Question 16</div><div class='question-body'>\n\n\nTake a look at the assumption plots (see [5B #assumptions](05b_slr.html#assumptions){target=\"_blank\"}) for your model.  \n    \n- The trick to looking at assumption plots in linear regression is to look for \"things that don't look random\". \n- As well as looking for patterns, these plots can also higlight individual datapoints that might be skewing the results. Can you figure out if there are any unusual monkeys in our dataset? Can you re-fit the model without that monkey? When you do so, do your conclusions change?  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(model1)\n```\n\n::: {.cell-output-display}\n![](05_ex_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nFrom these plots, we can see that the 57th observation is looking a bit influential. It is the one datapoint that is looking weird in all of the plots.    \nLet's look at them:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonkeyexp[57, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  name       age exploration_time\n  <chr>    <dbl>            <dbl>\n1 Lil Fizz     5             33.1\n```\n\n\n:::\n:::\n\n\n\n\nThis is a young monkey (5 years old) called \"Lil Fizz\", who seems to have spent quite a long time exploring the toy. It's important to remember that this monkey is a valuable datapoint, despite being a bit different from the general pattern.  \n\nHowever, it would be nice to know how much Lil Fizz is affecting our conclusions, so let's re-fit the model on everybody except that one monkey \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel1a <- lm(exploration_time ~ age, data = monkeyexp[-57, ])\nsummary(model1a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = exploration_time ~ age, data = monkeyexp[-57, ])\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-10.558  -2.321   0.427   2.386   9.884 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 11.46135    0.92155  12.437  < 2e-16 ***\nage         -0.16781    0.06212  -2.701  0.00805 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.769 on 105 degrees of freedom\nMultiple R-squared:  0.06498,\tAdjusted R-squared:  0.05608 \nF-statistic: 7.297 on 1 and 105 DF,  p-value: 0.008053\n```\n\n\n:::\n:::\n\n\n\n\nOur conclusions haven't changed - we still have a significant association.  \n\nWhat we have just done is called a \"sensitivity analysis\" - we've asked if our analyses are sensitive to a specific decision we could make (whether or not we include/exclude this monkey).  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(monkeyexp, aes(x=age,y=exploration_time))+\n  geom_point()+\n  geom_smooth(method=lm, fullrange=TRUE)+\n  ylim(0,34) + \n  labs(title=\"With monkey 57\") +\n\nggplot(monkeyexp[-57,], aes(x=age,y=exploration_time))+\n  geom_point()+\n  geom_smooth(method=lm, fullrange=TRUE)+\n  ylim(0,34) + \n  labs(title=\"Without monkey 57\")\n```\n\n::: {.cell-output-display}\n![](05_ex_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nWe now have a decision to make. Do we continue with the monkey removed, or do we keep them in? There's not really a right answer here, but it's worth noting a practical issue - our assumption plots look considerably better for our model without this monkey.  \n\nWhatever we do, when writing up the analysis we need to mention clearly _if_ and _why_ we exclude any observations, and _how_ that decision has/hasn't influenced our conclusions. \n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n\n\n\n### Monkey Exploration in Adulthood\n\nLet's suppose instead of having measured monkeys' ages in years, researchers simply recorded whether each monkey was an adult or a juvenile (species like Capuchins and Rhesus Macaques reach adulthood at about 8 years old).  \nThe code below creates a this new variable for us:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonkeyexp <- monkeyexp |> \n  mutate(\n    isAdult = ifelse(age >= 8, \"yes\",\"no\")\n  )\n```\n:::\n\n\n\n\n\n\n<div class='question-begin'>Question 17</div><div class='question-body'>\n\n\n\nFit the following model, and interpret the coefficients.  \n\n$$\n\\text{ExplorationTime} = b_0 + b_1 \\cdot \\text{isAdult} + \\varepsilon\n$$\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\nFor help interpreting the coefficients, see [5B #binary-predictors](05b_slr.html#binary-predictors){target=\"_blank\"}.  \n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel2 <- lm(exploration_time ~ 1 + isAdult, data = monkeyexp)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = exploration_time ~ 1 + isAdult, data = monkeyexp)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.2556  -2.3694  -0.0444   2.5556  21.4444 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   11.656      1.037  11.239   <2e-16 ***\nisAdultyes    -2.711      1.136  -2.386   0.0188 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.4 on 106 degrees of freedom\nMultiple R-squared:  0.05099,\tAdjusted R-squared:  0.04204 \nF-statistic: 5.695 on 1 and 106 DF,  p-value: 0.01878\n```\n\n\n:::\n:::\n\n\n\n- `(Intercept)` = the estimated exploration time of juvenile monkeys (11.7 minutes)\n- `isAdultyes` = the estimated change in exploration time from juvenile monkeys to adult monkeys (-2.7 minutes)  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(monkeyexp, aes(x = isAdult, y = exploration_time)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](05_ex_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 18</div><div class='question-body'>\n\n\nWe've actually already seen a way to analyse questions of this sort (\"is the average exploration-time different between juveniles and adults?\")  \n\nRun the following t-test, and consider the statistic, p value etc. How does it compare to the model in the previous question?  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(exploration_time ~ isAdult, data = monkeyexp, var.equal = TRUE)\n```\n:::\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(exploration_time ~ isAdult, data = monkeyexp, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  exploration_time by isAdult\nt = 2.3865, df = 106, p-value = 0.01878\nalternative hypothesis: true difference in means between group no and group yes is not equal to 0\n95 percent confidence interval:\n 0.4588049 4.9634174\nsample estimates:\n mean in group no mean in group yes \n        11.655556          8.944444 \n```\n\n\n:::\n:::\n\n\n\n\nIt is identical! the $t$-statistics are the same, the p-values are the same, the degrees of freedom. Everything!  \n\nThe two sample t-test is actually just a special case of the linear model, where we have a numeric outcome variable and a binary predictor! \n\n__And...__ the one-sample t-test is the linear model without any predictors, so just with an intercept.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(monkeyexp$exploration_time, mu = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  monkeyexp$exploration_time\nt = 21.722, df = 107, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n  8.538785 10.253807\nsample estimates:\nmean of x \n 9.396296 \n```\n\n\n:::\n\n```{.r .cell-code}\ninterceptonly_model <- lm(exploration_time ~ 1, data = monkeyexp)\n\nsummary(interceptonly_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error  t value     Pr(>|t|)\n(Intercept) 9.396296  0.4325657 21.72224 5.060938e-41\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Extra! A team task!   \n\n\n\n<div class='question-begin'>EXTRA!</div><div class='question-body'>\n\n\n\nThe data from this year's survey that you filled out in the first couple of weeks is available at [https://uoepsy.github.io/data/usmr2024.csv](https://uoepsy.github.io/data/usmr2024.csv).  \n\n- **Step 1:** Using the USMR 2024 survey data, make *either* the prettiest plot you can or the ugliest plot you can . \n- **Step 2:** Submit your plot! Go to [https://forms.office.com/e/KiGevk6xH3](https://forms.office.com/e/KiGevk6xH3){target=\"_blank\"} and upload your plot and the code used to create it (save the plot via the plot window in R/take a screenshot/put it in a .Rmd and knit/whatever gets the picture uploaded!)   \n\nAll plots submitted by end-of-day on 25th October will be rated by a number of non-USMR staff, and prizes made of chocolate will be awarded to the team with the prettiest plot and to the team with the ugliest plot. \n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"tocify-extend-page\" data-unique=\"tocify-extend-page\" style=\"height: 0;\"></div>\n",
    "supporting": [
      "05_ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}