<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - 3B: Practical Inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('jk-circle-right')) {
    f.classList.add('jk-circle-down')
    f.classList.remove('jk-circle-right')
} else {
    f.classList.add('jk-circle-right')
    f.classList.remove('jk-circle-down')
}
}
</script>

<!---<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>-->
<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03a_inference.html">Week 3</a></li><li class="breadcrumb-item"><a href="./03b_inference2.html">3B: Practical Inference</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">USMR</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Week 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01a_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1A: A first look at R &amp; RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01b_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1B: More R - Basic Data Skills</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Intro R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Week 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A: Measurement &amp; Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B: Curves &amp; Sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Week 3</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3A: Foundations of Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b_inference2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">3B: Practical Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: T-tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Week 4</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04a_chisq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4A: Chi-Square Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b_revisitnhst.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4B: Revisiting NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Chi-Square Tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Week 5</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05a_covcor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5A: Covariance and Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5B: Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Covariance, Correlation &amp; Linear Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Week 6</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_wt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">WalkThrough: Advanced Data Wrangling</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">Week 7</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07a_mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7A: Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07b_assumptdiag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Multiple Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
 <span class="menu-text">Week 8</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08a_scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8A: Centering and Scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08b_catpred.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8B: Categorical Predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Scaling | Categorical Predictors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Week 9</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Week 10</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Week 11</span></span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#t---distributions" id="toc-t---distributions" class="nav-link active" data-scroll-target="#t---distributions"><span class="math inline">\(t\)</span> - distributions</a></li>
  <li><a href="#t--test-demonstration" id="toc-t--test-demonstration" class="nav-link" data-scroll-target="#t--test-demonstration"><span class="math inline">\(t\)</span> -test demonstration</a></li>
  <li><a href="#make-life-easier-with-r" id="toc-make-life-easier-with-r" class="nav-link" data-scroll-target="#make-life-easier-with-r">Make life easier with R</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  <li><a href="#basic-tests" id="toc-basic-tests" class="nav-link" data-scroll-target="#basic-tests">Basic Tests</a>
  <ul class="collapse">
  <li><a href="#one-sample-t-test" id="toc-one-sample-t-test" class="nav-link" data-scroll-target="#one-sample-t-test">One sample t-test</a></li>
  <li><a href="#two-sample-t-test" id="toc-two-sample-t-test" class="nav-link" data-scroll-target="#two-sample-t-test">Two sample t-test</a></li>
  <li><a href="#paired-sample-t-test" id="toc-paired-sample-t-test" class="nav-link" data-scroll-target="#paired-sample-t-test">Paired sample t-test</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">3B: Practical Inference</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="lo">
<p>This reading:</p>
<ul>
<li>How does hypothesis testing work in practice?<br>
</li>
<li>How do we do all this in R?
<ul>
<li><em>spoiler: it’s easier than you think</em></li>
</ul></li>
<li>What are some basic hypothesis tests that we can conduct?
<ul>
<li>Tests of a single continuous variable</li>
<li>Tests of the relationship between a continuous variable and a binary categorical variable</li>
</ul></li>
</ul>
</div>
<p>In <a href="03a_inference.html" target="_blank">3A</a> we learned about the logic of <em>Null Hypothesis Significance Testing</em> (NHST), allowing us to draw perform inferentials tests about parameters in the <strong>population</strong>, based on statistics computed on the <strong>sample</strong> that we have collected.</p>
<div class="statbox">
<p><strong>NHST Recap</strong></p>
<p>We have a sample (<span class="math inline">\(n=10\)</span>):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>mysample <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">4</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="sc">-</span><span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And a sample mean:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(mysample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.9</code></pre>
</div>
</div>
<p>We’re interested in whether - in the <em>population</em> - the mean of this variable is different from 0. So we are testing between two hypotheses:</p>
<ul>
<li>Null Hypothesis <span class="math inline">\(H_0: \mu = 0\)</span>.<br>
</li>
<li>Alternative Hypothesis <span class="math inline">\(H_1: \mu \neq 0\)</span>.</li>
</ul>
<p>Remember, there are lots of samples of size <span class="math inline">\(n=10\)</span> that we <em>could</em> take, and they all have different means. To quantify the spread of these different means we can use the <strong>standard error</strong>, calculated using <span class="math inline">\(SE = \frac{\sigma}{\sqrt{n}}\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(mysample) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(mysample))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.394035</code></pre>
</div>
</div>
<p>We can use this information to express how far away from the null hypothesis (mean = 0) our observed sample is, in terms of standard errors:</p>
<p><span class="math display">\[
Z \ = \ \frac{\text{estimate}-\text{null}}{SE} \ = \ \frac{1.9 - 0}{1.39} \ = \ 1.36
\]</span> We can then calculate, <strong>if</strong> the mean in the population <em>is</em> 0, what is the probability of obtaining a <span class="math inline">\(Z\)</span>-statistic from a sample of this size at least as extreme as the one we <em>have</em> observed?</p>
<p>The resulting probability is our <strong>p-value:</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pnorm</span>(<span class="fl">1.36</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1738299</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pnorm23" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03b_inference2_files/figure-html/fig-pnorm23-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: 2*pnorm gives the two tails</figcaption>
</figure>
</div>
</div>
</div>
<p>As our <span class="math inline">\(p\)</span>-value is above our threshold of <span class="math inline">\(\alpha=.05\)</span>, we fail to reject the null hypothesis that the mean in the population is zero.</p>
<p>We can get to the same conclusion by constructing a 95% confidence interval:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">=</span> <span class="fu">mean</span>(mysample)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>se <span class="ot">=</span> <span class="fu">sd</span>(mysample) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(mysample))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(xbar <span class="sc">-</span> (<span class="fl">1.96</span> <span class="sc">*</span> se), xbar <span class="sc">+</span> (<span class="fl">1.96</span> <span class="sc">*</span> se))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.8323084  4.6323084</code></pre>
</div>
</div>
<p>As this interval includes zero, then at the 5% level we fail to reject the null hypothesis that the population mean is zero.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</div>
<p>While in practice NHST follows the logic described above, there is something important that we have been sweeping under the carpet.</p>
<p>In our estimation of the <strong>standard error</strong> we have used the formula that includes <span class="math inline">\(\sigma\)</span>, which refers to the <strong>population</strong> standard deviation. However, we never know this value (because we don’t have data for the population), so we have been using the <strong>sample</strong> standard deviation <span class="math inline">\(s\)</span> instead. This is an <em>approximation</em>, and might be okay when we have a very large <span class="math inline">\(n\)</span> (meaning <span class="math inline">\(s\)</span> provides an accurate estimate of <span class="math inline">\(\sigma\)</span>), but in practice this is not always feasible. <span class="math display">\[
SE = \frac{\sigma}{\sqrt{n}} \approx \frac{s}{\sqrt{n}}
\]</span></p>
<div class="divider div-transparent div-dot">

</div>
<section id="t---distributions" class="level1">
<h1><span class="math inline">\(t\)</span> - distributions</h1>
<p>To resolve the issues with the approximation of using <span class="math inline">\(s\)</span> in place of <span class="math inline">\(\sigma\)</span> to compute the standard error, we can move from using the normal distribution to referring to the <span class="math inline">\(t\)</span>-distribution.<br>
The <span class="math inline">\(t\)</span> distribution is very similar to the normal distribution, but it has slightly <em>heavier</em> tails (see <a href="#fig-tnorm">Figure&nbsp;2</a>). <span class="math inline">\(t\)</span>-distributions are always centered on zero, and the precise shape (how heavy the tails are) depends upon a parameter known as the <strong>degrees of freedom.</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-tnorm" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03b_inference2_files/figure-html/fig-tnorm-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Normal distribution (black) vs t-distribution with 3 degrees of freedom (red)</figcaption>
</figure>
</div>
</div>
</div>
<div class="sticky">
<p><strong>Degrees of Freedom - <span class="math inline">\(df\)</span></strong></p>
<p>‘Degrees of freedom’ is a tricky concept. One of the most intuitive ways to understand it is to think of it as the number of independent bits of information that go into calculating an estimate. Put another way, it is the number of datapoints that are <em>free to vary</em>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Degrees of freedom (df)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Suppose we have four unknown numbers (<span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, <span class="math inline">\(c\)</span> and <span class="math inline">\(d\)</span>) which <em>must</em> have a mean of 5.</p>
<p>Do the following, <em>in order:</em></p>
<ol type="1">
<li>Choose a value for <span class="math inline">\(a\)</span>.</li>
<li>Choose a value for <span class="math inline">\(b\)</span>.</li>
<li>Choose a value for <span class="math inline">\(c\)</span>.</li>
<li>Can you choose a value for <span class="math inline">\(d\)</span> while ensuring the mean of the four numbers you have chosen is 5?</li>
</ol>
<p>You are free to choose anything you like for <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span> and <span class="math inline">\(c\)</span>.<br>
But once those are fixed, you have no freedom to choose <span class="math inline">\(d\)</span>.</p>
<p>Example:</p>
<ul>
<li><span class="math inline">\(a\)</span> = 1<br>
</li>
<li><span class="math inline">\(b\)</span> = 2<br>
</li>
<li><span class="math inline">\(c\)</span> = 3</li>
</ul>
<p>We know that <span class="math inline">\(\frac{1+2+3+d}{4} = 5\)</span> So there is only one possible value for <span class="math inline">\(d\)</span>:<br>
<span class="math inline">\(\frac{1+2+3+d}{4} = 5\)</span><br>
<span class="math inline">\(1+2+3+d = 5*4\)</span><br>
<span class="math inline">\(1+2+3+d = 20\)</span><br>
<span class="math inline">\(d = 20-3-2-1\)</span><br>
<span class="math inline">\(d = 14\)</span></p>
</div>
</div>
</div>
</div>
<p>When we estimate the mean from a sample, we use up one of our degrees of freedom, and so our test of a single mean will require us to use a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-1\)</span> degrees of freedom. For <span class="math inline">\(t\)</span>-distributions, as the <span class="math inline">\(df\)</span> increases the distribution becomes closer and closer to a normal distribution (see <a href="#fig-tdf">Figure&nbsp;3</a>) - the use of these <span class="math inline">\(t\)</span>-distributions is exactly what we need in order to account for using <span class="math inline">\(s\)</span> in our calculation of the standard error.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-tdf" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03b_inference2_files/figure-html/fig-tdf-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3: t distributions with various degrees of freedom.</figcaption>
</figure>
</div>
</div>
</div>
<p>To make use of the <span class="math inline">\(t\)</span>-distribution in hypothesis testing, we need to move to performing <span class="math inline">\(t\)</span>-tests!</p>
<p>The logic remains the same as before, but where we previously were relying on the normal distribution:</p>
<ul>
<li><code>pnorm()</code> for our <span class="math inline">\(p\)</span>-values</li>
<li><code>qnorm()</code> in order to calculate our confidence intervals (<code>qnorm(0.975)</code> gives the 1.96 we have been using)</li>
</ul>
<p>We can use <code>pt()</code> and <code>qt()</code> to conduct the same process but in reference to the appropriate <span class="math inline">\(t\)</span>-distribution.</p>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="t--test-demonstration" class="level1">
<h1><span class="math inline">\(t\)</span> -test demonstration</h1>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>mysample <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">4</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="sc">-</span><span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let us then perform a more appropriate test against the null hypothesis that the mean in the population is zero. It is going to look pretty much the same as it did previously, but things like “Z” and “norm” are going to be replaced with “t”.</p>
<p>For example, our test-statistic is now going to be a <span class="math inline">\(t\)</span>-statistic:</p>
<p><span class="math display">\[
\begin{align}
&amp; t =  \frac{\bar x - \mu_0}{\frac{s}{\sqrt{n}}}\\
\ \\
&amp; \text{where:} \\
&amp; \bar x : \text{sample mean} \\
&amp; \mu_0 : \text{hypothesised population mean} \\
&amp; s : \text{sample standard deviation} \\
&amp; n : \text{sample size} \\
\end{align}
\]</span> Which can be calculated as:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(mysample)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sd</span>(mysample) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(mysample))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>tstat <span class="ot">&lt;-</span> (xbar <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> se</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>tstat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.36295</code></pre>
</div>
</div>
<p>While the calculation is just the same as it was previously, we’re calling it a <span class="math inline">\(t\)</span>-statistic because we are going to compare it to a reference <span class="math inline">\(t\)</span>-distribution. As our sample has <span class="math inline">\(n=10\)</span>, and as part of the statistic we are estimating a mean, the relevant <span class="math inline">\(t\)</span>-distribution for us has 9 (<span class="math inline">\(10-1\)</span>) degrees of freedom (we lose one by calculating the mean).</p>
<p>Our p-value can be found with the <code>pt()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(tstat, <span class="at">df =</span> <span class="dv">9</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2060213</code></pre>
</div>
</div>
<p>And our confidence interval can be constructed using: <span class="math display">\[
\text{CI} = \bar{x} \pm t^* \times SE \\
\]</span> Note that <span class="math inline">\(t^*\)</span> has replaced the 1.96 we saw in previous chapters, because we obtained that using the normal distribution. The code <code>qnorm(c(0.025, 0.975))</code> showed us that 95% of <strong>normal distribution</strong> is beyond 1.96 from the mean. But what we actually want to know is where 95% of the <strong><span class="math inline">\(t\)</span>-distribution</strong> with <span class="math inline">\(df=9\)</span> lies:<br>
So instead we can use:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">df =</span> <span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.262157  2.262157</code></pre>
</div>
</div>
<p>And our confidence interval is:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(mysample)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sd</span>(mysample) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(mysample))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>xbar <span class="sc">-</span> (<span class="fl">2.262157</span> <span class="sc">*</span> se)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>xbar <span class="sc">+</span> (<span class="fl">2.262157</span> <span class="sc">*</span> se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.253526</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.053526</code></pre>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="make-life-easier-with-r" class="level1">
<h1>Make life easier with R</h1>
<p>All of the above is crucial for understanding how this all works, but in practice we can avoid all of the rigmarole of ever calculating the standard error or using functions like <code>pt()</code>, <code>qt()</code>. This is where R starts to become far more powerful - there are functions that do all this sort of stuff for us - in just <em>one single line of code!</em></p>
<p>Take a look at the output of the function below. I have given it the sample, and specified that we want it to test against the null hypothesis that <span class="math inline">\(\mu=0\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mysample, <span class="at">mu =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  mysample
t = 1.363, df = 9, p-value = 0.206
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 -1.253526  5.053526
sample estimates:
mean of x 
      1.9 </code></pre>
</div>
</div>
<p>The <code>t.test()</code> function here gives us the <span class="math inline">\(t\)</span>-statistic, the <span class="math inline">\(df\)</span>, the <span class="math inline">\(p\)</span>-value, the 95% CI, the mean <span class="math inline">\(\bar x\)</span>, and it even tells us the alternative hypothesis (that the true mean is <span class="math inline">\(\neq 0\)</span>).</p>
<p>All of these numbers will match those that we calculated above (there may be a small bit of rounding error).</p>
<p>It’s <strong>that</strong> easy!</p>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="assumptions" class="level1">
<h1>Assumptions</h1>
<p>Statistical tests often require us to meet a set of conditions in order for our inferences to be valid. When we perform tests like these that involve estimating a mean, a common requirement is that the deviations from that mean are close to normally distributed. For t-tests, this assumption can be relaxed somewhat in cases where our sample size is larger and there is not too much skew.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="frame">
<p><strong>Assumption Plots</strong></p>
<p>We can evaluate how close to normal a distribution is by visualising it via histograms and density plots and making a judgment call, but this can sometimes be hard:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">mysample =</span> mysample)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data,<span class="fu">aes</span>(<span class="at">x=</span>mysample))<span class="sc">+</span><span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data,<span class="fu">aes</span>(<span class="at">x=</span>mysample))<span class="sc">+</span><span class="fu">geom_density</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-normalquestion" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03b_inference2_files/figure-html/fig-normalquestion-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Am I normal?</figcaption>
</figure>
</div>
</div>
</div>
<p>Another useful visualisation tool is the <strong>QQplot</strong>. The closer to the diagonal line, the closer our data is to being normally distributed:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(data<span class="sc">$</span>mysample) <span class="co"># make the plot</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(data<span class="sc">$</span>mysample) <span class="co"># add the line</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-normalqq" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03b_inference2_files/figure-html/fig-normalqq-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5: A QQplot</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: what are the ’theoretical quantiles?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The theoretical quantiles are the equivalent quantiles of the <em>standard normal distribution</em> (see <a href="02b_sampling.html#the-standard-normal-distribution" target="_blank">#2B standard-normal-distribution</a>).<br>
In the <code>data$mysample</code> example above, we have 10 datapoints. If we cut the standard normal distribution into 10 sections of equal area (see <a href="#fig-qqnormcurve">Figure&nbsp;6</a>), it is the points on the x-axis at the center of each area that we are plotting our data against.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-qqnormcurve" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03b_inference2_files/figure-html/fig-qqnormcurve-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6: 10 quantiles of the normal distribution</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="frame">
<p><strong>Assumption Tests</strong></p>
<p>There are also, if we wish to make use of them, specific hypothesis tests that assess normality, such as the ‘Shapiro-Wilks’ Test. The null hypothesis for this test is that the data we give it are drawn from a normal distribution. This means that <strong>we want a p-value <em>greater</em> than .05</strong>. So in the example below, we have no reason to reject the hypothesis that our data are drawn from a normal distribution. This means we can continue to conduct a t-test.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(mysample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  mysample
W = 0.94722, p-value = 0.6358</code></pre>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="basic-tests" class="level1">
<h1>Basic Tests</h1>
<p>Now that we’ve gone through all the nitty-gritty bits of how hypothesis testing works, the heavy lifting is done.<br>
we’re going to start to look at some of the different basic hypothesis tests that we can perform.</p>
<p>For each test below we show an example conducted the quick way (e.g.&nbsp;<code>t.test()</code> function), and also the manually computations (for those of you who are interested!). We’ve already seen the one sample <span class="math inline">\(t\)</span>-test in the example above, so you might want to skim over that section.</p>
<div class="imp">
<p><strong>something to bear in mind</strong></p>
<p>These tests are the simple hypothesis tests that were developed in the 19th and 20th centuries, and provide a good basis of understanding the <em>null hypothesis significance testing</em> framework.</p>
<p>In the latter half of this course, we move to focus on a modelling based approach for analysing data. We will start to see how many of these simple tests that we are learning now are actually special cases of a more general statistical model.</p>
</div>
<!-- For each test, we'll detail:   -->
<!-- - Purpose -->
<!-- - Hypotheses -->
<!-- - Test statistic -->
<!-- - P-value -->
<!-- - Assumptions -->
<!-- And then we will show an example conducted the quick way (e.g. `t.test()` function), and also the manually computations (for those of you who are interested!).   -->
<!-- We've already seen the one sample $t$-test in the example above, so you might want to skim over that section.   -->
<section id="one-sample-t-test" class="level2">
<h2 class="anchored" data-anchor-id="one-sample-t-test">One sample t-test</h2>
<div class="statbox">
<p><strong>Purpose</strong></p>
<p>The one sample t-test is what we have already seen above. We use it to test whether the mean is different from/greater than/less than some hypothesised value.</p>
<ul>
<li><strong>Examples:</strong>
<ul>
<li>Is the mean age of USMR students different from 20?</li>
<li>Is the mean IQ different from 100?<br>
</li>
<li>Do people read more than 250 words per minute?</li>
</ul></li>
</ul>
<p><strong>Assumptions:</strong></p>
<ul>
<li>The data are continuous (not discrete)</li>
<li>The data are independent (i.e.&nbsp;the value of a datapoint does not depend on the value of another datapoint in any way)</li>
<li>The data are normally distributed (can be relaxed somewhat if the sample size is “large enough” (rule-of-thumb n = 30) and the data are not strongly skewed)</li>
</ul>
</div>
<!-- :::statbox -->
<!-- __Hypotheses__  -->
<!-- Our hypotheses will take one of the combinations below, depending on if we want to perform the test of whether the mean $\mu$ is less than/different from/greater than some hypothesised value $\mu_0$.   -->
<!-- | Null Hypothesis   | Alternative Hypothesis | -->
<!-- | ----------- | ----------- | -->
<!-- | $H_0: \mu = \ \mu_0$  | $H_1: \mu \neq \ \mu_0$ | -->
<!-- | $H_0: \mu \leq \ \mu_0$  | $H_1: \mu > \ \mu_0$ | -->
<!-- | $H_0: \mu \geq \ \mu_0$  | $H_1: \mu < \ \mu_0$ | -->
<!-- ::: -->
<!-- :::statbox -->
<!-- __Test-statistic__  -->
<!-- $$ -->
<!-- \begin{align} -->
<!-- & t =  \frac{\bar x - \mu_0}{\frac{s}{\sqrt{n}}}\\ -->
<!-- \ \\ -->
<!-- & \text{where:} \\  -->
<!-- & \bar x : \text{sample mean} \\ -->
<!-- & \mu_0 : \text{hypothesised population mean} \\ -->
<!-- & s : \text{sample standard deviation} \\ -->
<!-- & n : \text{sample size} \\ -->
<!-- \end{align} -->
<!-- $$ -->
<!-- ::: -->
<!-- :::statbox -->
<!-- __P-value:__  -->
<!-- Our $p$-value will be computed from the $t$-distribution with $n-1$ degrees of freedom.   -->
<!-- If the alternative hypothesis is $H_1: \mu \neq \mu_0$, then we are asking about the probability of a test statistic at least as extreme _in either direction._   -->
<!-- So we would use:   -->
<!-- ```{r} -->
<!-- #| eval: false -->
<!-- # abs() takes the absolute value, ensuring we get the smaller tail -->
<!-- 2 * pt(abs(tstatistic), df = n-1, lower.tail = FALSE) -->
<!-- ``` -->
<!-- If $H_1: \mu > \mu_0$, then this would be  -->
<!-- ```{r} -->
<!-- #| eval: false -->
<!-- pt(tstatistic, df = n-1, lower.tail = FALSE) -->
<!-- ``` -->
<!-- And if $H_1: \mu < \mu_0$:   -->
<!-- ```{r} -->
<!-- #| eval: false -->
<!-- pt(tstatistic, df = n-1, lower.tail = TRUE) -->
<!-- ``` -->
<!-- ::: -->
<!-- :::statbox -->
<!-- __Assumptions:__  -->
<!-- - The data are continuous (not discrete) -->
<!-- - The data are independent (i.e. the value of a datapoint does not depend on the value of another datapoint in any way) -->
<!-- - The data are normally distributed _OR_ the sample size is large enough (rule-of-thumb n = 30) and the data are not strongly skewed -->
<!-- ::: -->
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Research Question &amp; Data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p><strong>Research Question:</strong> Do people read more than 250 words per minute?</p>
</blockquote>
<p>Fifty participants were recruited and tasked with reading a passage of text that was 2000 words long. Their reading times (in words per minute) was recorded, and these are accessible at <a href="https://uoepsy.github.io/data/usmr_tread.csv">https://uoepsy.github.io/data/usmr_tread.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>wpmtime <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_tread.csv"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wpmtime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  id      wpm
  &lt;chr&gt; &lt;dbl&gt;
1 ppt_1   307
2 ppt_2   265
3 ppt_3   205
4 ppt_4   300
5 ppt_5   207
6 ppt_6   300</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Descriptives and Assumptions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Below are some quick descriptives.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(wpmtime<span class="sc">$</span>wpm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 258.36</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(wpmtime<span class="sc">$</span>wpm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32.08646</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(wpmtime<span class="sc">$</span>wpm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03b_inference2_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Our histogram looks roughly normally distributed. We can (if we like), test this using the Shapiro-Wilk test.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(wpmtime<span class="sc">$</span>wpm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  wpmtime$wpm
W = 0.9636, p-value = 0.1258</code></pre>
</div>
</div>
<p>The <span class="math inline">\(p\)</span>-value of 0.126 is <span class="math inline">\(&gt;.05\)</span>, so we fail to reject the null hypothesis that the data come from a normal distribution. In other words, we have no reason to consider our assumption to be violated.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quick and easy <code>t.test()</code>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Paying careful attention to the research question (“Do people read more than 250 words per minute?”), our null hypothesis here is that reading time is <span class="math inline">\(\leq 250\)</span> words per minute (wpm), and our alternative hypothesis is that it is <span class="math inline">\(&gt;250\)</span> wpm.</p>
<p>This means that we will reject our null hypothesis if we get a test statistic indicating the mean is <span class="math inline">\(&gt;250\)</span>. We won’t reject it if the mean is <span class="math inline">\(&lt;250\)</span>.</p>
<p>We specify the direction of the alternative in the <code>t.test()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(wpmtime<span class="sc">$</span>wpm, <span class="at">mu =</span> <span class="dv">250</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  wpmtime$wpm
t = 1.8423, df = 49, p-value = 0.03574
alternative hypothesis: true mean is greater than 250
95 percent confidence interval:
 250.7523      Inf
sample estimates:
mean of x 
   258.36 </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Step-by-step calculations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Our test-statistic is calculated as <span class="math display">\[
t =  \frac{\bar x - \mu_0}{\frac{s}{\sqrt{n}}}
\]</span></p>
<p>There’s a lot of brackets in the code below, so go through it piece by piece if you are unsure of how it matches to the formula above</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">mean</span>(wpmtime<span class="sc">$</span>wpm) <span class="sc">-</span> <span class="dv">250</span> ) <span class="sc">/</span> (<span class="fu">sd</span>(wpmtime<span class="sc">$</span>wpm) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(wpmtime)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.842338</code></pre>
</div>
</div>
<p>The test we are performing is against the null hypothesis that <span class="math inline">\(\mu_0 \leq 250\)</span>. So we will only reject the null hypothesis if we get a test statistic indicating the mean is <span class="math inline">\(&gt;250\)</span>. This means that our p-value will be just the one tail of the <span class="math inline">\(t\)</span>-distribution:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="fl">1.842338</span>, <span class="at">df =</span> <span class="dv">49</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0357404</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Write-up
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="int">
<p>A one-sample t-test was conducted in order to determine if the average reading time was significantly (<span class="math inline">\(\alpha=.05\)</span>) higher than 250 words per minute (wpm).<br>
The sample of 50 participants read on average at 258 words per minute (Mean=258, SD=32). This was significantly above 250 (<span class="math inline">\(t(49)=1.84, p = .036\)</span>, one-tailed).</p>
</div>
</div>
</div>
</div>
</section>
<section id="two-sample-t-test" class="level2">
<h2 class="anchored" data-anchor-id="two-sample-t-test">Two sample t-test</h2>
<div class="statbox">
<p><strong>Purpose</strong><br>
The two sample t-test is used to test whether the mean of one group is different from/greater than/less than the mean of another.</p>
<ul>
<li><strong>Examples:</strong>
<ul>
<li>Is the mean age of cat people different from the mean age of dog people?</li>
<li>Do people who identify as “morning people” have a higher average rating of sleep quality than those who identify as “evening people”?</li>
<li>Is the average reaction time different between people who do and don’t drink caffeinated drinks?</li>
</ul></li>
</ul>
<p><strong>Assumptions:</strong></p>
<ul>
<li>The data are continuous (not discrete)</li>
<li>The data are independent (i.e.&nbsp;the value of a datapoint does not depend on the value of another datapoint in any way)</li>
<li>The data are normally distributed <em>for each group</em> (can be relaxed somewhat if the sample size is “large enough” (rule-of-thumb n = 30) and the data are not strongly skewed)</li>
<li>The variance is equal across groups*.</li>
</ul>
<p>*We can relax this assumption by using an adjusted test called the “Welch <span class="math inline">\(t\)</span>-test”, which calculates the standard error slightly differently, and estimates the degrees of freedom differently too. This is actually the default in R, and we change this easily in R using <code>t.test(...., var.equal = FALSE/TRUE)</code></p>
</div>
<!-- :::statbox -->
<!-- __Hypotheses:__    -->
<!-- Our hypotheses can be stated in terms of 2 population means, $\mu_1$ and $\mu_2$, representing the mean of each group.  -->
<!-- The null hypothesis is typically that the difference between the two means is zero:   -->
<!-- $H_0: \mu_1 - \mu_2 = 0$  -->
<!-- And our alternative hypothesis again can take on the following forms:     -->
<!-- $H_1: \mu_1 - \mu_2 \neq 0$   -->
<!-- $H_1: \mu_1 - \mu_2 > 0$   -->
<!-- $H_1: \mu_1 - \mu_2 < 0$   -->
<!-- ::: -->
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Research Question &amp; Data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p><strong>Research Question:</strong> Is the average reaction time different between people who do and don’t drink caffeinated drinks?</p>
</blockquote>
<p>One hundred participants were recruited and completed a simple reaction time task. They were also surveyed on whether they regularly drank caffeine in any form. The data are accessible at <a href="https://uoepsy.github.io/data/usmr_tcaff.csv">https://uoepsy.github.io/data/usmr_tcaff.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>tcaff <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_tcaff.csv"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tcaff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
     rt caff 
  &lt;dbl&gt; &lt;chr&gt;
1  482. yes  
2  389. yes  
3  484. no   
4  601. no   
5  409. yes  
6  368. no   </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Descriptives and Assumptions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>First some quick descriptive stats. We’ll calculate the mean and standard deviation of reaction times for each group:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>tcaff <span class="sc">|&gt;</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(caff) <span class="sc">|&gt;</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">m =</span> <span class="fu">mean</span>(rt),</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">s =</span> <span class="fu">sd</span>(rt)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  caff      m     s
  &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
1 no     408.  88.9
2 yes    465. 109. </code></pre>
</div>
</div>
<p>And we can make a plot here:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tcaff, <span class="fu">aes</span>(<span class="at">x =</span> rt)) <span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>caff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03b_inference2_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The data look fairly close to normally distributed for each group here. One thing to note is that the variances look like they may be different between the two groups. The caffeine drinkers’ reaction time’s have a standard deviation of 109ms, and the non-caffeine drinkers have an sd of only 89ms.</p>
<p>As before, we can (if we are so inclined) rely on specific tests of these assumptions, such as using <code>shapiro.test()</code> for the distribution <em>in each group separately</em>.</p>
<p>Similarly, the <code>var.test()</code> function performs a test to compare two variances (the null hypothesis of this test being that they are equal). However, it is more common to simply perform the Welch test straight away, and thus not have to worry about this assumption.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quick and easy <code>t.test()</code>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can give R the two sets of data in two ways. Either by extracting the relevant entries:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> tcaff<span class="sc">$</span>rt[tcaff<span class="sc">$</span>caff<span class="sc">==</span><span class="st">"no"</span>], </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> tcaff<span class="sc">$</span>rt[tcaff<span class="sc">$</span>caff<span class="sc">==</span><span class="st">"yes"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Or using the <strong>formula</strong> notation, with the <code>~</code> (“tilde”) symbol. In R, you can interpret <code>y ~ x</code> as “y is modeled as a function of x”. By splitting the numeric values (<code>rt</code> variable) by the categories of the <code>caff</code> variable, we can conduct a <span class="math inline">\(t\)</span>-test using:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(rt <span class="sc">~</span> caff, <span class="at">data =</span> tcaff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  rt by caff
t = -2.8497, df = 93.971, p-value = 0.005377
alternative hypothesis: true difference in means between group no and group yes is not equal to 0
95 percent confidence interval:
 -96.20205 -17.19423
sample estimates:
 mean in group no mean in group yes 
         408.0505          464.7486 </code></pre>
</div>
</div>
<p>Note that the default behaviour of <code>t.test()</code> is to perform the Welch test - so we don’t have to assume equal variances. If we want to override this, we can use <code>t.test(rt ~ caff, data = tcaff, var.equal = TRUE)</code>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Step-by-step calculations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Our test statistic here is:<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a><br>
<span class="math display">\[
\begin{align}
&amp; t =  \frac{\bar x_1 - \bar x_2}{SE}\\
\ \\
&amp; \text{where:} \\
&amp; \bar x_1 : \text{sample mean group 1} \\
&amp; \bar x_2 : \text{sample mean group 2} \\
&amp; SE : \sqrt{\frac{s^2_1}{n_1} + \frac{s^2_2}{n_2}} \\
&amp; s_1 : \text{sample standard deviation of group 1} \\
&amp; s_2 : \text{sample standard deviation of group 2} \\
&amp; n_1 : \text{sample size group 1} \\
&amp; n_2 : \text{sample size group 2} \\
\end{align}
\]</span></p>
<p>We can calculate each part:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>tcaff <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(caff) <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">xbar =</span> <span class="fu">mean</span>(rt),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">s =</span> <span class="fu">sd</span>(rt),</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">s2 =</span> <span class="fu">var</span>(rt),</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  caff   xbar     s     s2     n
  &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;
1 no     408.  88.9  7906.    40
2 yes    465. 109.  11892.    60</code></pre>
</div>
</div>
<p>plugging these bits in gives us: <span class="math display">\[
\begin{align}
SE &amp; = \sqrt{\frac{s^2_1}{n_1} + \frac{s^2_2}{n_2}} = \sqrt{\frac{7906}{40} + \frac{11892}{60}} = \sqrt{395.85} \\
\qquad \\
&amp; = 19.9
\end{align}
\]</span> and <span class="math display">\[
\begin{align}
t &amp; =  \frac{\bar x_1 - \bar x_2}{SE} = \frac{408.1 - 464.8}{19.9} \\
\qquad \\
&amp; = -2.849 \\
\end{align}
\]</span></p>
<p>Our <span class="math inline">\(p\)</span>-value is determined against a <span class="math inline">\(t\)</span>-distribution with a specific number of degrees of freedom. We are estimating two means here, the standard two-sample t-test uses <span class="math inline">\(df = n-2\)</span>. However, the Welch t-test, which we performed quickly with <code>t.test()</code>, where we don’t assume equal variances, makes the calculation of the degrees of freedom much more complicated.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>Using the same degrees of freedom as was used in the quick use of <code>t.test()</code> above, we get out our same p-value (or thereabouts - we have some rounding error):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(<span class="fu">abs</span>(<span class="sc">-</span><span class="fl">2.849</span>), <span class="at">df =</span> <span class="fl">93.971</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.005388563</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Write-up
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="int">
<p>A Welch two sample t-test was used to assess whether the mean reaction time of people who regularly drink caffeine (<span class="math inline">\(n = 60\)</span>) was different to that of people who do not (<span class="math inline">\(n=40\)</span>). There was a significant difference in average reaction time between the caffeine (Mean=465; SD=109) and non-caffeine (Mean=408; SD=89) groups (<span class="math inline">\(t(93.97)=-2.85, p = 0.005\)</span>, two-tailed). Therefore, we reject the null hypothesis that there is no difference in reaction times between caffeine drinkers and non-caffeine drinkers.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tcaff, <span class="fu">aes</span>(<span class="at">x =</span> caff, <span class="at">y =</span> rt)) <span class="sc">+</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"drinks caffeine"</span>,<span class="at">y=</span><span class="st">"reaction time (ms)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03b_inference2_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="paired-sample-t-test" class="level2">
<h2 class="anchored" data-anchor-id="paired-sample-t-test">Paired sample t-test</h2>
<div class="statbox">
<p><strong>Purpose</strong></p>
<p>The paired sample t-test is used to test whether the mean difference between two sets of <em>paired</em> observations is different from 0.</p>
<ul>
<li><strong>Examples:</strong>
<ul>
<li>Is the mean cognitive score of participants at age 60 different from when they are re-tested at age 70?<br>
</li>
<li>Are scores on test 1 different on average from scores on test 2 (with participants completing both tests).</li>
</ul></li>
</ul>
<p><strong>Assumptions:</strong></p>
<ul>
<li>The data are continuous (not discrete)</li>
<li>The <em>differences</em> are independent (i.e.&nbsp;the value of a the difference for one pair does not depend on the values of another pair in any way)</li>
<li>The <em>differences</em> are normally distributed <em>OR</em> the sample size is large enough (rule-of-thumb n = 30) and the data are not strongly skewed</li>
</ul>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Research Question &amp; Data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p><strong>Research Question:</strong> Is the mean cognitive score of participants at age 60 different from when they are re-tested at age 70?</p>
</blockquote>
<p>Addenbrooke’s Cognitive Examination-III (ACE-III) is a brief cognitive test that assesses five cognitive domains: attention, memory, verbal fluency, language and visuospatial abilities. The total score is 100 with higher scores indicating better cognitive functioning. A research project is examining changes in cognitive functioning with age, and administers the ACE-III to a set of participants at age 60, then again at age 70. The data is accessible at <a href="https://uoepsy.github.io/data/usmr_tcaff.csv">https://uoepsy.github.io/data/usmr_tcaff.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>acedata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/acedata.csv"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(acedata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  participant ace_60 ace_70
  &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;
1 sub1            93     85
2 sub2            95     92
3 sub3            93     90
4 sub4            93     95
5 sub5            96     88
6 sub6            91     85</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The paired t test is the one sample t test in disguise
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can either perform this with the data exactly as it is:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> acedata<span class="sc">$</span>ace_60, <span class="at">y =</span> acedata<span class="sc">$</span>ace_70, </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  acedata$ace_60 and acedata$ace_70
t = 2.2542, df = 24, p-value = 0.03359
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 0.2093364 4.7506636
sample estimates:
mean difference 
           2.48 </code></pre>
</div>
</div>
<p>Or we can compute the differences, and perform a one sample test on the mean of those differences being different from 0.<br>
It’s just the same result:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>acedata <span class="ot">&lt;-</span> acedata <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff_score =</span> ace_60 <span class="sc">-</span> ace_70)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(acedata<span class="sc">$</span>diff_score, <span class="at">mu =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  acedata$diff_score
t = 2.2542, df = 24, p-value = 0.03359
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 0.2093364 4.7506636
sample estimates:
mean of x 
     2.48 </code></pre>
</div>
</div>
</div>
</div>
</div>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Remember that confidence intervals provide a range of plausible values for the population mean. In this case, zero is a plausible value.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This is because with smaller samples we have less certainty in the estimate of the population standard deviation, and our estimates of mean and standard deviation are more dependent on one another. The bottom part of <span class="math inline">\(\frac{\bar x - \mu}{SE}\)</span> has a greater chance of being smaller than the top part, meaning that our resulting our test statistics will tend to be slightly bigger. To better represent this greater chance of seeing bigger test statistics from small samples, our <span class="math inline">\(t\)</span>-distributions have heavier tails.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>This is because, practically speaking, what we really <em>need</em> in order to make useful, defensible conclusions, is not that the <em>population</em> itself is normally distributed, but that the <em>sampling distribution of the statistic</em> is close enough to the <span class="math inline">\(t\)</span>-distribution. This can often be the case when we have a large sample without much skew.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The formula here is for the Welch test.<br>
For a standard two sample t-test that assumes equal variances, we first calculate the “pooled standard deviation” - <span class="math inline">\(s_p = \sqrt\frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}\)</span>.<br>
We then use this to calculate the standard error - <span class="math inline">\(SE_{(\bar{x}_1 - \bar{x}_2)} = s_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}\)</span><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>If you <em>really</em> want it, the formula is: <span class="math inline">\(\text{df}=\frac{\left(\dfrac{s_1^2}{n_1}+\dfrac{s_2^2}{n_2}\right)^2}{\dfrac{\left(\dfrac{s_1^2}{n_1}\right)^2}{n_1-1}+\dfrac{\left(\dfrac{s_2^2}{n_2}\right)^2}{n_2-1}}\)</span><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2023 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>