<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - 8B: Categorical Predictors</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('jk-circle-right')) {
    f.classList.add('jk-circle-down')
    f.classList.remove('jk-circle-right')
} else {
    f.classList.add('jk-circle-right')
    f.classList.remove('jk-circle-down')
}
}
</script>

<!---<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>-->
<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08a_scaling.html">Week 8</a></li><li class="breadcrumb-item"><a href="./08b_catpred.html">8B: Categorical Predictors</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">USMR</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Week 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01a_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1A: A first look at R &amp; RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01b_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1B: More R - Basic Data Skills</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Intro R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Week 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A: Measurement &amp; Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B: Curves &amp; Sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Week 3</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3A: Foundations of Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b_inference2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3B: Practical Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: T-tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Week 4</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04a_chisq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4A: Chi-Square Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b_revisitnhst.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4B: Revisiting NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Chi-Square Tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Week 5</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05a_covcor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5A: Covariance and Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5B: Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Covariance, Correlation &amp; Linear Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Week 6</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_wt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">WalkThrough: Advanced Data Wrangling</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">Week 7</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07a_mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7A: Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07b_assumptdiag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Multiple Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text">Week 8</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08a_scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8A: Centering and Scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08b_catpred.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">8B: Categorical Predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Scaling | Categorical Predictors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Week 9</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Week 10</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Week 11</span></span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#binary-predictors" id="toc-binary-predictors" class="nav-link active" data-scroll-target="#binary-predictors">Binary Predictors</a></li>
  <li><a href="#multiple-categories" id="toc-multiple-categories" class="nav-link" data-scroll-target="#multiple-categories">Multiple Categories</a>
  <ul class="collapse">
  <li><a href="#tests" id="toc-tests" class="nav-link" data-scroll-target="#tests">Tests</a></li>
  </ul></li>
  <li><a href="#contrasts" id="toc-contrasts" class="nav-link" data-scroll-target="#contrasts">Contrasts</a>
  <ul class="collapse">
  <li><a href="#treatment-contrasts-the-default" id="toc-treatment-contrasts-the-default" class="nav-link" data-scroll-target="#treatment-contrasts-the-default">Treatment Contrasts (the default)</a></li>
  <li><a href="#sum-contrasts" id="toc-sum-contrasts" class="nav-link" data-scroll-target="#sum-contrasts">Sum Contrasts</a></li>
  <li><a href="#optional-and-many-more.." id="toc-optional-and-many-more.." class="nav-link" data-scroll-target="#optional-and-many-more..">Optional: and many more..</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">8B: Categorical Predictors</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="binary-predictors" class="level1">
<h1>Binary Predictors</h1>
<p>Since we’ve started working with linear regression, we’ve seen a few examples of categorical variables as predictors in linear models, and most (if not all) of these have been binary predictors - i.e.&nbsp;having just <em>two</em> categories (yes/no, dog/cat, phonics/word). We talked initially (<a href="05b_slr.html#binary-predictors" target="_blank">5B#binary-predictors</a>) about how these get entered in the model as 0s and 1s.</p>
<p>Let’s consider a dataset which includes the brain mass and body mass of different primates. Below, we can see the species variable has 3 levels indicating whether the observation is a Human, a Rhesus monkey, or a Potar monkey. We can easily create a binary variable such as the <code>isMonkey</code> variable (created below), which will allow us to compare monkeys (of <em>any</em> type) vs not-monkeys (or “Humans”, as we are better known!).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>braindata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_braindata.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>braindata <span class="ot">&lt;-</span> braindata <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">isMonkey =</span> <span class="fu">ifelse</span>(species <span class="sc">!=</span> <span class="st">"Human"</span>, <span class="st">"YES"</span>, <span class="st">"NO"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(braindata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  species       mass_brain   age isMonkey
  &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   
1 Rhesus monkey      0.449     5 YES     
2 Human              0.577     2 NO      
3 Potar monkey       0.349    30 YES     
4 Human              0.626    27 NO      
5 Potar monkey       0.316    31 YES     
6 Rhesus monkey      0.398    11 YES     </code></pre>
</div>
</div>
<p>To recap what we’ve seen already - when we use a binary variable like <code>isMonkey</code> in a model as a predictor, it gets inputted into the model as a series of 0s and 1s. Because the coefficients of regression models are always interpreted as “the change in <span class="math inline">\(y\)</span> associated with a 1 unit change in <span class="math inline">\(x\)</span>”, the use of 0s and 1s for different levels of a categorical variable allows us to make “a 1 unit change in <span class="math inline">\(x\)</span>” represent moving from one level to another. Internally, our model is relying on a variable like the <code>isMonkeyYES</code> variable below:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  species       mass_brain   age isMonkey isMonkeyYES
  &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;
1 Rhesus monkey      0.449     5 YES                1
2 Human              0.577     2 NO                 0
3 Potar monkey       0.349    30 YES                1
4 Human              0.626    27 NO                 0
5 Potar monkey       0.316    31 YES                1
6 Rhesus monkey      0.398    11 YES                1</code></pre>
</div>
</div>
<p>This means that we can get out the model below an estimate of the difference in brain mass from the group <code>isMonkey == "NO"</code> to the group <code>isMonkey == "YES"</code>, because this is moving from 0 to 1. We can see this in the model and visualisation below.</p>
<div class="panelset">
<section id="model" class="level4 panel">
<h4 class="anchored" data-anchor-id="model">Model</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>monkmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_brain<span class="sc">~</span>isMonkey, <span class="at">data =</span> braindata)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(monkmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.60271    0.03475  17.346  &lt; 2e-16 ***
isMonkeyYES -0.25986    0.04486  -5.793 1.78e-06 ***</code></pre>
</div>
</div>
<ul>
<li><code>(Intercept)</code>: the estimated brain mass of Humans (when the isMonkeyYES variable is zero)</li>
<li><code>isMonkeyYES</code>: the estimated change in brain mass from Humans to Monkeys (change in brain mass when moving from isMonkeyYES = 0 to isMonkeyYES = 1).</li>
</ul>
</section>
<section id="visual" class="level4 panel">
<h4 class="anchored" data-anchor-id="visual">Visual</h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-binpredplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08b_catpred_files/figure-html/fig-binpredplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: A binary categorical predictor</figcaption>
</figure>
</div>
</div>
</div>
</section>
</div>
<p>When used as predictors in multiple regression models, binary variables behave much the same way. The coefficient will give us the estimated change in <span class="math inline">\(y\)</span> when moving from one level to the other<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, <em>while holding other predictors constant.</em></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>monkmod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_brain<span class="sc">~</span>age <span class="sc">+</span> isMonkey, <span class="at">data =</span> braindata)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(monkmod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.668308   0.050478  13.240 1.57e-14 ***
age         -0.004081   0.002337  -1.746   0.0904 .  
isMonkeyYES -0.246933   0.044152  -5.593 3.54e-06 ***</code></pre>
</div>
</div>
<ul>
<li><code>(Intercept)</code>: the estimated brain mass of <em>new-born</em> Humans (when both age is zero and isMonkeyYES is zero)</li>
<li><code>age</code>: the estimated change in brain mass for every 1 year increase in age, holding isMonkey constant.</li>
<li><code>isMonkeyYES</code>: the estimated change in brain mass from Humans to Monkeys (change in brain mass when moving from isMonkeyYES = 0 to isMonkeyYES = 1), holding age constant.</li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: a visual
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If we want a visual intuition to how a binary predictor works in multiple regression - it’s actually just like any other predictor, in that it’s just another dimension to the model. The only difference is that it is on a <strong>discrete</strong> scale - observations fall on <em>either</em> 0 <em>or</em> 1, not on the continuum in between.</p>
<p>So for the model <code>mass_brain ~ age + isMonkey</code>, rather than a 3D surface, we might think of our model as two edges of a surface, as shown in the left-hand panel of <a href="#fig-binpredmult">Figure&nbsp;2</a>. And if ‘monkey-ness’ was some sort of measurable continuum (“I’m 70% monkey?”) then this just joins those edges up back to a surface (right panel).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-binpredmult" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08b_catpred_files/figure-html/fig-binpredmult-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: a binary predictor is just another dimension, but data can only exist at either 0 or 1. If a variable were continuous, then observations can take any value along a line</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="multiple-categories" class="level1">
<h1>Multiple Categories</h1>
<p>What about when we have a predictor with <em>more than</em> two categories? We might have lots of different conditions in our experiment, or we might have observations from lots of different distinct groups of people.</p>
<p>In the primate brains example, we have various different species of primates - we have 3 (“Potar monkey”, “Rhesus Monkey” and “Human”). What happens when we consider a model which has a predictor like <code>species</code>?</p>
<p>Fitting the model <code>lm(mass_brain ~ species)</code> will by default use one of our categories as a “reference level”, and then our coefficients will show comparisons between each of the remaining levels to that reference level. So if the reference level is “Human”, the coefficients we get out include:</p>
<ul>
<li>the intercept (which is the estimated brain mass of humans);</li>
<li>the estimated difference in brain mass when we move from humans to potar monkeys;</li>
<li>and the difference when we move from humans to rhesus monkeys.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mass_brain ~ species, data = braindata)
...
Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           0.60271    0.02748  21.936  &lt; 2e-16 ***
speciesPotar monkey  -0.35735    0.04142  -8.627 7.38e-10 ***
speciesRhesus monkey -0.15261    0.04257  -3.585   0.0011 ** </code></pre>
</div>
</div>
<div class="rtip">
<p><strong>How do i know which one is my reference level??</strong></p>
<p>Notice that our coefficients are named <code>speciesPotar monkey</code> and <code>speciesRhesus monkey</code>. When faced with a categorical predictor, the lm function will name coefficients in the format <code>variableLevel</code>. We can see that we have coefficients for both “Potar monkey” and “Rhesus monkey”, so we can infer that the reference level is the one we can’t see (“Human”).<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>R will default to using alphabetical ordering, hence the reference level being set as “Human”. We could override this by making it a factor with an ordering to it’s levels (see the use of <code>factor()</code> and <code>levels()</code> in <a href="02a_measurement.html#categorical" target="_blank">2A#categorical</a>). Functions like <code>fct_relevel()</code> might be handy too.</p>
</div>
<p>Note that while we have 3 species in our data, we only have 2 coefficients from our model. This scales up - when we have categorical predictors with multiple levels, we end up having <span class="math inline">\(\text{number-of-levels}-1\)</span> coefficients in our model.</p>
<p>This is because to determine which of the <span class="math inline">\(k\)</span> categories an observation is in, we only need to have <span class="math inline">\(k-1\)</span> binary variables.</p>
<p>For instance, we can re-express all the the information contained in the <code>species</code> variable (with 3 levels) with just two binary variables:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>braindata <span class="ot">&lt;-</span> braindata <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">speciesPotar =</span> <span class="fu">ifelse</span>(species <span class="sc">==</span> <span class="st">"Potar monkey"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">speciesRhesus =</span> <span class="fu">ifelse</span>(species <span class="sc">==</span> <span class="st">"Rhesus monkey"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>braindata <span class="sc">%&gt;%</span> </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mass_brain, species, speciesPotar, speciesRhesus) <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  mass_brain species       speciesPotar speciesRhesus
       &lt;dbl&gt; &lt;chr&gt;                &lt;dbl&gt;         &lt;dbl&gt;
1      0.449 Rhesus monkey            0             1
2      0.577 Human                    0             0
3      0.349 Potar monkey             1             0
4      0.626 Human                    0             0
5      0.316 Potar monkey             1             0
6      0.398 Rhesus monkey            0             1</code></pre>
</div>
</div>
<ul>
<li>For a human, both <code>speciesPotar == 0</code> and <code>speciesRhesus == 0</code></li>
<li>For a Potar monkey, <code>speciesPotar == 1</code> and <code>speciesRhesus == 0</code></li>
<li>For a Rhesus monkey, <code>speciesPotar == 0</code> and <code>speciesRhesus == 1</code></li>
</ul>
<p>These two binary variables are actually pretty much what R will put into our model even though we only gave it the one <code>species</code> variable!</p>
<p>Recall that the intercept is the estimated outcome <em>when all predictors are zero</em>. In this case, when both variables are zero, we are looking at the Humans group. And when we move 1 on the <code>speciesPotar</code> scale, we move from the humans to the Potar monkeys. When we move 1 on the <code>speciesRhesus</code> scale, we move from humans to Rhesus monkeys. So each coefficient is comparing a level to the “reference level” (as in <a href="#fig-kpredplot">Figure&nbsp;3</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-kpredplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08b_catpred_files/figure-html/fig-kpredplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3: A categorical predictor with 3 levels</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: proving it to ourselves
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Try fitting a model that uses the two binary variables we made above instead of using <code>species</code>. Take a look at the coefficients, try to compare the models to one another.<br>
They are identical!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>specmod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_brain <span class="sc">~</span> speciesPotar <span class="sc">+</span> speciesRhesus, <span class="at">data =</span> braindata)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(specmod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mass_brain ~ speciesPotar + speciesRhesus, data = braindata)
...
Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    0.60271    0.02748  21.936  &lt; 2e-16 ***
speciesPotar  -0.35735    0.04142  -8.627 7.38e-10 ***
speciesRhesus -0.15261    0.04257  -3.585   0.0011 ** </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: more categories = more dimensions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We’ve just seen how a categorical variable with <span class="math inline">\(k\)</span> levels gets inputted into our model as a set of <span class="math inline">\(k-1\)</span> predictors. Each of these <span class="math inline">\(k-1\)</span> predictors is actually just another dimension to the model.</p>
<p>We could try (we maybe shouldn’t) to re-express <a href="#fig-kpredplot">Figure&nbsp;3</a> as a 3D plot. It would look a little like this:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08b_catpred_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="rtip">
<p><strong>Good practice</strong></p>
<p>In the primate-brains example, all this is happening as part of the model fitting process. This is because we are using variables with sets of characters (“YES” and “NO”, or “Human”, “Potar monkey” and “Rhesus monkey”). When we put these in a model, R doesn’t know how else to interpret it other than as a set of categories - i.e.&nbsp;it gets interpreted as a ‘factor’ (see <a href="02a_measurement.html#categorical" target="_blank">2A#categorical</a>) without us actually having to explicitly tell R that it is a factor.</p>
<p>If we have a variable where a set of categories is represented by numbers, then the model will interpret them as numerical values (i.e.&nbsp;2 is twice 1 etc).</p>
<p>If a variable is categorical, it is good practice to make it a factor when you read in your data. That way you don’t get into errors later on when modelling.</p>
</div>
<section id="tests" class="level2">
<h2 class="anchored" data-anchor-id="tests">Tests</h2>
<p>We have just seen how entering a categorical predictor with <span class="math inline">\(k\)</span> levels in as a predictor to a regression model is essentially equivalent to adding in <span class="math inline">\(k-1\)</span> different binary variables. We get out <span class="math inline">\(k-1\)</span> coefficients relating to each of those variables.</p>
<p>In our primate-brains example, our model <code>lm(mass_brain ~ species)</code> might look like it only has one predictor (<code>species</code>), but because it has 3 levels, we end up with 2 coefficients - we are essentially making a <em>multiple</em> regression model. So what can we test when it comes to <code>species</code>? We can test comparisons between specific levels, but we can also ask an overall question of “do species differ?”</p>
<section id="testing-differences-between-specific-groups" class="level4">
<h4 class="anchored" data-anchor-id="testing-differences-between-specific-groups">Testing differences between specific groups</h4>
<p>Tthe coefficients from our regression model represent specific comparisons between levels of a categorical predictor. The default behaviour in R is (as we have seen) to compare each level to the reference level.</p>
<p>The tests (Std. Error, t value, df, p value) associated of these coefficient estimates therefore provide us with a means of testing whether the difference in <span class="math inline">\(y\)</span> between two levels is significantly different from zero.</p>
<p>For example, from our model output below, we can say that..</p>
<div class="int">
<p>… both Potar monkeys and Rhesus monkeys had significantly lower brain mass than Humans (<span class="math inline">\(\beta=-0.357,t(32)=-8.627, p&lt;.001\)</span> and <span class="math inline">\(\beta=-0.153,t(32)=-3.585, p=.0011\)</span> respectively).</p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mass_brain ~ species, data = braindata)
...
Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           0.60271    0.02748  21.936  &lt; 2e-16 ***
speciesPotar monkey  -0.35735    0.04142  -8.627 7.38e-10 ***
speciesRhesus monkey -0.15261    0.04257  -3.585   0.0011 ** </code></pre>
</div>
</div>
</section>
<section id="testing-group-differences" class="level4">
<h4 class="anchored" data-anchor-id="testing-group-differences">Testing ‘group differences’</h4>
<p>It will hopefully come as little surprise that the way to test an overall question of “are there differences between groups” can be assessed by a model comparison between models with and without the predictor.</p>
<p>Why? because this allows us to use the F test as a “joint test” (see <a href="07a_mlr.html#model-comparisons" target="_blank">7A #model-comparisons</a>) of whether including all the information about groups explains a significant amount of additional variance in our outcome (i.e.&nbsp;if their inclusion provides a significant reduction in residual sums of squares).</p>
<p>So from our model comparison below, we can say something like… :::int … species differences (Human/Potar monkey/Rhesus monkey) explained a significant amount of variance in brain mass over the null model (<span class="math inline">\(F(2, 32) = 37.22,\ p &lt;.001\)</span>). :::</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_brain <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> braindata)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_brain <span class="sc">~</span> species, <span class="at">data =</span> braindata)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0, m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: mass_brain ~ 1
Model 2: mass_brain ~ species
  Res.Df     RSS Df Sum of Sq     F    Pr(&gt;F)    
1     34 1.12500                                 
2     32 0.33822  2   0.78678 37.22 4.453e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
</section>
</section>
<section id="contrasts" class="level1">
<h1>Contrasts</h1>
<p>We can actually do <em>lots</em> of clever things with categorical predictors in regression models, in order to compare different groups to one another.</p>
<p>The first thing we need to do is to explicitly tell R that they are categorical variables (i.e.&nbsp;we need to make them ‘factors’):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>braindata <span class="ot">&lt;-</span> braindata <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">isMonkey =</span> <span class="fu">factor</span>(isMonkey),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">species =</span> <span class="fu">factor</span>(species)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once we have done this we can see (and also manipulate) the way in which it gets treated by our model. This is because factors in R have some special attributes called “contrasts”. Contrasts are ultimately the thing that the model will use to decide what you want to compare to what.</p>
<p>The following code shows us the “contrast matrix” for a given variable. The rows of this show each level of our variable, and the columns are the coefficients (the comparisons which are estimated when we put the variable into a model).<br>
We can see that the default contrasts match the two binary variables we had created manually earlier on:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(braindata<span class="sc">$</span>species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/contrasts.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>We can easily “relevel” factor, thereby changing which one is the ‘reference level’ (the level against which all other levels are compared), by using handy functions like <code>fct_relevel()</code>.<br>
For instance, if we wanted to see how each species compared to Rhesus monkeys, re-levelling the factor changes the contrasts accordingly:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>braindata <span class="ot">&lt;-</span> braindata <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">species2 =</span> <span class="fu">fct_relevel</span>(species, <span class="st">"Rhesus monkey"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(braindata<span class="sc">$</span>species2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Human Potar monkey
Rhesus monkey     0            0
Human             1            0
Potar monkey      0            1</code></pre>
</div>
</div>
<p>We’re not going to delve too far into contrasts in this course (it’s a bit of a rabbit hole!), but it’s worth knowing about a couple of different types, and what we can use them to extract from our model.</p>
<div class="sticky">
<p><strong>Setting contrasts in R</strong></p>
<p>As we will see in action below, in order to change the contrasts used in a model, we can assign specific types of contrasts to the variable in the data, by using code such as:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(data<span class="sc">$</span>variable) <span class="ot">&lt;-</span> ...</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This <strong>changes an attribute of the data</strong>, which means that any model <em>subsequently</em> fitted to that data will now use the assigned contrasts.</p>
<p>To revert to the default, we can either a) read in the data again, or b) tell R that we now want to use the default contrasts, known as ‘treatment contrasts’, by using:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To reset the contrasts to the default used in R</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(data<span class="sc">$</span>variable) <span class="ot">&lt;-</span> <span class="st">"contr.treatment"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<section id="treatment-contrasts-the-default" class="level2">
<h2 class="anchored" data-anchor-id="treatment-contrasts-the-default">Treatment Contrasts (the default)</h2>
<p>“Treatment contrasts” are the default that R uses. These are the ones we’ve already discussed above. It compares each level to a reference level. A common example is to compare people taking different ‘treatments’ (drug A, drug B and drug C) to a placebo group (the reference level).</p>
<p>When we use this approach:</p>
<ul>
<li>the intercept is the estimated y when <em>all</em> predictors are zero. Because the reference level is kind of like “0” in our contrast matrix, this is part of the intercept estimate.<br>
</li>
<li>we get out a coefficient for each subsequent level, which are the estimated differences from each level to the reference group.</li>
</ul>
</section>
<section id="sum-contrasts" class="level2">
<h2 class="anchored" data-anchor-id="sum-contrasts">Sum Contrasts</h2>
<p>“sum contrasts” (sometimes called “deviation contrasts” and “effects coding”) are the next most commonly used in psychological research. These are a way of comparing each level to the overall mean.</p>
<p>This involves a bit of trickery that uses -1s and 1s rather than 0s and 1s, in order to make “0” be mid-way between all the levels - the average of the levels.</p>
<p>We can adjust the coding scheme that we use like so:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(braindata<span class="sc">$</span>isMonkey) <span class="ot">&lt;-</span> <span class="st">"contr.sum"</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(braindata<span class="sc">$</span>isMonkey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    [,1]
NO     1
YES   -1</code></pre>
</div>
</div>
<div class="imp">
<p>note that the column of the contrast matrix no longer has a name! It’s just got a <code>[,1]</code>. This means that the coefficient we get out is not going to have a name either!!!</p>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>monkmod_sum <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_brain<span class="sc">~</span>isMonkey, braindata)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(monkmod_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mass_brain ~ isMonkey, data = braindata)
...
Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.47279    0.02243  21.079  &lt; 2e-16 ***
isMonkey1    0.12993    0.02243   5.793 1.78e-06 ***</code></pre>
</div>
</div>
<p>The intercept from this model is the estimated average brain mass averaged across monkeys and non-monkeys. i.e.&nbsp;the estimated ‘grand mean’ brain mass.<br>
The coefficient represents moving from the overall mean brain mass to the <code>isMonkey=="NO"</code> mean brain mass.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> This is visualised in <a href="#fig-binpredplot2">Figure&nbsp;4</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-binpredplot2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08b_catpred_files/figure-html/fig-binpredplot2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4: A binary categorical predictor with sum contrasts</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: -1/1 vs -.5/.5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For sum contrasts, sometimes people prefer to use -.5 and .5 instead of -1 and 1. This is because it keeps the intercept as the “grand mean”, but makes the coefficient represent the difference between the two groups (which might be more useful as a number to talk about).</p>
<p>This works because with just these two groups, the distance from isMonkey==YES to isMonkey==NO is <em>twice as far</em> as the distance from the grand mean to the isMonkey==NO group (because the grand mean is the mid-point).<br>
By halving the contrast, it doubles our coefficient (because ‘a change in 1’ is now twice as far).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(braindata<span class="sc">$</span>isMonkey) <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">5</span>, <span class="sc">-</span>.<span class="dv">5</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(braindata<span class="sc">$</span>isMonkey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    [,1]
NO   0.5
YES -0.5</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>monkmod_sum <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_brain<span class="sc">~</span>isMonkey, braindata)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(monkmod_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mass_brain ~ isMonkey, data = braindata)
...
Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.47279    0.02243  21.079  &lt; 2e-16 ***
isMonkey1    0.25986    0.04486   5.793 1.78e-06 ***</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-binpredplot3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08b_catpred_files/figure-html/fig-binpredplot3-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5: A binary categorical predictor with sum contrasts using -.5 and .5</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>When we move to using variables with more than 2 levels, sum contrasts can look a lot more confusing, but the logic of how we interpret coefficients stays very much the same.<br>
For instance, using sum contrasts with the <code>species</code> variable:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(braindata<span class="sc">$</span>species) <span class="ot">&lt;-</span> <span class="st">"contr.sum"</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(braindata<span class="sc">$</span>species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              [,1] [,2]
Human            1    0
Potar monkey     0    1
Rhesus monkey   -1   -1</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>specmod_sum <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_brain <span class="sc">~</span> species, braindata)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(specmod_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mass_brain ~ species, data = braindata)
...
Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.43273    0.01755  24.654  &lt; 2e-16 ***
species1     0.16999    0.02366   7.185 3.70e-08 ***
species2    -0.18736    0.02507  -7.474 1.65e-08 ***</code></pre>
</div>
</div>
<ul>
<li>Our intercept is the ‘grand mean’ (the mean of each species’ estimated mean brain mass).</li>
<li>Our first coefficient is the difference from the grand mean to the mean of humans.</li>
<li>Our second coefficient is the difference from the grand mean to the mean of Potar monkeys.</li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: where have my rhesus monkeys gone?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It feels a bit odd, but we no longer have an estimate for our Rhesus monkeys.</p>
<p>This felt okay when we knew they were just being collapsed into our intercept, but where are they now? Our intercept is the grand mean. Where are my Rhesus Monkeys??</p>
<p>As stated above, our intercept is the mean of each species’ estimated mean brain mass (the ‘grand mean’). We can write this as:<br>
<span class="math display">\[
\begin{align}
\text{(Intercept)} &amp;: \frac{\bar{R}+\bar{P}+\bar{H}}{3} = 0.43\\
\text{where:}&amp;\\
&amp;\bar{R}, \,\bar{P}, \, \bar{H} \text{ are the mean brain mass for }\\
&amp;\text{Rhesus monkeys, Potar monkeys, and Humans respectively}
\end{align}
\]</span></p>
<p>The second coefficient of our model represents the difference from this value to the mean brain mass of humans, and the third represents the difference from this value to the mean brain mass of Potar monkeys:</p>
<p><span class="math display">\[
\begin{align}
\text{species1} &amp;: \bar{H} - 0.43 = 0.17 \\
\text{species2} &amp;: \bar{P} - 0.43 = -0.19 \\
\end{align}
\]</span> We can rewrite these to find those means for Humans and Potars as:<br>
$$ <span class="math display">\[\begin{align}
\bar{H} &amp;= \underbrace{0.43}_{\text{intercept}} &amp;+ \underbrace{0.17}_{\text{species1 coefficient}}  &amp;= &amp;0.6\\
\, \\
\bar{P} &amp;= \underbrace{0.43}_{\text{intercept}} &amp;+ \underbrace{-0.19}_{\text{species2 coefficient}}  &amp;= &amp;0.24\\

\end{align}\]</span> $$ Our Rhesus monkeys are actually still there in our intercept! They’re just only represented as a third of the intercept (the other two thirds being the humans and potar monkeys). If we substitute in our <span class="math inline">\(\bar H\)</span> and <span class="math inline">\(\bar P\)</span> values to our intercept:</p>
<p><span class="math display">\[
\begin{align}
\text{(Intercept)} :&amp;\, \frac{\bar{R}+\bar{P}+\bar{H}}{3} = 0.43\\
\, \\
&amp; \frac{\bar{R}+0.24+0.6}{3} = 0.43\\
\, \\
&amp; \bar{R}+0.24+0.6 = 3 \times 0.43\\
&amp; \bar{R}+0.24+0.6 = 1.29\\
&amp; \bar{R} = 1.29 - 0.24 - 0.6\\
&amp; \bar{R} = 0.45\\
\end{align}
\]</span> And there we have our Rhesus monkeys! Because there are no other predictors in our model, this should match exactly (with rounding error in the above calculations!) with what the mean brain mass of Rhesus monkeys is in our data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(braindata<span class="sc">$</span>mass_brain[braindata<span class="sc">$</span>species<span class="sc">==</span><span class="st">"Rhesus monkey"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4501</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="optional-and-many-more.." class="level2">
<h2 class="anchored" data-anchor-id="optional-and-many-more..">Optional: and many more..</h2>
<p>There are a whole load of other types of contrasts we can use, and we can even set custom ones of our own. The choices are many, <em>and confusing</em>, and it really depends on what exactly we want to get out of our model, which is going to depend on our research.</p>
<p>Some useful resources for your future research:</p>
<ul>
<li>A page showing many many different contrast coding schemes (with R code and interpretation): <a href="https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/" target="_blank">https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/</a></li>
<li>The <strong>emmeans</strong> package (“estimated marginal means”) can come in handy for lots and lots of ways to compare groups. The package ‘vignette’ is at <a href="https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html" target="_blank">https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html</a></li>
</ul>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>and the intercept will be the estimated <span class="math inline">\(y\)</span> when <strong>all</strong> predictors are zero<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This is all assuming that we have things set to their defaults in R. We’ll see below that we can change things up using something called ‘contrasts’.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>we know it is to this group because a 1 increase in the column of our contrast matrix takes us to this group<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2023 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>