{
  "hash": "4703515598e90817d7bc5edc4af1eff3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"8B: Categorical Predictors\"\nparams: \n    SHOW_SOLS: TRUE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n\n\n\n# Binary Predictors  \n\nSince we've started working with linear regression, we've seen a few examples of categorical variables as predictors in linear models, and most (if not all) of these have been binary predictors - i.e. having just *two* categories (yes/no, dog/cat, phonics/word). We talked initially ([5B#binary-predictors](05b_slr.html#binary-predictors){target=\"_blank\"}) about how these get entered in the model as 0s and 1s.  \n\nLet's consider a dataset which includes the brain mass and body mass of different primates. Below, we can see the `species` variable has 3 levels indicating whether the observation is a \"Human\", a \"Rhesus monkey\", or a \"Potar monkey\". We can easily create a binary variable such as the `isMonkey` variable (created below), which will allow us to compare monkeys (of _any_ type) vs not-monkeys (or \"Humans\", as we are better known!).  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nbraindata <- read_csv(\"https://uoepsy.github.io/data/usmr_braindata.csv\")\n\nbraindata <- braindata %>% mutate(\n  isMonkey = ifelse(species != \"Human\", \"YES\", \"NO\")\n)\nhead(braindata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  species       mass_brain   age isMonkey\n  <chr>              <dbl> <dbl> <chr>   \n1 Rhesus monkey      0.449     5 YES     \n2 Human              0.577     2 NO      \n3 Potar monkey       0.349    30 YES     \n4 Human              0.626    27 NO      \n5 Potar monkey       0.316    31 YES     \n6 Rhesus monkey      0.398    11 YES     \n```\n\n\n:::\n:::\n\n\n\n\nTo recap what we've seen already - when we use a binary variable like `isMonkey` in a model as a predictor, it gets inputted into the model as a column of 0s and 1s. Because the coefficients of regression models are always interpreted as \"the change in $y$ associated with a 1 unit change in $x$\", the use of 0s and 1s for different levels of a categorical variable allows us to make \"a 1 unit change in $x$\" represent moving from one level to another. Internally, our model is relying on a variable like the `isMonkeyYES` variable below:   \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  species       mass_brain   age isMonkey isMonkeyYES\n  <chr>              <dbl> <dbl> <chr>          <dbl>\n1 Rhesus monkey      0.449     5 YES                1\n2 Human              0.577     2 NO                 0\n3 Potar monkey       0.349    30 YES                1\n4 Human              0.626    27 NO                 0\n5 Potar monkey       0.316    31 YES                1\n6 Rhesus monkey      0.398    11 YES                1\n```\n\n\n:::\n:::\n\n\n\n\n\nThis means that from the model below we can get out an estimate of the difference in brain mass from the group `isMonkey == \"NO\"` to the group `isMonkey == \"YES\"`, because this is moving from 0 to 1. We can see this in the model and visualisation @fig-binpredplot.  \n\n\n::::panelset\n:::panel\n#### Model\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonkmod <- lm(mass_brain~isMonkey, data = braindata)\nsummary(monkmod)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.60271    0.03475  17.346  < 2e-16 ***\nisMonkeyYES -0.25986    0.04486  -5.793 1.78e-06 ***\n```\n\n\n:::\n:::\n\n\n\n\n- `(Intercept)`: the estimated brain mass of Humans (when the isMonkeyYES variable is zero)\n- `isMonkeyYES`: the estimated change in brain mass from Humans to Monkeys (change in brain mass when moving from isMonkeyYES = 0 to isMonkeyYES = 1). \n\n\n:::\n:::panel\n#### Visual\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A binary categorical predictor](08b_catpred_files/figure-html/fig-binpredplot-1.png){#fig-binpredplot fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n:::\n::::\n  \n<br>\nWhen used as predictors in **multiple** regression models (i.e. when there are other predictors involved), binary variables behave much the same way. The coefficient will give us the estimated change in $y$ when moving from one level to the other^[and the intercept will be the estimated $y$ when **all** predictors are zero], _while holding other predictors constant_ (see [7A#interpreting-coefficients](07a_mlr.html#interpreting-multiple-regression-coefficients)).  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonkmod2 <- lm(mass_brain~age + isMonkey, data = braindata)\nsummary(monkmod2)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.668308   0.050478  13.240 1.57e-14 ***\nage         -0.004081   0.002337  -1.746   0.0904 .  \nisMonkeyYES -0.246933   0.044152  -5.593 3.54e-06 ***\n```\n\n\n:::\n:::\n\n\n\n\n- `(Intercept)`: the estimated brain mass of *new-born* Humans (when both age is zero and isMonkeyYES is zero)\n- `age`: the estimated change in brain mass for every 1 year increase in age, holding isMonkey constant.\n- `isMonkeyYES`: the estimated change in brain mass from Humans to Monkeys (change in brain mass when moving from isMonkeyYES = 0 to isMonkeyYES = 1), holding age constant.  \n\n\n::: {.callout-caution collapse=\"true\"}\n#### optional: a visual\n\nIf we want a visual intuition to how a binary predictor works in multiple regression - it's actually just like any other predictor, in that it's just another dimension to the model. The only difference is that it is on a __discrete__ scale - observations fall on _either_ 0 _or_ 1, not on the continuum in between.  \n  \nSo for the model `mass_brain ~ age + isMonkey`, rather than a 3D surface, we might think of our model as two edges of a surface, as shown in the left-hand panel of @fig-binpredmult. \nAnd if 'monkey-ness' was some sort of measurable continuum (\"I'm 70% monkey?\") then this just joins those edges up back to a surface (right panel).  \n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![a binary predictor is just another dimension, but data can only exist at either 0 or 1. If a variable were continuous, then observations can take any value along a line](08b_catpred_files/figure-html/fig-binpredmult-1.png){#fig-binpredmult fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n:::\n\n\n# Multiple Categories  \n\nWhat about when we have a predictor with *more than* two categories? We might have lots of different conditions in our experiment, or we might have observations from lots of different distinct groups of people. \n\nIn the primate brains example, we have various different species of primates - we have 3 (\"Potar monkey\", \"Rhesus Monkey\" and \"Human\").  What happens when we consider a model which has a predictor like `species`?  \n\nFitting the model `lm(mass_brain ~ species)` will by default use one of our categories as a \"reference level\", and then our coefficients will show comparisons between each of the remaining levels to that reference level. So if the reference level is \"Human\", the coefficients we get out include:\n\n- the intercept (which is the estimated brain mass of humans); \n- the estimated difference in brain mass when we move from humans to potar monkeys; \n- and the difference when we move from humans to rhesus monkeys.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mass_brain ~ species, data = braindata)\n...\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           0.60271    0.02748  21.936  < 2e-16 ***\nspeciesPotar monkey  -0.35735    0.04142  -8.627 7.38e-10 ***\nspeciesRhesus monkey -0.15261    0.04257  -3.585   0.0011 ** \n```\n\n\n:::\n:::\n\n\n\n\n\n:::rtip\n__How do i know which one is my reference level??__  \n\nNotice that our coefficients are named `speciesPotar monkey` and `speciesRhesus monkey`. When faced with a categorical predictor, the lm function will name coefficients in the format `variableLevel`. We can see that we have coefficients for both \"Potar monkey\" and \"Rhesus monkey\", so we can infer that the reference level is the one we can't see (\"Human\").^[This is all assuming that we have things set to their defaults in R. We'll see below that we can change things up using something called 'contrasts'.]  \n\nR will default to using alphabetical ordering, hence the reference level being set as \"Human\". We could override this by making it a factor with an ordering to it's levels (see the use of `factor()` and `levels()` in [2A#categorical](02a_measurement.html#categorical){target=\"_blank\"}). Functions like `fct_relevel()` might be handy too.  \n\n:::\n\n\nNote that while we have **3** species in our variable, we only have **2** coefficients in our model.  \nThis logic scales up - when we have categorical predictors with multiple levels, we will have $\\text{number-of-levels}-1$ coefficients in our model. This is because to determine which of the $k$ categories an observation is in, we actually only need to have $k-1$ binary variables.  \n\nFor instance, we can re-express all the the information contained in the `species` variable (with 3 levels) with just two binary variables:   \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbraindata <- braindata %>% mutate(\n  speciesPotar = ifelse(species == \"Potar monkey\", 1, 0),\n  speciesRhesus = ifelse(species == \"Rhesus monkey\", 1, 0),\n)\nbraindata %>% \n  select(mass_brain, species, speciesPotar, speciesRhesus) %>%\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  mass_brain species       speciesPotar speciesRhesus\n       <dbl> <chr>                <dbl>         <dbl>\n1      0.449 Rhesus monkey            0             1\n2      0.577 Human                    0             0\n3      0.349 Potar monkey             1             0\n4      0.626 Human                    0             0\n5      0.316 Potar monkey             1             0\n6      0.398 Rhesus monkey            0             1\n```\n\n\n:::\n:::\n\n\n\n\n- For a human, both `speciesPotar == 0` and `speciesRhesus == 0`\n- For a Potar monkey, `speciesPotar == 1` and `speciesRhesus == 0`\n- For a Rhesus monkey, `speciesPotar == 0` and `speciesRhesus == 1`\n\nThese two binary variables are actually pretty much what R will put into our model even though we only gave it the one `species` variable!  \n\nRecall that the intercept is the estimated outcome _when all predictors are zero_. In this case, when both variables are zero, we are looking at the Humans group. And when we move 1 on the `speciesPotar` scale, we move from the humans to the Potar monkeys. When we move 1 on the `speciesRhesus` scale, we move from humans to Rhesus monkeys. So each coefficient is comparing a level to the \"reference level\" (as in @fig-kpredplot).  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A categorical predictor with 3 levels](08b_catpred_files/figure-html/fig-kpredplot-1.png){#fig-kpredplot fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n::: {.callout-caution collapse=\"true\"}\n#### optional: proving it to ourselves\n\nTry fitting a model that uses the two binary variables we made above instead of using `species`. Take a look at the coefficients, try to compare the models to one another.   \nThey are identical! \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nspecmod2 <- lm(mass_brain ~ speciesPotar + speciesRhesus, data = braindata)\nsummary(specmod2)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mass_brain ~ speciesPotar + speciesRhesus, data = braindata)\n...\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    0.60271    0.02748  21.936  < 2e-16 ***\nspeciesPotar  -0.35735    0.04142  -8.627 7.38e-10 ***\nspeciesRhesus -0.15261    0.04257  -3.585   0.0011 ** \n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n\n::: {.callout-caution collapse=\"true\"}\n#### optional: more categories = more dimensions\n\nWe've just seen how a categorical variable with $k$ levels gets inputted into our model as a set of $k-1$ predictors. Each of these $k-1$ predictors is actually just another dimension to the model.  \n\nWe could try (we maybe shouldn't) to re-express @fig-kpredplot as a 3D plot. It would look a little like this:  \n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08b_catpred_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n\n:::\n\n\n:::rtip\n__Good practice__  \n\nIn the primate-brains example, all this is happening as part of the model fitting process. This is because we are using variables with sets of characters (\"YES\" and \"NO\", or \"Human\", \"Potar monkey\" and \"Rhesus monkey\"). When we put these in a model, R doesn't know how else to interpret it other than as a set of categories - i.e. it gets interpreted as a 'factor' (see [2A#categorical](02a_measurement.html#categorical){target=\"_blank\"}) without us actually having to explicitly tell R that it is a factor.    \n\nIf we have a variable where a set of categories is represented by numbers, then the model will interpret them as numerical values (i.e. 2 is twice 1 etc).  \n\nIf a variable is categorical, it is good practice to make it a factor when you read in your data. That way you don't get into errors later on when modelling. \n\n:::\n\n## Tests  \n\nWe have just seen how entering a categorical predictor with $k$ levels in as a predictor to a regression model is essentially equivalent to adding in $k-1$ different binary variables. We get out $k-1$ coefficients relating to each of those variables.  \n\nIn our primate-brains example, our model `lm(mass_brain ~ species)` might look like it only has one predictor (`species`), but because it has 3 levels, we end up with 2 coefficients - we are essentially making a _multiple_ regression model. \nSo what can we *test* when it comes to `species`? The coefficients can let us test comparisons between specific levels, but we can also ask an overall question of \"do species differ?\" \n\n#### Testing differences between specific groups\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\nThe coefficients from our regression model represent specific comparisons between levels of a categorical predictor. The default behaviour in R is (as we have seen) to compare each level to the reference level.  \n\nThe tests (Std. Error, t value, df, p value) associated with these coefficient estimates therefore provide us with a means of testing whether the difference in $y$ between two levels is significantly different from zero.  \n\nFor example, from our model output below, we can say that..  \n\n:::int\n... both Potar monkeys and Rhesus monkeys had significantly lower brain mass than Humans ($b=-0.357,t(32)=-8.627, p<.001$ and $b=-0.153,t(32)=-3.585, p=.0011$ respectively).  \n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mass_brain ~ species, data = braindata)\n...\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           0.60271    0.02748  21.936  < 2e-16 ***\nspeciesPotar monkey  -0.35735    0.04142  -8.627 7.38e-10 ***\nspeciesRhesus monkey -0.15261    0.04257  -3.585   0.0011 ** \n```\n\n\n:::\n:::\n\n\n\n\n#### Testing 'group differences'\n\nIt will hopefully come as little surprise that the way to test an overall question of \"are there differences between groups\" can be assessed by a model comparison between models with and without the predictor.  \n\nWhy? because this allows us to use the F test as a \"joint test\" (see [7A #model-comparisons](07a_mlr.html#model-comparisons){target=\"_blank\"}) of whether including all the information about groups explains a significant amount of additional variance in our outcome (i.e. if their inclusion provides a significant reduction in residual sums of squares).\n\nSo from our model comparison below, we can say something like...   \n\n:::int\n... species differences (Human/Potar monkey/Rhesus monkey) explained a significant amount of variance in brain mass over the null model ($F(2, 32) = 37.22,\\ p <.001$).\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm0 <- lm(mass_brain ~ 1, data = braindata)\nm1 <- lm(mass_brain ~ species, data = braindata)\nanova(m0, m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: mass_brain ~ 1\nModel 2: mass_brain ~ species\n  Res.Df     RSS Df Sum of Sq     F    Pr(>F)    \n1     34 1.12500                                 \n2     32 0.33822  2   0.78678 37.22 4.453e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n\n# Contrasts\n\nWe can actually do *lots* of clever things with categorical predictors in regression models, in order to compare different groups to one another.  \n\nThe first thing we need to do is to explicitly tell R that they are categorical variables (i.e. we need to make them 'factors'): \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbraindata <- braindata %>% \n  mutate(\n    isMonkey = factor(isMonkey),\n    species = factor(species)\n  )\n```\n:::\n\n\n\n\nOnce we have done this we can see (and also manipulate) the way in which it gets treated by our model. This is because factors in R have some special attributes called \"contrasts\". Contrasts are ultimately the thing that the model will use to decide what you want to compare to what.  \n\nThe following code shows us the \"contrast matrix\" for a given variable. The rows of this show each level of our variable, and the columns are the coefficients (the comparisons which are estimated when we put the variable into a model).  \nWe can see that the default contrasts match the two binary variables we had created manually earlier on:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrasts(braindata$species)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/contrasts.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nWe can easily \"relevel\" factor, thereby changing which one is the 'reference level' (the level against which all other levels are compared), by using handy functions like `fct_relevel()`. For instance, if we wanted to see how each species compared to Rhesus monkeys, re-levelling the factor changes the contrasts accordingly:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbraindata <- braindata %>% \n  mutate(\n    species2 = fct_relevel(species, \"Rhesus monkey\")\n  )\ncontrasts(braindata$species2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Human Potar monkey\nRhesus monkey     0            0\nHuman             1            0\nPotar monkey      0            1\n```\n\n\n:::\n:::\n\n\n\n\nWe're not going to delve too far into contrasts in this course (it's a bit of a rabbit hole!), but it's worth knowing about a couple of different types, and what we can use them to extract from our model. \n\n\n:::sticky\n__Setting contrasts in R__  \n\nAs we will see in action below, in order to change the contrasts used in a model, we can assign specific types of contrasts to the variable in the data, by using code such as: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrasts(data$variable) <- ...\n```\n:::\n\n\n\n\nThis **changes an attribute of the data**, which means that any model _subsequently_ fitted to that data will now use the assigned contrasts.  \n\nTo revert to the default, we can either a) read in the data again, or b) tell R that we now want to use the default contrasts, known as 'treatment contrasts', by using:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# To reset the contrasts to the default used in R\ncontrasts(data$variable) <- \"contr.treatment\"\n```\n:::\n\n\n\n\n:::\n\n## Treatment Contrasts (the default)\n\n\"Treatment contrasts\" are the default that R uses. These are the ones we've already discussed above. It compares each level to a reference level. A common example is to compare people taking different 'treatments' (drug A, drug B and drug C) to a placebo group (the reference level).  \n\nWhen we use this approach:  \n\n- the intercept is the estimated y when _all_ predictors are zero. Because the reference level is kind of like \"0\" in our contrast matrix, this is part of the intercept estimate.  \n- we get out a coefficient for each subsequent level, which are the estimated differences from each level to the reference group.  \n\n\n## Sum Contrasts\n\n\"sum contrasts\" (sometimes called \"deviation contrasts\" and \"effects coding\") are the next most commonly used in psychological research. These are a way of comparing each level to the overall mean.  \n\nThis involves a bit of trickery that uses -1s and 1s rather than 0s and 1s, in order to make \"0\" be mid-way between all the levels - the average of the levels.  \n\nWe can adjust the coding scheme that we use like so:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrasts(braindata$isMonkey) <- \"contr.sum\"\ncontrasts(braindata$isMonkey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    [,1]\nNO     1\nYES   -1\n```\n\n\n:::\n:::\n\n\n\n\n:::imp\nnote that the column of the contrast matrix no longer has a name! It's just got a `[,1]`. This means that the coefficient we get out is not going to have a name either!!! \n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonkmod_sum <- lm(mass_brain~isMonkey, braindata)\nsummary(monkmod_sum)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mass_brain ~ isMonkey, data = braindata)\n...\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.47279    0.02243  21.079  < 2e-16 ***\nisMonkey1    0.12993    0.02243   5.793 1.78e-06 ***\n```\n\n\n:::\n:::\n\n\n\n\nThe intercept from this model is the estimated average brain mass averaged across monkeys and non-monkeys. i.e. the estimated 'grand mean' brain mass.  \nThe coefficient represents moving from the overall mean brain mass to the `isMonkey==\"NO\"` mean brain mass.^[we know it is to this group because a 1 increase in the column of our contrast matrix takes us to this group] This is visualised in @fig-binpredplot2.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A binary categorical predictor with sum contrasts](08b_catpred_files/figure-html/fig-binpredplot2-1.png){#fig-binpredplot2 fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n::: {.callout-caution collapse=\"true\"}\n#### optional: -1/1 vs -.5/.5\n\nFor sum contrasts, sometimes people prefer to use -.5 and .5 instead of -1 and 1. This is because it keeps the intercept as the \"grand mean\", but makes the coefficient represent the difference between the two groups (which might be more useful as a number to talk about).  \n\nThis works because with just these two groups, the distance from `isMonkey==YES` to `isMonkey==NO` is _twice as far_ as the distance from the grand mean to the `isMonkey==NO` group (because the grand mean is the mid-point).  \nBy halving the contrast, it doubles our coefficient (because 'a change in 1' is now twice as far).  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrasts(braindata$isMonkey) <- c(.5, -.5)\ncontrasts(braindata$isMonkey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    [,1]\nNO   0.5\nYES -0.5\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonkmod_sum <- lm(mass_brain~isMonkey, braindata)\nsummary(monkmod_sum)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mass_brain ~ isMonkey, data = braindata)\n...\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.47279    0.02243  21.079  < 2e-16 ***\nisMonkey1    0.25986    0.04486   5.793 1.78e-06 ***\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A binary categorical predictor with sum contrasts using -.5 and .5](08b_catpred_files/figure-html/fig-binpredplot3-1.png){#fig-binpredplot3 fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n:::\n\n\n\n\nWhen we move to using variables with more than 2 levels, sum contrasts can look a lot more confusing, but the logic of how we interpret coefficients stays very much the same.  \nFor instance, using sum contrasts with the `species` variable:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrasts(braindata$species) <- \"contr.sum\"\ncontrasts(braindata$species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              [,1] [,2]\nHuman            1    0\nPotar monkey     0    1\nRhesus monkey   -1   -1\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nspecmod_sum <- lm(mass_brain ~ species, braindata)\nsummary(specmod_sum)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mass_brain ~ species, data = braindata)\n...\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.43273    0.01755  24.654  < 2e-16 ***\nspecies1     0.16999    0.02366   7.185 3.70e-08 ***\nspecies2    -0.18736    0.02507  -7.474 1.65e-08 ***\n```\n\n\n:::\n:::\n\n\n\n\n- Our intercept is the 'grand mean' (the mean of each species' estimated mean brain mass). \n- Our first coefficient is the difference from the grand mean to the mean of humans. \n- Our second coefficient is the difference from the grand mean to the mean of Potar monkeys. \n\n\n::: {.callout-caution collapse=\"true\"}\n#### optional: where have my rhesus monkeys gone? \n\nIt feels a bit odd, but we no longer have an estimate for our Rhesus monkeys. \n\nThis felt okay when we knew they were just being collapsed into our intercept, but where are they now? Our intercept is the grand mean. Where are my Rhesus Monkeys?? \n\nAs stated above, our intercept is the mean of each species' estimated mean brain mass (the 'grand mean'). \nWe can write this as:  \n$$\n\\begin{align}\n\\text{(Intercept)} &: \\frac{\\bar{R}+\\bar{P}+\\bar{H}}{3} = 0.43\\\\\n\\text{where:}&\\\\\n&\\bar{R}, \\,\\bar{P}, \\, \\bar{H} \\text{ are the mean brain mass for }\\\\\n&\\text{Rhesus monkeys, Potar monkeys, and Humans respectively}\n\\end{align}\n$$\n\nThe second coefficient of our model represents the difference from this value to the mean brain mass of humans, and the third represents the difference from this value to the mean brain mass of Potar monkeys:  \n\n$$\n\\begin{align}\n\\text{species1} &: \\bar{H} - 0.43 = 0.17 \\\\\n\\text{species2} &: \\bar{P} - 0.43 = -0.19 \\\\\n\\end{align}\n$$\n\nWe can rewrite these to find those means for Humans and Potars as:  \n\n$$\n\\begin{align}\n\\bar{H} &= \\underbrace{0.43}_{\\text{intercept}} &+ \\underbrace{0.17}_{\\text{species1 coefficient}}  &= &0.6 \\\\\n\\quad & & \\\\\n\\bar{P} &= \\underbrace{0.43}_{\\text{intercept}} &+ \\underbrace{-0.19}_{\\text{species2 coefficient}}  &= &0.24 \\\\\n\\end{align}\n$$\n\nOur Rhesus monkeys are actually still there in our intercept! They're just only represented as a third of the intercept (the other two thirds being the humans and potar monkeys). \nIf we substitute in our $\\bar H$ and $\\bar P$ values to our intercept:  \n\n$$\n\\begin{align}\n\\text{(Intercept)} :&\\, \\frac{\\bar{R}+\\bar{P}+\\bar{H}}{3} = 0.43\\\\\n\\, \\\\\n& \\frac{\\bar{R}+0.24+0.6}{3} = 0.43\\\\\n\\, \\\\\n& \\bar{R}+0.24+0.6 = 3 \\times 0.43\\\\\n& \\bar{R}+0.24+0.6 = 1.29\\\\\n& \\bar{R} = 1.29 - 0.24 - 0.6\\\\\n& \\bar{R} = 0.45\\\\\n\\end{align}\n$$\nAnd there we have our Rhesus monkeys! Because there are no other predictors in our model, this should match exactly (with rounding error in the above calculations!) with what the mean brain mass of Rhesus monkeys is in our data:   \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(braindata$mass_brain[braindata$species==\"Rhesus monkey\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4501\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n\n## Optional: and many more.. \n\nThere are a whole load of other types of contrasts we can use, and we can even set custom ones of our own. The choices are many, _and confusing_, and it really depends on what exactly we want to get out of our model, which is going to depend on our research.  \n\nSome useful resources for your future research:  \n\n- A page showing many many different contrast coding schemes (with R code and interpretation): [https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/](https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/){target=\"_blank\"} \n- The **emmeans** package (\"estimated marginal means\") can come in handy for lots and lots of ways to compare groups. The package 'vignette' is at [https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html](https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html){target=\"_blank\"}  \n\n",
    "supporting": [
      "08b_catpred_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}