{
  "hash": "8ac717ac96abb56c4da86689ba63022b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercises: T-tests\"\nlink-citations: true\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\n---\n\n\n\n\n\n\n# Intervals again  \n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nAt the end of last week's exercises, we estimated the mean sleep-quality rating, and computed a confidence interval, using the formula below.  \n\n$$\n\\begin{align}\n\\text{95\\% CI: }& \\bar x \\pm 1.96 \\times SE \\\\\n\\end{align}\n$$\n\nCan you use R to show where the 1.96 comes from?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n`qnorm`!  (see the end of [03A #uncertainty-due-to-sampling](03a_inference.html#uncertainty-due-to-sampling){target=\"_blank\"})\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\nThe 1.96 comes from 95% of the normal distribution falling within 1.96 standard deviations of the mean:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqnorm(c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.959964  1.959964\n```\n\n\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\nAs we learned in [3B #t-distributions](03b_inference2.html#t---distributions){target=\"_blank\"}, the sampling distribution of a statistic has heavier tails the smaller the size of the sample it is derived from. In practice, we are better using $t$-distributions to construct confidence intervals and perform statistical tests.  \n\nThe code below creates a dataframe that contains the number of books read by 7 people in 2024.    \n(Note `tibble` is just a tidyverse version of `data.frame`):  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbookdata <- \n  tibble(\n    person = c(\"Martin\",\"Umberto\",\"Monica\",\"Emma\",\"Josiah\",\"Dan\",\"Aja\"),\n    books_read = c(12,19,9,11,8,28,13)\n  )\n```\n:::\n\n\n\n\nCalculate the mean number of books read in 2024, and construct an appropriate 95% confidence interval.   \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\nHere is our estimated average number of books read:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(bookdata$books_read)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.28571\n```\n\n\n:::\n:::\n\n\n\n\nAnd our standard error is still $\\frac{s}{\\sqrt{n}}$:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsd(bookdata$books_read)/sqrt(nrow(bookdata))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.652171\n```\n\n\n:::\n:::\n\n\n\n\nWith $n = 7$ observations, and estimating 1 mean, we are left with $6$ degrees of freedom.  \nFor our 95% confidence interval, the $t^*$ in the formula below is obtained via:^[(Why 97.5? and not 95? We want the _middle_ 95%, and $t$-distributions are symmetric, so we want to split that 5% in half, so that 2.5% is on either side. We could have also used `qt(0.025, df = 6)`, which will just give us the same number but negative: -2.4469119)]  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqt(0.975, df = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.446912\n```\n\n\n:::\n:::\n\n\n\n\nOur confidence interval is therefore:  \n$$\n\\begin{align}\n\\text{CI} &= \\bar{x} \\pm t^* \\times SE \\\\\n\\text{95\\% CI} &= 14.286 \\pm 2.447 \\times 2.652 \\\\\n\\text{95\\% CI} &= [7.80,\\, 20.78] \\\\\n\\end{align}\n$$\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nWill a 90% confidence interval be wider or narrow?  \nCalculate it and see.  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nA 90% confidence interval will be narrower:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqt(0.95, df = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.94318\n```\n\n\n:::\n:::\n\n\n\n\n$$\n\\begin{align}\n\\text{CI} &= \\bar{x} \\pm t^* \\times SE \\\\\n\\text{90\\% CI} &= 14.286 \\pm 1.943 \\times 2.652 \\\\\n\\text{90\\% CI} &= [9.13,\\, 19.44] \\\\\n\\end{align}\n$$\n\nThe intuition behind this is that our level of confidence is inversely related to the width of the interval.   \n\nTake it to the extremes:  \n\n- I have 100% confidence that the interval $[-Infinity, +Infinity]$ contains the true population mean. \n- If I want an narrower interval, then I have to sacrifice confidence. e.g. a 10% CI: $[13.94, 14.63]$\n\nImagine playing a game of [ringtoss](https://en.wikipedia.org/wiki/Ring_toss){target=\"_blank\"}. A person throwing a 2-meter diameter hoop will have much more confidence that they are going to get it over the pole than a person throwing a 10cm diameter ring.  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Procrastination Scores\n\n:::frame\n> __Research Question__\n> Do Edinburgh University students report endorsing procrastination less than the norm?  \n\nThe Procrastination Assessment Scale for Students (PASS) was designed to assess how individuals approach decision situations, specifically the tendency of individuals to postpone decisions (see [Solomon & Rothblum, 1984](http://dx.doi.org/10.1037/0022-0167.31.4.503)). The PASS assesses the prevalence of procrastination in six areas: writing a paper; studying for an exam; keeping up with reading; administrative tasks; attending meetings; and performing general tasks. For a measure of total endorsement of procrastination, responses to 18 questions (each measured on a 1-5 scale) are summed together, providing a single score for each participant (range 0 to 90). The mean score from Solomon & Rothblum, 1984 was 33.  \n\nA student administers the PASS to 20 students from Edinburgh University.  \nThe data are available at [https://uoepsy.github.io/data/pass_scores.csv](https://uoepsy.github.io/data/pass_scores.csv).  \n:::\n\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\n\n1. Read in the data\n2. Calculate some relevant descriptive statistics\n3. Check the assumptions that we will be concerned with for a one-sample test of whether the mean PASS scores is less than 33. \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- What counts as \"relevant statistics\"? Think about the question. It concerns just one variable (the PASS scores), which is numeric. What's a nice way of describing the center and spread of such a variable?  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n::::panelset\n:::panel\n#### Data\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npass_scores <- read_csv(\"https://uoepsy.github.io/data/pass_scores.csv\") \ndim(pass_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20  3\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(pass_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  sid   school       PASS\n  <chr> <chr>       <dbl>\n1 s_1   GeoSciences    31\n2 s_2   ECA            24\n3 s_3   LAW            32\n4 s_4   ECA            40\n5 s_5   LAW            28\n6 s_6   SSPS           31\n```\n\n\n:::\n:::\n\n\n\n\n:::\n:::panel\n#### Descriptives\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npass_scores |>\n  summarise(\n    mPASS = mean(PASS),\n    sdPASS = sd(PASS),\n    n = n()\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mPASS sdPASS     n\n  <dbl>  <dbl> <int>\n1  30.7   3.31    20\n```\n\n\n:::\n:::\n\n\n\n\n:::\n:::panel\n#### Assumptions\n\nWe want to check that the data are close to normally distributed. This is especially relevant as we have only 20 datapoints here. The plot below makes it look like we may have one or two data points in the tails of the distribution that are further than we might expect. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(pass_scores, aes(sample = PASS)) + \n  geom_qq() + \n  geom_qq_line()\n```\n\n::: {.cell-output-display}\n![](03_ex_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nBut the Shapiro-Wilk test of $p > .05$ indicates that we are probably okay to continue with our t-test  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nshapiro.test(pass_scores$PASS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  pass_scores$PASS\nW = 0.93617, p-value = 0.2028\n```\n\n\n:::\n:::\n\n\n\n\n:::\n::::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\nOur test here is going to be have the following hypotheses:  \n\n- __Null:__ mean PASS score in Edinburgh Uni students is $\\geq 33$\n- __Alternative:__ mean PASS score in Edinburgh Uni students is $< 33$ \n\n_Manually_ calculate the relevant test statistic.  \n_Note, we're doing this manually right now as it's a useful learning process. In later questions we will switch to the easy way!_  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \n\n- you can see the step-by-step calculation of a one sample t-test in [3B #one-sample-t-test](03b_inference2.html#one-sample-t-test){target=\"_blank\"}. \n- The relevant formula is:  \n$$\n\\begin{align}\n& t =  \\frac{\\bar x - \\mu_0}{\\frac{s}{\\sqrt{n}}} \\\\\n\\qquad \\\\\n& \\text{Where:} \\\\\n& \\bar x : \\text{mean of PASS in our sample} \\\\\n& \\mu_0 : \\text{hypothesised mean score of 33} \\\\\n& s : \\text{standard deviation of PASS in our sample} \\\\\n& n : \\text{number of observations}\n\\end{align}\n$$\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npass_scores <- read_csv(\"https://uoepsy.github.io/data/pass_scores.csv\") \n\npass_scores |> \n  summarise(\n    xbar = mean(PASS),\n    s = sd(PASS),\n    n = n(),\n    t = (xbar - 33)/(s / sqrt(n))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n   xbar     s     n     t\n  <dbl> <dbl> <int> <dbl>\n1  30.7  3.31    20 -3.11\n```\n\n\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\nUsing the test statistic calculated in question 1, compute the p-value.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \n\n- this will be needing the `pt()` function.\n- the degrees of freedom is $n-1$ (we used one up by estimating the mean).\n- The test we are performing is against the null hypothesis that the mean is $\\geq 33$. Our t-statistic is in the broad sense calculated as \"mean minus 33\", so negative numbers mean we have a mean lower than 33. These are the instances that we will reject the null hypothesis - if we get a test statistic very low. So we want the lower.tail of the distribution for our p-value.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\nWe have 20 participants, so $df=19$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npt(-3.107272, df = 19, lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.002900159\n```\n\n\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\nNow using the `t.test()` function, conduct the same test. Check that the numbers match with your step-by-step calculations in the previous two questions.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \nCheck out the help page for `t.test()` - there is an argument in the function that allows us to easily change between whether our alternative hypothesis is \"less than\", \"greater than\" or \"not equal to\".  \n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(pass_scores$PASS, mu = 33, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  pass_scores$PASS\nt = -3.1073, df = 19, p-value = 0.0029\nalternative hypothesis: true mean is less than 33\n95 percent confidence interval:\n    -Inf 31.9799\nsample estimates:\nmean of x \n     30.7 \n```\n\n\n:::\n:::\n\n\n\nThe $t$ statistic, our $df$, and our $p$-value all match the calculations from the previous questions.  \n\nThe simple `t.test()` approach even gives us a confidence interval! Well.. half of one! This is because we conducted a one-sided test. Remember that null hypothesis significance testing is like asking \"does our confidence interval contain zero?\". With a one-sided test we only reject the null hypothesis if the test statistic is large in _one_ direction, and so our confidence interval is one-sided also.  \n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\nCreate a visualisation to illustrate the results.  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = pass_scores, aes(x=PASS)) + \n  geom_boxplot() + \n  geom_vline(xintercept=33, lty=\"dashed\", col=\"red\")\n```\n\n::: {.cell-output-display}\n![Distribution of scores on the Procrastination Assessment Scale for Students (PASS) measure. The majority of the sample scored below the suggested normal score of 33 (red dashed line).](03_ex_files/figure-html/fig-passfig-1.png){#fig-passfig fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\nWrite up the results.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \nThere are some quick example write-ups for each test in [3B #basic-tests](03b_inference2.html#basic-tests){target=\"_blank\"}\n:::\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n\n\n\n\n:::int\nA one-sided one-sample t-test was conducted in order to determine if the average score on the Procrastination Assessment Scale for Students (PASS) for a sample of 20 students at Edinburgh University was significantly lower ($\\alpha = .05$) than the average score of 33 obtained during development of the PASS. \n\nEdinburgh University students scored lower (Mean = 30.7, SD = 3.31) than the score reported by the authors of the PASS (Mean = 33). This difference was statistically significant ($t(19)=-3.11$, $p < .05$, one-tailed).  \n:::\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Heights \n\n> __Research Question__\n>  Is the average height of University of Edinburgh Psychology students different from 165cm?  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/hypothesis/playmo_tms.jpg){fig-align='center' width=30%}\n:::\n:::\n\n\n\n\n:::frame\n__Data: Past Surveys__  \nIn the last few years, we have asked students of the statistics courses in the Psychology department to fill out a little survey.  \nAnonymised data are available at [https://uoepsy.github.io/data/surveydata_historical.csv](https://uoepsy.github.io/data/surveydata_historical.csv).  \n\n__Note:__ this does _not_ contain the responses from this year. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurveydata <- \n  read_csv(\"https://uoepsy.github.io/data/surveydata_historical.csv\")\n```\n:::\n\n\n\n:::\n\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\nNo more manual calculations of test statistics and p-values for this week.  \n\nConduct a one sample $t$-test to evaluate whether the average height of UoE psychology students in the last few years was different from 165cm.  \n\nMake sure to consider the assumptions of the test! \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \n\n- This is *real data*, and [real data is rarely normal](https://web.archive.org/web/20200927033407/https://dpananos.github.io/posts/2019/08/blog-post-23/)! If you conduct a Shapiro-Wilk test, you may well find $p<.05$ and conclude that your data is not normal.   \nSo what do we do if a test indicates our assumptions are violated?  \nWell, we should bear a couple of things in mind.  \n    1. A decision rule such as $p<.05$ on Shapiro-Wilk test creates very dichotomous thinking for something which is in reality not black and white. Real life distributions are not *either* normal *or* non-normal. Plot the data, and make a judgement!  \n    2. As it happens, the t-test is actually reasonably robust against slight deviations from normality, especially if the sample size is \"large enough\" (rule-of-thumb n = 30) and the data are not heavily skewed. Plot your data and make a judgement!  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The deeper you get into statistics, the more you discover that it is not simply a case of following step-by-step rules.](images/hypothesis/guidelines.gif){#fig-rules fig-align='center' width=80%}\n:::\n:::\n\n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n::::panelset\n:::panel\n#### Data\n\nWe'll read in our data and check the dimensions and variable names\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurveydata <- read_csv(\"https://uoepsy.github.io/data/surveydata_historical.csv\")\n\ndim(surveydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 548  24\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(surveydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"birthmonth\"        \"height\"            \"eyecolour\"        \n [4] \"catdog\"            \"threewords\"        \"year\"             \n [7] \"course\"            \"in_uk\"             \"gender\"           \n[10] \"optimism\"          \"spirituality\"      \"ampm\"             \n[13] \"sleeprating\"       \"extraversion\"      \"agreeableness\"    \n[16] \"conscientiousness\" \"emot_stability\"    \"imagination\"      \n[19] \"loc\"               \"phone_unlocks\"     \"caffeine\"         \n[22] \"caffeine_type\"     \"procrastination\"   \"multitasking\"     \n```\n\n\n:::\n:::\n\n\n\n\n:::\n:::panel\n#### Descriptives\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurveydata |> \n  summarise(\n    mheight = mean(height, na.rm = T),\n    sdheight = sd(height, na.rm = T),\n    n = sum(!is.na(height))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mheight sdheight     n\n    <dbl>    <dbl> <int>\n1    168.     8.27   537\n```\n\n\n:::\n:::\n\n\n\n:::\n:::panel\n#### Assumptions\n\nThe `shapiro.test()` suggests that our assumption of normality is not okay!  \n(the p-value is $<.05$, suggesting that we reject the hypothesis that the data are drawn from a normally distributed population)  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nshapiro.test(surveydata$height)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  surveydata$height\nW = 0.99063, p-value = 0.001731\n```\n\n\n:::\n:::\n\n\n\n\nHowever, as always, __visualisations are vital__ here. The histogram below doesn't look all that great, but the t.test is quite robust against slight violations of normality, especially as sample sizes increase beyond 30, and our data here actually looks fairly normal (this is a judgement call here - over time you will start to get a sense of what you might deem worrisome in these plots!).  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = surveydata, aes(x = height)) + \n  geom_histogram() +\n  # adding our hypothesised mean\n  geom_vline(xintercept = 165) \n```\n\n::: {.cell-output-display}\n![](03_ex_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nWe can also take a quick look at the QQplot. The points follow the line closely apart from at the tail ends, matching the heavier tails of the distribution that are visible in the histogram above. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqqnorm(surveydata$height)\nqqline(surveydata$height)\n```\n\n::: {.cell-output-display}\n![](03_ex_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nThe data are not very skewed, and together with the fact that we are working with a sample of 537, i feel fairly satisfied that the $t$-test will lead us to valid inferences.  \n\n:::\n:::panel\n#### t-test\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(surveydata$height, mu = 165, alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  surveydata$height\nt = 7.7102, df = 536, p-value = 6.146e-14\nalternative hypothesis: true mean is not equal to 165\n95 percent confidence interval:\n 167.0508 168.4531\nsample estimates:\nmean of x \n 167.7519 \n```\n\n\n:::\n:::\n\n\n\n\n:::\n::::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Names and Tips  \n\n:::frame\n> __Research Question__\n> Can a server earn higher tips simply by introducing themselves by name when greeting customers?\n\nResearchers investigated the effect of a server introducing herself by name on restaurant tipping.\nThe study involved forty, 2-person parties eating a \\$23.21 fixed-price buffet Sunday brunch at Charley Brown's Restaurant in Huntington Beach, California, on April 10 and 17, 1988.  \n\nEach two-person party was randomly assigned by the waitress to either a name or a no-name condition. The total amount paid by each party at the end of their meal was then recorded.  \n  \nThe data are available at [https://uoepsy.github.io/data/gerritysim.csv](https://uoepsy.github.io/data/gerritysim.csv). (This is a simulated example based on [Garrity and Degelman (1990)](https://doi.org/10.1111/j.1559-1816.1990.tb00405.x))  \n:::\n\n\n\n<div class='question-begin'>Question 11</div><div class='question-body'>\n\n\nConduct an independent samples $t$-test to assess whether higher tips were earned when the server introduced themselves by name, in comparison to when they did not.    \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \n\n- There is a direction in the research question stated above, which means we will want to set `alternative = ??`.  \n- We'll want to check the normality (either visually or with a test) of the variable of interest _for each group_.  \n- Some researchers suggest using the Welch t-test by default. This means you can relax the assumption of equal variances in the groups. If you want to _test_ whether two variances are equal, try the `var.test()` function.\n\n:::\n\n\n</div><p class=\"question-end\"></p>\n\n  \n\n\n\n<div style=\"display:none;\">\n\n\n\n::::panelset\n:::panel\n#### Data\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntipdata <- read_csv(\"https://uoepsy.github.io/data/gerritysim.csv\")\ndim(tipdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 40  3\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(tipdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n   paid condition party\n  <dbl> <chr>     <dbl>\n1  28.5 name          1\n2  27   no name       2\n3  24.1 no name       3\n4  28   name          4\n5  30   name          5\n6  27.5 name          6\n```\n\n\n:::\n:::\n\n\n\n\nIt might be nice to conduct our analysis on just the _tip_ given, and not the \\$23.21 meal price + tip.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#make a \"tip\" column, which is minus the meal amount\ntipdata <- \n  tipdata |> mutate(\n    tip = paid - 23.21\n  )\n```\n:::\n\n\n\n\n:::\n:::panel\n#### Descriptives\n  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntipdata |> \n  group_by(condition) |>\n  summarise(\n    meantip = mean(tip),\n    sdtip = sd(tip)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  condition meantip sdtip\n  <chr>       <dbl> <dbl>\n1 name         4.94  1.88\n2 no name      3.18  1.35\n```\n\n\n:::\n:::\n\n\n\n\n:::\n:::panel\n#### Plot\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = tipdata, aes(x = tip, y = condition)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](03_ex_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n:::\n:::panel\n#### Assumptions  \n\nAccording to these tests, we have normally distributed data for both groups, with equal variances. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nshapiro.test(tipdata$tip[tipdata$condition==\"name\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  tipdata$tip[tipdata$condition == \"name\"]\nW = 0.96267, p-value = 0.5985\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(tipdata$tip[tipdata$condition==\"no name\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  tipdata$tip[tipdata$condition == \"no name\"]\nW = 0.94405, p-value = 0.2857\n```\n\n\n:::\n\n```{.r .cell-code}\nvar.test(tip ~ condition, data = tipdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  tip by condition\nF = 1.9344, num df = 19, denom df = 19, p-value = 0.1595\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.7656473 4.8870918\nsample estimates:\nratio of variances \n           1.93437 \n```\n\n\n:::\n:::\n\n\n\n\n:::\n:::panel\n#### t-test  \n\nBecause the variances do not appear to be unequal, we can actually use the standard t-test with `var.equal = TRUE` if we want. However, we'll continue with the Welch t-test. \n\nRemember that our alternative hypothesis here is that the average tips in the \"name\" condition is greater than in the \"no name\" condition.  \nR will take the levels in order here (alphabetically), and assume that the alternative is for that group, so we use `alternative = \"greater\"` here to say that the alternative is $\\text{name}-\\text{no name} > 0$.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(tip ~ condition, data = tipdata, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  tip by condition\nt = 3.4117, df = 34.502, p-value = 0.0008314\nalternative hypothesis: true difference in means between group name and group no name is greater than 0\n95 percent confidence interval:\n 0.8893105       Inf\nsample estimates:\n   mean in group name mean in group no name \n               4.9450                3.1825 \n```\n\n\n:::\n:::\n\n\n\n\n:::\n::::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Optional Extras\n\nHere are a few extra questions for you to practice performing tests and making plots:  \n\n\n\n<div class='question-begin'>Optional Extra 1</div><div class='question-body'>\n\n\n\nAre dogs heavier on average than cats?  \nData from Week 1: [https://uoepsy.github.io/data/pets_seattle.csv](https://uoepsy.github.io/data/pets_seattle.csv)  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \n  \n- Remember from week 1 - not everything in that data is either a cat or a dog!  \n\n:::\n  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npets <- read.csv(\"https://uoepsy.github.io/data/pets_seattle.csv\")\ncatsndogs <- pets[pets$species != \"Goat\", ]\n```\n:::\n\n\n\n\nIn this case, we want to test whether $dogs > cats$. What we are testing then, whether $dogs - cats > 0$ or $cats - dogs < 0$.  \nBy default, as the `species` variable is a character, it will use alphabetical ordering, and `t.test()` will test $cats - dogs$. So we want our alternative hypothesis to be \"less\":  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(weight_kg ~ species, catsndogs,\n       alternative = \"less\")\n```\n:::\n\n\n\n\nAn alternative is to set it as a factor, and specify the levels in the order we want:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncatsndogs$species2 <- factor(catsndogs$species, levels = c(\"Dog\",\"Cat\"))\n```\n:::\n\n\n\nWhich would then allow us to shove that into the `t.test()` and perform the same test, but using $dogs - cats$ instead. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(weight_kg ~ species2, catsndogs,\n       alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  weight_kg by species2\nt = 92.4, df = 1335.2, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Dog and group Cat is greater than 0\n95 percent confidence interval:\n 15.60965      Inf\nsample estimates:\nmean in group Dog mean in group Cat \n        20.377489          4.484731 \n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncatsndogs |>\n  ggplot(aes(x=species,y=weight_kg)) + \n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](03_ex_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Optional Extra 2</div><div class='question-body'>\n\n\nIs taking part in a cognitive behavioural therapy (CBT) based programme associated with a greater reduction, on average, in anxiety scores in comparison to a Control group?  \nData are at [https://uoepsy.github.io/data/cbtanx.csv](https://uoepsy.github.io/data/cbtanx.csv). The dataset contains information on each person in an organisation, recording their professional role (management vs employee), whether they are allocated into the CBT programme or not (control vs cbt), and scores on anxiety at both the start and the end of the study period.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \n\n- you might have to make a new variable in order to test the research question. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nBecause we're testing the _reduction_ in anxiety, we need to calculate it. By subtracting anxiety at time 2 from anxiety at time 1, we create a variable for which bigger values represent more reduction in anxiety  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncbtanx <- read.csv(\"https://uoepsy.github.io/data/cbtanx.csv\")\n\ncbtanx <- cbtanx |> mutate(reduction = anx_t1 - anx_t2)\n```\n:::\n\n\n\n\nAnd we can then test whether $cbt - control > 0$:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(reduction ~ cbt, data = cbtanx, \n       alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  reduction by cbt\nt = 2.5953, df = 56.621, p-value = 0.006007\nalternative hypothesis: true difference in means between group cbt and group control is greater than 0\n95 percent confidence interval:\n 0.2744051       Inf\nsample estimates:\n    mean in group cbt mean in group control \n            1.0266667             0.2551724 \n```\n\n\n:::\n:::\n\n\n\nAnd to make sure we're getting things the right way around, make a plot:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(cbtanx, aes(x=cbt, y=reduction))+\n  geom_boxplot() + \n  labs(x=\"Experimental Group\",y=\"Reduction in Anxiety across study\")\n```\n\n::: {.cell-output-display}\n![](03_ex_files/figure-html/unnamed-chunk-39-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Optional Extra 3</div><div class='question-body'>\n\n\n\nAre students on our postgraduate courses shorter/taller than those on our undergraduate courses?  \nWe can again use the data from the past surveys: [https://uoepsy.github.io/data/surveydata_historical.csv](https://uoepsy.github.io/data/surveydata_historical.csv).  \n\n\"USMR\" is our only postgraduate course.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints  \n  \n- You'll need to create a variable that identifies whether a respondent is from a postgrad or and undergrad course.  \n\n:::\n  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurveydata <- read_csv(\"https://uoepsy.github.io/data/surveydata_historical.csv\")\nsurveydata <- surveydata |>\n  mutate(\n    isPG = course==\"usmr\"\n  )\ntable(surveydata$isPG)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n  240   308 \n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(height ~ isPG, data = surveydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  height by isPG\nt = -0.37785, df = 526.56, p-value = 0.7057\nalternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0\n95 percent confidence interval:\n -1.657337  1.122632\nsample estimates:\nmean in group FALSE  mean in group TRUE \n           167.6006            167.8679 \n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(surveydata, aes(x = isPG, y = height)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](03_ex_files/figure-html/unnamed-chunk-42-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n",
    "supporting": [
      "03_ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}