<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - 3A: Foundations of Inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('jk-circle-right')) {
    f.classList.add('jk-circle-down')
    f.classList.remove('jk-circle-right')
} else {
    f.classList.add('jk-circle-right')
    f.classList.remove('jk-circle-down')
}
}
</script>

<!---<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>-->
<link href="site_libs/panelset-0.3.0/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.3.0/panelset.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03a_inference.html">Week 3</a></li><li class="breadcrumb-item"><a href="./03a_inference.html">3A: Foundations of Inference</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">USMR</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Week 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01a_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1A: A first look at R &amp; RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01b_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1B: More R - Basic Data Skills</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Intro R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Week 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A: Measurement &amp; Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B: Curves &amp; Sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Week 3</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a_inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">3A: Foundations of Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b_inference2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3B: Practical Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: T-tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Week 4</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04a_chisq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4A: Binomial &amp; Chi-Square Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b_revisitnhst.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4B: Revisiting NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Binomial &amp; Chi-Square Tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Week 5</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05a_covcor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5A: Covariance and Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5B: Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Covariance, Correlation &amp; Linear Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Week 6</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_wt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">WalkThrough: Advanced Data Wrangling</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">Week 7</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07a_mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7A: Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07b_assumptdiag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Multiple Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
 <span class="menu-text">Week 8</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08a_scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8A: Centering and Scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08b_catpred.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8B: Categorical Predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Scaling | Categorical Predictors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">
 <span class="menu-text">Week 9</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09a_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9A: Interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Interactions!</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false">
 <span class="menu-text">Week 10</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10a_glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10A: The Generalized Linear Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: GLM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#uncertainty-due-to-sampling" id="toc-uncertainty-due-to-sampling" class="nav-link active" data-scroll-target="#uncertainty-due-to-sampling">Uncertainty due to sampling</a></li>
  <li><a href="#null-hypothesis-significance-testing-nhst" id="toc-null-hypothesis-significance-testing-nhst" class="nav-link" data-scroll-target="#null-hypothesis-significance-testing-nhst">Null Hypothesis Significance Testing (NHST)</a>
  <ul class="collapse">
  <li><a href="#test-statistics-p-values" id="toc-test-statistics-p-values" class="nav-link" data-scroll-target="#test-statistics-p-values">Test-statistics &amp; p-values</a></li>
  <li><a href="#making-decisions" id="toc-making-decisions" class="nav-link" data-scroll-target="#making-decisions">Making Decisions</a></li>
  <li><a href="#making-mistakes" id="toc-making-mistakes" class="nav-link" data-scroll-target="#making-mistakes">Making Mistakes</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">3A: Foundations of Inference</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="lo">
<p>This reading:</p>
<ul>
<li>How do we quantify uncertainty due to sampling?<br>
</li>
<li>How can we make decisions (what to believe/how to act, etc) that take uncertainty into account?<br>
</li>
<li>How likely are we to make the wrong decision?</li>
</ul>
</div>
<p>We use statistics primarily to estimate parameters in a population. Whether we are polling people to make predictions about the proportion of people who will vote for a certain party in the next election, or conducting a medical trial and assessing the change in blood pressure for patients given drug X vs those given a placebo in order to decide whether to put the drug into circulation in health service.</p>
<p>We have seen this already last week: We <em>observed</em> a sample of peoples’ life satisfaction ratings (scale 0-100), and we wanted to use these to make some statement about the wider population, such as “the average life-satisfaction rating is ?? out of 100”. So we use the mean of our sample, as an <em>estimate</em> of the mean of the population.</p>
<section id="uncertainty-due-to-sampling" class="level1">
<h1>Uncertainty due to sampling</h1>
<p>A sample estimate is not going to be spot-on. By taking measurements on only a subset of the population that we are interested in, we introduce sampling variability - we have uncertainty in the accuracy of our estimate. We saw <a href="02b_sampling.html">previously (2B)</a> how to make a <strong>confidence interval</strong> as a means of capturing this uncertainty, providing a range of plausible values.</p>
<p>Let’s look at this with a different example.</p>
<div class="frame">
<p><strong>Stroop Data</strong></p>
<p>The data we are going to use here come from an experiment using one of the best known tasks in psychology, the “Stroop task”.</p>
<p>In our dataset, we have information from 131 participants who completed an online task in which they saw two sets of coloured words. Participants spoke out loud the colour of each word, and timed how long it took to complete each set. In the one set of words, the words <em>matched</em> the colours they were presented in (e.g., word “blue” was coloured blue). In the other set of words, the words <em>mismatched</em> the colours (e.g., the word “blue” was coloured red (see <a href="#fig-stroop1">Figure&nbsp;1</a>). The order of matching/mismatching sets was randomly allocated for each participant. Participants’ recorded their times for each set (<em>matching</em> and <em>mismatching</em>).<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>The data are available at <a href="https://uoepsy.github.io/data/stroop.csv">https://uoepsy.github.io/data/stroop.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-stroop1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/numeric/stroop1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Stroop Task - Color word interference. Images from https://faculty.washington.edu/chudler/java/ready.html</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>First, we read in the data and take a look at it. We should note how many rows (130), how many columns (4), and so on.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>stroopdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/stroop.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stroopdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
     id   age matching mismatching
  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;
1     1    41     22.3        16.9
2     2    24     22.3        19.1
3     3    40     15.4        13.6
4     4    46      9.9        15.0
5     5    36     14.2        16.4
6     6    29     19.9        18.0</code></pre>
</div>
</div>
<p>What we are interested in is the differences between the matching and mismatching times. For someone who took 10 seconds for the matching set, and 30 seconds for the mismatching set, we want to record their score as a difference of 20 seconds.</p>
<p>So we can add this as a new variable to our data:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>stroopdata <span class="ot">&lt;-</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  stroopdata <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff =</span> mismatching <span class="sc">-</span> matching</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stroopdata) <span class="co"># take a look to check it works</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
     id   age matching mismatching  diff
  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;
1     1    41     22.3        16.9 -5.4 
2     2    24     22.3        19.1 -3.2 
3     3    40     15.4        13.6 -1.81
4     4    46      9.9        15.0  5.14
5     5    36     14.2        16.4  2.18
6     6    29     19.9        18.0 -1.90</code></pre>
</div>
</div>
<p>What we’re interested in is the distribution of these difference-scores. Are people, on average, <em>slower</em>? This would correspond to a positive value of the <code>diff</code> variable. Let’s get some summary statistics and a visualisation of out observed distribution.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># mean(stroopdata$diff) and sd(stroopdata$diff) work just as well</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>stroopdata <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">meandiff =</span> <span class="fu">mean</span>(diff),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sddiff =</span> <span class="fu">sd</span>(diff)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  meandiff sddiff
     &lt;dbl&gt;  &lt;dbl&gt;
1     2.40   5.02</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(stroopdata, <span class="fu">aes</span>(<span class="at">x =</span> diff)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03a_inference_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>What we’re really interested in talking about is the average ‘mismatching - matching’ score for <strong>everybody</strong>, not just our sample of 131. But we only have those 131 people, so we’ll have to make do and use their data to provide us with an <strong>estimate</strong>.</p>
<p>Our <strong>estimate</strong> is that people are 2.4 seconds slower, on average, when reading mismatched colour words than reading matched colour words.</p>
<p>Remember that there are many many different samples of <span class="math inline">\(n=131\)</span> that we <em>might have</em> taken. And if we had taken a different sample, then our mean ‘mismatching - matching’ score (the <code>mean(stroopdata$diff)</code> value) would be different.</p>
<p>Previously we learned about how the distribution of all possible sample means we <em>might</em> take is known as a <strong>sampling distribution</strong>. We also learned that these tend to be normally distributed (regardless of the underlying population distribution) and so we can use the standard deviation of the sampling distribution (known as the <strong>standard error</strong>) to quantify the variation due to sampling.</p>
<p>To actually get at the standard error, one of our options is to simulate the act of ‘taking many samples of size <span class="math inline">\(n\)</span>’ by taking lots of samples <em>with replacement</em> from our original sample (this is known as “bootstrapping”).</p>
<p>As our analyses become more advanced, then this will become more complex. In this example, because we are just interested in estimating a single mean value, we can use <code>replicate</code> to do calculate the means from 1000 resamples from our original sample. We can then simply calculate the standard deviation of all these means:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>stroop_bootstrapdist <span class="ot">&lt;-</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">mean</span>(<span class="fu">sample</span>(stroopdata<span class="sc">$</span>diff, <span class="at">size =</span> <span class="dv">131</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(stroop_bootstrapdist)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4503147</code></pre>
</div>
</div>
<p>Alternatively (and more conventionally), we use a formula of <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span>, which we can calculate much more easily.<br>
The symbol “<span class="math inline">\(\sigma\)</span>” is the standard deviation of the population, but we are going to approximate this with “<span class="math inline">\(s\)</span>”, the standard deviation of our sample. The “<span class="math inline">\(n\)</span>” is the size of our sample:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>stroopdata <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">s =</span> <span class="fu">sd</span>(diff), <span class="co"># standard deviation of sample</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(), <span class="co"># number of sample</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">SE =</span> s<span class="sc">/</span><span class="fu">sqrt</span>(n) <span class="co"># standard error of mean</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
      s     n    SE
  &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;
1  5.02   131 0.438</code></pre>
</div>
</div>
<p>What the standard error gives us is an idea of how much uncertainty there is going to be in our estimated mean from our sample of this size:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sampdist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03a_inference_files/figure-html/fig-sampdist-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Sampling distribution for mean of sample size 131, with SE = 5.01 / sqrt(131) = 0.44</figcaption>
</figure>
</div>
</div>
</div>
<p>This enables us to, for instance, construct a range of plausible values for our estimated ‘mismatching - matching’ score. The range is centered around our <strong>point estimate</strong> (the mean score in our sample), and we widen it to include X% of the possible means we might also see from a sample of the same size. This is achieved by multiplying the standard error by a value that corresponds to our confidence level.</p>
<p><span class="math display">\[
\begin{align}
\text{95\% CI} &amp; \qquad = \bar{x} \pm 1.96 \times SE &amp; \\
&amp; \qquad = 2.40 \pm 1.96 \times 0.438 \\
&amp; \qquad = 2.40 \pm 0.858 \\
&amp; \qquad = [1.542, 3.258] \\
\end{align}
\]</span> The 1.96 used here comes from our rules-of-thumb about the normal distribution (see <a href="02b_sampling.html#normal-distributions" target="_blank">2B #normal-distributions</a>): 95% of the data fall within 1.96 standard deviations of the mean:<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.959964  1.959964</code></pre>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="null-hypothesis-significance-testing-nhst" class="level1">
<h1>Null Hypothesis Significance Testing (NHST)</h1>
<p>Let’s suppose we are interested in asking a question.</p>
<blockquote class="blockquote">
<p><strong>is there</strong> an effect of the mismatching/matching colour-words?</p>
</blockquote>
<p>Our objective here has changed slightly: rather than being concerned with parameter estimation (“what is the estimated score”), our question is now about making a statement about two competing hypotheses:</p>
<ul>
<li><span class="math inline">\(H_0 \,\, (\text{The Null Hypothesis}):\)</span> There is <em>no</em> difference between matching and mismatching conditions.</li>
<li><span class="math inline">\(H_1 \,\, (\text{The Alternative Hypothesis}):\)</span> There is <em>some</em> difference between matching and mismatching conditions.</li>
</ul>
<p>If we use <span class="math inline">\(\mu\)</span> to denote the average ‘mismatching - matching’ score <em>in the population</em>, then we can state these as:</p>
<ul>
<li><span class="math inline">\(H_0: \mu = 0\)</span>.<br>
</li>
<li><span class="math inline">\(H_1: \mu \neq 0\)</span>.</li>
</ul>
<p>With the confidence interval that we have created above, we can already make a statement about these. Our 95% CI does not contain zero, meaning that we can, with that same level of confidence, reject <span class="math inline">\(H_0\)</span>.</p>
<p>However, there are instances where it is not feasible for us to create a confidence interval.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> This is where the other primary tool for null hypothesis significance testing comes in, the p-value.</p>
<section id="test-statistics-p-values" class="level2">
<h2 class="anchored" data-anchor-id="test-statistics-p-values">Test-statistics &amp; p-values</h2>
<p>The p-value is a formal way of testing a statistic against a null hypothesis. To introduce the p-value, instead of thinking first about what we <em>have</em> observed in our sample, we need to think about what we would expect to observe <em>if our null hypothesis is true.</em></p>
<p>With our Stroop Task example, our null hypothesis is that there is no difference between matching and mismatching conditions (<span class="math inline">\(H_0: \mu = 0\)</span>). Under <span class="math inline">\(H_0\)</span>, the average ‘mismatching-matching’ score in the population is zero, and we would expect most of the samples we <em>might</em> take to have a mean score of close to this (not <em>exactly</em> 0, but centered around 0). We saw above that we could express the sampling distribution of means taken from samples of size <span class="math inline">\(n=131\)</span> using the <strong>standard error</strong>. Under <span class="math inline">\(H_0\)</span> we would expect the samples of <span class="math inline">\(n=131\)</span> we <em>might</em> take to have means that follow something like the distribution in <a href="#fig-hyp">Figure&nbsp;3</a>. We can think of this as the sampling distribution of <span class="math inline">\(\bar{x}\)</span>, but centered on our null hypothesis (in this case, <span class="math inline">\(\mu = 0\)</span>). We call this the ‘null distribution’.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-hyp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03a_inference_files/figure-html/fig-hyp-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Sampling distribution for mean of sample size 131, assuming population mean = 0. Observed sample mean shown in red</figcaption>
</figure>
</div>
</div>
</div>
<div class="statbox">
<p><strong>Test-statistic</strong></p>
<p>The first step now is to create a test-statistic. That is, a statistic that tell us, in some <em>standardised units</em>, how big our observed effect is from the null hypothesis (i.e.&nbsp;in this case, how far from <span class="math inline">\(\mu=0\)</span> our sample mean is).</p>
<p>The straightforward way to do this is to express how far away from <span class="math inline">\(\mu=0\)</span> our sample mean is <em>in terms of standard errors.</em> We’ll call our test statistic <span class="math inline">\(Z\)</span>:</p>
<p><span class="math display">\[
Z = \frac{\text{estimate}-\text{null}}{SE}
\]</span></p>
<p>Our mean and standard error are:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(stroopdata<span class="sc">$</span>diff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.402977</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(stroopdata<span class="sc">$</span>diff) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(stroopdata))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4382302</code></pre>
</div>
</div>
<p>So our test-statistic is <span class="math display">\[
Z = \frac{2.40 - 0}{0.438} = 5.479
\]</span></p>
</div>
<div class="statbox">
<p><strong>p-value</strong></p>
<p>We can now calculate how likely it is to see values <em>at least as extreme</em> as our observed test-statistic, <em>if the null is true</em>.</p>
<p>If the null hypothesis is true (there was no ‘mismatching-matching’ difference) then we would expect Z-statistics to be normally distributed with a mean of 0 and a standard deviation of 1.</p>
<p>We have seen the process of how we might calculate a probability from a distribution like this already: the <code>pnorm()</code> function gives us the area of a distribution to the one side of a given value:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(??, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pnormstroop" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03a_inference_files/figure-html/fig-pnormstroop-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4: pnorm() provides us with a p-value for a z-statistic</figcaption>
</figure>
</div>
</div>
</div>
<p>Remember, our Z-statistic we calculated above is 5.479. If the null hypothesis were true then the probability that we would see a sample (<span class="math inline">\(n=131\)</span>) with a Z-statistic <em>at least</em> that large is:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">5.479</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.138682e-08</code></pre>
</div>
</div>
<p>which is R’s way of printing 0.00000002138682.</p>
<p>There is one last thing, and that the <em>direction</em> of our hypotheses. Recall from earlier that we stated <span class="math inline">\(H_0: \mu = 0\)</span> and <span class="math inline">\(H_1: \mu \neq 0\)</span>. This means that we are interested in the probability of getting results this far away from 0 <em>in either direction.</em><br>
We are interested in both tails:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pnormstroop2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03a_inference_files/figure-html/fig-pnormstroop2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5: 2*pnorm gives the two tails</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="fl">5.479</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.277364e-08</code></pre>
</div>
</div>
<p>or <span class="math inline">\(p =\)</span> 0.00000004277364.</p>
<div class="sticky">
<p><strong>p-value</strong></p>
<p>The p-value is the probability<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> that we observe a test statistic at least as extreme as the one we observed, <em>assuming the null hypothesis <span class="math inline">\(H_0\)</span> to be true</em>.</p>
</div>
</div>
</section>
<section id="making-decisions" class="level2">
<h2 class="anchored" data-anchor-id="making-decisions">Making Decisions</h2>
<p>Now that we have our p-value of 0.00000004277364, we need to use it to make a decision about our hypotheses.</p>
<p>Typically, we pre-specify the probability level at which we will consider results to be so unlikely to have arisen from the null distribution that we will take them as evidence to reject the null hypothesis. This pre-specified level is commonly referred to as <span class="math inline">\(\alpha\)</span> (“alpha”). Setting <span class="math inline">\(\alpha = 0.05\)</span> means that we will reject <span class="math inline">\(H_0\)</span> when we get a result which is extreme enough to only occur 0.05 (5%) of the time or less if the <span class="math inline">\(H_0\)</span> is true.</p>
<p>In our case, 0.00000004277364 <span class="math inline">\(&lt; 0.05\)</span>, so we reject the null hypothesis that there is no difference in the mismatching/matching conditions of the Stroop Task.</p>
<div class="sticky">
<p>There’s a lot of convention to how we talk about NHST, but the typical process is as follows:</p>
<ol type="1">
<li><em>Clearly</em> specify the null and alternative hypotheses.<br>
</li>
<li>Specify <span class="math inline">\(\alpha\)</span></li>
<li>Calculate statistic</li>
<li>Compute p-value
<ul>
<li>If <span class="math inline">\(p&lt;\alpha\)</span>, then reject the null hypothesis.</li>
<li>If <span class="math inline">\(p\geq\alpha\)</span>, then fail to reject* the null hypothesis.</li>
</ul></li>
</ol>
<p>*Note, we don’t “accept” anything, we just “reject” or “fail to reject” the null hypothesis. Think of it like a criminal court, and we are trying the null hypothesis - <span class="math inline">\(H_0\)</span> is “innocent until proven guilty”.</p>
</div>
</section>
<section id="making-mistakes" class="level2">
<h2 class="anchored" data-anchor-id="making-mistakes">Making Mistakes</h2>
<p>Whether our eventual decision is a) reject the null hypothesis, or b) fail to reject the null hypothesis, there’s always a chance that we might be making a mistake. There are actually two different types of mistakes we might make. An often used analogy (<a href="#fig-httrial">Figure&nbsp;6</a>) is the idea of criminal trials in which an innocent person can be wrongfully convicted, or a guilty person can be set free.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-httrial" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/hypothesis/ht-errors-trial.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Making errors in NHST is like a criminal court making errors in its decision on the defendent</figcaption>
</figure>
</div>
</div>
</div>
<p>We can actually quantify the chance that we’re making errors in our different decisions. Thinking back to the definition of a p-value, it is the probability of seeing our results <em>if</em> the null hypothesis is true. If we make a decision to reject the null hypothesis based on whether <span class="math inline">\(p&lt;\alpha\)</span>, then the probability that this decision is a mistake is <span class="math inline">\(\alpha\)</span>.</p>
<p>The probability that we the other sort of error (failing to reject the null hypothesis when the null hypothesis is actually false), we denote with <span class="math inline">\(\beta\)</span>.</p>
<p>Doing statistics is partly a matter of balancing these possibilities. If we used a very low <span class="math inline">\(\alpha\)</span>-level (e.g.&nbsp;we reject when <span class="math inline">\(p&lt;.0001\)</span> rather than <span class="math inline">\(p&lt;.05\)</span>) then we <em>increase</em> the probability of making a type II error.</p>
<div class="sticky">
<p><strong>Types of Errors in NHST</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-httrial2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/hypothesis/ht-errors-table-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7: Probabilities of making different errors in NHST</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="statbox">
<p><strong>Power (<span class="math inline">\(1-\beta\)</span>)</strong></p>
<p>A key notion in conducting studies is “statistical power”. Studies want to increase the probability of correctly rejecting the null hypothesis (i.e.&nbsp;correctly identifying that there <em>is</em> something more than chance going on).</p>
<p>This is the bottom right cell of the tables in <a href="#fig-httrial">Figure&nbsp;6</a> and <a href="#fig-httrial2">Figure&nbsp;7</a>. We know that this will depend on the <span class="math inline">\(\alpha\)</span>-level that we choose, but there are other important factors that influence <span class="math inline">\(1-\beta\)</span>:</p>
<ul>
<li>power increases as sample size increases
<ul>
<li><em>e.g.&nbsp;it’s easier to determine that cats weigh less than dogs if we measure 100 animals vs if we measure only 10 animals</em></li>
</ul></li>
<li>power increases the farther away the true value is from the null hypothesis value
<ul>
<li><em>e.g.&nbsp;it’s easier to determine that cats weigh less than elephants than it is to determine that cats weigh less than dogs</em></li>
</ul></li>
</ul>
</div>
<div class="divider div-transparent div-dot">

</div>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>You can try out the experiment at https://faculty.washington.edu/chudler/java/ready.html<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p> For other intervals, such as a 90% interval, we need to know the point at which 5% is either side of a normal distribution (i.e., giving us the middle 90%). <code>qnorm(c(0.05,0.95))</code> will give us 1.64, which we then put into our construction of the interval: <span class="math inline">\(90\%\, CI = \bar{x} \pm 1.64 \times SE\)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Think about an example where our question is about whether there is a difference in variable <span class="math inline">\(Y\)</span> between groups A, B, C and D. Around what should we construct our interval? Around the difference <span class="math inline">\(\bar{Y}_A - \bar{Y}_B\)</span> (difference between A and B’s average scores on <span class="math inline">\(Y\)</span>), or <span class="math inline">\(\bar{Y}_A - \bar{Y}_C\)</span>, or <span class="math inline">\(\bar{Y}_B - \bar{Y}_D\)</span>?<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>What we have been seeing is that probabilities in NHST are defined as the relative frequency of an event <em>over many trials</em> (as “many” <span class="math inline">\(\to \infty\)</span>). This requires assuming some features of the data generating process which guides what the “many trials” would look like (e.g., that there is no effect). The <span class="math inline">\(p\)</span>-value is the probability of observing results as or more extreme than the data, <em>if the data were really generated by a hypothesised chance process</em>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2024 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>