<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - 4A: Binomial &amp; Chi-Square Tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('jk-circle-right')) {
    f.classList.add('jk-circle-down')
    f.classList.remove('jk-circle-right')
} else {
    f.classList.add('jk-circle-right')
    f.classList.remove('jk-circle-down')
}
}
</script>

<!---<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>-->

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04a_chisq.html">Week 4</a></li><li class="breadcrumb-item"><a href="./04a_chisq.html">4A: Binomial &amp; Chi-Square Tests</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">USMR</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Week 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01a_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1A: A first look at R &amp; RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01b_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1B: More R - Basic Data Skills</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Intro R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Week 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A: Measurement &amp; Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B: Curves &amp; Sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Week 3</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3A: Foundations of Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b_inference2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3B: Practical Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: T-tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Week 4</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04a_chisq.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">4A: Binomial &amp; Chi-Square Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b_revisitnhst.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4B: Revisiting NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Binomial &amp; Chi-Square Tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Week 5</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05a_covcor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5A: Covariance and Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5B: Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Covariance, Correlation &amp; Linear Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Week 6</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_wt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">WalkThrough: Advanced Data Wrangling</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">Week 7</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07a_mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7A: Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07b_assumptdiag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Multiple Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
 <span class="menu-text">Week 8</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08a_scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8A: Centering and Scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08b_catpred.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8B: Categorical Predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Scaling | Categorical Predictors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">
 <span class="menu-text">Week 9</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09a_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9A: Interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Interactions!</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#binomials" id="toc-binomials" class="nav-link active" data-scroll-target="#binomials">Binomials</a></li>
  <li><a href="#more-than-2-categories" id="toc-more-than-2-categories" class="nav-link" data-scroll-target="#more-than-2-categories">More than 2 categories</a></li>
  <li><a href="#chi2-goodness-of-fit-test" id="toc-chi2-goodness-of-fit-test" class="nav-link" data-scroll-target="#chi2-goodness-of-fit-test"><span class="math inline">\(\chi^2\)</span> Goodness of Fit Test</a></li>
  <li><a href="#chi2-test-of-independence" id="toc-chi2-test-of-independence" class="nav-link" data-scroll-target="#chi2-test-of-independence"><span class="math inline">\(\chi^2\)</span> Test of Independence</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">4A: Binomial &amp; Chi-Square Tests</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="lo">
<p>This reading:</p>
<ul>
<li>What are the basic hypothesis tests that we can conduct when we are interested in variables that have categories instead of numbers?
<ul>
<li>Tests of a proportion</li>
<li>Tests of the distribution of a single categorical variable</li>
<li>Tests of the relationship between two categorical variables</li>
</ul></li>
</ul>
</div>
<p>Just like we did with the various types of <span class="math inline">\(t\)</span>-test, we’re going to continue with some more brief explainers of different basic statistical tests. The past few weeks have focused on tests for <strong>numeric</strong> outcome variables, where we have been concerned with the mean of that variable (e.g.&nbsp;whether that mean is different from some specific value, or whether it is different between two groups). We now turn to investigate tests for <strong>categorical</strong> outcome variables.</p>
<p>When studying categorical variables, we tend to be interested in <strong>counts</strong> (or “frequencies”), and these can be presented in tables:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>timehands <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/timehands.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">isLeft =</span> <span class="fu">ifelse</span>(handed<span class="sc">==</span><span class="st">"left"</span>, <span class="st">"left"</span>, <span class="st">"other"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(timehands<span class="sc">$</span>isLeft) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 left other 
   12    88 </code></pre>
</div>
</div>
<section id="binomials" class="level1">
<h1>Binomials</h1>
<p>If we just have two categories, then our frequency table really can be summarised as a proportion. E.g., “the proportion who are left-handed”. We know that the other number (the proportion who are <em>not</em> left-handed) <em>has</em> to be 1-the proportion who <em>are</em>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(timehands<span class="sc">$</span>isLeft) <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prop.table</span>() <span class="co"># turn into proportions</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 left other 
 0.12  0.88 </code></pre>
</div>
</div>
<p>Really, these proportions are “the number of <span class="math inline">\(x\)</span>’s out of <span class="math inline">\(n\)</span> things”, and we often see this written as “<span class="math inline">\(k\)</span> successes in <span class="math inline">\(n\)</span> trials”. The reason for this is because it is built upon counting up a series of independent binary observations. The distribution of “<span class="math inline">\(k\)</span> successes in <span class="math inline">\(n\)</span> trials” is known as the <strong>Binomial distribution</strong>.</p>
<p>As an example, if we think of what probability distribution governs a single coin flip, it would look something like the Left hand plot in <a href="#fig-bernbin">Figure&nbsp;1</a>. But if we are instead considering what governs the behaviour of “number of tails in 5 coin flips” then our probabilities of each possible outcome look like the Right hand panel.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-bernbin" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04a_chisq_files/figure-html/fig-bernbin-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Left: A ‘Bernoulli distribution’ - the probability for a single observation (e.g.&nbsp;a single coin flip) with a binary outcome, where the probability of ‘success’ (i.e.&nbsp;Tails) is 0.5. Right: A ‘Binomial distribution’ - the probability of k success in n trials, each with a binary outcome (e.g., number of tails in 5 coin flips).</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: Bernoulli and Binomial
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The distribution of something that can just take one of two discrete values (i.e.&nbsp;a single binary outcome like one coin flip) is referred to as a “Bernoulli” probability distribution. A “distribution” here is just a way of expressing the probability of seeing different values, and we can write it mathematically if we are that way inclined:</p>
<p><span class="math display">\[
P(k) = p^k(1-p)^{1-k} \qquad \textrm{for } k \in \{0,1\}
\]</span> This looks a bit nonsensical at first, but it’s actually just a complicated way of saying “the probability of seeing <span class="math inline">\(k = 1\)</span> is the probability that <span class="math inline">\(k = 1\)</span>”.<br>
For instance, if we had a coin-flip, and we said that Tails is our “success” (and we give it the value 1) then the probability of seeing Heads and of seeing Tails is: <span class="math display">\[
\begin{align}
\textrm{Probability of failure (Heads)} = P(0) &amp;= 0.5^0(1-0.5)^{1-0} \\
&amp;= 0.5^0(0.5)^{1} \\
&amp;= 0.5 \\
\textrm{Probability of success (Tails)} = P(1) &amp;= 0.5^1(1-0.5)^{1-1} \\
&amp;= 0.5^1(0.5)^{0} \\
&amp;= 0.5
\end{align}
\]</span> When we move to thinking about the number of success in a set of trials, there we have to factor in the different ways in which we could see that number of success. For instance, if we had 3 coin flips, we could either see 0 Tails, 1 Tails, 2 Tails, or 3 Tails. There is only <em>one</em> way we could see “0 Tails”, but there are 3 different ways we could see “1 Tails” - we could have THH, HTH, or HHT!</p>
<p>The probability of <span class="math inline">\(k\)</span> successes in <span class="math inline">\(n\)</span> trials is the Binomial distribution, and is written as:</p>
<p><span class="math display">\[
P(k) = {n \choose k}p^k(1-p)^{n-k}
\]</span> Which can be read as: the probability of seeing <span class="math inline">\(k\)</span> successes is “the number of ways in which we could see k successes in n trials” (this is the <span class="math inline">\({n \choose k}\)</span> bit) multiplied by the probability of success in a single trial to the power of <span class="math inline">\(k\)</span>, multiplied by the probability of failure in a single trial to the power of <span class="math inline">\(n-k\)</span>.</p>
<p>To make more sense, let’s put it in the context of our “1 Tails in 3 coin flips”. The coin is fair, so the probability of a single Tails is 0.5 (so below we replace <span class="math inline">\(p\)</span> with 0.5), and we saw just above that there are 3 ways that we can get 1 success in 3 trials (so the calculation <span class="math inline">\({3 \choose 1}\)</span> becomes 3)<br>
<span class="math display">\[
\begin{align}
\text{Probabiltiy of 1 Tails in 3 flips} = P(1) &amp;= {3 \choose 1}0.5^1(1-0.5)^{3-1} \\
&amp;= {3 \choose 1}0.5^1(0.5)^{2} \\
&amp;= {3 \choose 1}0.5 \times 0.25 \\
&amp;= {3 \choose 1} 0.125 \\
&amp;= 3 \times 0.125 \\
&amp;= 0.375 \\
\end{align}
\]</span></p>
<p>We can actually check this in R using a handy function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.375</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Returning to “the proportion of people who are left-handed”, the internet (and everything on there is true, of course) tells me that 10% of the population is left-handed. As we have 100 people in our dataset, our expectation of what we are likely to see from samples of 100 people (if the probability of being left-handed is 0.10) therefore looks something like <a href="#fig-exp100">Figure&nbsp;2</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-exp100" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04a_chisq_files/figure-html/fig-exp100-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Expected distribution of ‘number of left-handed people out of 100’, assuming the true probability of being left-handed is 0.1</figcaption>
</figure>
</div>
</div>
</div>
<p>Much like the null hypothesis testing we have seen already concerning whether our observed mean is different from some hypothesised value (see <a href="03b_inference2.html#one-sample-t-test" target="_blank">3B #one-sample-t-test</a>), we can conduct a test of whether our observed sample proportion (12/100 = 0.12) is likely to have been drawn from a population where the true probability is 0.1:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(timehands<span class="sc">$</span>isLeft)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 left other 
   12    88 </code></pre>
</div>
</div>
<p>Either of these will work, and both will produce the same output:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="at">x =</span> <span class="dv">12</span>, <span class="at">n =</span> <span class="dv">100</span>, <span class="at">p =</span> <span class="fl">0.1</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(timehands<span class="sc">$</span>isLeft) <span class="sc">|&gt;</span> <span class="fu">binom.test</span>(<span class="at">p =</span> <span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  12 and 100
number of successes = 12, number of trials = 100, p-value = 0.503
alternative hypothesis: true probability of success is not equal to 0.1
95 percent confidence interval:
 0.0635689 0.2002357
sample estimates:
probability of success 
                  0.12 </code></pre>
</div>
</div>
<p>In this case, the p-value is &gt;.05<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, so we fail to reject the null hypothesis that the probability of being left-handed is 0.1.</p>
</section>
<section id="more-than-2-categories" class="level1">
<h1>More than 2 categories</h1>
<p>While the binomials capture the distribution of a series of binary trials, what happens when we are interested in something that <em>isn’t</em> binary? There are lots of categorical variables that have more than two possible values. For example, handedness isn’t as simple as “Left vs Others”, we might have 3 categories:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(timehands<span class="sc">$</span>handed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 ambi  left right 
    4    12    84 </code></pre>
</div>
</div>
<p>Furthermore, we might have a slightly more nuanced question that involves two variables, rather than just one! For instance, we might be interested in whether left/right/ambidextrous proportions are different across people who prefer the morning or night.<br>
In this case, with 2 variables, we have a 2-dimensional table (also referred to as a ‘contingency table’):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(timehands<span class="sc">$</span>handed, timehands<span class="sc">$</span>ampm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
        morning night
  ambi        1     3
  left        9     3
  right      42    42</code></pre>
</div>
</div>
<p>So we want to be able to perform tests to examine things such as:</p>
<ol start="2" type="a">
<li>how likely we are to see our sample frequencies in a single categorical variable, if some some hypothesised null distribution were true (e.g.&nbsp;how likely are we to see the numbers of left/right/ambi people in our sample if in bigger population we expect a 1/3 chance of each?)<br>
</li>
<li>how likely we are to see our sample frequencies across two categorical variables, if these variables are <em>independent</em> in the population. (e.g.&nbsp;how likely are we to see the counts in the 2x2 table above, if being left/right/ambi has <em>nothing to do with</em> whether you are a morning or night person).</li>
</ol>
<p>The test-statistics for these sort of tests (denoted <span class="math inline">\(\chi^2\)</span>, spelled <em>chi-square</em>, pronounced “kai-square”) are obtained by adding up the standardized squared deviations in each cell of a table of frequencies:</p>
<p><span class="math display">\[
\chi^2 = \sum_{all\ cells} \frac{(\text{Observed} - \text{Expected})^2}{\text{Expected}}
\]</span> where:</p>
<ul>
<li><span class="math inline">\(\text{Observed}\)</span> = observed count for a cell</li>
<li><span class="math inline">\(\text{Expected}\)</span> = expected count for a cell</li>
</ul>
<p>Just like the <span class="math inline">\(t\)</span>-statistics we calculate follow <span class="math inline">\(t\)</span>-distributions, the <span class="math inline">\(\chi^2\)</span>-statistics follow <span class="math inline">\(\chi^2\)</span> distributions! If you look carefully at the formula above, it can never be negative (because the value on top of the fraction is squared, and so is always positive). For a given cell of the table, if we observe exactly what we expect, then <span class="math inline">\(\text{(Observed - Expected)}^2\)</span> becomes zero. The further away the observed count is from the expected count, the larger it becomes.</p>
<p>This means that under the null hypothesis, larger values are less likely. And the shape of our <span class="math inline">\(\chi^2\)</span> distributions follow this logic. They have higher probability for small values, getting progressively less likely for large values. <span class="math inline">\(\chi^2\)</span>-distributions <em>also</em> have a degrees of freedom, because with more cells in a table, there are more chances for random deviations between “observed and expected” to come in, meaning we are more likely to see higher test statistics when we have more cells in the table (and therefore more degrees of freedom). You can see the distribution of <span class="math inline">\(\chi^2\)</span> statistics with different degrees of freedom in <a href="#fig-chidist1">Figure&nbsp;3</a> below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-chidist1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Chi-square_pdf.svg/1200px-Chi-square_pdf.svg.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Chi-Square Distributions</figcaption>
</figure>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="chi2-goodness-of-fit-test" class="level1">
<h1><span class="math inline">\(\chi^2\)</span> Goodness of Fit Test</h1>
<div class="statbox">
<p><strong>Purpose</strong></p>
<p>The <span class="math inline">\(\chi^2\)</span> Goodness of Fit Test is typically used to investigate whether observed sample proportions are consistent with an hypothesis about the proportional breakdown of the various categories in the population.</p>
<ul>
<li><strong>Examples:</strong>
<ul>
<li>Do 20% of the adult population suffer from some form of depression?</li>
<li>Are people equally likely to be born on any of the seven days of the week?<br>
</li>
<li>Are 25% of <a href="https://g.co/kgs/wr3MCd" target="_blank">Smarties</a> brown?<br>
</li>
<li>Are 2/3 of people ‘dog people’ and 1/3 of people ‘cat people’?</li>
</ul></li>
</ul>
<p><strong>Assumptions</strong></p>
<ol type="1">
<li>Data should be randomly sampled from the population.</li>
<li>Data should be at the categorical or nominal level - goodness-of-fit test is not appropriate for continuous level data.</li>
<li>Expected counts should be <em>at least</em> 5.</li>
</ol>
</div>
<!-- :::statbox -->
<!-- __Hypotheses:__ -->
<!-- The null hypothesis for a $\chi^2$ Goodness of Fit Test involves specifying the hypothesised proportions for each category.  If the null hypothesis is that all categories are equally distributed, then this is just saying that all proportions are equal to $\frac{1}{\text{number of categories}}$.   -->
<!-- The alternative hypothesis is simply that at least one of those proportions is not equal to its hypothesised value.   -->
<!-- - __Null Hypothesis ($H_0$):__   -->
<!-- $$ -->
<!-- p_{1} = \ ?, \ p_{2} = \ ?, \ ... \ , \ p_{k} = \ ?  -->
<!-- $$ -->
<!-- - __Alternative Hypothesis ($H_1$):__   -->
<!-- $$ -->
<!-- p_{1} \neq \ ? \ \text{or} \ p_{2} \neq \ ? \ \text{or} \ \ ... \ \ \text{or} \ p_{k} \neq \ ?  -->
<!-- $$ -->
<!-- ::: -->
<!-- :::statbox -->
<!-- __Test Statistic__   -->
<!-- The test-statistic (denoted $\chi^2$, spelled *chi-square*, pronounced "kai-square") is obtained by adding up the standardized squared deviations in each category:   -->
<!-- $$ -->
<!-- \chi^2 = \sum_{i} \frac{(\text{Observed}_i - \text{Expected}_i)^2}{\text{Expected}_i} -->
<!-- $$ -->
<!-- where: -->
<!-- - $\text{Observed}_i$ = observed counts for category $i$ -->
<!-- - $\text{Expected}_i$ = expected counts for category $i$ -->
<!--   - calculated as $\text{Expected}_i = n \times p_{i,null}$, where $n$ = sample size, $p_{i,null}$ is the hypothesised population proportion for that category under the null hypothesis.   -->
<!-- ::: -->
<!-- :::statbox -->
<!-- __p-value__ -->
<!-- The p-value for a $\chi^2$ Goodness of Fit Test is computed using a $\chi^2$ distribution with $df = \text{nr categories} - 1$.  -->
<!-- ::: -->
<!-- :::statbox -->
<!-- __Assumptions__ -->
<!-- 1. Data should be randomly sampled from the population.  -->
<!-- 2. Data should be at the categorical or nominal level - goodness-of-fit test is not appropriate for continuous level data.  -->
<!-- 3. Expected counts should be *at least* 5.  -->
<!-- ::: -->
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Research Question &amp; Data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p><strong>Research Question:</strong> Have proportions of adults suffering no/mild/moderate/severe depression changed from 2019?</p>
</blockquote>
<p>In 2019, it was reported that 80% of adults (18+) experienced no symptoms of depression, 12% experienced mild symptoms, 4% experienced moderate symptoms, and 4% experienced severe symptoms.<br>
The dataset is accessible at <a href="https://uoepsy.github.io/data/usmr_chisqdep.csv">https://uoepsy.github.io/data/usmr_chisqdep.csv</a> contains data from 1000 people to whom the PHQ-9 depression scale was administered in 2022.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>depdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_chisqdep.csv"</span>) </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(depdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  id    dep    fam_hist
  &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;   
1 ID1   severe n       
2 ID2   mild   n       
3 ID3   no     n       
4 ID4   no     n       
5 ID5   no     n       
6 ID6   no     n       </code></pre>
</div>
</div>
<p>We can see our table of observed counts with the <code>table()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(depdata<span class="sc">$</span>dep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    mild moderate       no   severe 
     143       34      771       52 </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quick and easy <code>chisq.test()</code>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can perform the <span class="math inline">\(\chi^2\)</span> test very easily, by simply passing the table to the <code>chisq.test()</code> function, and passing it the hypothesised proportions. If we don’t give it any, it will assume they are equal.</p>
<div class="imp">
<p><strong>Note:</strong> the proportions must be in the correct order as the entries in the table!</p>
</div>
<p>This will give us the test statistic, degrees of freedom, and the p-value:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># note the order of the table is mild, moderate, no, severe. </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># so we put the proportions in that order</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(depdata<span class="sc">$</span>dep), <span class="at">p =</span> <span class="fu">c</span>(.<span class="dv">12</span>, .<span class="dv">04</span>, .<span class="dv">8</span>, .<span class="dv">04</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  table(depdata$dep)
X-squared = 9.9596, df = 3, p-value = 0.01891</code></pre>
</div>
</div>
<p>If the distribution of no/mild/moderate/severe depression were as suggested (80%/12%/4%/4%), then the probability that we would obtain a test statistic this large (or larger) by random chance alone is .019. With an <span class="math inline">\(\alpha = 0.05\)</span>, we reject the null hypothesis that the proportion of people suffering from different levels of depression are the same as those indicated previously in 2019.</p>
<div class="int">
<p><span class="math inline">\(\chi^2\)</span> goodness of fit test indicated that the observed proportions of people suffering from no/mild/moderate/severe depression were significantly different (<span class="math inline">\(\chi^2(3)=9.96, p = .019\)</span>) from those expected under the distribution suggested from a 2019 study (80%/12%/4%/4%).</p>
</div>
<p>We can examine where the biggest deviations from the hypothesised distribution are by examining the ‘residuals’:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(depdata<span class="sc">$</span>dep), <span class="at">p =</span> <span class="fu">c</span>(.<span class="dv">12</span>, .<span class="dv">04</span>, .<span class="dv">8</span>, .<span class="dv">04</span>))<span class="sc">$</span>residuals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      mild   moderate         no     severe 
 2.0996031 -0.9486833 -1.0253048  1.8973666 </code></pre>
</div>
</div>
<p>This matches with what we see when we look at the table of counts. With <span class="math inline">\(n=1000\)</span>, under our 2019 distribution, we would expect 800 to have no depression, 120 mild, 40 moderate, and 40 severe.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(depdata<span class="sc">$</span>dep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    mild moderate       no   severe 
     143       34      771       52 </code></pre>
</div>
</div>
<p>The difference in the moderate “observed - expected” is 6, and the difference in the “no depression” is 29. But these are not comparable, because really the 6 is a much bigger amount of the expected for that category than 29 is for the no depression category. The residuals are a way of standardising these.</p>
<p>They are calculated as: <span class="math display">\[
\text{residual} = \frac{\text{observed} - \text{expected}}{\sqrt{expected}}
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Step-by-step calculations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>First we calculate the observed counts:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>depdata <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(dep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  dep          n
  &lt;chr&gt;    &lt;int&gt;
1 mild       143
2 moderate    34
3 no         771
4 severe      52</code></pre>
</div>
</div>
<p>Let’s add to this the expected counts:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>depdata <span class="sc">|&gt;</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(dep) <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">expected =</span> <span class="fu">c</span>(.<span class="dv">12</span>, .<span class="dv">04</span>, .<span class="dv">8</span>, .<span class="dv">04</span>)<span class="sc">*</span><span class="dv">1000</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  dep          n expected
  &lt;chr&gt;    &lt;int&gt;    &lt;dbl&gt;
1 mild       143      120
2 moderate    34       40
3 no         771      800
4 severe      52       40</code></pre>
</div>
</div>
<p>How do we measure how far the observed counts are from the expected counts under the null? If we simply subtracted the expected counts from the observed counts and then add them up, you will get 0. Instead, we will square the differences between the observed and expected counts, and then add them up.</p>
<p>One issue, however, remains to be solved. A squared difference between observed and expected counts of 100 has a different weight in these two scenarios:</p>
<p><strong>Scenario 1:</strong> <span class="math inline">\(O = 30\)</span> and <span class="math inline">\(E = 20\)</span> leads to a squared difference <span class="math inline">\((O - E)^2 = 10^2 = 100\)</span>.<br>
<strong>Scenario 2:</strong> <span class="math inline">\(O = 3000\)</span> and <span class="math inline">\(E = 2990\)</span> leads to a squared difference <span class="math inline">\((O - E)^2 = 10^2 = 100\)</span></p>
<p>However, it is clear that a squared difference of 100 in Scenario 1 is much more substantial than a squared difference of 100 in Scenario 2. It is for this reason that we divide the squared differences by the the expected counts to “standardize” the squared deviation.</p>
<p><span class="math display">\[
\chi^2 = \sum_{i} \frac{(\text{Observed}_i - \text{Expected}_i)^2}{\text{Expected}_i}
\]</span></p>
<p>We can calculate each part of the equation:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>depdata <span class="sc">|&gt;</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(dep) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">expected =</span> <span class="fu">c</span>(.<span class="dv">12</span>, .<span class="dv">04</span>, .<span class="dv">8</span>, .<span class="dv">04</span>)<span class="sc">*</span><span class="dv">1000</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sq_diff =</span> (n <span class="sc">-</span> expected)<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">std_sq_diff =</span> sq_diff<span class="sc">/</span>expected</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  dep          n expected sq_diff std_sq_diff
  &lt;chr&gt;    &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;
1 mild       143      120     529        4.41
2 moderate    34       40      36        0.9 
3 no         771      800     841        1.05
4 severe      52       40     144        3.6 </code></pre>
</div>
</div>
<p>The test-statistic <span class="math inline">\(\chi^2\)</span> is obtained by adding up all the standardized squared deviations:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>depdata <span class="sc">|&gt;</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(dep) <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">expected =</span> <span class="fu">c</span>(.<span class="dv">12</span>, .<span class="dv">04</span>, .<span class="dv">8</span>, .<span class="dv">04</span>)<span class="sc">*</span><span class="dv">1000</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sq_diff =</span> (n <span class="sc">-</span> expected)<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">std_sq_diff =</span> sq_diff<span class="sc">/</span>expected</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">chi =</span> <span class="fu">sum</span>(std_sq_diff)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    chi
  &lt;dbl&gt;
1  9.96</code></pre>
</div>
</div>
<p>The p-value for a <span class="math inline">\(\chi^2\)</span> Goodness of Fit Test is computed using a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(df = \text{nr categories} - 1\)</span>.<br>
We calculate our p-value by using <code>pchisq()</code> and we have 4 levels of depression, so <span class="math inline">\(df = 4-1 = 3\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">9.959583</span>, <span class="at">df=</span><span class="dv">3</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01891284</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="chi2-test-of-independence" class="level1">
<h1><span class="math inline">\(\chi^2\)</span> Test of Independence</h1>
<div class="statbox">
<p><strong>Purpose</strong></p>
<p>The <span class="math inline">\(\chi^2\)</span> Test of Independence is used to determine whether or not there is a significant association between two categorical variables. To examine the independence of two categorical variables, we have a contingency table:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                   Family History of Depression
Depression Severity   n   y
           mild      93  50
           moderate  23  11
           no       532 239
           severe    37  15</code></pre>
</div>
</div>
<ul>
<li><strong>Examples:</strong>
<ul>
<li>Is depression severity associated with having a family history of depression?<br>
</li>
<li>Are people with blue eyes more likely to be over 6 foot tall?<br>
</li>
<li>Are people who carry the APOE-4 gene more likely to have mild cognitive impairment?</li>
</ul></li>
</ul>
<p><strong>Assumptions</strong></p>
<ol type="1">
<li>Two or more categories (groups) for each variable.</li>
<li>Independence of observations
<ul>
<li>there is no relationship between the subjects in each group</li>
</ul></li>
<li>Large enough sample size, such that:
<ul>
<li>expected frequencies for each cell are at least 1</li>
<li>expected frequencies should be at least 5 for the majority (80%) of cells</li>
</ul></li>
</ol>
</div>
<!-- :::statbox -->
<!-- __Hypotheses:__ -->
<!-- The hypotheses for the $\chi^2$ Test of Independence follow the same logic as the $\chi^2$ goodness of fit test. We have some hypothesised breakdown of proportions that we would _expect_.  However, it's less easy to compute these expected breakdowns and so we typically state the hypotheses as:   -->
<!-- - __Null Hypothesis ($H_0:$)__ Variable A is not associated with variable B   -->
<!-- - __Alternative Hypothesis ($H_1:$)__ Variable A is associated with variable B -->
<!-- ::: -->
<!-- :::statbox -->
<!-- __Test Statistic__   -->

<!-- Our test statistic looks much the same as before, but extends to all cells of the contingency table:   -->
<!-- $$ -->
<!-- \chi^2 = \sum_{all\ cells} \frac{(\text{Observed} - \text{Expected})^2}{\text{Expected}} -->
<!-- $$ -->
<!-- where: -->
<!-- - $Observed$ = observed count for a cell -->
<!-- - $Expected$ = expected count for a cell -->
<!-- ::: -->
<!-- :::statbox -->
<!-- __p-value__ -->
<!-- The p-value is computed using a $\chi^2$ distribution with $df = (\text{nr rows} - 1) \times (\text{nr columns} - 1)$.  -->

<!-- Why is this? Well, remember that the degrees of freedom is the number of values that are *free to vary* as we estimate parameters. In a table such as the one below, where we have 4 rows and 2 columns, the degrees of freedom is the number of cells in the table that can vary before we can simply calculate the values of the other cells (where we're constrained by the need to sum to our row/column totals).    -->
<!-- ```{r} -->
<!-- #| echo: false -->

<!-- table(depdata$dep,depdata$fam_hist,  dnn=c("Depression Severity","Family History of Depression")) -->
<!-- ``` -->
<!-- ::: -->
<!-- :::statbox -->
<!-- __Assumptions__ -->
<!-- 1. Two or more categories (groups) for each variable.  -->
<!-- 2. Independence of observations  -->
<!--     + there is not relationship between the subjects in each group  -->
<!-- 3. Large enough sample size, such that: -->
<!--     + expected frequencies for each cell are at least 1  -->
<!--     + expected frequencies should be at least 5 for the majority (80%) of cells  -->
<!-- ::: -->
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Research Question &amp; Data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p><strong>Research Question:</strong> Is severity of depression associated with having a family history of depression?</p>
</blockquote>
<p>The dataset accessible at <a href="https://uoepsy.github.io/data/usmr_chisqdep.csv">https://uoepsy.github.io/data/usmr_chisqdep.csv</a> contains data from 1000 people to whom the PHQ-9 depression scale was administered in 2022, and for which respondents were asked a brief family history questionnaire to establish whether they had a family history of depression.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>depdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_chisqdep.csv"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(depdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  id    dep    fam_hist
  &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;   
1 ID1   severe n       
2 ID2   mild   n       
3 ID3   no     n       
4 ID4   no     n       
5 ID5   no     n       
6 ID6   no     n       </code></pre>
</div>
</div>
<p>We can create our contingency table:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(depdata<span class="sc">$</span>dep, depdata<span class="sc">$</span>fam_hist)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
             n   y
  mild      93  50
  moderate  23  11
  no       532 239
  severe    37  15</code></pre>
</div>
</div>
<p>And even create a quick and dirty visualisation of this too:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">table</span>(depdata<span class="sc">$</span>dep, depdata<span class="sc">$</span>fam_hist))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04a_chisq_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quick and easy <code>chisq.test()</code>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Again, we can perform this test very easily by passing the table to the <code>chisq.test()</code> function. We don’t need to give it any hypothesised proportions here - it will work them out based on the null hypothesis that the two variables are independent.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(depdata<span class="sc">$</span>dep, depdata<span class="sc">$</span>fam_hist))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(depdata$dep, depdata$fam_hist)
X-squared = 1.0667, df = 3, p-value = 0.7851</code></pre>
</div>
</div>
<p>If there was no association between depression severity and having a family history of depression, then the probability that we would obtain a test statistic this large (or larger) by random chance alone is 0.79. With an <span class="math inline">\(\alpha=.05\)</span>, we fail to reject the null hypothesis that there is no association between depression severity and family history of depression.</p>
<div class="int">
<p>A <span class="math inline">\(\chi^2\)</span> test of independence indicated no significant association between severity and family history (<span class="math inline">\(\chi^2(3)=1.07, p=.785\)</span>), suggesting that a participants’ severity of depression was not dependent on whether or not they had a family history of depression.</p>
</div>
<p>We can see the expected and observed counts:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(depdata<span class="sc">$</span>dep, depdata<span class="sc">$</span>fam_hist))<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
                 n       y
  mild      97.955  45.045
  moderate  23.290  10.710
  no       528.135 242.865
  severe    35.620  16.380</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(depdata<span class="sc">$</span>dep, depdata<span class="sc">$</span>fam_hist))<span class="sc">$</span>observed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
             n   y
  mild      93  50
  moderate  23  11
  no       532 239
  severe    37  15</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Step-by-step calculations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We have our observed table:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(depdata<span class="sc">$</span>dep, depdata<span class="sc">$</span>fam_hist)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
             n   y
  mild      93  50
  moderate  23  11
  no       532 239
  severe    37  15</code></pre>
</div>
</div>
<p>To work out our <em>expected</em> counts, we have to do something a bit tricky. Let’s look at the variables independently:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(depdata<span class="sc">$</span>fam_hist)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  n   y 
685 315 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(depdata<span class="sc">$</span>dep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    mild moderate       no   severe 
     143       34      771       52 </code></pre>
</div>
</div>
<p>With <span class="math inline">\(\frac{315}{315+685} = 0.315\)</span> of the sample having a family history, then <em>if depression severity is independent of family history,</em> we would expect that 0.315 of each severity group to have a family history of depression. For example, for the mild depression, with 143 people, we would expect <span class="math inline">\(143 \times 0.315 = 45.045\)</span> people in that group to have a family history of depression.</p>
<p>For a given cell of the table we can calculate the expected count as <span class="math inline">\(\text{row total} \times \frac{\text{column total}}{\text{samplesize}}\)</span>.<br>
Or, quickly in R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">table</span>(depdata<span class="sc">$</span>dep, depdata<span class="sc">$</span>fam_hist)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>exp <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(obs) <span class="sc">%o%</span> <span class="fu">colSums</span>(obs) <span class="sc">/</span> <span class="fu">sum</span>(obs)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>exp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               n       y
mild      97.955  45.045
moderate  23.290  10.710
no       528.135 242.865
severe    35.620  16.380</code></pre>
</div>
</div>
<p>Now that we have our table of observed counts, and our table of expected counts, we can actually fit these into our formula to calculate the test statistic:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span> ( (obs <span class="sc">-</span> exp)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> exp )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.066686</code></pre>
</div>
</div>
<p>The p-value is computed using a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(df = (\text{nr rows} - 1) \times (\text{nr columns} - 1)\)</span>.</p>
<p>Why is this? Well, remember that the degrees of freedom is the number of values that are <em>free to vary</em> as we estimate parameters. In a table such as the one below, where we have 4 rows and 2 columns, the degrees of freedom is the number of cells in the table that can vary before we can simply calculate the values of the other cells (where we’re constrained by the need to sum to our row/column totals).</p>
<p>We have 4 rows, and 2 columns, so <span class="math inline">\(df = (4-1) \times (2-1) = 3\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">1.066686</span>, <span class="at">df =</span> <span class="dv">3</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7851217</code></pre>
</div>
</div>
</div>
</div>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>the conventional <span class="math inline">\(\alpha\)</span> level used in psychology<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2024 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>