<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10A: The Generalized Linear Model – USMR</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

function toggle_visibility(id1, id2) {

var e = document.getElementById(id1);

var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('jk-circle-right')) {

    f.classList.add('jk-circle-down')

    f.classList.remove('jk-circle-right')

} else {

    f.classList.add('jk-circle-right')

    f.classList.remove('jk-circle-down')

}

}

</script>



<!---<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>-->

<link href="site_libs/panelset-0.3.0/panelset.css" rel="stylesheet">

<script src="site_libs/panelset-0.3.0/panelset.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10a_glm.html">Week 10</a></li><li class="breadcrumb-item"><a href="./10a_glm.html">10A: The Generalized Linear Model</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">USMR</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01a_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1A: A first look at R &amp; RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01b_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1B: More R - Basic Data Skills</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Intro R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A: Measurement &amp; Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B: Curves &amp; Sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 3</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3A: Foundations of Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b_inference2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3B: Practical Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: T-tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 4</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04a_chisq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4A: Binomial &amp; Chi-Square Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b_revisitnhst.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4B: Revisiting NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Binomial &amp; Chi-Square Tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 5</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05a_covcor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5A: Covariance and Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5B: Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Covariance, Correlation &amp; Linear Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 6</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_wt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">WalkThrough: Advanced Data Wrangling</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 7</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07a_mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7A: Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07b_assumptdiag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Multiple Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 8</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08a_scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8A: Centering and Scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08b_catpred.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8B: Categorical Predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Scaling | Categorical Predictors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 9</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09a_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9A: Interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: Interactions!</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Week 10</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10a_glm.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">10A: The Generalized Linear Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises: GLM</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 11</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 11 Exercises: Tying up Loose Ends</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#quick-recaps" id="toc-quick-recaps" class="nav-link active" data-scroll-target="#quick-recaps">Quick recaps</a></li>
  <li><a href="#continuous-outcomes" id="toc-continuous-outcomes" class="nav-link" data-scroll-target="#continuous-outcomes">Continuous outcomes!</a></li>
  <li><a href="#other-outcomes" id="toc-other-outcomes" class="nav-link" data-scroll-target="#other-outcomes">Other outcomes</a></li>
  <li><a href="#introducing-the-glm" id="toc-introducing-the-glm" class="nav-link" data-scroll-target="#introducing-the-glm">Introducing the GLM</a></li>
  <li><a href="#fitting-glm-in-r" id="toc-fitting-glm-in-r" class="nav-link" data-scroll-target="#fitting-glm-in-r">Fitting GLM in R</a></li>
  <li><a href="#marshmallows" id="toc-marshmallows" class="nav-link" data-scroll-target="#marshmallows">Marshmallows</a></li>
  <li><a href="#comparing-models" id="toc-comparing-models" class="nav-link" data-scroll-target="#comparing-models">Comparing models</a></li>
  <li><a href="#coefficient-interpretation" id="toc-coefficient-interpretation" class="nav-link" data-scroll-target="#coefficient-interpretation">Coefficient Interpretation</a></li>
  <li><a href="#coefficient-tests-intervals" id="toc-coefficient-tests-intervals" class="nav-link" data-scroll-target="#coefficient-tests-intervals">Coefficient tests &amp; intervals</a></li>
  <li><a href="#visualising" id="toc-visualising" class="nav-link" data-scroll-target="#visualising">Visualising</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  <li><a href="#summary.lm-and-summary.glm" id="toc-summary.lm-and-summary.glm" class="nav-link" data-scroll-target="#summary.lm-and-summary.glm">summary.lm and summary.glm</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10a_glm.html">Week 10</a></li><li class="breadcrumb-item"><a href="./10a_glm.html">10A: The Generalized Linear Model</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">10A: The Generalized Linear Model</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<style>
  .zoomDiv {
    opacity: 0;
    position:fixed;
    top: 50%;
    left: 50%;
    z-index: 50;
    transform: translate(-50%, -50%);
    box-shadow: 0px 0px 50px #888888;
    max-height:100%; 
    overflow: scroll;
  }

.zoomImg {
  width: 150%;
}
</style>
<script type="text/javascript">
  $(document).ready(function() {
    $('body').prepend("<div class=\"zoomDiv\"><img src=\"\" class=\"zoomImg\"></div>");
    // onClick function for all plots (img's)
    $('img:not(.zoomImg)').click(function() {
      $('.zoomImg').attr('src', $(this).attr('src'));
      $('.zoomDiv').css({opacity: '1', width: '60%'});
    });
    // onClick function for zoomImg
    $('img.zoomImg').click(function() {
      $('.zoomDiv').css({opacity: '0', width: '0%'});
    });
  });
</script>
<section id="quick-recaps" class="level1">
<h1>Quick recaps</h1>
<p>Things have moved pretty quickly in the last couple of readings, so it’s worth taking a little bit of time on recaps to see how it all fits together.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Simple linear regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the simple linear regression, we were modelling a continuous outcome variable <span class="math inline">\(y\)</span> as a function of some predictor <span class="math inline">\(x\)</span>.<br>
Our model of <span class="math inline">\(y\)</span> was defined by a number of components:</p>
<ul>
<li><span class="math inline">\(b_0\)</span>: the “Intercept”. This is the predicted value of <span class="math inline">\(y\)</span> where <span class="math inline">\(x = 0\)</span>. In the plot below, it is where the regression line cuts the y-axis.<br>
</li>
<li><span class="math inline">\(b_1\)</span>: the “Coefficient for <span class="math inline">\(x\)</span>”. This is the predicted <em>increase</em> in <span class="math inline">\(y\)</span> for every unit increase of <span class="math inline">\(x\)</span>. In the plot below, this is the amount the regression line goes up for every one unit we move across.<br>
</li>
<li><span class="math inline">\(\varepsilon\)</span>: the “Residuals” or “Error term”. These are the distances from each of our observed values to the model predicted values. In the plot below, these are the vertical distances from each red dot to the black line. The standard deviation of all these gets denoted <span class="math inline">\(\sigma_\varepsilon\)</span>.</li>
</ul>
<p><strong>Model:</strong></p>
<p><span class="math display">\[
\begin{align}
y &amp;= b_0 + b_1 \cdot x_1 + \varepsilon\\
\qquad \\
&amp;\varepsilon \sim N(0, \sigma_\varepsilon)
\end{align}
\]</span></p>
<strong>In R:</strong>
<center>
<pre><code>lm(y ~ x1, data = mydata)</code></pre>
</center>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-simplelm" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simplelm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-simplelm-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simplelm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Simple linear regression model. one continuous predictor.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Multiple linear regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>When we extended this to multiple regression, we essentially just added more explanatory variables (more ‘predictors’ of the outcome <span class="math inline">\(y\)</span>).</p>
<p>In these models, the values of <span class="math inline">\(y\)</span> are now modelled as a set of relationship with more than just one <span class="math inline">\(x\)</span> variable. So our models are defined by more coefficients.</p>
<ul>
<li><span class="math inline">\(b_0\)</span>: the “Intercept”. This is the predicted value of <span class="math inline">\(y\)</span> when <em>all predictors are zero</em>.<br>
</li>
<li><span class="math inline">\(b_1\)</span>: the “Coefficient for <span class="math inline">\(x_1\)</span>”. This is the predicted <em>increase</em> in <span class="math inline">\(y\)</span> for every unit increase of <span class="math inline">\(x_1\)</span> <em>holding constant</em> all other predictors.<br>
</li>
<li>…</li>
<li>…</li>
<li><span class="math inline">\(b_p\)</span>: the “Coefficient for <span class="math inline">\(x_p\)</span>”. This is the predicted <em>increase</em> in <span class="math inline">\(y\)</span> for every unit increase of <span class="math inline">\(x_p\)</span> <em>holding constant</em> all other predictors.<br>
</li>
<li><span class="math inline">\(\varepsilon\)</span>: the “Residuals” or “Error term”. These are the distances from each of our observed values to the model predicted values. The standard deviation of all these gets denoted <span class="math inline">\(\sigma_\varepsilon\)</span>.</li>
</ul>
<p><strong>Model:</strong><br>
<span class="math display">\[
\begin{align}
y &amp;= b_0 + b_1 \cdot x_1 + b_2 \cdot x_2 \,\, ... \,\, + b_p \cdot x_p + \varepsilon\\
\qquad \\
&amp;\varepsilon \sim N(0, \sigma_\varepsilon)
\end{align}
\]</span></p>
<strong>In R:</strong><br>

<center>
<pre><code>lm(y ~ x1 + x2 ... + xp, data = mydata)</code></pre>
</center>
<p>In the plot below with <strong>two</strong> predictors, we would have a coefficient for each one, showing the slope of the regression surface along each dimension. The residuals continue to be the distances from the observed values to our model predicted values, so in this they are the vertical distances from each red dot to the surface.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-multiplelm" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multiplelm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-multiplelm-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multiplelm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: multiple linear regression model with two continuous predictors.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interactions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We then saw how we can let the relationships between the outcome <span class="math inline">\(y\)</span> and an explanatory variable <span class="math inline">\(x1\)</span> vary <em>as a function of</em> some other explanatory variable <span class="math inline">\(x2\)</span>.</p>
<p>In the plot below, if someone asks you “what is the relationship between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span>, your reply should (hopefully) be”it depends on what the value of <span class="math inline">\(x_2\)</span> is”</p>
<p>As we can see from the plot, for low values of <span class="math inline">\(x_2\)</span>, there is a steep downward slope between <span class="math inline">\(y\)</span> and <span class="math inline">\(x_1\)</span> (the red line in the plot). For high values of <span class="math inline">\(x_2\)</span>, the slope between <span class="math inline">\(y\)</span> and <span class="math inline">\(x_1\)</span> is much flatter (the blue line).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-intlm" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-intlm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-intlm-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-intlm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: multiple linear regression model with two continuous predictors that interact
</figcaption>
</figure>
</div>
</div>
</div>
<p>We can capture this by using an additional coefficient in our linear model. To express an interaction, we use the product of the two predictors (<span class="math inline">\(x_1 \cdot x_2\)</span>).</p>
<p><strong>Model:</strong><br>
<span class="math display">\[
\begin{align}
y &amp;= b_0 + b_1 \cdot x_1 + b_2 \cdot x_2 + b_3 \cdot x_1 \cdot x_2 + \,\, ... \,\, + b_p \cdot x_p + \varepsilon\\
\qquad \\
&amp;\varepsilon \sim N(0, \sigma_\varepsilon)
\end{align}
\]</span></p>
<strong>In R:</strong><br>

<center>
<pre><code>lm(y ~ x1 + x2 + x1:x2 + ..., data = mydata)  
  OR  
lm(y ~ x1*x2 + ..., data = mydata)  </code></pre>
</center>
<p>The resulting coefficients (<span class="math inline">\(b_1\)</span>, <span class="math inline">\(b_2\)</span> and <span class="math inline">\(b_3\)</span> in the equation above) provide us with:</p>
<ol type="1">
<li>the association between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span> when <span class="math inline">\(x_2 = 0\)</span><br>
</li>
<li>the association between <span class="math inline">\(x2\)</span> and <span class="math inline">\(y\)</span> when <span class="math inline">\(x_1 = 0\)</span><br>
</li>
<li>the amount to which 1. and 2. are adjusted when there is an increase in the other variable</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Categorical explanatory variables
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Throughout the models we’ve been fitting we have also seen how they behave with <strong>categorical</strong> predictors.</p>
<p>When we enter a categorical variable in as a predictor in a linear model, it gets entered as a set of “dummy variables” (typically zeroes or ones, but we it <em>is</em> possible to do more clever things). These represent differences between groups.</p>
<p>If we had a categorical variable which contained <span class="math inline">\(k\)</span> levels (or “groups”, or “categories”), then R will put <span class="math inline">\(k-1\)</span> variables into the model for us, and we will get out <span class="math inline">\(k-1\)</span> coefficients. The default behaviour in R is that, depending on what we set as our <strong>reference level</strong>, the coefficients represent the difference from this level to each of the other levels.</p>
<p>In the plots below, if “Group1” is the reference, then the coefficient <code>groupGroup2</code> would represent the vertical distance from the red line to the green line, and the coefficient <code>groupGroup3</code> would be the vertical distance from the red line to the blue line.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-catlm" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-catlm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-catlm-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catlm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: A categorical predictor in a regression model in R will by default set one level as a reference (e.g.&nbsp;Group1 here), and compare each level to that reference
</figcaption>
</figure>
</div>
</div>
</div>
<p><em>Note - because categorical predictors is all looking at the difference between groups - this is all still intrinsically “linear” - the only possible way to get from the red line to the green line is via a straight line.</em></p>
<p>We also saw how this same logic applies when categorical explanatory variables are involved in an interaction - e.g., a binary (two-level) predictor interacting with a continuous predictor allows two lines to be different slopes (as in <a href="#fig-catintglm" class="quarto-xref">Figure&nbsp;5</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-catintglm" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-catintglm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-catintglm-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catintglm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Continuous*Binary interaction
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="continuous-outcomes" class="level1">
<h1>Continuous outcomes!</h1>
<p>In all of the models thus far, we have been dealing with outcomes variables that are <em>continuous</em>. These are variables for which an observation can take <em>any</em> real value - i.e.&nbsp;3.4, or 1.50365, or 0.000532. We might not have have measured these variables with any degree of accuracy, but the models we have been fitting have fundamentally assumed this.</p>
<p>For instance, even if our outcome is a score on some neuropsychological test of cognition where we can only score whole numbers, our model predictions will be values that are much more specific. A model predicted score on the test could be 18.220483724…… This is because we are modelling a continuous line through the observed scores. This also means that the model extends to scores from negative to positive infinity (<span class="math inline">\(- \infty &lt; y &lt; \infty\)</span>), even if we know that people can’t score less than 0 or more than 30 (see <a href="#fig-mmsezoom" class="quarto-xref">Figure&nbsp;6</a> ).</p>
<p>Often, this is a perfectly acceptable thing to do, especially when we consider the outcome variable to be measuring a continuous thing (e.g.&nbsp;cognitive functioning), just hindered by the precision of measurement, and when the bounds of our measurement tool are not preventing us from capturing variation (e.g.&nbsp;if everyone scores maximum on the test, then there is no variance to explain).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mmsezoom" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mmsezoom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-mmsezoom-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:80.0%" height="350">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mmsezoom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Our lm(mmse ~ air_pol * apoe4) model is a continuous line extending infinitely
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="other-outcomes" class="level1">
<h1>Other outcomes</h1>
<p>There are lots of variables that we collect that don’t fit with this way of thinking. For instance, what if we want to model something that takes the form of a <strong>binary variable:</strong><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<ul>
<li>being Y vs not being Y<br>
</li>
<li>Y happening vs Y not happening</li>
</ul>
<p>For binary variables, values can only take one of two values, which we often encode as 0 or 1. Values can’t be 0.5, -2, or 1.3, they can <em>only</em> be 0 or 1.</p>
<p>Another type of outcome that we can’t really model as continuous is a <strong>count variable</strong>:</p>
<ul>
<li>The number of Y’s</li>
<li>How many times Y happened</li>
</ul>
<p>For count data, values can’t take <em>any</em> real number, they can only take integers (0, 1, 2, 3, …).</p>
<div class="frame">
<p><strong>An example</strong></p>
<p>At a lake, I survey 120 people who have just finished fishing for the day. I’m interested in how the length of time they spent fishing is associated with:</p>
<ol type="1">
<li>how tired they are from 0 to 100 (continuous)</li>
<li>catching <em>any</em> fish (binary, 1 = yes, 0 = no)</li>
<li>the number of fish caught (count)</li>
</ol>
<p>We can try at first to visualise all these relationships as scatterplots (<a href="#fig-outcomeplots" class="quarto-xref">Figure&nbsp;7</a>).</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>fish <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/fishing_exped.csv"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fish, <span class="fu">aes</span>(<span class="at">x =</span> hours, <span class="at">y =</span> tiredness)) <span class="sc">+</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"How tired are you (0 - 100)?"</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fish, <span class="fu">aes</span>(<span class="at">x =</span> hours, <span class="at">y =</span> caught_any)) <span class="sc">+</span> </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Did you catch any fish?"</span>) <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">1.2</span>),<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="fl">1.2</span>,.<span class="dv">2</span>))</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fish, <span class="fu">aes</span>(<span class="at">x =</span> hours, <span class="at">y =</span> n_fish)) <span class="sc">+</span> </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"How many fish did you catch?"</span>) <span class="sc">+</span> </span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">/</span> p2 <span class="sc">/</span> p3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-outcomeplots" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-outcomeplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-outcomeplots-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-outcomeplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Three different outcomes: continuous (top), binary (middle), count (bottom)
</figcaption>
</figure>
</div>
</div>
</div>
<p>We can happily model our first outcome, tiredness, with a linear model. In <a href="#fig-outcomeplots" class="quarto-xref">Figure&nbsp;7</a> (top panel), we can see that the relationship looks linear, and the residuals are spread fairly consistently above and below the fitted line.</p>
<p>For the binary outcome however <a href="#fig-outcomeplots" class="quarto-xref">Figure&nbsp;7</a> (middle panel), there are a couple of things that are problematic. For someone who spends 8 hours fishing, the model estimates approximately <strong>1.1</strong> “catching any fish”. But what does that 1.1 really mean? Does it mean that if I fish 8 hours I will have 1.1 fish? no, because it’s not a count. Does it mean there is a 110% probability of catching fish? This is closer, but again it doesn’t make much sense - how can we have a probability of 110%?</p>
<p>For the count variable (bottom panel), we can also see that the standard linear model looks problematic. Again it estimates values we simply <em>cannot</em> have (it looks like if I spend 1 hour fishing I will catch about negative 3 fish?). Another thing to note is that the variance in the points on the y axis tends to increase as we get higher. This is typical of count data - we’re going to see lots of people catching 0, 1 or 2 fish, and so the “people catching few fish” are all quite close (in number of fish) to one another, but because fewer people catch 20 fish, 30 fish etc, there is a lot more variability in “number of fish” when we get higher up. This is a problem for a linear model, which assumes <em>constant variance</em> across the fitted model.</p>
</div>
</section>
<section id="introducing-the-glm" class="level1">
<h1>Introducing the GLM</h1>
<p>To deal with these sorts of outcome variable, we need to learn about the <strong>Generalized Linear Model (GLM)</strong>.</p>
<p>The GLM involves a little bit of trickery, in which we translate something that is inherently not linear (e.g.&nbsp;“the <em>probability</em> of Y”, or for count variables “the <em>rate</em> of occurrence of Y”) into something which is both linear and unbounded, and model that thing instead.</p>
<p>The problem, fundamentally, is that things like probability is not linear. We think of it as getting ever and ever closer, but never reaching, 0 and 1. For instance, if the probability of <span class="math inline">\(y\)</span> ocurring increases with <span class="math inline">\(x\)</span>, it makes most sense to think of it looking something like <a href="#fig-plotprobab" class="quarto-xref">Figure&nbsp;8</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plotprobab" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plotprobab-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-plotprobab-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plotprobab-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: As x increases, probability of y gets closer and closer (but never meets) 1
</figcaption>
</figure>
</div>
</div>
</div>
<p>To allow us to use our linear toolbox for things like “probability”, we can’t think in terms of modelling how <span class="math inline">\(x\)</span> is associated with the the probability of <span class="math inline">\(y\)</span> <em>directly</em> (because we only ever observe <span class="math inline">\(y\)</span> as 0 or 1). What we do instead is model how <span class="math inline">\(x\)</span> is associated with the “log-odds of <span class="math inline">\(y\)</span>”.</p>
<p>We use a similar trick for modelling an outcome that is a count - instead of modelling counts directly, we can model the log of the counts.</p>
<div class="statbox">
<p><strong>Probability, odds, and log-odds</strong></p>
<p>If we let <span class="math inline">\(p\)</span> denote the probability of a given event, then <span class="math inline">\(\frac{p}{(1-p)}\)</span> are the odds of the event happening.</p>
<p>For example, the odds of rolling a 6 with a normal die is 1/5 (sometimes this is expressed ‘1:5’, and in gambling the order is sometimes flipped and you’ll see ‘5/1’ or ‘odds of five to one’).</p>
<p>The “log-odds” (sometimes called “logits”) are denoted by <span class="math inline">\(ln(\frac{p}{(1-p)})\)</span>, where <span class="math inline">\(ln\)</span> refers to the “natural logarithm”. Don’t worry about exactly what <span class="math inline">\(ln\)</span> means - the important thing is that it converts “odds” (which can go from 0 to infinity but do not increase linearly) in to a straight line (<a href="#fig-plodd" class="quarto-xref">Figure&nbsp;9</a>).</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: what are logarithms?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sticky">
<p><strong>Essentials of logarithms</strong></p>
<p>A logarithm is a mathematical way to write any positive number as a power of a “base number”.</p>
</div>
<p><strong>Log base 10</strong></p>
<p>Consider the base number 10. The R function implementing the logarithm base 10 is <code>log10()</code>.</p>
<p>To what power do I need to raise the base number 10 in order to obtain the desired number 100?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log10</span>(<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>log10(100) = 2 as we need to raise 10 to the power of 2 in order to obtain the desired number 100.</p>
<p>To what power do I need to raise the base number 10 in order to obtain the desired number 1000?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log10</span>(<span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>log10(1000) = 3 as we need to raise 10 to the power of 3 in order to obtain the desired number 1000.</p>
<p>Note that you can use this to write any desired number as a power of 10. For example, to which power do we raise 10 in order to obtain 13.5?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log10</span>(<span class="fl">13.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.130334</code></pre>
</div>
</div>
<p>So this is telling us that <span class="math inline">\(10^{1.130334} = 13.5\)</span> (with rounding error)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span><span class="sc">^</span><span class="fl">1.130334</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.50001</code></pre>
</div>
</div>
<p>An important property is that:</p>
<p><span class="math display">\[10^{\log_{10}(x)} = x\]</span></p>
<p>For example, <span class="math inline">\(10^{\log_{10}(100)} = 10^{2} = 100\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span><span class="sc">^</span><span class="fu">log10</span>(<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100</code></pre>
</div>
</div>
<p><strong>Natural Logarithms (aka Log base e)</strong></p>
<p>A special number in mathematics is Euler’s (or Napier’s) number <span class="math inline">\(e = 2.718282...\)</span>. As well as a logarithm in base 10, telling us which power to raise the base 10 to, in order to obtain a desired number, we can also use any other base, such as <span class="math inline">\(e\)</span>.</p>
<p>The logarithm with base number <span class="math inline">\(e\)</span> is implemented in the R function <code>log()</code>.</p>
<p>To which number do I need to raise <span class="math inline">\(e\)</span> in order to obtain 8?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.079442</code></pre>
</div>
</div>
<p>So this is telling us that <span class="math inline">\(e^{2.079442} = 8\)</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fl">2.718282</span><span class="sc">^</span><span class="fl">2.079442</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.000005</code></pre>
</div>
</div>
<p>Our property is preserved: <span class="math display">\[e^{\log(x)} = x\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fl">2.718282</span><span class="sc">^</span><span class="fu">log</span>(<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.000001</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plodd" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plodd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-plodd-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plodd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Probability, Odds, and Log-Odds
</figcaption>
</figure>
</div>
</div>
</div>
<div class="sticky">
<p><strong>Conversions</strong></p>
<p>Between probabilities, odds and log-odds (“logit”):</p>
<p><span class="math display">\[\begin{align}
&amp;\text{for probability p of Y for observation i:}\\
\qquad \\
odds_i &amp; = \frac{p_i}{1-p_i} \\
\qquad \\
logit_i &amp;= ln(odds_i) = ln(\frac{p_i}{1-p_i}) \\
\qquad \\
p_i &amp; = \frac{odds_i}{1 + odds_i} = \frac{e^{logit_i}}{(1+e^{logit_i})}

\end{align}\]</span></p>
</div>
<p><strong>Counts and log-counts</strong><br>
We can apply the same log transformation to count data in order to think about how we might consider an association on a linear scale:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-clcnt" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clcnt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-clcnt-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clcnt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: counts and log(counts)
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><br></p>
<p>This little trick of modelling something via a mapping from the outcome variable to the model (i.e.&nbsp;logit, or log) is what underpins the <strong>generalized linear model</strong>. It allows us to be able to talk about <em>linear</em> associations between predictors and the <em>log-odds of an event</em> (or between predictors and <em>log-counts</em>). In <a href="#fig-plodd" class="quarto-xref">Figure&nbsp;9</a>, and <a href="#fig-clcnt" class="quarto-xref">Figure&nbsp;10</a> above, we can see that by talking in terms of log-odds (or log-counts), we can model something that is <em>linear</em> and <em>unbounded</em>. So when we think about these models, what we are really have in mind is that we are capturing the associations seen in the right hand plots of <a href="#fig-plodd" class="quarto-xref">Figure&nbsp;9</a> and <a href="#fig-clcnt" class="quarto-xref">Figure&nbsp;10</a>.</p>
<p>As we will see below we can even convert our coefficients into something at least a little more interpretable than “log-odds” (but doing so comes at the expense of losing the ‘linearity’ of the association).</p>
<div class="sticky">
<p><strong>The Generalized Linear Model (GLM)</strong></p>
<p>In its general form, the GLM looks pretty similar to the standard LM.<br>
we can write it as:</p>
<p><span class="math display">\[
\color{green}{g(}\color{red}{y}\color{green}{)} = \mathbf{\color{blue}{b_0 + b_1 \cdot x_1 + ... + b_p \cdot x_p} }
\]</span> The difference is that <span class="math inline">\(\color{green}{g()}\)</span> is a function (like log, or logit) that links the expected value of <span class="math inline">\(\color{red}{y}\)</span> to the linear prediction of <span class="math inline">\(\color{blue}{b_0 + b_1 \cdot x_1 + ... + b_p \cdot x_k}\)</span>.</p>
</div>
<p><br></p>
</section>
<section id="fitting-glm-in-r" class="level1">
<h1>Fitting GLM in R</h1>
<p>In order to fit these models in R, we need to use the <code>glm()</code> function. This is (unsurprisingly) a generalized form of the <code>lm()</code> function we have already been using. The only difference is that we need to also tell the function the <code>family</code> of the outcome variable, and the “link function” (the mapping we use to get from the thing we want to model to the thing we <em>actually</em> model, e.g.&nbsp;<code>"log"</code>, or <code>"logit"</code>).</p>
<div class="sticky">
<p><strong>Linear Regression</strong><br>
Outcome <span class="math inline">\(y\)</span> is continuous, <span class="math inline">\(y \in (-\infty, \infty)\)</span></p>
<p><span class="math display">\[
\color{red}{y} = \mathbf{\color{blue}{b_0 + b_1 \cdot x_1 + ... + b_p \cdot x_p}}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>linear_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(continuous_y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> ... <span class="sc">+</span> xp, <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>As it happens, <code>lm()</code> is just a special case of <code>glm()</code>, where we use the “gaussian” family (Gaussian is another term for ‘normal’), with the “identity” link function (the identity function is just saying ‘model y directly’):</em></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glm</span>(continuous_y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> ... <span class="sc">+</span> xp, <span class="at">data =</span> df,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">family =</span> <span class="fu">gaussian</span>(<span class="at">link =</span> <span class="st">"identity"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="sticky">
<p><strong>Logistic Regression</strong><br>
Outcome <span class="math inline">\(y\)</span> is binary, <span class="math inline">\(y \in [0,1]\)</span><br>
<span class="math display">\[
\begin{align}
\color{red}{ln \left( \frac{p}{1-p} \right) } &amp;= \mathbf{\color{blue}{b_0 + b_1 \cdot x_1 + ... + b_p \cdot x_p}} \\
\qquad \\
\text{where } \color{red}{p} &amp;= \text{probability of event }y\\
\end{align}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>logistic_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(binary_y <span class="sc">~</span>  <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> ... <span class="sc">+</span> xp, <span class="at">data =</span> df,</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span><span class="st">"logit"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>just putting <code>family = binomial</code> and <code>family = "binomial"</code> will also work (and they will by default use the “logit” link).<br>
</li>
<li>the outcome can either be 0s and 1s, or coded as a factor with 2 levels.</li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: binomial? binary?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We’ve seen the “binomial” distribution before (think “number of heads in 20 coin-flips” in <a href="https://uoepsy.github.io/usmr/2324/lectures/lecture04.html#/binomial-distribution" target="_blank">Lecture 4!</a>).</p>
<p>The binomial distribution can be used to model the number of successes in a sequence of <span class="math inline">\(n\)</span> independent trials. If we have a binary variable, this is a special case of the binomial, where <span class="math inline">\(n = 1\)</span>.</p>
<p>The binomial logistic regression model, more generally, can be written as:</p>
<p><span class="math display">\[
\begin{align}
\color{red}{ln \left( \frac{p}{1-p} \right) } &amp;= \mathbf{\color{blue}{b_0 + b_1 \cdot x_1 + ... + b_p \cdot x_p}} \\
\qquad \\
\text{where } Y &amp;\sim Binomial(n, \color{red}{p})\\
\end{align}
\]</span></p>
<p>We can fit a more general binomial logistic regression model with any <span class="math inline">\(n\)</span> by specifying our outcome in terms of two things: the number of successes and the number of failures.<br>
This can be useful if, for instance, we have an outcome that is something like “the number of correct responses from a set of 20 questions”:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>  particpant nr_correct nr_incorrect  x1  x2
1       ppt1         17            3 ... ...
2       ppt2         14            6 ... ...
3       ppt3         11            9 ... ...
4       ppt4         16            4 ... ...
5        ...        ...          ... ... ...</code></pre>
</div>
</div>
<p>We can fit a model with this using <code>cbind()</code> to combine the two columns that together represent the outcome:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glm</span>(<span class="fu">cbind</span>(nr_correct, nr_incorrect) <span class="sc">~</span> x1 <span class="sc">+</span> ... <span class="sc">+</span> xp, <span class="at">data =</span> df,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span><span class="st">"logit"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</div>
<div class="sticky">
<p><strong>Poisson Regression</strong><br>
Outcome <span class="math inline">\(y\)</span> is positive <span class="math inline">\(y \in  (0, \infty)\)</span> <span class="math display">\[
\color{red}{ln (y) } = \mathbf{\color{blue}{b_0 + b_1(x_1) + ... + b_k(x_k)}}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(count_y <span class="sc">~</span>  <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> ... xk, <span class="at">data =</span> df,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">family=</span><span class="fu">poisson</span>(<span class="at">link=</span><span class="st">"log"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>family = poisson</code> and <code>family = "poisson"</code> will also work</li>
</ul>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: model estimation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For a linear regression model, R has been fitting our regression models by “minimising the residual sums of squares” (i.e., we rotate the line to find the point at which <span class="math inline">\(\sum{(y - \hat{y})^2}\)</span> is smallest. This gave us the “best fitting line” (<a href="#fig-resslineplot" class="quarto-xref">Figure&nbsp;11</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-resslineplot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resslineplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-resslineplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resslineplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: linear regression minimises the sum of squared residuals
</figcaption>
</figure>
</div>
</div>
</div>
<p>For the generalized linear models we can’t do this. For instance, in logistic regression model, what we’re really wanting is the “best fitting <em>squiggle</em>” (<a href="#fig-loglineplot" class="quarto-xref">Figure&nbsp;12</a>), and to get to this we must do something else other than looking at our residuals <span class="math inline">\(y - \hat{y}\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-loglineplot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-loglineplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-loglineplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-loglineplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Modelling the probability of Y across values of X requires fitting a squiggle
</figcaption>
</figure>
</div>
</div>
</div>
<p>Remember that the model is that we are actually fitting is a “logistic model” - i.e.&nbsp;we are fitting things with respect to “log-odds”.</p>
<p>But for our actual observations, the event has either happened or it hasn’t, so our observed values <span class="math inline">\(y_i\)</span> aren’t really “probabilities” which we can translate into log-odds. In fact, our observed values of 0 and 1, when translated into log odds, become -Infinity and +Infinity (attempted visual in <a href="#fig-mlelogodd" class="quarto-xref">Figure&nbsp;13</a>). This would mean our residuals would also all be infinity, and so it becomes impossible to work out anything!</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  observed odds  log_odds
  &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;   
1 0        0     -Inf    
2 1        Inf   Inf     
3 ...      ...   ...     </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mlelogodd" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlelogodd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-mlelogodd-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlelogodd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: In the log-odds world, comparing our predicted values to observed values of -Inf and Inf isn’t very useful, because all those distances will be infinite (there is no way of measuring the dotted lines, so we can’t really use them)
</figcaption>
</figure>
</div>
</div>
</div>
<p>Instead, <strong>maximum likelihood estimation</strong> is used to find the set of coefficients which best reproduce the observed data. To do this, the computer considers loads of different lines, trying to converge on the one which <em>maximises the probability of observing the data that we have</em>.</p>
<p>To understand this a bit better, let’s take consider one possible line in the probability world. The left-hand plot of <a href="#fig-mleprob" class="quarto-xref">Figure&nbsp;14</a> is the same line as the one shown in <a href="#fig-mlelogodd" class="quarto-xref">Figure&nbsp;13</a>, and we can see it translated back into probabilities in the right-hand plot, so that we have a predicted probability of the outcome for each datapoint. From the right-hand plot, we can then ask “what is the probability of seeing our data, given this line?”. To get this, we multiply up all the probabilities that observed 1s are predicted as 1s and that observed 0s predicted as 0s.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mleprob" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mleprob-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-mleprob-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mleprob-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Note - the dotted lines are not residuals, but just to show the projections of observations down to the line
</figcaption>
</figure>
</div>
</div>
</div>
<p>As an example <a href="#fig-mleprob2" class="quarto-xref">Figure&nbsp;15</a> shows the predicted probabilities for a couple of datapoints. The furthest left point is an observed 0, and so the probability of seeing this datapoint (according to the line we’ve drawn) is 1-0.16, or 0.84. The furthest right is an observed 1, so according to our line, the probability of seeing this datapoint as a 1 is 0.98. This means the probability of seeing those two datapoints, given the line we have, is 0.98 * 0.84. But what we want is the probability of seeing <em>all</em> our data, given this line, so we need to do this for <em>all</em> of our datapoints.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Once we have this, we can compare the probability of seeing all our data for this line, and for a different candidate line, and for a whole range of different lines.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mleprob2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mleprob2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10a_glm_files/figure-html/fig-mleprob2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mleprob2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Note - the dotted lines are not residuals, but just to show the projections of observations down to the line
</figcaption>
</figure>
</div>
</div>
</div>
<p>The cool thing is that computers do all this for us. <em>Maximum likelihood estimation (MLE)</em> is just a method to find out which parameters maximise the probability of seeing our data. MLE can be used for all sorts of models, but in the context of a logistic regression, we use it to find the values of coefficients <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> in our model <span class="math inline">\(\color{red}{ln\left(\frac{p}{1-p} \right)} = \color{blue}{b_0 \cdot{} 1 + b_1 \cdot{} x_1 }\)</span> that have the maximum likelihood of reproducing the data that we have observed.</p>
</div>
</div>
</div>
</section>
<section id="marshmallows" class="level1">
<h1>Marshmallows</h1>
<p>Let’s suppose we conduct an experiment in which we replicate the <a href="https://youtu.be/JSRmdzofkio?si=Po_kwp16am60ZQ78" target="_blank">Stanford Marshmallow Experiment</a>. 100 children took part, ranging from ages 3 to 10 years old. Each child was shown a marshmallow, and it was explained that they were about to be left alone for 10 minutes. They were told that they were welcome to eat the marshmallow while they were waiting, but if the marshmallow was still there after 10 minutes, they would be rewarded with <strong>two</strong> marshmallows.</p>
<p>We’re interested in how the ability to wait to obtain something that one wants develops with age (which was measured in months, but we have converted it to years).</p>
<p>Our outcome variable here is “whether or not the child takes the marshmallow”, and we have one continuous predictor (age).</p>
<p>Here is our data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mallow <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/mallow.csv"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mallow, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>taken))<span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span>.<span class="dv">5</span>, <span class="at">size=</span><span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Age (years)"</span>, <span class="at">y =</span> <span class="st">"Takes Marshmallow"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Practically speaking, fitting our logistic regression model is very straightforward, and the summary output looks fairly similar. We can also easily compare models in a similar (but not identical) way as we have done with linear models. The differences come in when we interpreting the coefficients from these models, and how we compare models to one another.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>mallowmod <span class="ot">&lt;-</span> <span class="fu">glm</span>(taken <span class="sc">~</span> age, <span class="at">data =</span> mallow,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family=</span>binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="comparing-models" class="level1">
<h1>Comparing models</h1>
<p>As we have seen with our linear regression models, we can examine whether certain variables (or <em>sets</em> of variables collectively) are useful in explaining our outcome variable, by comparing a model with a simpler “restricted” model without those variables.</p>
<p>For linear regression models, this involved examining the ‘reduction in residual sums of squares’, which resulted in an <span class="math inline">\(F\)</span> statistic.</p>
<p>In the generalized linear model world, we don’t have straightforward residuals, and we compare models on a different metric, known as <strong>deviance</strong>. With a big enough sample size, reductions in deviance are <span class="math inline">\(\chi^2\)</span> distributed, meaning that we can compare them to an appropriate <span class="math inline">\(\chi^2\)</span> distribution to compute a p-value.</p>
<p>For instance, we can compare our model to the null model (i.e.&nbsp;just an intercept):</p>
<p>In R we do this comparison as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>mallowmod0 <span class="ot">&lt;-</span> <span class="fu">glm</span>(taken <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mallow, <span class="at">family=</span>binomial)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>mallowmod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(taken <span class="sc">~</span> age, <span class="at">data =</span> mallow, <span class="at">family=</span>binomial)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mallowmod0, mallowmod1, <span class="at">test =</span> <span class="st">'Chisq'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: taken ~ 1
Model 2: taken ~ age
  Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
1        99     138.59                          
2        98     111.21  1   27.377 1.674e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The output shows the two fitted models, and reports the <em>Residual Deviance</em> of each model, 138.6 and 111.2 respectively. So by adding the predictor <code>age</code> to the model, we reduce our deviance from 138.6 to 111.2, i.e.&nbsp;we reduce it by 27.4 (remember, deviance is like badness-of-fit, so smaller is better).</p>
<p>Is this reduction big enough to be more than just due to random sampling variation? This is what the chi-squared test tells us!<br>
The <code>Pr(&gt;Chi)</code> column is our <span class="math inline">\(p\)</span>-value. It tells us that if in the population the predictor <code>age</code> were unrelated to taking the marshmallow, it would be very unlikely to see a reduction in deviance as big as or bigger than the one we have seen.</p>
<div class="sticky">
<p><strong>What is deviance?</strong></p>
<p>Deviance is a measure of deviation/discrepancy/mismatch between the data and the model. You can think of it as a generalisation of the terms making up the residual sum of squares in simple linear regression, in that it measures the misfit, or <em>badness of fit</em>. This means (as it was for the residual sum of squares) that smaller deviance is better!</p>
<p>More technically, deviance is calculated as -2 times the log-likelihood.</p>
<ul>
<li>Likelihood = <span class="math inline">\(P(data | model)\)</span> (the probability of seeing the sample data, given our model parameters). If we had a <em>perfect</em> model, this would be 1.
<ul>
<li>if you want a (slightly) more in depth look at “likelihood”, see <a href="lvp.html" target="_blank">here</a>.</li>
</ul></li>
<li>Log-likelihood = the log of the likelihood. The log transformation means that where likelihood ranges from 0 to 1, log-likelihood ranges from negative infinity to 0 (0 would be the perfect model)</li>
<li>-2Log-likelihood = turns it from negative to positive, and allows us to test it against a <span class="math inline">\(\chi^2\)</span> distribution.</li>
</ul>
</div>
<!-- Above was Drop-in-deviance GOF test -->
<!-- # Deviance GOF test -->
<!-- mdl_sat = glm(senility ~ factor(1:nrow(sen)), family = binomial, data = sen) -->
<!-- anova(mdl1, mdl_sat, test = 'Chisq') -->
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: Akaike and Bayesian Information Criteria
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Deviance measures lack of fit, and it can be reduced to zero by making the model more and more complex, effectively estimating the value at each single data point.</p>
<p>However, this involves adding more and more predictors, which makes the model more complex (and less interpretable).</p>
<p>Typically, simpler models are preferred when they still explain the data almost as well. This is why information criteria were devised, exactly to account for both the model misfit but also its complexity.</p>
<p><span class="math display">\[
\text{Information Criterion} = \text{Deviance} + \text{Penalty for model complexity}
\]</span></p>
<p>Depending on the chosen penalty, you get different criteria. Two common ones are the Akaike and Bayesian Information Criteria, AIC and BIC respectively: <span class="math display">\[
\begin{aligned}
\text{AIC} &amp;= \text{Deviance} + 2 p \\
\text{BIC} &amp;= \text{Deviance} + p \log(n)
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(p\)</span> is the number of coefficients in the model. <strong>Models that produce smaller values of these fitting criteria should be preferred.</strong></p>
<p>AIC and BIC differ in their degrees of penalization for number of regression coefficients, with BIC usually favouring models with fewer terms.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mallowmod0, mallowmod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           df      AIC
mallowmod0  1 140.5894
mallowmod1  2 115.2121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(mallowmod0, mallowmod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           df      BIC
mallowmod0  1 143.1946
mallowmod1  2 120.4224</code></pre>
</div>
</div>
<p>According to both AIC and BIC the model with <code>age</code> as a predictor has a lower score, meaning it’s preferable to the other.</p>
</div>
</div>
</div>
</section>
<section id="coefficient-interpretation" class="level1">
<h1>Coefficient Interpretation</h1>
<p>An important result of our model capturing the linear associations between the predictors and the <strong>log-odds of outcome Y</strong>, is that our coefficients are all in these units.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mallowmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = taken ~ age, family = binomial, data = mallow)
...
Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   3.7642     0.8539   4.408 1.04e-05 ***
age          -0.6247     0.1367  -4.570 4.87e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="thnfprzjcs" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#thnfprzjcs table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#thnfprzjcs thead, #thnfprzjcs tbody, #thnfprzjcs tfoot, #thnfprzjcs tr, #thnfprzjcs td, #thnfprzjcs th {
  border-style: none;
}

#thnfprzjcs p {
  margin: 0;
  padding: 0;
}

#thnfprzjcs .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#thnfprzjcs .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#thnfprzjcs .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#thnfprzjcs .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#thnfprzjcs .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#thnfprzjcs .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#thnfprzjcs .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#thnfprzjcs .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#thnfprzjcs .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#thnfprzjcs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#thnfprzjcs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#thnfprzjcs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#thnfprzjcs .gt_spanner_row {
  border-bottom-style: hidden;
}

#thnfprzjcs .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#thnfprzjcs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#thnfprzjcs .gt_from_md > :first-child {
  margin-top: 0;
}

#thnfprzjcs .gt_from_md > :last-child {
  margin-bottom: 0;
}

#thnfprzjcs .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#thnfprzjcs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#thnfprzjcs .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#thnfprzjcs .gt_row_group_first td {
  border-top-width: 2px;
}

#thnfprzjcs .gt_row_group_first th {
  border-top-width: 2px;
}

#thnfprzjcs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#thnfprzjcs .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#thnfprzjcs .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#thnfprzjcs .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#thnfprzjcs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#thnfprzjcs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#thnfprzjcs .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#thnfprzjcs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#thnfprzjcs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#thnfprzjcs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#thnfprzjcs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#thnfprzjcs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#thnfprzjcs .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#thnfprzjcs .gt_left {
  text-align: left;
}

#thnfprzjcs .gt_center {
  text-align: center;
}

#thnfprzjcs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#thnfprzjcs .gt_font_normal {
  font-weight: normal;
}

#thnfprzjcs .gt_font_bold {
  font-weight: bold;
}

#thnfprzjcs .gt_font_italic {
  font-style: italic;
}

#thnfprzjcs .gt_super {
  font-size: 65%;
}

#thnfprzjcs .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#thnfprzjcs .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#thnfprzjcs .gt_indent_1 {
  text-indent: 5px;
}

#thnfprzjcs .gt_indent_2 {
  text-indent: 10px;
}

#thnfprzjcs .gt_indent_3 {
  text-indent: 15px;
}

#thnfprzjcs .gt_indent_4 {
  text-indent: 20px;
}

#thnfprzjcs .gt_indent_5 {
  text-indent: 25px;
}

#thnfprzjcs .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#thnfprzjcs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="coefficient" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">coefficient</th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">estimate</th>
<th id="interpretation" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">interpretation</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="coefficient">(Intercept)</td>
<td class="gt_row gt_right" headers="estimate">3.76</td>
<td class="gt_row gt_left" headers="interpretation">the log-odds of taking the marshmallow for a child aged zero is 3.76</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="coefficient">age</td>
<td class="gt_row gt_right" headers="estimate">-0.62</td>
<td class="gt_row gt_left" headers="interpretation">being 1 year older is associated with a -0.62 decrease in the log-odds of a child taking the marshmallow</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>If you’re anything like me, these are not the most useful interpretations. I have no idea what decreasing -0.62 log-odds means in any practical terms.</p>
<p>What we can do instead is translate these back into odds, which might make things easier. The opposite of the natural <strong>logarithm</strong> is the <strong>exponential</strong> (see <a href="https://mathonweb.com/help_ebook/functions.htm#functions_3" target="_blank">here</a> if you’re interested). We can turn <span class="math inline">\(log(x)\)</span> back into <span class="math inline">\(x\)</span> by raising <span class="math inline">\(e\)</span> to the power of it: <span class="math inline">\(e^{\log(x)} = x\)</span>. In R, this is just the two functions <code>log()</code> and <code>exp()</code>: <code>exp(log(2)) == 2</code>.</p>
<p>This means we can turn our <em>log-odds</em> back into <em>odds</em> by using <code>exp()</code> on our coefficients! A crucial thing to note is that <em>addition</em> on the log-odds scale translates to <em>multiplication</em> on the odds scale. So while a coefficient on the log-odds scale is interpreted the same way as we interpret normal linear regression coefficients, when we convert these to odds using <code>exp()</code>, the effect is in terms of how much the odds get <strong>multiplied</strong> by.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="yvphebhiqp" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#yvphebhiqp table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#yvphebhiqp thead, #yvphebhiqp tbody, #yvphebhiqp tfoot, #yvphebhiqp tr, #yvphebhiqp td, #yvphebhiqp th {
  border-style: none;
}

#yvphebhiqp p {
  margin: 0;
  padding: 0;
}

#yvphebhiqp .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#yvphebhiqp .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#yvphebhiqp .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#yvphebhiqp .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#yvphebhiqp .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yvphebhiqp .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yvphebhiqp .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yvphebhiqp .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#yvphebhiqp .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#yvphebhiqp .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#yvphebhiqp .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#yvphebhiqp .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#yvphebhiqp .gt_spanner_row {
  border-bottom-style: hidden;
}

#yvphebhiqp .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#yvphebhiqp .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#yvphebhiqp .gt_from_md > :first-child {
  margin-top: 0;
}

#yvphebhiqp .gt_from_md > :last-child {
  margin-bottom: 0;
}

#yvphebhiqp .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#yvphebhiqp .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#yvphebhiqp .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#yvphebhiqp .gt_row_group_first td {
  border-top-width: 2px;
}

#yvphebhiqp .gt_row_group_first th {
  border-top-width: 2px;
}

#yvphebhiqp .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yvphebhiqp .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#yvphebhiqp .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#yvphebhiqp .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yvphebhiqp .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yvphebhiqp .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#yvphebhiqp .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#yvphebhiqp .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#yvphebhiqp .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yvphebhiqp .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yvphebhiqp .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#yvphebhiqp .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yvphebhiqp .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#yvphebhiqp .gt_left {
  text-align: left;
}

#yvphebhiqp .gt_center {
  text-align: center;
}

#yvphebhiqp .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#yvphebhiqp .gt_font_normal {
  font-weight: normal;
}

#yvphebhiqp .gt_font_bold {
  font-weight: bold;
}

#yvphebhiqp .gt_font_italic {
  font-style: italic;
}

#yvphebhiqp .gt_super {
  font-size: 65%;
}

#yvphebhiqp .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#yvphebhiqp .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#yvphebhiqp .gt_indent_1 {
  text-indent: 5px;
}

#yvphebhiqp .gt_indent_2 {
  text-indent: 10px;
}

#yvphebhiqp .gt_indent_3 {
  text-indent: 15px;
}

#yvphebhiqp .gt_indent_4 {
  text-indent: 20px;
}

#yvphebhiqp .gt_indent_5 {
  text-indent: 25px;
}

#yvphebhiqp .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#yvphebhiqp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="what" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">what</th>
<th id="interpretation" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">interpretation</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="what">linear regression lm()</td>
<td class="gt_row gt_left" headers="interpretation">if you go up 1 on X you add [b] on Y</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="what">logistic regrssion glm(), coefficients in log-odds</td>
<td class="gt_row gt_left" headers="interpretation">if you go up 1 on X you add [b] on log-odds(Y)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="what">logistic regression glm(), exponentiated coefficients</td>
<td class="gt_row gt_left" headers="interpretation">if you go up 1 on X, your odds are *multiplied by* [exp(b)]</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>For our marshmallow study, we can see our exponentiated coefficients here:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(mallowmod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
  43.129646    0.535418 </code></pre>
</div>
</div>
<p>The intercept is now the odds of a child aged zero taking the marhsmallow: 43.13. This means that we estimate for every 44.13 children aged zero, we would expect 43.13 of them to take the marshmallow, and 1 of them to not take it.</p>
<p>Our coefficient for <code>age</code> tells us that we estimate that for every year older a child is, the odds of them taking the marhsmallow are <em>multiplied</em> by 0.54.</p>
<p>The exponentiated coefficient for <code>age</code> here is referred to as an “odds ratio”.</p>
<div class="sticky">
<p><strong>Odds Ratios</strong></p>
<p>When we exponentiate coefficients from a model fitted to the log-odds, the resulting association is referred to as an “odds ratio” (OR).</p>
<p>There are various ways of describing odds ratios:</p>
<ul>
<li>“for a 1 unit increase in <span class="math inline">\(x\)</span> the odds of <span class="math inline">\(y\)</span> change by <em>a ratio</em> of <code>exp(b)</code>”<br>
</li>
<li>“for a 1 unit increase in <span class="math inline">\(x\)</span> the odds of <span class="math inline">\(y\)</span> are multiplied by <code>exp(b)</code>”<br>
</li>
<li>“for a 1 unit increase in <span class="math inline">\(x\)</span> there are <code>exp(b)</code> increased/decreased odds of <span class="math inline">\(y\)</span>”</li>
</ul>
<p>Instead of thinking of a coefficient of 0 as indicating “no association”, in odds ratios this when the OR = 1.</p>
<ul>
<li><strong>OR = 1</strong> : equal odds (<span class="math inline">\(1 \times odds = odds \text{ don't change}\)</span>).</li>
<li><strong>OR &lt; 1</strong> : decreased odds (<span class="math inline">\(0.5 \times odds = odds \text{ are halved}\)</span>)</li>
<li><strong>OR &gt; 1</strong> : increased odds (<span class="math inline">\(2 \times odds = odds \text{ are doubled}\)</span>)</li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
OR are not “exp(b) times more likely”
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Often you will hear people interpreting odds ratios as “<span class="math inline">\(y\)</span> is <code>exp(b)</code> times as likely”.<br>
Although it is true that increased odds is an increased likelihood of <span class="math inline">\(y\)</span> occurring, double the odds does not mean you will see <em>twice</em> as many occurrences of <span class="math inline">\(y\)</span> - i.e.&nbsp;it does not translate to doubling the probability.</p>
<p>Here’s a little more step-by-step explanation to explain:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="hzksnoifxo" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#hzksnoifxo table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hzksnoifxo thead, #hzksnoifxo tbody, #hzksnoifxo tfoot, #hzksnoifxo tr, #hzksnoifxo td, #hzksnoifxo th {
  border-style: none;
}

#hzksnoifxo p {
  margin: 0;
  padding: 0;
}

#hzksnoifxo .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hzksnoifxo .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hzksnoifxo .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hzksnoifxo .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hzksnoifxo .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hzksnoifxo .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hzksnoifxo .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hzksnoifxo .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hzksnoifxo .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hzksnoifxo .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hzksnoifxo .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hzksnoifxo .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hzksnoifxo .gt_spanner_row {
  border-bottom-style: hidden;
}

#hzksnoifxo .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hzksnoifxo .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hzksnoifxo .gt_from_md > :first-child {
  margin-top: 0;
}

#hzksnoifxo .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hzksnoifxo .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hzksnoifxo .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hzksnoifxo .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hzksnoifxo .gt_row_group_first td {
  border-top-width: 2px;
}

#hzksnoifxo .gt_row_group_first th {
  border-top-width: 2px;
}

#hzksnoifxo .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hzksnoifxo .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hzksnoifxo .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hzksnoifxo .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hzksnoifxo .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hzksnoifxo .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hzksnoifxo .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hzksnoifxo .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hzksnoifxo .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hzksnoifxo .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hzksnoifxo .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hzksnoifxo .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hzksnoifxo .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hzksnoifxo .gt_left {
  text-align: left;
}

#hzksnoifxo .gt_center {
  text-align: center;
}

#hzksnoifxo .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hzksnoifxo .gt_font_normal {
  font-weight: normal;
}

#hzksnoifxo .gt_font_bold {
  font-weight: bold;
}

#hzksnoifxo .gt_font_italic {
  font-style: italic;
}

#hzksnoifxo .gt_super {
  font-size: 65%;
}

#hzksnoifxo .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hzksnoifxo .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hzksnoifxo .gt_indent_1 {
  text-indent: 5px;
}

#hzksnoifxo .gt_indent_2 {
  text-indent: 10px;
}

#hzksnoifxo .gt_indent_3 {
  text-indent: 15px;
}

#hzksnoifxo .gt_indent_4 {
  text-indent: 20px;
}

#hzksnoifxo .gt_indent_5 {
  text-indent: 25px;
}

#hzksnoifxo .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#hzksnoifxo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="coefficient" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">coefficient</th>
<th id="b" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">b</th>
<th id="exp(b)" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">exp(b)</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="coefficient">(Intercept)</td>
<td class="gt_row gt_right" headers="b">3.76</td>
<td class="gt_row gt_right" headers="exp(b)">43.13</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="coefficient">age</td>
<td class="gt_row gt_right" headers="b">-0.62</td>
<td class="gt_row gt_right" headers="exp(b)">0.54</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<ol type="1">
<li>For children aged 2 years old the log-odds of them taking the marshmallow are 3.76 + -0.62*2 = 2.52.<br>
</li>
<li>Translating this to odds, we exponentiate it, so the odds of them taking the marshmallow are <span class="math inline">\(e^{(3.76 + -0.62*2)} = e^{2.52} = 12.43\)</span>.<br>
(This is the same<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> as <span class="math inline">\(e^{3.76} \times e^{-0.62*2}\)</span>)<br>
</li>
<li>These odds of 12.43 means that (rounded to nearest whole number) if we take 13 children aged 2 years, we would expect 12 of them to take the marshmallow, and 1 to not take it.<br>
</li>
<li>If we consider how the odds change for every extra year of age (i.e.&nbsp;for 3 year old as opposed to 2 year old children):
<ul>
<li>the log-odds of taking the marshmallow decrease by -0.62.<br>
</li>
<li>the odds of taking the marshmallow are multiplied by 0.54.<br>
</li>
<li>so for a 3 year old child, the odds are <span class="math inline">\(12.43 \times 0.54 = 6.69\)</span>.<br>
(And we can also calculate this as <span class="math inline">\(e^{2.52 + -0.62}\)</span>)<br>
</li>
</ul></li>
<li>So we have gone from odds of 12.4-to-1 for 2 year olds, and 6.7-to-1 for 3 year olds. The odds have been multiplied by 0.54.<br>
But those odds, when converted to probability, these are 0.93 and 0.87. So <span class="math inline">\(0.54 \times odds\)</span> is not <span class="math inline">\(0.54 \times probability\)</span>.</li>
</ol>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
the intercept (but not slopes) can be converted to a probability
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because our intercept is at a single point (it’s not an <em>association</em>), we can actually convert this to a probability. Remember that <span class="math inline">\(odds = \frac{p}{1-p}\)</span>, which means that <span class="math inline">\(p = \frac{odds}{1 + odds}\)</span>. So the probability of taking the marshmallow for a child aged zero is <span class="math inline">\(\frac{43.13}{1 + 43.13} = 0.98\)</span>.</p>
<p>Unfortunately, we can’t do the same for any slope coefficients. This is because while the intercept is “odds”, the slopes are “odds ratios” (i.e.&nbsp;changes in odds), and changes in odds are different at different levels of probability.</p>
<p>Consider how when we multiply odds by 2, the increase in probability is not constant:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Odds</th>
<th>Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.5</td>
<td><span class="math inline">\(\frac{1}{1+0.5} = 0.33\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\(\frac{1}{1+1} = 0.5\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\(\frac{2}{1+2} = 0.66\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\(\frac{4}{1+4} = 0.8\)</span></td>
</tr>
<tr class="odd">
<td>8</td>
<td><span class="math inline">\(\frac{8}{1+8} = 0.88\)</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="coefficient-tests-intervals" class="level1">
<h1>Coefficient tests &amp; intervals</h1>
<div class="statbox">
<p><strong>Coefficient Tests</strong></p>
<p>You might notice that the summary output of our logistic regression model has <span class="math inline">\(z\)</span> statistics instead of <span class="math inline">\(t\)</span> statistics. However, the logic of the tests remains just the same as it was for the linear model (and for all the tests we have done thus far) - it is a test against the null hypothesis that the coefficient is zero. Or, less formally, we can think of the corresponding p-value as “in the null universe where there is no relationship between <span class="math inline">\(x\)</span> and the occurrence of event <span class="math inline">\(y\)</span>, there is a <code>p-value</code> chance of seeing a sample of this size with an association as strong as the one we have got”</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mallowmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   3.7642     0.8539   4.408 1.04e-05 ***
age          -0.6247     0.1367  -4.570 4.87e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="int">
<p>For every additional month older a child is, the odds of them taking the marshmallow decreased by 0.54 (<span class="math inline">\(z = -4.57\)</span>, <span class="math inline">\(p &lt; .001\)</span>).</p>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: why z not t?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In <em>linear</em> regression, we have to estimate the variance of the residuals (<span class="math inline">\(\sigma^2\)</span> - we could get out the standard deviation <span class="math inline">\(\sigma\)</span> using <code>sigma(model)</code>). This term then went in to the calculation of the standard errors of our coefficients.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> But we are <em>estimating</em> the residual variance, so instead of using <span class="math inline">\(\sigma\)</span> (the population residual variance) we are really using <span class="math inline">\(s\)</span> (a sample estimate). This means we are going to be less certain with smaller samples (it’s the exact same thing as when we first learned about <span class="math inline">\(t\)</span> in <a href="03b_inference2.html#t---distributions" target="_blank">3B #t-distributions</a>).</p>
<p>In logistic regression, the variance is directly connect to the mean - we don’t have to estimate it separately. If something is binomially distributed with <span class="math inline">\(p\)</span> probability in <span class="math inline">\(n\)</span> trials, then the expected mean is <span class="math inline">\(np\)</span> and the expected variance is <span class="math inline">\(np(1-p)\)</span>. So we don’t actually need to estimate the variance. The upshot here is that we can use <span class="math inline">\(z\)</span> directly instead.</p>
</div>
</div>
</div>
</div>
<div class="statbox">
<p><strong>Confidence Intervals</strong><br>
With all our linear models (generalized or not), we can obtain confidence intervals using the <code>confint()</code> function. Because confidence intervals are just lower and upper bounds for a range of plausible values for our estimates, we can turn these into the confidence intervals around our odds ratios!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(mallowmod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %      97.5 %
(Intercept) 8.8574079 258.1777466
age         0.4015919   0.6889545</code></pre>
</div>
</div>
<div class="int">
<p>For every additional month older a child is, the odds of them taking the marshmallow decreased by 0.54 (95% CI [0.4, 0.69]).</p>
</div>
</div>
</section>
<section id="visualising" class="level1">
<h1>Visualising</h1>
<p>While interpreting coefficients leaves us speaking in the realm of odds-ratios, we can do more with visualisations! This is because we can simply display the predicted probability across values of some predictor. We don’t have to try and rely solely on a numerical description of a relationship - a picture speaks a thousand words (and it’s a lot easier!).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">effect</span>(<span class="at">term =</span> <span class="st">"age"</span>, <span class="at">mod =</span> mallowmod, <span class="at">xlevels =</span> <span class="dv">20</span>) <span class="sc">|&gt;</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>age,<span class="at">y=</span>fit,<span class="at">ymin=</span>lower,<span class="at">ymax=</span>upper))<span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span>.<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: manual plots
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>As with previous plots in linear models, to make plots manually, we need to create a little plotting data frame and then add to that the model estimated values and interval bounds.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>plotdata <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 50 values between 3 and 10 years old</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">seq</span>(<span class="dv">3</span>,<span class="dv">10</span>,<span class="at">length.out=</span><span class="dv">50</span>) </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For these models, we can actually predict on various different scales (e.g.&nbsp;do we want to predict log-odds values (<code>predict(mod, type="link")</code>) or probabilities (<code>predict(mod, type="response")</code>)?</p>
<p>Unfortunately, <code>augment</code> doesn’t easily give us intervals for these models, so we’ll have to make them ourselves. These have to be done on the log-odds scale first. We can’t take the estimated probability and then <span class="math inline">\(\pm\)</span> some number, because then it might go over 1 or below 0.</p>
<p><code>augment()</code> can get us <em>some</em> of the way there. We can get out fitted values (on whatever scale we want, either “link” - the log-odds, or “response” - the probabilities), and we can get out standard errors (on that same scale)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(mallowmod, <span class="at">newdata =</span> plotdata, </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">type.predict =</span> <span class="st">"link"</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">se_fit=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>   age .fitted .se.fit
1    3    1.89    0.47
2 3.14     1.8    0.46
3 3.29    1.71    0.44
4 3.43    1.62    0.42
5  ...     ...     ...</code></pre>
</div>
</div>
<p>Because this gets us the estimate and the standard error, we can then create out interval bounds using <span class="math inline">\(estimate \pm 1.96 \cdot SE\)</span>. The 1.96 is back, because we’re back using <span class="math inline">\(z\)</span> (“normal”) distributions.</p>
<p>However, we’re ultimately wanting to convert these back to probabilities for our plotting. We can do this with something like Martin’s <code>l2p()</code> function in the lecture.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>l2p <span class="ot">&lt;-</span> <span class="cf">function</span>(logits) {</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  odds <span class="ot">&lt;-</span> <span class="fu">exp</span>(logits)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  prob <span class="ot">&lt;-</span> odds<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> odds)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(prob)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(mallowmod, <span class="at">newdata =</span> plotdata, </span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">type.predict =</span> <span class="st">"link"</span>,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">se_fit=</span><span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">.lower =</span> <span class="fu">l2p</span>(.fitted <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>.se.fit),</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">.upper =</span> <span class="fu">l2p</span>(.fitted <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>.se.fit),</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">.fitted =</span> <span class="fu">l2p</span>(.fitted)</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>age,<span class="at">y=</span>.fitted,<span class="at">ymin=</span>.lower,</span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">ymax=</span>.upper))<span class="sc">+</span></span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span>.<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="assumptions" class="level1">
<h1>Assumptions</h1>
<p>Because these models don’t have the same expected error distribution (we don’t expect residuals to be “normally distributed around the mean, with constant variance”), checking the assumptions of logistic regression is a little different.</p>
<p>Typically, we look at the “deviance residuals”. But we <strong>don’t</strong> examine plots for patterns, we simply examine them for potentially outlying observations. If we use a standardised residual, it makes it easier to explore extreme values as we expect most residuals to be within -2, 2 or -3, 3 (depending on how strict we feel).</p>
<div class="statbox">
<p><strong>Deviance Residuals</strong></p>
<p>There are three ways we can get out deviance residuals, each scaled differently</p>
<ul>
<li><span class="math inline">\(i\)</span>th residual = measure of deviance contributed from the <span class="math inline">\(i\)</span>th observation</li>
<li><span class="math inline">\(i\)</span>th standardized residual = residual / SD(residual)</li>
<li><span class="math inline">\(i\)</span>th studentized residual = residual / SD(residual from model fitted without observation <span class="math inline">\(i\)</span>)</li>
</ul>
<p>We get these in R using:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># deviance residuals</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(mallowmod, <span class="at">type =</span> <span class="st">'deviance'</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># studentised residuals</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rstudent</span>(mallowmod, <span class="at">type =</span> <span class="st">'deviance'</span>)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="co"># standardised residuals</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rstandard</span>(mallowmod, <span class="at">type =</span> <span class="st">'deviance'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>We can check whether any residuals are larger than 2 or 3 in absolute value:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rstudent</span>(mallowmod, <span class="at">type =</span> <span class="st">'deviance'</span>), </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">'Studentized Deviance Residuals'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><em><em>Warning:</em> Don’t inspect this plot for patterns!!!</em></p>
<p>There appears to be 1 residual with a value slightly larger than 2 in absolute value. We will keep these in mind and check later if they are also influential points (using <code>cooks.distance</code>)</p>
<p>Sometimes a <strong>binned plot</strong><a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> can be more informative, but not always! It works by combining together all responses for people having the same covariate <span class="math inline">\(x_i\)</span> value, and taking the average studentized Pearson residual for those.</p>
<p>Before using this function, make sure you have installed the <strong>arm</strong> package!</p>
<p>There don’t appear to be any extreme residuals:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>arm<span class="sc">::</span><span class="fu">binnedplot</span>(<span class="fu">fitted</span>(mallowmod), </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rstudent</span>(mallowmod, <span class="at">type =</span> <span class="st">'deviance'</span>),</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">xlab =</span> <span class="st">'Prob. of Taking Marshmallow'</span>, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">ylab =</span> <span class="st">'Studentized Deviance Residuals'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="summary.lm-and-summary.glm" class="level1">
<h1>summary.lm and summary.glm</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
lm summary, annotated
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-summarylman" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-summarylman-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/glm/lmsummary.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-summarylman-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: lm summary, annotated. click the image to zoom in, click the image to zoom out
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
glm summary, annotated
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-summaryglman" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-summaryglman-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/glm/glmsummary.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-summaryglman-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: glm summary, annotated. click the image to zoom in, click the image to zoom out
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- 

<div class="optional-begin"><button id='opt-start-1' class="jk-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> Optional: Pearson Residuals </button></div><div class="optional-body" id = "opt-body-1" style="display: none;">

 -->
<!-- __Pearson Residuals__   -->
<!-- There is another form of residual we can use, called "Pearson residuals". These are similar to the Pearson residuals you might remember from the [chi-squared test (4A)](04a_chisq.html){target="_blank"}, which compared Observed and Expected values, but in this case Expected means Predicted from the model: -->
<!-- $$ -->
<!-- Pres_i = \frac{Observed - Expected}{\sqrt{Expected}} -->
<!-- $$ -->
<!-- In logistic regression, this is  -->
<!-- $$ -->
<!-- Pres_i = \frac{y_i - \hat p_i}{\sqrt{\hat p_i (1 - \hat p_i)}} -->
<!-- $$ -->
<!-- where  -->
<!-- - $y_i$ is the observed response for unit $i$, either 0 (failure) or 1 (success) -->
<!-- - $\hat p_i$ is the model-predicted probability of success -->
<!-- We can get these out from R, and use them to create similar plots to the one we made for deviance residuals.   -->
<!-- ```{r} -->
<!-- #| eval: false -->
<!-- # pearson residuals -->
<!-- residuals(mallowmod, type = 'pearson') -->
<!-- # standardised pearson residuals -->
<!-- rstandard(mallowmod, type = 'pearson') -->
<!-- # studentised pearson residuals -->
<!-- rstudent(mallowmod, type = 'pearson') -->
<!-- ``` -->
<!-- 

</div><p class="optional-end"></p>

 -->


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>we have seen this type of variable already when looking at categorical predictors in our models, but we haven’t seen how we use it as the <em>outcome</em>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This means we will end up with a lot of multiplying (computationally expensive), and a tiny tiny number. So instead we typically talk about the log-likelihood, and use summation instead of multiplication. The log-likelihood of the two data points highlighted in <a href="#fig-mleprob" class="quarto-xref">Figure&nbsp;14</a>, given the line is <code>log(0.98)+log(0.84)</code>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><span class="math inline">\(e^{a+b} = e^a \times e^b\)</span>. For example: <span class="math inline">\(2^2 \times 2^3 = 4 \times 8 = 32 = 2^5 = 2^{2+3}\)</span><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>COMPLETELY OPTIONAL COMPLEX FORMULA ALERT THAT YOU DON’T NEED TO KNOW: standard errors of coefficients are calculated as <span class="math inline">\(\sigma^2 (X'X)^{-1}\)</span>. The <span class="math inline">\(X\)</span> in this case is our “design matrix” (all our predictor variables, plus our intercept, for each observation). <span class="math inline">\((X'X)\)</span> is just a way of multiplying a matrix by itself - so it represents the relationships - in terms of sums of squares - between all our predictor variables in the model. So the formula for coefficients standard errors is based on the residual variance and the amount of (co)variance in our predictors.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>other functions like <code>plogis()</code> are available<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Gelman, A., &amp; Hill, J. (2006). Data Analysis Using Regression and Multilevel/Hierarchical Models (Analytical Methods for Social Research). Cambridge: Cambridge University Press. doi:10.1017/CBO9780511790942<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© Copyright 2019-2024 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>