<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.587">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - Covariance, Correlation, and Modelling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-left')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-left')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 1</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html">
 <span class="dropdown-text">Reading: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html">
 <span class="dropdown-text">Reading: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html">
 <span class="dropdown-text">Exercises</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 2</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html">
 <span class="dropdown-text">Reading: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html">
 <span class="dropdown-text">Reading: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html">
 <span class="dropdown-text">Exercises</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 3</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html">
 <span class="dropdown-text">Reading: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html">
 <span class="dropdown-text">Reading: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html">
 <span class="dropdown-text">Exercises</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 4</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04a_chisq.html">
 <span class="dropdown-text">Chi-Squared Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revistnhst.html">
 <span class="dropdown-text">NHST Revisited</span></a>
  </li>  
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#covariance-correlation" id="toc-covariance-correlation" class="nav-link active" data-scroll-target="#covariance-correlation">Covariance &amp; Correlation</a></li>
  <li><a href="#correlation-test" id="toc-correlation-test" class="nav-link" data-scroll-target="#correlation-test">Correlation Test</a>
  <ul class="collapse">
  <li><a href="#cautions" id="toc-cautions" class="nav-link" data-scroll-target="#cautions">Cautions!</a></li>
  </ul></li>
  <li><a href="#game-guess-the-r" id="toc-game-guess-the-r" class="nav-link" data-scroll-target="#game-guess-the-r"><b>Game:</b> Guess the <span class="math inline">\(r\)</span></a></li>
  <li><a href="#correlation-exercises" id="toc-correlation-exercises" class="nav-link" data-scroll-target="#correlation-exercises">Correlation Exercises</a></li>
  <li><a href="#functions-and-models-exercises" id="toc-functions-and-models-exercises" class="nav-link" data-scroll-target="#functions-and-models-exercises">Functions and Models Exercises</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Covariance, Correlation, and Modelling</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="covariance-correlation" class="level1">
<h1>Covariance &amp; Correlation</h1>
<p>Our data for this walkthrough is from a (hypothetical) study on memory. Twenty participants studied passages of text (c500 words long), and were tested a week later. The testing phase presented participants with 100 statements about the text. They had to answer whether each statement was true or false, as well as rate their confidence in each answer (on a sliding scale from 0 to 100). The dataset contains, for each participant, the percentage of items correctly answered, and the average confidence rating. Participants’ ages were also recorded.</p>
<p>Let’s take a look at the relationships between the percentage of items answered correctly (<code>recall_accuracy</code>) and participants’ average self-rating of confidence in their answers (<code>recall_confidence</code>):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>recalldata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/recalldata.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(recalldata, <span class="fu">aes</span>(<span class="at">x=</span>recall_confidence, recall_accuracy))<span class="sc">+</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(recalldata, <span class="fu">aes</span>(<span class="at">x=</span>age, recall_accuracy))<span class="sc">+</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>These two relationships look quite different.</p>
<ul>
<li>For participants who tended to be more confident in their answers, the percentage of items they correctly answered tends to be higher.<br>
</li>
<li>The older participants were, the lower the percentage of items they correctly answered tended to be.</li>
</ul>
<p>Which relationship should we be more confident in and why?</p>
<p>Ideally, we would have some means of quantifying the strength and direction of these sorts of relationship. This is where we come to the two summary statistics which we can use to talk about the association between two numeric variables: <strong>Covariance</strong> and <strong>Correlation</strong>.</p>
<div class="sticky">
<center>
<strong>Covariance</strong>
</center>
<p><br> Covariance is the measure of how two variables vary together. It is the change in one variable associated with the change in another variable.</p>
<p>For samples, covariance is calculated using the following formula:</p>
<p><span class="math display">\[\mathrm{cov}(x,y)=\frac{1}{n-1}\sum_{i=1}^n (x_{i}-\bar{x})(y_{i}-\bar{y})\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> are two variables; e.g., <code>age</code> and <code>recall_accuracy</code>;</li>
<li><span class="math inline">\(i\)</span> denotes the observational unit, such that <span class="math inline">\(x_i\)</span> is value that the <span class="math inline">\(x\)</span> variable takes on the <span class="math inline">\(i\)</span>th observational unit, and similarly for <span class="math inline">\(y_i\)</span>;</li>
<li><span class="math inline">\(n\)</span> is the sample size.</li>
</ul>
<p><strong>In R</strong><br>
We can calculate covariance in R using the <code>cov()</code> function.<br>
<code>cov()</code> can take two variables <code>cov(x = , y = )</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(<span class="at">x =</span> recalldata<span class="sc">$</span>recall_accuracy, <span class="at">y =</span> recalldata<span class="sc">$</span>recall_confidence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 118.0768</code></pre>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Optional: Manually calculating covariance</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<ol type="1">
<li>Create 2 new columns in the memory recall data, one of which is the mean recall accuracy, and one which is the mean recall confidence.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>recalldata <span class="ot">&lt;-</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  recalldata <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">maccuracy =</span> <span class="fu">mean</span>(recall_accuracy),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mconfidence =</span> <span class="fu">mean</span>(recall_confidence)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li><p>Now create three new columns which are:</p>
<ol type="i">
<li>recall accuracy minus the mean recall accuracy - this is the <span class="math inline">\((x_i - \bar{x})\)</span> part.<br>
</li>
<li>confidence minus the mean confidence - and this is the <span class="math inline">\((y_i - \bar{y})\)</span> part.<br>
</li>
<li>the product of i. and ii. - this is calculating <span class="math inline">\((x_i - \bar{x})\)</span><span class="math inline">\((y_i - \bar{y})\)</span>.</li>
</ol></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>recalldata <span class="ot">&lt;-</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  recalldata <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">acc_minus_mean_acc =</span> recall_accuracy <span class="sc">-</span> maccuracy,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">conf_minus_mean_conf =</span> recall_confidence <span class="sc">-</span> mconfidence,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">prod_acc_conf =</span> acc_minus_mean_acc <span class="sc">*</span> conf_minus_mean_conf</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>recalldata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 9
   ppt    recall_accuracy recall_confidence   age maccuracy mconfidence
   &lt;chr&gt;            &lt;dbl&gt;             &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
 1 ppt_1               72              66.6    72      69.2        55.4
 2 ppt_2               66              47.1    35      69.2        55.4
 3 ppt_3               47              43.8    48      69.2        55.4
 4 ppt_4               84              58.9    52      69.2        55.4
 5 ppt_5               84              75.1    46      69.2        55.4
 6 ppt_6               58              53.5    41      69.2        55.4
 7 ppt_7               52              48.5    86      69.2        55.4
 8 ppt_8               76              67.1    58      69.2        55.4
 9 ppt_9               41              40.4    59      69.2        55.4
10 ppt_10              67              46.8    22      69.2        55.4
11 ppt_11              60              50.6    62      69.2        55.4
12 ppt_12              67              28.7    40      69.2        55.4
13 ppt_13              76              69.0    47      69.2        55.4
14 ppt_14              93              67.9    51      69.2        55.4
15 ppt_15              71              54.5    34      69.2        55.4
16 ppt_16              71              64.6    37      69.2        55.4
17 ppt_17              99              66.3    37      69.2        55.4
18 ppt_18              66              49.0    51      69.2        55.4
19 ppt_19              77              58.5    41      69.2        55.4
20 ppt_20              58              51.4    57      69.2        55.4
# … with 3 more variables: acc_minus_mean_acc &lt;dbl&gt;,
#   conf_minus_mean_conf &lt;dbl&gt;, prod_acc_conf &lt;dbl&gt;</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Finally, sum the products, and divide by <span class="math inline">\(n-1\)</span></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>recalldata <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">prod_sum =</span> <span class="fu">sum</span>(prod_acc_conf),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  prod_sum     n
     &lt;dbl&gt; &lt;int&gt;
1    2243.    20</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fl">2243.46</span> <span class="sc">/</span> (<span class="dv">20-1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 118.0768</code></pre>
</div>
</div>
<p>Which is the same result as using <code>cov()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(<span class="at">x =</span> recalldata<span class="sc">$</span>recall_accuracy, <span class="at">y =</span> recalldata<span class="sc">$</span>recall_confidence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 118.0768</code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-2" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-2', 'opt-start-2')"> <span class="olab">Optional: Covariance explained visually</span></span>
</div>
<div id="opt-body-2" class="optional-body" style="display: none;">
<div class="cell" data-layout-align="center">

</div>
<p>Consider the following scatterplot:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><br> Now let’s superimpose a vertical dashed line at the mean of <span class="math inline">\(x\)</span> (<span class="math inline">\(\bar{x}\)</span>) and a horizontal dashed line at the mean of <span class="math inline">\(y\)</span> (<span class="math inline">\(\bar{y}\)</span>):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><br> Now let’s pick one of the points, call it <span class="math inline">\(x_i\)</span>, and show <span class="math inline">\((x_{i}-\bar{x})\)</span> and <span class="math inline">\((y_{i}-\bar{y})\)</span>.<br>
<br> Notice that this makes a rectangle.<br>
<br> As <span class="math inline">\((x_{i}-\bar{x})\)</span> and <span class="math inline">\((y_{i}-\bar{y})\)</span> are both positive values, their product - <span class="math inline">\((x_{i}-\bar{x})(y_{i}-\bar{y})\)</span> - is positive.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><br> In fact, for all these points in red, the product <span class="math inline">\((x_{i}-\bar{x})(y_{i}-\bar{y})\)</span> is positive (remember that a negative multiplied by a negative gives a positive):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><br> And for these points in blue, the product <span class="math inline">\((x_{i}-\bar{x})(y_{i}-\bar{y})\)</span> is negative:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><br> Now take another look at the formula for covariance:</p>
<p><span class="math display">\[\mathrm{cov}(x,y)=\frac{\sum_{i=1}^n (x_{i}-\bar{x})(y_{i}-\bar{y})}{n-1}\]</span></p>
<p>It is the sum of all these products divided by <span class="math inline">\(n-1\)</span>. It is the average of the products!</p>
</div>
<p class="optional-end">
</p>
<div class="sticky">
<center>
<strong>Correlation - <span class="math inline">\(r\)</span></strong>
</center>
<p><br> You can think of correlation as a standardized covariance. It has a scale from negative one to one, on which the distance from zero indicates the strength of the relationship.<br>
Just like covariance, positive/negative values reflect the nature of the relationship.</p>
<p>The <strong>correlation coefficient</strong> is a standardised number which quantifies the strength and direction of the <strong>linear</strong> relationship between two variables. In a population it is denoted by <span class="math inline">\(\rho\)</span>, and in a sample it is denoted by <span class="math inline">\(r\)</span>.</p>
<p>We can calculate <span class="math inline">\(r\)</span> using the following formula:</p>
<p><span class="math display">\[
r_{(x,y)}=\frac{\mathrm{cov}(x,y)}{s_xs_y}
\]</span></p>
<p>We can actually rearrange this formula to show that the correlation is simply the covariance, but with the values <span class="math inline">\((x_i - \bar{x})\)</span> divided by the standard deviation (<span class="math inline">\(s_x\)</span>), and the values <span class="math inline">\((y_i - \bar{y})\)</span> divided by <span class="math inline">\(s_y\)</span>:</p>
<p><span class="math display">\[
r_{(x,y)}=\frac{1}{n-1} \sum_{i=1}^n \left( \frac{x_{i}-\bar{x}}{s_x} \right) \left( \frac{y_{i}-\bar{y}}{s_y} \right)
\]</span></p>
<p><br> The correlation is the simply the covariance of <strong>standardised</strong> variables (variables expressed as the distance <em>in standard deviations</em> from the mean).</p>
<p><strong>Properties of correlation coefficients</strong></p>
<ul>
<li><span class="math inline">\(-1 \leq r \leq 1\)</span></li>
<li>The sign indicates the direction of association
<ul>
<li><em>positive association</em> (<span class="math inline">\(r &gt; 0\)</span>) means that values of one variable tend to be higher when values of the other variable are higher</li>
<li><em>negative association</em> (<span class="math inline">\(r &lt; 0\)</span>) means that values of one variable tend to be lower when values of the other variable are higher</li>
<li><em>no linear association</em> (<span class="math inline">\(r \approx 0\)</span>) means that higher/lower values of one variable do not tend to occur with higher/lower values of the other variable</li>
</ul></li>
<li>The closer <span class="math inline">\(r\)</span> is to <span class="math inline">\(\pm 1\)</span>, the stronger the linear association</li>
<li><span class="math inline">\(r\)</span> has no units and does not depend on the units of measurement</li>
<li>The correlation between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is the same as the correlation between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span></li>
</ul>
<p><strong>In R</strong><br>
Just like R has a <code>cov()</code> function for calculating covariance, there is a <code>cor()</code> function for calculating correlation:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> recalldata<span class="sc">$</span>recall_accuracy, <span class="at">y =</span> recalldata<span class="sc">$</span>recall_confidence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6993654</code></pre>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-3" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-3', 'opt-start-3')"> <span class="olab">Optional: Manually calculating correlation</span></span>
</div>
<div id="opt-body-3" class="optional-body" style="display: none;">
<p>We calculated above that <span class="math inline">\(\text{cov}(\text{recall-accuracy}, \text{recall-confidence})\)</span> = 118.077.</p>
<p>To calculate the <em>correlation</em>, we can simply divide this by the standard deviations of the two variables <span class="math inline">\(s_{\text{recall-accuracy}} \times s_{\text{recall-confidence}}\)</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>recalldata <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">s_ra =</span> <span class="fu">sd</span>(recall_accuracy),</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">s_rc =</span> <span class="fu">sd</span>(recall_confidence)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   s_ra  s_rc
  &lt;dbl&gt; &lt;dbl&gt;
1  14.5  11.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fl">118.08</span> <span class="sc">/</span> (<span class="fl">14.527</span> <span class="sc">*</span> <span class="fl">11.622</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6993902</code></pre>
</div>
</div>
<p>Which is the same result as using <code>cor()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> recalldata<span class="sc">$</span>recall_accuracy, <span class="at">y =</span> recalldata<span class="sc">$</span>recall_confidence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6993654</code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section>
<section id="correlation-test" class="level1">
<h1>Correlation Test</h1>
<p>Now that we’ve seen the formulae for <em>covariance</em> and <em>correlation</em>, as well as how to quickly calculate them in R using <code>cov()</code> and <code>cor()</code>, we can use a statistical test to establish the probability of finding an association this strong by chance alone.</p>
<div class="frame">
<p><strong>Hypotheses</strong></p>
<p>The hypotheses of the correlation test are, as always, statements about the <em>population</em> parameter (in this case the correlation between the two variables in the population - i.e., <span class="math inline">\(\rho\)</span>).</p>
<p><strong>Null Hypothesis:</strong></p>
<ul>
<li><span class="math inline">\(H_0: \rho = 0\)</span>. There is <em>not</em> a linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> in the population.</li>
</ul>
<p><strong>Alternative Hypothesis:</strong></p>
<ol type="a">
<li><span class="math inline">\(H_1: \rho &gt; 0\)</span> There is a positive linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</li>
<li><span class="math inline">\(H_1: \rho &lt; 0\)</span> There is a negative linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</li>
<li><span class="math inline">\(H_1: \rho \neq 0\)</span> There is a linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</li>
</ol>
</div>
<div class="frame">
<p><strong>Test Statistic</strong></p>
<p>The <strong>test statistic</strong> for this test here is <em>another</em> <span class="math inline">\(t\)</span> statistic, the formula for which depends on both the observed correlation (<span class="math inline">\(r\)</span>) and the sample size (<span class="math inline">\(n\)</span>):</p>
<p><span class="math display">\[t = r \sqrt{\frac{n-2}{1-r^2}}\]</span></p>
</div>
<div class="frame">
<p><strong>p-value</strong></p>
<p>We calculate the p-value for our <span class="math inline">\(t\)</span>-statistic as the long-run probability of a <span class="math inline">\(t\)</span>-statistic with <span class="math inline">\(n-2\)</span> degrees of freedom being less than, greater than, or more extreme in either direction (depending on the direction of our alternative hypothesis) than our observed <span class="math inline">\(t\)</span>-statistic.</p>
</div>
<div class="frame">
<p><strong>In R</strong><br>
We can test the significance of the correlation coefficient really easily with the function <code>cor.test()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(recalldata<span class="sc">$</span>recall_accuracy, recalldata<span class="sc">$</span>recall_confidence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  recalldata$recall_accuracy and recalldata$recall_confidence
t = 4.1512, df = 18, p-value = 0.0005998
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.3719603 0.8720125
sample estimates:
      cor 
0.6993654 </code></pre>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-4" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-4', 'opt-start-4')"> <span class="olab">Optional: Manually conducting the correlation test</span></span>
</div>
<div id="opt-body-4" class="optional-body" style="display: none;">
<p>Or, if we want to calculate our test statistic manually:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate r</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">=</span> <span class="fu">cor</span>(recalldata<span class="sc">$</span>recall_accuracy, recalldata<span class="sc">$</span>recall_confidence)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co">#get n</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">nrow</span>(recalldata)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate t    </span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>tstat <span class="ot">=</span> r <span class="sc">*</span> <span class="fu">sqrt</span>((n <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> r<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate p-value for t, with df = n-2 </span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(tstat, <span class="at">df=</span>n<span class="dv">-2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0005998222</code></pre>
</div>
</div>
<div class="frame">
<p><strong>Assumptions</strong></p>
<p>For a test of Pearson’s correlation coefficient <span class="math inline">\(r\)</span>, we need to make sure a few conditions are met:</p>
<ul>
<li>Both variables are quantitative</li>
<li>Both variables should be drawn from normally distributed populations.</li>
<li>The relationship between the two variables should be linear.</li>
</ul>
</div>
</div>
<p class="optional-end">
</p>
<section id="cautions" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="cautions">Cautions!</h2>
<p>Correlation is an invaluable tool for quantifying relationships between variables, but <strong>must be used with care</strong>.</p>
<p>Below are a few things to be aware of when we talk about correlation.</p>
<div class="frame">
<p><strong>Correlation can be heavily affected by outliers. Always plot your data!</strong></p>
<p>The two plots below only differ with respect to the inclusion of <em>one</em> observation. However, the correlation coefficient for the two sets of observations is markedly different.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="frame">
<p><strong>r = 0 means no linear association. The variables could still be otherwise associated. Always plot your data!</strong></p>
<p>The correlation coefficient in <a href="#fig-joface">Figure&nbsp;1</a> below is negligible, suggesting no <em>linear</em> association. The word “linear” here is crucial - the data are very clearly related.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-joface" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/fig-joface-1.png" style="width:80.0%" height="200" class="figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 1: Unrelated data?</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Similarly, take look at all the sets of data in <a href="#fig-datasaurus">Figure&nbsp;2</a> below. The summary statistics (means and standard deviations of each variable, and the correlation) are almost identical, but the visualisations suggest that the data are very different from one another.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-datasaurus" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="https://media1.giphy.com/media/UN2kVJQeMFUje/source.gif" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 2: Datasaurus! From Matejka, J., &amp; Fitzmaurice, G. (2017, May): Same stats, different graphs: generating datasets with varied appearance and identical statistics through simulated annealing.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<div class="frame">
<p><strong>Correlation does not imply causation!</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-xkcdcor" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/covcor/corcaus.jpeg" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 3: https://twitter.com/quantitudepod/status/1309135514839248896</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>You will have likely heard the phrase “correlation does not imply causation”. There is even a whole <a href="https://en.wikipedia.org/wiki/Correlation_does_not_imply_causation">wikipedia entry</a> devoted to the topic.</p>
<p><strong>Just because you observe an association between x and y, we should not deduce that x causes y</strong></p>
<p>An often cited paper (See <a href="#fig-choco">Figure&nbsp;4</a>) which appears to fall foul of this error took a correlation between a country’s chocolate consumption and its number of nobel prize winners to suggest a <em>causal relationship</em> between the two:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-choco" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/covcor/choco.jpeg" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 4: Chocolate consumption causes more Nobel Laureates?</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><em>“since chocolate consumption has been documented to improve cognitive function, it seems most likely that in a dose-dependent way, chocolate intake provides the abundant fertile ground needed for the sprouting of Nobel laureates”</em><br>
[Messerli, Franz. Chocolate Consumption, Cognitive Function, and Nobel Laureates. The New England Journal of Medicine 2012; 367:1562-4, (http://www.nejm.org/doi/full/10.1056/NEJMon1211064)]</p>
</div>
</section>
</section>
<section id="game-guess-the-r" class="level1 unnumbered">
<h1 class="unnumbered"><b>Game:</b> Guess the <span class="math inline">\(r\)</span></h1>
<p>Take a break and play this “guess the correlation” game to get an idea of what different strengths and directions of <span class="math inline">\(r\)</span> can look like.<br>
(if the game is not showing, try http://guessthecorrelation.com/).</p>
<iframe src="http://guessthecorrelation.com/" width="100%" height="650px" data-external="1">
</iframe>
<p><strong>source: <a href="http://guessthecorrelation.com/">http://guessthecorrelation.com/</a></strong></p>
</section>
<section id="correlation-exercises" class="level1">
<h1>Correlation Exercises</h1>
<div class="frame">
<p><strong>Data: Sleep levels and daytime functioning</strong></p>
<p>A researcher is interested in the relationship between hours slept per night and self-rated effects of sleep on daytime functioning. She recruited 50 healthy adults, and collected data on the Total Sleep Time (TST) over the course of a seven day period via sleep-tracking devices.<br>
At the end of the seven day period, participants completed a Daytime Functioning (DTF) questionnaire. This involved participants rating their agreement with ten statements (see Table @ref(tab:sleepitems)). Agreement was measured on a scale from 1-5. An overall score of daytime functioning can be calculated by:</p>
<ol type="1">
<li>reversing the scores for items 4,5 and 6 (because those items reflect agreement with <em>positive</em> statements, whereas the other ones are agreement with <em>negative</em> statement);</li>
<li>summing the scores on each item; and</li>
<li>subtracting the sum score from 50 (the max possible score). This will make higher scores reflect better perceived daytime functioning.</li>
</ol>
<p>The data is available at https://uoepsy.github.io/data/sleepdtf.csv.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Daytime Functioning Questionnaire</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Statement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Item_1</td>
<td style="text-align: left;">I often felt an inability to concentrate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Item_2</td>
<td style="text-align: left;">I frequently forgot things</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Item_3</td>
<td style="text-align: left;">I found thinking clearly required a lot of effort</td>
</tr>
<tr class="even">
<td style="text-align: left;">Item_4</td>
<td style="text-align: left;">I often felt happy</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Item_5</td>
<td style="text-align: left;">I had lots of energy</td>
</tr>
<tr class="even">
<td style="text-align: left;">Item_6</td>
<td style="text-align: left;">I worked efficiently</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Item_7</td>
<td style="text-align: left;">I often felt irritable</td>
</tr>
<tr class="even">
<td style="text-align: left;">Item_8</td>
<td style="text-align: left;">I often felt stressed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Item_9</td>
<td style="text-align: left;">I often felt sleepy</td>
</tr>
<tr class="even">
<td style="text-align: left;">Item_10</td>
<td style="text-align: left;">I often felt fatigued</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="question-begin">
Question A1
</div>
<div class="question-body">
<p>Read in the data, and calculate the overall daytime functioning score, following the criteria outlined above. Make this a new column in your dataset.</p>
<p><em>Hints:</em></p>
<ul>
<li>To reverse items 4, 5 and 6, we we need to make all the scores of 1 become 5, scores of 2 become 4, and so on… What number satisfies all of these equations: <code>? - 5 = 1</code>, <code>? - 4 = 2</code>, <code>? - 3 = 3</code>?</li>
<li>To quickly sum accross rows, you can use the <code>rowSums()</code> function.</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>sleepdtf <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/sleepdtf.csv"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sleepdtf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      TST             item_1         item_2         item_3         item_4    
 Min.   : 4.900   Min.   :1.00   Min.   :1.00   Min.   :1.00   Min.   :1.00  
 1st Qu.: 7.225   1st Qu.:1.00   1st Qu.:2.00   1st Qu.:1.25   1st Qu.:1.00  
 Median : 7.900   Median :1.00   Median :2.00   Median :2.00   Median :1.00  
 Mean   : 8.004   Mean   :1.58   Mean   :2.46   Mean   :2.38   Mean   :1.26  
 3rd Qu.: 9.025   3rd Qu.:2.00   3rd Qu.:3.00   3rd Qu.:3.00   3rd Qu.:1.00  
 Max.   :11.200   Max.   :3.00   Max.   :5.00   Max.   :5.00   Max.   :3.00  
     item_5         item_6         item_7         item_8        item_9    
 Min.   :1.00   Min.   :1.00   Min.   :1.00   Min.   :1.0   Min.   :1.00  
 1st Qu.:2.00   1st Qu.:2.00   1st Qu.:1.00   1st Qu.:2.0   1st Qu.:2.00  
 Median :2.00   Median :3.00   Median :2.00   Median :2.5   Median :3.00  
 Mean   :2.36   Mean   :2.78   Mean   :2.04   Mean   :2.5   Mean   :2.96  
 3rd Qu.:3.00   3rd Qu.:4.00   3rd Qu.:3.00   3rd Qu.:3.0   3rd Qu.:4.00  
 Max.   :4.00   Max.   :5.00   Max.   :4.00   Max.   :4.0   Max.   :5.00  
    item_10    
 Min.   :1.00  
 1st Qu.:2.00  
 Median :3.00  
 Mean   :2.54  
 3rd Qu.:3.00  
 Max.   :5.00  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To reverse the items, we can simply do 6 minus the score.   </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>sleepdtf <span class="ot">&lt;-</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  sleepdtf <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">item_4=</span><span class="dv">6</span><span class="sc">-</span>item_4,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">item_5=</span><span class="dv">6</span><span class="sc">-</span>item_5,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">item_6=</span><span class="dv">6</span><span class="sc">-</span>item_6</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Now using rowSums(), and subtracting it from 50 (the max score)</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>sleepdtf<span class="sc">$</span>dtf <span class="ot">=</span> <span class="dv">50</span><span class="sc">-</span><span class="fu">rowSums</span>(sleepdtf[, <span class="dv">2</span><span class="sc">:</span><span class="dv">11</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A2
</div>
<div class="question-body">
<p>Calculate the correlation between the total sleep time (<code>TST</code>) and the overall daytime functioning score.<br>
Conduct a test to establish the probability of observing a correlation this strong in a sample of this size assuming the true correlation to be 0.<br>
<br> Write a sentence or two summarising the results.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(sleepdtf<span class="sc">$</span>TST, sleepdtf<span class="sc">$</span>dtf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  sleepdtf$TST and sleepdtf$dtf
t = 6.244, df = 48, p-value = 1.062e-07
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4807039 0.7989417
sample estimates:
      cor 
0.6694741 </code></pre>
</div>
</div>
<div class="int">
<p>There was a strong positive correlation between total sleep time and self-reported daytime functioning score (<span class="math inline">\(r\)</span> = 0.67, <span class="math inline">\(t(48)\)</span> = 6.24, <span class="math inline">\(p &lt; .001\)</span>) in the current sample. As total sleep time increased, levels of self-reported daytime functioning increased.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A3
</div>
<div class="question-body">
<p><strong>Open-ended:</strong> Think about this relationship in terms of <em>causation</em>.<br>
<br> Claim: <em>Less sleep causes poorer daytime functioning.</em><br>
<br> Why might it be inappropriate to make the claim above based on these data alone? Think about what sort of study could provide stronger evidence for such a claim.</p>
<p>Things to think about:</p>
<ul>
<li>comparison groups.<br>
</li>
<li>random allocation.<br>
</li>
<li>measures of daytime functioning.<br>
</li>
<li>measures of sleep time.<br>
</li>
<li>other (unmeasured) explanatory variables.</li>
</ul>
</div>
<p class="question-end">
</p>
</section>
<section id="functions-and-models-exercises" class="level1">
<h1>Functions and Models Exercises</h1>
<div class="question-begin">
Question B1
</div>
<div class="question-body">
<p>The Scottish National Gallery kindly provided us with measurements of side and perimeter (in metres) for a sample of 10 square paintings.</p>
<p>The data are provided below:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>sng <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">side =</span> <span class="fu">c</span>(<span class="fl">1.3</span>, <span class="fl">0.75</span>, <span class="dv">2</span>, <span class="fl">0.5</span>, <span class="fl">0.3</span>, <span class="fl">1.1</span>, <span class="fl">2.3</span>, <span class="fl">0.85</span>, <span class="fl">1.1</span>, <span class="fl">0.2</span>),</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">perimeter =</span> <span class="fu">c</span>(<span class="fl">5.2</span>, <span class="fl">3.0</span>, <span class="fl">8.0</span>, <span class="fl">2.0</span>, <span class="fl">1.2</span>, <span class="fl">4.4</span>, <span class="fl">9.2</span>, <span class="fl">3.4</span>, <span class="fl">4.4</span>, <span class="fl">0.8</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Plot the data from the Scottish National Gallery using <code>ggplot()</code>.</p>
<p>We know that there is a mathematical model for the relationship between the side-length and perimeter of squares: <span class="math inline">\(perimeter = 4 \times \ side\)</span>.<br>
Try adding the following line to your plot:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="sc">~</span>.x <span class="sc">*</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>sng <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">side =</span> <span class="fu">c</span>(<span class="fl">1.3</span>, <span class="fl">0.75</span>, <span class="dv">2</span>, <span class="fl">0.5</span>, <span class="fl">0.3</span>, <span class="fl">1.1</span>, <span class="fl">2.3</span>, <span class="fl">0.85</span>, <span class="fl">1.1</span>, <span class="fl">0.2</span>),</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">perimeter =</span> <span class="fu">c</span>(<span class="fl">5.2</span>, <span class="fl">3.0</span>, <span class="fl">8.0</span>, <span class="fl">2.0</span>, <span class="fl">1.2</span>, <span class="fl">4.4</span>, <span class="fl">9.2</span>, <span class="fl">3.4</span>, <span class="fl">4.4</span>, <span class="fl">0.8</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sng, <span class="fu">aes</span>(<span class="at">x =</span> side, <span class="at">y =</span> perimeter)) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">'black'</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Side (m)'</span>, <span class="at">y =</span> <span class="st">'Perimeter (m)'</span>)<span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="sc">~</span>.x <span class="sc">*</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/squares-scatterplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">The exact relationship between side and perimeter of squares.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The above plot shows perfect agreement between the observed data and the model.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question B2
</div>
<div class="question-body">
<p>Use our mathematical model to predict the perimeter of a painting with a side of 1.5 metres.<br>
We do not have a painting with a side of 1.5 metres within the random sample of paintings from the Scottish National Gallery. We predict the perimeter of an unobserved squared painting having a 1.5 metre side using the mathematical model.</p>
<p>You can obtain this prediction either using a visual approach or an algebraic one.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p><strong>Visual approach</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Sometimes we can directly read a predicted value from the graph of the functional relationship.</p>
<p>Consider the plot created in the previous question. First, we need to check where x = 1.5. Then, we draw a vertical dashed line until it meets the blue line. The y value corresponding to x = 1.5 can be read off the y-axis.</p>
<p>However, in this case it is not that easy to read it from the drawing… Let’s try the next approach.</p>
<p><br> <strong>Algebraic approach</strong></p>
<p>You can substitute the x value in the formula and calculate the corresponding y value.</p>
<p><span class="math display">\[
y = 4 \times \ x = 4 \times \ (1.5) = 6
\]</span></p>
<p><br> We might write this up as:</p>
<div class="int">
<p>The predicted perimeter of squared paintings having a 1.5m side is 6m.</p>
</div>
<p><strong>NOTE</strong>: Don’t forget to always include the measurement units when reporting/writing-up results!</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question B3
</div>
<div class="question-body">
<p>Consider now the relationship between height (in inches) and handspan (in cm). <span class="citation" data-cites="Utts2015">@Utts2015</span> provides data for a sample of 167 students who reported their height and handspan as part of a class survey.</p>
<div class="optional-begin">
<span id="opt-start-9" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-9', 'opt-start-9')"> <span class="olab">Data: handheight.csv</span></span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p><strong>Download link</strong></p>
<p><a href="https://uoepsy.github.io/data/handheight.csv" target="_blank">Download the data here</a></p>
<p><strong>Description</strong></p>
<p>The data set records the height and handspan reported by a random sample of 167 students as part of a class survey <span class="citation" data-cites="Utts2015">[@Utts2015]</span>.</p>
<p>The variables are:</p>
<ul>
<li><code>height</code>, measured in inches</li>
<li><code>handspan</code>, measured in centimetres</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:center;"> height </th>
   <th style="text-align:center;"> handspan </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:center;width: 10em; "> 68 </td>
   <td style="text-align:center;width: 10em; "> 21.5 </td>
  </tr>
  <tr>
   <td style="text-align:center;width: 10em; "> 71 </td>
   <td style="text-align:center;width: 10em; "> 23.5 </td>
  </tr>
  <tr>
   <td style="text-align:center;width: 10em; "> 73 </td>
   <td style="text-align:center;width: 10em; "> 22.5 </td>
  </tr>
  <tr>
   <td style="text-align:center;width: 10em; "> 64 </td>
   <td style="text-align:center;width: 10em; "> 18.0 </td>
  </tr>
  <tr>
   <td style="text-align:center;width: 10em; "> 68 </td>
   <td style="text-align:center;width: 10em; "> 23.5 </td>
  </tr>
  <tr>
   <td style="text-align:center;width: 10em; "> 59 </td>
   <td style="text-align:center;width: 10em; "> 20.0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p class="optional-end">
</p>
<p>Read the handheight data into R, and investigate how handspan varies as a function of height for the students in the sample.</p>
<p>Do you notice any outliers or points that do not fit with the pattern in the rest of the data?</p>
<p>Comment on any main differences you notice between this relationship and the relationship between sides and perimeter of squares.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<p>The <code>handheight</code> data set contains two variables, height and handspan, which are both numeric and continuous. We display the relationship between two numeric variables with a scatterplot.</p>
<p>We can also add marginal boxplots for each variable using the package <code>ggExtra</code>. Before using the package, make sure you have it installed via <code>install.packages('ggExtra')</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>handheight <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">'https://uoepsy.github.io/data/handheight.csv'</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggExtra)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>plt <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(handheight, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> handspan)) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Height (in.)'</span>, <span class="at">y =</span> <span class="st">'Handspan (cm)'</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggMarginal</span>(plt, <span class="at">type =</span> <span class="st">'boxplot'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/handheight-scatterplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">The statistical relationship between height and handspan.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Outliers are extreme observations that do not seem to fit with the rest of the data. This could either be:</p>
<ul>
<li><em>marginally</em> along one axis: points that have an unusual (too high or too low) x-coordinate or y-coordinate;</li>
<li><em>jointly</em>: observations that do not fit with the rest of the point cloud.</li>
</ul>
<p>The boxplots in Figure @ref(fig:handheight-scatterplot) do not highlight any outliers in the marginal distributions of height and handspan. Furthermore, from the scatterplot we do not notice any extreme observations or points that do not fit with the rest of the point cloud.</p>
<p>We notice a moderate, positive (that is, increasing) linear relationship between height and handspan.</p>
<p>Recall Figure @ref(fig:squares-scatterplot), displaying the relationship between side and perimeters of squares. In the plot we notice two points on top of each other, reflecting the fact that two squares having the same side will always have the same perimeter. In fact, the data from the Scottish National Gallery include two squared paintings with a side of 1.1m, both having a measured perimeter of 4.4m.</p>
<p>Figure @ref(fig:handheight-scatterplot), instead, displays the relationship between height and handspan of a sample of students. The first thing that grabs our attention is the fact that students having the same height do not necessarily have the same handspan. Rather, we clearly see a variety of handspan values for students all having a height of, for example, 70in. To be more precise, the seven students who are 70 in. tall all have differing handspans.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question B4
</div>
<div class="question-body">
<p>Using the following command, superimpose on top of your scatterplot a best-fit line describing how handspan varies as a function of height. For the moment, the argument <code>se = FALSE</code> tells R to not display uncertainty bands.</p>
<pre><code>geom_smooth(method = lm, se = FALSE)</code></pre>
<p>Comment on any differences you notice with the line summarising the linear relationship between side and perimeter.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(handheight, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> handspan)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Height (in.)'</span>, <span class="at">y =</span> <span class="st">'Handspan (cm)'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_covcor_files/figure-html/handheight-fitted-model-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">The best-fit line.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The line representing the relationship between side and perimeter of squares is able to predict the actual perimeter value from the measurement of the side of a square. This is possible because the relationship between side and perimeter is an <strong>exact</strong> one. That is, any squares having the same side will have the same perimeter, and there will be no variation in those values.</p>
<p>The line that best fits the relationship between height and handspan, instead, is only able to predict the <strong>average</strong> handspan for a given value of height. This is because there will be a distribution of handspans at each value of height. The line will fit the trend/pattern in the values, but there will be individual-to-individual variability that we must accept around that average pattern.</p>
</div>
<p class="solution-end">
</p>
<div class="statbox">
<p>The <em>mathematical</em> model <span class="math inline">\(Perimeter = 4 \times \ Side\)</span> represents the <strong>exact</strong> relationship between side-length and perimeter of squares.</p>
<p>In contrast, the relationship between height and handspan shows deviations from an “average pattern”. Hence, we need to create a model that allows for deviations from the linear relationship. This is called a <em>statistical</em> model.</p>
<p>A statistical model includes <strong>both</strong> a deterministic function and a random error term:</p>
<p><span class="math display">\[
Handspan = \beta_0 + \beta_1 \ Height + \epsilon
\]</span></p>
<p>or, in short,</p>
<p><span class="math display">\[
y = \underbrace{\beta_0 + \beta_1 \ x}_{f(x)} + \underbrace{\epsilon}_{\text{random error}}
\]</span></p>
<p>The deterministic function need not be linear if the scatterplot displays signs of nonlinearity. In the equation above, the terms <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are numbers specifying where the line going through the data meets the y-axis and its slope (rate of increase/decrease).</p>
</div>
<div class="question-begin">
Question B5
</div>
<div class="question-body">
<div class="cell" data-layout-align="center">

</div>
<p>The line of best-fit is given by:<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p><span class="math display">\[
\widehat{Handspan} = -3 + 0.35 \ Height
\]</span></p>
<p>What is your best guess for the handspan of a student who is 73in tall?</p>
<p>And for students who are 5in?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<p>The predicted average handspan for students who are 73in tall is <span class="math inline">\(-3 + 0.35 * 73 = 22.55\)</span>cm.</p>
<p>The predicted average handspan for students who are 5in tall is <span class="math inline">\(-3 + 0.35 * 5 = -1.25\)</span>cm. But wait, handspan can not be negative… This does not make any sense! That’s right, we went too far off the range of the available data on heights, which were between 57in and 78in. We extrapolated. This is very dangerous…</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://imgs.xkcd.com/comics/extrapolating.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Source: Randall Munroe, xkcd.com</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>Yes, the error term is gone. This is because the line of best-fit gives you the prediction of the average handspan for a given height, and not the individual handspan of a person, which will almost surely be different from the prediction of the line.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>