<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.587">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - Week 5 Exercises: Cov, Cor, Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-down')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 1</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html">
 <span class="dropdown-text">1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html">
 <span class="dropdown-text">1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 2</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html">
 <span class="dropdown-text">2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html">
 <span class="dropdown-text">2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 3</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html">
 <span class="dropdown-text">3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html">
 <span class="dropdown-text">3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html">
 <span class="dropdown-text">Exercises: T-tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 4</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04a_chisq.html">
 <span class="dropdown-text">4A: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revistnhst.html">
 <span class="dropdown-text">4B: Revisiting NHST</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_ex.html">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 5</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li>
    <a class="dropdown-item" href="./05a_covcor.html">
 <span class="dropdown-text">5A: Covariance &amp; Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_ex.html">
 <span class="dropdown-text">Exercises: Cov, Cor, Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-6" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 6</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-6">    
        <li>
    <a class="dropdown-item" href="./06_wt.html">
 <span class="dropdown-text">Walkthrough: Advanced Data Wrangling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 7</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li>
    <a class="dropdown-item" href="./07a_slr.html">
 <span class="dropdown-text">7A: Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_ex.html">
 <span class="dropdown-text">Exercises: Simple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 8</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li>
    <a class="dropdown-item" href="./08a_mlr.html">
 <span class="dropdown-text">Reading 8A: Multiple Linear Regression</span></a>
  </li>  
        <li class="dropdown-header">Exercises</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 9</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li class="dropdown-header">Reading 9A: More Regression</li>
        <li class="dropdown-header">Exercises</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#correlation" id="toc-correlation" class="nav-link active" data-scroll-target="#correlation">Correlation</a></li>
  <li><a href="#functions-and-models" id="toc-functions-and-models" class="nav-link" data-scroll-target="#functions-and-models">Functions and Models</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 5 Exercises: Cov, Cor, Models</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p><strong>Q1:</strong> Go to <a href="http://guessthecorrelation.com/" target="_blank">http://guessthecorrelation.com/</a> and play the “guess the correlation” game for a little while to get an idea of what different strengths and directions of <span class="math inline">\(r\)</span> can look like.</p>
</div>
<p class="question-end">
</p>
<section id="correlation" class="level1">
<h1>Correlation</h1>
<div class="frame">
<p><strong>Data: Sleep levels and daytime functioning</strong></p>
<p>A researcher is interested in the relationship between hours slept per night and self-rated effects of sleep on daytime functioning. She recruited 50 healthy adults, and collected data on the Total Sleep Time (TST) over the course of a seven day period via sleep-tracking devices.<br>
At the end of the seven day period, participants completed a Daytime Functioning (DTF) questionnaire. This involved participants rating their agreement with ten statements (see <span class="citation" data-cites="tab-sleepitems">@tab-sleepitems</span>). Agreement was measured on a scale from 1-5. An overall score of daytime functioning can be calculated by:</p>
<ol type="1">
<li>reversing the scores for items 4,5 and 6 (because those items reflect agreement with <em>positive</em> statements, whereas the other ones are agreement with <em>negative</em> statement);</li>
<li>summing the scores on each item; and</li>
<li>subtracting the sum score from 50 (the max possible score). This will make higher scores reflect better perceived daytime functioning.</li>
</ol>
<p>The data is available at https://uoepsy.github.io/data/sleepdtf.csv.</p>
<div class="cell" data-layout-align="center" data-tbl-cap="Daytime Functioning Questionnaire">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Item    Statement                                        
   &lt;chr&gt;   &lt;chr&gt;                                            
 1 Item_1  I often felt an inability to concentrate         
 2 Item_2  I frequently forgot things                       
 3 Item_3  I found thinking clearly required a lot of effort
 4 Item_4  I often felt happy                               
 5 Item_5  I had lots of energy                             
 6 Item_6  I worked efficiently                             
 7 Item_7  I often felt irritable                           
 8 Item_8  I often felt stressed                            
 9 Item_9  I often felt sleepy                              
10 Item_10 I often felt fatigued                            </code></pre>
</div>
</div>
</div>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Read in the data, and calculate the overall daytime functioning score, following the criteria outlined above. Make this a new column in your dataset.</p>
<div class="hints">
<p>To reverse items 4, 5 and 6, we we need to make all the scores of 1 become 5, scores of 2 become 4, and so on… What number satisfies all of these equations: <code>? - 5 = 1</code>, <code>? - 4 = 2</code>, <code>? - 3 = 3</code>?</p>
<p><br>To quickly sum accross rows, you might find the <code>rowSums()</code> function useful (you don’t have to use it though)</p>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-1" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')"> Solution </span>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sleepdtf <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/sleepdtf.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sleepdtf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      TST             item_1         item_2         item_3         item_4    
 Min.   : 4.900   Min.   :1.00   Min.   :1.00   Min.   :1.00   Min.   :1.00  
 1st Qu.: 7.225   1st Qu.:1.00   1st Qu.:2.00   1st Qu.:1.25   1st Qu.:1.00  
 Median : 7.900   Median :1.00   Median :2.00   Median :2.00   Median :1.00  
 Mean   : 8.004   Mean   :1.58   Mean   :2.46   Mean   :2.38   Mean   :1.26  
 3rd Qu.: 9.025   3rd Qu.:2.00   3rd Qu.:3.00   3rd Qu.:3.00   3rd Qu.:1.00  
 Max.   :11.200   Max.   :3.00   Max.   :5.00   Max.   :5.00   Max.   :3.00  
     item_5         item_6         item_7         item_8        item_9    
 Min.   :1.00   Min.   :1.00   Min.   :1.00   Min.   :1.0   Min.   :1.00  
 1st Qu.:2.00   1st Qu.:2.00   1st Qu.:1.00   1st Qu.:2.0   1st Qu.:2.00  
 Median :2.00   Median :3.00   Median :2.00   Median :2.5   Median :3.00  
 Mean   :2.36   Mean   :2.78   Mean   :2.04   Mean   :2.5   Mean   :2.96  
 3rd Qu.:3.00   3rd Qu.:4.00   3rd Qu.:3.00   3rd Qu.:3.0   3rd Qu.:4.00  
 Max.   :4.00   Max.   :5.00   Max.   :4.00   Max.   :4.0   Max.   :5.00  
    item_10    
 Min.   :1.00  
 1st Qu.:2.00  
 Median :3.00  
 Mean   :2.54  
 3rd Qu.:3.00  
 Max.   :5.00  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To reverse the items, we can simply do 6 minus the score.   </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>sleepdtf <span class="ot">&lt;-</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  sleepdtf <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">item_4=</span><span class="dv">6</span><span class="sc">-</span>item_4,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">item_5=</span><span class="dv">6</span><span class="sc">-</span>item_5,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">item_6=</span><span class="dv">6</span><span class="sc">-</span>item_6</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Now using rowSums(), and subtracting it from 50 (the max score)</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>sleepdtf<span class="sc">$</span>dtf <span class="ot">=</span> <span class="dv">50</span><span class="sc">-</span><span class="fu">rowSums</span>(sleepdtf[, <span class="dv">2</span><span class="sc">:</span><span class="dv">11</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Calculate the correlation between the total sleep time (<code>TST</code>) and the overall daytime functioning score calculated in the previous question.<br>
Conduct a test to establish the probability of observing a correlation this strong in a sample of this size assuming the true correlation to be 0.<br>
<br> Write a sentence or two summarising the results.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(sleepdtf<span class="sc">$</span>TST, sleepdtf<span class="sc">$</span>dtf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  sleepdtf$TST and sleepdtf$dtf
t = 6.244, df = 48, p-value = 1.062e-07
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4807039 0.7989417
sample estimates:
      cor 
0.6694741 </code></pre>
</div>
</div>
<div class="int">
<p>There was a strong positive correlation between total sleep time and self-reported daytime functioning score (<span class="math inline">\(r\)</span> = 0.67, <span class="math inline">\(t(48)\)</span> = 6.24, <span class="math inline">\(p &lt; .001\)</span>) in the current sample. As total sleep time increased, levels of self-reported daytime functioning increased.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4 (open-ended)
</div>
<div class="question-body">
<p>Think about this relationship in terms of <em>causation</em>.<br>
<br> Claim: <em>Less sleep causes poorer daytime functioning.</em><br>
<br> Why might it be inappropriate to make the claim above based on these data alone? Think about what sort of study could provide stronger evidence for such a claim.</p>
<div class="hints">
<p>Things to think about:</p>
<ul>
<li>comparison groups.<br>
</li>
<li>random allocation.<br>
</li>
<li>measures of daytime functioning.<br>
</li>
<li>measures of sleep time.<br>
</li>
<li>other (unmeasured) explanatory variables.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="functions-and-models" class="level1">
<h1>Functions and Models</h1>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>The Scottish National Gallery kindly provided us with measurements of side and perimeter (in metres) for a sample of 10 square paintings.</p>
<p>The data are provided below:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sng <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">side =</span> <span class="fu">c</span>(<span class="fl">1.3</span>, <span class="fl">0.75</span>, <span class="dv">2</span>, <span class="fl">0.5</span>, <span class="fl">0.3</span>, <span class="fl">1.1</span>, <span class="fl">2.3</span>, <span class="fl">0.85</span>, <span class="fl">1.1</span>, <span class="fl">0.2</span>),</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">perimeter =</span> <span class="fu">c</span>(<span class="fl">5.2</span>, <span class="fl">3.0</span>, <span class="fl">8.0</span>, <span class="fl">2.0</span>, <span class="fl">1.2</span>, <span class="fl">4.4</span>, <span class="fl">9.2</span>, <span class="fl">3.4</span>, <span class="fl">4.4</span>, <span class="fl">0.8</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Plot the data from the Scottish National Gallery using <code>ggplot()</code>.</p>
<p>We know that there is a mathematical model for the relationship between the side-length and perimeter of squares: <span class="math inline">\(perimeter = 4 \times \ side\)</span>.<br>
Try adding the following line to your plot:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="sc">~</span>.x <span class="sc">*</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sng <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">side =</span> <span class="fu">c</span>(<span class="fl">1.3</span>, <span class="fl">0.75</span>, <span class="dv">2</span>, <span class="fl">0.5</span>, <span class="fl">0.3</span>, <span class="fl">1.1</span>, <span class="fl">2.3</span>, <span class="fl">0.85</span>, <span class="fl">1.1</span>, <span class="fl">0.2</span>),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">perimeter =</span> <span class="fu">c</span>(<span class="fl">5.2</span>, <span class="fl">3.0</span>, <span class="fl">8.0</span>, <span class="fl">2.0</span>, <span class="fl">1.2</span>, <span class="fl">4.4</span>, <span class="fl">9.2</span>, <span class="fl">3.4</span>, <span class="fl">4.4</span>, <span class="fl">0.8</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sng, <span class="fu">aes</span>(<span class="at">x =</span> side, <span class="at">y =</span> perimeter)) <span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">'black'</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Side (m)'</span>, <span class="at">y =</span> <span class="st">'Perimeter (m)'</span>)<span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="sc">~</span>.x <span class="sc">*</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-squares-scatterplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05_ex_files/figure-html/fig-squares-scatterplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 1: The exact relationship between side and perimeter of squares.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The above plot shows perfect agreement between the observed data and the model.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Use our mathematical model to predict the perimeter of a painting with a side of 1.5 metres.<br>
We do not have a painting with a side of 1.5 metres within the random sample of paintings from the Scottish National Gallery, but we can work out the perimeter of an hypothetical square painting with 1.5m sides, using our model.</p>
<p>You can obtain this prediction either using the plot from the previous question, or calculating it algebraically.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p><strong>Visual approach</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_ex_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Sometimes we can directly read a predicted value from the graph of the functional relationship.</p>
<p>Consider the plot created in the previous question. First, we need to check where x = 1.5. Then, we draw a vertical dashed line until it meets the blue line. The y value corresponding to x = 1.5 can be read off the y-axis.</p>
<p>However, in this case it is not that easy to read it from the drawing… Let’s try the next approach.</p>
<p><br> <strong>Algebraic approach</strong></p>
<p>You can substitute the x value in the formula and calculate the corresponding y value.</p>
<p><span class="math display">\[
y = 4 \times \ x = 4 \times \ (1.5) = 6
\]</span></p>
<p><br></p>
<div class="int">
<p>The predicted perimeter of squared paintings having a 1.5m side is 6m.</p>
</div>
<p><strong>NOTE</strong>: Don’t forget to always include the measurement units when reporting/writing-up results!</p>
</div>
<p class="solution-end">
</p>
<div class="frame">
<p><strong>Data: HandHeight</strong></p>
<p>This dataset, from Jessican M Utts and Robert F Heckard. 2015. <em>Mind on Statistics</em> (Cengage Learning)., records the height and handspan reported by a random sample of 167 students as part of a class survey.</p>
<p>The variables are:</p>
<ul>
<li><code>height</code>, measured in inches</li>
<li><code>handspan</code>, measured in centimetres</li>
</ul>
<p>The data are available at <a href="https://uoepsy.github.io/data/handheight.csv" target="_blank">https://uoepsy.github.io/data/handheight.csv</a></p>
</div>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Consider the relationship between height (in inches) and handspan (in cm).</p>
<p>Read the handheight data into R, and investigate how handspan varies as a function of height for the students in the sample.</p>
<p>Do you notice any outliers or points that do not fit with the pattern in the rest of the data?</p>
<p>Comment on any main differences you notice between this relationship and the relationship between sides and perimeter of squares.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>The <code>handheight</code> data set contains two variables, height and handspan, which are both numeric and continuous. We display the relationship between two numeric variables with a scatterplot.</p>
<p>We can also add marginal boxplots for each variable using the package <code>ggExtra</code>. Before using the package, make sure you have it installed via <code>install.packages('ggExtra')</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>handheight <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">'https://uoepsy.github.io/data/handheight.csv'</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggExtra)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>plt <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(handheight, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> handspan)) <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Height (in.)'</span>, <span class="at">y =</span> <span class="st">'Handspan (cm)'</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggMarginal</span>(plt, <span class="at">type =</span> <span class="st">'boxplot'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-handheight-scatterplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05_ex_files/figure-html/fig-handheight-scatterplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 2: The statistical relationship between height and handspan.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Outliers are extreme observations that do not seem to fit with the rest of the data. This could either be:</p>
<ul>
<li><em>marginally</em> along one axis: points that have an unusual (too high or too low) x-coordinate or y-coordinate;</li>
<li><em>jointly</em>: observations that do not fit with the rest of the point cloud.</li>
</ul>
<p>The boxplots in <span class="citation" data-cites="fig:handheight-scatterplot">@fig:handheight-scatterplot</span> do not highlight any outliers in the marginal distributions of height and handspan. Furthermore, from the scatterplot we do not notice any extreme observations or points that do not fit with the rest of the point cloud.</p>
<p>We notice a moderate, positive (that is, increasing) linear relationship between height and handspan.</p>
<p>Recall <a href="#fig-squares-scatterplot">Figure&nbsp;1</a>, displaying the relationship between side and perimeters of squares. In the plot we notice two points on top of each other, reflecting the fact that two squares having the same side will always have the same perimeter. In fact, the data from the Scottish National Gallery include two squared paintings with a side of 1.1m, both having a measured perimeter of 4.4m.</p>
<p>Figure @ref(fig:handheight-scatterplot), instead, displays the relationship between height and handspan of a sample of students. The first thing that grabs our attention is the fact that students having the same height do not necessarily have the same handspan. Rather, we clearly see a variety of handspan values for students all having a height of, for example, 70in. To be more precise, the seven students who are 70 in. tall all have differing handspans.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Using the following command, superimpose on top of your scatterplot a best-fit line describing how handspan varies as a function of height. For the moment, the argument <code>se = FALSE</code> tells R to not display uncertainty bands.</p>
<pre><code>geom_smooth(method = lm, se = FALSE)</code></pre>
<p>Comment on any differences you notice with the line summarising the linear relationship between side and perimeter.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(handheight, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> handspan)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Height (in.)'</span>, <span class="at">y =</span> <span class="st">'Handspan (cm)'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_ex_files/figure-html/handheight-fitted-model-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">The best-fit line.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The line representing the relationship between side and perimeter of squares is able to predict the actual perimeter value from the measurement of the side of a square. This is possible because the relationship between side and perimeter is an <strong>exact</strong> one. That is, any squares having the same side will have the same perimeter, and there will be no variation in those values.</p>
<p>The line that best fits the relationship between height and handspan, instead, is only able to predict the <strong>average</strong> handspan for a given value of height. This is because there will be a distribution of handspans at each value of height. The line will fit the trend/pattern in the values, but there will be individual-to-individual variability that we must accept around that average pattern.</p>
</div>
<p class="solution-end">
</p>
<div class="statbox">
<p>The <em>mathematical</em> model <span class="math inline">\(Perimeter = 4 \times \ Side\)</span> represents the <strong>exact</strong> relationship between side-length and perimeter of squares.</p>
<p>In contrast, the relationship between height and handspan shows deviations from an “average pattern”. Hence, we need to create a model that allows for deviations from the linear relationship. This is called a <em>statistical</em> model.</p>
<p>A statistical model includes <strong>both</strong> a deterministic function and a random error term:</p>
<p><span class="math display">\[
Handspan = \beta_0 + \beta_1 \ Height + \epsilon
\]</span></p>
<p>or, in short,</p>
<p><span class="math display">\[
y = \underbrace{\beta_0 + \beta_1 \ x}_{f(x)} + \underbrace{\epsilon}_{\text{random error}}
\]</span></p>
<p>The deterministic function need not be linear if the scatterplot displays signs of nonlinearity. In the equation above, the terms <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are numbers specifying where the line going through the data meets the y-axis and its slope (rate of increase/decrease).</p>
</div>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<div class="cell" data-layout-align="center">

</div>
<p>The line of best-fit is given by:<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p><span class="math display">\[
\widehat{Handspan} = -3 + 0.35 \ Height
\]</span></p>
<p>What is your best guess for the handspan of a student who is 73in tall?</p>
<p>And for students who are 5in?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>The predicted average handspan for students who are 73in tall is <span class="math inline">\(-3 + 0.35 * 73 = 22.55\)</span>cm.</p>
<p>The predicted average handspan for students who are 5in tall is <span class="math inline">\(-3 + 0.35 * 5 = -1.25\)</span>cm. But wait, handspan can not be negative… This does not make any sense! That’s right, we went too far off the range of the available data on heights, which were between 57in and 78in. We extrapolated. This is very dangerous…</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-xkcd2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="https://imgs.xkcd.com/comics/extrapolating.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 3: Source: Randall Munroe, xkcd.com</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>Yes, the error term is gone. This is because the line of best-fit gives you the prediction of the average handspan for a given height, and not the individual handspan of a person, which will almost surely be different from the prediction of the line.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>