<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - 7A: Simple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-down')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>
<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 1</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html">
 <span class="dropdown-text">1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html">
 <span class="dropdown-text">1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 2</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html">
 <span class="dropdown-text">2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html">
 <span class="dropdown-text">2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 3</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html">
 <span class="dropdown-text">3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html">
 <span class="dropdown-text">3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html">
 <span class="dropdown-text">Exercises: T-tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 4</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04a_chisq.html">
 <span class="dropdown-text">4A: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revisitnhst.html">
 <span class="dropdown-text">4B: Revisiting NHST</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_ex.html">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 5</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li class="dropdown-header">5A: Covariance &amp; Correlation</li>
        <li class="dropdown-header">Exercises: Cov, Cor, Models</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-6" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 6</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-6">    
        <li class="dropdown-header">Walkthrough: Advanced Data Wrangling</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 7</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li class="dropdown-header">7A: Simple Linear Regression</li>
        <li class="dropdown-header">Exercises: Simple Linear Regression</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 8</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li class="dropdown-header">8A: Multiple Linear Regression</li>
        <li class="dropdown-header">8B: Assumptions, Diagnostics, and Troubleshooting</li>
        <li class="dropdown-header">Exercises: Multiple Linear Regression</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 9</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li class="dropdown-header">9A: Interactions</li>
        <li class="dropdown-header">9B: Categorical Predictors</li>
        <li class="dropdown-header">Exercises: Interactions</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-10" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 10</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-10">    
        <li class="dropdown-header">10A: GLM!</li>
        <li class="dropdown-header">Exercises: Logistic Regression</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-11" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 11</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-11">    
        <li class="dropdown-header">11A: Common Tests as Linear Models</li>
        <li class="dropdown-header">11B: Writing Up</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-linear-model" id="toc-the-linear-model" class="nav-link active" data-scroll-target="#the-linear-model">The Linear Model</a>
  <ul class="collapse">
  <li><a href="#the-model" id="toc-the-model" class="nav-link" data-scroll-target="#the-model">The Model</a></li>
  <li><a href="#the-error" id="toc-the-error" class="nav-link" data-scroll-target="#the-error">The Error</a></li>
  </ul></li>
  <li><a href="#fitting-linear-models-in-r" id="toc-fitting-linear-models-in-r" class="nav-link" data-scroll-target="#fitting-linear-models-in-r">Fitting Linear Models in R</a>
  <ul class="collapse">
  <li><a href="#lm" id="toc-lm" class="nav-link" data-scroll-target="#lm">lm()</a></li>
  <li><a href="#model-summary" id="toc-model-summary" class="nav-link" data-scroll-target="#model-summary">Model Summary</a></li>
  <li><a href="#model-predictions" id="toc-model-predictions" class="nav-link" data-scroll-target="#model-predictions">Model Predictions</a></li>
  </ul></li>
  <li><a href="#inference-for-regression-coefficients" id="toc-inference-for-regression-coefficients" class="nav-link" data-scroll-target="#inference-for-regression-coefficients">Inference for Regression Coefficients</a></li>
  <li><a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation">Model Evaluation</a>
  <ul class="collapse">
  <li><a href="#partitioning-variance" id="toc-partitioning-variance" class="nav-link" data-scroll-target="#partitioning-variance">Partitioning Variance</a></li>
  <li><a href="#r2" id="toc-r2" class="nav-link" data-scroll-target="#r2"><span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#the-f-statistic" id="toc-the-f-statistic" class="nav-link" data-scroll-target="#the-f-statistic">The <span class="math inline">\(F\)</span> Statistic</a></li>
  </ul></li>
  <li><a href="#binary-predictors" id="toc-binary-predictors" class="nav-link" data-scroll-target="#binary-predictors">Binary Predictors</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">7A: Simple Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="the-linear-model" class="level1 page-columns page-full">
<h1>The Linear Model</h1>
<p>In its simplest form, linear regression is a way to make a model of the relationship between two variables. When both variables are continuous, it is nice and intuitive to envisage this as the ‘line of best fit’ on a scatterplot. For instance, in <a href="#fig-lmintro">Figure&nbsp;1</a> we see two variables <code>y</code> and <code>x</code>, and our linear regression model is the blue line.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lmintro" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-lmintro-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 1: y regressed onto x.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We’re going to use the data in this plot for the remainder of the reading. If you wish to play around with it yourself, it is available at <a href="https://uoepsy.github.io/data/usmr_slr.csv">https://uoepsy.github.io/data/usmr_slr.csv</a>, and contains a sample of 100 observations on variables <code>x</code> and <code>y</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_slr.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
      x     y
  &lt;dbl&gt; &lt;dbl&gt;
1  3.19  4.42
2  2.57  4.48
3  3.91  2.72
4  4.79  5.39
5  4.00  3.85
6  4.11  4.42</code></pre>
</div>
</div>
<p><a href="#fig-lmintro">Figure&nbsp;1</a>, above, highlights a linear relationship, where the data points are scattered around an underlying linear pattern with a roughly-constant spread as we move along <code>x</code>.</p>
<p>In <a href="05a_covcor.html" target="_blank">5A: Covariance &amp; Correlation</a> we have already talked about one way to describe this relationship, by calculating either the covariance or the correlation between <code>x</code> and <code>y</code>.<br>
However, as we will see in the coming weeks, the linear model provides us with the scope to extend our analysis to many more situations - it is the building block of many more complex analytical methods.</p>
<p>The simple linear regression model takes the form:</p>
<p><span class="math display">\[
\begin{align}
&amp; y = b_0 + b_1 \ x + \epsilon \quad \\
\end{align}
\]</span></p>

<div class="no-row-height column-margin column-container"><div class="">
<p>You will see a variety of different ways of specifying the linear model form in different resources, some use <span class="math inline">\(\beta\)</span>, some use <span class="math inline">\(b\)</span>. Sometimes you will see <span class="math inline">\(\alpha\)</span> instead of <span class="math inline">\(b_0\)</span>.</p>
</div></div><p>We typically refer to the outcome (‘dependent’) variable with the letter <span class="math inline">\(y\)</span> and to our predictor (‘explanatory’/‘independent’) variables with the letter <span class="math inline">\(x\)</span>. When we construct a linear model we are trying to re-express our outcome variable <span class="math inline">\(y\)</span> with some linear transformation of our predictor variable <span class="math inline">\(x\)</span>.</p>
<p>You can think of this in broader terms as:</p>
<p><span class="math display">\[
\begin{align}
&amp; \color{red}{Outcome}\color{} = \color{blue}{Model}\color{black}{} + Error\\
\end{align}
\]</span></p>
<section id="the-model" class="level2">
<h2 class="anchored" data-anchor-id="the-model">The Model</h2>
<p>When we fit a simple regression model, the bit we refer to as the ‘model’ is the line that is defined by two numbers:</p>
<ul>
<li>the <strong>intercept</strong>, denoted <span class="math inline">\(b_0\)</span>.<br>
This is the point at which the line hits the y-axis (i.e.&nbsp;where <span class="math inline">\(x=0\)</span>)</li>
<li>the <strong>slope</strong>, denoted <span class="math inline">\(b_1\)</span>.<br>
This is the angle of the line. It is the amount which the line increases for every 1 increase in <span class="math inline">\(x\)</span>.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-slr" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-slr-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 2: Simple linear regression model, with the systematic part of the model in blue</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>This line implies some <em>predicted</em> values for our observed <span class="math inline">\(x\)</span> values. For instance, we can see that when <span class="math inline">\(x=3\)</span>, the model (the blue line) will predict that <span class="math inline">\(y\)</span> is approximately 4. If we take each of our datapoints, and project them up/down to the line, then we get our fitted values (<a href="#fig-slrfit">Figure&nbsp;3</a>). We often denote these as <span class="math inline">\(\hat y\)</span> (or “y hat”), with the hat indicating that they are the model-estimated values of <span class="math inline">\(y\)</span>.</p>
<p><span class="math display">\[
\begin{align}
\color{red}{Outcome}\color{black} \qquad=\qquad &amp; \color{blue}{Model}\color{black}{} &amp; +\qquad Error\\
\color{red}{y}\color{black} \qquad = \qquad &amp; \color{blue}{\hat y}\color{black} &amp; +\qquad \epsilon \quad \\
\color{red}{y}\color{black} \qquad = \qquad &amp; \color{blue}{b_0 + b_1 \ (x)}\color{black} &amp; +\qquad \epsilon \quad \\
\end{align}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-slrfit" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-slrfit-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 3: Simple linear regression model, fitted values in blue</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Optional: Regression Slope vs Covariance</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p>With simple linear regression, the fitted line we are describing is actually a scaled version of our covariance.</p>
<p>Remember that covariance is the average of the products of <span class="math inline">\((x_{i}-\bar{x})(y_{i}-\bar{y})\)</span>, which is a bit like the average area of the rectangles in <a href="#fig-covsq">Figure&nbsp;4</a>. If we think about what the average <strong>width</strong> of these rectangles is, it is the average of <span class="math inline">\((x_{i}-\bar{x})\)</span>, which is actually just the variance of <span class="math inline">\(x\)</span>!</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-covsq" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-covsq-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 4: Covariance</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We can divide the area of the average rectangle (<span class="math inline">\(cov(x, y)\)</span>) by its width (<span class="math inline">\(var(x)\)</span>), thereby scaling it so that the width is 1. What we’re getting from our coefficient is the area of this new rectangle which has width = 1. Because width = 1, the area is also the height (<span class="math inline">\(\text{area} = \text{width} \times \text{height} = 1 \times \text{height}\)</span>). So what we get is the amount that <span class="math inline">\(y\)</span> increases (the height) as <span class="math inline">\(x\)</span> increases by 1 (the width).</p>
<p>We can see this working:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(my_data<span class="sc">$</span>x, my_data<span class="sc">$</span>y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6877738</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(my_data<span class="sc">$</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8823097</code></pre>
</div>
</div>
<p>This calculation gives us the same linear regression slope of 0.78 that we see when we fit the model lower down this page.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(my_data<span class="sc">$</span>x, my_data<span class="sc">$</span>y)<span class="sc">/</span><span class="fu">var</span>(my_data<span class="sc">$</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7795152</code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section>
<section id="the-error" class="level2">
<h2 class="anchored" data-anchor-id="the-error">The Error</h2>
<p>Our model is not perfect. It is a model - i.e.&nbsp;it is a simplification of the world, and so is inherently going to be inaccurate for individuals. This innaccuracy can be seen in the plots above: some points are higher than the model predicts, some lower. These deviations (shown by the red lines in <a href="#fig-slr2">Figure&nbsp;5</a>) from the model are the random error component <span class="math inline">\(\hat \epsilon\)</span>, or “residuals”.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-slr2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-slr2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 5: Simple linear regression model, with the systematic part of the model in blue, and residuals in red</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In full, we should really write our linear regression model out as:</p>
<p><span class="math display">\[
\begin{align}
&amp; y = b_0 + b_1 \ x + \epsilon \quad \\
&amp; \text{where} \\
&amp; \epsilon \sim N(0, \sigma) \text{ independently}
\end{align}
\]</span></p>
<p>The new bit here: “<span class="math inline">\(\epsilon \sim N(0, \sigma) \text{ independently}\)</span>” means that the errors around the line have mean zero and constant spread as x varies (we’ll read more about what this means later in this course, when we discuss the assumptions underlying regression). You can think of <span class="math inline">\(\sim N(0, \sigma)\)</span> as meaning “normally distributed with a mean of zero and a standard deviation of <span class="math inline">\(\sigma\)</span>”.</p>
<p>The standard deviation of the errors, denoted by <span class="math inline">\(\sigma\)</span> is an important quantity that our model estimates. It measures how much individual data points tend to deviate above and below the regression line. A small <span class="math inline">\(\sigma\)</span> indicates that the points hug the line closely and we should expect fairly accurate predictions, while a large <span class="math inline">\(\sigma\)</span> suggests that, even if we estimate the line perfectly, we can expect individual values to deviate from it by substantial amounts.</p>
<p><span class="math inline">\(\sigma\)</span> is estimated by essentially averaging squared residuals (giving the variance) and taking the square-root:</p>
<p><span class="math display">\[
\begin{align}
&amp; \hat \sigma = \sqrt{\frac{SS_{Residual}}{n - 2}} \\
\qquad \\
&amp; \text{where} \\
&amp; SS_{Residual} = \textrm{Sum of Squared Residuals} = \sum_{i=1}^n{(\epsilon_i)^2}
\end{align}
\]</span></p>
<div class="divider div-transparent div-dot">

</div>
</section>
</section>
<section id="fitting-linear-models-in-r" class="level1">
<h1>Fitting Linear Models in R</h1>
<section id="lm" class="level2">
<h2 class="anchored" data-anchor-id="lm">lm()</h2>
<p>In R it is very easy to fit linear models, we just need to use the <code>lm()</code> function.</p>
<p>The syntax of the <code>lm()</code> function is:</p>
<pre><code>model_name &lt;- lm(outcome ~ 1 + predictor, data = dataframe)</code></pre>
<p>We don’t <em>have</em> to include the <code>1 +</code> when we specify the model, as this will be included by default, so we can also simply write:</p>
<pre><code>model_name &lt;- lm(outcome ~ predictor, data = dataframe)</code></pre>
<div class="optional-begin">
<span id="opt-start-2" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-2', 'opt-start-2')"> <span class="olab">What is the ~1 + doing?</span></span>
</div>
<div id="opt-body-2" class="optional-body" style="display: none;">
<p>The fitted model can be written as</p>
<p><span class="math display">\[
\hat y = \hat b_0 + \hat b_1 x
\]</span></p>
<p>The predicted values for the outcome are equal to our intercept, <span class="math inline">\(\hat b_0\)</span>, plus our slope <span class="math inline">\(\hat b_1\)</span> multiplied by the value on our explanatory variable <span class="math inline">\(x\)</span>.<br>
The intercept is a <em>constant</em>. That is, we could write it as multiplied by 1:</p>
<p><span class="math display">\[
\hat y = \color{blue}{\hat b_0}\color{black}{}(\color{green}{1}\color{black}{})\color{blue}{ + \hat b_1 }\color{black}{}(\color{green}{x}\color{black}{})
\]</span></p>
<p>When we specify the linear model in R, we include after the tilde sign <code>~</code> all the things which appear to the right of each of the <span class="math inline">\(\hat b\)</span>s (the bits in green in the equartion above). That’s why the 1 is included. It is just saying “we want the intercept, <span class="math inline">\(b_0\)</span>, to be estimated”.</p>
</div>
<p class="optional-end">
</p>
</section>
<section id="model-summary" class="level2">
<h2 class="anchored" data-anchor-id="model-summary">Model Summary</h2>
<p>We can then view lots of information by giving our model to the <code>summary()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lmoutput" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/slr/slr1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6: Output of lm() for a simple regression in R</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The <strong>intercept</strong> <span class="math inline">\(b_0\)</span> is the point at which the line hits the y-axis (i.e.&nbsp;where <span class="math inline">\(x=0\)</span>), and the <strong>slope</strong> <span class="math inline">\(b_1\)</span> is the amount which the line increases for every 1 increase in <span class="math inline">\(x\)</span>. We can see the estimated values of these in <a href="#fig-lmoutput">Figure&nbsp;6</a>, providing us with our fitted line:</p>
<p><span class="math display">\[
\begin{align}
y &amp;= 1.54 + 0.78 (x) + \varepsilon \\
\end{align}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-slrest" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-slrest-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 7: Simple linear regression model, estimated intercept and slope included</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-predictions" class="level2">
<h2 class="anchored" data-anchor-id="model-predictions">Model Predictions</h2>
<p>Furthermore, we can get out the model predicted values for <span class="math inline">\(y\)</span>, the “y hats” (<span class="math inline">\(\hat y\)</span>), using functions such as:</p>
<ul>
<li><code>predict(my_model)</code></li>
<li><code>fitted(my_model)</code></li>
<li><code>fitted.values(my_model)</code></li>
<li><code>my_model$fitted.values</code></li>
</ul>
<p>A nice package which will come in handy is the <strong>broom</strong> package. It allows us to use the function <code>augment()</code>, which gives us out lots of information, such as the model predicted values, the residuals, and many more:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(my_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 8
       y     x .fitted .resid   .hat .sigma  .cooksd .std.resid
   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
 1  4.42  3.19    4.03  0.388 0.0102  0.935 0.000903      0.420
 2  4.48  2.57    3.54  0.941 0.0130  0.931 0.00681       1.02 
 3  2.72  3.91    4.59 -1.87  0.0180  0.916 0.0378       -2.03 
 4  5.39  4.79    5.28  0.107 0.0438  0.935 0.000319      0.118
 5  3.85  4.00    4.66 -0.809 0.0197  0.932 0.00776      -0.878
 6  4.42  4.11    4.74 -0.327 0.0222  0.935 0.00143      -0.355
 7  4.30  2.72    3.66  0.638 0.0114  0.933 0.00274       0.689
 8  5.94  4.02    4.68  1.26  0.0202  0.927 0.0193        1.37 
 9  1.70  3.05    3.92 -2.22  0.0100  0.908 0.0291       -2.40 
10  4.79  4.58    5.11 -0.318 0.0358  0.935 0.00224      -0.348
# … with 90 more rows</code></pre>
</div>
</div>
<p>We can also compute model-predicted values for other (unobserved) data. For instance, what about for an observation where <span class="math inline">\(x=10\)</span>, or <span class="math inline">\(20\)</span>?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make a dataframe with values for the predictor:</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>some_newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">20</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model predicted values of y, for the values of x inside the 'some_newdata' object:</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(my_model, <span class="at">newdata =</span> some_newdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
 9.33792 17.13307 </code></pre>
</div>
</div>
<p>Given that our fitted model takes the form below, we can work this out ourselves as well:</p>
<p><span class="math display">\[
\begin{align}
y &amp;= 1.54 + 0.78\cdot x \\
y &amp;= 1.54 + 0.78\cdot 10 \\
y &amp;= 1.54 + 7.80\\
y &amp;= 9.34 \\
\end{align}
\]</span></p>
<div class="divider div-transparent div-dot">

</div>
</section>
</section>
<section id="inference-for-regression-coefficients" class="level1 page-columns page-full">
<h1>Inference for Regression Coefficients</h1>
<p>Now that we have fitted a linear model, and we know how we interpret our coefficient estimates, we would like to be able to make a statement on whether these relationships are likely to hold in the population.<br>
Our coefficients accurately describe the relationship between <span class="math inline">\(y\)</span> (outcome) and <span class="math inline">\(x\)</span> (predictor) in our sample, but we are yet to perform a statistical test. A test will enable us to discuss how likely it is that we would see this relationship in our sample, if the relationship doesn’t hold for the population.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sillyfig" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/slr/conv1a.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 8: Estimates without inference</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Much like our discussion of sample means and intervals in <a href="02b_sampling.html" target="_blank">2B: Sampling &amp; Curves</a>, we have our coefficients:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(my_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           x 
  1.5427681   0.7795152 </code></pre>
</div>
</div>
<p>and to quantify the amount of uncertainty in each estimated coefficient that is due to sampling variability, we use the standard error (SE)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> of the coefficient.</p>
<p>The standard errors are found in the column “Std. Error” of the <code>summary()</code> of a model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my_model)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 1.5427681 0.32004944 4.820406 5.239619e-06
x           0.7795152 0.09959062 7.827194 5.917849e-12</code></pre>
</div>
</div>
<p>In this example the slope, 0.78, has a standard error of 0.10. One way to envision this is as a distribution. Our best guess (mean) for the slope parameter is 0.78. The standard deviation of this distribution is 0.10, which indicates the precision (uncertainty) of our estimate.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sampbeta" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-sampbeta-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 9: Sampling distribution of the slope coefficient. The distribution is approximately bell-shaped with a mean of 0.78 and a standard error of 0.10.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We can perform a test against the null hypothesis that the estimate is zero. The reference distribution in this case is a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, where <span class="math inline">\(n\)</span> is the sample size, and our test statistic is:</p>
<p><span class="math display">\[
t = \frac{\hat b_1 - 0}{SE(\hat b_1)}
\]</span></p>
<p>This allows us to test the hypothesis that the population slope is zero — that is, that there is no linear association between income and education level in the population.</p>
<p>We don’t actually have to <strong>do</strong> anything for this, it’s all provided for us in the <code>summary()</code> of the model! The information is contained in the row corresponding to the variable “education” in the output of <code>summary()</code>, which reports the t-statistic under <code>t value</code> and the p-value under <code>Pr(&gt;|t|)</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my_model)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 1.5427681 0.32004944 4.820406 5.239619e-06
x           0.7795152 0.09959062 7.827194 5.917849e-12</code></pre>
</div>
</div>
<div class="int">
<p>A significant association was found between x and y (<span class="math inline">\(b = 0.78\)</span>, <span class="math inline">\(SE = 0.10\)</span>, <span class="math inline">\(t(98)=7.83\)</span>, <span class="math inline">\(p&lt;.001\)</span>).</p>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Recall that the p-value <code>5.92-e12</code> in the <code>Pr(&gt;|t|)</code> column simply means <span class="math inline">\(5.92 \times 10^{-12}\)</span>. This is a very small value, hence we will report it as &lt;.001 following the APA guidelines.</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sillyfig2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/slr/conv2a.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 10: Conversations with statisticians</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="model-evaluation" class="level1 page-columns page-full">
<h1>Model Evaluation</h1>
<section id="partitioning-variance" class="level2">
<h2 class="anchored" data-anchor-id="partitioning-variance">Partitioning Variance</h2>
<p>We might ask ourselves if the model is useful in explaining the variance in our outcome variable <span class="math inline">\(y\)</span>. To quantify and assess model utility, we split the total variability of the outcome variable into two terms: the variability explained by the model plus the variability left unexplained in the residuals.</p>
<p><span class="math display">\[
\begin{align}
&amp; \qquad \qquad \qquad \qquad \text{total variability in response } =  \\
&amp; \text{variability explained by model } + \text{unexplained variability in residuals}
\end{align}
\]</span></p>
<p>The illustration in <a href="#fig-sstssrssm">Figure&nbsp;11</a> gets at the intuition behind this: the top panel shows the total variability in the outcome variable <span class="math inline">\(y\)</span> - for each datapoint we see the distance from the mean of y. These distances can be split into the bit from the mean to the model predicted value (seen in the bottom left panel of <a href="#fig-sstssrssm">Figure&nbsp;11</a>), and the bit from that value to the actual value (bottom right panel).</p>
<p>Each term can be quantified by a sum of squares:</p>
<p><span class="math display">\[
\begin{aligned}
SS_{Total} &amp;= SS_{Model} + SS_{Residual} \\
\sum_{i=1}^n (y_i - \bar y)^2 &amp;= \sum_{i=1}^n (\hat y_i - \bar y)^2 + \sum_{i=1}^n (y_i - \hat y_i)^2 \\
\quad \\
\text{Where:} \\
&amp; y_i = \text{observed value} \\
&amp;\bar{y} = \text{mean} \\
&amp; \hat{y}_i = \text{model predicted value} \\
\end{aligned}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sstssrssm" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-sstssrssm-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 11: Total Sums of Squares = Model Sums of Squares + Residual Sums of Squares</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="r2" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="r2"><span class="math inline">\(R^2\)</span></h2>
<p>A useful statistic is the <span class="math inline">\(R^2\)</span>, which shows us the proportion of the total variability in the outcome (<code>y</code>) that is explained by the linear relationship with the predictor (<code>x</code>).</p>
<div class="sticky">
<p>The <span class="math inline">\(R^2\)</span> coefficient is defined as the proportion of the total variability in the outcome variable which is explained by our model:</p>
<p><span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
</div>
<p>We can find the <span class="math inline">\(R^2\)</span> easily in the <code>summary()</code> of the model!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = my_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.4383 -0.6593  0.1075  0.5945  2.1867 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.54277    0.32005   4.820 5.24e-06 ***
x            0.77952    0.09959   7.827 5.92e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9308 on 98 degrees of freedom
Multiple R-squared:  0.3847,    Adjusted R-squared:  0.3784 
F-statistic: 61.26 on 1 and 98 DF,  p-value: 5.918e-12</code></pre>
</div>
</div>
<p>The output of <code>summary()</code> displays the R-squared value in the following line:</p>
<pre><code>Multiple R-squared:  0.3847</code></pre>

<div class="no-row-height column-margin column-container"><div class="">
<p>For the moment, ignore “Adjusted R-squared”. We will come back to this later on.</p>
</div></div><div class="int">
<p>Approximately 38% of the total variability in <code>y</code> is explained by the linear association with <code>x</code>.</p>
</div>
<div class="optional-begin">
<span id="opt-start-3" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-3', 'opt-start-3')"> <span class="olab">Optional - Manual calculation of R-Squared</span></span>
</div>
<div id="opt-body-3" class="optional-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>my_model_fitted <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">y_hat =</span> <span class="fu">predict</span>(my_model),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">resid =</span> y <span class="sc">-</span> y_hat</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(my_model_fitted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
      x     y y_hat  resid
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1  3.19  4.42  4.03  0.388
2  2.57  4.48  3.54  0.941
3  3.91  2.72  4.59 -1.87 
4  4.79  5.39  5.28  0.107
5  4.00  3.85  4.66 -0.809
6  4.11  4.42  4.74 -0.327</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>my_model_fitted <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">SSModel =</span> <span class="fu">sum</span>( (y_hat <span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">^</span><span class="dv">2</span> ),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">SSTotal =</span> <span class="fu">sum</span>( (y <span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">RSquared =</span> SSModel <span class="sc">/</span> SSTotal</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  RSquared
     &lt;dbl&gt;
1    0.385</code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section>
<section id="the-f-statistic" class="level2">
<h2 class="anchored" data-anchor-id="the-f-statistic">The <span class="math inline">\(F\)</span> Statistic</h2>
<p>This will become more relevant in coming weeks, but we can also perform a test to investigate if the model is ‘useful’ — that is, a test to see if the explanatory variable is a useful predictor of the outcome.<br>
We test the following hypotheses:</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: \text{the model is ineffective, } b_1 = 0 \\
H_1 &amp;: \text{the model is effective, } b_1 \neq 0
\end{aligned}
\]</span></p>
<div class="sticky">
<p>The relevant test-statistic is the F-statistic:</p>
<p><span class="math display">\[
\begin{split}
F = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model} / 1}{SS_{Residual} / (n-2)}
\end{split}
\]</span></p>
<p>which compares the amount of variation in the response explained by the model to the amount of variation left unexplained in the residuals.</p>
<p>The sample F-statistic is compared to an F-distribution with <span class="math inline">\(df_{1} = 1\)</span> and <span class="math inline">\(df_{2} = n - 2\)</span> degrees of freedom.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="optional-begin">
<span id="opt-start-4" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-4', 'opt-start-4')"> <span class="olab">Optional: Another formula for the F-test.</span></span>
</div>
<div id="opt-body-4" class="optional-body" style="display: none;">
<p>With some algebra we can also show that:</p>
<p><span class="math display">\[
F = \frac{R^2 / 1}{(1 - R^2) / (n - 2) } = \frac{R^2 / df_{Model}}{(1 - R^2) / df_{Residual} }
\]</span></p>
<p>Proof:</p>
<p><span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)}
= \frac{\frac{SS_{Model}}{SS_{Total}}}{\frac{SS_{Residual}}{SS_{Total}} \cdot \frac{1}{(n - 2)}}
= \frac{R^2 / 1}{(1 - R^2) / (n - 2)}
\end{aligned}
\]</span></p>
</div>
<p class="optional-end">
</p>
</div>
<p>Like the <span class="math inline">\(R^2\)</span>, the <code>summary()</code> of our model prints out the <span class="math inline">\(F\)</span>-statistic, degrees of freedom, and p-value. These are right at the bottom of the summary output, printed as:</p>
<pre><code>F-statistic: 61.26 on 1 and 98 DF,  p-value: 5.918e-12</code></pre>
<div class="int">
<p>The F-test of model utility was significant (<span class="math inline">\(F(1,98) = 61.26,\ p &lt;.001\)</span>) suggesting that the model is effective in explaining variance in outcome <span class="math inline">\(y\)</span>.</p>
</div>
<p>Note that the p-value here is exactly the same as the one for the coefficient. This is because in testing “the model is (in)effective”, the “model” is really <em>only</em> the relationship between the outcome and our one predictor. When we move to adding more predictors into our model, we have more <span class="math inline">\(b\)</span>’s, and the <span class="math inline">\(F\)</span>-test will be testing jointly whether <span class="math inline">\(b_1 = b_2 =\ ...\ = b_k = 0\)</span>.</p>
<div class="optional-begin">
<span id="opt-start-5" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-5', 'opt-start-5')"> <span class="olab">Optional: When only one predictor variable, the F-test is equivalent to the t-test of the slope</span></span>
</div>
<div id="opt-body-5" class="optional-body" style="display: none;">
<p><strong>In simple linear regression only</strong> (where we have just <strong>one</strong> predictor), the F-statistic for overall model significance is equal to the square of the t-statistic for <span class="math inline">\(H_0: b_1 = 0\)</span>.</p>
<p>You can check that the squared t-statistic is equal, up to rounding error, to the F-statistic:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my_model)<span class="sc">$</span>fstatistic[<span class="st">'value'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   value 
61.26497 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my_model)<span class="sc">$</span>coefficients[<span class="st">'x'</span>,<span class="st">'t value'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.827194</code></pre>
</div>
</div>
<p><span class="math display">\[
t^2 = F \\
7.827194^2 = 61.26497
\]</span></p>
<p>Here we will show the equivalence of the F-test for model effectiveness and t-test for the slope.</p>
<p>Recall the formula of the sum of squares due to the model. We will rewrite it in an equivalent form below:</p>
<p><span class="math display">\[
\begin{aligned}
SS_{Model} &amp;= \sum_i (\hat y_i - \bar y)^2 \\
&amp;= \sum_i (\hat b_0 + \hat b_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\bar y - \hat b_1 \bar x + \hat b_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\hat b_1 (x_i - \bar x))^2 \\
&amp;= \hat b_1^2 \sum_i (x_i - \bar x)^2
\end{aligned}
\]</span></p>
<p>The F-statistic is given by:</p>
<p><span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)}
= \frac{\hat b_1^2 \sum_i (x_i - \bar x)^2}{\hat \sigma^2}
= \frac{\hat b_1^2 }{\hat \sigma^2 / \sum_i (x_i - \bar x)^2}
\end{aligned}
\]</span></p>
<p>Now recall the formula of the t-statistic,</p>
<p><span class="math display">\[
t = \frac{\hat b_1}{SE(\hat b_1)} = \frac{\hat b_1}{\hat \sigma / \sqrt{\sum_i (x_i - \bar x)^2}}
\]</span></p>
<p>It is evident that the latter is obtained as the square root of the former.</p>
</div>
<p class="optional-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section>
</section>
<section id="binary-predictors" class="level1">
<h1>Binary Predictors</h1>
<p>Let’s suppose that instead of having measured <span class="math inline">\(x\)</span> so accurately, we simply had information on whether <span class="math inline">\(x&gt;3\)</span> or not. Our predictor variable would be binary categorical (think back to our discussion of types of data in <a href="02a_measurement.html" target="_blank">2A: Measurement</a>) - it would have 2 levels:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  my_data <span class="sc">%&gt;%</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x_cat =</span> <span class="fu">ifelse</span>(x <span class="sc">&lt;</span> <span class="dv">3</span>, <span class="st">"level1"</span>,<span class="st">"level2"</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We may then plot our relationship as a boxplot. If you want to see the individual points, you could always “jitter” them (right-hand plot below)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_data, <span class="fu">aes</span>(<span class="at">x =</span> x_cat, <span class="at">y =</span> y)) <span class="sc">+</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_data, <span class="fu">aes</span>(<span class="at">x =</span> x_cat, <span class="at">y =</span> y)) <span class="sc">+</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">height=</span><span class="dv">0</span>, <span class="at">width=</span>.<span class="dv">05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="statbox">
<p><strong>Binary predictors in linear regression</strong></p>
<p>We can include categorical predictors in a linear regression, but the interpretation of the coefficients is very specific. Whereas we talked about coefficients being interpreted as “the change in <span class="math inline">\(y\)</span> associated with a 1-unit increase in <span class="math inline">\(x\)</span>”, for categorical explanatory variables, coefficients can be considered to examine differences in group means. However, they are actually doing exactly the same thing - the model is simply translating the levels (like “Level1”/“Level2”, or “Yes”/“No”, or “High”/“Low”) in to 0s and 1s!<br>
So while we may have in our dataframe a categorical predictor like the middle column “x_cat”, below, what is inputted into our model is more like the third column, “isLevel2”.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 3
       y x_cat  isLevel2
   &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
 1  5.90 level2        1
 2  4.82 level2        1
 3  5.70 level2        1
 4  4.81 level2        1
 5  2.42 level1        0
 6  3.82 level1        0
 7  3.88 level1        0
 8  5.57 level2        1
 9  6.25 level2        1
10  3.51 level2        1
# … with 90 more rows</code></pre>
</div>
</div>
<p>Our coefficients are just the same as before. The intercept is where our predictor equals zero, and the slope is the change in our outcome variable associated with a 1-unit change in our predictor.</p>
<p>However, “zero” for this predictor variable now corresponds to a whole level. This is known as the “reference level”. So the intercept is the estimated mean of <span class="math inline">\(y\)</span> when <code>x_cat == "level1"</code> (it will default to alphabetical, so “level1” will be treated as zero). Accordingly, the 1-unit change in our predictor (the move from “zero” to “one”) corresponds to the estimated change in mean of <span class="math inline">\(y\)</span> when moving from “level1” to “level2” (i.e.&nbsp;the difference between the two levels).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="assumptions" class="level1">
<h1>Assumptions</h1>
<p>All our work here is in aim of making <strong>models of the world</strong>.</p>
<ul>
<li>Models are models. They are simplifications. They are therefore wrong.<br>
</li>
<li>Our residuals ( <span class="math inline">\(y - \hat{y}\)</span> ) reflect everything that we <strong>don’t</strong> account for in our model.<br>
</li>
<li>In an ideal world, our model accounts for <em>all</em> the systematic relationships. The leftovers (our residuals) are just random noise.<br>
</li>
<li>If our model is mis-specified, or we don’t measure some systematic relationship, then our residuals will reflect this.<br>
We check by examining how much “like randomness” the residuals appear to be (zero mean, normally distributed, constant variance, i.i.d (“independent and identically distributed”). These ideas tend to get referred to as our <strong>“assumptions”.</strong><br>
</li>
<li>While we will <strong>never</strong> know whether our residuals contain only randomness (we can never observe everything), our ability to generalise from the model we fit on sample data to the wider population relies on these assumptions.</li>
</ul>
<div class="statbox">
<p><strong>Assumptions in a nutshell</strong></p>
<p>In using linear regression, we have assumptions about our model in that we assume that modelling the outcome variable as a <strong>linear</strong> combination of the explanatory variables is an appropriate thing to do.<br>
We also make certain assumptions about what we have <em>left out</em> of our model - the <strong>errors</strong> component.<br>
<!-- $$ --> <!-- \color{red}{y} = \color{blue}{\underbrace{\beta_0 \cdot{} 1 + \beta_1 \cdot{} x_1 + ... + \beta_k \cdot x_k}_{X \boldsymbol \beta}} + \varepsilon --> <!-- $$ --></p>
<p>Specifically, we assume that our errors have <strong>“zero mean and constant variance”</strong>.</p>
<ul>
<li>mean of the residuals = zero across the predicted values on the linear predictor.<br>
</li>
<li>spread of residuals is normally distributed and constant across the predicted values on the linear predictor.</li>
</ul>
<div class="optional-begin">
<span id="opt-start-6" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-6', 'opt-start-6')"> <span class="olab">What does it look like?</span></span>
</div>
<div id="opt-body-6" class="optional-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-7" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">What does it <b>not</b> look like?</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p>Things look a bit wrong (like there is something systematic that we haven’t accounted for), when our residuals do not have mean zero:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Or do not have constant variance:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</div>
<div class="rtip">
<p><strong>Assumptions in R</strong></p>
<p>We can get a lot of plots for this kind of thing by using <strong>plot(model)</strong></p>
<p>Here’s what it looks like for a nice neat model:</p>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(my_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Top Left: For the <strong>Residuals vs Fitted</strong> plot, we want the red line to be horizontal at close to zero across the plot. We don’t want the residuals (the points) to be fanning in/out.<br>
</li>
<li>Top Right: For the <strong>Normal Q-Q</strong> plot, we want the residuals (the points) to follow closely to the diagonal line, indicating that they are relatively normally distributed <em>(QQplots plot the values against the associated percentiles of the normal distribution. So if we had ten values, it would order them lowest to highest, then plot them on the y against the 10th, 20th, 30th.. and so on percentiles of the standard normal distribution (mean 0, SD 1))</em>.</li>
<li>Bottom Left: For the <strong>Scale-Location</strong> plot, we want the red line to be horizontal across the plot. These plots allow us to examine the extent to which the variance of the residuals changes accross the fitted values. If it is angled, we are likely to see fanning in/out of the points in the residuals vs fitted plot.</li>
<li>Bottom Right: The <strong>Residuals vs Leverage</strong> plot indicates points that might be of individual interest as they may be unduly influencing the model. There are funnel-shaped lines that will appear on this plot for messier data (not visible above as the data is too neat!), ideally, the further the residual is to the right, the closer to the 0 we want it to be. We’ll look at this in more depth in a future reading.</li>
</ul>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="example" class="level1">
<h1>Example</h1>
<div class="frame">
<blockquote class="blockquote">
<p><strong>Research Question:</strong> Is perceptual speed associated with age?</p>
</blockquote>
<p>The data for this example contains a sample of 130 participants all of whom are over the age of 65, with ages ranging from 67 to 88. All participants completed a short task measuring Perceptual Speed and Accuracy that scores from 0 to 50.</p>
<div class="cell" data-layout-align="center">

</div>
<p>The data are accessible at <a href="https://uoepsy.github.io/data/usmr_percept1.csv">https://uoepsy.github.io/data/usmr_percept1.csv</a>.</p>
</div>
<div class="panelset">
<section id="exploring" class="level4 panel">
<h4 class="anchored" data-anchor-id="exploring">Exploring</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>percdat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../../data/usmr_percept1.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Some visualisations:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>plt1 <span class="ot">&lt;-</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(percdat, <span class="fu">aes</span>(<span class="at">x =</span> percept)) <span class="sc">+</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">300</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>plt2 <span class="ot">&lt;-</span> </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(percdat, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span> </span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">80</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>plt3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(percdat, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> percept)) <span class="sc">+</span> </span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>(plt1 <span class="sc">+</span> plt2) <span class="sc">/</span> plt3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fitting" class="level4 panel">
<h4 class="anchored" data-anchor-id="fitting">Fitting</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>p_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(percept <span class="sc">~</span> age, <span class="at">data =</span> percdat)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = percept ~ age, data = percdat)

Residuals:
    Min      1Q  Median      3Q     Max 
-23.771  -7.665   1.076   6.857  25.619 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  77.2111    21.8240   3.538 0.000563 ***
age          -0.6951     0.2820  -2.465 0.015017 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.93 on 128 degrees of freedom
Multiple R-squared:  0.04533,   Adjusted R-squared:  0.03787 
F-statistic: 6.077 on 1 and 128 DF,  p-value: 0.01502</code></pre>
</div>
</div>
</section>
<section id="checking" class="level4 panel">
<h4 class="anchored" data-anchor-id="checking">Checking</h4>
<p>These plots don’t look too bad to me. The Residuals vs Fitted plot looks like a random cloud of points (which is good). The residuals look relatively normally distributed (see the QQ plot), and apart from at the lower end of the fitted values, the variance is fairly constant across (see the Scale-Location plot).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpreting" class="level4 panel">
<h4 class="anchored" data-anchor-id="interpreting">Interpreting</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(p_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
 77.2111245  -0.6951299 </code></pre>
</div>
</div>
<ul>
<li><code>(Intercept)</code>: For someone of age zero, the estimated average score on the Perceptual Speed task is 77.2<br>
</li>
<li><code>age</code>: For each additional year of age, the estimated average score on the task is -0.695 points lower.</li>
</ul>
<p>Note the intercept isn’t very useful here at all. It estimates the score for a newborn (who wouldn’t be able to complete the task anyway). Furthermore, it estimates a score of 77, when the task only scores up to 50. This is because these models are <em>linear</em>, so the lines just keep on going outside of the range.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p_model)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04532774</code></pre>
</div>
</div>
<ul>
<li>age explains approximately 4.5% of the variance in scores of the perceptual speed task.</li>
</ul>
</section>
<section id="visualising" class="level4 panel">
<h4 class="anchored" data-anchor-id="visualising">Visualising</h4>
<p>There are lots of ways to visualise models, and lots of packages that are designed to help us.<br>
One such useful package:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(p_model, </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">"eff"</span>,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">show.data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$age</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-8" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-8', 'opt-start-8')"> <span class="olab">Optional: If we want to do it manually</span></span>
</div>
<div id="opt-body-8" class="optional-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>percdat <span class="sc">%&gt;%</span> </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get the fitted values</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fit =</span> <span class="fu">predict</span>(p_model),</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get the SE at each level of fitted values</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="fu">predict</span>(p_model, <span class="at">se =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>se.fit,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># create confidence intervals</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># df = 128 because we have 130 observations</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">c.lwr =</span> fit <span class="sc">-</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="at">df =</span> <span class="dv">128</span>) <span class="sc">*</span> se,</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">c.upr =</span> fit <span class="sc">+</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="at">df =</span> <span class="dv">128</span>) <span class="sc">*</span> se</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot!</span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> percept))<span class="sc">+</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> c.lwr, <span class="at">ymax =</span> c.upr), <span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section>
<section id="tabulating" class="level4 panel">
<h4 class="anchored" data-anchor-id="tabulating">Tabulating</h4>
<p>The same package (<strong>sjPlot</strong>) provides some nice quick ways to create regression tables (a bit like what we get from <code>summary(model)</code>, only presented a lot more nicely!)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(p_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">percept</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">77.21</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">34.03&nbsp;–&nbsp;120.39</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">age</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.70</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.25&nbsp;–&nbsp;-0.14</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>0.015</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">130</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.045 / 0.038</td>
</tr>

</tbody></table>

</div>
</div>
</section>
<section id="writing-up" class="level4 panel">
<h4 class="anchored" data-anchor-id="writing-up">Writing up</h4>
<p>A total of 130 participants were included in the analysis, with ages ranging from 67 to 88 (Mean = 77.3, sd = 3.4). On average, participants scored 23.5 (SD = 11.1) on the perceptual speed task.</p>
<p>A simple linear regression model was fitted, with scores on the perceptual speed task regressed on to age. A significant association was found, with scores on the task increasing by -0.7 with every year of age (<span class="math inline">\(b = -0.695\)</span>, <span class="math inline">\(SE = 0.28\)</span>, <span class="math inline">\(t(128)=-2.47\)</span>, <span class="math inline">\(p = 0.015\)</span>), suggesting that perception may get worse in older age.</p>
</section>
</div>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>Recall that a standard error gives a numerical answer to the question of how variable a statistic will be because of random sampling.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>Why <span class="math inline">\(n-2\)</span>? The most intuitive answer is that we have already used up 2 pieces of information in estimating the intercept and the slope. Once these things are fixed, <span class="math inline">\(n-2\)</span> of the datapoints could be wherever they like around that line, but the remaining 2 must be placed in such a way that results in that line<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p> <span class="math inline">\(SS_{Total}\)</span> has <span class="math inline">\(n - 1\)</span> degrees of freedom as one degree of freedom is lost in estimating the population mean with the sample mean <span class="math inline">\(\bar{y}\)</span>. <span class="math inline">\(SS_{Residual}\)</span> has <span class="math inline">\(n - 2\)</span> degrees of freedom. There are <span class="math inline">\(n\)</span> residuals, but two degrees of freedom are lost in estimating the intercept and slope of the line used to obtain the <span class="math inline">\(\hat y_i\)</span>s. Hence, by difference, <span class="math inline">\(SS_{Model}\)</span> has <span class="math inline">\(n - 1 - (n - 2) = 1\)</span> degree of freedom.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>