<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - Week 8 Exercises: Multiple Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-down')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 1</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html">
 <span class="dropdown-text">1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html">
 <span class="dropdown-text">1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 2</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html">
 <span class="dropdown-text">2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html">
 <span class="dropdown-text">2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 3</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html">
 <span class="dropdown-text">3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html">
 <span class="dropdown-text">3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html">
 <span class="dropdown-text">Exercises: T-tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 4</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04a_chisq.html">
 <span class="dropdown-text">4A: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revisitnhst.html">
 <span class="dropdown-text">4B: Revisiting NHST</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_ex.html">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 5</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li class="dropdown-header">5A: Covariance &amp; Correlation</li>
        <li class="dropdown-header">Exercises: Cov, Cor, Models</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-6" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 6</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-6">    
        <li class="dropdown-header">Walkthrough: Advanced Data Wrangling</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 7</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li class="dropdown-header">7A: Simple Linear Regression</li>
        <li class="dropdown-header">Exercises: Simple Linear Regression</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 8</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li class="dropdown-header">8A: Multiple Linear Regression</li>
        <li class="dropdown-header">8B: Assumptions, Diagnostics, and Troubleshooting</li>
        <li class="dropdown-header">Exercises: Multiple Linear Regression</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 9</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li class="dropdown-header">9A: Interactions</li>
        <li class="dropdown-header">9B: Categorical Predictors</li>
        <li class="dropdown-header">Exercises: Interactions</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-10" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 10</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-10">    
        <li class="dropdown-header">10A: GLM!</li>
        <li class="dropdown-header">Exercises: Logistic Regression</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-11" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 11</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-11">    
        <li class="dropdown-header">11A: Common Tests as Linear Models</li>
        <li class="dropdown-header">11B: Writing Up</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#wellbeing-and-outdoor-time" id="toc-wellbeing-and-outdoor-time" class="nav-link active" data-scroll-target="#wellbeing-and-outdoor-time">Wellbeing and Outdoor Time</a></li>
  <li><a href="#rmd" id="toc-rmd" class="nav-link" data-scroll-target="#rmd">Rmd</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 8 Exercises: Multiple Regression</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="wellbeing-and-outdoor-time" class="level1">
<h1>Wellbeing and Outdoor Time</h1>
<div class="frame">
<blockquote class="blockquote">
<p><strong>Research Question:</strong> <em>after</em> taking into account differences due to people’s level of social interactions, to what extent is well-being associated with the time people spend outdoors?</p>
</blockquote>
<p><strong>Data: wellbeing.csv</strong></p>
<p>Researchers interviewed 32 participants, selected at random from the population of residents of Edinburgh &amp; Lothians. They used the Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br>
The researchers also asked participants to estimate the average number of hours they spend outdoors each week, the average number of social interactions they have each week (whether on-line or in-person), and whether they believe that they stick to a routine throughout the week (Yes/No).</p>
<p>The dataset is available at <a href="https://uoepsy.github.io/data/wellbeing.csv" target="_blank">https://uoepsy.github.io/data/wellbeing.csv</a> and contains five attributes:</p>
<ul>
<li><code>wellbeing</code>: Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br>
</li>
<li><code>outdoor_time</code>: Self report estimated number of hours per week spent outdoors<br>
</li>
<li><code>social_int</code>: Self report estimated number of social interactions per week (both online and in-person)</li>
<li><code>routine</code>: Binary Yes/No response to the question “Do you follow a daily routine throughout the week?”</li>
<li><code>location</code>: Location of primary residence (City, Suburb, Rural)</li>
</ul>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Read in the data, and explore and describe the variables and relationships that are relevant to the research question.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<p>You might want to:</p>
<ul>
<li>plot the <em>marginal distributions</em> (the distributions of each variable in the analysis without reference to the other variables)</li>
<li>plot the <em>marginal relationships</em> between the outcome variable and each of the explanatory variables.<br>
</li>
<li>make a quick correlation matrix of the variables which are to be used in the analysis, and write a short paragraph describing the relationships.
<ul>
<li>e.g.&nbsp;<code>cor(data[,c(1:4)])</code> will give us a matrix of correlations between each pair of the first 4 variables in the data</li>
</ul></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div style="display:none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co">#used to arrange plots</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>mwdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/wellbeing.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>wellbeing_plot <span class="ot">&lt;-</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">250</span>) <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Score on WEMWBS (range 14-70)"</span>, <span class="at">y =</span> <span class="st">"Probability</span><span class="sc">\n</span><span class="st">density"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>outdoortime_plot <span class="ot">&lt;-</span> </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> outdoor_time)) <span class="sc">+</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">200</span>) <span class="sc">+</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time spent outdoors per week (hours)"</span>, <span class="at">y =</span> <span class="st">"Probability</span><span class="sc">\n</span><span class="st">density"</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>social_plot <span class="ot">&lt;-</span> </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> social_int)) <span class="sc">+</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">150</span>) <span class="sc">+</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of social interactions per week"</span>, <span class="at">y =</span> <span class="st">"Probability</span><span class="sc">\n</span><span class="st">density"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>wellbeing_plot <span class="sc">/</span> outdoortime_plot <span class="sc">/</span> social_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-marg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08_ex_files/figure-html/fig-marg-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 1: Marginal distribution plots of wellbeing sores, weekly hours spent outdoors, and social interactions</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="int">
<ul>
<li>The marginal distribution of scores on the WEMWBS is unimodal with a mean of approximately 43. There is variation in scores (SD = 11.7).<br>
</li>
<li>The marginal distribution of weekly hours spend outdoors is unimodal with a mean of approximately 14.8 hours. There is variation in outdoor time (SD = 6.9 hours).<br>
</li>
<li>The marginal distribution of numbers of social interactions per week is unimodal with a mean of approximately 16. There is variation in in numbers of social interactions per week (SD = 4.4).</li>
</ul>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>wellbeing_outdoor <span class="ot">&lt;-</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> outdoor_time, <span class="at">y =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time spent outdoors per week (hours)"</span>, <span class="at">y =</span> <span class="st">"Wellbeing score (WEMWBS)"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>wellbeing_social <span class="ot">&lt;-</span> </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> social_int, <span class="at">y =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of social interactions per week"</span>, <span class="at">y =</span> <span class="st">"Wellbeing score (WEMWBS)"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>wellbeing_outdoor <span class="sc">|</span> wellbeing_social</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mwdata-mlr-rels" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08_ex_files/figure-html/fig-mwdata-mlr-rels-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 2: Scatterplots displaying the relationships between scores on the WEMWBS and a) weekly outdoor time (hours), and b) weekly number of social interactions</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We can either use:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correlation matrix of the first 3 columns</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(mwdata[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>or:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select only the columns we want by name, and pass this to cor()</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>mwdata <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(wellbeing, outdoor_time, social_int) <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             wellbeing outdoor_time social_int
wellbeing    1.0000000    0.5815613  0.7939003
outdoor_time 0.5815613    1.0000000  0.3394469
social_int   0.7939003    0.3394469  1.0000000</code></pre>
</div>
</div>
<div class="int">
<p>There is a moderate, positive, linear relationship between weekly outdoor time and WEMWBS scores for the participants in the sample. Participants’ wellbeing scores tend to increase, on average, with the number of hours spent outdoors each week.<br>
There is a moderate, positive, linear relationship between the weekly number of social interactions and WEMWBS scores for the participants in the sample. Participants’ wellbeing scores tend to increase, on average, with the weekly number of social interactions. There is also a weak positive correlation between weekly outdoor time and the weekly number of social interactions.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Fit a regression model that you can use to answer the research question (make sure to give it a name to store it in your environment).</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<p><span class="math inline">\(Wellbeing = b_0 \ + \ b_1 \cdot Social Interactions \ + \ b_2 \cdot Outdoor Time \ + \ \epsilon\)</span></p>
</div>
</div>
<p class="question-end">
</p>
<div style="display:none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>wbmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int <span class="sc">+</span> outdoor_time, <span class="at">data =</span> mwdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Extract <em>and interpret</em> the parameter estimates (the coefficients) from your model.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>There’s a comprehensive section on how we interpret multiple regression coefficients in <a href="08a_mlr.html#multiple-regression-coefficients" target="_blank">8A#multiple-regression-coefficients</a></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div style="display:none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ 1 + social_int + outdoor_time, data = mwdata)

Residuals:
   Min     1Q Median     3Q    Max 
-9.742 -4.915 -1.255  5.628 10.936 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    5.3704     4.3205   1.243   0.2238    
social_int     1.8034     0.2691   6.702 2.37e-07 ***
outdoor_time   0.5924     0.1689   3.506   0.0015 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.148 on 29 degrees of freedom
Multiple R-squared:  0.7404,    Adjusted R-squared:  0.7224 
F-statistic: 41.34 on 2 and 29 DF,  p-value: 3.226e-09</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\hat \beta_0\)</span> = 5.37, the estimated average wellbeing score associated with zero hours of outdoor time and zero social interactions per week.<br>
</li>
<li><span class="math inline">\(\hat \beta_1\)</span> = 1.8, the estimated increase in average wellbeing score associated with an additional social interaction per week (an increase of one), <em>holding weekly outdoor time constant</em> (i.e., when the remaining explanatory variables are held at the same value or are fixed).</li>
<li><span class="math inline">\(\hat \beta_2\)</span> = 0.59, the estimated increase in average wellbeing score associated with one hour increase in weekly outdoor time, <em>holding the number of social interactions constant</em>.</li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Along with the p-values given by <code>summary()</code> that test the null hypothesis that each coefficient is equal to zero, we can obtain confidence intervals for our estimates to provide a range of plausible values for each coefficient. This may be useful if we want to focus more on the estimated value, rather than “is it zero or not?”.</p>
<p>Look up the function <code>confint()</code> and use it to obtain some 95% Confidence Intervals for the coefficients.</p>
</div>
<p class="question-end">
</p>
<div style="display:none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(wbmodel, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %     97.5 %
(Intercept)  -3.4660660 14.2068209
social_int    1.2530813  2.3538164
outdoor_time  0.2468371  0.9378975</code></pre>
</div>
</div>
<div class="int">
<ul>
<li>The average wellbeing score for all those with zero hours of outdoor time and zero social interactions per week is between -3.47 and 14.21.<br>
</li>
<li>When <em>holding weekly outdoor time constant</em>, each increase of one social interaction per week is associated with a difference in wellbeing scores between 1.25 and 2.35, on average.<br>
</li>
<li>When <em>holding the number of social interactions per week constant</em>, each one hour increase in weekly outdoor time is associated with a difference in wellbeing scores between 0.25 and 0.94, on average.</li>
</ul>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Does your model provide a better fit to the data than a model with no explanatory variables? (i.e., test against the alternative hypothesis that at least one of the explanatory variables significantly predicts wellbeing scores).</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>it’s all in the <code>summary()</code>!!</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div style="display:none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ 1 + social_int + outdoor_time, data = mwdata)

Residuals:
   Min     1Q Median     3Q    Max 
-9.742 -4.915 -1.255  5.628 10.936 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    5.3704     4.3205   1.243   0.2238    
social_int     1.8034     0.2691   6.702 2.37e-07 ***
outdoor_time   0.5924     0.1689   3.506   0.0015 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.148 on 29 degrees of freedom
Multiple R-squared:  0.7404,    Adjusted R-squared:  0.7224 
F-statistic: 41.34 on 2 and 29 DF,  p-value: 3.226e-09</code></pre>
</div>
</div>
<div class="int">
<div class="cell" data-layout-align="center">

</div>
<p>Weekly social interactions and outdoor time explained 72.2% of the variance (adjusted <span class="math inline">\(R^2\)</span> =0.722, <span class="math inline">\(F\)</span>(2,29)=41.3, p&lt;.001)</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Just to prove it to ourselves, conduct a model comparison between your model and the “null model”, and check that the <span class="math inline">\(F\)</span>-statistic from the <code>summary()</code> of your model matches that from the comparison.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>we talked about the ‘null model’, and conducting model comparison in <a href="08a_mlr.html#model-comparisons" target="_blank">8A#model-comparisons</a>.<br>
</li>
<li>we can fit a model with no predictors such as <code>lm(wellbeing ~ 1, data = mwdata)</code>.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div style="display:none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>nullmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mwdata)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(nullmodel, wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: wellbeing ~ 1
Model 2: wellbeing ~ 1 + social_int + outdoor_time
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     31 4222.0                                  
2     29 1096.2  2    3125.8 41.345 3.226e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Matches that seen in the bottom of <code>summary(wbmodel)</code>:</p>
<pre><code>F-statistic: 41.34 on 2 and 29 DF,  p-value: 3.226e-09</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Check the assumptions of your model.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>See <a href="08b_assumptdiag.html" target="_blank">8B#assumptions</a><br>
</li>
<li>You don’t necessarily have to perform statistical tests of assumptions, but check the plots at the very least!</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div style="display:none;">
<p>We only have <span class="math inline">\(n=32\)</span> observations here, so our plots might look a bit wobbly. I might perform some quick tests to reassure myself we’re okay.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_ex_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(wbmodel))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(wbmodel)
W = 0.94831, p-value = 0.129</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ncvTest</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.001925809, Df = 1, p = 0.965</code></pre>
</div>
</div>
<p>We seem to be okay!</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Check for influential observations.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li><a href="08b_assumptdiag.html#individual-case-diagnostics" target="_blank">8B#individual-case-diagnostics</a> covers a whole load of different metrics you might use. As a starting point, perhaps consider Cook’s Distances plots, or use <code>influence.measures()</code> to get lots of info.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div style="display:none;">
<p>Here are the Cook’s Distance values:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wbmodel, <span class="at">which =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_ex_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>We can see that one observation (labelled 27) is a little bit higher than the rest. It’s not hugely out of keeping with the others, so I might not be too worried.</p>
<p>It’s not flagged by <code>influence.measures()</code>, but another observation is flagged, this time on the covratio metric (influence on the standard errors).<br>
With only <span class="math inline">\(32\)</span> observations, excluding datapoints comes with a big reduction in statistical power. On balance I might report this influential point in the write up, but keep it in the analysis. This decision is also based on the distribution of covratio values - it doesn’t look like one value is really that much higher than the others (it is simply above the internal cutoff that <code>influence.measures()</code> uses).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">influence.measures</span>(wbmodel))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Potentially influential observations of
     lm(formula = wellbeing ~ 1 + social_int + outdoor_time, data = mwdata) :

   dfb.1_ dfb.scl_ dfb.otd_ dffit cov.r   cook.d hat  
32  0.10  -0.08    -0.07    -0.14  1.35_*  0.01   0.19</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">covratio</span>(wbmodel), <span class="at">breaks=</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_ex_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Create a visualisation of the relationship between wellbeing and outdoor time, after accounting for social interactions.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>There’s an example of visualising multiple regression coefficients in <a href="08a_mlr.html#multiple-regression-coefficients" target="_blank">8A#multiple-regression-coefficients</a>.<br>
</li>
<li>to visualise just one association, you might need the <code>terms</code> argument in <code>plot_model()</code>. Don’t forget you can look up the documentation by typing <code>?plot_model</code> in the console.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div style="display:none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(wbmodel, <span class="at">type =</span> <span class="st">"eff"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"outdoor_time"</span>), </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">show.data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_ex_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Create a regression table to present your results</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>There is a useful function called <code>tab_model()</code>, also from the <strong>sjPlot</strong> package. You can see it used in <a href="07a_slr.html#example" target="_blank">7A#example</a>.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div style="display:none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">wellbeing</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">5.37</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-3.47&nbsp;–&nbsp;14.21</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.224</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">social int</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">1.80</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">1.25&nbsp;–&nbsp;2.35</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">outdoor time</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.59</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.25&nbsp;–&nbsp;0.94</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">32</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.740 / 0.722</td>
</tr>

</tbody></table>

</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="rmd" class="level1">
<h1>Rmd</h1>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Let’s put this all together.</p>
<p>Create an rmarkdown file that:</p>
<ol type="1">
<li>Reads in data and fits the model</li>
<li>Describes the research question and the analytical method used to address it</li>
<li>Presents and interprets the results</li>
</ol>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>You’ve actually done all of this already in the earlier questions, it’s just a matter of shoving it in the .Rmd file and tidying it up.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>