<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - Week 9 Exercises: Interactions and Categorical Predictors</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-down')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 1</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html">
 <span class="dropdown-text">1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html">
 <span class="dropdown-text">1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 2</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html">
 <span class="dropdown-text">2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html">
 <span class="dropdown-text">2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 3</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html">
 <span class="dropdown-text">3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html">
 <span class="dropdown-text">3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html">
 <span class="dropdown-text">Exercises: T-tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 4</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04a_chisq.html">
 <span class="dropdown-text">4A: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revisitnhst.html">
 <span class="dropdown-text">4B: Revisiting NHST</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_ex.html">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 5</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li>
    <a class="dropdown-item" href="./05a_covcor.html">
 <span class="dropdown-text">5A: Covariance &amp; Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_ex.html">
 <span class="dropdown-text">Exercises: Cov, Cor, Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-6" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 6</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-6">    
        <li>
    <a class="dropdown-item" href="./06_wt.html">
 <span class="dropdown-text">Walkthrough: Advanced Data Wrangling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 7</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li>
    <a class="dropdown-item" href="./07a_slr.html">
 <span class="dropdown-text">7A: Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_ex.html">
 <span class="dropdown-text">Exercises: Simple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 8</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li>
    <a class="dropdown-item" href="./08a_mlr.html">
 <span class="dropdown-text">8A: Multiple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08b_assumptdiag.html">
 <span class="dropdown-text">8B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08_ex.html">
 <span class="dropdown-text">Exercises: Multiple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 9</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li>
    <a class="dropdown-item" href="./09a_interactions.html">
 <span class="dropdown-text">9A: Interactions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09b_contrasts.html">
 <span class="dropdown-text">9B: Categorical Predictors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09_ex.html">
 <span class="dropdown-text">Exercises: Interactions</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-10" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 10</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-10">    
        <li>
    <a class="dropdown-item" href="./10a_glm.html">
 <span class="dropdown-text">10A: GLM!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10_ex.html">
 <span class="dropdown-text">Exercises: Logistic Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-11" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 11</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-11">    
        <li>
    <a class="dropdown-item" href="./11_ex.html">
 <span class="dropdown-text">Exercises: Tying up Loose Ends</span></a>
  </li>  
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#aging-cognition" id="toc-aging-cognition" class="nav-link active" data-scroll-target="#aging-cognition">Aging Cognition</a></li>
  <li><a href="#personality-and-social-rank" id="toc-personality-and-social-rank" class="nav-link" data-scroll-target="#personality-and-social-rank">Personality and Social Rank</a></li>
  <li><a href="#seasonal-extraversion" id="toc-seasonal-extraversion" class="nav-link" data-scroll-target="#seasonal-extraversion">Seasonal Extraversion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 9 Exercises: Interactions and Categorical Predictors</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="aging-cognition" class="level1">
<h1>Aging Cognition</h1>
<div class="frame">
<p><strong>Data: cogapoe4.csv</strong></p>
<p>Ninety adult participants were recruited for a study investigating how cognitive functioning varies by age, and whether this is different depending on whether people carry an APOE-4 gene.</p>
<blockquote class="blockquote">
<p><strong>Research Question:</strong> Does the relationship between age and cognitive functioning differ between those with and without the APOE-4 genotype?</p>
</blockquote>
<p>The data are available at <a href="https://uoepsy.github.io/data/cogapoe4.csv">https://uoepsy.github.io/data/cogapoe4.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> variables </th>
   <th style="text-align:left;"> description </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> pid </td>
   <td style="text-align:left;"> Participant ID </td>
  </tr>
  <tr>
   <td style="text-align:left;"> age </td>
   <td style="text-align:left;"> Age (in Years) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> educ </td>
   <td style="text-align:left;"> Years of Education </td>
  </tr>
  <tr>
   <td style="text-align:left;"> birthweight_kg </td>
   <td style="text-align:left;"> Birthweight (in Kg) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> apoe4 </td>
   <td style="text-align:left;"> APOE-4 Gene expansion ('none', 'apoe4a', 'apoe4b', apoe4c') </td>
  </tr>
  <tr>
   <td style="text-align:left;"> acer </td>
   <td style="text-align:left;"> Score on Addenbrooke's Cognitive Examination </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<blockquote class="blockquote">
<p>Does the relationship between age and cognitive functioning differ between those with and without the APOE-4 genotype?</p>
</blockquote>
<p>Read in the data and explore the variables which you think you will use to answer the research question above (create some plots, some descriptive stats etc.)</p>
<div class="hints">
<p><strong>handy functions:</strong></p>
<ul>
<li>The <code>pairs.panels()</code> function from the <strong>psych</strong> package is quite a nice way to plot a scatterplot matrix of a dataset.<br>
</li>
<li>The <code>describe()</code> function is also quite nice (from the <strong>psych</strong> package too).</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-1" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')"> Solution </span>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>cogapoe <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/cogapoe4.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cogapoe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     pid                 age              educ       birthweight_kg  
 Length:90          Min.   : 45.00   Min.   :15.00   Min.   : 0.500  
 Class :character   1st Qu.: 57.25   1st Qu.:17.00   1st Qu.: 5.225  
 Mode  :character   Median : 67.00   Median :19.00   Median : 6.550  
                    Mean   : 70.53   Mean   :19.31   Mean   : 6.546  
                    3rd Qu.: 86.75   3rd Qu.:22.00   3rd Qu.: 8.150  
                    Max.   :100.00   Max.   :24.00   Max.   :11.500  
    apoe4                acer       
 Length:90          Min.   : 70.42  
 Class :character   1st Qu.: 78.52  
 Mode  :character   Median : 85.02  
                    Mean   : 86.53  
                    3rd Qu.: 95.36  
                    Max.   :100.00  </code></pre>
</div>
</div>
<p>Judging by the research question, we’re going to be interested in participants’ ages, whether they carry the APOE4 gene, and their cognitive functioning.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>cogapoe <span class="sc">%&gt;%</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, apoe4, acer) <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs.panels</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_ex_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cogapoe <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, apoe4, acer) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">describe</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       vars  n  mean    sd median trimmed   mad   min max range  skew kurtosis
age       1 90 70.53 16.28  67.00   70.28 19.27 45.00 100 55.00  0.21    -1.30
apoe4*    2 90  2.76  1.13   3.00    2.82  1.48  1.00   4  3.00 -0.25    -1.40
acer      3 90 86.53  9.39  85.02   86.63 13.11 70.42 100 29.58 -0.01    -1.34
         se
age    1.72
apoe4* 0.12
acer   0.99</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Check the <code>apoe4</code> variable. It currently has four levels (“none”/“apoe4a”/“apoe4b”/“apoe4c”), but the research question is actually interested in two (“none” vs “apoe4”).</p>
<p>Make a new variable that indicates whether or not someone has the APOE4 genotype.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>One way to do this would be to use <code>ifelse()</code> to define a variable which takes one value (e.g., “NO”) if the observation meets from some condition, or another value (e.g., “YES”) if it does not. You can use it to add a new variable either inside <code>mutate()</code>, or using <code>data$new_variable_name &lt;- ifelse(test, x, y)</code> syntax.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<p>Create a new variable for APOE4 Yes or No</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cogapoe <span class="ot">&lt;-</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  cogapoe <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">isAPOE4 =</span> <span class="fu">ifelse</span>(apoe4 <span class="sc">==</span> <span class="st">"none"</span>, <span class="st">"No"</span>, <span class="st">"Yes"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<blockquote class="blockquote">
<p>Does the relationship between age and cognitive functioning differ between those with and without the APOE-4 genotype?</p>
</blockquote>
<p>To answer this question, do you need an interaction? If so, between what kind of variables (continuous x continuous, continuous x categorical, or categorical x categorical)?</p>
<div class="hints">
<p><strong>Hint:</strong></p>
<ul>
<li>See <a href="09a_interactions.html#it-depends" target="_blank">9A#it-depends</a></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>Does the relationship between [continuous predictor] and [outcome] differ between [categorical predictor]?</p>
<p>It’s continuous x categorical!</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Especially for this type of interactions, we can start to get a sense of things by plotting the data and having a separate <em>facet</em> for each group.</p>
<p>Produce a visualisation of the relationship between age and cognitive functioning, with separate <em>facets</em> for people with and without the APOE4 gene.</p>
<div class="hints">
<p><strong>Hint:</strong></p>
<ul>
<li>remember <code>facet_wrap()</code>?</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> cogapoe, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> acer)) <span class="sc">+</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>isAPOE4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_ex_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<blockquote class="blockquote">
<p>Does the relationship between age and cognitive functioning differ between those with and without the APOE-4 genotype?</p>
</blockquote>
<p>Fit a model to answer this research question.</p>
<div class="hints">
<p><strong>Hint:</strong></p>
<ul>
<li>for how to fit interactions, see <a href="09a_interactions.html#fitting-interactions-in-r" target="_blank">9A#fitting-interactions-in-r</a></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>apoe4mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(acer <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> age <span class="sc">*</span> isAPOE4, <span class="at">data =</span> cogapoe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Looking at the coefficient estimates from your model, write a description of what each one corresponds to on the plot shown in <a href="#fig-plotannotateint">Figure&nbsp;1</a> (it may help to sketch out the plot yourself and annotate it).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plotannotateint" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09_ex_files/figure-html/fig-plotannotateint-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 1: Multiple regression model: ACER ~ Age * isAPOE4<br>The dotted lines show the extension back to where the x-axis is zero</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="hints">
<p><strong>Some options for you to choose from:</strong></p>
<ul>
<li>The point at which the blue line cuts the y-axis (where age = 0)</li>
<li>The point at which the red line cuts the y-axis (where age = 0)</li>
<li>The average vertical distance between the red and blue lines.</li>
<li>The vertical distance from the blue to the red line <em>at the y-axis</em> (where age = 0)</li>
<li>The vertical distance from the red to the blue line <em>at the y-axis</em> (where age = 0)</li>
<li>The vertical distance from the blue to the red line <em>at the center of the plot</em></li>
<li>The vertical distance from the red to the blue line <em>at the center of the plot</em></li>
<li>The slope (vertical increase on the y-axis associated with a 1 unit increase on the x-axis) of the blue line</li>
<li>The slope of the red line</li>
<li>The adjustment to the slope when you move from the blue to the red line</li>
<li>The adjustment to the slope when you move from the red to the blue line</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<p>As always, we can obtain our coefficient estimates using various functions such as <code>summary(apoe4mod)</code>,<code>coef(apoe4mod)</code>, <code>coefficients(apoe4mod)</code> etc.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(apoe4mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept)            age     isAPOE4Yes age:isAPOE4Yes 
  104.09765349    -0.09796756    -4.37223106    -0.17966769 </code></pre>
</div>
</div>
<ul>
<li><code>(Intercept)</code> = 104.1: The point at which the red line cuts the y-axis (where age = 0).<br>
</li>
<li><code>age</code> = -0.1: The slope (vertical change on the y-axis associated with a 1 unit change on the x-axis) of the red line.</li>
<li><code>isAPOE4Yes</code> = -4.37: The vertical distance from the red to the blue line <em>at the y-axis</em> (where age = 0).<br>
</li>
<li><code>age:isAPOE4Yes</code> = -0.18: How the slope of the line changes when you move from the red to the blue line.</li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Produce a visualisation of the estimated interaction.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>e.g.&nbsp;plot your model!</li>
<li>see <a href="09a_interactions.html#visualisation" target="_blank">9A#visualisation</a></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>If we use <strong>sjPlot</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(apoe4mod, <span class="at">type=</span><span class="st">"int"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_ex_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Or <strong>interactions</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(apoe4mod, <span class="at">pred =</span> <span class="st">"age"</span>, <span class="at">modx=</span><span class="st">"isAPOE4"</span>, <span class="at">interval =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_ex_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Write a short paragraph explaining the pattern of results, including coefficient estimates as appropriate.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(apoe4mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = acer ~ 1 + age * isAPOE4, data = cogapoe)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.8923 -2.1408 -0.0917  2.0802  9.1208 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    104.09765    2.72786  38.161  &lt; 2e-16 ***
age             -0.09797    0.03689  -2.655  0.00944 ** 
isAPOE4Yes      -4.37223    3.20121  -1.366  0.17556    
age:isAPOE4Yes  -0.17967    0.04372  -4.110 9.01e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.025 on 86 degrees of freedom
Multiple R-squared:  0.8996,    Adjusted R-squared:  0.8961 
F-statistic:   257 on 3 and 86 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>For those without the APOE4 gene, the estimated average score on the ACER was found to decrease by 0.1 points with every year of age (<span class="math inline">\(\beta = -0.1\)</span>, <span class="math inline">\(t(86) = -2.66\)</span>, <span class="math inline">\(p &lt;0.05\)</span>). A significant interaction between age and APOE4 status indicates that those <em>with</em> the APOE4 gene have an decline by 0.18 more for every year of age than those without the gene (<span class="math inline">\(\beta = -0.18\)</span>, <span class="math inline">\(t(86) = -4.11\)</span>, <span class="math inline">\(p &lt;0.05\)</span>). This is visualised in <a href="#fig-intplotwrite">Figure&nbsp;2</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-intplotwrite" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09_ex_files/figure-html/fig-intplotwrite-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 2: Decreases in cognition depend upon APOE4 genotype</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>It’s important to emphasise that models are structures that <em>we</em> design, then estimate from our data, and assess how well they fit.</p>
<p>Here are three models:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>cogapoe<span class="sc">$</span>isAPOE4 <span class="ot">=</span> <span class="fu">ifelse</span>(cogapoe<span class="sc">$</span>apoe4 <span class="sc">==</span> <span class="st">"none"</span>, <span class="st">"No"</span>, <span class="st">"Yes"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>apoe4mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(acer <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> age, <span class="at">data =</span> cogapoe)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>apoe4mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(acer <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> age <span class="sc">+</span> isAPOE4, <span class="at">data =</span> cogapoe)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>apoe4mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(acer <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> age <span class="sc">+</span> isAPOE4 <span class="sc">+</span> age<span class="sc">:</span>isAPOE4, <span class="at">data =</span> cogapoe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And below are those three models plotted, with the data added.<br>
Which model corresponds to which plot?</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_ex_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<p>The top left shows <em>non-parallel</em> lines. It’s an interaction! This is the model <code>acer ~ 1 + age + isAPOE4 + age:isAPOE4</code>.</p>
<p>The top right shows no estimated differences in ACER scores between APOE4 positive and negative. This is probably the model <code>acer ~ 1 + age</code>, where APOE4 isn’t in the model at all.</p>
<p>The bottom shows two parallel lines. They differ in height, so there <em>is</em> an estimated association between APOE4 and ACER scores. The lines being parallel means this will be the one <em>without</em> an interaction <code>acer ~ 1 + age + isAPOE4</code>.</p>
<div class="imp">
<p>If you fit a model with an interaction in it, you don’t always get non-parallel lines. If the interaction coefficient is 0 (and so non-significant), then the model would look like two parallel lines.</p>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="personality-and-social-rank" class="level1">
<h1>Personality and Social Rank</h1>
<div class="frame">
<p><strong>Data: scs_study.csv</strong></p>
<p>Data from 656 participants containing information on scores on each trait of a Big 5 personality measure, their perception of their own social rank, and their scores on a measure of depression. Previous research has identified an association between an individual’s perception of their social rank and symptoms of depression, anxiety and stress. We are interested in the individual differences in this relationship.</p>
<blockquote class="blockquote">
<p><strong>Research Question:</strong> After accounting for other personality traits, does the effect of social comparison on symptoms of depression, anxiety and stress vary depending on level of neuroticism?</p>
</blockquote>
<p>The data is available at <a href="https://uoepsy.github.io/data/scs_study.csv">https://uoepsy.github.io/data/scs_study.csv</a>.</p>
<p>The data in <code>scs_study.csv</code> contain seven attributes collected from a random sample of <span class="math inline">\(n=656\)</span> participants:</p>
<ul>
<li><code>zo</code>: Openness (Z-scored), measured on the Big-5 Aspects Scale (BFAS)</li>
<li><code>zc</code>: Conscientiousness (Z-scored), measured on the Big-5 Aspects Scale (BFAS)</li>
<li><code>ze</code>: Extraversion (Z-scored), measured on the Big-5 Aspects Scale (BFAS)</li>
<li><code>za</code>: Agreeableness (Z-scored), measured on the Big-5 Aspects Scale (BFAS)</li>
<li><code>zn</code>: Neuroticism (Z-scored), measured on the Big-5 Aspects Scale (BFAS)</li>
<li><code>scs</code>: Social Comparison Scale - An 11-item scale that measures an individual’s perception of their social rank, attractiveness and belonging relative to others. The scale is scored as a sum of the 11 items (each measured on a 5-point scale), with higher scores indicating more favourable perceptions of social rank. Scores range from 11 to 55.<br>
</li>
<li><code>dass</code>: Depression Anxiety and Stress Scale - The DASS-21 includes 21 items, each measured on a 4-point scale. The score is derived from the sum of all 21 items, with higher scores indicating higher a severity of symptoms. Scores range from 21 to 84.</li>
</ul>
<div class="optional-begin">
<span id="opt-start-10" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-10', 'opt-start-10')"> <span class="olab">What does ‘Z-scored’ mean?</span></span>
</div>
<div id="opt-body-10" class="optional-body" style="display: none;">
<p>“Z-scoring” is a method of standardising a variable so that it has a mean of zero and a standard deviation of one. We actually saw this back in <a href="02b_sampling.html#the-standard-normal-distribution" target="_blank">2B#the-standard-normal-distribution</a>.</p>
<p>To transform a given value <span class="math inline">\(x_i\)</span> into a <strong>z-score</strong> <span class="math inline">\(z_i\)</span>, we simply calculate the distance from <span class="math inline">\(x_i\)</span> to the mean, <span class="math inline">\(\bar{x}\)</span>, and divide this by the standard deviation, <span class="math inline">\(s\)</span>:</p>
<p><span class="math display">\[
z_i = \frac{x_i - \bar{x}}{s}
\]</span></p>
<p>A Z-score of a value is the number of standard deviations below/above the mean that the value falls.</p>
</div>
<p class="optional-end">
</p>
</div>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Read in the Social Comparison Study data and explore the relevant distributions and relationships between the variables of interest to the research question below.</p>
<blockquote class="blockquote">
<p>After accounting for other personality traits, does the effect of social comparison on symptoms of depression, anxiety and stress vary depending on level of neuroticism?</p>
</blockquote>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>scs_study <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/scs_study.csv"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(scs_study)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       zo                 zc                 ze                 za          
 Min.   :-2.81928   Min.   :-3.21819   Min.   :-3.00576   Min.   :-2.94429  
 1st Qu.:-0.63089   1st Qu.:-0.66866   1st Qu.:-0.68895   1st Qu.:-0.69394  
 Median : 0.08053   Median : 0.00257   Median :-0.04014   Median :-0.01854  
 Mean   : 0.09202   Mean   : 0.01951   Mean   : 0.00000   Mean   : 0.00000  
 3rd Qu.: 0.80823   3rd Qu.: 0.71215   3rd Qu.: 0.67085   3rd Qu.: 0.72762  
 Max.   : 3.55034   Max.   : 3.08015   Max.   : 2.80010   Max.   : 2.97010  
       zn               scs             dass      
 Min.   :-1.4486   Min.   :27.00   Min.   :23.00  
 1st Qu.:-0.7994   1st Qu.:33.00   1st Qu.:41.00  
 Median :-0.2059   Median :35.00   Median :44.00  
 Mean   : 0.0000   Mean   :35.77   Mean   :44.72  
 3rd Qu.: 0.5903   3rd Qu.:38.00   3rd Qu.:49.00  
 Max.   : 3.3491   Max.   :54.00   Max.   :68.00  </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> scs_study, <span class="fu">aes</span>(<span class="at">x=</span>dass)) <span class="sc">+</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Marginal distribution of DASS-21 Scores"</span>, </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Depression Anxiety and Stress Scale"</span>, <span class="at">y =</span> <span class="st">"Probability density"</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> scs_study, <span class="fu">aes</span>(<span class="at">x=</span>scs)) <span class="sc">+</span> </span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span> </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Marginal distribution of Social Comparison Scale (SCS) scores"</span>, </span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Social Comparison Scale Score"</span>, <span class="at">y =</span> <span class="st">"Probability density"</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> scs_study, <span class="fu">aes</span>(<span class="at">x=</span>zn)) <span class="sc">+</span> </span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span> </span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Marginal distribution of Neuroticism (Z-Scored)"</span>, </span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Neuroticism (Z-Scored)"</span>, <span class="at">y =</span> <span class="st">"Probability density"</span>)</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">/</span> (p2 <span class="sc">+</span> p3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_ex_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="int">
<p>The marginal distribution of scores on the Depression, Anxiety and Stress Scale (DASS-21) is unimodal with a mean of approximately 45 and a standard deviation of 7.</p>
<p>The marginal distribution of scores on the Social Comparison Scale (SCS) is unimodal with a mean of approximately 36 and a standard deviation of 4. There look to be a number of outliers at the upper end of the scale.</p>
<p>The marginal distribution of Neuroticism (Z-scored) is positively skewed, with the 25% of scores falling below -0.8, 75% of scores falling below 0.59.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> scs_study, <span class="fu">aes</span>(<span class="at">x=</span>scs, <span class="at">y=</span>dass)) <span class="sc">+</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"SCS"</span>, <span class="at">y =</span> <span class="st">"DASS-21"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> scs_study, <span class="fu">aes</span>(<span class="at">x=</span>zn, <span class="at">y=</span>dass)) <span class="sc">+</span> </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Neuroticism"</span>, <span class="at">y =</span> <span class="st">"DASS-21"</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">/</span> p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_ex_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr) <span class="co"># for making tables look nice</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the kable() function from the knitr package can make table outputs print nicely into html.</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>scs_study <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(dass, scs, zn) <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  cor <span class="sc">%&gt;%</span> </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  kable</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> dass </th>
   <th style="text-align:right;"> scs </th>
   <th style="text-align:right;"> zn </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> dass </td>
   <td style="text-align:right;"> 1.0000000 </td>
   <td style="text-align:right;"> -0.2280126 </td>
   <td style="text-align:right;"> 0.2001885 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> scs </td>
   <td style="text-align:right;"> -0.2280126 </td>
   <td style="text-align:right;"> 1.0000000 </td>
   <td style="text-align:right;"> 0.1146687 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> zn </td>
   <td style="text-align:right;"> 0.2001885 </td>
   <td style="text-align:right;"> 0.1146687 </td>
   <td style="text-align:right;"> 1.0000000 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="int">
<p>There is a weak, negative, linear relationship between scores on the Social Comparison Scale and scores on the Depression Anxiety and Stress Scale for the participants in the sample. Severity of symptoms measured on the DASS-21 tend to decrease, on average, the more favourably participants view their social rank.<br>
There is a weak, positive, linear relationship between the levels of Neuroticism and scores on the DASS-21. Participants who are more neurotic tend to, on average, display a higher severity of symptoms of depression, anxiety and stress.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Fit your model using <code>lm()</code>. Examine the coefficients, plot the relevant estimated associations to visually address the research question.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>there are sort of two bits to this:
<ul>
<li>“after accounting for” (i.e., the stuff we learned in <a href="08a_mlr.html" target="_blank">8A#multiple-regression</a>)</li>
<li>“the effect of this depends on that” (the interaction stuff from <a href="09a_interactions.html" target="_blank">9a#interactions</a>).</li>
</ul></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dass_mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(dass <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> zo <span class="sc">+</span> zc <span class="sc">+</span> ze <span class="sc">+</span> za <span class="sc">+</span> scs<span class="sc">*</span>zn, <span class="at">data =</span> scs_study)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dass_mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = dass ~ 1 + zo + zc + ze + za + scs * zn, data = scs_study)

Residuals:
    Min      1Q  Median      3Q     Max 
-17.346  -3.817  -0.195   3.865  45.214 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 60.83961    2.44077  24.926  &lt; 2e-16 ***
zo          -0.18341    0.23322  -0.786   0.4319    
zc          -0.05606    0.23795  -0.236   0.8138    
ze           0.72317    0.36203   1.998   0.0462 *  
za           0.19870    0.36289   0.548   0.5842    
scs         -0.44425    0.06798  -6.535 1.29e-10 ***
zn          20.13823    2.34987   8.570  &lt; 2e-16 ***
scs:zn      -0.51957    0.06524  -7.964 7.48e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.075 on 648 degrees of freedom
Multiple R-squared:  0.2002,    Adjusted R-squared:  0.1916 
F-statistic: 23.17 on 7 and 648 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Recall that the coefficient <code>zn</code> from our model now reflects the estimated change in the outcome associated with an increase of 1 in neuroticism, <em>when the other variable (SCS) is zero</em> (and holding constant other personality traits).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(dass_mdl, <span class="at">type =</span> <span class="st">"int"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_ex_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p>Think - what does “0” represent in each variable? And what does an increase of 1 represent? Are these meaningful?</p>
<p>The <code>zn</code> variable is standardised, meaning that “0” is the mean, and moving from “0” to “1” is moving 1 standard deviation.</p>
<p>I would argue that because “0” on <code>scs</code> variable is not a possible score that anyone can get, we may want to re-center this variable.</p>
<p>Recenter the <code>scs</code> variable on either:</p>
<ul>
<li>the minimum possible SCS score</li>
<li>the mean SCS score</li>
</ul>
<div class="hints">
<p><strong>Hint:</strong></p>
<ul>
<li>You can choose either min or mean. It won’t change your model, it will just change what you get out of it.<br>
</li>
<li>You can see an example of mean-centering in <a href="09a_interactions.html#getting-more-from-your-model" target="_blank">9A#getting-more-from-your-model</a>.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-13" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')"> Solution </span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>scs_study <span class="ot">&lt;-</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  scs_study <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">scs_Cmean =</span> scs <span class="sc">-</span> <span class="fu">mean</span>(scs),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">scs_Cmin =</span> scs <span class="sc">-</span> <span class="fu">min</span>(scs)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 13
</div>
<div class="question-body">
<p>Re-fit your model using your re-centered SCS scores instead of the original variable.</p>
<p>Fill in the blanks in the statements below.</p>
<ul>
<li>For those at the mean on all personality traits and scoring <strong>???</strong> on the SCS, the estimated DASS-21 Score is <strong>???</strong><br>
</li>
<li>For those who score <strong>???</strong> on the SCS, an increase of <strong>???</strong> in neuroticism is associated with a change of <strong>???</strong> in DASS-21 Scores, holding other personality traits constant.</li>
<li>For those of average neuroticism, an increase of <strong>???</strong> on the SCS is associated with a change of <strong>???</strong> in DASS-21 Scores, holding other personality traits constant.<br>
</li>
<li>For every increase of <strong>???</strong> in neuroticism, the change in DASS-21 associated with an increase of <strong>???</strong> on the SCS is asjusted by <strong>???</strong></li>
<li>For every increase of <strong>???</strong> in SCS, the change in DASS-21 associated with an increase of <strong>???</strong> in neuroticism is asjusted by <strong>???</strong></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-14" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-14', 'sol-start-14')"> Solution </span>
</div>
<div id="sol-body-14" class="solution-body" style="display: none;">
<div class="panelset">
<section id="mean-centered" class="level4 panel">
<h4 class="anchored" data-anchor-id="mean-centered">Mean Centered</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>dass_mdl2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(dass <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> scs_Cmean <span class="sc">*</span> zn, <span class="at">data =</span> scs_study)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># pull out the coefficients from the summary():</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dass_mdl2)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error    t value     Pr(&gt;|t|)
(Intercept)  44.9324476 0.24052861 186.807079 0.000000e+00
scs_Cmean    -0.4439065 0.06834135  -6.495431 1.643265e-10
zn            1.5797687 0.24086372   6.558766 1.105118e-10
scs_Cmean:zn -0.5186142 0.06552100  -7.915236 1.063297e-14</code></pre>
</div>
</div>
<ul>
<li>For those at the mean on all personality traits and scoring <strong>average</strong> on the SCS, the estimated DASS-21 Score is <strong>44.93</strong><br>
</li>
<li>For those who score <strong>average (mean)</strong> on the SCS, an increase of <strong>1 standard deviation</strong> in neuroticism is associated with a change of 1.58 in DASS-21 Scores, holding other personality traits constant.</li>
<li>For those of average neuroticism, an increase of <strong>1 point</strong> on the SCS is associated with a change of -0.44 in DASS-21 Scores, holding other personality traits constant.<br>
</li>
<li>For every increase of <strong>1 standard deviation</strong> in neuroticism, the change in DASS-21 associated with an increase of <strong>1 point</strong> on the SCS is asjusted by <strong>-0.52</strong></li>
<li>For every increase of <strong>1 point</strong> in SCS, the change in DASS-21 associated with an increase of <strong>1 standard deviation</strong> in neuroticism is asjusted by <strong>-0.52</strong></li>
</ul>
</section>
<section id="minimum-centered" class="level4 panel">
<h4 class="anchored" data-anchor-id="minimum-centered">Minimum-centered</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>dass_mdl2a <span class="ot">&lt;-</span> <span class="fu">lm</span>(dass <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> scs_Cmin <span class="sc">*</span> zn, <span class="at">data =</span> scs_study)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># pull out the coefficients from the summary():</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dass_mdl2a)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 48.8233968 0.64359279 75.860695 0.000000e+00
scs_Cmin    -0.4439065 0.06834135 -6.495431 1.643265e-10
zn           6.1255486 0.62628048  9.780839 3.572450e-21
scs_Cmin:zn -0.5186142 0.06552100 -7.915236 1.063297e-14</code></pre>
</div>
</div>
<ul>
<li>For those at the mean on all personality traits and scoring <strong>minimum</strong> on the SCS, the estimated DASS-21 Score is <strong>48.82</strong><br>
</li>
<li>For those who score <strong>the minimum</strong> on the SCS, an increase of <strong>1 standard deviation</strong> in neuroticism is associated with a change of 6.13 in DASS-21 Scores, holding other personality traits constant.</li>
<li>For those of average neuroticism, an increase of <strong>1 point</strong> on the SCS is associated with a change of -0.44 in DASS-21 Scores, holding other personality traits constant.<br>
</li>
<li>For every increase of <strong>1 standard deviation</strong> in neuroticism, the change in DASS-21 associated with an increase of <strong>1 point</strong> on the SCS is asjusted by <strong>-0.52</strong></li>
<li>For every increase of <strong>1 point</strong> in SCS, the change in DASS-21 associated with an increase of <strong>1 standard deviation</strong> in neuroticism is asjusted by <strong>-0.52</strong></li>
</ul>
</section>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="seasonal-extraversion" class="level1">
<h1>Seasonal Extraversion</h1>
<div class="frame">
<p><strong>USMR 2022 Data</strong></p>
<p>The data from the USMR 2022 survey (now closed) can be found at <a href="https://uoepsy.github.io/data/usmr2022.csv">https://uoepsy.github.io/data/usmr2022.csv</a>.</p>
<p><em>note, this is the survey data just from USMR <strong>this</strong> year, not other students on other courses or in previous years</em></p>
</div>
<div class="question-begin">
Question 14
</div>
<div class="question-body">
<p>We want to make a variable that indicates what season each person was born in.</p>
<p>We have seen the <code>ifelse()</code> command a few of times now, but something we are yet to see is that we can have <em>nested</em> statements. So we could turn everybody’s birth-months into a season by doing something like the below, where we ask “if it’s january then it’s winter, else if it’s february then it’s winter, else if it’s march…” and so on.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr2022.csv"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">season =</span> <span class="fu">ifelse</span>(birthmonth <span class="sc">==</span> <span class="st">"jan"</span>, <span class="st">"winter"</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(birthmonth <span class="sc">==</span> <span class="st">"feb"</span>, <span class="st">"winter"</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">ifelse</span>(birthmonth <span class="sc">==</span> <span class="st">"mar"</span>, <span class="st">"spring"</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">ifelse</span>( ..... </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can make this a little more efficient by use of the <code>%in%</code> operator, which allows us to ask “if it’s <em>one of</em> [december, january, february] then it’s winter, else…”.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">season =</span> <span class="fu">ifelse</span>(birthmonth <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"dec"</span>,<span class="st">"jan"</span>, <span class="st">"feb"</span>), <span class="st">"winter"</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(birthmonth <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"mar"</span>,<span class="st">"apr"</span>,<span class="st">"may"</span>), <span class="st">"spring"</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                         ...</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                         ...</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Complete the code above in order to make a column that assigns the correct birth-season based on their month of birth.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>you don’t have to write out the last “if”, because you can capture those in the final “else” bit.<br>
</li>
<li>if you want a more tidyverse way to do this then look up the help docs for the <code>case_when()</code> function.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-15" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-15', 'sol-start-15')"> Solution </span>
</div>
<div id="sol-body-15" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr2022.csv"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="ot">&lt;-</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  usmrdata <span class="sc">%&gt;%</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">season =</span> <span class="fu">ifelse</span>(birthmonth <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"dec"</span>,<span class="st">"jan"</span>, <span class="st">"feb"</span>), <span class="st">"winter"</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(birthmonth <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"mar"</span>,<span class="st">"apr"</span>,<span class="st">"may"</span>), <span class="st">"spring"</span>,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">ifelse</span>(birthmonth <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"jun"</span>,<span class="st">"jul"</span>,<span class="st">"aug"</span>), <span class="st">"summer"</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"autumn"</span>)))</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The tidyverse way:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="ot">&lt;-</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  usmrdata <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">season =</span> <span class="fu">case_when</span>(</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>      birthmonth <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"dec"</span>,<span class="st">"jan"</span>, <span class="st">"feb"</span>) <span class="sc">~</span> <span class="st">"winter"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>      birthmonth <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"mar"</span>,<span class="st">"apr"</span>,<span class="st">"may"</span>) <span class="sc">~</span> <span class="st">"spring"</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>      birthmonth <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"jun"</span>,<span class="st">"jul"</span>,<span class="st">"aug"</span>) <span class="sc">~</span> <span class="st">"summer"</span>,</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"autumn"</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 15
</div>
<div class="question-body">
<p>Make the season variable that you just created a factor.</p>
<p>We would like you to do the following, in order:</p>
<ol type="1">
<li>fit a model <code>lm(extraversion ~ season)</code>, and assign it the name <code>seasonmod1</code>.<br>
</li>
<li>relevel the season variable to have “spring” as the reference level.</li>
<li>fit the same model, this time assigning it the name <code>seasonmod2</code></li>
<li>set the contrasts for the season variable to be “sum contrasts”</li>
<li>fit the same model, this time assigning it the name <code>seasonmod3</code></li>
</ol>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>for relevelling factors, we’ve seen this in <a href="09a_interactions.html#getting-more-from-your-model" target="_blank">9A#getting-more-from-your-model</a>.</li>
<li>for “sum contrasts” and how to set them, see <a href="09b_contrasts.html#sum-contrasts" target="_blank">9B#sum-contrasts</a>.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-16" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-16', 'sol-start-16')"> Solution </span>
</div>
<div id="sol-body-16" class="solution-body" style="display: none;">
<p>Make it a factor:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>usmrdata<span class="sc">$</span>season <span class="ot">&lt;-</span> <span class="fu">factor</span>(usmrdata<span class="sc">$</span>season)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>fit model 1</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>seasonmod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(extraversion <span class="sc">~</span> season, <span class="at">data =</span> usmrdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>relevel to have spring as the reference:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>usmrdata<span class="sc">$</span>season <span class="ot">&lt;-</span> <span class="fu">fct_relevel</span>(usmrdata<span class="sc">$</span>season, <span class="st">"spring"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>fit model again (model 2)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>seasonmod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(extraversion <span class="sc">~</span> season, <span class="at">data =</span> usmrdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>here are the current contrasts:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(usmrdata<span class="sc">$</span>season)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       autumn summer winter
spring      0      0      0
autumn      1      0      0
summer      0      1      0
winter      0      0      1</code></pre>
</div>
</div>
<p>set them to sum contrasts:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(usmrdata<span class="sc">$</span>season) <span class="ot">&lt;-</span> <span class="st">"contr.sum"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and take a look</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(usmrdata<span class="sc">$</span>season)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       [,1] [,2] [,3]
spring    1    0    0
autumn    0    1    0
summer    0    0    1
winter   -1   -1   -1</code></pre>
</div>
</div>
<p>fit the model <em>again</em> (model 3)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>seasonmod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(extraversion <span class="sc">~</span> season, <span class="at">data =</span> usmrdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 16
</div>
<div class="question-body">
<p>Calculate the mean extraversion of people born in each season. From these, also calculate the mean of those four means.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>you can use the <code>data %&gt;% group_by %&gt;% summarise</code> logic here.<br>
</li>
<li>to calculate a mean of means, how about <code>data %&gt;% group_by %&gt;% summarise %&gt;% summarise</code>!</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-17" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-17', 'sol-start-17')"> Solution </span>
</div>
<div id="sol-body-17" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanEx =</span> <span class="fu">mean</span>(extraversion))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  season meanEx
  &lt;fct&gt;   &lt;dbl&gt;
1 spring   30.3
2 autumn   26.1
3 summer   33.2
4 winter   29.7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanEx =</span> <span class="fu">mean</span>(extraversion)) <span class="sc">%&gt;%</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">grandmeanEx =</span> <span class="fu">mean</span>(meanEx))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  grandmeanEx
        &lt;dbl&gt;
1        29.8</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 17
</div>
<div class="question-body">
<p>Because there aren’t any other predictors in our model, our coefficients from all three models we fitted in question 15 are going to be various comparisons between the numbers we calculated in question 16</p>
<p>For every coefficient estimate in the three models, write down what difference it is estimating, and check it against the numbers you calculated in question 16</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(seasonmod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) seasonspring seasonsummer seasonwinter 
   26.117647     4.174020     7.132353     3.609626 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(seasonmod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) seasonautumn seasonsummer seasonwinter 
  30.2916667   -4.1740196    2.9583333   -0.5643939 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(seasonmod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)     season1     season2     season3 
 29.8466466   0.4450201  -3.7289996   3.4033534 </code></pre>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-18" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-18', 'sol-start-18')"> Solution </span>
</div>
<div id="sol-body-18" class="solution-body" style="display: none;">
<div class="panelset">
<section id="seasonmod1" class="level4 panel">
<h4 class="anchored" data-anchor-id="seasonmod1">seasonmod1</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(seasonmod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) seasonspring seasonsummer seasonwinter 
   26.117647     4.174020     7.132353     3.609626 </code></pre>
</div>
</div>
<p>For the first model, the ordering of the levels is alphabetical, and so “autumn” is the reference level. This means the intercept is the extraversion of autumn-babies, and each coefficient is the other months compared to autumn:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="sc">%&gt;%</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanEx =</span> <span class="fu">mean</span>(extraversion)) <span class="sc">%&gt;%</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">compare =</span> meanEx <span class="sc">-</span> meanEx[season<span class="sc">==</span><span class="st">"autumn"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  season meanEx compare
  &lt;fct&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 spring   30.3    4.17
2 autumn   26.1    0   
3 summer   33.2    7.13
4 winter   29.7    3.61</code></pre>
</div>
</div>
</section>
<section id="seasonmod2" class="level4 panel">
<h4 class="anchored" data-anchor-id="seasonmod2">seasonmod2</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(seasonmod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) seasonautumn seasonsummer seasonwinter 
  30.2916667   -4.1740196    2.9583333   -0.5643939 </code></pre>
</div>
</div>
<p>For the second model, we changed it so that spring is the reference level, which means spring is the intercept, and the coefficients are each level compared to spring:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanEx =</span> <span class="fu">mean</span>(extraversion)) <span class="sc">%&gt;%</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">compare =</span> meanEx <span class="sc">-</span> meanEx[season<span class="sc">==</span><span class="st">"spring"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  season meanEx compare
  &lt;fct&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 spring   30.3   0    
2 autumn   26.1  -4.17 
3 summer   33.2   2.96 
4 winter   29.7  -0.564</code></pre>
</div>
</div>
</section>
<section id="seasonmod3" class="level4 panel">
<h4 class="anchored" data-anchor-id="seasonmod3">seasonmod3</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(seasonmod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)     season1     season2     season3 
 29.8466466   0.4450201  -3.7289996   3.4033534 </code></pre>
</div>
</div>
<p>For the final model it is a little more difficult. We’re using sum contrasts, so the intercept is going to be the ‘grand mean’ (mean of season means), which we calculated in question 16 was 29.85.</p>
<p>We know that the coefficients are going to be comparisons between each season and the grand mean. But (annoyingly) they no longer have useful names - the coefficients are just <code>season1</code> and <code>season2</code> (whatever they are).</p>
<p>To see it more clearly, we can look at our contrast matrix:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(usmrdata<span class="sc">$</span>season)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       [,1] [,2] [,3]
spring    1    0    0
autumn    0    1    0
summer    0    0    1
winter   -1   -1   -1</code></pre>
</div>
</div>
<p>We can see from the 1s that our coefficients are going to be spring vs the grand mean, autumn vs the grand mean and summer vs the grand mean.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="sc">%&gt;%</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanEx =</span> <span class="fu">mean</span>(extraversion)) <span class="sc">%&gt;%</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">compare =</span> meanEx <span class="sc">-</span> <span class="fl">29.85</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  season meanEx compare
  &lt;fct&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 spring   30.3   0.442
2 autumn   26.1  -3.73 
3 summer   33.2   3.4  
4 winter   29.7  -0.123</code></pre>
</div>
</div>
</section>
</div>
</div>
<p class="solution-end">
</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>