<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - 9A: Interactions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-down')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>
<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 1</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html">
 <span class="dropdown-text">1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html">
 <span class="dropdown-text">1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 2</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html">
 <span class="dropdown-text">2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html">
 <span class="dropdown-text">2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 3</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html">
 <span class="dropdown-text">3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html">
 <span class="dropdown-text">3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html">
 <span class="dropdown-text">Exercises: T-tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 4</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04a_chisq.html">
 <span class="dropdown-text">4A: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revisitnhst.html">
 <span class="dropdown-text">4B: Revisiting NHST</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_ex.html">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 5</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li>
    <a class="dropdown-item" href="./05a_covcor.html">
 <span class="dropdown-text">5A: Covariance &amp; Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_ex.html">
 <span class="dropdown-text">Exercises: Cov, Cor, Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-6" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 6</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-6">    
        <li>
    <a class="dropdown-item" href="./06_wt.html">
 <span class="dropdown-text">Walkthrough: Advanced Data Wrangling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 7</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li>
    <a class="dropdown-item" href="./07a_slr.html">
 <span class="dropdown-text">7A: Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_ex.html">
 <span class="dropdown-text">Exercises: Simple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 8</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li>
    <a class="dropdown-item" href="./08a_mlr.html">
 <span class="dropdown-text">8A: Multiple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08b_assumptdiag.html">
 <span class="dropdown-text">8B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08_ex.html">
 <span class="dropdown-text">Exercises: Multiple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 9</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li>
    <a class="dropdown-item" href="./09a_interactions.html">
 <span class="dropdown-text">9A: Interactions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09b_contrasts.html">
 <span class="dropdown-text">9B: Categorical Predictors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09_ex.html">
 <span class="dropdown-text">Exercises: Interactions</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-10" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 10</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-10">    
        <li class="dropdown-header">10A: GLM!</li>
        <li class="dropdown-header">Exercises: Logistic Regression</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-11" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 11</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-11">    
        <li class="dropdown-header">11A: Common Tests as Linear Models</li>
        <li class="dropdown-header">11B: Writing Up</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#holding-constant" id="toc-holding-constant" class="nav-link active" data-scroll-target="#holding-constant">Holding Constant…</a></li>
  <li><a href="#it-depends" id="toc-it-depends" class="nav-link" data-scroll-target="#it-depends">It Depends…</a></li>
  <li><a href="#interactions" id="toc-interactions" class="nav-link" data-scroll-target="#interactions">Interactions!</a></li>
  <li><a href="#fitting-interactions-in-r" id="toc-fitting-interactions-in-r" class="nav-link" data-scroll-target="#fitting-interactions-in-r">Fitting interactions in R</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#visualisation" id="toc-visualisation" class="nav-link" data-scroll-target="#visualisation">Visualisation</a></li>
  <li><a href="#getting-more-from-your-model" id="toc-getting-more-from-your-model" class="nav-link" data-scroll-target="#getting-more-from-your-model">Getting more from your model</a>
  <ul class="collapse">
  <li><a href="#mean-centering" id="toc-mean-centering" class="nav-link" data-scroll-target="#mean-centering">Mean Centering</a></li>
  <li><a href="#releveling-factors" id="toc-releveling-factors" class="nav-link" data-scroll-target="#releveling-factors">Releveling Factors</a></li>
  </ul></li>
  <li><a href="#optional-extra-getting-non-linear" id="toc-optional-extra-getting-non-linear" class="nav-link" data-scroll-target="#optional-extra-getting-non-linear">Optional Extra: Getting non-linear</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">9A: Interactions</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="holding-constant" class="level1">
<h1>Holding Constant…</h1>
<p>When we learned about multiple linear regression last week, we talked about the idea of the coefficients as “holding constant” the other predictors in the model.</p>
<p>Consider a model with the following structure:</p>
<p><span class="math display">\[
y = b_0 + b_1(x_1) + b_2(x_2) + \epsilon
\]</span></p>
<p>When we <em>fit</em> this model to our data, what we get out is some <em>estimated</em> values for the coefficients <span class="math inline">\(b_0\)</span>, <span class="math inline">\(b_1\)</span>, and <span class="math inline">\(b_2\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>mydata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_mlr.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>mymodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -2.39138    3.67735  -0.650  0.51867   
x1           0.17570    0.06435   2.730  0.00888 **
x2          -0.64756    0.19959  -3.244  0.00217 **</code></pre>
<p>The coefficient we get out for <span class="math inline">\(x_1\)</span> tells us that the model estimates that <span class="math inline">\(y\)</span> will increase by 0.17 for every increase of 1 unit in <span class="math inline">\(x_1\)</span>, <em>provided that we hold <span class="math inline">\(x_2\)</span> constant.</em></p>
<p>What this means is that whatever value <span class="math inline">\(x_2\)</span> is, provided it stays the same, a one unit increase in <span class="math inline">\(x_1\)</span> is associated with a <span class="math inline">\(b_1\)</span> change in <span class="math inline">\(y\)</span>.</p>
<p>As it happens, we can use <code>plot_model</code> to show us the how <span class="math inline">\(y\)</span> changes with <span class="math inline">\(x_1\)</span> <em>for some specific values of <span class="math inline">\(x_2\)</span></em>.<br>
Below, the three lines show the association between <span class="math inline">\(y\)</span> and <span class="math inline">\(x_1\)</span> when:</p>
<ul>
<li><span class="math inline">\(x_2 = 3\)</span> (red line)</li>
<li><span class="math inline">\(x_2 = 12\)</span> (blue line)</li>
<li><span class="math inline">\(x_2 = 20\)</span> (green line)</li>
</ul>
<p>As we can see, the slope of <span class="math inline">\(y\)</span> on <span class="math inline">\(x_1\)</span> is the same.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the effect of x1, at 3 specific values of x2</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(mymodel, <span class="at">type =</span> <span class="st">"eff"</span>, <span class="at">terms=</span><span class="fu">c</span>(<span class="st">"x1"</span>, <span class="st">"x2 [3, 12, 20]"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="frame">
<p><strong>Example</strong></p>
<p>We’re interested in estimating the association between BMI and cognition, after controlling for differences due to age.</p>
<p>We want to use this model:</p>
<p><span class="math display">\[
\text{score on test of cognition} = b_0 + b_1(\text{age}) + b_2(\text{BMI}) + \epsilon
\]</span></p>
<p>which we can fit using <code>lm()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(score <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> age <span class="sc">+</span> BMI, <span class="at">data =</span> ourdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and we might get some coefficients (estimates for the <span class="math inline">\(b_?\)</span> values) such as those below:<br>
<em>(I’ve just made up some nice round numbers to make it easier to think about)</em></p>
<pre><code>Coefficients:
            Estimate    ...   ...
(Intercept)  160.000    ...   ...
age         -1.50000    ...   ...
BMI         -2.50000    ...   ...</code></pre>
<p>The coefficient of interest, the one for BMI, is telling us that “a 1 unit increase in BMI is associated with a -2.5 decrease in Scores on the cognitive test, <em>holding age constant</em>”.</p>
<p>Consider 3 people:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pplconstant" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/ints/constant.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 1: Three theoretical people</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The coefficient for BMI represents the difference in cognitive scores we would expect between Person A and Person B.</p>
<p>Think about why this is.<br>
For some person <span class="math inline">\(i\)</span>, their model predicted score is:</p>
<p><span class="math display">\[
\hat{score_i} = b_0 + b_1(age_i) + b_2(BMI_i)
\]</span></p>
<p>Which from our model estimates is:</p>
<p><span class="math display">\[
\hat{score_i} = 160 - 1.5(age_i) - 2.5(BMI_i)
\]</span></p>
<ul>
<li>Person A’s score = <span class="math inline">\(160 - (1.5*50) - (2.5*22) = 30\)</span></li>
<li>Person B’s score = <span class="math inline">\(160 - (1.5*50) - (2.5*23) = 27.5\)</span></li>
<li>Person C’s score = <span class="math inline">\(160 - (1.5*60) - (2.5*23) = 12.5\)</span></li>
</ul>
<p>The difference in model estimated Score between Person A and Person B is the coefficient of BMI, because those two people <em>only differ</em> on BMI. Person A and Person C <em>also differ</em> on age. This is how the coefficient of BMI is interpreted as “holding age constant” - it is a comparison between two hypothetical people who differ on BMI but are identical with respect to the other predictors in the model.</p>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="it-depends" class="level1">
<h1>It Depends…</h1>
<p>There are lots of practical cases where we might think that the relationship between two variables <em>depends on</em> the value of a third. Put another way, we might think that the effect of one predictor <em>depends</em> on another.</p>
<p>Below are some examples of this idea, where the explanatory variables (the predictors) are of different types (e.g.&nbsp;continuous, categorical, etc):</p>
<div class="panelset">
<section id="example-1" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-1">Example 1</h4>
<blockquote class="blockquote">
<p>The amount to which spending time with my partner influences my wellbeing <em>depends on</em> the quality of our relationship.</p>
</blockquote>
<p>Variables:</p>
<ul>
<li><strong>Outcome:</strong> Wellbeing (questionnaire score ranging from 0 to 32)</li>
<li><strong>Continuous Predictor:</strong> Time spent with partner (hours per week)<br>
</li>
<li><strong>Continuous Predictor:</strong> Relationship Quality (rating from 0 to 100)</li>
</ul>
</section>
<section id="example-2" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-2">Example 2</h4>
<blockquote class="blockquote">
<p>The influence of air-pollution on cognitive functioning <em>depends on</em> your genetic status.</p>
</blockquote>
<p>Variables:</p>
<ul>
<li><strong>Outcome:</strong> Cognitive Functioning measured via the MMSE. Possible scores range from 0 to 30. Lower scores indicate poorer cognitive functioning</li>
<li><strong>Continuous Predictor:</strong> Air-Quality Pollution Index (AQI). Ranges from 0 to 500. The higher the AQI value, the greater the level of air pollution.</li>
<li><strong>Categorical Predictor:</strong> APOE-4 Genotype status: Negative vs Positive</li>
</ul>
</section>
<section id="example-3" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-3">Example 3</h4>
<blockquote class="blockquote">
<p>The influence of being anonymous on childrens’ greedy behaviours <em>depends on</em> if they are alone or part of a group.</p>
</blockquote>
<p>Variables:</p>
<ul>
<li><strong>Outcome</strong>: Number of candy bars taken while trick or treating</li>
<li><strong>Categorical Predictor:</strong> Whether or not the childs’ identity is hidden by their costume (anonymous vs identifiable)</li>
<li><strong>Categorical Predictor:</strong> Whether the child is trick or treating as a group or alone (alone vs group)</li>
</ul>
</section>
</div>
<hr>
<p>In each of the above examples, we can no longer think about “the relationship between [outcome] and [predictor]” without discussing the level of the other predictor.</p>
<div class="columns">
<div class="column" style="width:55%;">
<p>Using Example 1 above, let’s return to thinking about this in terms of two different observations (i.e.&nbsp;two different people in <a href="#fig-pplint">Figure&nbsp;2</a>).</p>
<p>How do we think each person’s wellbeing will change if they spend an extra hour with their partner?</p>
<p>Person A (who has a really great relationship), will probably increase in wellbeing if they were to spend more timewith their partner.</p>
<p>Will it be the same for Person B? Person B doesn’t have a great relationship. If they spend an extra hour with their partner, we probably wouldn’t expect their wellbeing to increase <em>to the same extent as Person A</em>. It might even go down for Person B!</p>
</div><div class="column" style="width:45%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pplint" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/ints/ints.png" style="width:80.0%" height="400" class="figure-img"></p>
<p></p><figcaption class="figure-caption">Figure 2: Two theoretical people</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>To capture this, what we need is an extra bit of information to tell us “how <em>much</em> does the association between ‘time spent with partner’ and wellbeing change as relationship quality changes?” And this is something we can include in our model, and get an estimate for!</p>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="interactions" class="level1">
<h1>Interactions!</h1>
<p>We can model the idea of “the association between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span> changes <em>depending on</em> the level of <span class="math inline">\(x_2\)</span>” by including a product (multiplication) term between the two predictors.<br>
Such a model would take the form:</p>
<p><span class="math display">\[
y = b_0 + b_1(x_1) + b_2(x_2) + b_3(x_1 \cdot x_2) + \epsilon
\]</span></p>
<p>What this is doing is saying that our outcome <span class="math inline">\(y\)</span> is predicted by:</p>
<ul>
<li>some amount of <span class="math inline">\(x_1\)</span></li>
<li>some amount of <span class="math inline">\(x_2\)</span></li>
<li>and a little addition to each of those amounts depending on the value of of the other variable.</li>
</ul>
<p>To provide a visual intuition and build on how we have been thinking of multiple regression upto this point, when we have two predictors that interact, our regression surface is no longer flat, but <em>twists</em>. This is because the slope along values of <span class="math inline">\(x_1\)</span> <em>changes</em> as we move up <span class="math inline">\(x_2\)</span>:</p>
<div class="panelset">
<section id="example-1-1" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-1-1">Example 1</h4>
<blockquote class="blockquote">
<p>The amount to which spending time with my partner influences my wellbeing <em>depends on</em> the quality of our relationship.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-i.contcont" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/fig-i.contcont-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 3: Interaction between two continuous predictors, viewed from two angles</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>At high values of relationship quality, the amount wellbeing increases with time spent is greater than it is at low values of relationship quality.<br>
And we can phrase this the other way around: at high amounts of time spent with partner, relationship quality has a bigger effect on wellbeing than it does for low amounts of time spent.</p>
<p>In the model with this interaction:</p>
<p><span class="math display">\[
\text{wellbeing} = b_0 + b_1(\text{time}) + b_2(\text{quality}) + b_3(\text{time} \times \text{quality})
\]</span></p>
<p>The interaction coefficient <span class="math inline">\(b_3\)</span> is the adjustment we make to the slope of wellbeing with “time spent with partner”, as we move 1 up in “relationship quality”.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</section>
<section id="example-2-1" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-2-1">Example 2</h4>
<blockquote class="blockquote">
<p>The influence of air-pollution on cognitive functioning <em>depends on</em> your genetic status.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-i.contcat" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/fig-i.contcat-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 4: Interaction between a continuous and a binary categorical predictors</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>This kind of interaction (where one predictor is continuous and the other is categorical), is sometimes the easiest to think about.</p>
<p>We can see in <a href="#fig-i.contcat">Figure&nbsp;4</a> that cognition decreases as air pollution increases, <strong>but</strong> this is different depending on genetic status. In the APOE4-positive group, the association is steeper than in the APOE4-negative group. The interaction is evident in that the two lines are non-parallel.</p>
<p>In the model:</p>
<p><span class="math display">\[
\text{Cognition} = b_0 + b_1(\text{air pollution}) + b_2(\text{APOE4+}) + b_3(\text{air pollution} \times \text{APOE4+})
\]</span></p>
<p>The interaction term <span class="math inline">\(b_3\)</span> is the estimated adjustment made to the slope of cogition across air pollution to move from one group to the other. e.g.&nbsp;the slope for the APOE4-positive group is equal to the slope of the APOE4-negative group <em>plus the interaction term</em>.</p>
</section>
<section id="example-3-1" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-3-1">Example 3</h4>
<blockquote class="blockquote">
<p>The influence of being anonymous on childrens’ greedy behaviours <em>depends on</em> if they are alone or part of a group.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-i.catcat" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/fig-i.catcat-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 5: Interaction between two categorical predictors</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>For interactions between two categorical variables, we tend to plot the mean of the outcome variable for each combination of levels. We can see the interaction in <a href="#fig-i.catcat">Figure&nbsp;5</a> in the fact that the two dotted lines we have added to join the group-means are not parallel.</p>
<p>Children who are anonymous tend to take more candybars than those who are identifiable, but this difference is much greater when children are trick of treating in a group than when they are doing so alone!</p>
<p>In the model</p>
<p><span class="math display">\[
\text{candy bars} = b_0 + b_1(\text{anonymity}) + b_2(\text{group}) + b_3(\text{anonymity} \times \text{group})
\]</span></p>
<p>The interaction term <span class="math inline">\(b_3\)</span> is going to be the estimated adjustment to the difference between alone vs group for anonymous vs identifiable children. Put another way, it is how the difference between red and blue dots changes between the left and right hand side of <a href="#fig-i.catcat">Figure&nbsp;5</a>.</p>
</section>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="fitting-interactions-in-r" class="level1">
<h1>Fitting interactions in R</h1>
<p>In R, the interaction term gets denoted by a colon <code>:</code> between the two predictor variables. We can fit an interaction term in a regression model quite easily in R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we don't *need* to put the 1, it's up to you :)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x1<span class="sc">:</span>x2, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This maps to the model equation we saw earlier:</p>
<p><span class="math display">\[
y = b_0 + b_1(x_1) + b_2(x_2) + b_3(x_1 \cdot x_2) + \epsilon
\]</span></p>
<div class="rtip">
<p><strong>Shortcut</strong></p>
<p>To express <code>x1 + x2 + x1:x2</code>, we can also use just <code>x1*x2</code>.</p>
<p>These two models are equivalent:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x1<span class="sc">:</span>x2, <span class="at">data =</span> dataset)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1<span class="sc">*</span>x2, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="imp">
<p>If we fit the interaction <code>x1:x2</code>, we almost <em>always</em> want to also fit the separate effects <code>x1</code> and <code>x2</code>.</p>
<p><em>“Except in special circumstances, a model including a product term for interaction between two explanatory variables should also include terms with each of the explanatory variables individually, even though their coefficients may not be significantly different from zero. Following this rule avoids the logical inconsistency of saying that the effect of <span class="math inline">\(x_1\)</span> depends on the level of <span class="math inline">\(x_2\)</span> but that there is no effect of <span class="math inline">\(x_1\)</span>.”</em> <a href="https://www.cengage.uk/c/the-statistical-sleuth-3e-ramsey-schafer/9781133490678/" target="_blank">Ramsey &amp; Schafer</a></p>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="interpretation" class="level1">
<h1>Interpretation</h1>
<p>When we include an interaction term in our model, we are saying that two effects on the outcome are <em>dependent upon</em> one another. This means that with an interaction in the model <code>lm(y ~ x1 + x2 + x1:x2)</code> we can no longer talk about the “effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span><em>‘holding <span class="math inline">\(x_2\)</span> constant’</em>”. Instead we have to talk about <em>conditional effects</em> - e.g.&nbsp;the effect of <span class="math inline">\(x_1\)</span> <em>at a <strong>specific</strong> value</em> of <span class="math inline">\(x_2\)</span>.</p>
<div class="sticky">
<p>The individual coefficients for each predictor that is involved in an interaction are estimated <em>when the other predictor in the interaction is zero.</em></p>
</div>
<p>For example:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2 + x1:x2, data = df)
...
Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  70.6259     1.1442  61.727  &lt; 2e-16 ***
x1            2.6987     0.9933   2.717  0.00782 ** 
x2            2.3835     1.0151   2.348  0.02092 *  
x1:x2        -1.7513     0.8306  -2.108  0.03759 *  </code></pre>
</div>
</div>
<p>These coefficients are interpreted, in turn as:</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>(Intercept)</code></td>
<td>the estimated <span class="math inline">\(y\)</span> when all predictors (<span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>) are zero is 70.63</td>
</tr>
<tr class="even">
<td><code>x1</code></td>
<td><strong>when <span class="math inline">\(x_2\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_1\)</span> is associated with a 2.7 change in <span class="math inline">\(y\)</span></td>
</tr>
<tr class="odd">
<td><code>x2</code></td>
<td><strong>when <span class="math inline">\(x_1\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_2\)</span> is associated with a 2.38 change in <span class="math inline">\(y\)</span>.</td>
</tr>
<tr class="even">
<td><code>x1:x2</code></td>
<td>as <span class="math inline">\(x_2\)</span> increases by 1, the association between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span> changes by -1.75<br><em><strong>or</strong></em><br>as <span class="math inline">\(x_1\)</span> increases by 1, the association between <span class="math inline">\(x_2\)</span> and <span class="math inline">\(y\)</span> changes by -1.75</td>
</tr>
</tbody>
</table>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">What if there are other things in the model too?</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p>Note that the interaction <code>x1:x2</code> changes how we interpret the individual coefficients for <code>x1</code> and <code>x2</code>.</p>
<p>It does <strong><em>not</em></strong> change how we interpret coefficients for other predictors that might be in our model.</p>
<p>For example, suppose we <em>also</em> had another predictor <span class="math inline">\(c_1\)</span> in our model:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ c1 + x1 + x2 + x1:x2, data = df)
...
Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  70.6645     1.1081  63.772  &lt; 2e-16 ***
c1            3.2889     1.2112   2.715  0.00786 ** 
x1            2.6653     0.9619   2.771  0.00673 ** 
x2            2.4604     0.9834   2.502  0.01406 *  
x1:x2        -1.7984     0.8045  -2.235  0.02773 *  </code></pre>
</div>
</div>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>(Intercept)</code></td>
<td>the estimated <span class="math inline">\(y\)</span> when all predictors (<span class="math inline">\(c_1\)</span>, <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>) are zero is 70.66</td>
</tr>
<tr class="even">
<td><code>c1</code></td>
<td>a 1 unit increase in <span class="math inline">\(c_1\)</span> is associated with a 3.29 increase in <span class="math inline">\(y\)</span>, holding constant all other variables in the model (<span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>)</td>
</tr>
<tr class="odd">
<td><code>x1</code></td>
<td>holding <span class="math inline">\(c_1\)</span> constant, <strong>when <span class="math inline">\(x_2\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_1\)</span> is associated with a 2.67 change in <span class="math inline">\(y\)</span></td>
</tr>
<tr class="even">
<td><code>x2</code></td>
<td>holding <span class="math inline">\(c_1\)</span> constant, <strong>when <span class="math inline">\(x_1\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_2\)</span> is associated with a 2.46 change in <span class="math inline">\(y\)</span>.</td>
</tr>
<tr class="odd">
<td><code>x1:x2</code></td>
<td>holding <span class="math inline">\(c_1\)</span> constant, as <span class="math inline">\(x_2\)</span> increases by 1, the association between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span> changes by -1.8<br><em><strong>or</strong></em><br>holding <span class="math inline">\(c_1\)</span> constant, as <span class="math inline">\(x_1\)</span> increases by 1, the association between <span class="math inline">\(x_2\)</span> and <span class="math inline">\(y\)</span> changes by -1.8</td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
<p><br><br></p>
<div class="panelset">
<section id="example-1-2" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-1-2">Example 1</h4>
<blockquote class="blockquote">
<p>The amount to which spending time with my partner influences my wellbeing <em>depends on</em> the quality of our relationship.</p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>partnertime <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_partnertime.csv"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>eg1mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> partner_time <span class="sc">*</span> relationship_qual, <span class="at">data =</span> partnertime)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(eg1mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ partner_time * relationship_qual, data = partnertime)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.5592 -0.5559  0.1243  0.8884  3.2944 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    14.413160   2.192467   6.574 1.75e-08 ***
partner_time                   -1.405842   0.293737  -4.786 1.28e-05 ***
relationship_qual              -0.055658   0.036693  -1.517    0.135    
partner_time:relationship_qual  0.044363   0.004862   9.124 1.14e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.281 on 56 degrees of freedom
Multiple R-squared:  0.9377,    Adjusted R-squared:  0.9343 
F-statistic: 280.8 on 3 and 56 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>For someone who spends 0 hours with their partner, and who has a relationship quality score of 0, their estimated wellbeing is 14.41.<br>
</li>
<li>For someone who has a relationship quality score of 0, every hour spent with their partner is associated with a -1.41 change in wellbeing.<br>
</li>
<li>For someone who spends 0 hours with their partner, an increase of 1 in the relationship quality is associated with a -0.06 change in wellbeing.<br>
</li>
<li>For every 1 increase in relationship quality, an extra hour spent with their partner is associated with an <em>additional</em> 0.04 change in wellbeing.</li>
</ul>
</section>
<section id="example-2-2" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-2-2">Example 2</h4>
<blockquote class="blockquote">
<p>The influence of air-pollution on cognitive functioning <em>depends on</em> your genetic status.</p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>airpol <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_airpol.csv"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>eg2mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(mmse <span class="sc">~</span> aqpi <span class="sc">*</span> apoe4, <span class="at">data =</span> airpol)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(eg2mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mmse ~ aqpi * apoe4, data = airpol)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8225 -1.0241  0.2269  0.9554  3.8932 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   28.128929   0.642991  43.747  &lt; 2e-16 ***
aqpi          -0.016474   0.002930  -5.623 6.18e-07 ***
apoe4pos      -3.297908   0.904448  -3.646 0.000584 ***
aqpi:apoe4pos -0.014635   0.004405  -3.322 0.001578 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.674 on 56 degrees of freedom
Multiple R-squared:  0.8344,    Adjusted R-squared:  0.8255 
F-statistic: 94.06 on 3 and 56 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>For people who are APOE4 negative (the reference level, see <a href="08a_mlr.html#multiple-categories-multiple-regression" target="_blank">8A#multiple-categories-multiple-regression</a>), living where the Air Quality Pollution Index is 0 (no pollution), the estimated score on the MMSE (mini mental state exam) is 28.13.<br>
</li>
<li>For people who are APOE4 negative, a 1 unit increase in air pollution is associated with a -0.02 change in MMSE scores.<br>
</li>
<li>For people living with 0 air pollution, being APOE4 positive is associated with -3.3 lower MMSE scores compared to APOE4 negative</li>
<li>Compared to APOE4 negative, being APOE4 positive is associated with -0.01 greater decrease in MMSE scores for every 1 increase in air pollution.</li>
</ul>
</section>
<section id="example-3-2" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-3-2">Example 3</h4>
<blockquote class="blockquote">
<p>The influence of being anonymous on childrens’ greedy behaviours <em>depends on</em> if they are alone or part of a group.</p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_candy.csv"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>eg3mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(candybars <span class="sc">~</span> anonymity <span class="sc">*</span> asgroup, <span class="at">data =</span> candy)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(eg3mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = candybars ~ anonymity * asgroup, data = candy)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.9000 -0.3636  0.0000  0.9444  1.9444 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                         10.0556     0.2236  44.974  &lt; 2e-16 ***
anonymityidentifiable               -2.0556     0.3047  -6.746 9.08e-09 ***
asgroupgroup                         3.8444     0.3741  10.276 1.69e-14 ***
anonymityidentifiable:asgroupgroup  -4.4808     0.5144  -8.711 5.31e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9486 on 56 degrees of freedom
Multiple R-squared:  0.8548,    Adjusted R-squared:  0.847 
F-statistic: 109.9 on 3 and 56 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>An anonymous child trick or treating alone is estimated to take 10 candybars.</li>
<li>When trick or treating alone, compared to an anonymous child, an identifiable child is estimated to take -2 fewer candybars.<br>
</li>
<li>When anonymous, compared to an trick or treating alone, children who are part of a group are estimated to take 4 more candybars.<br>
</li>
<li>When children trick or treat as part of a group, the difference between identifiable and anonymous children’s candybar taking is -4 fewer than the difference between identifiable and anonymous children who trick or treat alone.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(y<span class="sc">~</span>x1<span class="sc">*</span>x2,catcat <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(x1<span class="sc">:</span>x2,factor)))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_model</span>(fit, <span class="at">type=</span><span class="st">"int"</span>,<span class="at">show.data=</span>T)<span class="sc">+</span><span class="fu">geom_line</span>()</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># it's just viewing that cube from one side </span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scatterplot3d)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>plt <span class="ot">&lt;-</span> <span class="fu">with</span>(catcat,<span class="fu">scatterplot3d</span>(x1,x2,y, <span class="at">scale.y=</span>.<span class="dv">8</span>,<span class="at">angle=</span><span class="sc">-</span><span class="dv">30</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">x.ticklabs =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="cn">NA</span>,<span class="cn">NA</span>,<span class="cn">NA</span>,<span class="cn">NA</span>,<span class="dv">1</span>), </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">y.ticklabs =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="cn">NA</span>,<span class="cn">NA</span>,<span class="cn">NA</span>,<span class="cn">NA</span>,<span class="dv">1</span>), </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">main=</span><span class="st">"y~x1*x2</span><span class="sc">\n</span><span class="st">(x1 and x2 are categorical)"</span>))</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(y<span class="sc">~</span>x1<span class="sc">*</span>x2,catcat)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">x1=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,.<span class="dv">1</span>), <span class="at">x2=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,.<span class="dv">1</span>))</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>pp<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, pp)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>pp1 <span class="ot">&lt;-</span> pp[pp<span class="sc">$</span>x2<span class="sc">==</span><span class="dv">0</span>,]</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>pp2 <span class="ot">&lt;-</span> pp[pp<span class="sc">$</span>x2<span class="sc">==</span><span class="dv">1</span>,]</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>pp3 <span class="ot">&lt;-</span> pp[pp<span class="sc">$</span>x1<span class="sc">==</span><span class="dv">0</span>,]</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>pp4 <span class="ot">&lt;-</span> pp[pp<span class="sc">$</span>x1<span class="sc">==</span><span class="dv">1</span>,]</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>plt<span class="sc">$</span><span class="fu">points</span>(pp1<span class="sc">$</span>x1,pp1<span class="sc">$</span>x2,pp1<span class="sc">$</span>y,<span class="at">type=</span><span class="st">"l"</span>)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>plt<span class="sc">$</span><span class="fu">points</span>(pp2<span class="sc">$</span>x1,pp2<span class="sc">$</span>x2,pp2<span class="sc">$</span>y,<span class="at">type=</span><span class="st">"l"</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>plt<span class="sc">$</span><span class="fu">points</span>(pp3<span class="sc">$</span>x1,pp3<span class="sc">$</span>x2,pp3<span class="sc">$</span>y,<span class="at">type=</span><span class="st">"l"</span>)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>plt<span class="sc">$</span><span class="fu">points</span>(pp4<span class="sc">$</span>x1,pp4<span class="sc">$</span>x2,pp4<span class="sc">$</span>y,<span class="at">type=</span><span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="visualisation" class="level1">
<h1>Visualisation</h1>
<p>We have seen lots of 3-dimensional plots above to try and help in building our intuition about how we model an interaction. However, we typically don’t really want to visualise models like this (in part because our models often have more than 2 predictors, and so have more than 3 dimensions).</p>
<p>What we therefore need to do is find ways to represent these relationships in 2-dimensional plots. This is slightly different depending on the type of variables we are dealing with.</p>
<ul>
<li>For a continuous <span class="math inline">\(\times\)</span> categorical interaction, we can plot the association of the continuous predictor with the outcome for each level of the categorical variable.</li>
<li>For a continuous <span class="math inline">\(\times\)</span> continuous interaction, we can plot the association of one predictor at some judiciously chosen values of the other (e.g.&nbsp;at the min, mean and max, or at -1 SD, mean, and +1 SD).<br>
</li>
<li>For a categorical <span class="math inline">\(\times\)</span> categorical interaction, we can plot the various group means, with optional dotted<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> lines to illustrate the non-parallelism</li>
</ul>
<p>Fortunately, we can do a lot of this with a variety of useful packages, such as:</p>
<ul>
<li>From the <strong>sjPlot</strong> package: <code>plot_model(model, type = "int")</code> or `plot_model(model, type = “eff”, terms = c(“x1”,“x2”))<br>
</li>
<li>From the <strong>interactions</strong> package: <code>interact_plot(model, pred = "x1", modx = "x2")</code>, and <code>cat_plot()</code></li>
</ul>
<div class="panelset">
<section id="example-1-3" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-1-3">Example 1</h4>
<blockquote class="blockquote">
<p>The amount to which spending time with my partner influences my wellbeing <em>depends on</em> the quality of our relationship.</p>
</blockquote>
<p>Plotting continuous by continuous interactions requires choosing a set of values for one of our predictors, at which we plot the slope of the other.<br>
By default, the <code>plot_model</code> function chooses to show <code>y~x1</code> when x2 is at its min and max.<br>
The interactions package defaults to showing the <code>y~x1</code> relationship when x2 is at -1 SD below the mean, at the mean, and +1 SD above the mean.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>partnertime <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_partnertime.csv"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>eg1mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> partner_time <span class="sc">*</span> relationship_qual, <span class="at">data =</span> partnertime)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(eg1mod, <span class="at">type =</span> <span class="st">"int"</span>) <span class="sc">/</span> </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(eg1mod, <span class="at">pred =</span> <span class="st">"partner_time"</span>, <span class="at">modx =</span> <span class="st">"relationship_qual"</span>, <span class="at">interval =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>We can change these manually, for instance. For instance, to make <code>plot_model</code> show the association when relationship quality is zero, when it is 50, and when it is 100, we could use:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(eg1mod, <span class="at">type =</span> <span class="st">"eff"</span>, <span class="at">terms=</span><span class="fu">c</span>(<span class="st">"partner_time"</span>,<span class="st">"relationship_qual [0, 50, 100]"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="example-2-3" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-2-3">Example 2</h4>
<blockquote class="blockquote">
<p>The influence of air-pollution on cognitive functioning <em>depends on</em> your genetic status.</p>
</blockquote>
<p>This is the most straightforward type of interaction to visualise, as there are only a set number of values that one of the variables can take, meaning only a finite number of lines we need to draw:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>airpol <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_airpol.csv"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>eg2mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(mmse <span class="sc">~</span> aqpi <span class="sc">*</span> apoe4, <span class="at">data =</span> airpol)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(eg2mod, <span class="at">type =</span> <span class="st">"int"</span>) <span class="sc">/</span> </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(eg2mod, <span class="at">pred =</span> <span class="st">"aqpi"</span>, <span class="at">modx =</span> <span class="st">"apoe4"</span>, <span class="at">interval =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="example-3-3" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-3-3">Example 3</h4>
<blockquote class="blockquote">
<p>The influence of being anonymous on childrens’ greedy behaviours <em>depends on</em> if they are alone or part of a group.</p>
</blockquote>
<p>For these types of interactions (between categorical variables), plotting the estimates from our model is best done as our set of group means. This what functions like <code>plot_model()</code> and <code>cat_plot()</code> will do!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_candy.csv"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>eg3mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(candybars <span class="sc">~</span> anonymity <span class="sc">*</span> asgroup, <span class="at">data =</span> candy)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(eg3mod, <span class="at">type =</span> <span class="st">"int"</span>) <span class="sc">/</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat_plot</span>(eg3mod, <span class="at">pred =</span> <span class="st">"anonymity"</span>, <span class="at">modx =</span> <span class="st">"asgroup"</span>, <span class="at">interval =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">

</div>
</section>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="getting-more-from-your-model" class="level1">
<h1>Getting more from your model</h1>
<p>Reporting on interactions is a bit like telling a story. Listing the interpretation of the coefficients is fine, but often reads a bit awkwardly. A good presentation of the results would provide the reader with the overall pattern of results, pulling out the key parts that are of interest. There are various things we can do to get out coefficients that might be of more use to us in telling our story.</p>
<section id="mean-centering" class="level2">
<h2 class="anchored" data-anchor-id="mean-centering">Mean Centering</h2>
<p>By mean centering a continuous predictor, we change what “0” means. Normally, when we don’t have an interaction, this simply changes the intercept value. If we have the interaction <code>y ~ x1 + x2 + x1:x2</code>, then mean centering <code>x1</code> will make the coefficient for <code>x2</code> now represent “the association between <span class="math inline">\(x_2\)</span> and <span class="math inline">\(y\)</span> for someone at the <em>average</em> of <span class="math inline">\(x_1\)</span>”.</p>
<p>Using one of our examples from throughout this reading, we might mean-center the air-pollution so that we can consider the difference in MMSE scores between APOE4 positive and negative people <em>at the average air-pollution level</em></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>airpol <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_airpol.csv"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># make a new variable that is mean centered air pollution</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>airpol <span class="ot">&lt;-</span> airpol <span class="sc">%&gt;%</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">aqpiC =</span> aqpi <span class="sc">-</span> <span class="fu">mean</span>(aqpi)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># model with original variable</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>eg2mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(mmse <span class="sc">~</span> aqpi <span class="sc">*</span> apoe4, <span class="at">data =</span> airpol)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># model with mean centered predictor</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>eg2mod_cent <span class="ot">&lt;-</span> <span class="fu">lm</span>(mmse <span class="sc">~</span> aqpiC <span class="sc">*</span> apoe4, <span class="at">data =</span> airpol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># coefficients:</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(eg2mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)          aqpi      apoe4pos aqpi:apoe4pos 
  28.12892936   -0.01647447   -3.29790816   -0.01463533 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(eg2mod_cent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept)          aqpiC       apoe4pos aqpiC:apoe4pos 
   25.16379896    -0.01647447    -5.93202402    -0.01463533 </code></pre>
</div>
</div>
<p>This is because the coefficient for APOE4 compares the heights of the two lines when the other predictor is zero. So if we change what “zero” represents, we can change what that estimates. In the model plots below, we can see that <em>the model doesn’t change</em>, it is just extracting different information (it is the distance to move from the blue dot to the red dot):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="releveling-factors" class="level2">
<h2 class="anchored" data-anchor-id="releveling-factors">Releveling Factors</h2>
<p>Another thing that can be useful (especially when working with categorical variables with lots of levels) is to make sure your variables are <code>factors</code> in R, and to set a useful reference level. Typically, the reference level is what we think of as “normal”, e.g.&nbsp;if we have 3 groups: Placebo, Drug A, and Drug B, then we might compare each drug to the placebo condition, because that’s comparable to most people (i.e.&nbsp;who aren’t taking the drug).</p>
<p>For example, when we have two categorical variables:</p>
<ul>
<li>anonymity = “anonymous” vs “identifiable”</li>
<li>asgroup = “alone” vs “group”</li>
</ul>
<p>Then the default is to take the alphabetical ordering. We can change the ordering using functions that “relevel” a factor. Note, this only works if the variable is <em>already</em> a <code>factor</code> in R (see <a href="02a_measurement.html#categorical" target="_blank">2A#categorical</a> for a reminder of ‘factors’).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_candy.csv"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># make both predictors 'factors'</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  candy <span class="sc">%&gt;%</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">anonymity =</span> <span class="fu">factor</span>(anonymity),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">asgroup =</span> <span class="fu">factor</span>(asgroup)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once they are factors, we can see the default levels:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(candy<span class="sc">$</span>anonymity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "anonymous"    "identifiable"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(candy<span class="sc">$</span>asgroup)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "alone" "group"</code></pre>
</div>
</div>
<p>This is the original model, with the default levels:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>eg3mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(candybars <span class="sc">~</span> anonymity <span class="sc">*</span> asgroup, <span class="at">data =</span> candy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s relevel anonymity to have “identifiable” as the first level.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  candy <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">anonymity =</span> <span class="fu">fct_relevel</span>(anonymity, <span class="st">"identifiable"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(candy<span class="sc">$</span>anonymity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "identifiable" "anonymous"   </code></pre>
</div>
</div>
<p>And refit the model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>eg3mod_rel <span class="ot">&lt;-</span> <span class="fu">lm</span>(candybars <span class="sc">~</span> anonymity <span class="sc">*</span> asgroup, <span class="at">data =</span> candy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the coefficients:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(eg3mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       (Intercept)              anonymityidentifiable 
                         10.055556                          -2.055556 
                      asgroupgroup anonymityidentifiable:asgroupgroup 
                          3.844444                          -4.480808 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(eg3mod_rel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    (Intercept)              anonymityanonymous 
                      8.0000000                       2.0555556 
                   asgroupgroup anonymityanonymous:asgroupgroup 
                     -0.6363636                       4.4808081 </code></pre>
</div>
</div>
<p>Again, the model doesn’t change, we are simply extracting different bits from it:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/unnamed-chunk-32-2.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<div class="sticky">
<p><strong>Mapping model estimates to model plots</strong></p>
<p>To help with interpretation of the estimated coefficients from a model, a very useful exercise is to try and map them to what we see in our model plots (as seen above).</p>
<p>As models get more complex, there is a very important distinction to make between plotting the data, and plotting the model estimates. Whereas previously we could plot a simple regression <code>lm(y~x)</code> by plotting the <em>data</em> and adding <code>geom_smooth(method=lm)</code>, now that we are working with multiple regression in order to visualise our results we should think of it as plotting the <em>model</em> (and we can add the data if desired).</p>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
</section>
<section id="optional-extra-getting-non-linear" class="level1">
<h1>Optional Extra: Getting non-linear</h1>
<p>You might be noticing that when we start talking about our regression surface “twisting” (e.g.&nbsp;in <a href="#fig-i.contcont">Figure&nbsp;3</a>), we’re starting to see curves in our model.</p>
<p>We can model <em>curves</em> in a “linear” model!?</p>
<p>An interaction does in a sense introduce non-linearity to our thinking, because there we no longer think of a linear effect of <span class="math inline">\(x_1\)</span> (it “depends on” <span class="math inline">\(x_2\)</span>). This a little bit of a trick, because ultimately our model is still linear - we are estimating our outcome <span class="math inline">\(y\)</span> as the <em>linear combination</em> of a set of predictors. In the model <span class="math inline">\(y = b_0 + b_1(x_1) + b_2(x_2) + b_3(x_1 \cdot x_2)\)</span>, the adjustment that we make <span class="math inline">\(b_3\)</span> to each of the coefficients <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> is a constant.</p>
<p>We can even exploit this to model more clearly “non-linear” associations, such as the age and height example below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-nonlin" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09a_interactions_files/figure-html/fig-nonlin-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6: Two linear models, one with a quadratic term (right)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We will cover this a lot more in the multivariate stats course, so don’t worry too much about it right now.<br>
However, it’s useful as a means of seeing how we can extend linear models to fit these sort of relationships. In the model on the right of <a href="#fig-nonlin">Figure&nbsp;6</a>, the model returns three coefficients:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 28.09831    2.88606   9.736 4.99e-16 ***
age         18.04500    0.88602  20.366  &lt; 2e-16 ***
I(age^2)    -0.71034    0.05299 -13.406  &lt; 2e-16 ***</code></pre>
</div>
</div>
<p>It is estimating a persons’ height as:</p>
<ul>
<li>an intercept of 28.1 (the estimated height of a newborn baby of age 0)</li>
<li>plus 18.04 cm for every year of age they have</li>
<li>plus -0.71 cm for every year of age they have, squared.</li>
</ul>
<p>So for a 4 year old, the estimated height is:</p>
<p><span class="math display">\[
height = 28.1 + (28.1 \times 4) + (28.1 \times 4^2) = 88.9
\]</span></p>
<p>and for a 10 year old, it is:</p>
<p><span class="math display">\[
height = 28.1 + (28.1 \times 10) + (28.1 \times 10^2) = 138.1
\]</span></p>
<p>We can see how the quadratic “<span class="math inline">\(\text{age}^2\)</span> term has a larger effect as age increases, capturing the plateauing of heights as children get older.</p>
<!-- # Optional: further exploration -->
<!-- ## Simple Slopes -->
<!-- we've kind of already done it visually.   -->
<!-- plot the slope of y~x1 for certain values of x2.   -->
<!-- we've done this visually, but it would be nice to get out a "is y~x1 significant when x2 = ?"   -->
<!-- ## Johnson Neyman -->


</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>This example comes from our lovely tutor Ian!<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>And vice versa! It is also the adjustment we make to the slope of wellbeing with “relationship quality”, as we move 1 up in “time spent with partner”<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>and this example comes from Otto!<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4" role="doc-endnote"><p>This example was suggested by Tia<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5" role="doc-endnote"><p>dotted is a good way to indicate that there is no data across that line - it is linking two categories<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>