<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - Week 10 Exercises: Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-down')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>
<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 1</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html">
 <span class="dropdown-text">1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html">
 <span class="dropdown-text">1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 2</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html">
 <span class="dropdown-text">2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html">
 <span class="dropdown-text">2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 3</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html">
 <span class="dropdown-text">3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html">
 <span class="dropdown-text">3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html">
 <span class="dropdown-text">Exercises: T-tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 4</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04a_chisq.html">
 <span class="dropdown-text">4A: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revisitnhst.html">
 <span class="dropdown-text">4B: Revisiting NHST</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_ex.html">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 5</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li>
    <a class="dropdown-item" href="./05a_covcor.html">
 <span class="dropdown-text">5A: Covariance &amp; Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_ex.html">
 <span class="dropdown-text">Exercises: Cov, Cor, Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-6" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 6</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-6">    
        <li>
    <a class="dropdown-item" href="./06_wt.html">
 <span class="dropdown-text">Walkthrough: Advanced Data Wrangling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 7</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li>
    <a class="dropdown-item" href="./07a_slr.html">
 <span class="dropdown-text">7A: Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_ex.html">
 <span class="dropdown-text">Exercises: Simple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 8</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li>
    <a class="dropdown-item" href="./08a_mlr.html">
 <span class="dropdown-text">8A: Multiple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08b_assumptdiag.html">
 <span class="dropdown-text">8B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08_ex.html">
 <span class="dropdown-text">Exercises: Multiple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 9</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li>
    <a class="dropdown-item" href="./09a_interactions.html">
 <span class="dropdown-text">9A: Interactions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09b_contrasts.html">
 <span class="dropdown-text">9B: Categorical Predictors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09_ex.html">
 <span class="dropdown-text">Exercises: Interactions</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-10" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 10</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-10">    
        <li>
    <a class="dropdown-item" href="./10a_glm.html">
 <span class="dropdown-text">10A: GLM!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10_ex.html">
 <span class="dropdown-text">Exercises: Logistic Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-11" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 11</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-11">    
        <li>
    <a class="dropdown-item" href="./11_finish.html">
 <span class="dropdown-text">Exercises</span></a>
  </li>  
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#odd-probability" id="toc-odd-probability" class="nav-link active" data-scroll-target="#odd-probability">Odd Probability</a></li>
  <li><a href="#drunkdoor" id="toc-drunkdoor" class="nav-link" data-scroll-target="#drunkdoor">Drunkdoor</a>
  <ul class="collapse">
  <li><a href="#age-effects" id="toc-age-effects" class="nav-link" data-scroll-target="#age-effects">Age effects</a></li>
  <li><a href="#tackling-the-research-question" id="toc-tackling-the-research-question" class="nav-link" data-scroll-target="#tackling-the-research-question">Tackling the research question</a></li>
  </ul></li>
  <li><a href="#dog-peoplecat-people" id="toc-dog-peoplecat-people" class="nav-link" data-scroll-target="#dog-peoplecat-people">Dog people/Cat people</a></li>
  <li><a href="#optional-extra-red-and-white" id="toc-optional-extra-red-and-white" class="nav-link" data-scroll-target="#optional-extra-red-and-white">Optional Extra: Red and White</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 10 Exercises: Logistic Regression</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="odd-probability" class="level1">
<h1>Odd Probability</h1>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<ol type="1">
<li>The probability of a coin landing on heads if 0.5, or 50%. What are the odds, and what are the log-odds?<br>
</li>
<li>Last year’s Tour de France winner, Tadej Pogacar, was given odds of 11 to 4 by a popular gambling site (i.e., if we could run the race over and over again, for every 4 he won he would lose 11). Translate this into the implied probability of him winning.</li>
</ol>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li><span class="math inline">\(odds = \frac{p}{1-p}\)</span><br>
</li>
<li>See <a href="10a_glm.html#introducing-the-glm" target="_blank">10A#introducing-the-glm</a></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-1" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')"> Solution </span>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<ol type="1">
<li><p>A 50% chance of landing on heads is equivalent to the odds of <span class="math inline">\(\frac{0.5}{(1-0.5)} = \frac{0.5}{0.5} = \frac{1}{1}\)</span> (odds of 1 to 1, i.e., “equal odds”).<br>
The log-odds can be calculated using <code>log(1)</code> in R, which returns 0.</p></li>
<li><p>If Pogacar is predicted to win 4 for every 11 he loses, then this is means he is predicted to win 4 in every 15 races, so the implied probability of him winning is <span class="math inline">\(\frac{4}{15} = 0.267\)</span>.</p></li>
</ol>
</div>
<p class="solution-end">
</p>
</section>
<section id="drunkdoor" class="level1">
<h1>Drunkdoor</h1>
<div class="frame">
<blockquote class="blockquote">
<p><strong>Research Questions</strong> Is susceptibility to change blindness influenced by level of alcohol intoxication and perceptual load?</p>
</blockquote>
<p><strong>Method</strong> Researchers conducted a study in which they approached 120 people, recruited from within the vicinity of a number of establishments with licenses to sell alcohol to be consumed on-premises. Initially, experimenter A approached participants and asked if they were interested in participating in a short study, and obtained their written consent. While experimenter A subsequently talked each participant through a set of questions on multiple pieces of paper (with the pretense of explaining what the participant was required to do), experimenters B and C carrying a door passed between the participant and experimenter A, with experimenter C replacing A (as can be viewed in the video below).</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/FWSxSQsspiQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<p><a href="https://www.cse.iitk.ac.in/users/se367/11/papers/simons-ambinder-05_change-blindness.pdf">Simons, D. J., &amp; Levin, D. T. (1997). Change blindness. Trends in cognitive sciences, 1(7), 261-267.</a></p>
<p>The perceptual load of the experiment was manipulated via a) the presentation of the door and b) the papers held by the experimenters. For 60 of these participants, the door was painted with some detailed graffiti and had a variety of pieces of paper and notices attached to the side facing the participants. Additionally, for these participants, the experimenters handled a disorganised pile of 30 papers, with the top pages covered in drawings around the printed text. For the remaining 60, the door was a standard MDF construction painted a neutral grey, and the experimenters handled only 2 sheets of paper which had minimal printed text on them and nothing else.</p>
<p><strong>Measures</strong><br>
After experimenters A and C had successfully swapped positions, the participant was asked (now by C) to complete small number of questions taking approximately 1 minute. Either after this set of questions, or if the participant made an indication that they had noticed the swap, the experimenters regrouped and the participant was explicitly asked whether they had noticed the swap.<br>
Immediately after this, participants were breathalysed, and their blood alcohol content was recorded. In addition, participants’ age was recorded, as previous research suggests that change-blindness increases with age.</p>
<p><strong>Data</strong></p>
<div class="cell" data-layout-align="center">

</div>
<p>The data can be downloaded from <a href="https://uoepsy.github.io/data/drunkdoor.csv">https://uoepsy.github.io/data/drunkdoor.csv</a>.<br>
A description of the variables included is presented below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="rfaxqekhph" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#rfaxqekhph .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#rfaxqekhph .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rfaxqekhph .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#rfaxqekhph .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#rfaxqekhph .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rfaxqekhph .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rfaxqekhph .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#rfaxqekhph .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#rfaxqekhph .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#rfaxqekhph .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#rfaxqekhph .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#rfaxqekhph .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#rfaxqekhph .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#rfaxqekhph .gt_from_md > :first-child {
  margin-top: 0;
}

#rfaxqekhph .gt_from_md > :last-child {
  margin-bottom: 0;
}

#rfaxqekhph .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#rfaxqekhph .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#rfaxqekhph .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#rfaxqekhph .gt_row_group_first td {
  border-top-width: 2px;
}

#rfaxqekhph .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rfaxqekhph .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#rfaxqekhph .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#rfaxqekhph .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rfaxqekhph .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rfaxqekhph .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#rfaxqekhph .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#rfaxqekhph .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rfaxqekhph .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rfaxqekhph .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rfaxqekhph .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rfaxqekhph .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rfaxqekhph .gt_left {
  text-align: left;
}

#rfaxqekhph .gt_center {
  text-align: center;
}

#rfaxqekhph .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#rfaxqekhph .gt_font_normal {
  font-weight: normal;
}

#rfaxqekhph .gt_font_bold {
  font-weight: bold;
}

#rfaxqekhph .gt_font_italic {
  font-style: italic;
}

#rfaxqekhph .gt_super {
  font-size: 65%;
}

#rfaxqekhph .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#rfaxqekhph .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#rfaxqekhph .gt_indent_1 {
  text-indent: 5px;
}

#rfaxqekhph .gt_indent_2 {
  text-indent: 10px;
}

#rfaxqekhph .gt_indent_3 {
  text-indent: 15px;
}

#rfaxqekhph .gt_indent_4 {
  text-indent: 20px;
}

#rfaxqekhph .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">description</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">id</td>
<td class="gt_row gt_left">Unique ID number</td></tr>
    <tr><td class="gt_row gt_left">bac</td>
<td class="gt_row gt_left">Blood Alcohol Content (BAC), A BAC of 0.0 is sober, while in the United States 0.08 is legally intoxicated, and above that is very impaired. BAC levels above 0.40 are potentially fatal.</td></tr>
    <tr><td class="gt_row gt_left">age</td>
<td class="gt_row gt_left">Age (in years)</td></tr>
    <tr><td class="gt_row gt_left">condition</td>
<td class="gt_row gt_left">Condition - Perceptual load created by distracting oject (door) and details and amount of papers handled in front of participant (Low vs High)</td></tr>
    <tr><td class="gt_row gt_left">notice</td>
<td class="gt_row gt_left">Whether or not the participant noticed the swap (Yes = 1 vs No = 0)</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</div>
<section id="age-effects" class="level2">
<h2 class="anchored" data-anchor-id="age-effects">Age effects</h2>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>To begin with, we’re going to ignore the research question, and just look at the relationship between age and whether or not participants noticed the person-switch.</p>
<p>Make a scatterplot of this relationship, and add to the plot <code>geom_smooth(method="lm")</code>. This will plot the regression line for a simple model of <code>lm(notice ~ age)</code>.</p>
<div class="hints">
<p><strong>Hint:</strong> It won’t look very nice!</p>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>drunkdoor <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/drunkdoor.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(drunkdoor, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>notice))<span class="sc">+</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10_ex_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Just visually following the line from the plot produced in the previous question, what do you think the predicted model value would be for someone who is aged 30?<br>
What does this value <em>mean</em>?</p>
<div class="hints">
<p><strong>Hint:</strong> There’s not really an answer to this.</p>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>This plot will make it easier to see that the model predicted value for someone aged 30 is approximately 1.15.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10_ex_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>What does <strong>1.15</strong> really mean here? A 30 year old participant will notice 1.15 experimenter-swaps? They have a 115% probability of noticing the swap? That is maybe closer, but we can’t have such a probability - probability is between 0 and 1.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Fit a logistic regression model investigating whether participants’ age predicts the log-odds of noticing the person they are talking to being switched out mid-conversation. Look at the <code>summary()</code> output of your model.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>To fit a logistic regression model, we need to use<code>glm()</code>, a slightly more general form of <code>lm()</code>.</li>
<li>The syntax is pretty much the same, but we need to add in a <code>family</code> at the end, to tell it that we are doing a binomial<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> logistic regression.<br>
</li>
<li>See <a href="10a_glm.html#fitting-glm-in-r" target="_blank">10A#fitting-glm-in-r</a></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(notice <span class="sc">~</span> age, <span class="at">data =</span> drunkdoor, <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span><span class="st">"logit"</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = notice ~ age, family = binomial(link = "logit"), 
    data = drunkdoor)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.3788  -0.7897   0.2578   0.8250   1.8877  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  10.2270     1.9634   5.209 1.90e-07 ***
age          -0.1819     0.0349  -5.213 1.86e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 166.06  on 119  degrees of freedom
Residual deviance: 120.28  on 118  degrees of freedom
AIC: 124.28

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Based on your model output, complete the following sentence:</p>
<p>“Being 1 year older decreases _________ by 0.18.”</p>
<div class="hints">
<p><strong>Hint:</strong> on what scale (probability, odds, log-odds) are we modelling <em>linear</em> associations?</p>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>“Being 1 year older decreases <strong>the log-odds of noticing a mid-conversation person switch</strong> by 0.18.”</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>To get this association into something that is (slightly) more easy to understand, exponentiate the coefficients from your model in order to translate them back from log-odds in to “odds ratios”. Provide an interpretation of what the resulting estimates mean.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>The opposite of the natural logarithm <code>log()</code> is the exponential <code>exp()</code>.</li>
<li>See <a href="10a_glm.html#interpretation-of-coefficients" target="_blank">10A#interpretation-of-coefficients</a></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age 
2.763972e+04 8.336732e-01 </code></pre>
</div>
</div>
<div class="int">
<ul>
<li>The odds of noticing a mid-conversation person-switch for someone age 0 is 27639:1.<br>
</li>
<li>For every year older someone is, the odds of noticing the switch are multiplied by 0.83.</li>
</ul>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Based on your answer to the previous question, calculate the odds of noticing the swap for a one year-old (for now, forget about the fact that this experiment wouldn’t work on a 1 year old!)<br>
And what about for a 40 year old?</p>
<p>Can you translate the odds back in to probabilities?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age 
2.763972e+04 8.336732e-01 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The odds of noticing a mid-conversation person-switch for someone age 0 is 27639:1.<br>
For every year older someone is, the odds of noticing decrease by 0.83.</p>
</blockquote>
<p><strong>For a one year old</strong></p>
<p>This means that for a one year old, the odds of noticing are <span class="math inline">\(27640 \times 0.83\)</span>, or more precisely <span class="math inline">\(27640 \times 0.8336732\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model1)[<span class="dv">1</span>]) <span class="sc">*</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model1)[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   23042.49 </code></pre>
</div>
</div>
<p>So the odds for a one-year old are 23042:1.</p>
<p>We can also get to this using addition on the log-odds scale:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model1)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(model1)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
    10.0451 </code></pre>
</div>
</div>
<p>and <em>then</em> exponentiating it:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">10.0451</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23042.6</code></pre>
</div>
</div>
<p><strong>For a 40 year old</strong></p>
<p>The odds for a 40 year old are <span class="math inline">\(27640 \times 0.83 \times 0.83 \times 0.83 \times 0.83 \times 0.83 \times ...\)</span> or <span class="math inline">\(27640 \times 0.83^{40}\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model1)[<span class="dv">1</span>]) <span class="sc">*</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model1)[<span class="dv">2</span>])<span class="sc">^</span><span class="dv">40</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   19.11465 </code></pre>
</div>
</div>
<p>Or using log-odds:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>( <span class="fu">coef</span>(model1)[<span class="dv">1</span>] <span class="sc">+</span> (<span class="fu">coef</span>(model1)[<span class="dv">2</span>]<span class="sc">*</span><span class="dv">40</span>) ) <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">exp</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   19.11465 </code></pre>
</div>
</div>
<p><strong>Converting to probabilities</strong></p>
<p>And we can now turn these back into probabilities.</p>
<p>Predicted probability of noticing for a one year old = <span class="math inline">\(\frac{23042.6}{1 + 23042.6} = 0.9999\)</span> Predicted probability of noticing for a 40 year old = <span class="math inline">\(\frac{19.11}{1 + 19.11} = 0.95\)</span></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>It’s possible to calculate predicted probabilities for a specific value of the predictor(s), but what would be nice is to see how the <em>probability</em> of noticing the swap changes with age.</p>
<p>The code below creates a dataframe with the variable <code>age</code> in it, which has the values 1 to 100. Can you use this object and the <code>predict()</code> function, along with your model, to calculate the predicted probabilities of the outcome (noticing the swap) for each year of age from 1 to 100?<br>
Can you then plot this?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ages100 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">age =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="hint">
<p><strong>Hints:</strong></p>
<ul>
<li><code>predict(model, newdata = ???)</code><br>
</li>
<li>try seeing what happens to the plot when you change between:
<ul>
<li><code>predict(model, newdata = ???, type = "link")</code></li>
<li><code>predict(model, newdata = ???, type = "response")</code><br>
</li>
</ul></li>
<li><a href="10a_glm.html#visualising" target="_blank">10A#visualising</a></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>This will spit out the predicted probabilities for each observation</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model1, <span class="at">newdata =</span> ages100, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s add them to the <code>ages100</code> tibble</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ages100 <span class="ot">&lt;-</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  ages100 <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">predprobs =</span> <span class="fu">predict</span>(model1, <span class="at">newdata =</span> ages100, <span class="at">type =</span> <span class="st">"response"</span>),</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">predlogodds =</span> <span class="fu">predict</span>(model1, <span class="at">newdata =</span> ages100, <span class="at">type =</span> <span class="st">"link"</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and plot them against age! We can also add those two people (the 1 year old and the 40 year old) that we were predicting in the earlier question</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ages100, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> predprobs)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"predicted probability of noticing the swap"</span>)<span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">40</span>), <span class="at">lty=</span><span class="st">"dotted"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10_ex_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Note that the <code>predict(model, type="link")</code> gives us the estimated log-odds. If we plot those:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ages100, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> predlogodds)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"predicted log-odds of noticing the swap"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10_ex_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="tackling-the-research-question" class="level2">
<h2 class="anchored" data-anchor-id="tackling-the-research-question">Tackling the research question</h2>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Recall our research question, which we will now turn to:</p>
<blockquote class="blockquote">
<p><strong>Research Questions</strong> Is susceptibility to change blindness influenced by level of alcohol intoxication and perceptual load?</p>
</blockquote>
<p>Try and make a mental list of the different relationships between variables that this question invokes, can you identify one variable as the ‘outcome’ or ‘response’ variable? (it often helps to think about the implicit direction of the relationship in the question)</p>
<p>In addition, are there known things that it might be useful to account for, so that you capture associations that are independent from differences due to these things (hint hint, what have you just been looking at?).</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<p>The question seems to ask about two relationships:</p>
<ul>
<li>susceptibility to change blindness ← alcohol intoxication<br>
</li>
<li>susceptibility to change blindness ← perceptual load</li>
</ul>
<p>and we know (from previous research, as well as our previous exercises) that change-blindness is associated with age.</p>
<p>The arrows above are used to show the <em>implied</em> direction of the influence, and in the <code>lm()/glm()</code> syntax, you could imagine each of these mapping to a formula syntax we have seen a few times (e.g., <code>t.test(outcome ~ group)</code> and <code>lm(outcome ~ predictor)</code>). We can see that the ‘susceptibility to change blindness’ is our outcome variable:</p>
<ul>
<li><code>change blindness ~ alcohol</code><br>
</li>
<li><code>change blindness ~ perceptual load</code><br>
</li>
<li>and we also have reason to think <code>change blindness ~ age</code></li>
</ul>
<p>As a general rule of thumb, it is often worth asking yourself “why run multiple models when one will do?”. Think about what we have learned about moving from simple to multiple regression - some of the explanatory power of <code>x</code> in the relationship <code>y~x</code> might be shared by the relationship <code>y~z</code>.<br>
This will depend on precisely what quantity you want to estimate, i.e., “the overall effect of <span class="math inline">\(x\)</span> on <span class="math inline">\(y\)</span> <em>ignoring <span class="math inline">\(z\)</span></em>” or “the effect of <span class="math inline">\(x\)</span> on <span class="math inline">\(y\)</span> <em>after accounting for differences due to <span class="math inline">\(y\)</span></em>”. The former statement might indicate a simple bivariate relationship, and the latter requires more advanced techniques (e.g., multiple regression).</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Think about our outcome variable and how it is measured. What type of data is it? Numeric? Categorical?</p>
<p>What type of distribution does it follow? For instance, do values vary around a central point, or fall into one of various categories, or follow the count of successes in a number of trials?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<p>Our outcome variable here is <code>drunkdoor$notice</code>, and is stored as a set of 0s and 1s. These are the only two values that an observation can take, and they represent the number of successes in n = 1 trial.</p>
<p>So, from this we learn that our method of analysis should be suited to model this binary outcome. So things like <code>lm()</code> and <code>t.test()</code> are not very suitable.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Think about our explanatory variable(s). Is there more than one? What type of variables are they? Do we want to model these together? Might they be correlated?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<p>We know that <code>drunkdoor$bac</code> is simply the observed blood alcohol level (BAC). This is technically measured as a proportion, but for the current purposes we can just treat it as any other numeric scale. However, we might consider scaling the variable so that instead of the coefficient representing the change when moving from 0% to 1% BAC (1% blood alcohol is fatal!), we might want to have the change associated with 0% to 0.01% BAC (i.e, a we want to talk about effects in terms of changing 1/100th of a percentage of BAC).</p>
<p>The <code>drunkdoor$condition</code> variable is an experimental manipulation. That is, the researchers had control over what observations fell into which group. We wouldn’t therefore expect any correlation between this and the <code>bac</code> variable (unless researchers did not allocate participants to conditions randomly).</p>
<p>As we’ve talked about already, we have the idea based on previous research that change-blindness appears to vary depending upon age. From the earlier exercises here we have some evidence to corroborate this. We may therefore want to include this in our model. If we don’t, any results might simply be due to, e.g.&nbsp;older people tending to be more highly intoxicated (and so we see an effects of alcohol that might actually be simply the effect of age).</p>
<p>We might also think about any other possible variables which might influence our results, even if we didn’t measure them. This sort of thinking becomes important in the discussion section.</p>
<div class="lo">
<p><strong>John Stuart Mill - Three Criteria for Causality</strong><br>
To varying extents, all of these criteria can be incredibly difficult to satisfy. Criteria 3 especially is one of the things that makes scientific investigation so interesting.</p>
<ol type="1">
<li>The cause precedes the effect</li>
<li>The cause is demonstrably related to the effect</li>
<li>There are no plausible alternative explanations</li>
</ol>
<p><em>Mill, J. S. (1869). A System of Logic, Ratiocinative and Inductive: Being a Connected View of the Principles of Evidence and the Methods of Scientific Investigation. Harper and brothers.</em></p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<ol type="1">
<li>Write a sentence describing the model you will fit. It might help to also describe each variable as you introduce it.<br>
</li>
<li>Fit the model.</li>
</ol>
<div class="hints">
<p><strong>Hints:</strong></p>
<p>Think of this as writing out the R code but <em>in words.</em><br>
For instance: <code>glm(outcome ~ predictor1 + predictor2 +</code> <code>Predictor1:Predictor2, family = binomial)</code> might be described as “Outcome (binary,”Level 1” vs “Level 2”) was modelled using logistic regression, predicted by Predictor1, Predictor2 and their interaction”</p>
<ul>
<li>Do you want BAC on the current scale, or could you transform it somehow?</li>
<li>Is condition a factor? What is your reference level? Have you checked <code>contrasts(drunkdoor$condition)</code>? (Remember that this will only work if you make it a factor first)</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="int">
<p>Whether or not participants noticed the swap mid-conversation (binary 0 vs 1) is modelled using logistic regression, with blood alcohol content (measured in 100th of percentages blood content) and perceptual load condition (low load vs high load, with low as the reference level) and age (in years, mean centered).</p>
</div>
<p>In the sentence above, I stated that I want blood alcohol in terms of 100ths of percentages, rather than percentages. And I want age centered on the mean (this won’t change anything other than the intercept).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>drunkdoor <span class="ot">&lt;-</span> drunkdoor <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">bac100 =</span> bac<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">ageC =</span> age <span class="sc">-</span> <span class="fu">mean</span>(age)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I also stated that the low-load will be the reference level.<br>
Currently it will be the other way around, because “high” comes before “low” in the alphabet. I can change it:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make it a factor and give it the levels in the right order</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># note this requires getting the levels named exactly as they appear in the variable. </span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># if we use lowercase "low", then every "Low" in the variable will turn to NA</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>drunkdoor<span class="sc">$</span>condition <span class="ot">&lt;-</span> <span class="fu">factor</span>(drunkdoor<span class="sc">$</span>condition, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>,<span class="st">"High"</span>))</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># check the contrasts</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(drunkdoor<span class="sc">$</span>condition)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     High
Low     0
High    1</code></pre>
</div>
</div>
<p>Finally, let’s fit our model!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>changeblind_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(notice <span class="sc">~</span> ageC <span class="sc">+</span> bac100 <span class="sc">+</span> condition, <span class="at">data =</span> drunkdoor, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(changeblind_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = notice ~ ageC + bac100 + condition, family = "binomial", 
    data = drunkdoor)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-3.0505  -0.6747   0.2138   0.6118   2.2543  

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   -0.51577    0.53536  -0.963  0.33534    
ageC          -0.22584    0.04214  -5.359 8.35e-08 ***
bac100         0.35002    0.11128   3.145  0.00166 ** 
conditionHigh -1.59215    0.54008  -2.948  0.00320 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 166.06  on 119  degrees of freedom
Residual deviance: 100.99  on 116  degrees of freedom
AIC: 108.99

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 13
</div>
<div class="question-body">
<p>Compute 95% confidence intervals for the log-odds coefficients using <code>confint()</code>. Wrap the whole thing in <code>exp()</code> in order to convert all these back into odds and odds-ratios.</p>
<p>Try the <strong>sjPlot</strong> package and using <code>tab_model(model)</code> and <code>plot_model(model, type = "est")</code> on your model. What do you get?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-13" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')"> Solution </span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(changeblind_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %     97.5 %
(Intercept)   -1.5931147  0.5259275
ageC          -0.3183866 -0.1514958
bac100         0.1438639  0.5849749
conditionHigh -2.7166875 -0.5805803</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(changeblind_model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %    97.5 %
(Intercept)   0.20329144 1.6920275
ageC          0.72732154 0.8594215
bac100        1.15472697 1.7949460
conditionHigh 0.06609332 0.5595736</code></pre>
</div>
</div>
<p>We can get out the same but in a nice little html table:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(changeblind_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">notice</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Odds Ratios</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.60</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.20&nbsp;–&nbsp;1.69</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.335</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">ageC</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.80</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.73&nbsp;–&nbsp;0.86</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">bac100</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">1.42</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">1.15&nbsp;–&nbsp;1.79</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>0.002</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">condition [High]</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.20</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.07&nbsp;–&nbsp;0.56</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>0.003</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">120</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> Tjur</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.475</td>
</tr>

</tbody></table>

</div>
</div>
<p>And the <code>plot_model</code> with <code>type = "est"</code> gives a nice little way of visualising these odds ratios and confidence intervals.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(changeblind_model, <span class="at">type =</span> <span class="st">"est"</span>) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10_ex_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 14
</div>
<div class="question-body">
<p>Write up the results of the study.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>Often when reporting odds ratios, it’s easiest to interpret them as simply “increased odds of <outcome> (OR = &lt;??&gt; [95% CI: <lower>, <upper>])”. This saves a bit of hassle too! &amp;#128516</upper></lower></outcome></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-14" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-14', 'sol-start-14')"> Solution </span>
</div>
<div id="sol-body-14" class="solution-body" style="display: none;">
<p>Whether or not participants noticed the swap mid-conversation (binary 0 vs 1) is modelled using logistic regression, with blood alcohol content (measured in 100th of percentages blood content) and perceptual load condition (low load vs high load, with low as the reference level) and age (in years, mean centered).</p>
<p>In keeping with previous research, age was associated with susceptibility to change-blindness, as indicated by a decreased odds of noting the mid-conversation swap (<span class="math inline">\(OR = 0.8 95\%\, CI\, [0.73, 0.86]\)</span>), after accounting for differences in blood alcohol levels and perceptual load. In contrary to what might be expected, change-blindness appeared to decrease with alcohol intoxication, with the odds of noticing the swap increasing 1.42 times for every 1/100th of a percentage increase in blood alcohol content (<span class="math inline">\([1.15, 1.79]\)</span>), holding age and perceptual load constant. After accounting for age and blood alcohol levels, the odds of noticing the swap were significantly different depending upon the perceptual load, with higher perceptual load associated with 0.2 (<span class="math inline">\([0.07, 0.56]\)</span>) times the odds of noticing the change.</p>
<p>Results corroborate previous findings of age increasing the susceptibility to changeblindness. Increased perceptual load was also found to increase the chances of people being blind to change, in keeping with the intuition that we have a finite capacity for attention, which is taken up more by more distracting objects. Surprisingly, levels of alcohol intoxication appeared to be associated with a greater chance of noticing change. Further work could investigate possible explanations for this association.</p>
</div>
<p class="solution-end">
</p>
</section>
</section>
<section id="dog-peoplecat-people" class="level1">
<h1>Dog people/Cat people</h1>
<div class="frame">
<p><strong>USMR 2022 Data</strong></p>
<p>The data from the USMR 2022 survey (now closed) can be found at <a href="https://uoepsy.github.io/data/usmr2022.csv">https://uoepsy.github.io/data/usmr2022.csv</a>.</p>
<p><em>note, this is the survey data just from USMR <strong>this</strong> year, not other students on other courses or in previous years</em></p>
</div>
<div class="question-begin">
Question 15
</div>
<div class="question-body">
<p>People often talk about personality differences between “cat people” and “dog people” (e.g.&nbsp;if you’re more introverted then you’re more likely to be a cat person).<br>
In our survey, we forced you to choose between “cat” and “dog”, and we also measured a bunch of personality traits from a set of 50 questions (these were aggregated up into scores for ‘extraversion’, ‘conscientiousness’, and so on).</p>
<p>Fit a model that tries to predict whether someone is a cat- or dog- person, based on aspects of their personality.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>your outcome variable is currently not 0 and 1, but “cat” and “dog”. Remember how R prefers to think of categories - as <code>factors</code>.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-15" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-15', 'sol-start-15')"> Solution </span>
</div>
<div id="sol-body-15" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>usmr <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr2022.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>make the outcome a factor</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>usmr<span class="sc">$</span>catdog <span class="ot">&lt;-</span> <span class="fu">factor</span>(usmr<span class="sc">$</span>catdog)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>we can see from the ordering of the levels that it will treat “cat” as 0 and “dog” as 1, so our model with <code>glm(catdog ~ ...)</code> will be predicted the logodds of being a dog person:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(usmr<span class="sc">$</span>catdog)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "cat" "dog"</code></pre>
</div>
</div>
<p>And we are interested in predicted dog-person-ness vs cat-person-ness by different personality traits:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>catdogmod <span class="ot">&lt;-</span> <span class="fu">glm</span>(catdog <span class="sc">~</span> extraversion <span class="sc">+</span> agreeableness <span class="sc">+</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                   conscientiousness <span class="sc">+</span> emot_stability <span class="sc">+</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                   imagination, </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data=</span>usmr, <span class="at">family=</span>binomial)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(catdogmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = catdog ~ extraversion + agreeableness + conscientiousness + 
    emot_stability + imagination, family = binomial, data = usmr)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.6406  -1.1555   0.7651   0.9902   1.6671  

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)       -3.50586    2.48706  -1.410    0.159
extraversion       0.01161    0.03221   0.360    0.719
agreeableness      0.05005    0.04472   1.119    0.263
conscientiousness  0.06285    0.04196   1.498    0.134
emot_stability     0.03074    0.02788   1.102    0.270
imagination       -0.04470    0.03748  -1.193    0.233

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 108.90  on 78  degrees of freedom
Residual deviance: 102.33  on 73  degrees of freedom
  (1 observation deleted due to missingness)
AIC: 114.33

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="statbox">
<p><strong>Using GLM to classify</strong></p>
<p>A table of predicted outcome vs observed outcome sometimes gets referred to as a <em>confusion matrix</em>, and we can think of the different cells in general terms (<a href="#fig-confmat">Figure&nbsp;1</a>).<br>
Another way to think about how our model is fitted is that it aims to maximise (TP + TN)/n, or, put another way, to minimise (FP+FN)/n.&nbsp;Which is equivalent to the good old idea of minimising sums of squares (where we minimise the extend to which the predicted values differ from the observed values).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-confmat" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/glm/cmat.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 1: Confusion Matrix</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<div class="question-begin">
Question 16
</div>
<div class="question-body">
<ol type="1">
<li>Add new column to the survey dataset which contains the predicted probability of being a cat/dog person for each observation.<br>
</li>
<li>Then, using <code>ifelse()</code>, add another column which is these predicted probabilities translated into the predicted binary outcome (0 or 1) based on whether the probability is greater than &gt;.5.<br>
</li>
<li>Create a two-way contingency table of the predicted outcome and the observed outcome.<br>
</li>
<li>What proportion of observations are correctly predicted?</li>
</ol>
<div class="hints">
<p><strong>Hint:</strong></p>
<ul>
<li>you don’t need the <code>newdata</code> argument for <code>predict()</code> if you want to use the original data the model was fitted on.<br>
</li>
<li>if there are NAs in any of the variables in your model (predictors or outcome), then the number of rows in your data will be greater than the number of model predictions.
<ul>
<li>if you want a handy function which might help with this, check out what the <strong>broom</strong> package has to offer. What does <code>augment(model, type.predict = "response")</code> do?</li>
</ul></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-16" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-16', 'sol-start-16')"> Solution </span>
</div>
<div id="sol-body-16" class="solution-body" style="display: none;">
<p>if we just try to add the predictions to the data, we get an error:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>usmr <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">predprobs =</span> <span class="fu">predict</span>(catdogmod)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in `mutate()`:
! Problem while computing `predprobs = predict(catdogmod)`.
✖ `predprobs` must be size 80 or 1, not 79.</code></pre>
</div>
</div>
<p>We <em>could</em> try making our dataset <em>“complete cases”</em> (remove all rows with any missingness), and then refit our model, and then the data and the model would all be the same number of observations.</p>
<p>However, the <strong>broom</strong> package has a really useful function which will bring us back the data that was fed into the model (i.e.&nbsp;excluding the NAs), and lots of information about the model fit itself such as predictions (<code>.fitted</code> column), residuals, and leverage etc.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(catdogmod, <span class="at">type.predict =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 79 × 13
   .rown…¹ catdog extra…² agree…³ consc…⁴ emot_…⁵ imagi…⁶ .fitted .resid .std.…⁷
   &lt;chr&gt;   &lt;fct&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
 1 1       dog         30      42      33      30      33   0.614  0.987   1.00 
 2 2       dog         34      39      36      31      33   0.641  0.943   0.956
 3 3       cat         22      44      29      27      37   0.488 -1.16   -1.20 
 4 4       cat         23      40      35      20      42   0.426 -1.05   -1.08 
 5 5       dog         16      36      31      27      40   0.371  1.41    1.46 
 6 6       dog         34      44      42      37      36   0.779  0.707   0.724
 7 7       cat         32      43      32      24      40   0.495 -1.17   -1.19 
 8 8       dog         32      35      43      16      28   0.637  0.951   1.02 
 9 9       cat         31      42      42      20      46   0.539 -1.24   -1.28 
10 10      cat         31      43      39      36      34   0.740 -1.64   -1.67 
# … with 69 more rows, 3 more variables: .hat &lt;dbl&gt;, .sigma &lt;dbl&gt;,
#   .cooksd &lt;dbl&gt;, and abbreviated variable names ¹​.rownames, ²​extraversion,
#   ³​agreeableness, ⁴​conscientiousness, ⁵​emot_stability, ⁶​imagination,
#   ⁷​.std.resid</code></pre>
</div>
</div>
<p>So we can use this to get out the observed and the predicted!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(catdogmod, <span class="at">type.predict =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">prediction =</span> <span class="fu">ifelse</span>(.fitted <span class="sc">&gt;</span>.<span class="dv">5</span>, <span class="st">"pred_dog"</span>, <span class="st">"pred_cat"</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(catdog, prediction) <span class="sc">%&gt;%</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">%&gt;%</span> prop.table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      prediction
catdog  pred_cat  pred_dog
   cat 0.2405063 0.2151899
   dog 0.1392405 0.4050633</code></pre>
</div>
</div>
<p>So 19 cat people are predicted as cat people, and 32 dog people are predicted as dog people. But 17 cat people are predicted as dog-people, and 11 dog people are predicted to be cat people.</p>
<p><span class="math display">\[
\frac{19+32}{19+32+17+11} = \frac{51}{79} = 0.65
\]</span></p>
<p>65% of observations are correctly predicted by our model.</p>
</div>
<p class="solution-end">
</p>
</section>
<section id="optional-extra-red-and-white" class="level1">
<h1>Optional Extra: Red and White</h1>
<div class="question-begin">
Question 16
</div>
<div class="question-body">
<p>People are a lot more difficult to predict than something like, say, the colour of different wines.</p>
<p>You can download a dataset of 6497 different wines (1599 red, 4898 white) from <a href="https://uoepsy.github.io/data/usmr_wines.csv">https://uoepsy.github.io/data/usmr_wines.csv</a>.</p>
<p>It contains information on various physiochemical properties such as pH, a measure of level of sulphates, residual sugar, citric acid, volatile acidity and alcohol content, and also quality ratings from a sommelier (wine expert). All the wines are vinho verde from Portugal, and the data was collected between 2004 and 2007.</p>
<p>Build a model that predicts the colour of wine based on all available information.<br>
How accurately can it predict wine colours?</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li><code>glm(outcome ~ ., data = mydata)</code> is a shorthand way of putting <em>all</em> variables in the data in as predictors.</li>
<li>Generally speaking, this question doesn’t reflect how we do research in psychology. Ideally, we would have a theoretical question that motivates the inclusion (and testing of) specific predictors.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-17" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-17', 'sol-start-17')"> Solution </span>
</div>
<div id="sol-body-17" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>wines <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_wines.csv"</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>wines<span class="sc">$</span>col <span class="ot">&lt;-</span> <span class="fu">factor</span>(wines<span class="sc">$</span>col)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>winemod <span class="ot">&lt;-</span> <span class="fu">glm</span>(col <span class="sc">~</span> ., <span class="at">data =</span> wines, <span class="at">family =</span> binomial)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(winemod, <span class="at">type.predict=</span><span class="st">"response"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred =</span> <span class="fu">ifelse</span>(.fitted<span class="sc">&gt;</span>.<span class="dv">5</span>,<span class="st">"white"</span>,<span class="st">"red"</span>)</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(col,pred) <span class="sc">%&gt;%</span> </span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prop.table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       pred
col            red      white
  red   0.20917346 0.03694013
  white 0.02616592 0.72772049</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(winemod, <span class="at">type.predict=</span><span class="st">"response"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred =</span> <span class="fu">ifelse</span>(.fitted<span class="sc">&gt;</span>.<span class="dv">5</span>,<span class="st">"white"</span>,<span class="st">"red"</span>),</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">correct =</span> <span class="fu">ifelse</span>(pred<span class="sc">==</span>col, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(correct) <span class="sc">%&gt;%</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">%&gt;%</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prop.table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>correct
         0          1 
0.06310605 0.93689395 </code></pre>
</div>
</div>
<p>93.6% accurate!</p>
</div>
<p class="solution-end">
</p>


</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>In this case it happens to be the special case of a binomial where <span class="math inline">\(n=1\)</span>, which sometimes gets referred to as ‘binary logistic regression’<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>