<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - 10A: The generalised linear model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-down')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>
<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 1</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html">
 <span class="dropdown-text">1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html">
 <span class="dropdown-text">1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 2</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html">
 <span class="dropdown-text">2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html">
 <span class="dropdown-text">2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 3</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html">
 <span class="dropdown-text">3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html">
 <span class="dropdown-text">3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html">
 <span class="dropdown-text">Exercises: T-tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 4</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04a_chisq.html">
 <span class="dropdown-text">4A: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revisitnhst.html">
 <span class="dropdown-text">4B: Revisiting NHST</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_ex.html">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 5</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li>
    <a class="dropdown-item" href="./05a_covcor.html">
 <span class="dropdown-text">5A: Covariance &amp; Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_ex.html">
 <span class="dropdown-text">Exercises: Cov, Cor, Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-6" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 6</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-6">    
        <li>
    <a class="dropdown-item" href="./06_wt.html">
 <span class="dropdown-text">Walkthrough: Advanced Data Wrangling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 7</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li>
    <a class="dropdown-item" href="./07a_slr.html">
 <span class="dropdown-text">7A: Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_ex.html">
 <span class="dropdown-text">Exercises: Simple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 8</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li>
    <a class="dropdown-item" href="./08a_mlr.html">
 <span class="dropdown-text">8A: Multiple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08b_assumptdiag.html">
 <span class="dropdown-text">8B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08_ex.html">
 <span class="dropdown-text">Exercises: Multiple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 9</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li>
    <a class="dropdown-item" href="./09a_interactions.html">
 <span class="dropdown-text">9A: Interactions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09b_contrasts.html">
 <span class="dropdown-text">9B: Categorical Predictors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09_ex.html">
 <span class="dropdown-text">Exercises: Interactions</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-10" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 10</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-10">    
        <li>
    <a class="dropdown-item" href="./10a_glm.html">
 <span class="dropdown-text">10A: GLM!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10_ex.html">
 <span class="dropdown-text">Exercises: Logistic Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-11" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 11</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-11">    
        <li class="dropdown-header">11A: Common Tests as Linear Models</li>
        <li class="dropdown-header">11B: Writing Up</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#quick-recaps" id="toc-quick-recaps" class="nav-link active" data-scroll-target="#quick-recaps">Quick recaps</a></li>
  <li><a href="#continuous-outcomes" id="toc-continuous-outcomes" class="nav-link" data-scroll-target="#continuous-outcomes">Continuous outcomes!</a></li>
  <li><a href="#other-outcomes" id="toc-other-outcomes" class="nav-link" data-scroll-target="#other-outcomes">Other outcomes</a></li>
  <li><a href="#introducing-the-glm" id="toc-introducing-the-glm" class="nav-link" data-scroll-target="#introducing-the-glm">Introducing the GLM</a></li>
  <li><a href="#fitting-glm-in-r" id="toc-fitting-glm-in-r" class="nav-link" data-scroll-target="#fitting-glm-in-r">Fitting GLM in R</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#interpretation-of-coefficients" id="toc-interpretation-of-coefficients" class="nav-link" data-scroll-target="#interpretation-of-coefficients">Interpretation of Coefficients</a></li>
  <li><a href="#inference" id="toc-inference" class="nav-link" data-scroll-target="#inference">Inference</a>
  <ul class="collapse">
  <li><a href="#visualising" id="toc-visualising" class="nav-link" data-scroll-target="#visualising">Visualising</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#comparing-models" id="toc-comparing-models" class="nav-link" data-scroll-target="#comparing-models">Comparing models</a>
  <ul class="collapse">
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">10A: The generalised linear model</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="quick-recaps" class="level1">
<h1>Quick recaps</h1>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Simple linear regression</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p>Things have moved pretty quickly in the last couple of weeks.<br>
In the simple linear regression, we defined our model through a number of components:</p>
<ul>
<li><span class="math inline">\(b_0\)</span>: the “Intercept”. This is the predicted value of <span class="math inline">\(y\)</span> where <span class="math inline">\(x = 0\)</span>. In the plot below, it is the predicted value of wellbeing where outdoor_time is 0 (where the regression line cuts the y-axis)</li>
<li><span class="math inline">\(b_1\)</span>: the “Coefficient for <span class="math inline">\(x\)</span>”. This is the predicted <em>increase</em> in <span class="math inline">\(y\)</span> for every unit increase of <span class="math inline">\(x\)</span>. In the plot below, this is the amount the regression line goes up for every one unit we move across.<br>
</li>
<li><span class="math inline">\(\varepsilon\)</span>: the “Residuals” or “Error term”. These are the distances from each of our observed values to the model predicted values. The standard deviation of all these gets denoted <span class="math inline">\(\sigma_\varepsilon\)</span>. In the plot below, these are the vertical distances from each red dot to the black line.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-2" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-2', 'opt-start-2')"> <span class="olab">Multiple linear regression</span></span>
</div>
<div id="opt-body-2" class="optional-body" style="display: none;">
<p>When we extended this to multiple regression, we essentially just added more explanatory variables, meaning we fitted more coefficients.</p>
<p>The values of <span class="math inline">\(y\)</span> are now modelled as some relationship of more than just one <span class="math inline">\(x\)</span> variable.</p>
<p>In the plot below with two predictors, we would have a coefficient for each one, showing the slope of the regression surface along each dimension.</p>
<p>The residuals continue to be the distances from the observed values to our model predicted values. In the plot below, these are the vertical distances from each red dot to the surface.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-3" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-3', 'opt-start-3')"> <span class="olab">Interactions</span></span>
</div>
<div id="opt-body-3" class="optional-body" style="display: none;">
<p>We then saw how we can let the relationships between the outcome <span class="math inline">\(y\)</span> and an explanatory variable <span class="math inline">\(x1\)</span> vary <em>as a function of</em> some other explanatory variable <span class="math inline">\(x2\)</span>.</p>
<p>In the plot below, if someone asks you “what is the relationship between <span class="math inline">\(x1\)</span> and <span class="math inline">\(x\)</span>, your reply should (hopefully) be ‘it depends on what the value of <span class="math inline">\(x2\)</span> is’</p>
<p>This is captured in the curvature of the regression surface below, and we estimate it with a combination of 3 coefficients:</p>
<ol type="1">
<li>the association between <span class="math inline">\(x1\)</span> and <span class="math inline">\(y\)</span> where <span class="math inline">\(x2=0\)</span><br>
(this is the slope of the surface where it meets the <strong>front</strong> face of the cube)<br>
</li>
<li>the association between <span class="math inline">\(x2\)</span> and <span class="math inline">\(y\)</span> where <span class="math inline">\(x1=0\)</span><br>
(this is the slope of the surface where it meets the <strong>left</strong> of face of the cube)<br>
</li>
<li>the amount to which <strong>1.</strong> and <strong>2.</strong> are adjusted when there is an increase in the other variable.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-4" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-4', 'opt-start-4')"> <span class="olab">Categorical explanatory variables</span></span>
</div>
<div id="opt-body-4" class="optional-body" style="display: none;">
<p>Throughout these, we also saw how this applied when we had explanatory variables that were <strong>categorical</strong>.</p>
<p>They were entered in to the model as a set of “dummy variables” (zeroes and ones), representing differences between groups. If we had a categorical variable which contained <span class="math inline">\(k\)</span> levels (or “groups”, or “categories”), then we R will put <span class="math inline">\(k-1\)</span> dummy variables into the model for us, and we will get out <span class="math inline">\(k-1\)</span> coefficients.</p>
<p>The default behaviour in R is that, depending on what we set as our <strong>reference level</strong>, the coefficients represent the difference from this group to each of the others.<br>
In the plots below, if “Group1” is the reference, then the coefficient <code>groupGroup2</code> would represent the vertical distance from the red line to the green line, and the coefficient <code>groupGroup3</code> would be the vertical distance from the red line to the blue line.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><em>Note - because categorical predictors are coded as various dummy variables of zeroes and ones, the assumption of linearity is intrinsically there. The only possible way to get from the red line to the green line is via a straight line.</em></p>
<p>We also saw how this same logic applies when categorical explanatory variables are involved in an interaction, as in <a href="#fig-catintglm">Figure&nbsp;1</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-catintglm" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/glm/catint.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 1: https://uoepsy.github.io/usmr/2223/lectures/lecture_9.html#62</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The coefficients provide:</p>
<ol type="1">
<li>coefficient for practice: the increase in ‘reading age’ associated with an increase of 1 unit of ‘practice’, when the dummy variables for ‘method’ are all 0
<ul>
<li>(Where the reference level is <em>phonics</em>, this is the slope of the red line)</li>
</ul></li>
<li>the coefficient for methodWord: the change in ‘reading age’ associated with the move from the reference level <em>phonics</em> to <em>word</em>, when ‘practice’ = 0.
<ul>
<li>(This is the distance between the two lines where they meet the y-axis).<br>
</li>
</ul></li>
<li>the coefficient for the interaction: the adjustment to 1 and 2 associated with an increase of 1 in other variable (which for the categorical variable means the move to the other group).</li>
</ol>
</div>
<p class="optional-end">
</p>
</section>
<section id="continuous-outcomes" class="level1">
<h1>Continuous outcomes!</h1>
<p>In all of the models thus far, we have been dealing with outcomes variables that are <em>continuous</em>. These are variables for which an observation can take <em>any</em> real value - i.e.&nbsp;3.4, or 1.50365, or 0.000532. We might not have have measured these variables with any degree of accuracy, but the models we have been fitting have fundamentally assumed this.</p>
<p>For instance, even if our outcome is the “sleep quality rating” from our class survey, measured in whole numbers from 0 to 100, our model predictions will be values that are much more specific, and my model predicted sleep quality might be 36.54374. This is because we are modelling a continuous line through the sleep quality ratings. This also means that the model extends to scores of from negative to positive infinity (<span class="math inline">\(- \infty &lt; y &lt; \infty\)</span>), even though we know our scale is bounded at 0 and 100 (see <a href="#fig-sleepqualzoom">Figure&nbsp;2</a>).</p>
<p>Often, this is a perfectly acceptable thing to do, especially when we consider the outcome variable to be measuring a continuous thing (e.g.&nbsp;sleep quality), just hindered by the precision of measurement, and when the bounds of our measurement tool are not preventing us from capturing variation (e.g.&nbsp;if everyone rates sleep as 100, there is no variance to explain).</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>usmr <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr2022.csv"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(usmr, <span class="fu">aes</span>(<span class="at">x =</span> loc, <span class="at">y =</span> sleeprating)) <span class="sc">+</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm) <span class="sc">+</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"our model"</span>) <span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(usmr, <span class="fu">aes</span>(<span class="at">x =</span> loc, <span class="at">y =</span> sleeprating)) <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm) <span class="sc">+</span> </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">50</span>,<span class="dv">50</span>) <span class="sc">+</span> </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"our model (zoomed out)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-sleepqualzoom" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/fig-sleepqualzoom-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 2: Our sleep quality ~ loc model is a continuous line extending infinitely</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="other-outcomes" class="level1">
<h1>Other outcomes</h1>
<p>There are lots of variables that we collect that don’t fit with this way of thinking. For instance, what if we want to model something that takes the form of a <strong>binary variable:</strong><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<ul>
<li>being Y vs not being Y<br>
</li>
<li>Y happening vs Y not happening</li>
</ul>
<p>For binary variables, values can only take one of two values, which we often encode as 0 or 1. Values can’t be 0.5, -2, or 1.3, they can <em>only</em> be 0 or 1.</p>
<p>Another type of outcome that we can’t really model as continuous is <strong>count variable</strong>:</p>
<ul>
<li>The number of Y’s</li>
<li>How many times Y happened</li>
</ul>
<p>For count data, values can’t take <em>any</em> real number, they can only take integers (0, 1, 2, 3, …).</p>
<div class="frame">
<p><strong>An example</strong></p>
<p>At a lake, I survey 120 people who have just finished fishing for the day. I’m interested in how the length of time they spent fishing is associated with:</p>
<ol type="1">
<li>how tired they are from 0 to 100 (continuous)</li>
<li>catching <em>any</em> fish (binary, 1 = yes, 0 = no)</li>
<li>the number of fish caught (count)</li>
</ol>
<p>We can try at first to visualise all these relationships as scatterplots (<a href="#fig-outcomeplots">Figure&nbsp;3</a>).</p>
<p>We can happily model our first outcome, tiredness, with a linear model. In <a href="#fig-outcomeplots">Figure&nbsp;3</a> (top panel), we can see that the relationship looks linear, and the residuals are spread fairly consistently above and below the fitted line.</p>
<p>For the binary outcome however (middle panel), there are a couple of things that are problematic. For someone who spends 8 hours fishing, the model estimates approximately <strong>1.1</strong> “catching any fish”. But what does that 1.1 really mean? Does it mean that if I fish 8 hours I will have 1.1 fish? no, because it’s not a count. Does it mean there is a 110% probability of catching fish? This is closer, but again it doesn’t make much sense - how can we have a probability of 115%?</p>
<p>For the count variable (bottom panel), we can also see that the standard <code>lm</code> model looks problematic. Again it estimates values we simply <em>cannot</em> have (it looks like if i spend 1 hour fishing I will catch about negative 3 fish?). Another thing to note is that the variance in the points on the y axis tends to increase as we get higher. This is typical of count data - we’re going to see lots of people catching 0, 1 or 2 fish, and so the “people catching few fish” are all quite close (in number of fish) to one another, but because fewer people catch 20 fish, 30 fish etc, there is a lot more variability in “number of fish” when we get higher up. This is a problem for a linear model, which assumes <em>constant variance</em> across the fitted model.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>fish <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/fishing_exped.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fish, <span class="fu">aes</span>(<span class="at">x =</span> hours, <span class="at">y =</span> tiredness)) <span class="sc">+</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"How tired are you (0 - 100)"</span>) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fish, <span class="fu">aes</span>(<span class="at">x =</span> hours, <span class="at">y =</span> caught_any)) <span class="sc">+</span> </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Did you catch any fish?"</span>) <span class="sc">+</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">1.2</span>),<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="fl">1.2</span>,.<span class="dv">2</span>))</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fish, <span class="fu">aes</span>(<span class="at">x =</span> hours, <span class="at">y =</span> n_fish)) <span class="sc">+</span> </span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"How many fish did you catch?"</span>) <span class="sc">+</span> </span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">/</span> p2 <span class="sc">/</span> p3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-outcomeplots" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/fig-outcomeplots-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 3: Three different outcomes: continuous (top), binary (middle), count (bottom)</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="introducing-the-glm" class="level1">
<h1>Introducing the GLM</h1>
<p>To deal with these sorts of outcome variable, we need to learn about the <strong>Generalised Linear Model (GLM)</strong>.</p>
<p>The GLM involves a little bit of trickery, in which we translate something that is inherently not linear (e.g.&nbsp;the <em>probability</em> of Y, or the increase in numbers of Y) into something which is both linear and unbounded, and model that instead.</p>
<p>The problem, fundamentally, is that probability is not linear. We think of it as getting ever and ever closer, but never reaching - 0 and 1 (<a href="#fig-plotprobab">Figure&nbsp;4</a>)</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plotprobab" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/fig-plotprobab-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 4: As x increases, probability of y gets closer and closer (but never meets) 1</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>To use our linear toolbox for probability, we can’t think in terms of modelling how <span class="math inline">\(x\)</span> influences the probability of <span class="math inline">\(y\)</span> <em>directly</em>, but we can model it in terms of how it influences the “log-odds of <span class="math inline">\(y\)</span>”. The same is true for count data: instead of modelling counts directly, we can model the log of the counts.</p>
<div class="statbox">
<p><strong>Probability, odds, and log-odds</strong></p>
<p>If we let <span class="math inline">\(p\)</span> denote the probability of a given event, then:</p>
<ul>
<li><span class="math inline">\(\frac{p}{(1-p)}\)</span> are the odds of the event happening.<br>
For example, the odds of rolling a 6 with a normal die is 1/5 (sometimes this is expressed ‘1:5’, and in gambling the order is sometimes flipped and you’ll see ‘5/1’ or ‘odds of five to one’).<br>
If we ever need to convert between the two:
<ul>
<li><span class="math inline">\(odds = \frac{p}{(1-p)}\)</span><br>
</li>
<li><span class="math inline">\(p = \frac{odds}{1 + odds}\)</span><br>
</li>
</ul></li>
<li><span class="math inline">\(ln(\frac{p}{(1-p)})\)</span> are the log-odds of the event.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plodd" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/fig-plodd-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure 5: Probability, Odds, and Log-Odds</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="sticky">
<p><strong>Conversions</strong></p>
<p>Between probabilities, odds and log-odds (“logit”):</p>
<p>$$ <span class="math display">\[\begin{align}
&amp;\text{for probability of Y for observation i:}\\
\qquad \\
odds_i &amp; = \frac{p_i}{1-p_i} \\
\qquad \\
logit_i &amp;= log(odds_i) = log(\frac{p_i}{1-p_i}) \\
\qquad \\
p_i &amp; = \frac{odds_i}{1 + odds_i} = \frac{e^{logit_i}}{(1+e^{logit_i})}

\end{align}\]</span> $$</p>
</div>
<p><strong>Counts and log-counts</strong><br>
We can apply the same log transformation to count data in order to think about how we might consider an association on a linear</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-clcnt" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/fig-clcnt-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6: counts and log(counts)</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-5" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-5', 'opt-start-5')"> <span class="olab">Optional: What are logarithms?</span></span>
</div>
<div id="opt-body-5" class="optional-body" style="display: none;">
<div class="sticky">
<p><strong>Essentials of logarithms</strong></p>
<p>A logarithm is a mathematical way to write any positive number as a power of a “base number”.</p>
</div>
<div class="frame">
<p><strong>Log base 10</strong></p>
<p>Consider the base number 10. The R function implementing the logarithm base 10 is <code>log10()</code>.</p>
<ul>
<li>To what power do I need to raise the base number 10 in order to obtain the desired number 100?</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">100</span>  <span class="co"># 100 = 10^2</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>pow <span class="ot">&lt;-</span> <span class="fu">log10</span>(x)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>pow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>log10(100) = 2 as we need to raise 10 to the power of 2 in order to obtain the desired number 100.</p>
<ul>
<li>To what power do I need to raise the base number 10 in order to obtain the desired number 1000?</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1000</span>  <span class="co"># 1000 = 10^3</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>pow <span class="ot">&lt;-</span> <span class="fu">log10</span>(x)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>pow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>log10(1000) = 3 as we need to raise 10 to the power of 3 in order to obtain the desired number 1000.</p>
<p>Note that you can use this to write any desired number as a power of 10. For example, to which power do we raise 10 in order to obtain 13.5?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fl">13.5</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pow <span class="ot">&lt;-</span> <span class="fu">log10</span>(x)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>pow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.130334</code></pre>
</div>
</div>
<p>In fact, 10^1.130334 = 13.5 (up to rounding error)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span><span class="sc">^</span>pow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.5</code></pre>
</div>
</div>
<p>An important property is that:</p>
<p><span class="math display">\[10^{\log_{10}(x)} = x\]</span></p>
<p>For example, <span class="math inline">\(10^{\log_{10}(100)} = 10^{2} = 100\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span><span class="sc">^</span><span class="fu">log10</span>(<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100</code></pre>
</div>
</div>
</div>
<div class="frame">
<p><strong>Log base e (aka natural logarithm)</strong></p>
<p>A special number in mathematics is Euler’s (or Napier’s) number <span class="math inline">\(e = 2.718282\)</span>. As well as a logarithm in base 10, telling us which power to raise the base 10 to, in order to obtain a desired number, we can also use any other bases such as <span class="math inline">\(e\)</span>.</p>
<p>In R, you obtain Euler’s number as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="dv">1</span>)  <span class="co"># obtain the e number</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>e</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.718282</code></pre>
</div>
</div>
<p>The logarithm with base number <span class="math inline">\(e\)</span> is implemented in the R function <code>log()</code>.</p>
<ul>
<li>To which number do I need to raise <span class="math inline">\(e\)</span> in order to obtain 8?</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>pow <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="dv">8</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>pow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.079442</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>e<span class="sc">^</span>pow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p>Up to rounding error, you see that you get 8 back.</p>
<p>To not have rounding errors, save the full result:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>pow <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="dv">8</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>e<span class="sc">^</span>pow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p>An important property is that:</p>
<p><span class="math display">\[e^{\log(x)} = x\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>e<span class="sc">^</span><span class="fu">log</span>(<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<p><br></p>
<p>This little trick allows us to be able to talk about <em>linear</em> associations between predictors and the <em>log-odds of an event</em>, or between predictors and <em>log-counts</em>. In <a href="#fig-plodd">Figure&nbsp;5</a>, and <a href="#fig-clcnt">Figure&nbsp;6</a> above, we can see that by talking in terms of log-odds, or log-counts, we can model something that is linear and unbounded. So when we think about these models, what we are really have in mind is that we are capturing the associations seen in the right hand plots of <a href="#fig-plodd">Figure&nbsp;5</a> and <a href="#fig-clcnt">Figure&nbsp;6</a>.</p>
<div class="sticky">
<p><strong>The Generalised Linear Model</strong></p>
<p>In its general form, the GLM looks pretty similar to the standard LM.<br>
we can write it as:</p>
<p><span class="math display">\[
\color{green}{g(\color{red}{y})} = \mathbf{\color{blue}{b_0 + b_1(x_1) + ... + b_k(x_k)} }
\]</span></p>
<p>The difference is that <span class="math inline">\(\color{green}{g}\)</span> is a function (like log, or logit) that links the expected value of <span class="math inline">\(\color{red}{y}\)</span> to the linear prediction of <span class="math inline">\(\color{blue}{b_0 + b_1(x_1) + ... + b_k(x_k)}\)</span>.</p>
</div>
<p><br></p>
</section>
<section id="fitting-glm-in-r" class="level1">
<h1>Fitting GLM in R</h1>
<p>In order to fit these models in R, we need to use the <code>glm()</code> function. This is (unexpectedly) a generalised form of the <code>lm()</code> function we have been using. The only difference is that we need to also tell the function the <code>family</code> of the response variable, and the “link function” (the mapping we use to get from the thing we want to model to the thing we <em>actually</em> model, e.g.&nbsp;<code>"log"</code>, or <code>"logit"</code> (log-odds)).</p>
<div class="sticky">
<p><strong>Linear Regression</strong><br>
Outcome <span class="math inline">\(y\)</span> is continuous <span class="math inline">\(y \in (-\infty, \infty)\)</span></p>
<p><span class="math display">\[
\color{red}{y} = \mathbf{\color{blue}{b_0 + b_1(x_1) + ... + b_k(x_k)}}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>linear_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(continuous_y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> ... xk, <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>As it happens, <code>lm()</code> is just a special case of this, where we use the “gaussian” family (Gaussian is another term for ‘normal’), with the “identity” link function (the identity function is just saying ‘model y directly’):</em></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glm</span>(continuous_y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> ... xk, <span class="at">data =</span> df,</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">family =</span> <span class="fu">gaussian</span>(<span class="at">link =</span> <span class="st">"identity"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="sticky">
<p><strong>Logistic Regression</strong><br>
Outcome <span class="math inline">\(y\)</span> is binary, <span class="math inline">\(y \in [0,1]\)</span></p>
<p><span class="math display">\[
\begin{align}
\color{red}{ln \left( \frac{p}{1-p} \right) } &amp;= \mathbf{\color{blue}{b_0 + b_1(x_1) + ... + b_k(x_k)}} \\
\qquad \\
\text{where } \color{red}{p} &amp;= \text{probability of event }y\\
\end{align}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>logistic_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(binary_y <span class="sc">~</span>  <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> ... xk, <span class="at">data =</span> df,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span><span class="st">"logit"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>family = binomial</code> and <code>family = "binomial"</code> will also work.</li>
<li>the outcome can either be 0s and 1s, or coded as a <code>factor</code> with 2 levels.</li>
</ul>
<div class="optional-begin">
<span id="opt-start-6" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-6', 'opt-start-6')"> <span class="olab">Binomial? Binary?</span></span>
</div>
<div id="opt-body-6" class="optional-body" style="display: none;">
<p>The “binomial” distribution, which is used to represent the number of successes in a sequence of <span class="math inline">\(n\)</span> independent trials (e.g.&nbsp;number of heads in 20 coin-flips follows a binomial distribution, see <a href="https://uoepsy.github.io/usmr/2223/lectures/lecture_4.html#10" target="_blank">Lecture 4!</a>).<br>
A binary response is a special case of this, where <span class="math inline">\(n = 1\)</span>.</p>
<p>The logistic regression model, more generally, can be written as:</p>
<p><span class="math display">\[
\begin{align}
\color{red}{ln \left( \frac{p}{1-p} \right) } &amp;= \mathbf{\color{blue}{b_0 + b_1(x_1) + ... + b_k(x_k)}} \\
\qquad \\
\text{where } Y &amp;\sim Binomial(n, \color{red}{p})\\
\end{align}
\]</span></p>
</div>
<p class="optional-end">
</p>
</div>
<div class="sticky">
<p><strong>Poisson Regression</strong><br>
Outcome <span class="math inline">\(y\)</span> is positive <span class="math inline">\(y \in (0, \infty)\)</span></p>
<p><span class="math display">\[
\color{red}{ln (y) } = \mathbf{\color{blue}{b_0 + b_1(x_1) + ... + b_k(x_k)}}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(count_y <span class="sc">~</span>  <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> ... xk, <span class="at">data =</span> df,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">family=</span><span class="fu">poisson</span>(<span class="at">link=</span><span class="st">"log"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>family = poisson</code> and <code>family = "poisson"</code> will also work</li>
</ul>
</div>
<div class="optional-begin">
<span id="opt-start-7" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">Optional: A tangent: Model estimation</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p><strong>Maximum Likelihood Estimation</strong></p>
<p>For a linear regression, R has been fitting our regression models by “minimising the residual sums of squares” (i.e., we rotate the line to find the point at which <span class="math inline">\(\sum{(y - \hat{y})^2}\)</span> is smallest. This gave us the “best fitting line” (<a href="#fig-resslineplot">Figure&nbsp;7</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-resslineplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/glm/ss.png" class="img-fluid figure-img" style="width:60.0%"></p>
<p></p><figcaption class="figure-caption">Figure 7: https://uoepsy.github.io/usmr/2223/lectures/lecture_7.html#34</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>For the generalized linear models we can’t do this. For instance, in logistic regression model, what we’re really wanting is the “best fitting <em>squiggle</em>” (<a href="#fig-loglineplot">Figure&nbsp;8</a>), and to get to this we must do something else other than looking at our residuals <span class="math inline">\(y - \hat{y}\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-loglineplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/fig-loglineplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 8: Probability of Y across values of X</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The reason we have to do something different is because for our actual observations, the event has either happened or it hasn’t. So we can’t take the raw data as “probabilities” which we can translate into log-odds. We can try, but it doesn’t make sense, and we would just be trying to fit some line between infinity and negative infinity (<a href="#fig-mlelogodd">Figure&nbsp;9</a>). This would mean the residuals would also all be infinity, and so it becomes impossible to work out anything!</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  observed odds  log_odds
  &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;   
1 0        0     -Inf    
2 1        Inf   Inf     
3 ...      ...   ...     </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mlelogodd" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/fig-mlelogodd-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 9: In the log-odds world, comparing our predicted values to observed values of -Inf and Inf isn’t very useful, because all those distances will be infinite (there is no way of measuring the dotted lines, so we can’t really use them)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Instead, <strong>maximum likelihood estimation</strong> is used to find the set of coefficients which best reproduce the observed data.<br>
To do this, the computer considers loads of different lines, trying to slowly converge on the one which <em>increases the likelihood of the data</em>.</p>
<p>To understand this a bit better, let’s take consider one possible line in the probability world. The left-hand plot of <a href="#fig-mleprob">Figure&nbsp;10</a> is the same line as the one shown in <a href="#fig-mlelogodd">Figure&nbsp;9</a>, and we can see it translated back into probabilities in the right-hand plot, so that we have a predicted probability of the outcome for each datapoint. From the right-hand plot, we can then ask “what is the likelihood of the data, given this line?”. To get this, we multiply up all the probabilities that observed 1s are predicted as 1s and that observed 0s predicted as 0s.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mleprob" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/fig-mleprob-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure 10: Note - the dotted lines are not residuals, but just to show the projections of observations down to the line</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>As an example <a href="#fig-mleprob2">Figure&nbsp;11</a> shows the predicted probabilities for a couple of datapoints. The furthest left point is an observed 0, and so the likelihood of this data given the predicted probability is 1-0.12, or 0.88. The furthest right is an observed 1, so the likelihood of this is 0.98. This means the probability of seeing those two datapoints, given the line we have, is 0.98 * 0.88. But what we want is the probability of seeing <em>all</em> our data, given this line. So we need to do this for <em>all</em> of the datapoints.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Once we have this, we can compare the likelihood of all of seeing this data for a whole range of different lines.</p>
<p>The cool thing is that computers do all this for us. <em>Maximum likelihood estimation</em> is just a method to find out which parameters maximise the likelihood of the data. In our context, it tells us what values of coefficients in <span class="math inline">\(\color{red}{ln\left(\frac{p}{1-p} \right)} = \color{blue}{\beta_0 \cdot{} 1 + \beta_1 \cdot{} X_1 }\)</span> maximise the likelihood of reproducing the data we observed.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mleprob2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/fig-mleprob2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 11: Note - the dotted lines are not residuals, but just to show the projections of observations down to the line</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<p><br><br></p>
</section>
<section id="logistic-regression" class="level1">
<h1>Logistic Regression</h1>
<div class="lo">
<p>For the remainder of this reading, we’re going to leave discussions of Poisson regression and focus on working with binary outcomes using logistic regression, which you are much more likely to encounter in your reading/research. A lot of the logic of these models transfers across to when we work with count data, but <strong>you will <em>not</em> need poisson regression for any assignment on this course.</strong></p>
</div>
<p>Let’s return to our fishing example, and fit a model in which we predict “having caught some fish” by the number of hours spent fishing.</p>
<p>Practically, speaking, this quite straightforward. We have a binary outcome (1 = caught fish, 0 is didn’t catch fish), so we’ll fit a logistic regression. We have a single predictor, which is “hours spent fishing”:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fish <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/fishing_exped.csv"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>fishmod <span class="ot">&lt;-</span> <span class="fu">glm</span>(caught_any <span class="sc">~</span> hours, <span class="at">data =</span> fish,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span><span class="st">"logit"</span>))</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fishmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = caught_any ~ hours, family = binomial(link = "logit"), 
    data = fish)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.7450  -0.8866   0.2910   0.8161   1.8381  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -2.3567     0.5322  -4.428 9.50e-06 ***
hours         0.6704     0.1377   4.870 1.12e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 165.15  on 119  degrees of freedom
Residual deviance: 127.70  on 118  degrees of freedom
AIC: 131.7

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<section id="interpretation-of-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-of-coefficients">Interpretation of Coefficients</h2>
<p>An important result of our model capturing the linear associations between the predictors and the <strong>log-odds of outcome Y</strong>, is that our coefficients are all in these units.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fishmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = caught_any ~ hours, family = binomial(link = "logit"), 
...
Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -2.3567     0.5322  -4.428 9.50e-06 ***
hours         0.6704     0.1377   4.870 1.12e-06 ***</code></pre>
</div>
</div>
<ul>
<li><code>(Intercept)</code>: the log-odds of having caught some fish when spending zero hours fishing are -2.36.<br>
</li>
<li><code>hours</code> coefficient: for every hour someone has spent fishing, the log-odds of them having caught some fish increase by 0.67.</li>
</ul>
<p>If you’re anything like me, these are not the most useful interpretations. I have no idea what increasing 0.67 log-odds means in real terms. What we can do instead is translate these back into odds, which might make things easier. The opposite of the natural <strong>logarithm</strong> is the <strong>exponential</strong> (see <a href="https://mathonweb.com/help_ebook/functions.htm#functions_3" target="_blank">here</a> if you’re interested). We can turn <span class="math inline">\(log(x)\)</span> back into <span class="math inline">\(x\)</span> by raising <span class="math inline">\(e\)</span> to the power of it: <span class="math inline">\(e^{\log(x)} = x\)</span>. In R, this is just the two functions <code>log()</code> and <code>exp()</code>: <code>exp(log(2)) == 2</code>.</p>
<p>This means we can turn our <em>log-odds</em> back into <em>odds</em> by using <code>exp()</code> on our coefficients! A crucial thing to note is that <em>addition</em> on the log-odds scale is the same as <em>multiplication</em> on the odds scale. A coefficient on the log-odds scale is interpreted the same way as we interpret normal linear regression coefficients: <em>“if you go up 1 on X you add <code>b</code> on log-odds(Y)”</em>. When we convert these coefficients to odds using <code>exp()</code>, the interpretation becomes <em>“if you go up 1 on X, your odds are <strong>multiplied</strong> by <code>exp(b)</code>”.</em></p>
<p>We can see our exponentiated coefficients here:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(fishmod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       hours 
 0.09473306  1.95504622 </code></pre>
</div>
</div>
<p>The intercept is now the odds of having caught a fish when spending zero hours fishing: 0.09.</p>
<p>Because our intercept is at a single point (it’s not an <em>association</em>), we can actually convert this to a probability. Remember that <span class="math inline">\(odds = \frac{p}{1-p}\)</span>, which means that <span class="math inline">\(p = \frac{odds}{1 + odds}\)</span>. So the probability of catching a fish if I spend zero hours fishing is <span class="math inline">\(\frac{0.09}{1 + 0.09} = 0.08\)</span>.</p>
<p>Unfortunately, we can’t do the same for any of the slope coefficients. This is because changes in odds are not the same for different levels of probability.</p>
<div class="optional-begin">
<span id="opt-start-8" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-8', 'opt-start-8')"> <span class="olab">quick demonstration</span></span>
</div>
<div id="opt-body-8" class="optional-body" style="display: none;">
<p>Consider how when we multiply odds by 2, the increase in probability is not constant:</p>
<table class="table">
<thead>
<tr class="header">
<th>Odds</th>
<th>Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.5</td>
<td><span class="math inline">\(\frac{1}{1+0.5} = 0.33\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\(\frac{1}{1+1} = 0.5\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\(\frac{2}{1+2} = 0.66\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\(\frac{4}{1+4} = 0.8\)</span></td>
</tr>
<tr class="odd">
<td>8</td>
<td><span class="math inline">\(\frac{8}{1+8} = 0.88\)</span></td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
<p>Our best interpretation of our coefficient for <code>hours</code> is simply that for every hour someone has spent fishing, the odds of them having caught some fish are <em>multiplied</em> by 1.96.</p>
<div class="sticky">
<p><strong>Odds Ratios</strong></p>
<p>When we exponentiate coefficients from a model fitted to the log-odds, the resulting association is referred to as an “odds ratio” (OR).</p>
<p>For every 1 unit increase in <span class="math inline">\(x\)</span>:</p>
<ul>
<li>“the odds of <span class="math inline">\(y\)</span> change by <em>a ratio</em> of <code>exp(b)</code>”<br>
</li>
<li>“the odds of <span class="math inline">\(y\)</span> are multiplied by <code>exp(b)</code>”<br>
</li>
<li>“there are <code>exp(b)</code> increased/decreased odds of <span class="math inline">\(y\)</span>”</li>
</ul>
<p>Instead of thinking of a coefficient of 0 as indicating “no association”, in odds ratios this when the OR = 1.</p>
<ul>
<li><strong>OR = 1</strong> : equal odds (<span class="math inline">\(1 \times odds = odds \text{ don't change}\)</span>).</li>
<li><strong>OR &lt; 1</strong> : decreased odds (<span class="math inline">\(0.5 \times odds = odds \text{ are halved}\)</span>)</li>
<li><strong>OR &gt; 1</strong> : increased odds (<span class="math inline">\(2 \times odds = odds \text{ are doubled}\)</span>)</li>
</ul>
<p><img src="images/danger.svg" style="width:30px;"> <small><small> Often you will hear people interpreting OR as “<span class="math inline">\(y\)</span> is <code>exp(b)</code> times as likely to occur”.<br>
Although it is true that increased odds is increased likelihood of <span class="math inline">\(y\)</span> occurring. Double the odds does not mean you will see <em>twice</em> as many occurrences of <span class="math inline">\(y\)</span> (see the “I still don’t really get odds” box below). </small></small></p>
</div>
<div class="optional-begin">
<span id="opt-start-9" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-9', 'opt-start-9')"> <span class="olab">I still don’t really get odds.. </span></span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p>Even talking in odds and multiplying odds can be frustratingly confusing, so here’s a little more step-by-step explanation to try and help:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="ldpfmoimjj" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ldpfmoimjj .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ldpfmoimjj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ldpfmoimjj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ldpfmoimjj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ldpfmoimjj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ldpfmoimjj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ldpfmoimjj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ldpfmoimjj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ldpfmoimjj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ldpfmoimjj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ldpfmoimjj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ldpfmoimjj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ldpfmoimjj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ldpfmoimjj .gt_from_md > :first-child {
  margin-top: 0;
}

#ldpfmoimjj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ldpfmoimjj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ldpfmoimjj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ldpfmoimjj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ldpfmoimjj .gt_row_group_first td {
  border-top-width: 2px;
}

#ldpfmoimjj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ldpfmoimjj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ldpfmoimjj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ldpfmoimjj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ldpfmoimjj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ldpfmoimjj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ldpfmoimjj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ldpfmoimjj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ldpfmoimjj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ldpfmoimjj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ldpfmoimjj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ldpfmoimjj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ldpfmoimjj .gt_left {
  text-align: left;
}

#ldpfmoimjj .gt_center {
  text-align: center;
}

#ldpfmoimjj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ldpfmoimjj .gt_font_normal {
  font-weight: normal;
}

#ldpfmoimjj .gt_font_bold {
  font-weight: bold;
}

#ldpfmoimjj .gt_font_italic {
  font-style: italic;
}

#ldpfmoimjj .gt_super {
  font-size: 65%;
}

#ldpfmoimjj .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#ldpfmoimjj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ldpfmoimjj .gt_indent_1 {
  text-indent: 5px;
}

#ldpfmoimjj .gt_indent_2 {
  text-indent: 10px;
}

#ldpfmoimjj .gt_indent_3 {
  text-indent: 15px;
}

#ldpfmoimjj .gt_indent_4 {
  text-indent: 20px;
}

#ldpfmoimjj .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">term</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">b</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">exp(b)</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">(Intercept)</td>
<td class="gt_row gt_right">-2.36</td>
<td class="gt_row gt_right">0.09</td></tr>
    <tr><td class="gt_row gt_left">hours</td>
<td class="gt_row gt_right">0.67</td>
<td class="gt_row gt_right">1.96</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
<ol type="1">
<li>For people spending just 1 hour fishing, the log-odds of them having caught fish are -2.36 + 0.67 = -1.69.<br>
</li>
<li>Translating this to odds, we exponentiate it, so the odds of them having caught fish are <span class="math inline">\(e^{(-2.36 + 0.67)} = e^{-1.69} = 0.19\)</span>.<br>
(This is the same<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> as <span class="math inline">\(e^{-2.36} \times e^{0.67}\)</span>)<br>
</li>
<li>These odds of 0.19 equate to approximately <span class="math inline">\(\frac{1}{5}\)</span>, which means that if we take 6 people who have each spent 1 hour fishing, we expect 1 of them to have caught fish, and 5 of them to have not caught anything.<br>
</li>
<li>If we consider how the odds increase for every hour spent fishing (i.e.&nbsp;for those spending <strong>2</strong> hours fishing as opposed to just 1):
<ul>
<li>the log-odds of catching fish increase by 0.67.<br>
</li>
<li>the odds of catching fish are multiplied by 1.96.<br>
</li>
<li>so for 2 hours of fishing, the odds are <span class="math inline">\(0.19 \times 1.96 = 0.36\)</span>.<br>
(And we can also calculate this as <span class="math inline">\(e^{-1.69 + 0.67}\)</span>)<br>
</li>
</ul></li>
<li>So these new odds of 0.36 for 2 hours fished are 1.96 times greater than the odds of 0.19 for 1 hour fished. For ease, let’s just round 1.96 to 2 and say that the odds have doubled.<br>
What does this mean? It means we’ve gone from odds of <span class="math inline">\(\frac{1}{5}\)</span> to <span class="math inline">\(\frac{2}{5}\)</span>. This doesn’t mean we’ll now see 2 out of 6 people catching fish. It means we’ll see 2 out of 7 (<a href="#fig-fishing">Figure&nbsp;12</a>).</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-fishing" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/glm/fishing.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure 12: Increasing from odds of 1/5 to 2/5</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section>
<section id="inference" class="level2">
<h2 class="anchored" data-anchor-id="inference">Inference</h2>
<div class="statbox">
<p><strong>Coefficient Tests</strong></p>
<p>You might notice that the summary output of our logistic regression model has <span class="math inline">\(z\)</span> statistics instead of <span class="math inline">\(t\)</span> statistics. For logistic regression, the distribution of the estimated coefficients gets close and closer to a Normal distribution as the sample size gets larger. All of the tests are based on the hypothesis that the sample size is large enough<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> to justify a normal approximation.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fishmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -2.3567     0.5322  -4.428 9.50e-06 ***
hours         0.6704     0.1377   4.870 1.12e-06 ***</code></pre>
</div>
</div>
<p>The logic of the tests remains the same as it was for the linear model, where it is a test against the null hypothesis that the coefficient is zero. Or, less formally, we can think of the corresponding p-value as “in the null universe where there is no relationship between <span class="math inline">\(x\)</span> and the occurrence of event <span class="math inline">\(y\)</span>, there is a <code>p-value</code> chance of seeing a sample of this size with an association as strong as the one we have got”</p>
<div class="int">
<p>For every hour more someone spent fishing, the odds of them catching a fish increased by 1.96 (<span class="math inline">\(z = 4.87\)</span>, <span class="math inline">\(p &lt; .001\)</span>).</p>
</div>
</div>
<div class="statbox">
<p><strong>Confidence Intervals</strong><br>
As previously, we can obtain confidence intervals using the <code>confint()</code> function. Because confidence intervals are just lower and upper bounds for a range of plausible values for our estimates, we can turn these into the confidence intervals around our odds ratios!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(fishmod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) 0.03102087 0.2534272
hours       1.52614259 2.6275396</code></pre>
</div>
</div>
<div class="int">
<p>For every hour more someone spent fishing, the odds of them catching a fish increased by 1.96 (95% CI [1.53 - 2.63]).</p>
</div>
</div>
<section id="visualising" class="level3">
<h3 class="anchored" data-anchor-id="visualising">Visualising</h3>
<p>While interpreting coefficients leaves us in speaking in the realm of odds-ratios, we can do more with visualisations! This is because we can simply display the predicted probability across values of some predictor. We don’t have to try and rely solely on a numerical description of a relationship - a picture speaks a thousand words (and it’s a lot easier!)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(fishmod, <span class="at">type =</span> <span class="st">"eff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$hours</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-10" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-10', 'opt-start-10')"> <span class="olab">Optional: making plots manually</span></span>
</div>
<div id="opt-body-10" class="optional-body" style="display: none;">
<p>to make plots manually, we need to give our model some new data to predict values for, and then plot those predictions!<br>
For these models, we can actually predict on various different scales (e.g.&nbsp;do we want to predict log-odds values (<code>predict(mod, type="link")</code>) or probabilities (<code>predict(mod, type="response")</code>)?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>plotdata <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># make hours a sequence of length 50, from 0 to 10</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">hours =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="at">length.out =</span> <span class="dv">50</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="co"># add the predcted probabilities</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>plotdata <span class="ot">&lt;-</span> </span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  plotdata <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob =</span> <span class="fu">predict</span>(fishmod, <span class="at">newdata =</span> plotdata, <span class="at">type =</span> <span class="st">"response"</span>),</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the predicted probabilities</span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plotdata, <span class="fu">aes</span>(<span class="at">x =</span> hours, <span class="at">y =</span> prob)) <span class="sc">+</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the intervals is much trickier, but essentially requires computing the upper and lower bounds on the log-odds scale and then converting them back:</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>plotdata <span class="ot">&lt;-</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  plotdata <span class="sc">%&gt;%</span> </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">logodd =</span> <span class="fu">predict</span>(fishmod, <span class="at">newdata =</span> plotdata, <span class="at">type =</span> <span class="st">"link"</span>),</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="fu">predict</span>(fishmod, <span class="at">newdata =</span> plotdata, <span class="at">type =</span> <span class="st">"link"</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>se,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">logoddlower =</span> logodd <span class="sc">-</span> (<span class="fl">1.96</span><span class="sc">*</span>se),</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">logoddupper =</span> logodd <span class="sc">+</span> (<span class="fl">1.96</span><span class="sc">*</span>se),</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob =</span> fishmod<span class="sc">$</span>family<span class="sc">$</span><span class="fu">linkinv</span>(logodd),</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> fishmod<span class="sc">$</span>family<span class="sc">$</span><span class="fu">linkinv</span>(logoddlower),</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> fishmod<span class="sc">$</span>family<span class="sc">$</span><span class="fu">linkinv</span>(logoddupper)</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plotdata, <span class="fu">aes</span>(<span class="at">x =</span> hours, <span class="at">y =</span> prob)) <span class="sc">+</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>lower,<span class="at">ymax=</span>upper), <span class="at">alpha=</span>.<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-44-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section>
</section>
</section>
<section id="comparing-models" class="level1">
<h1>Comparing models</h1>
<p>When moving from linear regression to more advanced and flexible models, testing of goodness of fit is more often done by comparing a model of interest to a simpler one. The only caveat is that the two models need to be <strong>nested</strong>, i.e.&nbsp;one model needs to be a simplification of the other, and all predictors of one model needs to be within the other.</p>
<p>To compare models, we test the difference in <strong>deviance</strong>.</p>
<div class="sticky">
<p><strong>Deviance</strong></p>
<p>Deviance is a measure of deviation/discrepancy/mismatch between the data and the model. You can think of it as a generalisation of the terms making up the residual sum of squares in simple linear regression, in that it measures the misfit, or <em>badness of fit</em>. This means (as it was for the residual sum of squares) that smaller deviance is better!</p>
<p>More technically, deviance is calculated as -2 times the log-likelihood.</p>
<ul>
<li>Likelihood = <span class="math inline">\(P(data | model)\)</span> (the probability of seeing the sample data given our model). If we had a <em>perfect</em> model, this would be 1.
<ul>
<li>if you want a (slightly) more in depth look at “likelihood”, see <a href="lvp.html" target="_blank">here</a>.</li>
</ul></li>
<li>Log-likelihood = the log of the likelihood. The log transformation means that where likelihood ranges from 0 to 1, log-likelihood ranges from negative infinity to 0 (0 would be the perfect model)</li>
<li>-2Log-likelihood = turns it from negative to positive, and allows us to test it against a <span class="math inline">\(\chi^2\)</span> distribution.</li>
</ul>
</div>
<p>For instance, we can compare our model to the model where all slopes are 0. The null hypothesis will be that the simpler model is a good fit, while the alternative is that the more complex model is needed.</p>
<p>In R we do this comparison as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>fishmod0 <span class="ot">&lt;-</span> <span class="fu">glm</span>(caught_any <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> fish,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span><span class="st">"logit"</span>))</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>fishmod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(caught_any <span class="sc">~</span> hours, <span class="at">data =</span> fish,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span><span class="st">"logit"</span>))</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fishmod0, fishmod1, <span class="at">test =</span> <span class="st">'Chisq'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: caught_any ~ 1
Model 2: caught_any ~ hours
  Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
1       119     165.15                          
2       118     127.70  1    37.45 9.378e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The above code shows the two fitted models, amd reports the <em>Residual Deviance</em> of each model, 165.1 and 127.7 respectively. So by adding the predictor <code>hours</code> to the model, we reduce our deviance from 165.1 to 127.7, i.e.&nbsp;we reduce it by 37.4 (remember, deviance is like badness-of-fit, so smaller is better).<br>
Is this reduction sufficient to be attributed solely to the contribution of the predictor, or could it just be due to random sampling variation? This is what the chi-squared test tells us!</p>
<!-- Above was Drop-in-deviance GOF test -->
<!-- # Deviance GOF test -->
<!-- mdl_sat = glm(senility ~ factor(1:nrow(sen)), family = binomial, data = sen) -->
<!-- anova(mdl1, mdl_sat, test = 'Chisq') -->
<div class="optional-begin">
<span id="opt-start-11" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-11', 'opt-start-11')"> <span class="olab">Optional Akaike and Bayesian Information Criteria</span></span>
</div>
<div id="opt-body-11" class="optional-body" style="display: none;">
<p>Deviance measures lack of fit, and it can be reduced to zero by making the model more and more complex, effectively estimating the value at each single data point. However, this involves adding more and more predictors, which makes the model more complex (and less interpretable).</p>
<p>Typically, simpler models are preferred when they still explain the data almost as well. This is why information criteria were devised, exactly to account for both the model misfit but also its complexity.</p>
<p><span class="math display">\[
\text{Information Criterion} = \text{Deviance} + \text{Penalty for model complexity}
\]</span></p>
<p>Depending on the chosen penalty, you get different criteria. Two common ones are the Akaike and Bayesian Information Criteria, AIC and BIC respectively:</p>
<p><span class="math display">\[
\begin{aligned}
\text{AIC} &amp;= \text{Deviance} + 2 p \\
\text{BIC} &amp;= \text{Deviance} + p \log(n)
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(p\)</span> is the number of regression coefficients in the model. <strong>Models that produce smaller values of these fitting criteria should be preferred.</strong></p>
<p>AIC and BIC differ in their degrees of penalization for number of regression coefficients, with BIC usually favouring models with fewer terms.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fishmod0, fishmod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         df      AIC
fishmod0  1 167.1533
fishmod1  2 131.7031</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(fishmod0, fishmod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         df      BIC
fishmod0  1 169.9408
fishmod1  2 137.2781</code></pre>
</div>
</div>
<p>According to both AIC and BIC the model with hours as a predictor has a lower score, meaning it’s preferable to the other.</p>
</div>
<p class="optional-end">
</p>
<section id="assumptions" class="level3">
<h3 class="anchored" data-anchor-id="assumptions">Assumptions</h3>
<p>Because these models don’t have the same expected error distribution (we don’t expect residuals to be normally distributed around the mean, with constant variance), checking the assumptions of logistic regression is a little different.</p>
<p>Typically, we look at the “deviance residuals”. But we <strong>don’t</strong> examine plots for patterns, we simply examine them for potentially outlying observations. If we use a standardised residual, it makes it easier to explore extreme values as we expect most residuals to be within -2, 2 or -3, 3 (depending on how strict we feel).</p>
<div class="statbox">
<p><strong>Deviance Residuals</strong></p>
<p>There are three ways we can get out deviance residuals, each scaled differently</p>
<ul>
<li><span class="math inline">\(i\)</span>th residual = measure of deviance contributed from the <span class="math inline">\(i\)</span>th observation</li>
<li><span class="math inline">\(i\)</span>th standardized residual = residual / SD(residual)</li>
<li><span class="math inline">\(i\)</span>th studentized residual = residual / SD(residual from model fitted without observation <span class="math inline">\(i\)</span>)</li>
</ul>
<p>We get these in R using:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># deviance residuals</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(fishmod, <span class="at">type =</span> <span class="st">'deviance'</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="co"># studentised residuals</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rstudent</span>(fishmod, <span class="at">type =</span> <span class="st">'deviance'</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="co"># standardised residuals</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rstandard</span>(fishmod, <span class="at">type =</span> <span class="st">'deviance'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can check whether any residuals are larger than 2 or 3 in absolute value:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rstudent</span>(fishmod, <span class="at">type =</span> <span class="st">'deviance'</span>), </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">'Studentized Deviance Residuals'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><em><em>Warning:</em> Don’t inspect this plot for patterns!!!</em></p>
<p>There appears to be 1 residual with a value slightly larger than 2 in absolute value. We will keep these in mind and check later if they are also influential points (using <code>cooks.distance</code>)</p>
<p>Sometimes a <strong>binned plot</strong><a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> can be more informative, but not always! It works by combining together all responses for people having the same covariate <span class="math inline">\(x_i\)</span> value, and taking the average studentized Pearson residual for those.</p>
<p>Before using this function, make sure you have installed the <strong>arm</strong> package!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>arm<span class="sc">::</span><span class="fu">binnedplot</span>(<span class="fu">fitted</span>(fishmod), <span class="fu">rstudent</span>(fishmod, <span class="at">type =</span> <span class="st">'deviance'</span>), </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">xlab =</span> <span class="st">'Prob. of Catching fish'</span>, <span class="at">ylab =</span> <span class="st">'Studentized Deviance Residuals'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10a_glm_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>There doesn’t appear to be any extreme residuals.</p>
</div>
<!-- 

<div class="optional-begin"><span id='opt-start-12' class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-12', 'opt-start-12')"> <span class="olab">Optional: Pearson Residuals</span></span></div><div class="optional-body" id = "opt-body-12" style="display: none;">

 -->
<!-- __Pearson Residuals__   -->
<!-- There is another form of residual we can use, called "Pearson residuals". These are similar to the Pearson residuals you might remember from the [chi-squared test (4A)](04a_chisq.html){targt="_blank"}, which compared Observed and Expected values, but in this case Expected means Predicted from the model: -->
<!-- $$ -->
<!-- Pres_i = \frac{Observed - Expected}{\sqrt{Expected}} -->
<!-- $$ -->
<!-- In logistic regression, this is  -->
<!-- $$ -->
<!-- Pres_i = \frac{y_i - \hat p_i}{\sqrt{\hat p_i (1 - \hat p_i)}} -->
<!-- $$ -->
<!-- where  -->
<!-- - $y_i$ is the observed response for unit $i$, either 0 (failure) or 1 (success) -->
<!-- - $\hat p_i$ is the model-predicted probability of success -->
<!-- We can get these out from R, and use them to create similar plots to the one we made for deviance residuals.   -->
<!-- ```{r} -->
<!-- #| eval: false -->
<!-- # pearson residuals -->
<!-- residuals(fishmod, type = 'pearson') -->
<!-- # standardised pearson residuals -->
<!-- rstandard(fishmod, type = 'pearson') -->
<!-- # studentised pearson residuals -->
<!-- rstudent(fishmod, type = 'pearson') -->
<!-- ``` -->
<!-- 

</div><p class="optional-end"></p>

 -->


</section>
</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>we have seen this type of variable already when looking at categorical predictors in our models, but we haven’t seen how we use it as the <em>outcome</em><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>This means we will end up with a lot of multiplying (computationally expensive), and a tiny tiny number. So instead we typically talk about the log-likelihood, and use summation instead of multiplication. The log-likelihood of the two data points highlighted in <a href="#fig-mleprob">Figure&nbsp;10</a>, given the line is <code>log(0.98)+log(0.88)</code>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p><span class="math inline">\(e^{a+b} = e^a \times e^b\)</span>. For example: <span class="math inline">\(2^2 \times 2^3 = 4 \times 8 = 32 = 2^5 = 2^{2+3}\)</span><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4" role="doc-endnote"><p>whatever ‘large enough’ is!<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5" role="doc-endnote"><p>Gelman, A., &amp; Hill, J. (2006). Data Analysis Using Regression and Multilevel/Hierarchical Models (Analytical Methods for Social Research). Cambridge: Cambridge University Press. doi:10.1017/CBO9780511790942<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>