{
  "hash": "e27fc9796076b1b39907ca0b03aff863",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"9A: Interactions\"\nparams: \n    SHOW_SOLS: TRUE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n\n# Holding Constant...\n\nSo far, when we've been using multiple linear regression models, all our coefficients have been being interpreted as the \"change in $y$ for a 1-unit change in $x$ **while holding constant** the other predictors in the model\".   \n\nConsider a model with the following structure:    \n$$\ny = b_0 + b_1 \\cdot x_1 + b_2 \\cdot x_2 + \\epsilon\n$$\n\nWhen we fit this model structure to some data, we get out our estimated values for the coefficients $b_0$, $b_1$, and $b_2$, e.g.,:   \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmydata <- read_csv(\"https://uoepsy.github.io/data/usmr_mlr.csv\")\nmymodel <- lm(y ~ x1 + x2, data = mydata)\n```\n:::\n\n\n\n```\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)   \n(Intercept) -2.39138    3.67735  -0.650  0.51867   \nx1           0.17570    0.06435   2.730  0.00888 **\nx2          -0.64756    0.19959  -3.244  0.00217 **\n```\n\nThe coefficient we get out for $x_1$ tells us that the model estimates that $y$ will increase by 0.17 for every increase of 1 unit in $x_1$, _provided that we hold $x_2$ constant._  \n\nSo for _any_ value of $x_2$, a one unit increase in $x_1$ is associated with a $b_1$ change in $y$, provided that $x_2$ value stays as it is.  \n\nLet's use our primate brains data for a more realistic example: \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbraindata <- read_csv(\"https://uoepsy.github.io/data/usmr_braindata.csv\")\nbraindata <- braindata %>% mutate(\n  isMonkey = ifelse(species != \"Human\", \"YES\", \"NO\")\n)\n\nmonkeymod <- lm(mass_brain ~ age + isMonkey, data = braindata)\nsummary(monkeymod)\n```\n:::\n\n\n\n```\n...\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.668308   0.050478  13.240 1.57e-14 ***\nage         -0.004081   0.002337  -1.746   0.0904 .  \nisMonkeyYES -0.246933   0.044152  -5.593 3.54e-06 ***\n---\n```\n\nOur coefficient for `isMonkeyYES` coefficient is the estimated difference in brain mass between a human and a monkey **of the same age**.  \nSimilarly, our coefficient for `age` is the estimated change in brain mass for every additional year of age, provided we are not comparing a monkey to a human. \n\nThe idea of this can be seen on the plot in @fig-constplot. Imagine 4 different participants in our data. The coefficient for `isMonkeyYES` is the difference between A and C, or the difference between B and D. It doesn't matter where on the x-axis we go, it is the _vertical_ distance between the two lines.  \nThe `age` coefficient is the comparison between A and B, or between C and D.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![multiple regression model of brain mass predicted by age and isMonkey. The age coefficient is the slope of the lines, and the isMonkey coefficient is the difference in their heights](09a_interactions_files/figure-html/fig-constplot-1.png){#fig-constplot fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n#### *another* example (if you want one)\n\nWe're interested in estimating the association between BMI and cognition, after controlling for differences due to age.  \n\nWe want to use this model:  \n$$\n\\text{score on test of cognition} = b_0 + b_1 \\cdot \\text{age} + b_2 \\cdot \\text{BMI} + \\epsilon\n$$\nwhich we can fit using `lm()`:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(score ~ 1 + age + BMI, data = ourdata)\n```\n:::\n\n\n\nand we might get some coefficients (estimates for the $b_?$ values) such as those below:  \n_(I've just made up some nice round numbers to make it easier to think about)_  \n\n```\nCoefficients:\n            Estimate    ...   ...\n(Intercept)  160.000    ...   ...\nage         -1.50000    ...   ...\nBMI         -2.50000    ...   ...\n```\n\nThe coefficient of interest, the one for BMI, is telling us that \"a 1 unit increase in BMI is associated with a -2.5 decrease in Scores on the cognitive test, _holding age constant_\".  \n\nConsider 3 people: \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Three theoretical people](images/ints/constant.png){#fig-pplconstant fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\nThe coefficient for BMI represents the difference in cognitive scores we would expect between Person A and Person B.  \n\nThink about why this is.  \nFor some person $i$, their model predicted score is:  \n$$\n\\hat{score_i} = b_0 + b_1 \\cdot age_i + b_2 \\cdot BMI_i\n$$\nWhich from our model estimates is:  \n$$\n\\hat{score_i} = 160 - 1.5 \\cdot age_i - 2.5 \\cdot BMI_i\n$$\n\n- Person A's score = $160 - (1.5*50) - (2.5*22) = 30$\n- Person B's score = $160 - (1.5*50) - (2.5*23) = 27.5$\n- Person C's score = $160 - (1.5*60) - (2.5*23) = 12.5$\n\nThe difference in model estimated Score between Person A and Person B is the coefficient of BMI, because those two people _only differ_ on BMI. Person A and Person C _also differ_ on age. This is how the coefficient of BMI is interpreted as \"holding age constant\" - it is a comparison between two hypothetical people who differ on BMI but are identical with respect to the other predictors in the model.  \n:::\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# It Depends...\n\nSometimes, however, we might have reason to think that a certain association should *not* be the same at every value of another variable.  \n\nThere are lots of practical cases where we might think that the relationship between two variables _depends on_ the value of a third. \n\nBelow are some examples of this idea, where the explanatory variables (the predictors) are of different types (e.g. continuous, categorical, etc):  \n\n:::panelset\n\n:::panel\n#### Example 1\n\n> The amount to which spending time with partner influences wellbeing _depends on_ the quality of the relationship.  \n\nVariables:  \n\n- __Outcome:__ Wellbeing (questionnaire score ranging from 0 to 32)\n- __Continuous Predictor:__ Time spent with partner (hours per day)  \n- __Continuous Predictor:__ Relationship Quality (rating from 0 to 100)  \n\n\n:::\n:::panel\n#### Example 2\n\n> The influence of air-pollution on cognitive functioning _depends on_ genetic status.  \n\nVariables:  \n\n- __Outcome:__ Cognitive Functioning measured via the MMSE. Possible scores range from 0 to 30. Lower scores indicate poorer cognitive functioning\n- __Continuous Predictor:__ Air-Quality Pollution Index (AQI). Ranges from 0 to 500. The higher the AQI value, the greater the level of air pollution.\n- __Categorical Predictor:__ APOE-4 Genotype status: Negative vs Positive  \n\n\n:::\n:::panel\n#### Example 3\n\n> Trick-or-treating children are more greedy when their costume hides their identity. But this is different _depending on_ whether they are alone or in a group.  \n\n\nVariables:  \n\n- __Outcome__: Number of candy bars taken while trick or treating\n- __Categorical Predictor:__  Whether or not the childs' identity is hidden by their costume (anonymous vs identifiable)\n- __Categorical Predictor:__ Whether the child is trick or treating as a group or alone (alone vs group)  \n\n\n:::\n\n:::\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Interactions!\n\nIn each of the above examples, we can no longer think about \"the relationship between [outcome] and [predictor]\" without discussing the level of the other predictor.  \n\n:::: {.columns}\n::: {.column width=\"55%\"}\nUsing Example 1 above, let's return to thinking about this in terms of two different observations (i.e. two different people in @fig-pplint).  \nHow do we think people's wellbeing will differ between someone who spends 1 hour with their partner and someone who spends 2 hours with their partner?  \n\nIf these are people from group A (these are people who have a really great relationship), then that extra hour will probably make a big impact on wellbeing!  \n\nWill it be the same for people from group B? People in group B are those people who don't have great relationships. For these people, whether you spend 1 hour or 2 hours with your partner doesn't pattern with a difference in wellbeing to the same extent as it does for the people in group A. It might even have a negative impact!  \n\n:::\n::: {.column width=\"45%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Comparisons between two theoretical observations who differ on only one predictor now depends on some other predictor](images/ints/ints.png){#fig-pplint fig-align='center' width=80% height=400px}\n:::\n:::\n\n\n\n\n:::\n::::\n\n\nTo capture this, what we need is an _extra_ bit of information to tell us \"how _much_ does the association between 'time spent with partner' and wellbeing change as relationship quality changes?\" And this is something we can include in our model, and get an estimate for!   \n\nWe can model the idea of \"the association between $x_1$ and $y$ changes _depending on_ the level of $x_2$\" by including a product (multiplication) term between the two predictors.   \n\nSuch a model would take the form:  \n\n\n$$\ny = b_0 + b_1 \\cdot x_1 + b_2 \\cdot x_2 + b_3 \\cdot x_1 \\cdot x_2 + \\epsilon\n$$\n\nWhat this is doing is saying that our outcome $y$ is predicted by: \n\n- some amount of $x_1$\n- some amount of $x_2$\n- and a little addition to each of those amounts depending on the value of of the other variable.   \n\nTo provide a visual intuition and build on how we have been thinking of multiple regression upto this point, when we have two predictors that interact, our regression surface is no longer flat, but _twists_. This is because the slope along values of $x_1$ _changes_ as we move up $x_2$:   \n\n\n::: {.callout-caution collapse=\"true\"}\n#### why is it multiplication?  \n\nIf we think about the simple additive model (additive = **without** the interaction), then what we're saying is that the effect of $x_1$ on $y$ is simply $b_1$, which is a _constant_ (i.e. just a single number).  \n  \n$$\ny = b_0 + \\underbrace{b_1}_{\\text{effect}\\\\ \\text{of } x_1} \\cdot x_1 + b_2 \\cdot x_2 + \\epsilon\n$$\nBut what we want to model is that \"the effect of $x_1$ _depends_ on $x_2$\", so the effect is not just a single constant number, it's more like \"some number plus an amount of $x_2$\".  \nFor \"an amount of $x_2$\" let's use $b_3 \\cdot x_2$:  \n\n$$\ny = b_0 + \\underbrace{(\\overbrace{b_1}^{\\,\\,\\text{ some}\\\\ \\text{number}} + \\overbrace{b_{3} \\cdot x_2}^{\\text{some amount of }x_2})}_{\\text{effect of } x_1} \\cdot x_1 + b_2 \\cdot x_2 + \\epsilon\n$$\n\nWhich really expands out to:  \n\n$$\ny = b_0 + b_1 \\cdot x_1 + b_3 \\cdot x_2 \\cdot x_1 + b_2 \\cdot x_2 + \\epsilon\n$$\n\n:::\n\n\n\n\n:::panelset\n\n:::panel\n#### Example 1\n\n> The amount to which spending time with my partner influences my wellbeing _depends on_ the quality of our relationship.^[This example comes from Ian Hajnosz, who previously tutored on USMR]  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Interaction between two continuous predictors, viewed from two angles](09a_interactions_files/figure-html/fig-i.contcont-1.png){#fig-i.contcont fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nAt high values of relationship quality, the amount wellbeing increases with time spent is greater than it is at low values of relationship quality.  \nAnd we can phrase this the other way around: at high amounts of time spent with partner, relationship quality has a bigger effect on wellbeing than it does for low amounts of time spent. \n\nIn the model with this interaction:  \n$$\n\\text{wellbeing} = b_0 + b_1 \\cdot \\text{time} + b_2 \\cdot \\text{quality} + b_3 \\cdot \\text{time} \\cdot \\text{quality}\n$$\nThe interaction coefficient $b_3$ is the adjustment we make to the slope of wellbeing with \"time spent with partner\", as we move 1 up in \"relationship quality\".^[And vice versa! It is also the adjustment we make to the slope of wellbeing with \"relationship quality\", as we move 1 up in \"time spent with partner\"]  \n\n:::\n:::panel\n#### Example 2\n\n> The influence of air-pollution on cognitive functioning _depends on_ your genetic status.^[This example comes from Otto Jutila, who previously tutored on USMR]  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Interaction between a continuous and a binary categorical predictors](09a_interactions_files/figure-html/fig-i.contcat-1.png){#fig-i.contcat fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nThis kind of interaction (where one predictor is continuous and the other is categorical), is sometimes the easiest to think about.  \n\nWe can see in @fig-i.contcat that cognition decreases as air pollution increases, __but__ this is different depending on genetic status. In the APOE4-positive group, the association is steeper than in the APOE4-negative group. The interaction is evident in that the two lines are non-parallel.   \n\nIn the model:  \n\n$$\n\\text{Cognition} = b_0 + b_1 \\cdot\\text{pollution} + b_2\\cdot\\text{APOE4} + b_3\\cdot\\text{pollution} \\cdot \\text{APOE4}\n$$\n\nThe interaction term $b_3$ is the estimated adjustment made to the slope of cogition across air pollution when we move from one group to the other. e.g. the slope for the APOE4-positive group is equal to the slope of the APOE4-negative group _plus the interaction term_.\n\n:::\n:::panel\n#### Example 3\n\n> The influence of being anonymous on childrens' greedy behaviours _depends on_ if they are alone or part of a group.^[This example comes from Tia Gong, who previously tutored on USMR]  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Interaction between two categorical predictors](09a_interactions_files/figure-html/fig-i.catcat-1.png){#fig-i.catcat fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nFor interactions between two categorical variables, we tend to plot the mean of the outcome variable for each combination of levels. We can see the interaction in @fig-i.catcat in the fact that the two dotted lines we have added to join the group-means are not parallel. \n\nChildren who are anonymous tend to take more candybars than those who are identifiable, but this difference is much greater when children are trick of treating in a group than when they are doing so alone!  \n\nIn the model\n$$\n\\text{candy} = b_0 + b_1 \\cdot\\text{isAnon} + b_2\\cdot\\text{inGroup} + b_3\\cdot\\text{isAnon} \\cdot \\text{inGroup}\n$$\n\nThe interaction term $b_3$ is going to be the estimated adjustment to the difference between anonymous vs identifiable for children in a group vs those alone. Put another way, it is how the difference between the two blue dots in alone vs group for is different from the difference between the two red dots.  \ne.g. the difference between anonymous & identifiable children in a group is equal to the difference between anonymous & identifiable children who are alone _plus the interaction term_.\n\n:::\n\n:::\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Fitting interactions in R\n\nIn R, the interaction term gets denoted by a colon `:` between the two predictor variables. We can fit an interaction term in a regression model quite easily in R:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# we don't *need* to put the 1, it's up to you :)\nlm(y ~ 1 + x1 + x2 + x1:x2, data = dataset)\n```\n:::\n\n\n\nThis maps to the model equation we saw earlier: \n$$\ny = b_0 + b_1\\cdot x_1 + b_2 \\cdot x_2 + b_3 \\cdot x_1 \\cdot x_2 + \\epsilon\n$$\n\n:::rtip\n__Shortcut__  \n\nTo express `x1 + x2 + x1:x2`, we can also use just `x1*x2`.  \n\nThese two models are equivalent: \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(y ~ 1 + x1 + x2 + x1:x2, data = dataset)\nlm(y ~ 1 + x1*x2, data = dataset)\n```\n:::\n\n\n\n\n:::\n\n:::imp\n\nIf we fit the interaction `x1:x2`, we almost _always_ want to also fit the separate effects `x1` and `x2`.  \n\n_\"Except in special circumstances, a model including a product term for interaction between two explanatory variables should also include terms with each of the explanatory variables individually, even though their coefficients may not be significantly different from zero. Following this rule avoids the logical inconsistency of saying that the effect of $x_1$ depends on the level of $x_2$ but that there is no effect of $x_1$.\"_ [Ramsey & Schafer](https://www.cengage.uk/c/the-statistical-sleuth-3e-ramsey-schafer/9781133490678/){target=\"_blank\"}\n\n:::\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Interpretation\n\nWhen we include an interaction term in our model, we are saying that two effects of the two predictors on the outcome are _dependent upon_ one another. This means that with an interaction in the model `lm(y ~ x1 + x2 + x1:x2)` we can no longer talk about the \"effect of $x_1$ on $y$_'holding $x_2$ constant'_\". Instead we have to talk about **marginal effects** - e.g. the effect of $x_1$ _at a **specific** value_ of $x_2$.   \n\nWhen we fit a model with an interaction in R, we get out coefficients for both predictors, and for the interaction. The coefficients for each individual predictor reflect the effect on the outcome _when the other predictor is zero_. \n\n```\nlm(formula = y ~ x1 * x2, data = df)\n...\n...\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)  \n(Intercept)  ...        ....       ...      ...  \nx1           ...        ....       ...      ...  \nx2           ...        ....       ...      ...  \nx1:x2        ...        ....       ...      ...  \n---\n```\n\n\n:::sticky\n**marginal effects when the other predictor is zero**  \n\nThe individual coefficients for each predictor that is involved in an interaction are estimated _when the other predictor in the interaction is zero._  \n\n:::\n\n\nThese coefficients can be interpreted, in turn as:  \n\n| Coefficient      | Interpretation |\n| ----------- | ----------- |\n| `(Intercept)` | the estimated $y$ when all predictors ($x_1$ and $x_2$) are zero is [*estimate*] |\n| `x1`  | **when $x_2$ is zero,** a 1 unit increase in $x_1$ is associated with a [*estimate*] change in $y$ |\n| `x2`  | **when $x_1$ is zero,** a 1 unit increase in $x_2$ is associated with a [*estimate*] change in $y$. |\n| `x1:x2`  | as $x_2$ increases by 1, the association between $x_1$ and $y$ changes by [*estimate*]<br>_**or**_<br>as $x_1$ increases by 1, the association between $x_2$ and $y$ changes by [*estimate*] |\n\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n#### What if there are other things in the model too?\n\nNote that the interaction `x1:x2` changes how we interpret the individual coefficients for `x1` and `x2`.  \n\nIt does __*not*__ change how we interpret coefficients for other predictors that might be in our model. For variables that **aren't** involved in the interaction term, these are still held constant.  \n\nFor example, suppose we _also_ had another predictor $c_1$ in our model: \n```\nlm(y ~ c1 + x1 + x2 + x1:x2)\n```\n\n| Coefficient      | Interpretation |\n| ----------- | ----------- |\n| `(Intercept)` | the estimated $y$ when all predictors ($c_1$, $x_1$ and $x_2$) are zero is [*estimate*] |\n| `c1` | a 1 unit increase in $c_1$ is associated with a [*estimate*] increase in $y$, holding constant all other variables in the model ($x_1$ and $x_2$) |\n| `x1`  | holding $c_1$ constant, **when $x_2$ is zero,** a 1 unit increase in $x_1$ is associated with a [*estimate*] change in $y$ |\n| `x2`  | holding $c_1$ constant, **when $x_1$ is zero,** a 1 unit increase in $x_2$ is associated with a [*estimate*] change in $y$. |\n| `x1:x2`  | holding $c_1$ constant, as $x_2$ increases by 1, the association between $x_1$ and $y$ changes by [*estimate*]<br>_**or**_<br>holding $c_1$ constant, as $x_1$ increases by 1, the association between $x_2$ and $y$ changes by [*estimate*] |\n\n\n:::\n\n\n\n<br><br>\n\n:::panelset\n\n:::panel\n#### Example 1\n\n> The amount to which spending time with my partner influences my wellbeing _depends on_ the quality of our relationship.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# data\nptdat <- read_csv(\"https://uoepsy.github.io/data/usmr_partnertime.csv\")\n# model\neg1mod <- lm(wellbeing ~ partner_time * relationship_qual, data = ptdat)\nsummary(eg1mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wellbeing ~ partner_time * relationship_qual, data = ptdat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5592 -0.5559  0.1243  0.8884  3.2944 \n\nCoefficients:\n                                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                    14.413160   2.192467   6.574 1.75e-08 ***\npartner_time                   -1.405842   0.293737  -4.786 1.28e-05 ***\nrelationship_qual              -0.055658   0.036693  -1.517    0.135    \npartner_time:relationship_qual  0.044363   0.004862   9.124 1.14e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.281 on 56 degrees of freedom\nMultiple R-squared:  0.9377,\tAdjusted R-squared:  0.9343 \nF-statistic: 280.8 on 3 and 56 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n- For someone who spends 0 hours with their partner, and who has a relationship quality score of 0, their estimated wellbeing is 14.41.  \n- For someone who has a relationship quality score of 0, every hour spent with their partner is associated with a -1.41 change in wellbeing.  \n- For someone who spends 0 hours with their partner, an increase of 1 in the relationship quality is associated with a -0.06 change in wellbeing.  \n- For every 1 increase in relationship quality, an extra hour spent with their partner is associated with an _additional_ 0.04 change in wellbeing. \n\n\n:::\n:::panel\n#### Example 2\n\n> The influence of air-pollution on cognitive functioning _depends on_ your genetic status.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# data\nairpol <- read_csv(\"https://uoepsy.github.io/data/usmr_airpol.csv\")\n# model\neg2mod <- lm(mmse ~ aqpi * apoe4, data = airpol)\nsummary(eg2mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mmse ~ aqpi * apoe4, data = airpol)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.8225 -1.0241  0.2269  0.9554  3.8932 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   28.128929   0.642991  43.747  < 2e-16 ***\naqpi          -0.016474   0.002930  -5.623 6.18e-07 ***\napoe4pos      -3.297908   0.904448  -3.646 0.000584 ***\naqpi:apoe4pos -0.014635   0.004405  -3.322 0.001578 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.674 on 56 degrees of freedom\nMultiple R-squared:  0.8344,\tAdjusted R-squared:  0.8255 \nF-statistic: 94.06 on 3 and 56 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n- For people who are APOE4 negative (the reference level, see [8A#multiple-categories-multiple-regression](08a_mlr.html#multiple-categories-multiple-regression){target=\"_blank\"}), living where the Air Quality Pollution Index is 0 (no pollution), the estimated score on the MMSE (mini mental state exam) is 28.13.  \n- For people who are APOE4 negative, a 1 unit increase in air pollution is associated with a -0.02 change in MMSE scores.  \n- For people living with 0 air pollution, being APOE4 positive is associated with -3.3 lower MMSE scores compared to APOE4 negative\n- Compared to APOE4 negative, being APOE4 positive is associated with -0.01 greater decrease in MMSE scores for every 1 increase in air pollution.\n\n\n:::\n:::panel\n#### Example 3\n\n> The influence of being anonymous on childrens' greedy behaviours _depends on_ if they are alone or part of a group.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# data\ncandy <- read_csv(\"https://uoepsy.github.io/data/usmr_candy.csv\")\n# model\neg3mod <- lm(candybars ~ anonymity * asgroup, data = candy)\nsummary(eg3mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = candybars ~ anonymity * asgroup, data = candy)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.9000 -0.3636  0.0000  0.9444  1.9444 \n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                         10.0556     0.2236  44.974  < 2e-16 ***\nanonymityidentifiable               -2.0556     0.3047  -6.746 9.08e-09 ***\nasgroupgroup                         3.8444     0.3741  10.276 1.69e-14 ***\nanonymityidentifiable:asgroupgroup  -4.4808     0.5144  -8.711 5.31e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9486 on 56 degrees of freedom\nMultiple R-squared:  0.8548,\tAdjusted R-squared:  0.847 \nF-statistic: 109.9 on 3 and 56 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n- An anonymous child trick or treating alone is estimated to take 10 candybars.\n- When trick or treating alone, compared to an anonymous child, an identifiable child is estimated to take 2 fewer candybars.  \n- When anonymous, compared to trick or treating alone, children who are part of a group are estimated to take 3.8 more candybars.  \n- The difference between identifiable and anonymous children's candybar taking is 4 fewer when children are trick or treating in a group than when they are alone.  \n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n:::\n\n:::\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Visualisation\n\nWe have seen lots of 3-dimensional plots above to try and help in building our intuition about how we model an interaction. However, we typically don't really want to visualise models like this (in part because our models often have more than 2 predictors, and so have more than 3 dimensions).  \n\nWhat we therefore need to do is find ways to represent these relationships in 2-dimensional plots. This is slightly different depending on the type of variables we are dealing with. \n\n- For a continuous $\\times$ categorical interaction, we can plot the association of the continuous predictor with the outcome *for each level* of the categorical variable. \n- For a continuous $\\times$ continuous interaction, we can plot the association of one predictor *at some judiciously chosen values* of the other (e.g. at the min, mean and max, or at -1 SD, mean, and +1 SD).  \n- For a categorical $\\times$ categorical interaction, we can plot the various estimated group means, with optional dotted^[dotted is a good way to indicate that there is no data across that line - it is linking two categories. Martin disagrees and thinks you should never have lines] lines to illustrate the non-parallelism   \n\n\n::: {.callout-note collapse=\"true\"}\n#### optional helper packages\n\nWe can make these sort of plots very easily using handy packages that are designed to make our lives easier. The _big_ downsides are that reliance on these packages will a) make it harder to customise plots, b) make it harder to troubleshoot when things go wrong, and c) stop us from having to *think* (and thinking is always good!).  \n\n**Use with caution:**    \n\n- From the **sjPlot** package: `plot_model(model, type = \"int\")` or `plot_model(model, type = \"eff\", terms = c(\"x1\",\"x2\"))`  \n- From the **interactions** package: `interact_plot(model, pred = \"x1\", modx = \"x2\")`, and `cat_plot()` for categorical interactions.     \n\n\n:::\n\n\n\n:::panelset\n\n:::panel\n#### Example 1\n\n> The amount to which spending time with my partner influences my wellbeing _depends on_ the quality of our relationship.  \n\nPlotting continuous by continuous interactions requires choosing a set of values for one of our predictors, at which we plot the slope of the other.  \n\nHere, we could choose to plot the slope of `wellbeing ~ partner_time` for the mean `relationship_qual`, and for 1 SD above and below that mean.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# data\nptdat <- read_csv(\"https://uoepsy.github.io/data/usmr_partnertime.csv\")\n# model\neg1mod <- lm(wellbeing ~ partner_time * relationship_qual, data = ptdat)\n\n# plot data\nplotdat <- expand_grid(\n  partner_time = 0:13, #min to max of sample\n  relationship_qual = c(\n    mean(ptdat$relationship_qual)-sd(ptdat$relationship_qual),\n    mean(ptdat$relationship_qual),\n    mean(ptdat$relationship_qual)+sd(ptdat$relationship_qual)\n  )\n)\n# plot\nbroom::augment(eg1mod, newdata = plotdat, interval=\"confidence\") |>\n  ggplot(aes(x=partner_time, y=.fitted, \n             col=relationship_qual,\n             group=relationship_qual))+\n  geom_point(data = ptdat,aes(y=wellbeing))+\n  geom_line()+\n  geom_ribbon(aes(ymin=.lower,ymax=.upper,fill=relationship_qual),\n              alpha=.2)\n```\n\n::: {.cell-output-display}\n![](09a_interactions_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n<!-- ::: {.callout-tip collapse=\"true\"} -->\n<!-- #### optional helper packages -->\n\n<!-- The interactions package defaults to showing the y~x1 relationship when x2 is at -1 SD below the mean, at the mean, and +1 SD above the mean.   -->\n<!-- ```{r} -->\n<!-- library(interactions) -->\n<!-- interact_plot(eg1mod, pred = \"partner_time\", modx = \"relationship_qual\", interval = TRUE) -->\n<!-- ``` -->\n\n<!-- The __sjPlot__ package can do this too, but wil default to showing it at the min and max of the other predictor.   -->\n<!-- ```{r} -->\n<!-- library(sjPlot) -->\n<!-- plot_model(eg1mod, type=\"int\") -->\n<!-- ``` -->\n<!-- We can change these manually. For instance, to make `plot_model` show the association when relationship quality is zero, when it is 50, and when it is 100, we could use:  -->\n<!-- ```{r} -->\n<!-- #| eval: false -->\n<!-- plot_model(eg1mod, type = \"eff\", terms=c(\"partner_time\",\"relationship_qual [0, 50, 100]\")) -->\n<!-- ``` -->\n\n<!-- ::: -->\n\n\n:::\n:::panel\n#### Example 2\n\n> The influence of air-pollution on cognitive functioning _depends on_ your genetic status.  \n\nThis is the most straightforward type of interaction to visualise, as there are only a set number of values that one of the variables can take, meaning only a finite number of lines we need to draw:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# data\nairpol <- read_csv(\"https://uoepsy.github.io/data/usmr_airpol.csv\")\n# model\neg2mod <- lm(mmse ~ aqpi * apoe4, data = airpol)\n\n# plot data\nplotdat <- expand_grid(\n  aqpi = 0:500,\n  apoe4 = c(\"neg\",\"pos\")\n)\n# plot\nbroom::augment(eg2mod, newdata = plotdat, interval=\"confidence\") |>\n  ggplot(aes(x=aqpi, y = .fitted, \n             col = apoe4, fill = apoe4)) + \n  geom_point(data = airpol, aes(y = mmse), alpha=.3, size=3) +\n  geom_line() +\n  geom_ribbon(aes(ymin=.lower,ymax=.upper), alpha=.3)\n```\n\n::: {.cell-output-display}\n![](09a_interactions_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n<!-- ::: {.callout-tip collapse=\"true\"} -->\n<!-- #### optional helper packages -->\n\n<!-- ```{r} -->\n<!-- p1 <- sjPlot::plot_model(eg2mod, type = \"int\") -->\n<!-- p2 <- interactions::interact_plot(eg2mod, pred = \"aqpi\", modx = \"apoe4\", interval = TRUE) -->\n<!-- p1 / p2 -->\n<!-- ``` -->\n<!-- ::: -->\n\n\n:::\n:::panel\n#### Example 3\n\n> The influence of being anonymous on childrens' greedy behaviours _depends on_ if they are alone or part of a group.\n\nFor these types of interactions (between categorical variables), plotting the estimates from our model is best done as our set of estimated group means.   \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# data\ncandy <- read_csv(\"https://uoepsy.github.io/data/usmr_candy.csv\")\n# model\neg3mod <- lm(candybars ~ anonymity * asgroup, data = candy)\n\n# plot data\nplotdat <- expand_grid(\n  anonymity = c(\"anonymous\",\"identifiable\"),\n  asgroup = c(\"alone\",\"group\")\n)\n\n# plot\nbroom::augment(eg3mod, newdata=plotdat, interval=\"confidence\") |>\n  ggplot(aes(x = anonymity, col = asgroup)) + \n  geom_jitter(data = candy, aes(y = candybars),\n              alpha = .3, size = 3,\n              height = 0, width = .2) +\n  geom_pointrange(aes(y=.fitted, ymin=.lower, ymax=.upper),\n                  position = position_dodge(width=.2))\n```\n\n::: {.cell-output-display}\n![](09a_interactions_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n<!-- ::: {.callout-tip collapse=\"true\"} -->\n<!-- #### optional helper packages -->\n\n<!-- ```{r} -->\n<!-- p1 <- sjPlot::plot_model(eg3mod, type = \"int\")  -->\n<!-- p2 <- interactions::cat_plot(eg3mod, pred = \"anonymity\", modx = \"asgroup\", interval = TRUE) -->\n\n<!-- p1 / p2 -->\n<!-- ``` -->\n\n\n<!-- ::: -->\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n:::\n\n:::\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Getting more from your model\n\nReporting on interactions is a bit like telling a story. Listing the interpretation of the coefficients is fine, but often reads a bit awkwardly. A good presentation of the results would provide the reader with the overall pattern of results, pulling out the key parts that are of interest. There are various things we can do to get out coefficients that might be of more use to us in telling our story.  \n\n## Mean Centering\n\nBy mean centering a continuous predictor, we change what \"0\" means. Normally, when we don't have an interaction, this simply changes the intercept value (see [8A #centering-and-scaling-predictors](08a_scaling.html#centering-and-scaling-predictors){target=\"_blank\"}). If we have the interaction `y ~ x1 + x2 + x1:x2`, then mean centering `x1` will make the coefficient for `x2` now represent \"the association between $x_2$ and $y$ for someone at the _average_ of $x_1$\". \n\nUsing one of our examples from throughout this reading, we might mean-center the air-pollution so that we can consider the difference in MMSE scores between APOE4 positive and negative people _at the average air-pollution level_\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# data\nairpol <- read_csv(\"https://uoepsy.github.io/data/usmr_airpol.csv\")\n# model with original variable\neg2mod <- lm(mmse ~ aqpi * apoe4, data = airpol)\n# model with mean centered predictor\neg2mod_cent <- lm(mmse ~ scale(aqpi,scale=FALSE) * apoe4, data = airpol)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# coefficients:\ncoef(eg2mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)          aqpi      apoe4pos aqpi:apoe4pos \n  28.12892936   -0.01647447   -3.29790816   -0.01463533 \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(eg2mod_cent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        (Intercept)          scale(aqpi, scale = FALSE) \n                        25.16379896                         -0.01647447 \n                           apoe4pos scale(aqpi, scale = FALSE):apoe4pos \n                        -5.93202402                         -0.01463533 \n```\n\n\n:::\n:::\n\n\n\n\nThis is because the coefficient for APOE4 compares the heights of the two lines when the other predictor is zero. So if we change what \"zero\" represents, we can change what that estimates. In the model plots below, we can see that _the model doesn't change_, it is just extracting different information (it is the distance to move from the blue dot to the red dot):  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09a_interactions_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## Relevelling Factors\n\nAnother thing that can be useful (especially when working with categorical variables with lots of levels) is to make sure your variables are `factors` in R, and to set a useful reference level. Typically, the reference level is what we think of as \"normal\", e.g. if we have 3 groups: Placebo, Drug A, and Drug B, then we might compare each drug to the placebo condition, because that's comparable to most people (i.e. who aren't taking the drug).\n\nFor example, when we have two categorical variables:  \n\n- anonymity = \"anonymous\" vs \"identifiable\"\n- asgroup = \"alone\" vs \"group\"\n\nThen the default is to take the alphabetical ordering. We can change the ordering using functions that \"relevel\" a factor. Note, this only works if the variable is _already_ a `factor` in R (see [2A#categorical](02a_measurement.html#categorical){target=\"_blank\"} for a reminder of 'factors').   \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# data \ncandy <- read_csv(\"https://uoepsy.github.io/data/usmr_candy.csv\")\n\n# make both predictors 'factors'\ncandy <- \n  candy %>% \n  mutate(\n    anonymity = factor(anonymity),\n    asgroup = factor(asgroup)\n  )\n```\n:::\n\n\n\n\nOnce they are factors, we can see the default levels:  \n\n:::: {.columns}\n::: {.column width=\"47.5%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlevels(candy$anonymity)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"anonymous\"    \"identifiable\"\n```\n\n\n:::\n:::\n\n\n\n:::\n::: {.column width=\"5%\"}\n<!-- empty column to create gap -->\n:::\n::: {.column width=\"47.5%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlevels(candy$asgroup)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"alone\" \"group\"\n```\n\n\n:::\n:::\n\n\n\n:::\n\n::::\n\n\nThis is the original model, with the default levels:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\neg3mod <- lm(candybars ~ anonymity * asgroup, data = candy)\ncoef(eg3mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       (Intercept)              anonymityidentifiable \n                         10.055556                          -2.055556 \n                      asgroupgroup anonymityidentifiable:asgroupgroup \n                          3.844444                          -4.480808 \n```\n\n\n:::\n:::\n\n\n\n\nLet's relevel anonymity to have \"identifiable\" as the first level, and then refit the model:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncandy <- \n  candy %>% \n  mutate(\n    anonymity = fct_relevel(anonymity, \"identifiable\")\n  )\n\neg3mod_rel <- lm(candybars ~ anonymity * asgroup, data = candy)\n\ncoef(eg3mod_rel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    (Intercept)              anonymityanonymous \n                      8.0000000                       2.0555556 \n                   asgroupgroup anonymityanonymous:asgroupgroup \n                     -0.6363636                       4.4808081 \n```\n\n\n:::\n:::\n\n\n\n\nAgain, the model doesn't change, we are simply extracting different bits from it:  \n\n::::panelset\n:::panel\n#### reference level = \"anonymous\"\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09a_interactions_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n:::\n:::panel\n#### reference level = \"identifiable\"\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09a_interactions_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::\n::::\n\n<!-- :::sticky -->\n<!-- __Mapping model estimates to model plots__   -->\n\n<!-- To help with interpretation of the estimated coefficients from a model, a very useful exercise is to try and map them to what we see in our model plots (as seen above).   -->\n\n<!-- As we've talked about already - as models get more complex, there is a very important distinction to make between plotting the data and plotting the model estimates.   -->\n<!-- Whereas previously we could plot a simple regression `lm(y~x)` by plotting the _data_ and adding `geom_smooth(method=lm)`, now that we are working with multiple regression in order to visualise our results we should think of it as plotting the _model_ (and we can add the data if desired).   -->\n\n<!-- ::: -->\n\n\n::: {.callout-caution collapse=\"true\"}\n#### Optional: Interactions and Sum Contrasts  \n\n\n\n\n\n\n\n\n\n\nWhen we have categorical predictors, our choice of contrasts coding changes the bits that we're getting our of our model.  \n\nSuppose we have a 2x2 design (condition A and B, in groups 1 and 2):  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Categorical x Categorical Interaction plot](09a_interactions_files/figure-html/fig-sumplot-1.png){#fig-sumplot fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nWhen we are using the default contrasts coding (treatment - [see 8B #contrasts](08b_catpred.html#contrasts){target=\"_blank\"}) in R, then our coefficients for the individual predictors represent moving between the dots in @fig-sumplot.  \n\n```\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            1.9098     0.1759  10.855  < 2e-16 ***\nconditionB             1.1841     0.2488   4.759 5.65e-06 ***\ngrouping2             -1.6508     0.2488  -6.635 1.09e-09 ***\nconditionB:grouping2  -2.1627     0.3519  -6.146 1.15e-08 ***\n---\n```\n\n- The intercept is the red circle in @fig-sumplot.  \n- The coefficient for condition is the difference between the red circle and the red triangle in @fig-sumplot.  \n- The coefficient for grouping is the difference between the red circle and the blue circle in @fig-sumplot.  \n- The interaction coefficient is the difference from the slope of the red line to the slope of the blue line.  \n\n\nHowever, when we change to using sum contrasts, we're switching where zero is in our model. So if we change to sum contrasts (here we've changed __both__ predictors to using sum contrasts), then we end up estimating the effect of each predictor averaged across the other.  \n\n```\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           1.13577    0.08796  12.912  < 2e-16 ***\nconditionB            0.05141    0.08796   0.584     0.56    \ngrouping2            -1.36607    0.08796 -15.530  < 2e-16 ***\nconditionB:grouping2 -0.54066    0.08796  -6.146 1.15e-08 ***\n---\n```\n\n- The intercept is the grey X in @fig-sumplot2.  \n- The coefficient for condition is the difference between the grey X and the grey triangle in @fig-sumplot2.  \n- The coefficient for grouping is the difference between the grey X and the blue line in @fig-sumplot2.  \n- The interaction coefficient is the difference from the slope of the grey line to slope of the blue line.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Visualisation of sum-contrasts for categorical x categorical interaction plot](09a_interactions_files/figure-html/fig-sumplot2-1.png){#fig-sumplot2 fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\nIt can get quite confusing when we start switching up the contrasts, but it's all just because we're changing what \"zero\" means, and what \"moving 1\" means:  \n\n::::panelset\n:::panel\n#### Treatment contrasts\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09a_interactions_files/figure-html/unnamed-chunk-34-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n:::\n:::panel\n#### Sum contrasts\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09a_interactions_files/figure-html/unnamed-chunk-35-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n:::\n::::\n\n\n\n:::\n\n\n::: {.callout-caution collapse=\"true\"}\n#### Optional Extra: Getting non-linear  \n\nYou might be noticing that when we start talking about our regression surface \"twisting\" (e.g. in @fig-i.contcont), we're starting to see curves in our model.  \n\nWe can model _curves_ in a \"linear\" model!?  \n\nAn interaction does in a sense introduce non-linearity to our thinking, because there we no longer think of a linear effect of $x_1$ (it \"depends on\" $x_2$). This a little bit of a trick, because ultimately our model is still linear - we are estimating our outcome $y$ as the _linear combination_ of a set of predictors. In the model $y = b_0 + b_1 \\cdot x_1 + b_2 \\cdot x_2 + b_3 \\cdot x_1 \\cdot x_2$, the adjustment that we make $b_3$ to each of the coefficients $b_1$ and $b_2$ is a constant.  \n\nWe can even exploit this to model more clearly \"non-linear\" associations, such as the age and height example below.  \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Two linear models, one with a quadratic term (right)](09a_interactions_files/figure-html/fig-nonlin-1.png){#fig-nonlin fig-align='center' width=100%}\n:::\n:::\n\n\n\n\nWe will cover this a lot more in the multivariate stats course, so don't worry too much about it right now.  \nHowever, it's useful as a means of seeing how we can extend linear models to fit these sort of relationships. In the model on the right of @fig-nonlin, the model returns three coefficients:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 28.09831    2.88606   9.736 4.99e-16 ***\nage         18.04500    0.88602  20.366  < 2e-16 ***\nI(age^2)    -0.71034    0.05299 -13.406  < 2e-16 ***\n```\n\n\n:::\n:::\n\n\n\n\nIt is estimating a persons' height as:\n\n- an intercept of 28.1 (the estimated height of a newborn baby of age 0)\n- plus 18.04 cm for every year of age they have\n- plus -0.71 cm for every year of age they have, squared.  \n\nSo for a 4 year old, the estimated height is: \n\n$$\nheight = 28.1 + (18.04 \\times 4) + (-0.71 \\times 4^2) = 88.9\n$$\nand for a 10 year old, it is:  \n\n$$\nheight = 28.1 + (18.04 \\times 10) + (-0.71 \\times 10^2) = 138.1\n$$\nWe can see how the quadratic \"$\\text{age}^2$ term has a larger (negative) effect as age increases (for the 4 year old it makes the estimated height $-0.71 \\times 4^2 = -11.4$ lower, and for the 10 year old it makes the estimated height $-0.71 \\times 10^2 = -71$ lower). This captures the plateauing of heights as children get older.  \n\n:::\n\n<!-- # Optional: further exploration -->\n\n<!-- ## Simple Slopes -->\n\n<!-- we've kind of already done it visually.   -->\n<!-- plot the slope of y~x1 for certain values of x2.   -->\n\n<!-- we've done this visually, but it would be nice to get out a \"is y~x1 significant when x2 = ?\"   -->\n\n\n\n\n<!-- ## Johnson Neyman -->\n\n\n\n",
    "supporting": [
      "09a_interactions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}