{
  "hash": "b80a0bff5fd583d6c4f7d9d0b6b36613",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercises: GLM\"\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nBefore doing anything else, watch this video, and try to count _exactly_ how many times the players wearing white pass the basketball.    \n\n<iframe width=\"336\" height=\"189\" src=\"https://www.youtube.com/embed/vJG698U2Mvo?si=ovazszvjhjobNMUg&amp;start=5\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n# Invisible Gorillas\n\n:::frame\n__Data: invisibleg.csv__  \n\n\n\n\n\n\n\n\n\nThe data here come from a study of 483 participants who completed a Big 5 Personality Inventory (providing standardised scores on 5 personality traits of Openness, Conscientiousness, Extraversion, Agreeableness and Neuroticism), and then completed the selective attention task as seen above, from [Simons & Chabris 1999](https://doi.org/10.1068/p281059){target=\"_blank\"}.  \n\nWe're interested in whether and how individual differences in personality are associated with susceptibility to _inattentional blindness_ (i.e. not noticing the gorilla).  \n\nThe data are available at [https://uoepsy.github.io/data/invisibleg.csv](https://uoepsy.github.io/data/invisibleg.csv){target=\"_blank\"}. \n\n\n\n\n::: {#tbl-invisdict .cell layout-align=\"center\" tbl-cap='Data dictionary for invisibleg.csv'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qrrxpzzhbi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qrrxpzzhbi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qrrxpzzhbi thead, #qrrxpzzhbi tbody, #qrrxpzzhbi tfoot, #qrrxpzzhbi tr, #qrrxpzzhbi td, #qrrxpzzhbi th {\n  border-style: none;\n}\n\n#qrrxpzzhbi p {\n  margin: 0;\n  padding: 0;\n}\n\n#qrrxpzzhbi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qrrxpzzhbi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qrrxpzzhbi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qrrxpzzhbi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qrrxpzzhbi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qrrxpzzhbi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qrrxpzzhbi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qrrxpzzhbi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qrrxpzzhbi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qrrxpzzhbi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qrrxpzzhbi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qrrxpzzhbi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qrrxpzzhbi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qrrxpzzhbi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qrrxpzzhbi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qrrxpzzhbi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qrrxpzzhbi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qrrxpzzhbi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qrrxpzzhbi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qrrxpzzhbi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qrrxpzzhbi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qrrxpzzhbi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qrrxpzzhbi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qrrxpzzhbi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qrrxpzzhbi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qrrxpzzhbi .gt_left {\n  text-align: left;\n}\n\n#qrrxpzzhbi .gt_center {\n  text-align: center;\n}\n\n#qrrxpzzhbi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qrrxpzzhbi .gt_font_normal {\n  font-weight: normal;\n}\n\n#qrrxpzzhbi .gt_font_bold {\n  font-weight: bold;\n}\n\n#qrrxpzzhbi .gt_font_italic {\n  font-style: italic;\n}\n\n#qrrxpzzhbi .gt_super {\n  font-size: 65%;\n}\n\n#qrrxpzzhbi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qrrxpzzhbi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qrrxpzzhbi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qrrxpzzhbi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qrrxpzzhbi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qrrxpzzhbi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qrrxpzzhbi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qrrxpzzhbi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qrrxpzzhbi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">ppt_id</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant ID number</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">ppt_name</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Name (if recorded)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">O</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Openness (Z-scored)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">C</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Conscientiousness (Z-scored)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">E</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Extraversion (Z-scored)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">A</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Agreeableness (Z-scored)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">N</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Neuroticism (Z-scored)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">gorilla</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Whether or not participants noticed the gorilla (0 = did not notice, 1 = did notice)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\nRead in the data, have a look around, plot, describe, and generally explore.  \nDo any cleaning that you think might be necessary.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThere's nothing new to any of the data cleaning that needs done here. We can do everything that needs doing by using something like `ifelse()`.  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninvis <- read_csv(\"https://uoepsy.github.io/data/invisibleg.csv\")\n\nsummary(invis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    ppt_id            ppt_name               O                   C            \n Length:483         Length:483         Min.   :-2.786578   Min.   :-2.510626  \n Class :character   Class :character   1st Qu.:-0.687997   1st Qu.:-0.659786  \n Mode  :character   Mode  :character   Median : 0.011968   Median :-0.030208  \n                                       Mean   :-0.001907   Mean   : 0.005702  \n                                       3rd Qu.: 0.685956   3rd Qu.: 0.675251  \n                                       Max.   : 3.667985   Max.   : 3.119541  \n       E                   A                  N                gorilla        \n Min.   :-2.916437   Min.   :-3.39605   Min.   :-99.00000   Min.   :-99.0000  \n 1st Qu.:-0.678922   1st Qu.:-0.63624   1st Qu.: -0.66889   1st Qu.:  0.0000  \n Median : 0.012801   Median : 0.03289   Median :  0.01216   Median :  0.0000  \n Mean   :-0.008537   Mean   : 0.01091   Mean   : -0.81698   Mean   : -0.8468  \n 3rd Qu.: 0.693415   3rd Qu.: 0.66549   3rd Qu.:  0.71102   3rd Qu.:  1.0000  \n Max.   : 2.544318   Max.   : 2.31373   Max.   :  2.94009   Max.   :  1.0000  \n```\n\n\n:::\n:::\n\n\n\n\n\nRight away we can see there's something odd with the Neuroticism variable (`N`). It shouldn't have values of -99.  \n\nAs it happens, a well-known statistical software package ([ahem](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/SPSS_logo.svg/1200px-SPSS_logo.svg.png){target=\"_blank\"}) often ends with missing values being stored as \"-99\", or \"-999\".  \n\nWe can also see that we have some \"-99\" in the `gorilla` variable.  \n\nSo let's replace all those with NA's\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninvis <- invis |>\n  mutate(\n    N = ifelse(N == -99, NA, N),\n    gorilla = ifelse(gorilla == -99, NA, gorilla)\n  )\n\nsummary(invis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    ppt_id            ppt_name               O                   C            \n Length:483         Length:483         Min.   :-2.786578   Min.   :-2.510626  \n Class :character   Class :character   1st Qu.:-0.687997   1st Qu.:-0.659786  \n Mode  :character   Mode  :character   Median : 0.011968   Median :-0.030208  \n                                       Mean   :-0.001907   Mean   : 0.005702  \n                                       3rd Qu.: 0.685956   3rd Qu.: 0.675251  \n                                       Max.   : 3.667985   Max.   : 3.119541  \n                                                                              \n       E                   A                  N                gorilla      \n Min.   :-2.916437   Min.   :-3.39605   Min.   :-3.057349   Min.   :0.0000  \n 1st Qu.:-0.678922   1st Qu.:-0.63624   1st Qu.:-0.630916   1st Qu.:0.0000  \n Median : 0.012801   Median : 0.03289   Median : 0.016932   Median :0.0000  \n Mean   :-0.008537   Mean   : 0.01091   Mean   : 0.002915   Mean   :0.3878  \n 3rd Qu.: 0.693415   3rd Qu.: 0.66549   3rd Qu.: 0.724583   3rd Qu.:1.0000  \n Max.   : 2.544318   Max.   : 2.31373   Max.   : 2.940095   Max.   :1.0000  \n                                        NA's   :4           NA's   :6       \n```\n\n\n:::\n:::\n\n\n\n\nThere's not a great deal to describe here, because our variables are already Z-scored (i.e. they all have means of 0 and standard deviations of 1).  \n\nIt's still important to look at our data though: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npsych::pairs.panels(invis)\n```\n\n::: {.cell-output-display}\n![](10_ex_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nAnd we can tabulate the number of participants that do/don't notice the gorilla:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(invis$gorilla)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  0   1 \n292 185 \n```\n\n\n:::\n:::\n\n\n\nOnly 39% of people noticed the gorilla!  \n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nHere is an \"intercept-only\" model of the binary outcome 'did they notice the gorilla or not':  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglm(gorilla ~ 1, data = invis, family=binomial) |>\n  summary()\n```\n:::\n\n\n\n```\n...\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -0.45640    0.09397  -4.857 1.19e-06 ***\n```\n\n1. Convert the intercept estimate from **log-odds** into **odds**  \n2. Convert those **odds** into **probability**  \n3. What does that probability represent?  \n    - *hint:* in `lm(y~1)` the intercept is the same as `mean(y)`\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n\n\n\n\n\n\nThe intercept estimate of -0.456 is in log-odds.  \n  \nTo convert from log-odds to odds, we exponentiate ($odds = e^{log-odds}$)  \n\nThe odds of noticing the gorilla are $e^{-0.456} = 0.634$.   \n  \nTo convert this back to probability, we calculate $\\frac{odds}{1+odds}$.  \n\n$\\frac{0.634}{1.634} = 0.388$.  \n\nSo there is a 0.388 probability of a participant noticing the gorilla.  \n\nDoes this number seem familiar?  \nBecause there's no predictors in the model, our intercept is just the proportion of 1s in our outcome variable!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprop.table(table(invis$gorilla))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n        0         1 \n0.6121593 0.3878407 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\nDoes personality (i.e. all our measured personality traits collectively) predict inattentional blindness?  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nWe're wanting to test the influence of a _set_ of predictors here. Sounds like a job for model comparison! (see [10A #comparing-models](10a_glm.html#comparing-models){target=\"_blank\"}).    \n\nBUT WAIT... we might have some missing data...  \n_(this depends on whether, during your data cleaning, you a) replaced values of -99 with `NA`, or b) removed those entire rows from the data)._  \n\nModels like `lm()` and `glm()` will exclude any observation (the entire row) if it has a missing value for _any_ variable in the model (outcome _or_ predictor). As we have missing data on the `N` variable, then when we put that in as a predictor, those rows are omitted from the model.  \n\nSo we'll need to ensure that _both_ models that we are comparing are fitted to exactly the same set of observations.\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-1' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-1', 'sol-start-1')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-1\" style=\"display: none;\">\n\n\n\nIf we just try a comparison, we get an error:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm0 <- glm(gorilla ~ 1, data = invis, family=binomial)\nm1 <- glm(gorilla ~ O+C+E+A+N, data = invis, family=binomial)\nanova(m0,m1, test=\"Chisq\")\n```\n:::\n\n\n\n<p style=\"color:red;font-size:.8em\">Error in anova.glmlist(c(list(object), dotargs), dispersion = dispersion,  :<br> \n  models were not all fitted to the same size of dataset</p>\n  \nSo what we need to do is fit both models to the data that has values for all of the variables in our full model.  \n\nIf you haven't discovered it already, `na.omit(dataset)` is a quick way to remove all rows that have incomplete data.  \n\nBut we need to be careful - if we just use `na.omit()` on the _entire_ dataset, then we could be removing a whole load of data that is actually perfectly useful to us:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# number of rows in entire dataset:\ninvis |> nrow()\n# number of rows with complete data:\nna.omit(invis) |> nrow()\n# number of rows with complete data in the variables we're using in model:\nna.omit(invis[,3:8]) |> nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 483\n[1] 411\n[1] 473\n```\n\n\n:::\n:::\n\n\n\n\nWe can see that if we just used `na.omit(invis)` here, we would be removing 72 people. As it happens, this is excluding a whole bunch of participants for whom their names are missing. But we're not using their names, so we can actually use these in our model!\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmoddat <- na.omit(invis[,3:8])\n\nm0 <- glm(gorilla ~ 1, data = moddat,\n          family=binomial)\nm1 <- glm(gorilla ~ O+C+E+A+N, data = moddat, \n          family=binomial)\n\nanova(m0,m1, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: gorilla ~ 1\nModel 2: gorilla ~ O + C + E + A + N\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1       472     631.30                          \n2       467     608.23  5   23.067 0.0003278 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n:::int\nThe inclusion of the Big 5 Personality Traits (Openness, Conscientiousness, Extraversion, Agreeablenss and Neuroticism) were found to result in a significant improvement in model fit over the null model ($\\chi^2(5)=23.07, p<0.001$), suggesting that personality is useful in predicting inattentional blindness. \n:::\n  \n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\nHow are different aspects of personality associated with inattentional blindness?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThe interpretation of logistic regression coefficients is explained in [10A #coefficient-interpretation](10a_glm.html#coefficient-interpretation){target=\"_blank\"}.  \n\nYou might want to explain the key finding(s) in terms of odds ratios.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nThe coefficients we get from our model are in log-odds. So values $<0$ represent decreasing probability, and values $>0$ represent increasing probability.  \n\nBut that's about as much as we can interpret in this scale.  \nWhen we exponentiate them, we get our odds-ratios. These are \"how much the odds are multiplied by\", so values $<1$ represent decreased odds (i.e. decreasing probability) and values $>1$ represent increased odds.  \n\nOnly Openness (`O`) is significantly associated with the probability of noticing the gorilla.  \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mtwycqemag\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mtwycqemag table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mtwycqemag thead, #mtwycqemag tbody, #mtwycqemag tfoot, #mtwycqemag tr, #mtwycqemag td, #mtwycqemag th {\n  border-style: none;\n}\n\n#mtwycqemag p {\n  margin: 0;\n  padding: 0;\n}\n\n#mtwycqemag .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mtwycqemag .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mtwycqemag .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mtwycqemag .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mtwycqemag .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mtwycqemag .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mtwycqemag .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mtwycqemag .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mtwycqemag .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mtwycqemag .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mtwycqemag .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mtwycqemag .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mtwycqemag .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mtwycqemag .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mtwycqemag .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mtwycqemag .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mtwycqemag .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mtwycqemag .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mtwycqemag .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mtwycqemag .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mtwycqemag .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mtwycqemag .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mtwycqemag .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mtwycqemag .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mtwycqemag .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mtwycqemag .gt_left {\n  text-align: left;\n}\n\n#mtwycqemag .gt_center {\n  text-align: center;\n}\n\n#mtwycqemag .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mtwycqemag .gt_font_normal {\n  font-weight: normal;\n}\n\n#mtwycqemag .gt_font_bold {\n  font-weight: bold;\n}\n\n#mtwycqemag .gt_font_italic {\n  font-style: italic;\n}\n\n#mtwycqemag .gt_super {\n  font-size: 65%;\n}\n\n#mtwycqemag .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mtwycqemag .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mtwycqemag .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mtwycqemag .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mtwycqemag .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mtwycqemag .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mtwycqemag .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mtwycqemag .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mtwycqemag div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"coefficient\">coefficient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"b\">b</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"exp(b)\">exp(b)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"interpretation\">interpretation</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"b\" class=\"gt_row gt_right\">-0.48***</td>\n<td headers=\"exp(b)\" class=\"gt_row gt_right\">0.62***</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">for someone at the mean on all personality traits, the odds of noticing the gorilla are 0.62 to 1</td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">O</td>\n<td headers=\"b\" class=\"gt_row gt_right\">0.38***</td>\n<td headers=\"exp(b)\" class=\"gt_row gt_right\">1.46***</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">holding other personality traits constant, being 1 SD higher on openness is associated with 1.46 times the odds of noticing the gorilla</td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">C</td>\n<td headers=\"b\" class=\"gt_row gt_right\">-0.19</td>\n<td headers=\"exp(b)\" class=\"gt_row gt_right\">0.82</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\"></td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">E</td>\n<td headers=\"b\" class=\"gt_row gt_right\">0.17</td>\n<td headers=\"exp(b)\" class=\"gt_row gt_right\">1.18</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\"></td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">A</td>\n<td headers=\"b\" class=\"gt_row gt_right\">0.07</td>\n<td headers=\"exp(b)\" class=\"gt_row gt_right\">1.07</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\"></td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">N</td>\n<td headers=\"b\" class=\"gt_row gt_right\">-0.13</td>\n<td headers=\"exp(b)\" class=\"gt_row gt_right\">0.88</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\"></td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\nCompute confidence intervals for your odds ratios.  \n\n::: {.callout-tip collapse=\"true\"}\n#### confidence interval refresher\n\nWe haven't been using confidence intervals very much, but we very easily could have been. Functions like `t.test()`, `cor.test()` etc present confidence intervals in their output, and functions like `confint()` can be used on linear regression models to get confidence intervals for our coefficients.  \n\nConfidence intervals (CIs) are often used to make a statement about a null hypothesis _just like_ a p-value (see [3A #inference](03a_inference.html#null-hypothesis-significance-testing-nhst){target=\"_blank\"}. If a 95% CI does not contain zero then we can, with that same level of confidence, reject the null hypothesis that the population value is zero. So a 95% confidence interval maps to $p<.05$, and a 99% CI maps to $p<.01$, and so on.  \n\nHowever, many people these days prefer confidence intervals to $p$-values as they take the focus (slightly) away from the null hypothesis and toward a range of effect sizes that are compatible with the data.  \n\nThe function `confint()` will give you confidence intervals. The function `car::Confint()`^[the colon here means \"look in the **car** package and use the `Confint()` function. It saves having to load the package with `library(car)`] will do exactly the same but put them alongside the estimates (which saves you scrolling up and down between different outputs).  \n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexp(car::Confint(m1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Estimate     2.5 %    97.5 %\n(Intercept) 0.6174089 0.5093876 0.7459179\nO           1.4572206 1.1922054 1.7917164\nC           0.8244801 0.6719649 1.0086947\nE           1.1830867 0.9777058 1.4362320\nA           1.0712494 0.8782219 1.3084848\nN           0.8785279 0.7189474 1.0716537\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n:::int\nholding other personality traits constant, being 1 SD higher on openness is associated with 1.46 (95% CI: 1.19, 1.79) times the odds of noticing the gorilla\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\nProduce a plot of the predicted probabilities of noticing the gorilla as a function of openness.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThere's an example of this at [10A #visualising](10a_glm.html#visualising){target=\"_blank\"}. Using the __effects__ package will be handy.  \n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nthe `xlevels` argument here says to give us the fitted values for 20 different values across the predictor  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effects)\n\neffect(term = \"O\", mod = m1, xlevels = 20) |>\n  as.data.frame() |>\n  ggplot(aes(x=O,y=fit,ymin=lower,ymax=upper))+\n  geom_line()+\n  geom_ribbon(alpha=.3)\n```\n\n::: {.cell-output-display}\n![](10_ex_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\nTry creating an equivalent plot for the other personality traits - before you do, what do you expect them to look like?  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nFrom our coefficients, we should expect the lines to go *up* as E and A increase, and *down* as C and N increase.  \nHowever, for all of these, we should expect a lot of uncertainty (i.e. for all of these, 0 is inside our confidence intervals (i.e. they're non-significant))  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncar::Confint(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate       2.5 %       97.5 %\n(Intercept) -0.48222369 -0.67454599 -0.293139778\nO            0.37653095  0.17580488  0.583174041\nC           -0.19300227 -0.39754917  0.008657158\nE            0.16812690 -0.02254645  0.362022998\nA            0.06882561 -0.12985594  0.268869789\nN           -0.12950767 -0.32996703  0.069202969\n```\n\n\n:::\n:::\n\n\n\n\ne.g., for extraversion:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(patchwork)\nplte <- effect(term = \"E\", mod = m1, xlevels = 20) |>\n  as.data.frame() |>\n  ggplot(aes(x=E,y=fit,ymin=lower,ymax=upper))+\n  geom_line()+\n  geom_ribbon(alpha=.3)\n\npltc <- effect(term = \"C\", mod = m1, xlevels = 20) |>\n  as.data.frame() |>\n  ggplot(aes(x=C,y=fit,ymin=lower,ymax=upper))+\n  geom_line()+\n  geom_ribbon(alpha=.3)\n\npltn <- effect(term = \"N\", mod = m1, xlevels = 20) |>\n  as.data.frame() |>\n  ggplot(aes(x=N,y=fit,ymin=lower,ymax=upper))+\n  geom_line()+\n  geom_ribbon(alpha=.3)\n\nplta <- effect(term = \"A\", mod = m1, xlevels = 20) |>\n  as.data.frame() |>\n  ggplot(aes(x=A,y=fit,ymin=lower,ymax=upper))+\n  geom_line()+\n  geom_ribbon(alpha=.3)\n\n(plte + plta) / (pltn + pltc)\n```\n\n::: {.cell-output-display}\n![](10_ex_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n# Invisible Marshmallows\n\n:::frame\n__Data: mallow2.csv__ \n\n\n\n\n\n\n\n\n\nWe already played with some marshmallow-related data in [reading 10A](10a_glm.html#fitting-glm-in-r){target=\"_blank\"}. Here we are extending this study to investigate whether the visibility of the immediate reward moderates age effects on the ability to delay gratification (the ability to forgo an immediate reward for a greater reward at a later point).  \n\n304 children took part, ranging in ages from 3 to 10 years old. Each child was shown a marshmallow, and it was explained that they were about to be left alone for 10 minutes. They were told that they were welcome to eat the marshmallow while they were waiting, but if the marshmallow was still there after 10 minutes, they would be rewarded with __two__ marshmallows.  \n\nFor half of the children who took part, the marshmallow was visible for the entire 10 minutes (or until they ate it!). For the other half, the marshmallow was placed under a plastic cup.  \n\nThe experiment took part at various times throughout the working day, and researchers were worried about children being more hungry at certain times of day, so they kept track of whether each child completed the task in the morning or the afternoon, so that they could control for this in their analyses.  \n\nThe data are available at [https://uoepsy.github.io/data/mallow2.csv](https://uoepsy.github.io/data/mallow2.csv){target=\"_blank\"}. \n\n\n\n\n::: {#tbl-mallow2dict .cell layout-align=\"center\" tbl-cap='Data dictionary for mallow2.csv'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wzpjrqhjrk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wzpjrqhjrk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wzpjrqhjrk thead, #wzpjrqhjrk tbody, #wzpjrqhjrk tfoot, #wzpjrqhjrk tr, #wzpjrqhjrk td, #wzpjrqhjrk th {\n  border-style: none;\n}\n\n#wzpjrqhjrk p {\n  margin: 0;\n  padding: 0;\n}\n\n#wzpjrqhjrk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wzpjrqhjrk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wzpjrqhjrk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wzpjrqhjrk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wzpjrqhjrk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wzpjrqhjrk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wzpjrqhjrk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wzpjrqhjrk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wzpjrqhjrk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wzpjrqhjrk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wzpjrqhjrk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wzpjrqhjrk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wzpjrqhjrk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wzpjrqhjrk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wzpjrqhjrk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wzpjrqhjrk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wzpjrqhjrk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wzpjrqhjrk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wzpjrqhjrk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wzpjrqhjrk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wzpjrqhjrk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wzpjrqhjrk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wzpjrqhjrk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wzpjrqhjrk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wzpjrqhjrk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wzpjrqhjrk .gt_left {\n  text-align: left;\n}\n\n#wzpjrqhjrk .gt_center {\n  text-align: center;\n}\n\n#wzpjrqhjrk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wzpjrqhjrk .gt_font_normal {\n  font-weight: normal;\n}\n\n#wzpjrqhjrk .gt_font_bold {\n  font-weight: bold;\n}\n\n#wzpjrqhjrk .gt_font_italic {\n  font-style: italic;\n}\n\n#wzpjrqhjrk .gt_super {\n  font-size: 65%;\n}\n\n#wzpjrqhjrk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wzpjrqhjrk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wzpjrqhjrk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wzpjrqhjrk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wzpjrqhjrk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wzpjrqhjrk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wzpjrqhjrk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wzpjrqhjrk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wzpjrqhjrk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Name</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">agemonths</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age in months</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">timeofday</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Time of day that the experiment took place ('am' = morning, 'pm' = afternoon)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">visibility</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Experimental condition - whether the marshmallow was 'visible' or 'hidden' for the 10 minutes</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">taken</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Whether or not the participant took the marshmallow within the 10 minutes</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\nRead in the data, check, clean, plot, describe, explore.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- It's good practice to set categorical variables as factors (see [](){target=\"_blank\"}).  \n- It might be easier to transform age into years rather than months (up to you!)\n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution Part 1 - Check</button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmallow2 <- read_csv(\"https://uoepsy.github.io/data/mallow2.csv\")\n```\n:::\n\n\n\n\nWe've only got one numeric variable here (age), so I'm going to plot that, and then tabulate the rest: \n\nSomething looks odd here.. a couple of very old children!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(mallow2$agemonths)\n```\n\n::: {.cell-output-display}\n![](10_ex_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nAccording to the design, our age range should be 3 to 10 years old. So here are all the participants over 10 years old (i.e. over 120 months old):  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmallow2[mallow2$agemonths>120, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  name   agemonths timeofday visibility taken \n  <chr>      <dbl> <chr>     <chr>      <chr> \n1 Martin       636 am        hidden     taken \n2 Josiah       396 pm        visible    waited\n```\n\n\n:::\n:::\n\n\n\nAha... who knows how they got in there! We'll deal with them in a minute.. \n\nThe `visibility` variable looks as we would expect - half in each condition:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(mallow2$visibility)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n hidden visible \n    152     152 \n```\n\n\n:::\n:::\n\n\n\n\nThis looks off.. we have one mis-coded as \"5 pm\", which I'm guessing should just be \"pm\". And we have one at \"noon\". There's no way of knowing whether that was morning or afternoon, so I would be inclined to remove it.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(mallow2$timeofday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n5 pm   am noon   pm \n   1  145    1  157 \n```\n\n\n:::\n:::\n\n\n\n\nAnd we can see that our outcome variable has got 2 unique values, which is what we expect.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(mallow2$taken)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n taken waited \n   136    168 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-3' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution Part 2 - Clean</button></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\nSo we need to:\n\n1. replace \"5 pm\" with \"pm\" in `timeofday`\n2. remove \"noon\" with `NA` in `timeofday` \n3. remove Martin and Josiah.. they are not the population we're interested in... \n4. make any appropriate variables factors (good practice!)\n5. while we're there - I think I'll also make an `age` variable that is in years rather than months\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmallow2 <- \n  mallow2 |>\n    mutate(\n      age = agemonths/12,\n      timeofday = factor(timeofday, \n                         levels=c(\"am\",\"pm\",\"5 pm\"), # possible levels\n                         labels = c(\"am\",\"pm\",\"pm\")), # make the levels these\n      visibility = factor(visibility, \n                          levels=c(\"visible\",\"hidden\")),\n      taken = factor(taken, \n                     levels=c(\"waited\",\"taken\"))\n    ) |>\n  filter(agemonths <= 120, !is.na(timeofday))\n```\n:::\n\n\n\n\n**KEEP TRACK**  \nWe've removed 3 observations entirely from the data. \nTwo of these (Martin & Josiah) were clearly not representative of the population of interest. The other was one that had an unclear `timeofday` value. If we replaced it with `NA`, any analysis using that variable would not include that observation. And since we know we're going to use `timeofday` in our analysis (and since it's just 1 participant), it may be cleaner to just to start with a complete data.  \n\nWhen writing up, we would want to:\n\n1. Detail any removal of observations and the reasons for doing so.  \n2. Describe the final dataset (if the final dataset contains `NA`s, then it's also worth providing descriptions of the patterns of missingness).  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-4' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution Part 3 - Describe & Explore</button></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmallow2 |>\n  group_by(visibility) |>\n  summarise(\n    n = n(),\n    mean_age = mean(age),\n    sd_age = sd(age),\n    percent_pm = sum(timeofday==\"pm\")/n()*100,\n    percent_taken = sum(taken==\"taken\")/n()*100\n  ) |>\n  gt::gt() # this just a nice way to prettify tables \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"unypavgdib\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#unypavgdib table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#unypavgdib thead, #unypavgdib tbody, #unypavgdib tfoot, #unypavgdib tr, #unypavgdib td, #unypavgdib th {\n  border-style: none;\n}\n\n#unypavgdib p {\n  margin: 0;\n  padding: 0;\n}\n\n#unypavgdib .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#unypavgdib .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#unypavgdib .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#unypavgdib .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#unypavgdib .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#unypavgdib .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#unypavgdib .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#unypavgdib .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#unypavgdib .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#unypavgdib .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#unypavgdib .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#unypavgdib .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#unypavgdib .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#unypavgdib .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#unypavgdib .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#unypavgdib .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#unypavgdib .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#unypavgdib .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#unypavgdib .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#unypavgdib .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#unypavgdib .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#unypavgdib .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#unypavgdib .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#unypavgdib .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#unypavgdib .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#unypavgdib .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#unypavgdib .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#unypavgdib .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#unypavgdib .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#unypavgdib .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#unypavgdib .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#unypavgdib .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#unypavgdib .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#unypavgdib .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#unypavgdib .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#unypavgdib .gt_left {\n  text-align: left;\n}\n\n#unypavgdib .gt_center {\n  text-align: center;\n}\n\n#unypavgdib .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#unypavgdib .gt_font_normal {\n  font-weight: normal;\n}\n\n#unypavgdib .gt_font_bold {\n  font-weight: bold;\n}\n\n#unypavgdib .gt_font_italic {\n  font-style: italic;\n}\n\n#unypavgdib .gt_super {\n  font-size: 65%;\n}\n\n#unypavgdib .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#unypavgdib .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#unypavgdib .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#unypavgdib .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#unypavgdib .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#unypavgdib .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#unypavgdib .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#unypavgdib .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#unypavgdib div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"visibility\">visibility</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_age\">mean_age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd_age\">sd_age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"percent_pm\">percent_pm</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"percent_taken\">percent_taken</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"visibility\" class=\"gt_row gt_center\">visible</td>\n<td headers=\"n\" class=\"gt_row gt_right\">150</td>\n<td headers=\"mean_age\" class=\"gt_row gt_right\">6.596667</td>\n<td headers=\"sd_age\" class=\"gt_row gt_right\">1.820964</td>\n<td headers=\"percent_pm\" class=\"gt_row gt_right\">50.66667</td>\n<td headers=\"percent_taken\" class=\"gt_row gt_right\">56.00000</td></tr>\n    <tr><td headers=\"visibility\" class=\"gt_row gt_center\">hidden</td>\n<td headers=\"n\" class=\"gt_row gt_right\">151</td>\n<td headers=\"mean_age\" class=\"gt_row gt_right\">6.525938</td>\n<td headers=\"sd_age\" class=\"gt_row gt_right\">1.922869</td>\n<td headers=\"percent_pm\" class=\"gt_row gt_right\">53.64238</td>\n<td headers=\"percent_taken\" class=\"gt_row gt_right\">33.11258</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\nFit a model that you can use to address the research aims of the study.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nTake a look back at the description of the study.  \n\n- What are we wanting to find out? How can we operationalise this into a model?   \n  - *hint:* 'moderation' is another word for 'interaction'.  \n- Is there anything that we think it is important to account for? \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmm1 <- glm(taken ~ timeofday + age * visibility, data = mallow2, family = binomial)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 11</div><div class='question-body'>\n\n\nWhat do you conclude?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Remember...  \n\nWhen you have an interaction `Y ~ X1 + X2 + X3 + X2:X3` in your model, the coefficients that involved in the interaction (`X2` and `X3`) represent the associations _when_ the other variable in the interaction is zero.  \nThe interaction coefficient itself represents the *adjustment* to these associations when we move up 1 in the other variable.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-5' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\nHere are the coefficients from the model we have fitted. We've exponentiated them so that they are in odds ratios.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexp(car::Confint(mm1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         Estimate        2.5 %       97.5 %\n(Intercept)          560.14617820 83.620250311 4934.3779476\ntimeofdaypm            0.64074627  0.354154685    1.1383851\nage                    0.41993953  0.312221939    0.5440124\nvisibilityhidden       0.01193413  0.001120213    0.1058236\nage:visibilityhidden   1.64076760  1.189141035    2.3113652\n```\n\n\n:::\n:::\n\n\n\n\nFrom our coefficients, it looks like when the marshmallow is visible, the odds of taking the marshmallow are more than halved (0.42) for every year older a child is.  \n\nCompared to when the marshmallow is visible, the odds ratio associated with every additional year of age is 1.64 times bigger in the hidden-marshmallow condition.  \n\nThis is a bit of a weird one to think about, but it means that instead of having an OR of 0.42 (as we do for the visible condition), for the hidden condition we have an OR that is $0.42 \\times 1.64 = 0.69$.  \n\nThis is almost always going to be more easily presented as a plot of predicted probabilities:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_ex_files/figure-html/unnamed-chunk-34-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 12</div><div class='question-body'>\n\n\nWrite up the methods and results, providing a plot and regression table.  \n\nA template RMarkown file can be found at [https://uoepsy.github.io/usmr/2324/misc/marshmallows.Rmd](https://uoepsy.github.io/usmr/2324/misc/marshmallows.Rmd){target=\"_blank\"} if you want it. It contains a list of questions try and make sure you answer in your write-up.  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n# Optional Extras\n\n\n\n<div class='question-begin'>Question 13</div><div class='question-body'>\n\n\nBelow is the background and design to a study investigating how different types of more active learning strategies improve understanding, in comparison to just studying materials.  \n\nFit an appropriate model to address the research aims, interpret it, make a plot, etc.  \n\n::: {.callout-note collapse=\"true\"}\n#### immersivelearning.csv  \n\nAn experiment was run to investigate strategies for learning. Three groups of 30 participants were presented with materials on a novel language to learn.  \n\nAll groups were given two hours of preparation time, after which their learning was assessed. The first group (`studystudy`) spent both hours studying the materials. The second group (`studytest`) spent the first hour studying the materials, and the second hour testing themselves on the materials. The third group (`studyimmersion`) spent the first hour studying the materials, and the second hour trying to converse with a native speaker of the language (they were not permitted to attempt to converse in any other language during this time).  \n\nAfter the two hours were up, participants were the assessed via a series of 30 communication tasks. The number of tasks each participant got correct was recorded.  \n\nInformation on two potential covariates was also included - previous language learning experience (novice/experienced), and cognitive aptitude (a 20 item questionnaire leading to a standardised test score).  \n\nThe data are available at [https://uoepsy.github.io/data/immersivelearning.csv](https://uoepsy.github.io/data/immersivelearning.csv){target=\"_blank\"}. \n\n\n\n\n::: {#tbl-immersedict .cell layout-align=\"center\" tbl-cap='Data dictionary: immersivelearning.csv'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vaosbtmugr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vaosbtmugr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vaosbtmugr thead, #vaosbtmugr tbody, #vaosbtmugr tfoot, #vaosbtmugr tr, #vaosbtmugr td, #vaosbtmugr th {\n  border-style: none;\n}\n\n#vaosbtmugr p {\n  margin: 0;\n  padding: 0;\n}\n\n#vaosbtmugr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vaosbtmugr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vaosbtmugr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vaosbtmugr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vaosbtmugr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vaosbtmugr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vaosbtmugr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vaosbtmugr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vaosbtmugr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vaosbtmugr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vaosbtmugr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vaosbtmugr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vaosbtmugr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vaosbtmugr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vaosbtmugr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vaosbtmugr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vaosbtmugr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vaosbtmugr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vaosbtmugr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vaosbtmugr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vaosbtmugr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vaosbtmugr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vaosbtmugr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vaosbtmugr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vaosbtmugr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vaosbtmugr .gt_left {\n  text-align: left;\n}\n\n#vaosbtmugr .gt_center {\n  text-align: center;\n}\n\n#vaosbtmugr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vaosbtmugr .gt_font_normal {\n  font-weight: normal;\n}\n\n#vaosbtmugr .gt_font_bold {\n  font-weight: bold;\n}\n\n#vaosbtmugr .gt_font_italic {\n  font-style: italic;\n}\n\n#vaosbtmugr .gt_super {\n  font-size: 65%;\n}\n\n#vaosbtmugr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vaosbtmugr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vaosbtmugr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vaosbtmugr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vaosbtmugr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vaosbtmugr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vaosbtmugr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vaosbtmugr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vaosbtmugr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">PID</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant ID number</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">group</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Experimental group (studystudy = 2 hours of study, studytest = 1 hour study, 1 hour testing, studyimmersion = 1 hour study, 1 hour conversing)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">plle</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Previous language learning experience (novice or experienced)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">cog_apt</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Cognitive Aptitude (Standardised Z Score)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">n_correct</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of the 30 communication tasks that each participant correctly completed</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- This might not be binary (0 or 1), but it's binomial (\"how many success in 30 trials\").  \n- See the optional box under logistic regression in [10A #fitting-glm-in-r](10a_glm.html#fitting-glm-in-r){target=\"_blank\"} for how to fit a binomial model to data like this.   \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nBelow is the code *we* would use to investigate this. Some of these decisions you might make differently, and that is okay - the important thing is to clearly explain and justify the decision we make.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nimmers <- read_csv(\"https://uoepsy.github.io/data/immersivelearning.csv\")\n\nimmers <- immers |> mutate(\n  fct_relevel(factor(group), \"studystudy\")\n)\n\nmst1 = glm(cbind(n_correct,30-n_correct) ~ plle+cog_apt+group,\n    data = immers, family=binomial)\n\nsummary(mst1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cbind(n_correct, 30 - n_correct) ~ plle + cog_apt + \n    group, family = binomial, data = immers)\n\nCoefficients:\n                Estimate Std. Error z value Pr(>|z|)    \n(Intercept)      0.60154    0.10591   5.680 1.35e-08 ***\npllenovice      -0.10897    0.09905  -1.100    0.271    \ncog_apt         -0.03194    0.03725  -0.857    0.391    \ngroupstudystudy -1.02919    0.09798 -10.504  < 2e-16 ***\ngroupstudytest  -0.51064    0.09661  -5.286 1.25e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 644.49  on 89  degrees of freedom\nResidual deviance: 529.99  on 85  degrees of freedom\nAIC: 862.24\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\neffect(term = \"group\", mod = mst1) |>\n  as.data.frame() |>\n  ggplot(aes(x=group, y=fit,ymin=lower,ymax=upper))+\n  geom_pointrange()\n```\n\n::: {.cell-output-display}\n![](10_ex_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 14</div><div class='question-body'>\n\n\nPeople and behaviours are a lot more difficult to predict than something like, say, the colour of different wines. \n\nBuild a model that predicts the colour of wine based on all available information. How accurately can it predict wine colours?  \n\n*(Generally speaking, this question doesn't reflect how we do research in psychology. Ideally, we would have a theoretical question that motivates the inclusion (and testing of) specific predictors.)*\n\n::: {.callout-note collapse=\"true\"}\n#### usmr_wines.csv\n\nYou can download a dataset of 6497 different wines (1599 red, 4898 white) from [https://uoepsy.github.io/data/usmr_wines.csv](https://uoepsy.github.io/data/usmr_wines.csv).  \n\nIt contains information on various physiochemical properties such as pH, a measure of level of sulphates, residual sugar, citric acid, volatile acidity and alcohol content, and also quality ratings from a sommelier (wine expert).  All the wines are vinho verde from Portugal, and the data was collected between 2004 and 2007.  \n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- `glm(outcome ~ ., data = mydata)` is a shorthand way of putting _all_ variables in the data in as predictors.  \n- See [the lecture slides](https://uoepsy.github.io/usmr/2324/lectures/lecture09.html#/accuracy){target=\"_blank\"} for an example of how we can get a number for \"how accurately can my model predict\".  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nBelow is the code *we* would use to investigate this. Some of these decisions you might make differently, and that is okay - the important thing is to clearly explain and justify the decision we make.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwines <- read_csv(\"https://uoepsy.github.io/data/usmr_wines.csv\")\n\nwines <- \n  wines |> \n  mutate(\n    col = factor(col, levels=c(\"white\",\"red\"))\n  )\n\nwinemod <- glm(col ~ ., data = wines, family = binomial)\n\n# in logit units\nguess <- predict(winemod)\n# logit 0 is p of .5:\nguess <- ifelse(guess > 0, \"red\", \"white\")\n# how many predicted colours match the observed colours??\nhits <- sum(guess == wines$col)\n# what percentage?  \nhits/length(wines$col)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.936894\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "10_ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}