---
title: "Sums of Squares"
bibliography: references.bib
biblio-style: apalike
link-citations: yes
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---

```{r setup, include=FALSE}
source('assets/setup.R')
library(tidyverse)
library(patchwork)
```


# Model Building

We've learned about how to specify the structure of linear regression models to address different types of research question, and we've talked about the different hypothesis tests that we can perform with these models. For instance, we can test whether a specific slope is different from zero (the coefficients in `summary()`), or test the improvement in model fit (by reduction in sums of squared residuals) gained from the addition of one (or several) predictors (model comparison with `anova(model1, model2)`).
But all this supposes that we already know what to include in our model.

typically interested in one or more specific predictors, or an interaction.
may mention specific things to "control for" (e.g. to also take into account).

to use a model to predict the world:
shove everything, keep whatever sticks


to use a model to explain the world:
include variables which theoretically make sense as influencing the outcome
don't simply exclude predictors that are not significant
don't throw the kitchen sink at it. parsimony is also good
remember the research question
it may help to think of predictors in sets (e.g. demographic, historical)