{
  "hash": "0ab839724f7d935b43abc39b7c42ed91",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 11 Exercises: Tying up Loose Ends\"\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n\n:::lo\n__Please Note__\n\nThis might look like a lot of stuff, but it is just writing, bit by bit, the stuff that we have covered through the course. \n\nWhen writing up -- most important is to think carefully about what the questions are really asking (and therefore what kind of test might be appropriate), and to explain your analytical process as clearly as you can, pulling out and interpreting the key information from the models that help to guide the reader to your conclusion.\n\n<!-- **NOTE** This is not a \"perfect\" answer (I may well have made mistakes, or have written certain sections unclearly). -->\nWith regards to the coursework report, there are marks available even if you don't get all of the \"bits\"\n\n:::\n\n\n\n# Couch to 5k\n\n:::frame\n\n__Background: Couch to 5k__  \n\n[Couch to 5k](https://www.nhs.uk/live-well/exercise/get-running-with-couch-to-5k/) is an NHS-sponsored fitness programme which lasts 9 weeks, taking participants from a gentle start up to a half-hour run.  \n\nThe NHS wants to research some of the potential impact this programme has on wellbeing. They have conducted a small study of 121 people in 2 cities (Edinburgh and Glasgow), all of whom started the Couch to 5k programme, across the course of a year.  \n\nThe researchers' interests are two-fold: They are interested in the effects of taking the programme on psychological wellbeing, and also in the psychological factors that make people continue on the programme. \n\n__Methods__  \n\nAt Week 0, all participants completed a questionnaire measuring the psychometric factors of accountability and self-motivation.  \nUpon either completing the programme (Week 9) or dropping out (< Week 9), participants completed a questionnaire which included a measure of their self-reported happiness, and a \"health\" measure derived from a number of physiological tests. Researchers also recorded the season in which participants started the programme, as evidence from previous research suggests that the probability of completing the couch to 5k programme varies substantially across the year. \n\nYou can download the dataset from [https://uoepsy.github.io/data/couchto5k.csv](https://uoepsy.github.io/data/couchto5k.csv). Details of the variables can be found in the table below.    \n  \n_Please note that Couch to 5k is a real programme, but the data you will be analysing comes from our febrile minds._  \n  \n---\n\n__Data Dictionary:__\n\nColumn    | Content\n----------|-------------\n`pptID`   | random ID code for participant\n`age`     | age in years\n`accountability` | psychometric measure of accountability (or 'responsibility') (Sum of 5 questions, each scored 1-7). \n`selfmot` | psychometric measure of self-motivation (Sum of 5 questions, each scored 1-7)\n`health`  | multi-test health measure (0-100)\n`happiness` | simple happiness scale (0-100)\n`season`  | season of the year participants were interviewed in\n`city`    | city participant was recruited in\n`week_stopped` | week of programme participant stopped in (week 9 = completed the programme)\n\n\n:::\n\n<br>  \n\n## Clean and describe\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nHave a look at the data. Check for impossible values and deal with these in an appropriate manner. Describe the data, either in words or using suitable graphs (or a combination).  \n\nWrite it up! Remember to detail the decisions you have made.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- to clean data, go through each variable in turn. If numeric, what is the min and max? If categorical, what are the possible levels?  \n- to describe data, you might want to use tables and plots, or you might find describing in text can work too.  \n- There's no right way to deal with missing values. \n  - one option is to cross-tabulate the _reasons for_ missingness, and then remove them from the dataset at this point. This means all your analyses are conducted on the same set of \"complete cases\". This can be the neat and tidy option, but if some variables have lots of missingness, you might end up needlessly limiting some of your analyses in terms of statistical power. \n  - another option is to leave all missing values in the dataset and let them be dealt with by each of your model(s) and test(s). The downside of this is that different tests end up being performed on different subsets of data, making it harder to describe (it also means you need to be very careful with model comparisons)\n- There's no right way to deal with outliers.  \n  - Some fields of research will identify at the outset any observations that are outlying by looking at each variable individually. These they will then remove, or scale back ([6A #outliers](06_wt.html#outliers){target=\"_blank\"}) prior to any analysis. This should really only be done if you are sure that these observations are outlying because of either a) measurement error or b) not belonging to the target population of interest. If the outlyingness could well simply be natural variation in the variable, keep it in. You can always then examine its influence on subsequent analyses!  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncouchto5k <- read_csv(\"https://uoepsy.github.io/data/couchto5k.csv\")\n```\n:::\n\n\n\n\n\nGoing through each variable:  \n\n- `age` is an integer variable, shouldn't have negative values **by definition of variable**. There are a couple of values $\\geq 100$, which we should probably either exclude, or at the very least mention in our writing. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(couchto5k$age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  18.00   32.00   39.00   40.62   48.00  129.00 \n```\n\n\n:::\n\n```{.r .cell-code}\nhist(couchto5k$age)\n```\n\n::: {.cell-output-display}\n![](11_ex_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n- `accountability` and `selfmot` are both integer variables should both be $5 \\leq x \\leq 35$ - **by definition**\n\nWe can see that `accountability` looks to be okay, but `selfmot` has a minimum value of -99, which we can't have.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncouchto5k |> \n  select(accountability, selfmot) |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n accountability     selfmot      \n Min.   : 6.00   Min.   :-99.00  \n 1st Qu.:16.00   1st Qu.: 13.00  \n Median :20.00   Median : 15.00  \n Mean   :19.92   Mean   : 12.84  \n 3rd Qu.:23.00   3rd Qu.: 17.00  \n Max.   :32.00   Max.   : 23.00  \n```\n\n\n:::\n:::\n\n\n\n\n\n- `health` and `happiness` are both integer and should be $0 \\leq x \\leq 100$ - **by definition of variable**\n\nboth `health` and `happiness` variables are within the possible ranges  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncouchto5k |> \n  select(health, happiness) |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     health        happiness     \n Min.   :35.00   Min.   :  0.00  \n 1st Qu.:50.00   1st Qu.: 17.00  \n Median :57.00   Median : 44.00  \n Mean   :56.99   Mean   : 44.69  \n 3rd Qu.:64.00   3rd Qu.: 69.00  \n Max.   :82.00   Max.   :100.00  \n```\n\n\n:::\n:::\n\n\n\n\n\n- `season` should be one of \"spring\", \"summer\", \"autumn\", \"winter\" \n\nWe have some mis-spellings of \"autumn\" as \"autunm\" which we should fix  \n(i'm adding in the `useNA=\"always\"` bit just so i can also see if there are any that are already missing)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(couchto5k$season, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nautumn autunm spring summer winter   <NA> \n     6      4     67     36      8      0 \n```\n\n\n:::\n:::\n\n\n\n\n- `city` should be one of \"Edinburgh\", \"Glasgow\"\n\nThis looks fine:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(couchto5k$city, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEdinburgh   Glasgow      <NA> \n       87        34         0 \n```\n\n\n:::\n:::\n\n\n\n\n- `week_stopped` is an integer variable and should be $1 \\leq x \\leq 9$ - **by definition of variable**\n\nWe have an entry of 12, which we can't have. Could this be interpreted as someone doing the programme for an extra 5 weeks beyond the 9? In which case could we turn that 12 into a 9? It's just a possible that it's a typo, and it's supposed to be a 1. This ambiguity is probably going to be best dealt with by considering that datapoint to be missing.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(couchto5k$week_stopped, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   1    2    3    4    5    7    8    9   12 <NA> \n  12   11   10   15    3    5    4   60    1    0 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nWe'll do all of our cleaning inside one `mutate()`. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncouchto5k <- \n  couchto5k |> \n  mutate(\n    # ages >100, make NA\n    age = ifelse(age>100, NA, age),\n    # selfmot scores <5, make NA\n    selfmot = ifelse(selfmot < 5, NA, selfmot),\n    # change autunm to autumn\n    season = ifelse(season == \"autunm\",\"autumn\",season),\n    # and then make it a factor (lets set the levels too)\n    season = factor(season, levels = c(\"spring\",\"summer\",\"autumn\",\"winter\")),\n    # make city a factor\n    city = factor(city),\n    # weekstopped if >9, then NA\n    week_stopped = ifelse(week_stopped > 9, NA, week_stopped)\n  )\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(couchto5k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    pptID                age        accountability     selfmot     \n Length:121         Min.   :18.00   Min.   : 6.00   Min.   : 7.00  \n Class :character   1st Qu.:32.00   1st Qu.:16.00   1st Qu.:13.00  \n Mode  :character   Median :39.00   Median :20.00   Median :15.00  \n                    Mean   :39.35   Mean   :19.92   Mean   :14.72  \n                    3rd Qu.:47.50   3rd Qu.:23.00   3rd Qu.:17.00  \n                    Max.   :60.00   Max.   :32.00   Max.   :23.00  \n                    NA's   :2                       NA's   :2      \n     health        happiness         season          city     week_stopped  \n Min.   :35.00   Min.   :  0.00   spring:67   Edinburgh:87   Min.   :1.000  \n 1st Qu.:50.00   1st Qu.: 17.00   summer:36   Glasgow  :34   1st Qu.:3.000  \n Median :57.00   Median : 44.00   autumn:10                  Median :8.500  \n Mean   :56.99   Mean   : 44.69   winter: 8                  Mean   :6.217  \n 3rd Qu.:64.00   3rd Qu.: 69.00                              3rd Qu.:9.000  \n Max.   :82.00   Max.   :100.00                              Max.   :9.000  \n                                                             NA's   :1      \n```\n\n\n:::\n:::\n\n\n\n\nBecause we know that the resulting missingness is restricted to a relatively small proportion of the dataset, we'll just stick with the complete cases. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncouchto5k <- na.omit(couchto5k)\n```\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n121 participants were recruited to take part in the study. \n2 participants recorded ages exceeding 100, 2 participants recorded an impossible score on the self-motivation scale, and a further one participant recorded having stopped the programme 3 weeks after the defined maximum. These 5 participants were excluded from all analyses.  \n\nThe remaining 116 participants were all over 18 (Mean age 40, SD 11.3) and were recruited from Edinburgh (73%) and Glasgow (27%). \nThe median number of weeks spent in the 'couch-to-5k' programme was 8.5, with 50% successfully completing the 9 weeks. Spring and summer were the most common seasons for attempting the programme (56% and 30% of participants respectively), with 8% undertaking it in autumn and only 6% in winter. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>  \n\n## City differences\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\n\nThe researchers conducting the study want to first find out a little more about differences between the Edinburgh and Glasgow study sites. Specifically, they would like to investigate whether dropping out of the programme early (prior to week 5), late (week 5 onwards) or not at all (completed all 9 weeks), is different between Edinburgh and Glasgow participants. They would also like to know if the average age of participants is different between the cities.  \n\nPerform any appropriate analyses and write up your methods and results, providing plots and tables where useful.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- There are two questions here: city differences in dropout, and city differences in age. These are nice and simple questions about the relationships between only two variables.  \n- You might need to make a new variable for \"early/late/no dropout\".  \n- The first 5 weeks of the course focused on some of the more fundamental tests of relationships between two variables. Some of these might be useful here!  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\nThe `dropout ~ city` question is asking us to categorise when participants stop the programme into \"early\", \"late\", or \"not at all\". So the question is `categorical ~ categorical`. Sounds like a $\\chi^2$ test to me!  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncouchto5k <- \n  couchto5k |>\n    mutate(\n      dropout = ifelse(week_stopped < 5, \"early\",\n                      ifelse(week_stopped <9, \"late\", \"not at all\"))\n    )\n```\n:::\n\n\n\n\nlet's check that the above `ifelse` statement worked as we wanted:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(couchto5k$dropout, couchto5k$week_stopped)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            \n              1  2  3  4  5  7  8  9\n  early      12 10 10 14  0  0  0  0\n  late        0  0  0  0  3  5  4  0\n  not at all  0  0  0  0  0  0  0 58\n```\n\n\n:::\n:::\n\n\n\n\nand let's look at the differences between the cities, and also perform a $\\chi^2$ test. \nWe're going to simulate the p-value here, because some of our expected cell counts are going to be $<5$ (see e.g. [Week 4 Exercises #favourite-colours](04_ex.html#childrens-favourite-colours){target=\"_blank\"})  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(couchto5k$dropout, couchto5k$city)\nchisq.test(table(couchto5k$dropout, couchto5k$city), simulate.p.value = TRUE)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n            \n             Edinburgh Glasgow\n  early             34      12\n  late               8       4\n  not at all        43      15\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with simulated p-value (based on 2000\n\treplicates)\n\ndata:  table(couchto5k$dropout, couchto5k$city)\nX-squared = 0.29923, df = NA, p-value = 0.9055\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nThe `age ~ city` question, on the other hand, is asking whether a continuous variable is different between two groups (Edinburgh and Glasgow). We can do this with a $t$-test!   \n\nLet's first assess the extent to which the ages of two groups of participants (Edinburgh folk and Glasgow folk) have similar variances (an assumption of the standard t-test), as well as the extent to which they are normally distributed: \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(couchto5k$age[couchto5k$city==\"Edinburgh\"], \n     main = \"Edinburgh\", xlab = \"Age\")\nhist(couchto5k$age[couchto5k$city==\"Glasgow\"], \n     main = \"Glasgow\", xlab = \"Age\")\n\nqqnorm(couchto5k$age[couchto5k$city==\"Edinburgh\"], main = \"Edinburgh\")\nqqline(couchto5k$age[couchto5k$city==\"Edinburgh\"])\n\nqqnorm(couchto5k$age[couchto5k$city==\"Glasgow\"], main = \"Glasgow\")\nqqline(couchto5k$age[couchto5k$city==\"Glasgow\"])\n```\n\n::: {.cell-output-display}\n![](11_ex_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=80%}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\nThese look almost okay to me. Not great, but not completely awful. We should bear in mind that we have >30 participants in each group, which means we can be a little more relaxed about requiring very close to normal data.  \n\nThe test of equal variances suggests we have no reason to reject the hypothesis that the two groups have equal variances: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvar.test(age ~ city, data = couchto5k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  age by city\nF = 1.2079, num df = 84, denom df = 30, p-value = 0.5703\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.6361894 2.1058008\nsample estimates:\nratio of variances \n          1.207877 \n```\n\n\n:::\n:::\n\n\n\n\nSo we can carry on with our t-test of the difference in means^[If we had reason to believe the variances are not equal, we can look at doing Welch's t-test]:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(age ~ city, data = couchto5k, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  age by city\nt = 1.2222, df = 114, p-value = 0.2242\nalternative hypothesis: true difference in means between group Edinburgh and group Glasgow is not equal to 0\n95 percent confidence interval:\n -1.790235  7.557218\nsample estimates:\nmean in group Edinburgh   mean in group Glasgow \n               40.27059                37.38710 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n\n\n\n\n\n\nA $\\chi^2$ test of independence indicated that rate of attrition (early-/late-/no- dropout) did not significantly differ between Edinburgh and Glasgow ($\\chi^2$(n=116) = 0.299, Monte Carlo simulated (B=2000) p = 0.906). From both cities, approximately half of participants did not drop out of the programme, late drop-outs made up 13% of Glasgow participants and 9% of those from Edinburgh, with the remainder dropping out early (39% of Glasgow, 40% of Edinburgh).  \n\nThe mean age of participants was not significantly different between the two cities ($t( 114 )=1.22$, $p=0.22$), with a mean age in Edinburgh of 40.3 and in Glasgow of 37.4.\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>  \n\n## Happiness, Health, and a 5k Run  \n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nResearchers would like you to examine whether, beyond seasonal and age-related variation, happiness ratings are influenced by how far participants get through the couchto5k programme. Note that they are interested specifically in whether - and how - the effects of couchto5k progression are amplified by feeling healthy, such that getting further along in the programme might lead to greater increases in happiness when people are healthier.    \n\nPerform an appropriate analysis and write up your methods and results, providing plots and tables where useful.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- The use of the word \"beyond\" here should cue us to be thinking in terms of multiple regression. The question is asking about the relationship between happiness and couchto5k progression _after_ we account for participants' ages and the season in which they took the programme.  \n- We also have a clear suggestion of an interaction here, because it asks about an effect of one predictor on the outcome (programme progression on happiness) being \"amplified\" (i.e. _different_) by another predictor (health)\n- This feels a bit like two questions, but the latter really supersedes the first - if we have an interaction, then the question of \"what is the effect of progression on happiness?\" can only really be answered with \"it depends..\".      \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nlet's standardise the health measure, because we probably don't want to look at things where people have health of 0, and i'm not sure that an increase of 1 is that meaningful..    \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncouchto5k <- couchto5k |>\n  mutate(\n    healthZ = (health-mean(health))/sd(health),\n  )\n```\n:::\n\n\n\nHere's our model:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhhmod <- lm(happiness ~ age + season + week_stopped * healthZ, couchto5k)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\nlet's take a look at assumptions\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(hhmod)\n```\n\n::: {.cell-output-display}\n![](11_ex_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nso this looks a little weird - we've got some sharp 'edges' to our cloud of data in the residual vs fitted plot.  \nWhat I think this is reflecting is that we are being limited by the bounds of the happiness measure (i.e. people are using the full scale of 0 up to 100). Consider how this might influence the residuals. As predicted values get closer to the edges of the scale, the residuals will get smaller. This might not be too much of a problem, but may well be worth discussing. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nLet's conduct an F-test of the interaction:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(hhmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: happiness\n                      Df Sum Sq Mean Sq F value    Pr(>F)    \nage                    1   1074  1073.6  1.2983   0.25704    \nseason                 3   6422  2140.7  2.5888   0.05669 .  \nweek_stopped           1   3264  3263.8  3.9470   0.04949 *  \nhealthZ                1    110   109.5  0.1325   0.71661    \nweek_stopped:healthZ   1  25379 25378.5 30.6910 2.153e-07 ***\nResiduals            108  89306   826.9                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n- the final row tells us that the interaction weekstopped*health explains significantly more variance than we would expect by chance\n\n\n- the coefficients can tell us effect sizes, directions etc.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(hhmod)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           23.7368    13.0236   1.823   0.0711 .  \nage                    0.3638     0.3130   1.162   0.2477    \nseasonsummer           1.4023     8.4395   0.166   0.8683    \nseasonautumn         -14.4972    12.0201  -1.206   0.2304    \nseasonwinter         -22.7635    13.0608  -1.743   0.0842 .  \nweek_stopped           1.6887     1.2824   1.317   0.1907    \nhealthZ              -31.0210     6.8032  -4.560 1.36e-05 ***\nweek_stopped:healthZ   5.0320     0.9083   5.540 2.15e-07 ***\n```\n\n\n:::\n:::\n\n\n\n\ngetting further along the couchto5k programme is associated with being more happy, the more healthy you feel. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n- and plots are going to be a *very* useful way to understand and to present.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nplotdat <- expand_grid(\n  age = mean(couchto5k$age),\n  season = \"spring\",\n  week_stopped=1:9,\n  healthZ = c(-1, 0, 1)\n)\n\nbroom::augment(hhmod, newdata = plotdat, interval=\"confidence\") |>\n  mutate(\n    health = factor(healthZ, levels=c(\"-1\",\"0\",\"1\"),\n                    labels=c(\"Poor health (-1 SD)\", \n                             \"Average health\",\n                             \"Good health (+1 SD)\")\n                    )\n  ) |> ggplot(aes(x=week_stopped,y=.fitted, col=health,fill=health))+\n  geom_line(aes(lty=health)) +\n  geom_ribbon(aes(ymin=.lower,ymax=.upper), alpha=.2) +\n  scale_color_viridis_d(option=\"C\")+\n  scale_fill_viridis_d(option=\"C\")+\n  scale_x_continuous(breaks=1:9)+\n  labs(y=\"Happiness (0-100)\",x=\"- Week Stopped -\") +\n  guides(col=\"none\",fill=\"none\")\n```\n\n::: {.cell-output-display}\n![](11_ex_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n- we can also, if we want, get out some standardised coefficients - i.e. some coefficients in terms of standard deviations (for those predictors where SD is applicable). Note that healthZ is _already_ standardised.   \n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhhmod2 <- lm(scale(happiness) ~ scale(age) + season + scale(week_stopped) * healthZ, data = couchto5k)\nsummary(hhmod2)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nCoefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  0.098261   0.134015   0.733   0.4650    \nscale(age)                   0.124067   0.106738   1.162   0.2477    \nseasonsummer                 0.042441   0.255419   0.166   0.8683    \nseasonautumn                -0.438752   0.363783  -1.206   0.2304    \nseasonwinter                -0.688930   0.395280  -1.743   0.0842 .  \nscale(week_stopped)          0.161352   0.122529   1.317   0.1907    \nhealthZ                      0.009042   0.106258   0.085   0.9323    \nscale(week_stopped):healthZ  0.480784   0.086785   5.540 2.15e-07 ***\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\nTo investigate the extent to which, over and above seasonal and age related differences, happiness ratings are associated with getting further through (and feeling healthier following) the couch-to-5k programme, happiness ratings on a scale of 0 to 100 were modelled using multiple regression. \n\nThe number of weeks at which participants stopped (1-9), a multi-test measure of health (Z-scored) and their interaction were included as predictors, along with the covariates of age (years) and season (treatment coded with spring as the reference level). The regression model appeared to meet all assumptions, with residuals displaying a constant mean at approximately zero, although the boundaries of the happiness scale induced a smaller residual variance at the tail ends of the fitted values (see Appendix X). This is corroborated by 30% of participants reporting happiness in either the bottom or top 10th of the scale. \n\nAnalysis of variance indicated that after accounting for season and age, there was a significant interaction between participants' self-reported health at the end of the programme and the week at which they stopped ($F(1,108)=30.69$,  $p <0.001$). The full model explained approximately 24% (adjusted $R^2$) of the variance in happiness scores.\n\n\n\n\n::: {#tbl-couchanova .cell layout-align=\"center\" tbl-cap='Analysis of variance in happiness scores'}\n::: {.cell-output-display}\n\n-------------------------------------------------------------------------\n          &nbsp;             df    Sum Sq   Mean Sq     F         p      \n--------------------------- ----- -------- --------- ------- ------------\n          **Age**             1     1074     1074      1.3      0.257    \n\n        **Season**            3     6422     2141     2.59      0.057    \n\n     **Week Stopped**         1     3264     3264     3.95    **0.049**  \n\n        **Health**            1     110       110     0.13      0.717    \n\n **Week Stopped : Health**    1    25379     25379    30.69   **<0.001** \n\n       **Residual**          108   89306      827                        \n-------------------------------------------------------------------------\n\n\n:::\n:::\n\n\n\n\nFor those of average health, there was no statistically reliable change in happiness associated with additional weeks of the couch-to-5k programme ($b = 1.69$, $\\beta = 0.16$, $t(108) = \\, 1.32$, $p = 0.191$).\n\nHowever this effect was moderated by health such that the weekly change in happiness was more positive for healthier, and more negative for less healthy, people. For each 1SD (10 raw points) change in health from the average, happiness ratings changed by an additional 5.03 points every week ($b = 5.03$, $\\beta = 0.48$, $t(108) = \\, 5.54$, $p <0.001$). \n@fig-couchint shows the shape of this interaction, and a full regression table can be found in @tbl-couchinttab.  \n\nHappiness following the couch-to-5k programme was found to be related to how far through the programme participants got, and this relationship depended on participant health, with the happiness of healthier participants increasing more for every week longer through the programme they lasted than it did for participants of average health. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Interaction between health and duration completed of couch-to-5k on happiness, estimated for the average age and commencing the programme in Spring](11_ex_files/figure-html/fig-couchint-1.png){#fig-couchint fig-align='center' width=100%}\n:::\n:::\n\n::: {#tbl-couchinttab .cell layout-align=\"center\" tbl-cap='Happiness ratings (0-100). Table of regression coefficients'}\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Happiness (0-100)</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">23.74</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;2.08&nbsp;&ndash;&nbsp;49.55</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.071</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Age (years)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.36</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.26&nbsp;&ndash;&nbsp;0.98</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.248</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Season [Summer]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.40</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;15.33&nbsp;&ndash;&nbsp;18.13</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.868</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Season [Autumn]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;14.50</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;38.32&nbsp;&ndash;&nbsp;9.33</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.230</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Season [Winter]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;22.76</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;48.65&nbsp;&ndash;&nbsp;3.13</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.084</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Week Stopped (1-9)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.69</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.85&nbsp;&ndash;&nbsp;4.23</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.191</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Health Metric (Z-scored)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;31.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;44.51&nbsp;&ndash;&nbsp;-17.54</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Week Stopped * Health Metric</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">5.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">3.23&nbsp;&ndash;&nbsp;6.83</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">116</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.289 / 0.243</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>  \n\n## Predictors of Drop-out\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\nThe second aim of the research is to examine the psychological factors that are associated with people completing the programme. \n\nPerform an appropriate analysis and write up your methods and results, providing plots and tables where useful.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- Completing vs Dropping-out? Sounds like a binary outcome!  \n- Recall (from study description above) that completing the programme has previously been found to vary substantially across the year. _We may well therefore want to account for this in our model!_  \n- What variables do we have that measure \"psychological factors\" that might influence dropping out? (pay attention to _when_ each variable is measured!)  \n- How might we visualise the results?   \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nWe need to make a binary outcome out of the `week_stopped` variable. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncouchto5k <- couchto5k |>\n  mutate(\n    completed = ifelse(week_stopped == 9, 1, 0)\n  )\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nSo what is going into our model? We know that we're interested in the 'psychological factors' (i.e. the variables `accountability` and `selfmot`), so at the very least we will have `dropout ~ ?? + accountability + selfmot`.  \n\nBut what about controlling for other variables?  \nPer the study description, many of these were measured after participants stopped programme.  \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n---------------------------------------------\n    variable                 when            \n---------------- ----------------------------\n     pptID                    NA             \n\n      age         unclear when measured, but \n                  assume it is consistent at \n                         both points         \n\n accountability       measured at start      \n\n    selfmot           measured at start      \n\n     health            measured at end       \n\n   happiness           measured at end       \n\n     season           measured at start      \n\n      city        unclear when measured, but \n                  assume it is consistent at \n                         both points         \n\n  week_stopped         measured at end       \n\n    dropout            measured at end       \n\n   completed           measured at end       \n---------------------------------------------\n\n\n:::\n:::\n\n\n\n\nIt doesn't really make sense for us to think about your happiness _after_ the programme influencing whether or not you complete it (this is not to say that it will not be associated).  \n\nage, season and city are all things that *might* influence completion, or might influence predictors of interest like accountability or self-motivation. We know specifically that season has previously been found to influence completion, so it would be good to at least include that. I can think up some argument that older people are more motivated/hold themselves more accountable, and so I might want to control for age to ensure I am looking at the independent effects of these psychological features separate from any age effects.  \n\nIt's probably worth scaling the `accountability` and `selfmot` variables. They are both the sum of 7 questions, each scored 1-5, so it's slightly unclear what a \"1 unit increase\" really means. It's answering.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncouchto5k <-\n  couchto5k |> \n  mutate(\n    accountabilityZ = scale(accountability)[,1],\n    selfmotZ = scale(selfmot)[,1]\n  )\n```\n:::\n\n\n\n\nAnd here's a model!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncompmod <- glm(completed ~ season + age + city + accountabilityZ + selfmotZ, \n               data = couchto5k, family=binomial)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nTo examine whether psychological factors (collectively) are associated with more/less probability of completing the couchto5k programme, we can compare our model:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncompmod <- glm(completed ~ season + age + city + accountabilityZ + selfmotZ, \n               data = couchto5k, family=binomial)\n```\n:::\n\n\n\n\nWith a restricted model that doesn't include them:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncompmod0 <- glm(completed ~ season + age + city, data = couchto5k, family=binomial)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(compmod0, compmod, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: completed ~ season + age + city\nModel 2: completed ~ season + age + city + accountabilityZ + selfmotZ\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)  \n1       110     98.794                       \n2       108     91.010  2   7.7836  0.02041 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nbeyond participants' age, location and which season programme is undertaken in, psychological factors of accountability and self motivation _do_ appear to improve model fit  \n\nFrom our coefficients, we can see that this is likely being driven by an association between self-motivation and the probability of completing the couchto5k programme:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(compmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = completed ~ season + age + city + accountabilityZ + \n    selfmotZ, family = binomial, data = couchto5k)\n\nCoefficients:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -1.426e+00  9.878e-01  -1.444  0.14878    \nseasonsummer     3.576e+00  6.591e-01   5.426 5.77e-08 ***\nseasonautumn     3.617e+00  1.180e+00   3.066  0.00217 ** \nseasonwinter     1.931e+01  1.420e+03   0.014  0.98915    \nage              9.931e-04  2.357e-02   0.042  0.96640    \ncityGlasgow     -7.770e-01  6.537e-01  -1.189  0.23459    \naccountabilityZ -1.066e-01  2.788e-01  -0.383  0.70206    \nselfmotZ         7.328e-01  2.771e-01   2.644  0.00818 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 160.81  on 115  degrees of freedom\nResidual deviance:  91.01  on 108  degrees of freedom\nAIC: 107.01\n\nNumber of Fisher Scoring iterations: 16\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nIt's always worth visualising the two focal predictors in terms of predicted probability of completion.  \n\nNote that because so few people took part in autumn and winter, this introduces a lot of uncertainty if we try and get at the effect holding `season` at its proportion, so we might be better off just providing the plot for Spring, as that is the most frequent season that people start the programme.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effects)\np1 <- effect(c(\"selfmotZ\",\"season\"), compmod, xlevels=20) |>\n  as.data.frame() |>\n  filter(season==\"spring\") |>\n  ggplot(aes(x=selfmotZ,y=fit))+\n  geom_line()+\n  geom_ribbon(aes(ymin=lower,ymax=upper),alpha=.2) +\n  labs(title=\"Predicted probability of\\ncouch-to-5k completion\",x=\"Self Motivation (Z-scored)\",y=\"P(Completed)\")\n\np2 <- effect(c(\"accountabilityZ\",\"season\"), compmod, xlevels=20) |>\n  as.data.frame() |>\n  filter(season==\"spring\") |>\n  ggplot(aes(x=accountabilityZ,y=fit))+\n  geom_line()+\n  geom_ribbon(aes(ymin=lower,ymax=upper),alpha=.2) +\n  labs(title=\"Predicted probability of\\ncouch-to-5k completion\",x=\"Accountability (Z-scored)\",y=\"P(Completed)\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](11_ex_files/figure-html/unnamed-chunk-42-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\nCouch-to-5k completion (completed vs dropped out) was modelled using logistic regression, with the location (Glasgow, Edinburgh) and season in which participants undertake the programme as predictors, along with participants age, and their scores on two psychometric measures of accountability and self-motivation that were administered prior to participants starting the programme. A likelihood ratio test indicated that the inclusion of these two measures (accountability and self-motivation) collectively improves model fit over and above age, location and season ($\\chi^2(2) = 7.78, \\, p = 0.02$). All deviance residuals for the full model were less than 3 in magnitude. \n\nIn keeping with previous research, completion of the programme was found to differ between seasons, with participants undertaking the programme in both summer and autumn being associated with increased odds of programme completion ($OR: 35.73$, $95\\% CI [10.89, 149.2]$ and $37.23$ $[5.2, 792.8]$ respectively). Age and city were not found to significantly predict completion.  \n\nWhile completing the programme was not significantly associated with scores on the accountability measure, a relationship was found between self motivation and programme completion; a 1 standard deviation increase in self-motivation was associated with doubling the odds of finishing the entire 9-weeks ($OR: 2.08\\, [1.23, 3.7]$). The model-predicted probabilities of programme completion across values of the two psychometric measures are visualised in @fig-couchglm. Full table of results can be found in @tbl-couchglmcoef  \n\nThe present study indicated that the psychometric factors of accountability and self motivation, taken together, were useful in predicting the completion (vs drop out) of the couch-to-5k programme. Specifically, a strong association was found between self-motivation and programme completion, with more motivated participants have a higher probability of finishing the full 9 weeks.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Model estimated probability of completing the couch-to-5k programme across measures of accountability and self-motivation (both Z-scored), estimated for starting the programme in spring, and holding other predictors at their average/proportions](11_ex_files/figure-html/fig-couchglm-1.png){#fig-couchglm fig-align='center' width=80%}\n:::\n:::\n\n::: {#tbl-couchglmcoef .cell layout-align=\"center\" tbl-cap='Couch-to-5k completion modeled using logistic regression. Table of coefficients.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rhtvvkqulk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rhtvvkqulk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rhtvvkqulk thead, #rhtvvkqulk tbody, #rhtvvkqulk tfoot, #rhtvvkqulk tr, #rhtvvkqulk td, #rhtvvkqulk th {\n  border-style: none;\n}\n\n#rhtvvkqulk p {\n  margin: 0;\n  padding: 0;\n}\n\n#rhtvvkqulk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rhtvvkqulk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rhtvvkqulk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rhtvvkqulk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rhtvvkqulk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rhtvvkqulk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rhtvvkqulk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rhtvvkqulk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rhtvvkqulk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rhtvvkqulk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rhtvvkqulk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rhtvvkqulk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rhtvvkqulk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rhtvvkqulk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rhtvvkqulk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhtvvkqulk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rhtvvkqulk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rhtvvkqulk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rhtvvkqulk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhtvvkqulk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rhtvvkqulk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhtvvkqulk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rhtvvkqulk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhtvvkqulk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rhtvvkqulk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rhtvvkqulk .gt_left {\n  text-align: left;\n}\n\n#rhtvvkqulk .gt_center {\n  text-align: center;\n}\n\n#rhtvvkqulk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rhtvvkqulk .gt_font_normal {\n  font-weight: normal;\n}\n\n#rhtvvkqulk .gt_font_bold {\n  font-weight: bold;\n}\n\n#rhtvvkqulk .gt_font_italic {\n  font-style: italic;\n}\n\n#rhtvvkqulk .gt_super {\n  font-size: 65%;\n}\n\n#rhtvvkqulk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rhtvvkqulk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rhtvvkqulk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rhtvvkqulk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rhtvvkqulk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rhtvvkqulk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rhtvvkqulk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rhtvvkqulk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rhtvvkqulk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Predictors\">Predictors</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Odds-Ratios\">Odds Ratios</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Predictors\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"Odds Ratios\" class=\"gt_row gt_left\">0.2 [0.03, 1.61]</td></tr>\n    <tr><td headers=\"Predictors\" class=\"gt_row gt_left\">Season [Summer]</td>\n<td headers=\"Odds Ratios\" class=\"gt_row gt_left\">35.7 [10.89, 149.2]</td></tr>\n    <tr><td headers=\"Predictors\" class=\"gt_row gt_left\">Season [Autumn]</td>\n<td headers=\"Odds Ratios\" class=\"gt_row gt_left\">37.2 [5.2, 792.8]</td></tr>\n    <tr><td headers=\"Predictors\" class=\"gt_row gt_left\">Season [Winter]</td>\n<td headers=\"Odds Ratios\" class=\"gt_row gt_left\">2.4x10^8 [0, Inf]</td></tr>\n    <tr><td headers=\"Predictors\" class=\"gt_row gt_left\">Age (years)</td>\n<td headers=\"Odds Ratios\" class=\"gt_row gt_left\">1 [0.96, 1.05]</td></tr>\n    <tr><td headers=\"Predictors\" class=\"gt_row gt_left\">City [Glasgow]</td>\n<td headers=\"Odds Ratios\" class=\"gt_row gt_left\">0.5 [0.12, 1.6]</td></tr>\n    <tr><td headers=\"Predictors\" class=\"gt_row gt_left\">Accountability (Z-scored)</td>\n<td headers=\"Odds Ratios\" class=\"gt_row gt_left\">0.9 [0.52, 1.56]</td></tr>\n    <tr><td headers=\"Predictors\" class=\"gt_row gt_left\">Self-Motivation (Z-scored)</td>\n<td headers=\"Odds Ratios\" class=\"gt_row gt_left\">2.1 [1.23, 3.7]</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<!-- # Development of Counterfactual Thinking -->\n\n<!-- :::frame -->\n<!-- __Kominsky.csv__   -->\n\n<!-- Do young children struggle to answer the question \"what would have happened?\" Developmental researchers [Kominsky et al. (2021)](https://cicl.stanford.edu/papers/kominsky2021trajectory.pdf){target=\"_blank\"} asked children between the ages of 5 and 10 to imagine counterfactual situations. Children were randomly assigned to one of the two conditions. They observed a video where Ball A hit Ball E and Ball E started to move. -->\n\n<!-- :::: {.columns} -->\n<!-- ::: {.column width=\"40%\"} -->\n<!-- __Singly-Determined__   -->\n\n<!-- In the singly-determined condition, the brick wall altered Ball E’s trajectory such that it went into the goal. -->\n\n<!-- ![](images/Brickcon2v2.gif) -->\n\n<!-- ::: -->\n<!-- ::: {.column width=\"10%\"} -->\n<!-- ::: -->\n<!-- ::: {.column width=\"40%\"} -->\n<!-- __Over-Determined__   -->\n\n<!-- In the over-determined condition, Ball E also deflects off the wall but would have gone into the goal regardless.  -->\n\n<!-- ![](images/Brickdis2v2.gif) -->\n\n<!-- ::: -->\n<!-- :::: -->\n\n<!-- The children were then asked: “What if the brick wall had not been there? Would Ball E have gone into the goal?” (“Yes” or “No”). -->\n\n<!-- You can download a dataset of 120 children from [https://uoepsy.github.io/data/Kominsky.csv](https://uoepsy.github.io/data/Kominsky.csv){target=\"_blank\"}.^[Note, data used here was modified, so it is different from the original dataset.]   -->\n\n<!-- ```{r} -->\n<!-- tibble( -->\n<!--   variable = c(\"ID\",\"Sex\",\"Age\",\"Condition\",\"Accuracy\"), -->\n<!--   description = c(\"Unique ID number\",\"Children's gender\",\"Children's age\",\"The video children watched: singly-determined vs. over-determined. In the singly-determined condition, the brick was the single cause that caused Ball E to go into the goal. In the over-determined condition, the brick was not the single cause because Ball E would have gone into the goal without it.\",\"Whether children answered the question correctly (1) or no (0). The correct answer should be “no” for the singly-determined condition and should be “yes” for the over-determined condition\") -->\n<!-- ) |> gt::gt() -->\n<!-- ``` -->\n\n<!-- Researchers were interested in children’s counterfactual thinking ability: How did children perform in the singly-determined vs. over-determined situations, and whether it differed between ages? -->\n\n<!-- They managed to get the same number of children for the 5-6, 7-8, and 9-10 three age groups. Since the sample size was small and the range of ages was small, instead of using age (numeric) as a predictor, they used the age group (factors) as a predictor. -->\n\n<!-- ::: -->\n\n\n\n\n\n",
    "supporting": [
      "11_ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}