<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - Week 8 Exercises: Multiple Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-down')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html" rel="" target="">
 <span class="dropdown-text">1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html" rel="" target="">
 <span class="dropdown-text">1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html" rel="" target="">
 <span class="dropdown-text">2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html" rel="" target="">
 <span class="dropdown-text">2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 3</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html" rel="" target="">
 <span class="dropdown-text">3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html" rel="" target="">
 <span class="dropdown-text">3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: T-tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 4</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04a_chisq.html" rel="" target="">
 <span class="dropdown-text">4A: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revisitnhst.html" rel="" target="">
 <span class="dropdown-text">4B: Revisiting NHST</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 5</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li>
    <a class="dropdown-item" href="./05a_covcor.html" rel="" target="">
 <span class="dropdown-text">5A: Covariance &amp; Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Cov, Cor, Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-6" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 6</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-6">    
        <li>
    <a class="dropdown-item" href="./06_wt.html" rel="" target="">
 <span class="dropdown-text">Walkthrough: Advanced Data Wrangling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 7</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li>
    <a class="dropdown-item" href="./07a_slr.html" rel="" target="">
 <span class="dropdown-text">7A: Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Simple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 8</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li>
    <a class="dropdown-item" href="./08a_mlr.html" rel="" target="">
 <span class="dropdown-text">8A: Multiple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08b_assumptdiag.html" rel="" target="">
 <span class="dropdown-text">8B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Multiple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 9</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li>
    <a class="dropdown-item" href="./09a_interactions.html" rel="" target="">
 <span class="dropdown-text">9A: Interactions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09b_contrasts.html" rel="" target="">
 <span class="dropdown-text">9B: Categorical Predictors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Interactions</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-10" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 10</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-10">    
        <li>
    <a class="dropdown-item" href="./10a_glm.html" rel="" target="">
 <span class="dropdown-text">10A: GLM!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Logistic Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-11" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 11</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-11">    
        <li>
    <a class="dropdown-item" href="./11_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Tying up Loose Ends</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#wellbeing-and-outdoor-time" id="toc-wellbeing-and-outdoor-time" class="nav-link active" data-scroll-target="#wellbeing-and-outdoor-time">Wellbeing and Outdoor Time</a></li>
  <li><a href="#student-sleep-quality" id="toc-student-sleep-quality" class="nav-link" data-scroll-target="#student-sleep-quality">Student Sleep Quality</a></li>
  <li><a href="#rmarkdown" id="toc-rmarkdown" class="nav-link" data-scroll-target="#rmarkdown">RMarkdown</a></li>
  <li><a href="#optional-extra-conscientiousness" id="toc-optional-extra-conscientiousness" class="nav-link" data-scroll-target="#optional-extra-conscientiousness">Optional Extra: Conscientiousness</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 8 Exercises: Multiple Regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="wellbeing-and-outdoor-time" class="level1">
<h1>Wellbeing and Outdoor Time</h1>
<div class="frame">
<blockquote class="blockquote">
<p><strong>Research Question:</strong> <em>after</em> taking into account differences due to people’s level of social interactions, to what extent is well-being associated with the time people spend outdoors?</p>
</blockquote>
<p><strong>Data: wellbeing.csv</strong></p>
<p>Researchers interviewed 32 participants, selected at random from the population of residents of Edinburgh &amp; Lothians. They used the Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br>
The researchers also asked participants to estimate the average number of hours they spend outdoors each week, the average number of social interactions they have each week (whether on-line or in-person), and whether they believe that they stick to a routine throughout the week (Yes/No).</p>
<p>The dataset is available at <a href="https://uoepsy.github.io/data/wellbeing.csv" target="_blank">https://uoepsy.github.io/data/wellbeing.csv</a> and contains five attributes:</p>
<ul>
<li><code>wellbeing</code>: Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br>
</li>
<li><code>outdoor_time</code>: Self report estimated number of hours per week spent outdoors<br>
</li>
<li><code>social_int</code>: Self report estimated number of social interactions per week (both online and in-person)</li>
<li><code>routine</code>: Binary Yes/No response to the question “Do you follow a daily routine throughout the week?”</li>
<li><code>location</code>: Location of primary residence (City, Suburb, Rural)</li>
</ul>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Read in the data, and explore and describe the variables and relationships that are relevant to the research question.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<p>You might want to:</p>
<ul>
<li>plot the <em>marginal distributions</em> (the distributions of each variable in the analysis without reference to the other variables)</li>
<li>plot the <em>marginal relationships</em> between the outcome variable and each of the explanatory variables.<br>
</li>
<li>make a quick correlation matrix of the variables which are to be used in the analysis, and write a short paragraph describing the relationships.
<ul>
<li>e.g.&nbsp;<code>cor(data[,c(1:4)])</code> will give us a matrix of correlations between each pair of the first 4 variables in the data</li>
</ul></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-1" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')"> Solution </span>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co">#used to arrange plots</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>mwdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/wellbeing.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>wellbeing_plot <span class="ot">&lt;-</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">250</span>) <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Score on WEMWBS (range 14-70)"</span>, <span class="at">y =</span> <span class="st">"Probability</span><span class="sc">\n</span><span class="st">density"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>outdoortime_plot <span class="ot">&lt;-</span> </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> outdoor_time)) <span class="sc">+</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">200</span>) <span class="sc">+</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time spent outdoors per week (hours)"</span>, <span class="at">y =</span> <span class="st">"Probability</span><span class="sc">\n</span><span class="st">density"</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>social_plot <span class="ot">&lt;-</span> </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> social_int)) <span class="sc">+</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">150</span>) <span class="sc">+</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of social interactions per week"</span>, <span class="at">y =</span> <span class="st">"Probability</span><span class="sc">\n</span><span class="st">density"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>wellbeing_plot <span class="sc">/</span> outdoortime_plot <span class="sc">/</span> social_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-marg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08_ex_files/figure-html/fig-marg-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Marginal distribution plots of wellbeing sores, weekly hours spent outdoors, and social interactions</figcaption>
</figure>
</div>
</div>
</div>
<div class="int">
<ul>
<li>The marginal distribution of scores on the WEMWBS is unimodal with a mean of approximately 43. There is variation in scores (SD = 11.7).<br>
</li>
<li>The marginal distribution of weekly hours spend outdoors is unimodal with a mean of approximately 14.8 hours. There is variation in outdoor time (SD = 6.9 hours).<br>
</li>
<li>The marginal distribution of numbers of social interactions per week is unimodal with a mean of approximately 16. There is variation in in numbers of social interactions per week (SD = 4.4).</li>
</ul>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>wellbeing_outdoor <span class="ot">&lt;-</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> outdoor_time, <span class="at">y =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time spent outdoors per week (hours)"</span>, <span class="at">y =</span> <span class="st">"Wellbeing score (WEMWBS)"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>wellbeing_social <span class="ot">&lt;-</span> </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> social_int, <span class="at">y =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of social interactions per week"</span>, <span class="at">y =</span> <span class="st">"Wellbeing score (WEMWBS)"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>wellbeing_outdoor <span class="sc">|</span> wellbeing_social</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mwdata-mlr-rels" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08_ex_files/figure-html/fig-mwdata-mlr-rels-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Scatterplots displaying the relationships between scores on the WEMWBS and a) weekly outdoor time (hours), and b) weekly number of social interactions</figcaption>
</figure>
</div>
</div>
</div>
<p>We can either use:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correlation matrix of the first 3 columns</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(mwdata[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>or:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select only the columns we want by name, and pass this to cor()</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>mwdata <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(wellbeing, outdoor_time, social_int) <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             wellbeing outdoor_time social_int
wellbeing    1.0000000    0.5815613  0.7939003
outdoor_time 0.5815613    1.0000000  0.3394469
social_int   0.7939003    0.3394469  1.0000000</code></pre>
</div>
</div>
<div class="int">
<p>There is a moderate, positive, linear relationship between weekly outdoor time and WEMWBS scores for the participants in the sample. Participants’ wellbeing scores tend to increase, on average, with the number of hours spent outdoors each week.<br>
There is a moderate, positive, linear relationship between the weekly number of social interactions and WEMWBS scores for the participants in the sample. Participants’ wellbeing scores tend to increase, on average, with the weekly number of social interactions. There is also a weak positive correlation between weekly outdoor time and the weekly number of social interactions.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<blockquote class="blockquote">
<p><strong>Research Question:</strong> <em>after</em> taking into account differences due to people’s level of social interactions, to what extent is well-being associated with the time people spend outdoors?</p>
</blockquote>
<p>Fit a regression model that you can use to answer the research question (make sure to give it a name to store it in your environment).</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<p><span class="math inline">\(Wellbeing = b_0 \ + \ b_1 \cdot Social Interactions \ + \ b_2 \cdot Outdoor Time \ + \ \epsilon\)</span></p>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>wbmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int <span class="sc">+</span> outdoor_time, <span class="at">data =</span> mwdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Extract <em>and interpret</em> the parameter estimates (the coefficients) from your model.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>There’s a comprehensive section on how we interpret multiple regression coefficients in <a href="08a_mlr.html#multiple-regression-coefficients" target="_blank">8A#multiple-regression-coefficients</a></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ 1 + social_int + outdoor_time, data = mwdata)

Residuals:
   Min     1Q Median     3Q    Max 
-9.742 -4.915 -1.255  5.628 10.936 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    5.3704     4.3205   1.243   0.2238    
social_int     1.8034     0.2691   6.702 2.37e-07 ***
outdoor_time   0.5924     0.1689   3.506   0.0015 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.148 on 29 degrees of freedom
Multiple R-squared:  0.7404,    Adjusted R-squared:  0.7224 
F-statistic: 41.34 on 2 and 29 DF,  p-value: 3.226e-09</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\hat \beta_0\)</span> = 5.37, the estimated average wellbeing score associated with zero hours of outdoor time and zero social interactions per week.<br>
</li>
<li><span class="math inline">\(\hat \beta_1\)</span> = 1.8, the estimated increase in average wellbeing score associated with an additional social interaction per week (an increase of one), <em>holding weekly outdoor time constant</em> (i.e., when the remaining explanatory variables are held at the same value or are fixed).</li>
<li><span class="math inline">\(\hat \beta_2\)</span> = 0.59, the estimated increase in average wellbeing score associated with one hour increase in weekly outdoor time, <em>holding the number of social interactions constant</em>.</li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Along with the p-values given by <code>summary()</code> that test the null hypothesis that each coefficient is equal to zero, we can obtain confidence intervals for our estimates to provide a range of plausible values for each coefficient. This may be useful if we want to focus more on the estimated value, rather than “is it zero or not?”.</p>
<p>Look up the function <code>confint()</code> and use it to obtain some 95% Confidence Intervals for the coefficients.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(wbmodel, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %     97.5 %
(Intercept)  -3.4660660 14.2068209
social_int    1.2530813  2.3538164
outdoor_time  0.2468371  0.9378975</code></pre>
</div>
</div>
<div class="int">
<ul>
<li>The average wellbeing score for all those with zero hours of outdoor time and zero social interactions per week is between -3.47 and 14.21.<br>
</li>
<li>When <em>holding weekly outdoor time constant</em>, each increase of one social interaction per week is associated with a difference in wellbeing scores between 1.25 and 2.35, on average.<br>
</li>
<li>When <em>holding the number of social interactions per week constant</em>, each one hour increase in weekly outdoor time is associated with a difference in wellbeing scores between 0.25 and 0.94, on average.</li>
</ul>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Does your model provide a better fit to the data than a model with no explanatory variables? (i.e., test against the alternative hypothesis that <em>at least one</em> of the explanatory variables significantly predicts wellbeing scores).</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>it’s all in the <code>summary()</code>!!</li>
<li>this might not be a useful question to ask, but we’re just trying to go through what each bit of the model output shows.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ 1 + social_int + outdoor_time, data = mwdata)

Residuals:
   Min     1Q Median     3Q    Max 
-9.742 -4.915 -1.255  5.628 10.936 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    5.3704     4.3205   1.243   0.2238    
social_int     1.8034     0.2691   6.702 2.37e-07 ***
outdoor_time   0.5924     0.1689   3.506   0.0015 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.148 on 29 degrees of freedom
Multiple R-squared:  0.7404,    Adjusted R-squared:  0.7224 
F-statistic: 41.34 on 2 and 29 DF,  p-value: 3.226e-09</code></pre>
</div>
</div>
<div class="int">
<p>Weekly social interactions and outdoor time explained 72.2% of the variance (adjusted <span class="math inline">\(R^2\)</span> =0.722, <span class="math inline">\(F\)</span>(2,29)=41.3, p&lt;.001)</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Optional Question 6
</div>
<div class="question-body">
<p>Just to prove it to ourselves, conduct a model comparison between your model and the “null model”, and check that the <span class="math inline">\(F\)</span>-statistic from the <code>summary()</code> of your model matches that from the comparison.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>we talked about the ‘null model’, and conducting model comparison in <a href="08a_mlr.html#model-comparisons" target="_blank">8A#model-comparisons</a>.<br>
</li>
<li>we can fit a model with no predictors such as <code>lm(wellbeing ~ 1, data = mwdata)</code>.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>nullmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mwdata)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(nullmodel, wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: wellbeing ~ 1
Model 2: wellbeing ~ 1 + social_int + outdoor_time
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     31 4222.0                                  
2     29 1096.2  2    3125.8 41.345 3.226e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Matches that seen in the bottom of <code>summary(wbmodel)</code>:</p>
<pre><code>F-statistic: 41.34 on 2 and 29 DF,  p-value: 3.226e-09</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Check the assumptions of your model.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>See <a href="08b_assumptdiag.html" target="_blank">8B#assumptions</a><br>
</li>
<li>You don’t necessarily have to perform statistical tests of assumptions, but check the plots at the very least!<br>
</li>
<li>Interpreting these plots is ultimately a judgement call, and comes with experience.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>We only have <span class="math inline">\(n=32\)</span> observations here, so our plots might look a bit wobbly. I might perform some quick tests to reassure myself we’re okay.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_ex_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(wbmodel))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(wbmodel)
W = 0.94831, p-value = 0.129</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ncvTest</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.001925809, Df = 1, p = 0.965</code></pre>
</div>
</div>
<p>We seem to be okay!</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Check for influential observations.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li><a href="08b_assumptdiag.html#individual-case-diagnostics" target="_blank">8B#individual-case-diagnostics</a> covers a whole load of different metrics you might use. As a starting point, perhaps consider Cook’s Distances plots, or use <code>influence.measures()</code> to get lots of info.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>Here are the Cook’s Distance values:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wbmodel, <span class="at">which =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_ex_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>We can see that one observation (labelled 27) is a little bit higher than the rest. It’s not hugely out of keeping with the others, so I might not be too worried.</p>
<p>It’s not flagged by <code>influence.measures()</code>, but another observation is flagged, this time on the covratio metric (influence on the standard errors).<br>
With only <span class="math inline">\(32\)</span> observations, excluding datapoints comes with a big reduction in statistical power. On balance I might report this influential point in the write up, but keep it in the analysis. This decision is also based on the distribution of covratio values - it doesn’t look like one value is really that much higher than the others (it is simply above the internal cutoff that <code>influence.measures()</code> uses).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">influence.measures</span>(wbmodel))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Potentially influential observations of
     lm(formula = wellbeing ~ 1 + social_int + outdoor_time, data = mwdata) :

   dfb.1_ dfb.scl_ dfb.otd_ dffit cov.r   cook.d hat  
32  0.10  -0.08    -0.07    -0.14  1.35_*  0.01   0.19</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">covratio</span>(wbmodel), <span class="at">breaks=</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_ex_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Create a visualisation of the relationship between wellbeing and outdoor time, after accounting for social interactions.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>There’s an example of visualising multiple regression coefficients in <a href="08a_mlr.html#multiple-regression-coefficients" target="_blank">8A#multiple-regression-coefficients</a>.<br>
</li>
<li>to visualise just one association, you might need the <code>terms</code> argument in <code>plot_model()</code>. Don’t forget you can look up the documentation by typing <code>?plot_model</code> in the console.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(wbmodel, <span class="at">type =</span> <span class="st">"eff"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"outdoor_time"</span>), </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">show.data =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_ex_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Create a regression table to present your results</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>There is a useful function called <code>tab_model()</code>, also from the <strong>sjPlot</strong> package. You can see it used in <a href="07a_slr.html#example" target="_blank">7A#example</a>.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">wellbeing</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.37</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-3.47&nbsp;–&nbsp;14.21</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.224</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">social int</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.80</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.25&nbsp;–&nbsp;2.35</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">outdoor time</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.59</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.25&nbsp;–&nbsp;0.94</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">32</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.740 / 0.722</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="student-sleep-quality" class="level1">
<h1>Student Sleep Quality</h1>
<div class="frame">
<p><strong>USMR 2022 Data</strong></p>
<p>The data from the USMR 2022 survey (now closed) can be found at <a href="https://uoepsy.github.io/data/usmr2022.csv">https://uoepsy.github.io/data/usmr2022.csv</a>.</p>
<p><em>note, this is the survey data just from USMR <strong>this</strong> year, not other students on other courses or in previous years</em></p>
</div>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Recall that last week we discussed my little theory that people who believe they have more control over life will rate their sleep quality as being better.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-locsleep" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08_ex_files/figure-html/fig-locsleep-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3: linear model predicting sleep quality ratings by perceived locus of control</figcaption>
</figure>
</div>
</div>
</div>
<p>Monica has pointed out that it’s likely that the association we have found (<a href="#fig-locsleep">Figure&nbsp;3</a>) might be due to other things. There are lots of explanations we could come up with. Some of these might involve variables we have measured.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> What if the relationship we see between peoples’ <code>loc</code> and <code>sleeprating</code> is better explained by their emotional stability? Monica makes a convincing argument that having higher emotional stability may be correlated with feeling more in control of one’s life, and may also influence sleep quality.<br>
Sometimes it can help to think of models in the form of diagrams:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-surveydag" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/mlr/surveydag.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Monica’s suggestion, where emotional stability and locus of control are correlated (indicated by double headed arrow), and both influence sleep quality (indicated by single headed arrows)</figcaption>
</figure>
</div>
</div>
</div>
<p>Monica tells me that if I want to look at how ‘locus of control’ is associated with sleep quality, it would be more useful to think about the association <em>after</em> controlling for emotional stability.</p>
<blockquote class="blockquote">
<p>How does locus of control (<code>loc</code>) influence sleep quality (<code>sleeprating</code>) <em>after</em> accounting for emotional stability (<code>emot_stability</code>)?</p>
</blockquote>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li><p>See section <a href="08a_mlr.html#multiple-regression-coefficients" target="_blank">8A#multiple-regression-coefficients</a> for how this might be achieved.</p></li>
<li><p>the way the question is phrased suggests that <code>sleeprating</code> is our outcome (the thing being explained/influenced/predicted); <code>loc</code> is the <em>focal predictor</em> (the main predictor of interest); and <code>emot_stability</code> is a <em>covariate</em>. we treat “covariates” and “focal predictors” exactly the same in the model: <code>lm(outcome ~ covariates and focal predictors)</code>, it is just terminology that we use to distinguish what we are interested in from what we want to acknowledge as being theoretically relevant.</p></li>
<li><p>Don’t worry about assumptions, we’ll take a look at them next.</p></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<p>First we read in the data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr2022.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our model is going to be sleep ratings predicted by emotional stability and locus of control:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>sleeplocmod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(sleeprating <span class="sc">~</span> emot_stability <span class="sc">+</span> loc, usmrdata)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sleeplocmod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sleeprating ~ emot_stability + loc, data = usmrdata)

Residuals:
    Min      1Q  Median      3Q     Max 
-65.886  -9.772   2.162  10.671  43.887 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)      9.5850    12.9005   0.743  0.45978   
emot_stability   0.9083     0.2695   3.370  0.00118 **
loc              1.4192     0.5740   2.472  0.01565 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.91 on 76 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.2454,    Adjusted R-squared:  0.2255 
F-statistic: 12.36 on 2 and 76 DF,  p-value: 2.256e-05</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p>Monica and I want to write up our study of how locus of control is associated with sleep ratings.</p>
<p>However, we haven’t checked any of our model assumptions, and so we shouldn’t really trust the p-values we have been looking at so far.</p>
<p>Take a look at the assumptions and diagnostics of your model. If your assumptions are worryingly weird, there are things that may be useful to consider doing. We would probably recommend bootstrapping (see <a href="08b_assumptdiag.html#back-to-the-bootstrap">8B#back-to-the-bootstrap</a>).</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li><p>You can ask yourself one of two questions (or both if you like), but we recommend the visualisation approach:</p>
<ul>
<li>Do the plots look okay? (<a href="08b_assumptdiag.html#plotting-assumptions" target="_blank">8B#plotting-assumptions</a>)</li>
<li>Do the residuals pass statistical tests? (<a href="08b_assumptdiag.html#testing-assumptions" target="_blank">8B#testing-assumptions</a>)</li>
</ul></li>
<li><p>It’s also worth taking a look at the ‘diagnostics’ (such as the influence of individual cases, see <a href="08b_assumptdiag.html#individual-case-diagnostics" target="_blank">8B#individual-case-diagnostics</a>.</p></li>
<li><p>In order to bootstrap, you might need to fit the model to a dataset without any NAs in it.</p></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<p>Let’s have a little look at assumption plots:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sleeplocmod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_ex_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>None of these plots look great to me.</p>
<ul>
<li>The “residuals vs fitted” shows a curved line rather than a horizontal line at 0</li>
<li>The “normal QQ” plot looks okay apart from a couple of points that are dragging it down at the bottom.</li>
<li>The “scale-location” plot indicates the variance of residuals changes across the fitted values (the red line isn’t horizontal).</li>
<li>The “residuals vs leverage” plot shows a few points might be quite influential. However, they are within the bounds of the cook’s distance thresholds (the dotted lines).
<ul>
<li>note that some of these points, the 46th and 47th observations, are the same as the ones pulling down the QQplot..</li>
</ul></li>
</ul>
<p>Let’s take a look at if we have some people who are too influential:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">influence.measures</span>(sleeplocmod2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Potentially influential observations of
     lm(formula = sleeprating ~ emot_stability + loc, data = usmrdata) :

   dfb.1_ dfb.emt_ dfb.loc dffit   cov.r   cook.d hat    
21 -0.02  -0.04     0.05    0.06    1.18_*  0.00   0.12_*
25  0.06  -0.05    -0.04   -0.08    1.15_*  0.00   0.10  
37  0.33  -0.08    -0.24    0.39    0.87_*  0.05   0.03  
46  0.26  -0.64     0.03   -0.79_*  0.67_*  0.18   0.04  
47  0.17   0.30    -0.41   -0.58    0.72_*  0.10   0.03  
65 -0.90  -0.03     0.88   -0.94_*  1.17_*  0.29   0.21_*
70  0.02   0.07    -0.07   -0.10    1.22_*  0.00   0.15_*</code></pre>
</div>
</div>
<p>According to cooks distance, all of these are fine (no stars next to the <code>cook.d</code> column values). However, observations 46, 47 and 65 all have fairly large values for some of the DFbeta - suggesting they have fairly large influence (relative to the other observations) on our coefficients.</p>
<p>Let’s perform a bootstrap, which means we can relax our assumptions about the distribution of the residuals.</p>
<p>To do so, we need to get a dataset with only <em>complete cases</em>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>moddata <span class="ot">&lt;-</span> usmrdata <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sleeprating, emot_stability, loc) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then refit the model and bootstrap:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>sleeplocmod2a <span class="ot">&lt;-</span> <span class="fu">lm</span>(sleeprating <span class="sc">~</span> emot_stability <span class="sc">+</span> loc, moddata)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>bootmod <span class="ot">&lt;-</span> <span class="fu">Boot</span>(sleeplocmod2a, <span class="at">R =</span> <span class="dv">2000</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">Confint</span>(bootmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bootstrap bca confidence intervals

                Estimate        2.5 %   97.5 %
(Intercept)    9.5849711 -18.92238462 41.23737
emot_stability 0.9083068   0.32088748  1.41394
loc            1.4191828  -0.03208951  2.65852</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 13
</div>
<div class="question-body">
<p>Monica convinces me that we have theoretical motivation for thinking that sleeprating is influenced by both emotional stability and locus of control.</p>
<p>Tia is curious if other aspects of personality influence sleep quality ratings. She knows that we measured 5 personality traits: emotional stability, imagination, extraversion, agreeableness, and conscientiousness.</p>
<p>Tia asks us:</p>
<blockquote class="blockquote">
<p>Over and above the influence of locus of control and emotional stability, are other personality traits important predictors of how sleep quality is rated?</p>
</blockquote>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>This question asks about the explanatory power of a <strong>set of</strong> predictors. The best way to test this might be model comparison (see <a href="08a_mlr.html#model-comparisons" target="_blank">8A#model-comparisons</a>)</li>
<li>To compare two models, the models need to be fitted to the <em>same</em> data. However, when we fit a model using <code>lm()</code>, rows where there is missing data for <em>any</em> of the variables in the model will be excluded.
<ul>
<li>if we have a model <code>mod1 &lt;- lm(y ~ x1)</code> and we compare it to <code>mod2 &lt;- lm(y ~ x1 + x2)</code>, if there is missing data on <code>x2</code>, then <code>mod2</code> will be fitted to a smaller set of the data.<br>
</li>
<li>a good approach is to make a separate object in your environment which is the data you want to model.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select all variables included in either model, and omit the NAs</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>moddata <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(y, x1, x2) <span class="sc">%&gt;%</span> na.omit</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># these two models will now be fitted to the same data</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1, moddata)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, moddata)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co"># meaning we can compare them:</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod1, mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-13" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')"> Solution </span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<p>Make a dataset with the complete cases on relevant variables:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>moddata <span class="ot">&lt;-</span> usmrdata <span class="sc">%&gt;%</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sleeprating, emot_stability, loc, extraversion, agreeableness, conscientiousness, imagination) <span class="sc">%&gt;%</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  na.omit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Fit two models, with and without the relevant set of personality variables:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(sleeprating <span class="sc">~</span> emot_stability <span class="sc">+</span> loc, moddata)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(sleeprating <span class="sc">~</span> emot_stability <span class="sc">+</span> loc <span class="sc">+</span> extraversion <span class="sc">+</span> agreeableness <span class="sc">+</span> conscientiousness <span class="sc">+</span> imagination, moddata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Conduct a model comparison:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2,m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: sleeprating ~ emot_stability + loc
Model 2: sleeprating ~ emot_stability + loc + extraversion + agreeableness + 
    conscientiousness + imagination
  Res.Df   RSS Df Sum of Sq      F  Pr(&gt;F)  
1     75 29996                              
2     71 26889  4    3107.3 2.0512 0.09638 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="rmarkdown" class="level1">
<h1>RMarkdown</h1>
<div class="question-begin">
Question 14
</div>
<div class="question-body">
<p>Create an RMarkdown document that presents and describes analyses that addresses the research questions below, and then presents and interprets the results.</p>
<blockquote class="blockquote">
<p><strong>Research Questions</strong></p>
<ol type="1">
<li>After accounting for emotional stability, how is perceived control over one’s life associated with quality of sleep?</li>
<li>In addition to the associations studied above, are other personality traits associated with differences in sleep quality?</li>
</ol>
</blockquote>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>You’ve done the modelling already in the last couple of questions, so this just a matter of writing, interpreting, and presenting!</li>
<li>Don’t forget that we have the “Rmd-bootcamp” materials for reference: <a href="https://uoepsy.github.io/scs/rmd-bootcamp/" target="_blank">https://uoepsy.github.io/scs/rmd-bootcamp/</a></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
</section>
<section id="optional-extra-conscientiousness" class="level1">
<h1>Optional Extra: Conscientiousness</h1>
<div class="question-begin">
Optional Question 15
</div>
<div class="question-body">
<div class="columns">
<div class="column" style="width:80%;">
<p>This is Eleanor Abernathy. She has been learning about astrology and horoscopes, but is still skeptical. She wants to know if, after accounting for differences between cat/dog people, a person’s month-of-birth is associated with how conscientious they are.</p>
</div><div class="column" style="width:20%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/mlr/Eleanor_Abernathy.png" width="60" height="100" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>Using the same USMR 2022 survey data, fit the a model and use it to address the following research question:</p>
<blockquote class="blockquote">
<p>After accounting for differences between cat/dog people, is month-of-birth associated with conscientiousness?</p>
</blockquote>
<div class="hints">
<p><strong>Hint:</strong></p>
<ul>
<li>Note that the question is more a matter of “is”/“does”, and not “what is”/“how does”.</li>
<li>To answer this question, we might be more inclined to analyse the variance in conscientiousness explained by birth-months (rather than looking at specific differences) - see <a href="08a.mlr#analysis-of-variance" target="_blank">8A#analysis-of-variance</a>.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-14" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-14', 'sol-start-14')"> Solution </span>
</div>
<div id="sol-body-14" class="solution-body" style="display: none;">
<p>Here’s our data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>usmrdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr2022.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To conduct the analyis of variance, all we do is fit a linear model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>bmonthmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(conscientiousness <span class="sc">~</span> catdog <span class="sc">+</span> birthmonth, <span class="at">data =</span> usmrdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and then pass that to the <code>anova()</code> function, in order to examine the variance explained by the <code>birthmonth</code> grouping as a whole:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(bmonthmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: conscientiousness
           Df  Sum Sq Mean Sq F value Pr(&gt;F)
catdog      1   49.80  49.796  1.2748 0.2629
birthmonth 11  610.24  55.477  1.4202 0.1846
Residuals  67 2617.16  39.062               </code></pre>
</div>
</div>
<p>Interestingly, note that one of our birthmonth coefficients <strong>is</strong> significant!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bmonthmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = conscientiousness ~ catdog + birthmonth, data = usmrdata)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.8046  -3.6269   0.4943   4.6773   9.1954 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     32.259      2.500  12.902   &lt;2e-16 ***
catdogdog        1.989      1.560   1.275   0.2068    
birthmonthaug    2.414      3.398   0.710   0.4799    
birthmonthdec    1.749      3.378   0.518   0.6063    
birthmonthfeb   -7.247      6.641  -1.091   0.2790    
birthmonthjan    4.500      3.827   1.176   0.2439    
birthmonthjul    1.416      2.856   0.496   0.6217    
birthmonthjun   -1.752      2.974  -0.589   0.5578    
birthmonthmar    5.247      3.398   1.544   0.1272    
birthmonthmay   -0.454      3.014  -0.151   0.8807    
birthmonthnov    1.313      3.440   0.382   0.7039    
birthmonthoct    1.951      3.564   0.547   0.5860    
birthmonthsep    8.546      3.605   2.371   0.0206 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.25 on 67 degrees of freedom
Multiple R-squared:  0.2014,    Adjusted R-squared:  0.05837 
F-statistic: 1.408 on 12 and 67 DF,  p-value: 0.1843</code></pre>
</div>
</div>
<p>This is because it is testing the <em>specific</em> difference between September and April (the reference level). Taken alone, this is a significant difference. But considered all together, the month-level differences in conscientiousness aren’t significant <em>enough</em> to improve over what we’d expect from 12 random groupings.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(usmrdata, <span class="fu">aes</span>(<span class="at">x=</span>birthmonth, <span class="at">y=</span>conscientiousness)) <span class="sc">+</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08_ex_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>When designing a study/collected data, it’s good practice to do this sort of thinking before hand, to make sure you measure all the things you want to measure<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>