<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - Week 11 Exercises: Tying up Loose Ends</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-down')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>
<link href="site_libs/panelset-0.3.0/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.3.0/panelset.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html" rel="" target="">
 <span class="dropdown-text">1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html" rel="" target="">
 <span class="dropdown-text">1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html" rel="" target="">
 <span class="dropdown-text">2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html" rel="" target="">
 <span class="dropdown-text">2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 3</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html" rel="" target="">
 <span class="dropdown-text">3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html" rel="" target="">
 <span class="dropdown-text">3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: T-tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 4</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04a_chisq.html" rel="" target="">
 <span class="dropdown-text">4A: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revisitnhst.html" rel="" target="">
 <span class="dropdown-text">4B: Revisiting NHST</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 5</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li>
    <a class="dropdown-item" href="./05a_covcor.html" rel="" target="">
 <span class="dropdown-text">5A: Covariance &amp; Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Cov, Cor, Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-6" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 6</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-6">    
        <li>
    <a class="dropdown-item" href="./06_wt.html" rel="" target="">
 <span class="dropdown-text">Walkthrough: Advanced Data Wrangling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 7</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li>
    <a class="dropdown-item" href="./07a_slr.html" rel="" target="">
 <span class="dropdown-text">7A: Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Simple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 8</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li>
    <a class="dropdown-item" href="./08a_mlr.html" rel="" target="">
 <span class="dropdown-text">8A: Multiple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08b_assumptdiag.html" rel="" target="">
 <span class="dropdown-text">8B: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Multiple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 9</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li>
    <a class="dropdown-item" href="./09a_interactions.html" rel="" target="">
 <span class="dropdown-text">9A: Interactions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09b_contrasts.html" rel="" target="">
 <span class="dropdown-text">9B: Categorical Predictors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Interactions</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-10" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 10</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-10">    
        <li>
    <a class="dropdown-item" href="./10a_glm.html" rel="" target="">
 <span class="dropdown-text">10A: GLM!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Logistic Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-11" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Week 11</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-11">    
        <li>
    <a class="dropdown-item" href="./11_ex.html" rel="" target="">
 <span class="dropdown-text">Exercises: Tying up Loose Ends</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#couch-to-5k" id="toc-couch-to-5k" class="nav-link active" data-scroll-target="#couch-to-5k">Couch to 5k</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 11 Exercises: Tying up Loose Ends</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="lo">
<p><strong>Please Note</strong></p>
<p>This might look like a lot of stuff, but it is just writing, bit by bit, the stuff that we have covered through the course. This is not a “perfect” answer (I may well have made mistakes, or have written certain sections unclearly).<br>
With regards to the coursework report, there are marks available even if you don’t get all of the “bits” – most important is to think carefully about what the questions are really asking (and therefore what kind of test might be appropriate), and to explain your analytical process as clearly as you can, pulling out and interpreting the key information from the models that help to guide the reader to your conclusion.</p>
</div>
<section id="couch-to-5k" class="level1">
<h1>Couch to 5k</h1>
<div class="frame">
<p><strong>Background: Couch to 5k</strong></p>
<p><a href="https://www.nhs.uk/live-well/exercise/get-running-with-couch-to-5k/">Couch to 5k</a> is an NHS-sponsored fitness programme which lasts 9 weeks, taking participants from a gentle start up to a half-hour run.</p>
<p>The NHS wants to research some of the potential impact this programme has on wellbeing. They have conducted a small study of 121 people in 2 cities (Edinburgh and Glasgow), all of whom started the Couch to 5k programme, across the course of a year.</p>
<p>The researchers’ interests are two-fold: They are interested in the effects of taking the programme on psychological wellbeing, and also in the psychological factors that make people continue on the programme.</p>
<p><strong>Methods</strong></p>
<p>At Week 0, all participants completed a questionnaire measuring the psychometric factors of accountability and self-motivation.<br>
Upon either completing the programme (Week 9) or dropping out (&lt; Week 9), participants completed a questionnaire which included a measure of their self-reported happiness, and a “health” measure derived from a number of physiological tests. Researchers also recorded the season in which participants started the programme, as evidence from previous research suggests that the probability of completing the couch to 5k programme varies substantially across the year.</p>
<p>You can download the dataset from <a href="https://uoepsy.github.io/data/couchto5k.csv">https://uoepsy.github.io/data/couchto5k.csv</a>. Details of the variables can be found in the table below.</p>
<p><em>Please note that Couch to 5k is a real programme, but the data you will be analysing comes from our febrile minds.</em></p>
<hr>
<p><strong>Data Dictionary:</strong></p>
<table class="table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th>Content</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>pptID</code></td>
<td>random ID code for participant</td>
</tr>
<tr class="even">
<td><code>age</code></td>
<td>age in years</td>
</tr>
<tr class="odd">
<td><code>accountability</code></td>
<td>psychometric measure of accountability (or ‘responsibility’) (Sum of 5 questions, each scored 1-7).</td>
</tr>
<tr class="even">
<td><code>selfmot</code></td>
<td>psychometric measure of self-motivation (Sum of 5 questions, each scored 1-7)</td>
</tr>
<tr class="odd">
<td><code>health</code></td>
<td>multi-test health measure (0-100)</td>
</tr>
<tr class="even">
<td><code>happiness</code></td>
<td>simple happiness scale (0-100)</td>
</tr>
<tr class="odd">
<td><code>season</code></td>
<td>season of the year participants were interviewed in</td>
</tr>
<tr class="even">
<td><code>city</code></td>
<td>city participant was recruited in</td>
</tr>
<tr class="odd">
<td><code>week_stopped</code></td>
<td>week of programme participant stopped in (week 9 = completed the programme)</td>
</tr>
</tbody>
</table>
</div>
<div class="question-begin">
Clean and describe
</div>
<div class="question-body">
<p>Have a look at the data. Check for impossible values and deal with these in an appropriate manner. Describe the data, either in words or using suitable graphs (or a combination). Remember to detail the decisions you have made.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>to clean data, go through each variable in turn. If numeric, what is the min and max? If categorical, what are the possible levels?<br>
</li>
<li>to describe data, you might want to use tables and plots, or you might find describing in text can work too.<br>
</li>
<li>There’s no right way to deal with missing values.
<ul>
<li>one option is to cross-tabulate the <em>reasons for</em> missingness, and then remove them from the dataset at this point. This means all your analyses are conducted on the same set of “complete cases”. This can be the neat and tidy option, but if some variables have lots of missingness, you might end up needlessly limiting some of your analyses in terms of statistical power.</li>
<li>another option is to leave all missing values in the dataset and let them be dealt with by each of your model(s) and test(s). The downside of this is that different tests end up being performed on different subsets of data, making it harder to describe (it also means you need to be very careful with model comparisons)</li>
</ul></li>
<li>There’s no right way to deal with outliers.
<ul>
<li>Some fields of research will identify at the outset any observations that are outlying by looking at each variable individually. These they will then remove, or scale back (<a href="06_wt.html#outliers" target="_blank">6WalkThrough#outliers</a>) prior to any analysis. This should really only be done if you are sure that these observations are outlying because of either a) measurement error or b) not belonging to the target population of interest. If the outlyingness could well simply be natural variation in the variable, keep it in. You can always then examine its influence on subsequent analyses!</li>
</ul></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-1" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')"> Explore</span>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>couchto5k <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/couchto5k.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Going through each variable:</p>
<ul>
<li><code>age</code> is an integer variable, shouldn’t have negative values <strong>by definition of variable</strong>. There are a couple of values <span class="math inline">\(\geq 100\)</span>, which we should probably either exclude, or at the very least mention in our writing.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(couchto5k<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  18.00   32.00   39.00   40.62   48.00  129.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(couchto5k<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_ex_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><code>accountability</code> and <code>selfmot</code> are both integer variables should both be <span class="math inline">\(5 \leq x \leq 35\)</span> - <strong>by definition</strong></li>
</ul>
<p>We can see that <code>accountability</code> looks to be okay, but <code>selfmot</code> has a minimum value of -99, which we can’t have.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>couchto5k <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(accountability, selfmot) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> accountability     selfmot      
 Min.   : 6.00   Min.   :-99.00  
 1st Qu.:16.00   1st Qu.: 13.00  
 Median :20.00   Median : 15.00  
 Mean   :19.92   Mean   : 12.84  
 3rd Qu.:23.00   3rd Qu.: 17.00  
 Max.   :32.00   Max.   : 23.00  </code></pre>
</div>
</div>
<ul>
<li><code>health</code> and <code>happiness</code> are both integer and should be <span class="math inline">\(0 \leq x \leq 100\)</span> - <strong>by definition of variable</strong></li>
</ul>
<p>both <code>health</code> and <code>happiness</code> variables are within the possible ranges</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>couchto5k <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(health, happiness) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     health        happiness     
 Min.   :35.00   Min.   :  0.00  
 1st Qu.:50.00   1st Qu.: 17.00  
 Median :57.00   Median : 44.00  
 Mean   :56.99   Mean   : 44.69  
 3rd Qu.:64.00   3rd Qu.: 69.00  
 Max.   :82.00   Max.   :100.00  </code></pre>
</div>
</div>
<ul>
<li><code>season</code> should be one of “spring”, “summer”, “autumn”, “winter”</li>
</ul>
<p>We have some mis-spellings of “autumn” as “autunm” which we should fix<br>
(i’m adding in the <code>useNA="always"</code> bit just so i can also see if there are any that are already missing)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(couchto5k<span class="sc">$</span>season, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
autumn autunm spring summer winter   &lt;NA&gt; 
     6      4     67     36      8      0 </code></pre>
</div>
</div>
<ul>
<li><code>city</code> should be one of “Edinburgh”, “Glasgow”</li>
</ul>
<p>This looks fine:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(couchto5k<span class="sc">$</span>city, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Edinburgh   Glasgow      &lt;NA&gt; 
       87        34         0 </code></pre>
</div>
</div>
<ul>
<li><code>week_stopped</code> is an integer variable and should be <span class="math inline">\(1 \leq x \leq 9\)</span> - <strong>by definition of variable</strong></li>
</ul>
<p>We have an entry of 12, which we can’t have. Could this be interpreted as someone doing the programme for an extra 5 weeks beyond the 9? In which case could we turn that 12 into a 9? It’s just a possible that it’s a typo, and it’s supposed to be a 1. This ambiguity is probably going to be best dealt with by considering that datapoint to be missing.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(couchto5k<span class="sc">$</span>week_stopped, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    7    8    9   12 &lt;NA&gt; 
  12   11   10   15    3    5    4   60    1    0 </code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Clean</span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<p>We’ll do all of our cleaning inside one <code>mutate()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>couchto5k <span class="ot">&lt;-</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  couchto5k <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># ages &gt;100, make NA</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">age =</span> <span class="fu">ifelse</span>(age<span class="sc">&gt;</span><span class="dv">100</span>, <span class="cn">NA</span>, age),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># selfmot scores &lt;5, make NA</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">selfmot =</span> <span class="fu">ifelse</span>(selfmot <span class="sc">&lt;</span> <span class="dv">5</span>, <span class="cn">NA</span>, selfmot),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># change autunm to autumn</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">season =</span> <span class="fu">ifelse</span>(season <span class="sc">==</span> <span class="st">"autunm"</span>,<span class="st">"autumn"</span>,season),</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># and then make it a factor (lets set the levels too)</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">season =</span> <span class="fu">factor</span>(season, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"spring"</span>,<span class="st">"summer"</span>,<span class="st">"autumn"</span>,<span class="st">"winter"</span>)),</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># make city a factor</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">city =</span> <span class="fu">factor</span>(city),</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># weekstopped if &gt;9, then NA</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">week_stopped =</span> <span class="fu">ifelse</span>(week_stopped <span class="sc">&gt;</span> <span class="dv">9</span>, <span class="cn">NA</span>, week_stopped)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(couchto5k)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    pptID                age        accountability     selfmot     
 Length:121         Min.   :18.00   Min.   : 6.00   Min.   : 7.00  
 Class :character   1st Qu.:32.00   1st Qu.:16.00   1st Qu.:13.00  
 Mode  :character   Median :39.00   Median :20.00   Median :15.00  
                    Mean   :39.35   Mean   :19.92   Mean   :14.72  
                    3rd Qu.:47.50   3rd Qu.:23.00   3rd Qu.:17.00  
                    Max.   :60.00   Max.   :32.00   Max.   :23.00  
                    NA's   :2                       NA's   :2      
     health        happiness         season          city     week_stopped  
 Min.   :35.00   Min.   :  0.00   spring:67   Edinburgh:87   Min.   :1.000  
 1st Qu.:50.00   1st Qu.: 17.00   summer:36   Glasgow  :34   1st Qu.:3.000  
 Median :57.00   Median : 44.00   autumn:10                  Median :8.500  
 Mean   :56.99   Mean   : 44.69   winter: 8                  Mean   :6.217  
 3rd Qu.:64.00   3rd Qu.: 69.00                              3rd Qu.:9.000  
 Max.   :82.00   Max.   :100.00                              Max.   :9.000  
                                                             NA's   :1      </code></pre>
</div>
</div>
<p>Because we know that the resulting missingness is restricted to a relatively small proportion of the dataset, we’ll just stick with the complete cases.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>couchto5k <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(couchto5k)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Describe</span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>121 participants were recruited to take part in the study. 2 participants recorded ages exceeding 100, 2 participants recorded an impossible score on the self-motivation scale, and a further one participant recorded having stopped the programme 3 weeks after the defined maximum. These 5 participants were excluded from all analyses.</p>
<p>The remaining 116 participants were all over 18 (Mean age 40, SD 11.3) and were recruited from Edinburgh (73%) and Glasgow (27%). The median number of weeks spent in the ‘couch-to-5k’ programme was 8.5, with 50% successfully completing the 9 weeks. Spring and summer were the most common seasons for attempting the programme (56% and 30% of participants respectively), with 8% undertaking it in autumn and only 6% in winter.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
City differences
</div>
<div class="question-body">
<p>The researchers conducting the study want to first find out a little more about differences between the Edinburgh and Glasgow study sites. Specifically, they would like to investigate whether dropping out of the programme early (prior to week 5), late (week 5 onwards) or not at all (completed all 9 weeks), is different between Edinburgh and Glasgow participants. They would also like to know if the average age of participants is different between the cities.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>The first 5 weeks of the course focused on some of the more fundamental tests of relationships between two variables. Some of these might be useful here!</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Conducting the tests</span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>There are two questions here, <code>dropout ~ city</code> and <code>age ~ city</code>. These are nice and simple questions about the relationships between only two variables.</p>
<p>The <code>dropout ~ city</code> question is asking us to categorise when participants stop the programme into “early”, “late”, or “not at all”. So the question is <code>categorical ~ categorical</code>. Sounds like a <span class="math inline">\(\chi^2\)</span> test to me!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>couchto5k <span class="ot">&lt;-</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  couchto5k <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">dropout =</span> <span class="fu">ifelse</span>(week_stopped <span class="sc">&lt;</span> <span class="dv">5</span>, <span class="st">"early"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">ifelse</span>(week_stopped <span class="sc">&lt;</span><span class="dv">9</span>, <span class="st">"late"</span>, <span class="st">"not at all"</span>))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>let’s check that the above <code>ifelse</code> statement worked as we wanted:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(couchto5k<span class="sc">$</span>dropout, couchto5k<span class="sc">$</span>week_stopped)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            
              1  2  3  4  5  7  8  9
  early      12 10 10 14  0  0  0  0
  late        0  0  0  0  3  5  4  0
  not at all  0  0  0  0  0  0  0 58</code></pre>
</div>
</div>
<p>and let’s look at the differences between the cities, and also perform a <span class="math inline">\(\chi^2\)</span> test. We’re going to simulate the p-value here, because some of our expected cell counts are going to be <span class="math inline">\(&lt;5\)</span> (see e.g.&nbsp;<a href="04_ex.html#eye-colours" target="_blank">Week 4 Exercises #eye-colours</a>)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(couchto5k<span class="sc">$</span>dropout, couchto5k<span class="sc">$</span>city)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(couchto5k<span class="sc">$</span>dropout, couchto5k<span class="sc">$</span>city), <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>            
             Edinburgh Glasgow
  early             34      12
  late               8       4
  not at all        43      15</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with simulated p-value (based on 2000
    replicates)

data:  table(couchto5k$dropout, couchto5k$city)
X-squared = 0.29923, df = NA, p-value = 0.9055</code></pre>
</div>
</div>
<p><br><br></p>
<p>The <code>age ~ city</code> question, on the other hand, is asking whether a continuous variable is different between two groups (Edinburgh and Glasgow). We can do this with a <span class="math inline">\(t\)</span>-test!</p>
<p>Let’s first assess the extent to which the ages of two groups of participants (Edinburgh folk and Glasgow folk) have similar variances (an assumption of the standard t-test), as well as the extent to which they are normally distributed:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(couchto5k<span class="sc">$</span>age[couchto5k<span class="sc">$</span>city<span class="sc">==</span><span class="st">"Edinburgh"</span>], </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Edinburgh"</span>, <span class="at">xlab =</span> <span class="st">"Age"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(couchto5k<span class="sc">$</span>age[couchto5k<span class="sc">$</span>city<span class="sc">==</span><span class="st">"Glasgow"</span>], </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Glasgow"</span>, <span class="at">xlab =</span> <span class="st">"Age"</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(couchto5k<span class="sc">$</span>age[couchto5k<span class="sc">$</span>city<span class="sc">==</span><span class="st">"Edinburgh"</span>], <span class="at">main =</span> <span class="st">"Edinburgh"</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(couchto5k<span class="sc">$</span>age[couchto5k<span class="sc">$</span>city<span class="sc">==</span><span class="st">"Edinburgh"</span>])</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(couchto5k<span class="sc">$</span>age[couchto5k<span class="sc">$</span>city<span class="sc">==</span><span class="st">"Glasgow"</span>], <span class="at">main =</span> <span class="st">"Glasgow"</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(couchto5k<span class="sc">$</span>age[couchto5k<span class="sc">$</span>city<span class="sc">==</span><span class="st">"Glasgow"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_ex_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These look almost okay to me. Not great, but not completely awful. We should bear in mind that we have &gt;30 participants in each group, which means we can be a little more relaxed about requiring very close to normal data.</p>
<p>The test of equal variances suggests we have no reason to reject the hypothesis that the two groups have equal variances:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(age <span class="sc">~</span> city, <span class="at">data =</span> couchto5k)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  age by city
F = 1.2079, num df = 84, denom df = 30, p-value = 0.5703
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.6361894 2.1058008
sample estimates:
ratio of variances 
          1.207877 </code></pre>
</div>
</div>
<p>So we can carry on with our t-test of the difference in means<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(age <span class="sc">~</span> city, <span class="at">data =</span> couchto5k, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  age by city
t = 1.2222, df = 114, p-value = 0.2242
alternative hypothesis: true difference in means between group Edinburgh and group Glasgow is not equal to 0
95 percent confidence interval:
 -1.790235  7.557218
sample estimates:
mean in group Edinburgh   mean in group Glasgow 
               40.27059                37.38710 </code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Writing up</span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>A <span class="math inline">\(\chi^2\)</span> test of independence indicated that rate of attrition (early-/late-/no- dropout) did not significantly differ between Edinburgh and Glasgow (<span class="math inline">\(\chi^2\)</span>(2, n=116) = 0.299, Monte Carlo simulated (B=2000) p = 0.906). From both cities, approximately half of participants did not drop out of the programme, late drop-outs made up 13% of Glasgow participants and 9% of those from Edinburgh, with the remainder dropping out early (39% of Glasgow, 40% of Edinburgh).</p>
<p>The mean age of participants was not significantly different between the two cities (<span class="math inline">\(t( 114 )=1.22\)</span>, <span class="math inline">\(p=0.22\)</span>), with a mean age in Edinburgh of 40.3 and in Glasgow of 37.4.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Happiness, Health, and a 5k Run
</div>
<div class="question-body">
<p>Researchers would like you to examine whether, beyond seasonal and age-related variation, happiness ratings are influenced by how far participants get through the couchto5k programme. They would also like you to investigate whether - and how - the effects of couchto5k progression are amplified by feeling healthy, such that getting further along in the programme might lead to greater increases in happiness when people are healthier.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>The use of the word “beyond” here should cue us to be thinking in terms of multiple regression. The question is asking about the relationship between happiness and couchto5k progression <em>after</em> we account for participants’ ages and the season in which they took the programme.<br>
</li>
<li>We also have a clear suggestion of an interaction here, because it asks about an effect of one predictor on the outcome (programme progression on happiness) being “amplified” (i.e.&nbsp;<em>different</em>) by another predictor (health)</li>
<li>This feels a bit like two questions, but we might not need to fit two models.
<ul>
<li>for instance by fitting <code>mod &lt;- lm(y ~ x1 + x2 + x3 + x4 + x3:x4)</code>, use of <code>anova(mod)</code> might allow us to answer multiple “<em>is</em> there an effect of ?” questions, with <code>coef(mod)</code> telling us <em>what</em>.</li>
</ul></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Fitting model(s)</span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<p>here’s our model.<br>
let’s standardise the health measure, because we probably don’t want to look at things where people have health of 0, and i’m not sure that an increase of 1 is that meaningful..</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>couchto5k <span class="ot">&lt;-</span> couchto5k <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">healthC =</span> (health<span class="sc">-</span><span class="fu">mean</span>(health))<span class="sc">/</span><span class="fu">sd</span>(health),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>hhmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness <span class="sc">~</span> age <span class="sc">+</span> season <span class="sc">+</span> week_stopped <span class="sc">*</span> healthC, couchto5k)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>let’s take a look at assumptions</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hhmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_ex_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>so this looks a little weird - we’ve got some sharp ‘edges’ to our cloud of data in the residual vs fitted plot.<br>
What I think this is reflecting is that we are being limited by the bounds of the happiness measure (i.e.&nbsp;people are using the full scale of 0 upto 100). Consider how this might influence the residuals. As predicted values get closer to the edges of the scale, the residuals will get smaller. This might not be too much of a problem, but may well be worth discussing.</p>
<p>Let’s conduct an anova in order to look at how weekstopped explains variance after the season and age. Remember that the order of the predictors in the model matters here, so i was careful to put age and season first, <em>then</em> week stopped, <em>then</em> the health and interaction bit.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(hhmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: happiness
                      Df Sum Sq Mean Sq F value    Pr(&gt;F)    
age                    1   1074  1073.6  1.2983   0.25704    
season                 3   6422  2140.7  2.5888   0.05669 .  
week_stopped           1   3264  3263.8  3.9470   0.04949 *  
healthC                1    110   109.5  0.1325   0.71661    
week_stopped:healthC   1  25379 25378.5 30.6910 2.153e-07 ***
Residuals            108  89306   826.9                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p>the third row tells us that after accounting for age and season, weekstopped explains more variance than we would expect by chance</p></li>
<li><p>the final row tells us the interaction weekstopped*health also explains significantly more variance than we would expect by chance</p></li>
<li><p>the coefficients can tell us effects sizes, directions etc.<br>
</p></li>
<li><p>we can also, if we want, get out some standardised coefficients.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hhmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           23.7368    13.0236   1.823   0.0711 .  
age                    0.3638     0.3130   1.162   0.2477    
seasonsummer           1.4023     8.4395   0.166   0.8683    
seasonautumn         -14.4972    12.0201  -1.206   0.2304    
seasonwinter         -22.7635    13.0608  -1.743   0.0842 .  
week_stopped           1.6887     1.2824   1.317   0.1907    
healthC              -31.0210     6.8032  -4.560 1.36e-05 ***
week_stopped:healthC   5.0320     0.9083   5.540 2.15e-07 ***</code></pre>
</div>
</div>
<ul>
<li>and plots are going to be a useful way to understand and to present.</li>
</ul>
<p>getting further along the couchto5k programme is associated with being more happy, the more healthy you feel</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(hhmod, <span class="at">pred=</span><span class="st">"week_stopped"</span>,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">modx =</span> <span class="st">"healthC"</span>, </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">interval=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_ex_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>We can also get out some coefficients in terms of standard deviations if we want (for those predictors where SD is applicable).</p>
<div class="imp">
<p><strong>note:</strong> post-hoc standardising of coefficient with pacakges like <strong>lsr</strong> and <strong>lm.beta</strong> is probably best avoided when your model contains either categorical predictors or interactions.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>hhmod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">scale</span>(happiness) <span class="sc">~</span> <span class="fu">scale</span>(age) <span class="sc">+</span> season <span class="sc">+</span> <span class="fu">scale</span>(week_stopped) <span class="sc">*</span> <span class="fu">scale</span>(healthC), <span class="at">data =</span> couchto5k)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hhmod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Coefficients:
                                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                         0.098261   0.134015   0.733   0.4650    
scale(age)                          0.124067   0.106738   1.162   0.2477    
seasonsummer                        0.042441   0.255419   0.166   0.8683    
seasonautumn                       -0.438752   0.363783  -1.206   0.2304    
seasonwinter                       -0.688930   0.395280  -1.743   0.0842 .  
scale(week_stopped)                 0.161352   0.122529   1.317   0.1907    
scale(healthC)                      0.009042   0.106258   0.085   0.9323    
scale(week_stopped):scale(healthC)  0.480784   0.086785   5.540 2.15e-07 ***</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Writing up</span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>To investigate the extent to which, over and above seasonal and age related differences, happiness ratings are associated with getting further through (and feeling healthier following) the couch-to-5k programme, happiness ratings on a scale of 0 to 100 were modelled using multiple regression.</p>
<p>The number of weeks at which participants stopped (1-9), a multi-test measure of health (Z-scored) and their interaction were included as predictors, along with the covariates of age (years) and season (treatment coded with spring as the reference level). The regression model appeared to meet all assumptions, with residuals displaying a constant mean at approximately zero (see Appendix X), although the boundaries of the happiness scale induced a smaller residual variance at the tail ends of the fitted values (see Appendix X). This is corroborated by 30% of participants reporting happiness in either the bottom or top 10th of the scale.</p>
<p>Analysis of variance indicated that after accounting for season and age, the week at which participants stopped the couch-to-5k programme explained significantly more variation in happiness ratings than would be expected by chance (<span class="math inline">\(F(1,108)=3.95\)</span>, <span class="math inline">\(p = 0.049\)</span>). Results also showed a significant interaction between health and programme progression (<span class="math inline">\(F(1,108)=30.69\)</span>, <span class="math inline">\(p &lt;0.001\)</span>). The full model explained approximately 24% (adjusted <span class="math inline">\(R^2\)</span>) of the variance in happiness scores.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-couchanova" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1: Analysis of variance in happiness scores</caption>
<colgroup>
<col style="width: 37%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">&nbsp;</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">Sum Sq</th>
<th style="text-align: center;">Mean Sq</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Age</strong></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1074</td>
<td style="text-align: center;">1074</td>
<td style="text-align: center;">1.3</td>
<td style="text-align: center;">0.257</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Season</strong></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6422</td>
<td style="text-align: center;">2141</td>
<td style="text-align: center;">2.59</td>
<td style="text-align: center;">0.057</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Week Stopped</strong></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3264</td>
<td style="text-align: center;">3264</td>
<td style="text-align: center;">3.95</td>
<td style="text-align: center;"><strong>0.049</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Health</strong></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">0.717</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Week Stopped : Health</strong></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">25379</td>
<td style="text-align: center;">25379</td>
<td style="text-align: center;">30.69</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Residual</strong></td>
<td style="text-align: center;">108</td>
<td style="text-align: center;">89306</td>
<td style="text-align: center;">827</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>For those of average health, there was no statistically reliable change in happiness associated with additional weeks of the couch-to-5k programme (<span class="math inline">\(b = 1.69\)</span>, <span class="math inline">\(\beta = 0.16\)</span>, <span class="math inline">\(t(108) = \, 1.32\)</span>, <span class="math inline">\(p = 0.191\)</span>).</p>
<p>However this effect was moderated by health such that the weekly change in happiness was more positive for healthier, and more negative for less healthy, people. For each 1SD (10 raw points) change in health from the average, happiness ratings changed by an additional 5.03 points every week (<span class="math inline">\(b = 5.03\)</span>, <span class="math inline">\(\beta = 0.48\)</span>, <span class="math inline">\(t(108) = \, 5.54\)</span>, <span class="math inline">\(p &lt;0.001\)</span>). <a href="#fig-couchint">Figure&nbsp;1</a> shows the shape of this interaction, and a full regression table can be found in <a href="#tbl-couchinttab">Table&nbsp;2</a>.</p>
<p>Happiness following the couch-to-5k programme was found to be related to how far through the programme participants got, and this relationship depended on participant health, with the happiness healthier participants increasing more for every week longer through the programme they lasted than it did for participants of average health.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-couchint" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="11_ex_files/figure-html/fig-couchint-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Interaction between health and duration completed of couch-to-5k on happiness</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-couchinttab" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;2: Happiness ratings (0-100). Table of regression coefficients</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Happiness (0-100)</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">23.74</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-2.08&nbsp;–&nbsp;49.55</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.071</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Age (years)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.36</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.26&nbsp;–&nbsp;0.98</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.248</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Season [Summer]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.40</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-15.33&nbsp;–&nbsp;18.13</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.868</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Season [Autumn]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-14.50</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-38.32&nbsp;–&nbsp;9.33</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.230</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Season [Winter]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-22.76</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-48.65&nbsp;–&nbsp;3.13</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.084</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Week Stopped (1-9)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.69</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.85&nbsp;–&nbsp;4.23</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.191</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Health Metric (Z-scored)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-31.02</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-44.51&nbsp;–&nbsp;-17.54</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Week Stopped * Health Metric</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.03</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3.23&nbsp;–&nbsp;6.83</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">116</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.289 / 0.243</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Predictors of Drop-out
</div>
<div class="question-body">
<p>The second aim of the research is to examine the psychological factors that are associated with people completing the programme.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>Completing vs Dropping-out? Sounds like a binary outcome!<br>
</li>
<li>Recall (from study description above) that completing the programme has previously been found to vary substantially across the year. <em>We may well therefore want to account for this in our model!</em><br>
</li>
<li>What variables do we have that measure “psychological factors” that might influence dropping out? (pay attention to <em>when</em> each variable is measured!)<br>
</li>
<li>How might we visualise the results?</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Fitting model(s)</span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>We need to make a binary outcome, out of the <code>week_stopped</code> variable.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>couchto5k <span class="ot">&lt;-</span> couchto5k <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">completed =</span> <span class="fu">ifelse</span>(week_stopped <span class="sc">==</span> <span class="dv">9</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>here are our variables:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(couchto5k)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "pptID"          "age"            "accountability" "selfmot"       
 [5] "health"         "happiness"      "season"         "city"          
 [9] "week_stopped"   "dropout"        "healthC"        "completed"     </code></pre>
</div>
</div>
<p>per the study description, many of these were measured after participants stopped programme</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 23%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">variable</th>
<th style="text-align: center;">when</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">pptID</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">age</td>
<td style="text-align: center;">unclear when measured, but assume it is consistent at both points</td>
</tr>
<tr class="odd">
<td style="text-align: center;">accountability</td>
<td style="text-align: center;">measured at start</td>
</tr>
<tr class="even">
<td style="text-align: center;">selfmot</td>
<td style="text-align: center;">measured at start</td>
</tr>
<tr class="odd">
<td style="text-align: center;">health</td>
<td style="text-align: center;">measured at end</td>
</tr>
<tr class="even">
<td style="text-align: center;">happiness</td>
<td style="text-align: center;">measured at end</td>
</tr>
<tr class="odd">
<td style="text-align: center;">season</td>
<td style="text-align: center;">measured at start</td>
</tr>
<tr class="even">
<td style="text-align: center;">city</td>
<td style="text-align: center;">unclear when measured, but assume it is consistent at both points</td>
</tr>
<tr class="odd">
<td style="text-align: center;">week_stopped</td>
<td style="text-align: center;">measured at end</td>
</tr>
<tr class="even">
<td style="text-align: center;">dropout</td>
<td style="text-align: center;">measured at end</td>
</tr>
<tr class="odd">
<td style="text-align: center;">completed</td>
<td style="text-align: center;">measured at end</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>it doesn’t really make sense for us to think about your happiness <em>after</em> the programme influencing whether or not you complete it (this is not to say that it will not be associated).</p>
<p>age, season and city are all things that <em>might</em> influence completion, or might influence predictors of interest like accountability or self-motivation. We know specifically that season has previously been found to influence completion, so it would be good to at least include that. We also did a test early on that indicated that cities didn’t differ in their dropout rates, and also that they didn’t differ in the average age of participants.</p>
<p>It’s probably worth scaling the psychometric variables. They are both the sum of 7 questions, each scored 1-5, so it’s slightly unclear what a “1 unit increase” really means. It’s answering.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>couchto5k <span class="ot">&lt;-</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  couchto5k <span class="sc">%&gt;%</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">accountabilityZ =</span> <span class="fu">scale</span>(accountability)[,<span class="dv">1</span>],</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">selfmotZ =</span> <span class="fu">scale</span>(selfmot)[,<span class="dv">1</span>]</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>compmod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(completed <span class="sc">~</span> season <span class="sc">+</span> age <span class="sc">+</span> city, <span class="at">data =</span> couchto5k, <span class="at">family=</span>binomial)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>compmod2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(completed <span class="sc">~</span> season <span class="sc">+</span> age <span class="sc">+</span> city <span class="sc">+</span> accountabilityZ <span class="sc">+</span> selfmotZ, <span class="at">data =</span> couchto5k, <span class="at">family=</span>binomial)</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(compmod1, compmod2, <span class="at">test=</span><span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: completed ~ season + age + city
Model 2: completed ~ season + age + city + accountabilityZ + selfmotZ
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)  
1       110     98.794                       
2       108     91.010  2   7.7836  0.02041 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>beyond participants’ age, location and which season programme is undertaken in, psychological factors of accountability and self motivation <em>do</em> appear to improve model fit</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(compmod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = completed ~ season + age + city + accountabilityZ + 
seasonautumn     3.617e+00  1.180e+00   3.066  0.00217 ** 
seasonwinter     1.931e+01  1.420e+03   0.014  0.98915    
age              9.931e-04  2.357e-02   0.042  0.96640    
cityGlasgow     -7.770e-01  6.537e-01  -1.189  0.23459    
accountabilityZ -1.066e-01  2.788e-01  -0.383  0.70206    
selfmotZ         7.328e-01  2.771e-01   2.644  0.00818 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)</code></pre>
</div>
</div>
<p>worth visualising the two focal predictors in terms of predicted probability of completion</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(compmod2, <span class="at">type=</span><span class="st">"pred"</span>, <span class="at">term=</span><span class="fu">c</span>(<span class="st">"accountabilityZ"</span>)) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_model</span>(compmod2, <span class="at">type=</span><span class="st">"pred"</span>, <span class="at">term=</span><span class="fu">c</span>(<span class="st">"selfmotZ"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_ex_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Writing up</span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<p>Couch-to-5k completion (completed vs dropped out) was modelled using logistic regression, with the location (Glasgow, Edinburgh) and season in which participants undertake the programme as predictors, along with participants age, and their scores on two psychometric measures of accountability and self-motivation that were administered prior to participants starting the programme. A likelihood ratio test indicated that the inclusion of these two measures (accountability and self-motivation) collectively improves model fit over and above age, location and season (<span class="math inline">\(\chi^2(2) = 7.78, \, p = 0.02\)</span>). All deviance residuals for the full model were less than 3 in magnitude.</p>
<p>In keeping with previous research, completion of the programme was found to differ between seasons, with participants undertaking the programme in both summer and autumn being associated with increased odds of programme completion (<span class="math inline">\(OR: 35.73\)</span>, <span class="math inline">\(95\% CI [10.89, 149.2]\)</span> and <span class="math inline">\(37.23\)</span> <span class="math inline">\([5.2, 792.8]\)</span> respectively). Age and city were not found to significantly predict completion.</p>
<p>While the likelihood of completing the programme was not significantly associated with scores on the accountability measure, a relationship was found between self motivation and programme completion; a 1 standard deviation increase in self-motivation was associated with doubling the odds of finishing the entire 9-weeks (<span class="math inline">\(OR: 2.08\, [1.23, 3.7]\)</span>). The model-predicted probabilities of programme completion across values of the two psychometric measures are visualised in <a href="#fig-couchglm">Figure&nbsp;2</a>. Full table of results can be found in <a href="#tbl-couchglmcoef">Table&nbsp;3</a></p>
<p>The present study indicated that the psychometric factors of accountability and self motivation, taken together, were useful in predicting the completion (vs drop out) of the couch-to-5k programme. Specifically, a strong association was found between self-motivation and programme completion, with more motivated participants have a higher probability of finishing the full 9 weeks.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-couchglm" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="11_ex_files/figure-html/fig-couchglm-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Model estimated probability of completing the couch-to-5k programme across measures of accountability and self-motivation (both Z-scored)</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-couchglmcoef" class="anchored">

<div id="rhtvvkqulk" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#rhtvvkqulk table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#rhtvvkqulk thead, #rhtvvkqulk tbody, #rhtvvkqulk tfoot, #rhtvvkqulk tr, #rhtvvkqulk td, #rhtvvkqulk th {
  border-style: none;
}

#rhtvvkqulk p {
  margin: 0;
  padding: 0;
}

#rhtvvkqulk .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#rhtvvkqulk .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#rhtvvkqulk .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#rhtvvkqulk .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#rhtvvkqulk .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rhtvvkqulk .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rhtvvkqulk .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rhtvvkqulk .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#rhtvvkqulk .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#rhtvvkqulk .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#rhtvvkqulk .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#rhtvvkqulk .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#rhtvvkqulk .gt_spanner_row {
  border-bottom-style: hidden;
}

#rhtvvkqulk .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#rhtvvkqulk .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#rhtvvkqulk .gt_from_md > :first-child {
  margin-top: 0;
}

#rhtvvkqulk .gt_from_md > :last-child {
  margin-bottom: 0;
}

#rhtvvkqulk .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#rhtvvkqulk .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#rhtvvkqulk .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#rhtvvkqulk .gt_row_group_first td {
  border-top-width: 2px;
}

#rhtvvkqulk .gt_row_group_first th {
  border-top-width: 2px;
}

#rhtvvkqulk .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rhtvvkqulk .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#rhtvvkqulk .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#rhtvvkqulk .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rhtvvkqulk .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rhtvvkqulk .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#rhtvvkqulk .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#rhtvvkqulk .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#rhtvvkqulk .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rhtvvkqulk .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rhtvvkqulk .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rhtvvkqulk .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rhtvvkqulk .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rhtvvkqulk .gt_left {
  text-align: left;
}

#rhtvvkqulk .gt_center {
  text-align: center;
}

#rhtvvkqulk .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#rhtvvkqulk .gt_font_normal {
  font-weight: normal;
}

#rhtvvkqulk .gt_font_bold {
  font-weight: bold;
}

#rhtvvkqulk .gt_font_italic {
  font-style: italic;
}

#rhtvvkqulk .gt_super {
  font-size: 65%;
}

#rhtvvkqulk .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#rhtvvkqulk .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#rhtvvkqulk .gt_indent_1 {
  text-indent: 5px;
}

#rhtvvkqulk .gt_indent_2 {
  text-indent: 10px;
}

#rhtvvkqulk .gt_indent_3 {
  text-indent: 15px;
}

#rhtvvkqulk .gt_indent_4 {
  text-indent: 20px;
}

#rhtvvkqulk .gt_indent_5 {
  text-indent: 25px;
}

#rhtvvkqulk .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#rhtvvkqulk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"><caption>Table&nbsp;3:  <p>Couch-to-5k completion modeled using logistic regression. Table of
coefficients.</p> </caption>
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Predictors">Predictors</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Odds Ratios">Odds Ratios</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Predictors" class="gt_row gt_left">(Intercept)</td>
<td headers="Odds Ratios" class="gt_row gt_left">0.2 [0.03, 1.61]</td></tr>
    <tr><td headers="Predictors" class="gt_row gt_left">Season [Summer]</td>
<td headers="Odds Ratios" class="gt_row gt_left">35.7 [10.89, 149.2]</td></tr>
    <tr><td headers="Predictors" class="gt_row gt_left">Season [Autumn]</td>
<td headers="Odds Ratios" class="gt_row gt_left">37.2 [5.2, 792.8]</td></tr>
    <tr><td headers="Predictors" class="gt_row gt_left">Season [Winter]</td>
<td headers="Odds Ratios" class="gt_row gt_left">2.4x10^8 [0, Inf]</td></tr>
    <tr><td headers="Predictors" class="gt_row gt_left">Age (years)</td>
<td headers="Odds Ratios" class="gt_row gt_left">1 [0.96, 1.05]</td></tr>
    <tr><td headers="Predictors" class="gt_row gt_left">City [Glasgow]</td>
<td headers="Odds Ratios" class="gt_row gt_left">0.5 [0.12, 1.6]</td></tr>
    <tr><td headers="Predictors" class="gt_row gt_left">Accountability (Z-scored)</td>
<td headers="Odds Ratios" class="gt_row gt_left">0.9 [0.52, 1.56]</td></tr>
    <tr><td headers="Predictors" class="gt_row gt_left">Self-Motivation (Z-scored)</td>
<td headers="Odds Ratios" class="gt_row gt_left">2.1 [1.23, 3.7]</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<!-- # Development of Counterfactual Thinking -->
<!-- :::frame -->
<!-- __Kominsky.csv__   -->
<!-- Do young children struggle to answer the question "what would have happened?" Developmental researchers [Kominsky et al. (2021)](https://cicl.stanford.edu/papers/kominsky2021trajectory.pdf){target="_blank"} asked children between the ages of 5 and 10 to imagine counterfactual situations. Children were randomly assigned to one of the two conditions. They observed a video where Ball A hit Ball E and Ball E started to move. -->
<!-- :::: {.columns} -->
<!-- ::: {.column width="40%"} -->
<!-- __Singly-Determined__   -->
<!-- In the singly-determined condition, the brick wall altered Ball E’s trajectory such that it went into the goal. -->
<!-- ![](images/Brickcon2v2.gif) -->
<!-- ::: -->
<!-- ::: {.column width="10%"} -->
<!-- ::: -->
<!-- ::: {.column width="40%"} -->
<!-- __Over-Determined__   -->
<!-- In the over-determined condition, Ball E also deflects off the wall but would have gone into the goal regardless.  -->
<!-- ![](images/Brickdis2v2.gif) -->
<!-- ::: -->
<!-- :::: -->
<!-- The children were then asked: “What if the brick wall had not been there? Would Ball E have gone into the goal?” (“Yes” or “No”). -->
<!-- You can download a dataset of 120 children from [https://uoepsy.github.io/data/Kominsky.csv](https://uoepsy.github.io/data/Kominsky.csv){target="_blank"}.^[Note, data used here was modified, so it is different from the original dataset.]   -->
<!-- ```{r} -->
<!-- tibble( -->
<!--   variable = c("ID","Sex","Age","Condition","Accuracy"), -->
<!--   description = c("Unique ID number","Children's gender","Children's age","The video children watched: singly-determined vs. over-determined. In the singly-determined condition, the brick was the single cause that caused Ball E to go into the goal. In the over-determined condition, the brick was not the single cause because Ball E would have gone into the goal without it.","Whether children answered the question correctly (1) or no (0). The correct answer should be “no” for the singly-determined condition and should be “yes” for the over-determined condition") -->
<!-- ) %>% gt::gt() -->
<!-- ``` -->
<!-- Researchers were interested in children’s counterfactual thinking ability: How did children perform in the singly-determined vs. over-determined situations, and whether it differed between ages? -->
<!-- They managed to get the same number of children for the 5-6, 7-8, and 9-10 three age groups. Since the sample size was small and the range of ages was small, instead of using age (numeric) as a predictor, they used the age group (factors) as a predictor. -->
<!-- ::: -->


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>If we had reason to believe the variances are not equal, we can look at doing Welch’s t-test<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>