---
title: "invisible marshmallows"
author: "me!"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# packages and data ----
library(tidyverse)
#mallow2 <- read_csv("https://uoepsy.github.io/data/mallow2.csv")

# data cleaning here ----


# analysis here ----



```


**describe your data**  

- How many observations? 
  - Are there any observations that have been excluded based on pre-defined criteria? How many, and for what reason(s)?  
- Describe (and visualise if useful) the variables of interest. How are they scored? have they been transformed at all?  
- Describe/visualise initial relationships between variables.  

**describe your method**  

- what analysis was conducted?
  - using what variables? (measured on what scale?)  
  - is this conducted on the exact same data as described above, or on a subset? if a subset, explain how many were excluded and why.  

**present your results**

- what test/comparison is used to address the research question?  
  - if an F test, make sure to report $F(?, ?) = ?, p = ?$  
  - if a chi-square test, make sure to report $\chi^2(?) = ?, p = ?$  
  - if a t test, make sure to report the estimate and $t(?) = ?, p = ?$  
  - if a z test, make sure to report the estimate and $z = ?, p = ?$
  - if opting for confidence intervals, ensure to provide the estimate and 95% CI [lower, upper].
- are the assumptions and conditions of the test/model satisfied? (Hopefully yes, or there is more work to do...)
- provide an interpretation of the estimate(s) of interest. e.g. what goes up/down as what increases? remember to include the units of measurement.  
- what do your results suggest in relation to your research question/aims?
- provide plot(s) of the key result(s) of interest
- provide a table of results if applicable (i.e. a regression table)

