---
title: "8A: Centering and Scaling"
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
editor_options: 
  chunk_output_type: console
---



# centering/scaling/standardising

sticky centering
moving the location by subtracting some value. 
such as mean-centering
subtract the mean

sticky scaling/standardising
subtract the mean, divide by the standard deviation
what does it do - makes sd 1, mean 0

consider Martin. he goes on a lot about people's heights. he is 182cm tall. and he has size 43 feet (in EU sizes)
is his tallness more unusual than his feet?  


# centering predictors  

changes intercept
why? changes what "0" represents in our data  

# scaling predictors

changes intercept and changes slope
why?
changes what "0" represents
changes what "moving 1" represents (now represents moving 1 SD)

# standardised coefficients  

puts everythng on the same magnitude 
makes qualitative comparisons more easy  


notation


# packages

BE CAREFUL THOUGH

