---
title: "8C: Optional Extra: Good Controls and Bad Controls"
link-citations: yes
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
#| include: false
source('assets/setup.R')
library(xaringanExtra)
library(tidyverse)
library(patchwork)
xaringanExtra::use_panelset()
```

When you first learn about multiple regression and the idea of "controlling for ....", it's tempting to shove _EVERY_ variable that you have into your model. That way you've controlled for everything, right?  

Unfortunately, it just doesn't work like that.  

In this reading, we're going to have to start thinking about models in terms of drawings.  


```{r}
library(dagitty)
 
# in our example above, this was what we theorised:
g1 <- dagitty( "dag {
    Caff -> RHR
    Age -> Caff
    Age -> RHR
}")
plot(graphLayout(g1))

# if that is the case, we _do_ want to control for Age. If we don't control for Age, then all of the Age -> RHR relationship has to go via Age -> Caff -> RHR. 
# by including Age in the model, it opens the path from Age -> RHR, allowing Caff -> RHR to be estimated without the confounding effect of Age.  


# caffeine creates more cortisol receptors in the brain (result = fatigue)
# higher RHR causes fatigue (heart working harder)  
g1 <- dagitty( "dag {
    Caff -> RHR
    RHR -> Fatigue
    Caff -> Fatigue
}")
plot(graphLayout(g1))  
# we're still interested in Caff -> RHR
# if we control for Fatigue, then we open it up for some of the effect of Caffeine to RHR to go via Fatigue.  

fs <- function(){
  Caff = rnorm(100, 100, 30)
  RHR = 60 + 1*Caff + rnorm(100,0,3)
  Fatigue = .5*Caff + 2*RHR + rnorm(100, 0, 5)
  return(c(
    bXY.Z = coef(lm(RHR ~ Caff + Fatigue))[2],
    bXY = coef(lm(RHR ~ Caff))[2]
  )
  )
}

res = mcreplicate::mc_replicate(1e3, fs())
res = data.frame(t(res))
library(ggplot2)
ggplot(res)+
  geom_density(aes(x=bXY.Z.Caff),col="red")+
  geom_density(aes(x=bXY.Caff),col="darkolivegreen")

```


