project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!archive_2425/*"
  output-dir: ../docs/2526/labs2011211-2015-101519918-61518-1-16189265/

website:
  title: "USMR"
  navbar:
    background: primary
    search: true
    left: 
      - text: "Intro to R & Statistics"
        menu: 
          - 01_ex.qmd
      - text: "Linear Models"
      
format:
  html:
    toc: true
    toc_float: true
    code-annotations: hover
    link-citations: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


