---
title: "Welcome to USMR"
output: 
  bookdown::html_document2:
    toc: false
---


Welcome to the Univariate Statistics & Methodology in R (USMR) lab workbook. Using the menu above, you can find lab materials for each week. These include sets of exercises along with walkthrough readings in which we introduce some of the more important R code.  
 
#### Solutions   
Solutions will be made available immediately below each exercise, in the week *after* they are set, so make sure to re-visit the labs to check your answers.  
  
  
#### Asking Questions  
We encourage you to use the various support options below. Details of these are also available on the weekly pages on Blackboard Learn. 

+ **Lab Drop-in sessions.** We have an excellent team of tutors who are available at various slots throughout the week (all at different times of day). You can join a session and ask them anything about the exercises. 
+ **Discussion Forums.** There are weekly discussion forums for you to ask questions on any of the content from that week (or for you to share with other students any relevant materials you might have found useful). There are separate forums for questions concerning, for instance, course assessments, as well as a general forum for anything else. 
+ **Office Hours of Lecturers and STCs.** Lecturers and Senior Teaching Coordinators hold office hours every week. Feel free to drop in and ask any questions you might have about the materials, logistics of the course, or just come and say hi! You can also email the STCs at [pg.ppls.stats@ed.ac.uk](mailto:pg.ppls.stats@ed.ac.uk).  
