project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!temp/*"
    - "!07*"
    - "!08*"
    - "!09*"
    - "!10*"
    - "!11*"
    - "!12*"
    - "!13*"
    - "!14*"
    - "!15*"
    - "!16*"
  output-dir: ../docs/2526/readings/

website:
  title: "Linear Models"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - 01_R.qmd
      - 02_data.qmd
      - 03_measurement.qmd
      - 04_sampling.qmd
      - 05_inference.qmd
      - 06_inference2.qmd
      # - 07_chisq.qmd
      # - 08_revisitnhst.qmd
      # - 09_covcor.qmd
      # - 10_slr.qmd
      # - zz_wt.qmd
      # - 11_mlr.qmd
      # - 12_assumptdiag.qmd
      # - 13_scaling.qmd
      # - 14_catpred.qmd
      # - 15_interactions.qmd
      # - 16_glm.qmd

format:
  live-html:
    toc: true
    toc_float: true
    code-annotations: hover
    link-citations: true
    theme: 
      - united
      - assets/style-labs.scss
      - assets/active/_style.scss
      - assets/active/_webex.scss
    include-after-body: 
      - assets/active/_webex.js
      - assets/active/_displayall.js
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false
webr: 
  packages: ['learnr']


