project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!temp/*"
  output-dir: ../docs/2526/readings/

website:
  title: "Linear Models"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "Introductions"
        contents:
          - 01a_R.qmd
          - 01b_data.qmd
          - 02a_measurement.qmd
          - 02b_sampling.qmd
          - 03a_inference.qmd
          - 03b_inference2.qmd
          - 04a_chisq.qmd
          - 04b_revisitnhst.qmd
          - 05a_covcor.qmd
      - section: "Linear models"
        contents:
          - 05b_slr.qmd
          - 06_wt.qmd
          - 07a_mlr.qmd
          - 07b_assumptdiag.qmd
          - 08a_scaling.qmd
          - 08b_catpred.qmd
          - 09a_interactions.qmd
          - 10a_glm.qmd

format:
  live-html:
    toc: true
    toc_float: true
    code-annotations: hover
    link-citations: true
    theme: 
      - united
      - assets/style-labs.scss
      - assets/active/_style.scss
      - assets/active/_webex.scss
    include-after-body: 
      - assets/active/_webex.js
      - assets/active/_displayall.js
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


