<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11: Multiple Linear Regression – Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-97338aec0b8b6c6d6887a474ba26a80e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/live-runtime/live-runtime.js" type="module"></script>
<link href="site_libs/quarto-contrib/live-runtime/live-runtime.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

function toggle_visibility(id1, id2) {

var e = document.getElementById(id1);

var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('jk-circle-right')) {

    f.classList.add('jk-circle-down')

    f.classList.remove('jk-circle-right')

} else {

    f.classList.add('jk-circle-right')

    f.classList.remove('jk-circle-down')

}

}

</script>



<!---<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>-->

<script type="module" src="site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
<link href="site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">
<link href="site_libs/panelset-0.3.0/panelset.css" rel="stylesheet">

<script src="site_libs/panelset-0.3.0/panelset.js"></script>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./11_mlr.html">11: Multiple Linear Regression</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Linear Models</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1: A first look at R &amp; RStudio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2: More R - Basic Data Skills</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3: Measurement &amp; Distributions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4: Curves &amp; Sampling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5: Foundations of Inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_inference2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6: Practical Inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_chisq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7: Binomial &amp; Chi-Square Tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_revisitnhst.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8: Revisiting NHST</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_covcor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9: Covariance and Correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10: Simple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./zz_wt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">- WalkThrough: Advanced Data Wrangling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_mlr.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">11: Multiple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_assumptdiag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#variance-explained-in-simple-regression" id="toc-variance-explained-in-simple-regression" class="nav-link active" data-scroll-target="#variance-explained-in-simple-regression">Variance Explained in Simple Regression</a>
  <ul class="collapse">
  <li><a href="#r2-proportion-of-variance-explained" id="toc-r2-proportion-of-variance-explained" class="nav-link" data-scroll-target="#r2-proportion-of-variance-explained"><span class="math inline">\(R^2\)</span>: proportion of variance explained</a></li>
  <li><a href="#the-f-statistic" id="toc-the-f-statistic" class="nav-link" data-scroll-target="#the-f-statistic">The <span class="math inline">\(F\)</span> Statistic</a></li>
  </ul></li>
  <li><a href="#the-multiple-regression-model" id="toc-the-multiple-regression-model" class="nav-link" data-scroll-target="#the-multiple-regression-model">The Multiple Regression Model</a>
  <ul class="collapse">
  <li><a href="#fitting-multiple-regression-models-in-r" id="toc-fitting-multiple-regression-models-in-r" class="nav-link" data-scroll-target="#fitting-multiple-regression-models-in-r">Fitting Multiple Regression Models in R</a></li>
  </ul></li>
  <li><a href="#variance-explained-in-multiple-regression" id="toc-variance-explained-in-multiple-regression" class="nav-link" data-scroll-target="#variance-explained-in-multiple-regression">Variance Explained in Multiple Regression</a>
  <ul class="collapse">
  <li><a href="#the-adjusted-r2" id="toc-the-adjusted-r2" class="nav-link" data-scroll-target="#the-adjusted-r2">The Adjusted <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#the-f-statistic-a-joint-test" id="toc-the-f-statistic-a-joint-test" class="nav-link" data-scroll-target="#the-f-statistic-a-joint-test">The <span class="math inline">\(F\)</span>-statistic: a joint test</a></li>
  </ul></li>
  <li><a href="#model-comparisons" id="toc-model-comparisons" class="nav-link" data-scroll-target="#model-comparisons">Model Comparisons</a></li>
  <li><a href="#associations-in-multiple-regression" id="toc-associations-in-multiple-regression" class="nav-link" data-scroll-target="#associations-in-multiple-regression">Associations in multiple regression</a></li>
  <li><a href="#shortcuts-for-model-comparisons" id="toc-shortcuts-for-model-comparisons" class="nav-link" data-scroll-target="#shortcuts-for-model-comparisons">Shortcuts for model comparisons</a></li>
  <li><a href="#interpreting-multiple-regression-coefficients" id="toc-interpreting-multiple-regression-coefficients" class="nav-link" data-scroll-target="#interpreting-multiple-regression-coefficients">Interpreting Multiple Regression Coefficients</a></li>
  <li><a href="#model-visualisations" id="toc-model-visualisations" class="nav-link" data-scroll-target="#model-visualisations">Model Visualisations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">11: Multiple Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="lo">
<p>This reading:</p>
<ul>
<li>“Variance explained” in a linear model</li>
<li>Multiple regression: Building models where more than one thing explains variance</li>
<li>Comparing models</li>
<li>Associations in multiple regression</li>
</ul>
</div>
<p>When we introduced the linear regression model (see <a href="10_slr.html">Chapter 10</a>), we talked mainly about the intercept and the slope (collectively referred to as “the coefficients”). We saw that the model summary output (from <code>summary(model)</code>) gave us some tests next to each coefficient:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>slr_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_slr.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>simplemod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> slr_data)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simplemod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = slr_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.4383 -0.6593  0.1075  0.5945  2.1867 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.54277    0.32005   4.820 5.24e-06 ***
x            0.77952    0.09959   7.827 5.92e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9308 on 98 degrees of freedom
Multiple R-squared:  0.3847,    Adjusted R-squared:  0.3784 
F-statistic: 61.26 on 1 and 98 DF,  p-value: 5.918e-12</code></pre>
</div>
</div>
<p>However, there is another way we can look at our regression model, and that is by considering how the model, <em>as a whole</em>, explains variation in our outcome model.</p>
<section id="variance-explained-in-simple-regression" class="level1 page-columns page-full">
<h1>Variance Explained in Simple Regression</h1>
<p>To quantify and assess a model’s utility in explaining variance in an outcome variable, we can split the total variability of that outcome variable into two terms: the variability explained by the model plus the variability left unexplained in the residuals.</p>
<p><span class="math display">\[
\begin{align}
&amp; \qquad \qquad \qquad \qquad \text{total variability in outcome } =  \\
&amp; \text{variability explained by model } + \text{unexplained variability in residuals}
\end{align}
\]</span></p>
<p>The illustration in <a href="#fig-sstssrssm" class="quarto-xref">Figure&nbsp;1</a> gets at the intuition behind this: the top panel shows the total variability in the outcome variable <span class="math inline">\(y\)</span> - for each datapoint we see the distance from the mean of <span class="math inline">\(y\)</span>. These distances can be split into the bit from the mean to the model predicted value (seen in the bottom left panel of <a href="#fig-sstssrssm" class="quarto-xref">Figure&nbsp;1</a>), and the bit from that value to the actual value (bottom right panel).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sstssrssm" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sstssrssm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11_mlr_files/figure-html/fig-sstssrssm-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sstssrssm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Total Sums of Squares = Model Sums of Squares + Residual Sums of Squares
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each of these terms can be quantified as a ‘sum of squares’ (i.e.&nbsp;summing the squared differences). For the ‘total sums of squares’, this is the sum of squared differences from each observation to the mean. For the ‘model sums of squares’, this is the sum of the squared differences from each model-predicted value to the mean. For the ‘residual sums of squares’, it is the sum of the squared differences from each observation to the relative model-predicted value.</p>
<p><span class="math display">\[
\begin{aligned}
SS_{Total} &amp;= SS_{Model} \quad\quad + \quad SS_{Residual} \\
\sum_{i=1}^n (y_i - \bar y)^2 &amp;= \sum_{i=1}^n (\hat y_i - \bar y)^2 + \sum_{i=1}^n (y_i - \hat y_i)^2 \\
\quad \\
\text{Where:} \\
&amp; y_i = \text{observed value} \\
&amp;\bar{y} = \text{mean} \\
&amp; \hat{y}_i = \text{model predicted value} \\
\end{aligned}
\]</span></p>
<section id="r2-proportion-of-variance-explained" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="r2-proportion-of-variance-explained"><span class="math inline">\(R^2\)</span>: proportion of variance explained</h2>
<p>A useful statistic is the <span class="math inline">\(R^2\)</span>, which tell us the proportion of the total variability in the outcome (<code>y</code>) that is explained by the linear relationship with the predictor (<code>x</code>).</p>
<div class="sticky">
<p>The <span class="math inline">\(R^2\)</span> coefficient is defined as the proportion of the total variability in the outcome variable which is explained by our model:<br>
<span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
</div>
<p>We can find the <span class="math inline">\(R^2\)</span> easily in the <code>summary()</code> of the model!</p>
<p>The output of <code>summary()</code> displays the R-squared value in the following line:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simplemod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>...
...
Multiple R-squared:  0.3847,  Adjusted R-squared:  0.3784
...
</code></pre>

<div class="no-row-height column-margin column-container"><div class="">
<p>For the moment, ignore “Adjusted R-squared”. We will come back to this in a little bit.</p>
</div></div><div class="int">
<p>Approximately 38% of the total variability in <code>y</code> is explained by the linear association with <code>x</code>.</p>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: manual calculation of R-Squared
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>slr_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_slr.csv"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>simplemod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> slr_data)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>simplemod_fitted <span class="ot">&lt;-</span> slr_data <span class="sc">|&gt;</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y_hat =</span> <span class="fu">predict</span>(simplemod),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">resid =</span> y <span class="sc">-</span> y_hat</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(simplemod_fitted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
      x     y y_hat  resid
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1  3.19  4.42  4.03  0.388
2  2.57  4.48  3.54  0.941
3  3.91  2.72  4.59 -1.87 
4  4.79  5.39  5.28  0.107
5  4.00  3.85  4.66 -0.809
6  4.11  4.42  4.74 -0.327</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>simplemod_fitted <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">SSModel =</span> <span class="fu">sum</span>( (y_hat <span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">^</span><span class="dv">2</span> ),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">SSTotal =</span> <span class="fu">sum</span>( (y <span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">RSquared =</span> SSModel <span class="sc">/</span> SSTotal</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  RSquared
     &lt;dbl&gt;
1    0.385</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-f-statistic" class="level2">
<h2 class="anchored" data-anchor-id="the-f-statistic">The <span class="math inline">\(F\)</span> Statistic</h2>
<p>We can also perform a test to investigate if the model is ‘useful’ — that is, a test to see if our explanatory variable explains more variance in our outcome than we would expect by just some random chance variable.</p>
<p>Our test is framed in terms of the following hypotheses:</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: \text{the model is ineffective, } b_1 = 0 \\
H_1 &amp;: \text{the model is effective, } b_1 \neq 0
\end{aligned}
\]</span> The relevant test-statistic is the F-statistic, which uses “Mean Squares” (these are Sums of Squares divided by the relevant degrees of freedom). We then compare that against (you guessed it) an F-distribution! F-distributions vary according to two parameters, which are both degrees of freedom.</p>
<p>We won’t go into details of why we use <span class="math inline">\(F\)</span>, but the logic of the significance test is just the same as it was for <span class="math inline">\(z\)</span>, <span class="math inline">\(t\)</span> and <span class="math inline">\(\chi^2\)</span>:</p>
<ul>
<li>we calculate a test statistic</li>
<li>we have a distribution of what we would expect test statistics from a sample of this size to be, if the null hypothesis is true (the “null distribution”).</li>
<li>we can then ask how unlikely it is that we would observe our statistic (or more extreme) if the null hypothesis were true.</li>
</ul>
<div class="sticky">
<p><strong><span class="math inline">\(F\)</span>-statistic for simple linear regression</strong></p>
<p><span class="math display">\[
\begin{split}
F = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model} / 1}{SS_{Residual} / (n-2)}
\end{split}
\]</span></p>
<p>This is a comparison between amount of variation in the outcome explained by the model and the amount of variation ‘explained by’ (or leftover in) the residuals.</p>
<p>The sample F-statistic is compared to an F-distribution with <span class="math inline">\(df_{1} = 1\)</span> and <span class="math inline">\(df_{2} = n - 2\)</span> degrees of freedom.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</div>
<p>Like the R-squared, the <code>summary()</code> of our model prints out the F-statistic, degrees of freedom, and p-value. These are right at the bottom of the summary output, printed as:</p>
<pre><code>...

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.54277    0.32005   4.820 5.24e-06 ***
x            0.77952    0.09959   7.827 5.92e-12 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.9308 on 98 degrees of freedom
Multiple R-squared:  0.3847,    Adjusted R-squared:  0.3784 
F-statistic: 61.26 on 1 and 98 DF,  p-value: 5.918e-12</code></pre>
<div class="int">
<p>The F-test of model utility was significant (<span class="math inline">\(R^2=0.38, F(1,98) = 61.26,\ p &lt;.001\)</span>), suggesting that predictor <span class="math inline">\(x\)</span> is effective in explaining variance in the outcome.</p>
</div>
<p>Note that the p-value here is exactly the same as the one for the coefficient. This is because in testing “the model is (in)effective”, the “model” is really <em>only</em> the relationship between the outcome and our <strong>one</strong> predictor. We’re about to start adding more explanatory variables into our model, which means that our hypotheses for the <span class="math inline">\(F\)</span>-test will be about a <em>set</em> of <span class="math inline">\(b\)</span>’s, and so the tests will be of different things.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: with only one predictor variable, the F-test is equivalent to the t-test of the slope
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>In simple linear regression only</strong> (where we have just <strong>one</strong> predictor), the F-statistic for overall model significance is equal to the square of the t-statistic for <span class="math inline">\(H_0: b_1 = 0\)</span>.</p>
<p>You can check that the squared t-statistic is equal, up to rounding error, to the F-statistic:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>slr_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_slr.csv"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>simplemod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> slr_data)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simplemod)<span class="sc">$</span>fstatistic[<span class="st">'value'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   value 
61.26497 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simplemod)<span class="sc">$</span>coefficients[<span class="st">'x'</span>,<span class="st">'t value'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.827194</code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{align}
&amp; t^2 = F \\
&amp; 7.827194^2 = 61.26497
\end{align}
\]</span></p>
<p>We can also show the equivalence of the F-test for model effectiveness and t-test for the slope through their respecive formulae.</p>
<p>Recall the formula of the sum of squares due to the model. We are going to re-express this in an equivalent form below: <span class="math display">\[
\begin{aligned}
SS_{Model} &amp;= \sum_i (\hat y_i - \bar y)^2 \\
&amp;= \sum_i (\hat b_0 + \hat b_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\bar y - \hat b_1 \bar x + \hat b_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\hat b_1 (x_i - \bar x))^2 \\
&amp;= \hat b_1^2 \sum_i (x_i - \bar x)^2
\end{aligned}
\]</span></p>
<p>The F-statistic is given by: <span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)}
= \frac{\hat b_1^2 \sum_i (x_i - \bar x)^2}{\hat \sigma^2}
= \frac{\hat b_1^2 }{\hat \sigma^2 / \sum_i (x_i - \bar x)^2}
\end{aligned}
\]</span></p>
<p>Now recall the formula of the t-statistic, <span class="math display">\[
t = \frac{\hat b_1}{SE(\hat b_1)} = \frac{\hat b_1}{\hat \sigma / \sqrt{\sum_i (x_i - \bar x)^2}}
\]</span></p>
<p>It is evident that the latter is obtained as the square root of the former.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: expressing <span class="math inline">\(F\)</span> in terms of <span class="math inline">\(R^2\)</span>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>With some algebra we can also show that: <span class="math display">\[
F = \frac{R^2 / 1}{(1 - R^2) / (n - 2) } = \frac{R^2 / df_{Model}}{(1 - R^2) / df_{Residual} }
\]</span></p>
<p>Proof:</p>
<p><span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)}
= \frac{\frac{SS_{Model}}{SS_{Total}}}{\frac{SS_{Residual}}{SS_{Total}} \cdot \frac{1}{(n - 2)}}
= \frac{R^2 / 1}{(1 - R^2) / (n - 2)}
\end{aligned}
\]</span></p>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
</section>
<section id="the-multiple-regression-model" class="level1">
<h1>The Multiple Regression Model</h1>
<p>The real power of regression models comes into effect when we start to concern ourselves with more than just “one outcome explained by one predictor”.</p>
<p>Enter… <span class="math inline">\(x_2\)</span>!</p>
<p>We’re going to start with looking at the case of “one outcome, two predictors”, but the beauty of this is that the logic scales up to however many predictor variables we want to include in our model.</p>
<p>When we fitted the simple regression model with <strong>one</strong> predictor: <span class="math display">\[
y = b_0 + b_1 \cdot x + \epsilon
\]</span> we were fitting a <em>line</em> to a scatterplot of points that we plotted in <em>2 dimensions</em> (an x-axis and a y-axis).</p>
<p>When we fit a multiple regression model with <strong>two</strong> predictors:<br>
<span class="math display">\[
y = b_0 + b_1 \cdot x_1 + b_2 \cdot x_2 + \epsilon
\]</span> we are fitting a <strong>surface</strong> (or “plane”) to a 3-dimensional cloud of datapoints (<a href="#fig-regsurf" class="quarto-xref">Figure&nbsp;2</a>). There are three dimensions: x1, x2, and y.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-regsurf" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regsurf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11_mlr_files/figure-html/fig-regsurf-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regsurf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Regression surface for y~x1+x2, from two different angles
</figcaption>
</figure>
</div>
</div>
</div>
<p>Don’t worry about trying to figure out how to visualise it if we had more predictors! We can only conceive of 3 spatial dimensions.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> However, the logic stays the same when we increase this to having <span class="math inline">\(k\)</span> predictors, but we have a model that is a <span class="math inline">\(k\)</span>-dimensional surface, and each coefficient is the angle of that surface with respect to each predictor.</p>
<p>When we have two predictors, such as in the visualisation of <a href="#fig-regsurf" class="quarto-xref">Figure&nbsp;2</a>, our model is now determined by three numbers:</p>
<ul>
<li>the <strong>intercept</strong>, denoted <span class="math inline">\(b_0\)</span>.<br>
This is the point at which the plane hits the y-axis (i.e.&nbsp;where <span class="math inline">\(x_1=0\)</span> <strong>and</strong> <span class="math inline">\(x_2=0\)</span>)</li>
<li>the <strong>slope of x1</strong>, in this case denoted <span class="math inline">\(b_1\)</span>.<br>
This is the angle of the regression plane with respect to the axis of <span class="math inline">\(x_1\)</span>. It is the amount which the plane increases for every 1 increase in <span class="math inline">\(x_1\)</span>.<br>
</li>
<li>the <strong>slope of x2</strong>, in this case denoted <span class="math inline">\(b_2\)</span>.<br>
This is the angle of the regression plane with respect to the axis of <span class="math inline">\(x_2\)</span>. It is the amount which the plane increases for every 1 increase in <span class="math inline">\(x_2\)</span>.</li>
</ul>
<section id="fitting-multiple-regression-models-in-r" class="level2">
<h2 class="anchored" data-anchor-id="fitting-multiple-regression-models-in-r">Fitting Multiple Regression Models in R</h2>
<p>As we did for simple linear regression, we can fit our multiple regression model using the <code>lm()</code> function. We can add as many explanatory variables as we like, separating them with a <code>+</code>.</p>
<pre><code>model_name &lt;- lm(y ~ 1 + x1 + x2 + ... + xk, data = dataframe)</code></pre>
<p>And we can use all the same functions that we have already seen such as <code>summary()</code>, <code>predict()</code>, <code>fitted()</code>, <code>coef()</code> etc.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mlr_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_mlr.csv"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mlr_data)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2, data = mlr_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.5201  -4.2912  -0.0268   3.3044  16.2154 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -2.39138    3.67735  -0.650  0.51867   
x1           0.17570    0.06435   2.730  0.00888 **
x2          -0.64756    0.19959  -3.244  0.00217 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.069 on 47 degrees of freedom
Multiple R-squared:  0.2643,    Adjusted R-squared:  0.233 
F-statistic: 8.443 on 2 and 47 DF,  p-value: 0.0007369</code></pre>
</div>
</div>
<p>Just like we saw for the regression model with one predictor, the <code>summary()</code> output of a multiple regression model shows us all the same information: residuals, coefficients, <span class="math inline">\(R^2\)</span> and and <span class="math inline">\(F\)</span>-test. We’ll get to the coefficients a little later on, but first we’re going to take a look at the overall model in terms of how much variance is now explained.</p>
<div class="divider div-transparent div-dot">

</div>
</section>
</section>
<section id="variance-explained-in-multiple-regression" class="level1">
<h1>Variance Explained in Multiple Regression</h1>
<section id="the-adjusted-r2" class="level2">
<h2 class="anchored" data-anchor-id="the-adjusted-r2">The Adjusted <span class="math inline">\(R^2\)</span></h2>
<p>We know from above that in simple linear regression the R-squared can be obtained as: <span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
<p>In multiple regression, the “multiple <span class="math inline">\(R^2\)</span>” uses this exact same formula. However, when we add more and more predictors into a multiple regression model, <span class="math inline">\(SS_{Residual}\)</span> <em>cannot</em> increase. In fact, it will <em>always</em> decrease, regardless of how useful our new predictors are. This means that <span class="math inline">\(R^2\)</span> will <em>always increase</em> (because <span class="math inline">\(SS_{Total}\)</span> is constant, so <span class="math inline">\(1-\frac{SS_{Residual}}{SS_{Total}}\)</span> will increase as <span class="math inline">\(SS_{Residual}\)</span> decreases).</p>
<p>If we added randomly generated 1000 new predictors (completely random, so they have nothing to do with the outcome), then by chance alone they will explain <em>some</em> variance in the outcome <span class="math inline">\(y\)</span>, and the multiple <span class="math inline">\(R^2\)</span> will always increase.</p>
<p>An alternative, the “Adjusted-<span class="math inline">\(R^2\)</span>”, does not necessarily increase with the addition of more explanatory variables, by the inclusion of a penalty according to the number of explanatory variables in the model. The number by itself isn’t directly meaningful, but can be useful in determining the amount of additional variance explained by adding predictor(s) into a model.</p>
<div class="sticky">
<p>The <strong>Adjusted</strong> <span class="math inline">\(R^2\)</span> is a measure of the proportion of variability in the outcome that is explained by our model, <em>adjusted for the number of predictors in the model.</em></p>
<p><span class="math display">\[
\begin{align}
&amp; Adjusted{-}R^2=1-\frac{(1-R^2)(n-1)}{n-k-1} \\
&amp; \quad \\
&amp; \text{Where:} \\
&amp; n = \text{sample size} \\
&amp; k = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
</div>
<p><strong>In R,</strong> we can view both the mutiple and adjusted <span class="math inline">\(R^2\)</span> at the bottom of the output of <code>summary()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mlr_data)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/mlr/output_mlr_rsq.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-f-statistic-a-joint-test" class="level2">
<h2 class="anchored" data-anchor-id="the-f-statistic-a-joint-test">The <span class="math inline">\(F\)</span>-statistic: a joint test</h2>
<p>We saw just above that with one predictor, the F-statistic is used to test the null hypothesis that the regression slope for that predictor is zero. In multiple regression, the logic is the same, but we are now testing against the null hypothesis that <strong>all</strong> regression slopes are zero (now that we have multiple predictors, “all” is more than 1).</p>
<p><span class="math display">\[
\begin{aligned}
H_0: &amp; \text{the model is ineffective, } \\
&amp; b_1, ..., b_k = 0 \\
H_1: &amp;\text{the model is effective, } \\
&amp; \text{any of }b_1, ..., b_k \neq 0
\end{aligned}
\]</span></p>
<p>The <span class="math inline">\(F\)</span>-statistic is sometimes called the <span class="math inline">\(F\)</span>-ratio because it is the ratio of the how much of the variation is explained by the model (per parameter) versus how much of the variation is unexplained (per remaining degrees of freedom). We can generalise the formula for the <span class="math inline">\(F\)</span>-statistic in simple regression that we saw above, to encompass situations where there are more predictors:</p>
<div class="sticky">
<p><strong><span class="math inline">\(F\)</span>-ratio</strong></p>
<p><span class="math display">\[
\begin{align}
&amp; F_{df_{model},df_{residual}} = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model}/df_{Model}}{SS_{Residual}/df_{Residual}} \\
&amp; \quad \\
&amp; \text{Where:} \\
&amp; df_{model} = k \\
&amp; df_{residual} = n-k-1 \\
&amp; n = \text{sample size} \\
&amp; k  = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
</div>
<p><strong>In R,</strong> at the bottom of the output of <code>summary()</code>, you can view the F statistic, along with the hypothesis test against the null hypothesis that all the coefficients are 0:<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mlr_data)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/mlr/output_mlr_f.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="int">
<p>the linear model with <span class="math inline">\(x1\)</span> and <span class="math inline">\(x2\)</span> explained a significant amount of variance in <span class="math inline">\(y\)</span> beyond what we would expect by chance (<span class="math inline">\(R^2=0.26, F(2, 47) = 8.44,\ p &lt;.001\)</span>).</p>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
</section>
<section id="model-comparisons" class="level1">
<h1>Model Comparisons</h1>
<p>Now we have seen that we can add in more predictors to a linear regression model, what are we going to <em>do</em> with our modelling? Well, one useful thing we can do is to compare models with and without some predictor(s).</p>
<p>An easy starting point would be to compare how the <span class="math inline">\(R^2\)</span> values change when we add predictors - showing the extent to which different models ‘explain variance’ in our outcome. The two models below explain 10% and 26%, respectively, of the variance in y.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1, <span class="at">data =</span> mlr_data)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mlr_data)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09953216</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2643057</code></pre>
</div>
</div>
<p>But this comparison is <em>descriptive</em>, in that we are not performing any <em>test</em> of whether the differences between the models’ explanatory power is more than we might just expect by chance. To do this, we need to utilise our <span class="math inline">\(F\)</span>-tests again!</p>
<p>As it happens, the <span class="math inline">\(F\)</span>-statistic we see at the bottom of <code>summary(model)</code> is actually a comparison between two models: our model (with some explanatory variables in predicting <span class="math inline">\(y\)</span>) and <strong>the null model.</strong></p>
<div class="sticky">
<p><strong>the null model / “intercept-only model”</strong></p>
<p>The null model can be thought of as the model in which all explanatory variables have zero regression coefficients. Put another way, when all predictor variable coefficients are zero, then we are only estimating <span class="math inline">\(y\)</span> via an intercept (which will be the mean: <span class="math inline">\(\bar y\)</span>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>nullmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mlrdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>We aren’t limited to comparing our model to the null model. We can compare any the intermediate models which vary in the complexity, from the null model to our full model.</p>
<p>If (<em>and only if</em>) two models are <strong>nested</strong> (one model contains all the predictors of the other and is fitted to the same data), we can compare them using an <em>incremental F-test.</em> This is a formal test of whether the <strong>additional predictors</strong> provide a better fitting model. “Better fitting” here refers to a reduction in the residual sums of squares, hence why this is just another form of the <span class="math inline">\(F\)</span>-ratio we’ve seen above.</p>
<div class="sticky">
<p><strong>Incremental F-test</strong></p>
<ul>
<li><span class="math inline">\(H_0:\)</span> coefficients for the added/ommitted variables are all zero.</li>
<li><span class="math inline">\(H_1:\)</span> at least one of the added/ommitted variables has a coefficient that is not zero.</li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: F-ratio written for model comparison
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The F-ratio for comparing the residual sums of squares between two models can be written as:</p>
<p><span class="math display">\[
\begin{align}
&amp; F_{(df_R-df_F),df_F} = \frac{(SSR_R-SSR_F)/(df_R-df_F)}{SSR_F / df_F} \\
&amp; \quad \\
&amp; \text{Where:} \\
&amp; SSR_R = \text{residual sums of squares for the restricted model} \\
&amp; SSR_F = \text{residual sums of squares for the full model} \\
&amp; df_R = \text{residual degrees of freedom from the restricted model} \\
&amp; df_F = \text{residual degrees of freedom from the full model} \\
\end{align}
\]</span></p>
</div>
</div>
</div>
</div>
<p><strong>In R,</strong> we can conduct an incremental F-test to compare two models by fitting both models using <code>lm()</code>, and passing them to the <code>anova()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( ... )</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>( ... )</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1, model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<!-- ::: {.callout-caution collapse="true"} -->
<!-- #### why 'anova' -->
<!-- What we are actually doing when we conduct a model comparison is asking "is there a reduction in residual sums of squares?".^[The residuals are, remember, the distances from the actual observed values to the model predicted values. If we square those distances (to make them all positive), and sum them up, we get the "residual sums of squares".]   -->
<!-- Another way of phrasing "is there are reduction in residual sums of squares?" is to say "is more variance explained?". The `anova()` function stands for "analysis of variance".   -->
<!-- ::: -->
<p>If we wanted to, for example, compare a model with just one predictor, <span class="math inline">\(x_1\)</span>, to a model with 3 predictors: <span class="math inline">\(x_1,\ x_2,\ x_3\)</span>, we can assess the extent to which the variables <span class="math inline">\(x_2\)</span> and <span class="math inline">\(x_3\)</span> <em>jointly</em> improve model fit by explaining more variance (i.e.&nbsp;by reducing the residual sums of squares):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1, <span class="at">data =</span> mlr_data)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3, <span class="at">data =</span> mlr_data)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1, model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: y ~ x1
Model 2: y ~ x1 + x2 + x3
  Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)  
1     48 2874.8                              
2     45 2294.3  3    580.55 3.7956 0.01648 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="int">
<p><span class="math inline">\(x2\)</span> and <span class="math inline">\(x3\)</span> explained a significant amount of additional variance in <span class="math inline">\(y\)</span> beyond <span class="math inline">\(x1\)</span> (<span class="math inline">\(F(3,45) = 3.8,\ p =.017\)</span>).</p>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="associations-in-multiple-regression" class="level1">
<h1>Associations in multiple regression</h1>
<p>Okay, so we can build multiple regression models, adding in as many predictors as we like, and we can compare models with and without certain predictors. But <strong>why</strong> is this a useful thing that we may want to do?</p>
<p>One important reason is that it allows us to exercise <em>statistical control</em>. We often conduct research where we are interested mainly in one relationship, but we know that there are other things also at play - there are other variables that will probably strongly influence results if they aren’t held constant.</p>
<p>Statistical control allows us to examine the relationship of interest <em>after accounting for variance explained by other predictors.</em> Including additional predictors also often has the benefit of improving the predictive accuracy of our model (although this is not often the primary goal in Psychological studies, which are less concerned with ‘the best fitting model’ and more geared towards understanding and estimating the relevant relationship while exercising appropriate control).</p>
<p>Multiple regression allows to do this because when we have multiple predictor variables in our model, we can examine the association between the outcome <span class="math inline">\(y\)</span> and <strong>the bit of our focal predictor variable that is unique from the other predictors</strong> (i.e.&nbsp;“after accounting for” those other predictors).</p>
<p>For example, suppose we are interested in the relationship between ‘commuting time’ and ‘job satisfaction’ (e.g.&nbsp;people might be more/less satisfied with jobs depending upon the distance of their commute). In this scenario, we are looking at whether our outcome (job satisfaction) varies according to a focal predictor (the distance of commute). <em>But,</em> it’s extremely likely that people with more flexible working patterns will tend to have longer commutes (they will spend more time at home, and so be more prepared to travel further on the days they <em>do</em> go in). And this flexible working has other features that will influence job satisfaction. So we need to make it clear that we are interested in the bit of ‘commuting time’ that is <em>separate from</em> ‘work flexibility’ - we want to <em>control for</em> work flexibility.</p>
<div class="statbox">
<p><strong>Terminology</strong></p>
<p>As with all areas of statistics, people seem to use lots of different terms here. It can be confusing!</p>
<ul>
<li><strong>outcome/response/dependent variable</strong>: variable on the left hand side of the model equation <em>(thing that varies and we’re trying to explain how/why)</em></li>
<li><strong>predictor:</strong> any variable on the right hand side of the model equation <em>(things that we thing explain differences in the outcome)</em></li>
<li><strong>focal predictor/independent variable:</strong> the predictor of interest</li>
<li><strong>covariates/confounders/control variables:</strong> other variables that we are less interested in but believe to be relevant to how the data comes about, and that may influence both the outcome and the focal predictor.<br>
</li>
</ul>
</div>
<p>One way to build this intuition is to consider a Venn diagram with a circle showing the variance in each variable. <a href="#fig-vennslr" class="quarto-xref">Figure&nbsp;3</a> shows a simple linear regression with one predictor (i.e.&nbsp;<code>lm(y ~ x1)</code>). The circle for <span class="math inline">\(y\)</span> shows the total variance in <span class="math inline">\(y\)</span> (the same for the <span class="math inline">\(x_1\)</span> circle). The overlap between circles (labelled “A”) shows the variance in <span class="math inline">\(y\)</span> that is explained by <span class="math inline">\(x_1\)</span> (i.e.&nbsp;the covariance).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-vennslr" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-vennslr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlr/venn_slr.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-vennslr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Venn Diagram for Simple Regression y ~ x1
</figcaption>
</figure>
</div>
</div>
</div>
<p>When we add in a new predictor, <span class="math inline">\(x_2\)</span>, where do we add it? If <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> are <em>completely</em> uncorrelated with one another, then it would look something like <a href="#fig-vennmlr1" class="quarto-xref">Figure&nbsp;4</a>, where there is no overlap between the <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> circles. The total variance explained in <span class="math inline">\(y\)</span> by both predictors is <span class="math inline">\(A + B\)</span>, and in this case, nothing changes in our estimate of the relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x_1\)</span>. It’s just the same as before (the area labelled “A” is the same in both <a href="#fig-vennslr" class="quarto-xref">Figure&nbsp;3</a> and <a href="#fig-vennmlr1" class="quarto-xref">Figure&nbsp;4</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-vennmlr1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-vennmlr1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlr/venn_mlr1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-vennmlr1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Venn Diagram for Multiple Regression y ~ x1 + x2 where x1 and x2 are completely uncorrelated
</figcaption>
</figure>
</div>
</div>
</div>
<p>However, in practice the predictors in our regression model are likely to overlap a bit (it’s hard to make sure our focal predictor is completely unrelated to other predictors). In this case, our Venn diagram is going to look like <a href="#fig-vennmlr2" class="quarto-xref">Figure&nbsp;5</a>. The correlation between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> is shown by the overlap of those two circles (the area <span class="math inline">\(C + D\)</span> in the diagram). The total variance explained in <span class="math inline">\(y\)</span> is now separated into the areas <span class="math inline">\(A + B + C\)</span> (and <span class="math inline">\(E\)</span> is the <em>unexplained</em> variance - the residuals).</p>
<p>Areas <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are no longer the same as in the previous diagrams - there’s a little bit (area <span class="math inline">\(C\)</span>) that we don’t want to double count in its explanatory power as it can’t be attributable to specifically one variable or the other.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-vennmlr2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-vennmlr2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlr/venn_mlr2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-vennmlr2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Venn Diagram for Multiple Regression y ~ x1 + x2 where x1 and x2 are somewhat correlated
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><span class="math inline">\(A\)</span> is the variance in <span class="math inline">\(y\)</span> <em>uniquely</em> explained by <span class="math inline">\(x_1\)</span><br>
</li>
<li><span class="math inline">\(B\)</span> is the variance in <span class="math inline">\(y\)</span> <em>uniquely</em> explained by <span class="math inline">\(x_2\)</span></li>
<li><span class="math inline">\(C\)</span> is the variance in <span class="math inline">\(y\)</span> that is explained by both <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> but not attributable to either one uniquely.</li>
</ul>
<p>We can map the model comparisons we talked about above to this diagram too. The model comparison below would allow us to ask whether the area <span class="math inline">\(B\)</span> is explaining a significant amount of <span class="math inline">\(y\)</span> (excluding the area <span class="math inline">\(A+C\)</span>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1, <span class="at">data =</span> mlr_data)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mlr_data)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1, model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Happy Commuters
</div>
</div>
<div class="callout-body-container callout-body">
<p>We have a sample of 100 people who all completed a questionnaire that has given us measures of their job satisfaction (range 5-35, higher scores indicate more satisfaction), their average commuting time (in minutes), their work flexibility (range 5-35, with higher scores indicating more flexibility in working patterns).</p>
<p>We’re interested in estimating how length of commute is associated with differences in job satisfaction. However, we also have reason to believe that job satisfaction differs depending upon how flexible the working patterns are <em>and</em> that people on more flexible contracts tend to have longer commutes. So we want to isolate the differences in job satisfaction due to commuting from those due to work flexbility.</p>
<p>The toy dataset for our happy commuters example is at <a href="https://uoepsy.github.io/data/happycommute.csv">https://uoepsy.github.io/data/happycommute.csv</a>. We can see plots of the different relationships in <a href="#fig-commuteplot" class="quarto-xref">Figure&nbsp;6</a>. It looks from these like job satisfaction <em>increases</em> with longer commuting time, and also <em>increases</em> with more work flexibility. Note also that commuting time increases with more work flexibility.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>happycommute <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/happycommute.csv"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(happycommute, <span class="fu">aes</span>(<span class="at">x=</span>commute,<span class="at">y=</span>jobsat))<span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Commuting Time (minutes)"</span>,<span class="at">y=</span><span class="st">"Job Satisfaction"</span>) <span class="sc">+</span> </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(happycommute, <span class="fu">aes</span>(<span class="at">x=</span>work_flex,<span class="at">y=</span>jobsat))<span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Work Flexibility Rating"</span>,<span class="at">y=</span><span class="st">"Job Satisfaction"</span>) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(happycommute, <span class="fu">aes</span>(<span class="at">x=</span>work_flex,<span class="at">y=</span>commute))<span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Work Flexibility Rating"</span>,<span class="at">y=</span><span class="st">"Commuting Time (minutes)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-commuteplot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-commuteplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11_mlr_files/figure-html/fig-commuteplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-commuteplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: bi-variate relationships between each of Job Satisfaction, Commuting Time and Work Flexibility
</figcaption>
</figure>
</div>
</div>
</div>
<p>If we fit a simple regression <span class="math inline">\(JobSat \sim b_0 + b_1(CommuteTime)\)</span>, we get a nice line, and our model is significant. The coefficient is positive suggesting to us that people who commute for longer are more satisfied with their jobs. Good news for me, it takes me 2 hours to get into work!</p>
<div class="panelset">
<section id="plot" class="level4 panel">
<h4 class="anchored" data-anchor-id="plot">Plot</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(happycommute, <span class="fu">aes</span>(<span class="at">x=</span>commute,<span class="at">y=</span>jobsat))<span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm)<span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Commuting Time (minutes)"</span>,<span class="at">y=</span><span class="st">"Job Satisfaction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_mlr_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-summary" class="level4 panel">
<h4 class="anchored" data-anchor-id="model-summary">Model summary</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(jobsat <span class="sc">~</span> commute, <span class="at">data =</span> happycommute) <span class="sc">|&gt;</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = jobsat ~ commute, data = happycommute)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.2759  -2.6475   0.0467   2.9659   9.4927 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  9.11847    1.29422   7.046 2.59e-10 ***
commute      0.24794    0.03425   7.240 1.02e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.247 on 98 degrees of freedom
Multiple R-squared:  0.3485,    Adjusted R-squared:  0.3418 
F-statistic: 52.42 on 1 and 98 DF,  p-value: 1.02e-10</code></pre>
</div>
</div>
</section>
</div>
<p><br> But… what if the reason that we are seeing “more commuting &gt;&gt; more job satisfaction” is <em>not</em> because long commutes are enjoyable, but because the people who have longer commutes are those who tend to be in more flexible working patterns (and so are more satisfied in their work for a myriad of other reasons)?</p>
<p>When we compare two models, one with job satisfaction predicted by work flexibility, and one with job satisfaction predicted by both work flexibility <em>and</em> commuting time, we now conclude that commuting time is <strong>not</strong> a useful predictor..</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>jobmodel1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(jobsat <span class="sc">~</span> work_flex, <span class="at">data =</span> happycommute)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>jobmodel2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(jobsat <span class="sc">~</span> work_flex <span class="sc">+</span> commute, <span class="at">data =</span> happycommute)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(jobmodel1, jobmodel2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: jobsat ~ work_flex
Model 2: jobsat ~ work_flex + commute
  Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)  
1     98 336.77                              
2     97 325.30  1    11.472 3.4209 0.06742 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Why? Because after we take into account how flexible peoples’ work is, knowing their commuting time doesn’t actually provide any new information about their job satisfaction.</p>
<p>If it helps, we might think of this model as the diagram in <a href="#fig-venncommute" class="quarto-xref">Figure&nbsp;7</a>. When we don’t have <code>work flexibility</code> in our model, then the estimated association between <code>commuting time</code> and <code>job satisfaction</code> is the areas <span class="math inline">\(B + C\)</span>. When we <em>do</em> have <code>work flexibility</code> in the model, the <em>additional</em> variance in <code>job satisfaction</code> explained <em>uniquely</em> by <code>commuting time</code> is just the tiny area <span class="math inline">\(B\)</span> (not a useful amount).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-venncommute" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-venncommute-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlr/venn_commute.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-venncommute-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: lm(jobsat ~ work_flex + commute)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="frame">
<p>This example is a very extreme one where the relationship completely disappears. in real data associations tend to be more subtle/less clear cut. Including <span class="math inline">\(x_2\)</span> may increase or decrease the association between <span class="math inline">\(y\)</span> and <span class="math inline">\(x_1\)</span>, depending on the extent to which <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> are correlated.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: control on the front-end
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If we haven’t collected the data yet, one good option is to <strong>control by design</strong>. This would involve trying to collect our data such that the predictor of interest is <em>independent</em> from other possibly confounding variables.</p>
<p>We could do this by <strong>randomisation</strong>, where we randomly allocate people to different levels of our focal predictor, meaning that other variables will not be related to the focal predictor. This is what a “randomized control trial” does, randomly allocating people to take drug X or a placebo means that the two groups should be similar in aspects such as age.</p>
<p>Alternatively, we could do achieve it by <strong>“case-matching”</strong>. This involves finding people at different levels of the focal predictor who match on possible confounders. For example, for every 60 year who takes drug X, we also collect data from a 60 year old who does not.</p>
<p>There are lots of different types of study design, and it is not something to be rushed through. Careful design can make for great science, and clever statistics cannot save a poorly designed study!</p>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="shortcuts-for-model-comparisons" class="level1">
<h1>Shortcuts for model comparisons</h1>
<p><a href="#model-comparisons">Above</a> we saw that we can compare two models by testing the reduction in residual sums of squares. To do this, we fitted each model and then gave both those models to the <code>anova()</code> function.</p>
<p>There are some shortcuts that will sometimes save us time, as they don’t involve fitting more than the one model.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Comparisons incrementally adding each predictor
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>Using the order in which predictors are entered into our model</em>, we can set up a series of models that incrementally add each next predictor.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mlr_data)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1, <span class="at">data =</span> mlr_data)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mlr_data)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3, <span class="at">data =</span> mlr_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can then easily compare them by giving them <em>all</em> to the <code>anova()</code> function (which can take as many models as we want to give it).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model0, model1, model2, model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: y ~ 1
Model 2: y ~ 1 + x1
Model 3: y ~ 1 + x1 + x2
Model 4: y ~ 1 + x1 + x2 + x3
  Res.Df    RSS Df Sum of Sq       F   Pr(&gt;F)   
1     49 3192.6                                 
2     48 2874.8  1    317.77  6.2327 0.016271 * 
3     47 2348.8  1    526.06 10.3181 0.002435 **
4     45 2294.3  2     54.50  0.5344 0.589671   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The output here compares each model to the model before it. This means each test is of the <strong>incremental</strong> addition of of each predictor after the predictors before it.</p>
<p>However, if we just give the fullest model to <code>anova()</code>, then it will do this procedure for us!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: y
          Df  Sum Sq Mean Sq F value   Pr(&gt;F)   
x1         1  317.77  317.77  6.2327 0.016271 * 
x2         1  526.06  526.06 10.3181 0.002435 **
x3         2   54.50   27.25  0.5344 0.589671   
Residuals 45 2294.29   50.98                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>These are testing, in order - - the inclusion of x1 over the null model (without any predictors) - the inclusion of x1 over the model with just x1 - the inclusion of x3 over the model with x1 and x2</p>
<div class="imp">
<p><strong>THE ORDER MATTERS</strong></p>
<p>When we give one model the <code>anova()</code>, the order that we write our predictors in our model makes a difference!</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Comparisons with and without each predictor
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We might instead want to set up a series of comparisons that individually drop each predictor:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>modelall   <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3, <span class="at">data =</span> mlr_data)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>modeldrop1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span>      x2 <span class="sc">+</span> x3, <span class="at">data =</span> mlr_data)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>modeldrop2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span>      x3, <span class="at">data =</span> mlr_data)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>modeldrop3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> x2,      <span class="at">data =</span> mlr_data)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modeldrop1, modelall) <span class="co"># models with and without x1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: y ~ 1 + x2 + x3
Model 2: y ~ 1 + x1 + x2 + x3
  Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)   
1     46 2710.5                               
2     45 2294.3  1     416.2 8.1634 0.00645 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modeldrop2, modelall) <span class="co"># models with and without x2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: y ~ 1 + x1 + x3
Model 2: y ~ 1 + x1 + x2 + x3
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1     46 2739.4                                
2     45 2294.3  1     445.1 8.7301 0.004965 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modeldrop3, modelall) <span class="co"># models with and without x3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: y ~ 1 + x1 + x2
Model 2: y ~ 1 + x1 + x2 + x3
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1     47 2348.8                           
2     45 2294.3  2    54.496 0.5344 0.5897</code></pre>
</div>
</div>
<p>There is also a shorthand way of doing this!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(modelall, <span class="at">test=</span><span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
y ~ 1 + x1 + x2 + x3
       Df Sum of Sq    RSS    AIC F value   Pr(&gt;F)   
&lt;none&gt;              2294.3 201.31                    
x1      1     416.2 2710.5 207.64  8.1634 0.006450 **
x2      1     445.1 2739.4 208.17  8.7301 0.004965 **
x3      2      54.5 2348.8 198.48  0.5344 0.589671   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="imp">
<p>The order that our predictors are put into the model doesn’t matter here because we’re just taking each predictor and comparing a model with and without it.</p>
<p>However, for more complicated models containing “interactions” (we learn about these in a couple of weeks), then this approach is sensitive to how we put categorical predictors into our model.</p>
</div>
<p>Note that this is like taking each predictor as if it were the “last one in” in the “incremental” approach above. For proof, you’ll note that the test of x3 is the same as above).</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: types of Sums of Squares
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Being able to test different sorts of associations for the same predictors in multiple regression is referred to as “Types of Sums of Squares” because it involves different methods for partitioning and attributing the variability.</p>
<ul>
<li><p>Type 1 Sums of Squares is the incremental addition of predictors, as seen with <code>anova(model)</code> above.</p></li>
<li><p>Type 3 Sums of Squares calculates the unique contribution of each predictor to the model, adjusting for all other predictors (as seen in <code>drop1(model)</code> above)</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sstype" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sstype-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlr/venn_ss_types.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sstype-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Types of Sums of Squares. Type 1 (Left) incrementally adds each predictor in turn. Type 3 (Right) assesses the marginal associations.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The coefficients from a multiple regression model are more closely tied to the Type 3 approach - they represent the association between outcome and the predictor after accounting for all other predictors.</p>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="interpreting-multiple-regression-coefficients" class="level1">
<h1>Interpreting Multiple Regression Coefficients</h1>
<p>Thus far in this chapter we have mainly been looking at our models in terms of their overall fit - i.e.&nbsp;assessing and comparing them in terms of ‘variance explained’. But the estimated coefficients also provide us with a wealth of information. They tell us <em>how</em> things are associated with <span class="math inline">\(y\)</span> (i.e.&nbsp;they quantify the effect), not just <em>whether</em> there are associations.</p>
<div class="sticky">
<ul>
<li>F tests and Model Comparisons: <strong>does/do</strong> [predictor(s)] explain variance in [outcome]?<br>
</li>
<li>Coefficients: <em><strong>how</strong></em> <strong>is</strong> [predictor] associated with [outcome]?</li>
</ul>
</div>
<p>We’ve seen that when we include multiple predictors, we get out multiple coefficients. The intercept in multiple regression model is very similar to the simple regression model - it is the estimated value of <span class="math inline">\(y\)</span> <em>when all predictors are zero</em>. The coefficients for each predictor are similar to previously in that they still represent the “change in <span class="math inline">\(y\)</span> (outcome) for a 1 unit change in <span class="math inline">\(x\)</span> (predictor). However, these are now the estimated associations while <em>holding all other predictors constant</em>.</p>
<p>Sometimes, this gets phrased as “the increase in [outcome] for a one unit increase in [predictor] when…”</p>
<ul>
<li>“holding [other predictors] constant.”</li>
<li>“holding [other predictors] fixed.”</li>
<li>“accounting for [other predictors].”</li>
<li>“adjusting for [other predictors].”</li>
<li>“controlling for differences in [other predictors].”</li>
<li>“partialling out the effects of [other predictors].”</li>
<li>“holding [other predictors] equal.”</li>
<li>“accounting for effects of [other predictors].”</li>
</ul>
<p>What exactly do all these mean? If we return to our regression surface, our coefficients are the angles of this surface. We can see that as <span class="math inline">\(x_2\)</span> increases, the surface goes down (the angle of the orange lines in the grid). This decrease is the same no matter where on <span class="math inline">\(x_1\)</span> we are (i.e.&nbsp;the angle doesn’t change as we move up <span class="math inline">\(x_1\)</span>). The coefficient for <span class="math inline">\(x_2\)</span> is the amount the surface changes on <span class="math inline">\(y\)</span>, provided we stay at the same value for <span class="math inline">\(x_1\)</span>.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_mlr_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mlr_data)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -2.39138    3.67735  -0.650  0.51867   
x1           0.17570    0.06435   2.730  0.00888 **
x2          -0.64756    0.19959  -3.244  0.00217 **</code></pre>
</div>
</div>
<p>Another way to think of this is to imagine a person who scores 3 on <span class="math inline">\(x_2\)</span>. What is the estimated difference between in <span class="math inline">\(y\)</span> between them and someone who scored 4 instead? The coefficient for <span class="math inline">\(x_2\)</span> tells us their scores on <span class="math inline">\(y\)</span> would differ by -0.65 <em>provided they don’t also differ on <span class="math inline">\(x_1\)</span>.</em> So we are moving along the regression surface in the <span class="math inline">\(x_2\)</span> direction. This makes sense, because if they <em>also</em> differed on <span class="math inline">\(x_1\)</span>, then we would expect their score on <span class="math inline">\(y\)</span> to change because of this too (i.e.&nbsp;we would be moving diagonally on the surface).</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: F and t
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Back to our Venn diagrams, the coefficients from our multiple regression model reflect the areas in each variable that overlap with <span class="math inline">\(y\)</span> and <em>not</em> with other variables, but they are scaled to be in terms of “change in <span class="math inline">\(y\)</span> associated with a one unit change in [predictor], holding [other predictors] constant”.</p>
<p>This means that our interpretation of multiple regression <em>coefficients</em> is analogous to the idea of a model comparison with and without that predictor.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 60%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th>model comparison</th>
<th>coefficient for x2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>model1 &lt;- lm(y~x1,mlr_data)</code><br><code>model2 &lt;- lm(y~x1+x2,mlr_data)</code><br><code>anova(model1, model2)</code></td>
<td><code>model2 &lt;- lm(y~x1+x2,mlr_data)</code><br><code>coef(model2)['x2']</code></td>
</tr>
<tr class="even">
<td>“<em>does X2</em> explain additional variance after accounting for x1?”</td>
<td>“what is the association between x2 and y, after accounting for x1?”</td>
</tr>
</tbody>
</table>
<p>In fact, the <span class="math inline">\(p-values\)</span> from the model comparison will even match those from the coefficient tests (see below). These are equivalent in this specific case, but when we more to more general forms of the model, it does not hold. The key reason being is that the model comparison in the linear regression world is assessing the reduction in residual sums of squares, which is directly linked to the slope of a regression line (see back to <a href="#fig-sstssrssm" class="quarto-xref">Figure&nbsp;1</a> above). When we move to more general models, the way we assess “improvements in fit” is not always about reduction in residual sums of squares, and so this equivalence can break.</p>
<div class="panelset">
<section id="model-comparison" class="level4 panel">
<h4 class="anchored" data-anchor-id="model-comparison">Model comparison</h4>
<p>With and without x2.<br>
<span class="math display">\[
F(1,47)=10.527,\, p = .00217
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1, <span class="at">data =</span> mlr_data)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mlr_data)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1, model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: y ~ x1
Model 2: y ~ x1 + x2
  Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)   
1     48 2874.8                               
2     47 2348.8  1    526.06 10.527 0.00217 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="coefficient" class="level4 panel">
<h4 class="anchored" data-anchor-id="coefficient">Coefficient</h4>
<p>coefficient for x2.</p>
<p><span class="math display">\[
t(47)=-3.244,\, p = .00217
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mlr_data)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2, data = mlr_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.5201  -4.2912  -0.0268   3.3044  16.2154 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -2.39138    3.67735  -0.650  0.51867   
x1           0.17570    0.06435   2.730  0.00888 **
x2          -0.64756    0.19959  -3.244  0.00217 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.069 on 47 degrees of freedom
Multiple R-squared:  0.2643,    Adjusted R-squared:  0.233 
F-statistic: 8.443 on 2 and 47 DF,  p-value: 0.0007369</code></pre>
</div>
</div>
</section>
</div>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="model-visualisations" class="level1">
<h1>Model Visualisations</h1>
<p>The associations we get out from our coefficients are conditional upon holding constant other predictors. How are we supposed to visualise this? Three-dimensional plots like the ones above are lovely, but a) they’re difficult to make and b) they only work when there is <em>one</em> other predictor variable being controlled for.</p>
<p>The typical way to plot these associations is to make a 2-dimensional figure that shows the <em>model estimated</em> increase in outcome <span class="math inline">\(y\)</span> across values of predictor <span class="math inline">\(x\)</span>.</p>
<p>Notice what we are doing here is plotting a “model estimated” slope. We can’t just plot our data an add <code>geom_smooth(method=lm)</code>, because that would give a visualisation of a linear model <strong>with just one predictor</strong> (whichever one is on the x-axis).</p>
<p>Returning to our Happy Commuter example from above, we want a way to present the estimated slope of <code>commute</code> from the model which <em>also</em> has <code>work_flex</code> in it.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>happycommute <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/happycommute.csv"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(jobsat <span class="sc">~</span> work_flex <span class="sc">+</span> commute, <span class="at">data =</span> happycommute)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   work_flex     commute 
-9.06999839  1.36735284 -0.03732698 </code></pre>
</div>
</div>
<p>In our Happy Commuters example, the difference between the coefficients when we did/didn’t include the <code>work_flex</code> predictor were <em>very</em> different.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_mlr_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>So how do we create plots like the on one the right? There are various helpful packages that are designed to make this easy (which we will come to a little later on in the course), but right now it will be very useful to go through the process of making these plots manually.</p>
<p>We will need to create a little dataset of the values of the predictors that we wish to predict across. We’ll go across all values of <code>commute</code> from 3 to 58 (the range of commuting times in our data), and we’ll keep <code>work_flex</code> as 20.75 (which is the mean of <code>work_flex</code> in our data):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>plotdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">commute =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">58</span>, <span class="co"># integers from 3 to 58</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">work_flex =</span> <span class="fl">20.75</span> <span class="co"># every value will be 20.75</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using this little dataset we can now form predictions from our model, which we can then plot. Using the <strong>broom</strong> package is a nice way to get the confidence intervals<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> as well as the predictions, and it returns it all attached to the dataframe:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model2, <span class="at">newdata =</span> plotdata, <span class="at">interval=</span><span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 56 × 5
   commute work_flex .fitted .lower .upper
     &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1       3      20.8    19.2   17.8   20.5
 2       4      20.8    19.2   17.8   20.5
 3       5      20.8    19.1   17.8   20.4
 4       6      20.8    19.1   17.8   20.3
 5       7      20.8    19.0   17.8   20.2
 6       8      20.8    19.0   17.8   20.2
 7       9      20.8    19.0   17.8   20.1
 8      10      20.8    18.9   17.8   20.0
 9      11      20.8    18.9   17.8   19.9
10      12      20.8    18.9   17.8   19.9
# ℹ 46 more rows</code></pre>
</div>
</div>
<p>And this looks like something we can put into ggplot!!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model2, <span class="at">newdata =</span> plotdata, <span class="at">interval=</span><span class="st">"confidence"</span>) <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> commute, <span class="at">y =</span> .fitted,</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">ymin =</span> .lower, <span class="at">ymax =</span> .upper)) <span class="sc">+</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">alpha =</span> .<span class="dv">3</span>) <span class="co"># alpha sets the transparency</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_mlr_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<!-- ::::panelset -->
<!-- :::panel -->
<!-- #### sjPlot -->
<!-- The __sjPlot__ package can make it very easy for us to create plots of model estimated effects. We need to give it the model, the type of thing we want plotted (in this case "eff" for "effect"), and the relevant predictor term (in this case "commute"):   -->
<!-- ```{r} -->
<!-- #| fig-height: 2.5 -->
<!-- library(sjPlot) -->
<!-- plot_model(model2, type = "eff", terms = "commute") -->
<!-- ``` -->
<!-- ::: -->
<!-- :::panel -->
<!-- #### jtools -->
<!-- __jtools__ is an alternative to sjPlot, and it's just as easy:   -->
<!-- ```{r} -->
<!-- library(jtools) -->
<!-- effect_plot(model2, pred=commute, interval=TRUE) -->
<!-- ``` -->
<!-- ::: -->
<!-- :::panel -->
<!-- #### effects -->
<!-- The __effects__ package is handy because it can give us a dataframe of estimates with upper and lower intervals to plot. It's a bit more cumbersome than __sjPlot__, but can be handy if we want more customisation:   -->
<!-- ```{r} -->
<!-- library(effects) -->
<!-- effect(term = "commute", mod = model2) |> -->
<!--   as.data.frame() -->
<!-- ``` -->
<!-- That dataframe we can then use to plot:   -->
<!-- ```{r} -->
<!-- # the xlevels tells it to estimate at 50 different values. -->
<!-- # this makes it a smoother plot: -->
<!-- effect(term = "commute", mod = model2, xlevels=50) |> -->
<!--   as.data.frame() |> -->
<!--   ggplot(aes(x=commute,y=fit))+ -->
<!--   geom_line()+ -->
<!--   geom_ribbon(aes(ymin=lower,ymax=upper), alpha=.3) -->
<!-- ``` -->
<!-- ::: -->
<!-- :::panel -->
<!-- #### Manually (optional) -->
<!-- We can extract the predicted values, and confidence bounds, using `predict()`. First we create a dataset of the values of the predictors that we wish to predict across. We'll predict `jobsat` for all values of `commute` from 3 to 58 (the range of commuting times in our data), and holding `work_flex` as 20.75 (the mean of `work_flex` in our data):  -->
<!-- ```{r} -->
<!-- plotdata <- data.frame( -->
<!--   work_flex = 20.75, -->
<!--   commute = 3:58 -->
<!-- ) -->
<!-- ``` -->
<!-- Then we add the predictions and the standard error   -->
<!-- ```{r} -->
<!-- plotdata <- plotdata |> -->
<!--   mutate( -->
<!--     predy = predict(model2, newdata=plotdata), -->
<!--     se = predict(model2, plotdata, se.fit = TRUE)$se -->
<!--   ) -->
<!-- ``` -->
<!-- And use the standard error to create the confidence intervals. Doing $1.96 \times SE$ would get us close, but to do it properly we should use the $t$-distribution:  -->
<!-- ```{r} -->
<!-- plotdata <- plotdata |>  -->
<!--   mutate( -->
<!--     lower = predy - (qt(.975, df=47) * se), -->
<!--     upper = predy + (qt(.975, df=47) * se) -->
<!--   ) -->
<!-- ``` -->
<!-- And finally we can plot!  -->
<!-- ```{r} -->
<!-- ggplot(plotdata, aes(x = commute, y = predy,  -->
<!--                      ymin = lower, ymax = upper)) + -->
<!--   geom_line() +  -->
<!--   geom_ribbon(alpha = .3) # alpha sets the transparency -->
<!-- ``` -->
<!-- ::: -->
<!-- :::: -->
<!-- It might help to think of this as if we are just tilting the our view of the regression surface so that we see it from only one edge:  -->
<!-- ```{r} -->
<!-- #| echo: false -->
<!-- mlr_data <- happycommute |> transmute(y=jobsat,x1=work_flex,x2=commute) -->
<!-- fit<-lm(y~x1+x2, data=mlr_data) -->
<!-- steps=50 -->
<!-- x1 <- with(mlr_data, seq(min(x1),max(x1),length=steps)) -->
<!-- x2 <- with(mlr_data, seq(min(x2),max(x2),length=steps)) -->
<!-- newdat <- expand.grid(x1=x1, x2=x2) -->
<!-- y <- matrix(predict(fit, newdat), steps, steps) -->
<!-- par(mfrow=c(1,2)) -->
<!-- p <- persp(x1,x2,y, theta = 50,phi=25, col = NA, -->
<!--            zlim=c(min(mlr_data$y),max(mlr_data$y))) -->
<!-- obs <- with(mlr_data, trans3d(x1,x2, y, p)) -->
<!-- pred <- with(mlr_data, trans3d(x1, x2, fitted(fit), p)) -->
<!-- points(obs, col = "red", pch = 16) -->
<!-- segments(obs$x, obs$y, pred$x, pred$y,lty = "dashed") -->
<!-- p <- persp(x1,x2,y, theta = 90,phi=46, col = NA, -->
<!--            zlim=c(min(mlr_data$y),max(mlr_data$y))) -->
<!-- obs <- with(mlr_data, trans3d(x1,x2, y, p)) -->
<!-- pred <- with(mlr_data, trans3d(x1, x2, fitted(fit), p)) -->
<!-- points(obs, col = "red", pch = 16) -->
<!-- segments(obs$x, obs$y, pred$x, pred$y,lty = "dashed") -->
<!-- par(mfrow=c(1,1)) -->
<!-- ``` -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<div id="exercise-loading-indicator" class="exercise-loading-indicator d-none d-flex align-items-center gap-2">
<div id="exercise-loading-status" class="d-flex gap-2">

</div>
<div class="spinner-grow spinner-grow-sm">

</div>
</div>
<script type="vfs-file">
W10=
</script>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p> - <span class="math inline">\(SS_{Total}\)</span> has <span class="math inline">\(n - 1\)</span> degrees of freedom as one degree of freedom is used up by estimating the mean <span class="math inline">\(\bar{y}\)</span>.<br>
- <span class="math inline">\(SS_{Residual}\)</span> has <span class="math inline">\(n - 2\)</span> degrees of freedom. There are <span class="math inline">\(n\)</span> datapoints in total, and once we define the regression line, <span class="math inline">\(n-2\)</span> of these could be <em>anywhere at all</em> (they are ‘free to vary’). The remaining 2 are determined by the other <span class="math inline">\(n-2\)</span> in order to get that line. - By difference, <span class="math inline">\(SS_{Model}\)</span> has <span class="math inline">\((n - 1) - (n - 2) = 1\)</span> degree of freedom. In other words, the model here is really just one thing - a line!<br>
<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>One could imagine this surface changing over time, which would bring in a 4th dimension, but beyond that, it’s not worth trying!<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>under the null hypothesis that all coefficients = 0, the ratio of explained:unexplained variance should be approximately 1<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>and vice versa for the coefficient of <span class="math inline">\(x_1\)</span>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>these intervals are using the standard errors multiplied by the appropriate value of <span class="math inline">\(t\)</span>. We did this more explicitly in Week 5, but the <code>augment()</code> function will do it for us here<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script>



/* update total correct if #webex-total_correct exists */

update_total_correct = function() {

  console.log("webex: update total_correct");



  var t = document.getElementsByClassName("webex-total_correct");

  for (var i = 0; i < t.length; i++) {

    p = t[i].parentElement;

    var correct = p.getElementsByClassName("webex-correct").length;

    var solvemes = p.getElementsByClassName("webex-solveme").length;

    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;

    var selects = p.getElementsByClassName("webex-select").length;



    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";

  }

}



/* webex-solution button toggling function */

b_func = function() {

  console.log("webex: toggle hide");



  var cl = this.parentElement.classList;

  if (cl.contains('open')) {

    cl.remove("open");

  } else {

    cl.add("open");

  }

}



/* check answers */

check_func = function() {

  console.log("webex: check answers");



  var cl = this.parentElement.classList;

  if (cl.contains('unchecked')) {

    cl.remove("unchecked");

    this.innerHTML = "Hide Answers";

  } else {

    cl.add("unchecked");

    this.innerHTML = "Show Answers";

  }

}



/* function for checking solveme answers */

solveme_func = function(e) {

  console.log("webex: check solveme");



  var real_answers = JSON.parse(this.dataset.answer);

  var my_answer = this.value;

  var cl = this.classList;

  if (cl.contains("ignorecase")) {

    my_answer = my_answer.toLowerCase();

  }

  if (cl.contains("nospaces")) {

    my_answer = my_answer.replace(/ /g, "")

  }



  if (my_answer == "") {

    cl.remove("webex-correct");

    cl.remove("webex-incorrect");

  } else if (real_answers.includes(my_answer)) {

    cl.add("webex-correct");

    cl.remove("webex-incorrect");

  } else {

    cl.add("webex-incorrect");

    cl.remove("webex-correct");

  }



  // match numeric answers within a specified tolerance

  if(this.dataset.tol > 0){

    var tol = JSON.parse(this.dataset.tol);

    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)

    if (matches.reduce((a, b) => a + b, 0) > 0) {

      cl.add("webex-correct");

    } else {

      cl.remove("webex-correct");

    }

  }



  // added regex bit

  if (cl.contains("regex")){

    answer_regex = RegExp(real_answers.join("|"))

    if (answer_regex.test(my_answer)) {

      cl.add("webex-correct");

    }

  }



  update_total_correct();

}



/* function for checking select answers */

select_func = function(e) {

  console.log("webex: check select");



  var cl = this.classList



  /* add style */

  cl.remove("webex-incorrect");

  cl.remove("webex-correct");

  if (this.value == "answer") {

    cl.add("webex-correct");

  } else if (this.value != "blank") {

    cl.add("webex-incorrect");

  }



  update_total_correct();

}



/* function for checking radiogroups answers */

radiogroups_func = function(e) {

  console.log("webex: check radiogroups");



  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');

  var cl = checked_button.parentElement.classList;

  var labels = checked_button.parentElement.parentElement.children;



  /* get rid of styles */

  for (i = 0; i < labels.length; i++) {

    labels[i].classList.remove("webex-incorrect");

    labels[i].classList.remove("webex-correct");

  }



  /* add style */

  if (checked_button.value == "answer") {

    cl.add("webex-correct");

  } else {

    cl.add("webex-incorrect");

  }



  update_total_correct();

}



window.onload = function() {

  console.log("webex onload");

  /* set up solution buttons */

  var buttons = document.getElementsByTagName("button");



  for (var i = 0; i < buttons.length; i++) {

    if (buttons[i].parentElement.classList.contains('webex-solution')) {

      buttons[i].onclick = b_func;

    }

  }



  var check_sections = document.getElementsByClassName("webex-check");

  console.log("check:", check_sections.length);

  for (var i = 0; i < check_sections.length; i++) {

    check_sections[i].classList.add("unchecked");



    let btn = document.createElement("button");

    btn.innerHTML = "Show Answers";

    btn.classList.add("webex-check-button");

    btn.onclick = check_func;

    check_sections[i].appendChild(btn);



    let spn = document.createElement("span");

    spn.classList.add("webex-total_correct");

    check_sections[i].appendChild(spn);

  }



  /* set up webex-solveme inputs */

  var solveme = document.getElementsByClassName("webex-solveme");



  for (var i = 0; i < solveme.length; i++) {

    /* make sure input boxes don't auto-anything */

    solveme[i].setAttribute("autocomplete","off");

    solveme[i].setAttribute("autocorrect", "off");

    solveme[i].setAttribute("autocapitalize", "off");

    solveme[i].setAttribute("spellcheck", "false");

    solveme[i].value = "";



    /* adjust answer for ignorecase or nospaces */

    var cl = solveme[i].classList;

    var real_answer = solveme[i].dataset.answer;

    if (cl.contains("ignorecase")) {

      real_answer = real_answer.toLowerCase();

    }

    if (cl.contains("nospaces")) {

      real_answer = real_answer.replace(/ /g, "");

    }

    solveme[i].dataset.answer = real_answer;



    /* attach checking function */

    solveme[i].onkeyup = solveme_func;

    solveme[i].onchange = solveme_func;



    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")

  }



  /* set up radiogroups */

  var radiogroups = document.getElementsByClassName("webex-radiogroup");

  for (var i = 0; i < radiogroups.length; i++) {

    radiogroups[i].onchange = radiogroups_func;

  }



  /* set up selects */

  var selects = document.getElementsByClassName("webex-select");

  for (var i = 0; i < selects.length; i++) {

    selects[i].onchange = select_func;

    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")

  }



  update_total_correct();

}



</script>

<script>

if (window.location.href.includes('displayall')) {

  document.body.id = 'displayall';

} else {

  document.body.id = 'progressive';

}

</script>

<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<script type="module">
if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
window._ojs.paths.runtimeToDoc = "../..";
window._ojs.paths.runtimeToRoot = "../..";
window._ojs.paths.docToRoot = "";
window._ojs.selfContained = false;
window._ojs.runtime.interpretFromScriptTags();
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>