<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>15: Interactions – Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-97338aec0b8b6c6d6887a474ba26a80e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/live-runtime/live-runtime.js" type="module"></script>
<link href="site_libs/quarto-contrib/live-runtime/live-runtime.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

function toggle_visibility(id1, id2) {

var e = document.getElementById(id1);

var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('jk-circle-right')) {

    f.classList.add('jk-circle-down')

    f.classList.remove('jk-circle-right')

} else {

    f.classList.add('jk-circle-right')

    f.classList.remove('jk-circle-down')

}

}

</script>



<!---<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>-->

<script type="module" src="site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
<link href="site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">
<link href="site_libs/panelset-0.3.0/panelset.css" rel="stylesheet">

<script src="site_libs/panelset-0.3.0/panelset.js"></script>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./15_interactions.html">15: Interactions</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Linear Models</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1: A first look at R &amp; RStudio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2: More R - Basic Data Skills</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3: Measurement &amp; Distributions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4: Curves &amp; Sampling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5: Foundations of Inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_inference2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6: Practical Inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_chisq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7: Binomial &amp; Chi-Square Tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_revisitnhst.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8: Revisiting NHST</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_covcor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9: Covariance and Correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10: Simple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./zz_wt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">- WalkThrough: Advanced Data Wrangling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11: Multiple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_assumptdiag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12: Assumptions, Diagnostics, and Troubleshooting</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">13: Centering and Scaling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_catpred.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">14: Categorical Predictors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_interactions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">15: Interactions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16_glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">16: The Generalized Linear Model</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#holding-constant" id="toc-holding-constant" class="nav-link active" data-scroll-target="#holding-constant">Holding Constant…</a></li>
  <li><a href="#it-depends" id="toc-it-depends" class="nav-link" data-scroll-target="#it-depends">It Depends…</a></li>
  <li><a href="#interactions" id="toc-interactions" class="nav-link" data-scroll-target="#interactions">Interactions!</a></li>
  <li><a href="#fitting-interactions-in-r" id="toc-fitting-interactions-in-r" class="nav-link" data-scroll-target="#fitting-interactions-in-r">Fitting interactions in R</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#visualisation" id="toc-visualisation" class="nav-link" data-scroll-target="#visualisation">Visualisation</a></li>
  <li><a href="#getting-more-from-your-model" id="toc-getting-more-from-your-model" class="nav-link" data-scroll-target="#getting-more-from-your-model">Getting more from your model</a>
  <ul class="collapse">
  <li><a href="#mean-centering" id="toc-mean-centering" class="nav-link" data-scroll-target="#mean-centering">Mean Centering</a></li>
  <li><a href="#relevelling-factors" id="toc-relevelling-factors" class="nav-link" data-scroll-target="#relevelling-factors">Relevelling Factors</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">15: Interactions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="lo">
<p>This reading:</p>
<ul>
<li>What happens when the association between two variables <em>depends on</em> the level of a third? How can we build this into a linear model?<br>
</li>
<li>Scaling and contrast schemes in the context of models with interactions</li>
</ul>
</div>
<section id="holding-constant" class="level1">
<h1>Holding Constant…</h1>
<p>So far, when we’ve been using multiple linear regression models, all our coefficients have been being interpreted as the “change in <span class="math inline">\(y\)</span> for a 1-unit change in <span class="math inline">\(x\)</span> <strong>while holding constant</strong> the other predictors in the model”.</p>
<p>Consider a model with the following structure:<br>
<span class="math display">\[
y = b_0 + b_1 \cdot x_1 + b_2 \cdot x_2 + \epsilon
\]</span></p>
<p>When we fit this model structure to some data, we get out our estimated values for the coefficients <span class="math inline">\(b_0\)</span>, <span class="math inline">\(b_1\)</span>, and <span class="math inline">\(b_2\)</span>, e.g.,:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>mydata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_mlr.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>mymodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -2.39138    3.67735  -0.650  0.51867   
x1           0.17570    0.06435   2.730  0.00888 **
x2          -0.64756    0.19959  -3.244  0.00217 **</code></pre>
<p>The coefficient we get out for <span class="math inline">\(x_1\)</span> tells us that the model estimates that <span class="math inline">\(y\)</span> will increase by 0.17 for every increase of 1 unit in <span class="math inline">\(x_1\)</span>, <em>provided that we hold <span class="math inline">\(x_2\)</span> constant.</em></p>
<p>So for <em>any</em> value of <span class="math inline">\(x_2\)</span>, a one unit increase in <span class="math inline">\(x_1\)</span> is associated with a <span class="math inline">\(b_1\)</span> change in <span class="math inline">\(y\)</span>, provided that <span class="math inline">\(x_2\)</span> value stays as it is.</p>
<p>Let’s use our primate brains data for a more realistic example:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>braindata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_braindata.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>braindata <span class="ot">&lt;-</span> braindata <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">isMonkey =</span> <span class="fu">ifelse</span>(species <span class="sc">!=</span> <span class="st">"Human"</span>, <span class="st">"YES"</span>, <span class="st">"NO"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>monkeymod <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_brain <span class="sc">~</span> age <span class="sc">+</span> isMonkey, <span class="at">data =</span> braindata)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(monkeymod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>...
Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.668308   0.050478  13.240 1.57e-14 ***
age         -0.004081   0.002337  -1.746   0.0904 .  
isMonkeyYES -0.246933   0.044152  -5.593 3.54e-06 ***
---</code></pre>
<p>Our coefficient for <code>isMonkeyYES</code> coefficient is the estimated difference in brain mass between a human and a monkey <strong>of the same age</strong>.<br>
Similarly, our coefficient for <code>age</code> is the estimated change in brain mass for every additional year of age, provided we are not comparing a monkey to a human.</p>
<p>The idea of this can be seen on the plot in <a href="#fig-constplot" class="quarto-xref">Figure&nbsp;1</a>. Imagine 4 different participants in our data. The coefficient for <code>isMonkeyYES</code> is the difference between A and C, or the difference between B and D. It doesn’t matter where on the x-axis we go, it is the <em>vertical</em> distance between the two lines.<br>
The <code>age</code> coefficient is the comparison between A and B, or between C and D.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-constplot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-constplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15_interactions_files/figure-html/fig-constplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-constplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: multiple regression model of brain mass predicted by age and isMonkey. The age coefficient is the slope of the lines, and the isMonkey coefficient is the difference in their heights
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<em>another</em> example (if you want one)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We’re interested in estimating the association between BMI and cognition, after controlling for differences due to age.</p>
<p>We want to use this model:<br>
<span class="math display">\[
\text{score on test of cognition} = b_0 + b_1 \cdot \text{age} + b_2 \cdot \text{BMI} + \epsilon
\]</span> which we can fit using <code>lm()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(score <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> age <span class="sc">+</span> BMI, <span class="at">data =</span> ourdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and we might get some coefficients (estimates for the <span class="math inline">\(b_?\)</span> values) such as those below:<br>
<em>(I’ve just made up some nice round numbers to make it easier to think about)</em></p>
<pre><code>Coefficients:
            Estimate    ...   ...
(Intercept)  160.000    ...   ...
age         -1.50000    ...   ...
BMI         -2.50000    ...   ...</code></pre>
<p>The coefficient of interest, the one for BMI, is telling us that “a 1 unit increase in BMI is associated with a -2.5 decrease in Scores on the cognitive test, <em>holding age constant</em>”.</p>
<p>Consider 3 people:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pplconstant" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pplconstant-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/ints/constant.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pplconstant-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Three theoretical people
</figcaption>
</figure>
</div>
</div>
</div>
<p>The coefficient for BMI represents the difference in cognitive scores we would expect between Person A and Person B.</p>
<p>Think about why this is.<br>
For some person <span class="math inline">\(i\)</span>, their model predicted score is:<br>
<span class="math display">\[
\hat{score_i} = b_0 + b_1 \cdot age_i + b_2 \cdot BMI_i
\]</span> Which from our model estimates is:<br>
<span class="math display">\[
\hat{score_i} = 160 - 1.5 \cdot age_i - 2.5 \cdot BMI_i
\]</span></p>
<ul>
<li>Person A’s score = <span class="math inline">\(160 - (1.5*50) - (2.5*22) = 30\)</span></li>
<li>Person B’s score = <span class="math inline">\(160 - (1.5*50) - (2.5*23) = 27.5\)</span></li>
<li>Person C’s score = <span class="math inline">\(160 - (1.5*60) - (2.5*23) = 12.5\)</span></li>
</ul>
<p>The difference in model estimated Score between Person A and Person B is the coefficient of BMI, because those two people <em>only differ</em> on BMI. Person A and Person C <em>also differ</em> on age. This is how the coefficient of BMI is interpreted as “holding age constant” - it is a comparison between two hypothetical people who differ on BMI but are identical with respect to the other predictors in the model.</p>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="it-depends" class="level1">
<h1>It Depends…</h1>
<p>Sometimes, however, we might have reason to think that a certain association should <em>not</em> be the same at every value of another variable.</p>
<p>There are lots of practical cases where we might think that the relationship between two variables <em>depends on</em> the value of a third.</p>
<p>Below are some examples of this idea, where the explanatory variables (the predictors) are of different types (e.g.&nbsp;continuous, categorical, etc):</p>
<div class="panelset">
<section id="example-1" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-1">Example 1</h4>
<blockquote class="blockquote">
<p>The amount to which spending time with partner influences wellbeing <em>depends on</em> the quality of the relationship.</p>
</blockquote>
<p>Variables:</p>
<ul>
<li><strong>Outcome:</strong> Wellbeing (questionnaire score ranging from 0 to 32)</li>
<li><strong>Continuous Predictor:</strong> Time spent with partner (hours per day)<br>
</li>
<li><strong>Continuous Predictor:</strong> Relationship Quality (rating from 0 to 100)</li>
</ul>
</section>
<section id="example-2" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-2">Example 2</h4>
<blockquote class="blockquote">
<p>The influence of air-pollution on cognitive functioning <em>depends on</em> genetic status.</p>
</blockquote>
<p>Variables:</p>
<ul>
<li><strong>Outcome:</strong> Cognitive Functioning measured via the MMSE. Possible scores range from 0 to 30. Lower scores indicate poorer cognitive functioning</li>
<li><strong>Continuous Predictor:</strong> Air-Quality Pollution Index (AQI). Ranges from 0 to 500. The higher the AQI value, the greater the level of air pollution.</li>
<li><strong>Categorical Predictor:</strong> APOE-4 Genotype status: Negative vs Positive</li>
</ul>
</section>
<section id="example-3" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-3">Example 3</h4>
<blockquote class="blockquote">
<p>Trick-or-treating children are more greedy when their costume hides their identity. But this is different <em>depending on</em> whether they are alone or in a group.</p>
</blockquote>
<p>Variables:</p>
<ul>
<li><strong>Outcome</strong>: Number of candy bars taken while trick or treating</li>
<li><strong>Categorical Predictor:</strong> Whether or not the childs’ identity is hidden by their costume (anonymous vs identifiable)</li>
<li><strong>Categorical Predictor:</strong> Whether the child is trick or treating as a group or alone (alone vs group)</li>
</ul>
</section>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="interactions" class="level1">
<h1>Interactions!</h1>
<p>In each of the above examples, we can no longer think about “the relationship between [outcome] and [predictor]” without discussing the level of the other predictor.</p>
<div class="columns">
<div class="column" style="width:55%;">
<p>Using Example 1 above, let’s return to thinking about this in terms of two different observations (i.e.&nbsp;two different people in <a href="#fig-pplint" class="quarto-xref">Figure&nbsp;3</a>).<br>
How do we think people’s wellbeing will differ between someone who spends 1 hour with their partner and someone who spends 2 hours with their partner?</p>
<p>If these are people from group A (these are people who have a really great relationship), then that extra hour will probably make a big impact on wellbeing!</p>
<p>Will it be the same for people from group B? People in group B are those people who don’t have great relationships. For these people, whether you spend 1 hour or 2 hours with your partner doesn’t pattern with a difference in wellbeing to the same extent as it does for the people in group A. It might even have a negative impact!</p>
</div><div class="column" style="width:45%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pplint" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pplint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/ints/ints.png" class="quarto-figure quarto-figure-center figure-img" style="width:80.0%" height="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pplint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Comparisons between two theoretical observations who differ on only one predictor now depends on some other predictor
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>To capture this, what we need is an <em>extra</em> bit of information to tell us “how <em>much</em> does the association between ‘time spent with partner’ and wellbeing change as relationship quality changes?” And this is something we can include in our model, and get an estimate for!</p>
<p>We can model the idea of “the association between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span> changes <em>depending on</em> the level of <span class="math inline">\(x_2\)</span>” by including a product (multiplication) term between the two predictors.</p>
<p>Such a model would take the form:</p>
<p><span class="math display">\[
y = b_0 + b_1 \cdot x_1 + b_2 \cdot x_2 + b_3 \cdot x_1 \cdot x_2 + \epsilon
\]</span></p>
<p>What this is doing is saying that our outcome <span class="math inline">\(y\)</span> is predicted by:</p>
<ul>
<li>some amount of <span class="math inline">\(x_1\)</span></li>
<li>some amount of <span class="math inline">\(x_2\)</span></li>
<li>and a little addition to each of those amounts depending on the value of of the other variable.</li>
</ul>
<p>To provide a visual intuition and build on how we have been thinking of multiple regression upto this point, when we have two predictors that interact, our regression surface is no longer flat, but <em>twists</em>. This is because the slope along values of <span class="math inline">\(x_1\)</span> <em>changes</em> as we move up <span class="math inline">\(x_2\)</span>:</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
why is it multiplication?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If we think about the simple additive model (additive = <strong>without</strong> the interaction), then what we’re saying is that the effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> is simply <span class="math inline">\(b_1\)</span>, which is a <em>constant</em> (i.e.&nbsp;just a single number).</p>
<p><span class="math display">\[
y = b_0 + \underbrace{b_1}_{\text{effect}\\ \text{of } x_1} \cdot x_1 + b_2 \cdot x_2 + \epsilon
\]</span> But what we want to model is that “the effect of <span class="math inline">\(x_1\)</span> <em>depends</em> on <span class="math inline">\(x_2\)</span>”, so the effect is not just a single constant number, it’s more like “some number plus an amount of <span class="math inline">\(x_2\)</span>”.<br>
For “an amount of <span class="math inline">\(x_2\)</span>” let’s use <span class="math inline">\(b_3 \cdot x_2\)</span>:</p>
<p><span class="math display">\[
y = b_0 + \underbrace{(\overbrace{b_1}^{\,\,\text{ some}\\ \text{number}} + \overbrace{b_{3} \cdot x_2}^{\text{some amount of }x_2})}_{\text{effect of } x_1} \cdot x_1 + b_2 \cdot x_2 + \epsilon
\]</span></p>
<p>Which really expands out to:</p>
<p><span class="math display">\[
y = b_0 + b_1 \cdot x_1 + b_3 \cdot x_2 \cdot x_1 + b_2 \cdot x_2 + \epsilon
\]</span></p>
</div>
</div>
</div>
<div class="panelset">
<section id="example-1-1" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-1-1">Example 1</h4>
<blockquote class="blockquote">
<p>The amount to which spending time with my partner influences my wellbeing <em>depends on</em> the quality of our relationship.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-i.contcont" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-i.contcont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15_interactions_files/figure-html/fig-i.contcont-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-i.contcont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Interaction between two continuous predictors, viewed from two angles
</figcaption>
</figure>
</div>
</div>
</div>
<p>At high values of relationship quality, the amount wellbeing increases with time spent is greater than it is at low values of relationship quality.<br>
And we can phrase this the other way around: at high amounts of time spent with partner, relationship quality has a bigger effect on wellbeing than it does for low amounts of time spent.</p>
<p>In the model with this interaction:<br>
<span class="math display">\[
\text{wellbeing} = b_0 + b_1 \cdot \text{time} + b_2 \cdot \text{quality} + b_3 \cdot \text{time} \cdot \text{quality}
\]</span> The interaction coefficient <span class="math inline">\(b_3\)</span> is the adjustment we make to the slope of wellbeing with “time spent with partner”, as we move 1 up in “relationship quality”.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</section>
<section id="example-2-1" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-2-1">Example 2</h4>
<blockquote class="blockquote">
<p>The influence of air-pollution on cognitive functioning <em>depends on</em> your genetic status.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-i.contcat" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-i.contcat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15_interactions_files/figure-html/fig-i.contcat-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-i.contcat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Interaction between a continuous and a binary categorical predictors
</figcaption>
</figure>
</div>
</div>
</div>
<p>This kind of interaction (where one predictor is continuous and the other is categorical), is sometimes the easiest to think about.</p>
<p>We can see in <a href="#fig-i.contcat" class="quarto-xref">Figure&nbsp;5</a> that cognition decreases as air pollution increases, <strong>but</strong> this is different depending on genetic status. In the APOE4-positive group, the association is steeper than in the APOE4-negative group. The interaction is evident in that the two lines are non-parallel.</p>
<p>In the model:</p>
<p><span class="math display">\[
\text{Cognition} = b_0 + b_1 \cdot\text{pollution} + b_2\cdot\text{APOE4} + b_3\cdot\text{pollution} \cdot \text{APOE4}
\]</span></p>
<p>The interaction term <span class="math inline">\(b_3\)</span> is the estimated adjustment made to the slope of cogition across air pollution when we move from one group to the other. e.g.&nbsp;the slope for the APOE4-positive group is equal to the slope of the APOE4-negative group <em>plus the interaction term</em>.</p>
</section>
<section id="example-3-1" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-3-1">Example 3</h4>
<blockquote class="blockquote">
<p>The influence of being anonymous on childrens’ greedy behaviours <em>depends on</em> if they are alone or part of a group.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-i.catcat" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-i.catcat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15_interactions_files/figure-html/fig-i.catcat-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-i.catcat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Interaction between two categorical predictors
</figcaption>
</figure>
</div>
</div>
</div>
<p>For interactions between two categorical variables, we tend to plot the mean of the outcome variable for each combination of levels. We can see the interaction in <a href="#fig-i.catcat" class="quarto-xref">Figure&nbsp;6</a> in the fact that the two dotted lines we have added to join the group-means are not parallel.</p>
<p>Children who are anonymous tend to take more candybars than those who are identifiable, but this difference is much greater when children are trick of treating in a group than when they are doing so alone!</p>
<p>In the model <span class="math display">\[
\text{candy} = b_0 + b_1 \cdot\text{isAnon} + b_2\cdot\text{inGroup} + b_3\cdot\text{isAnon} \cdot \text{inGroup}
\]</span></p>
<p>The interaction term <span class="math inline">\(b_3\)</span> is going to be the estimated adjustment to the difference between anonymous vs identifiable for children in a group vs those alone. Put another way, it is how the difference between the two blue dots in alone vs group for is different from the difference between the two red dots.<br>
e.g.&nbsp;the difference between anonymous &amp; identifiable children in a group is equal to the difference between anonymous &amp; identifiable children who are alone <em>plus the interaction term</em>.</p>
</section>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="fitting-interactions-in-r" class="level1">
<h1>Fitting interactions in R</h1>
<p>In R, the interaction term gets denoted by a colon <code>:</code> between the two predictor variables. We can fit an interaction term in a regression model quite easily in R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we don't *need* to put the 1, it's up to you :)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x1<span class="sc">:</span>x2, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This maps to the model equation we saw earlier: <span class="math display">\[
y = b_0 + b_1\cdot x_1 + b_2 \cdot x_2 + b_3 \cdot x_1 \cdot x_2 + \epsilon
\]</span></p>
<div class="rtip">
<p><strong>Shortcut</strong></p>
<p>To express <code>x1 + x2 + x1:x2</code>, we can also use just <code>x1*x2</code>.</p>
<p>These two models are equivalent:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x1<span class="sc">:</span>x2, <span class="at">data =</span> dataset)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1<span class="sc">*</span>x2, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="imp">
<p>If we fit the interaction <code>x1:x2</code>, we almost <em>always</em> want to also fit the separate effects <code>x1</code> and <code>x2</code>.</p>
<p><em>“Except in special circumstances, a model including a product term for interaction between two explanatory variables should also include terms with each of the explanatory variables individually, even though their coefficients may not be significantly different from zero. Following this rule avoids the logical inconsistency of saying that the effect of <span class="math inline">\(x_1\)</span> depends on the level of <span class="math inline">\(x_2\)</span> but that there is no effect of <span class="math inline">\(x_1\)</span>.”</em> <a href="https://www.cengage.uk/c/the-statistical-sleuth-3e-ramsey-schafer/9781133490678/" target="_blank">Ramsey &amp; Schafer</a></p>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="interpretation" class="level1">
<h1>Interpretation</h1>
<p>When we include an interaction term in our model, we are saying that two effects of the two predictors on the outcome are <em>dependent upon</em> one another. This means that with an interaction in the model <code>lm(y ~ x1 + x2 + x1:x2)</code> we can no longer talk about the “effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span><em>‘holding <span class="math inline">\(x_2\)</span> constant’</em>”. Instead we have to talk about <strong>marginal effects</strong> - e.g.&nbsp;the effect of <span class="math inline">\(x_1\)</span> <em>at a <strong>specific</strong> value</em> of <span class="math inline">\(x_2\)</span>.</p>
<p>When we fit a model with an interaction in R, we get out coefficients for both predictors, and for the interaction. The coefficients for each individual predictor reflect the effect on the outcome <em>when the other predictor is zero</em>.</p>
<pre><code>lm(formula = y ~ x1 * x2, data = df)
...
...
Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  ...        ....       ...      ...  
x1           ...        ....       ...      ...  
x2           ...        ....       ...      ...  
x1:x2        ...        ....       ...      ...  
---</code></pre>
<div class="sticky">
<p><strong>marginal effects when the other predictor is zero</strong></p>
<p>The individual coefficients for each predictor that is involved in an interaction are estimated <em>when the other predictor in the interaction is zero.</em></p>
</div>
<p>These coefficients can be interpreted, in turn as:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>(Intercept)</code></td>
<td>the estimated <span class="math inline">\(y\)</span> when all predictors (<span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>) are zero is [<em>estimate</em>]</td>
</tr>
<tr class="even">
<td><code>x1</code></td>
<td><strong>when <span class="math inline">\(x_2\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_1\)</span> is associated with a [<em>estimate</em>] change in <span class="math inline">\(y\)</span></td>
</tr>
<tr class="odd">
<td><code>x2</code></td>
<td><strong>when <span class="math inline">\(x_1\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_2\)</span> is associated with a [<em>estimate</em>] change in <span class="math inline">\(y\)</span>.</td>
</tr>
<tr class="even">
<td><code>x1:x2</code></td>
<td>as <span class="math inline">\(x_2\)</span> increases by 1, the association between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span> changes by [<em>estimate</em>]<br><em><strong>or</strong></em><br>as <span class="math inline">\(x_1\)</span> increases by 1, the association between <span class="math inline">\(x_2\)</span> and <span class="math inline">\(y\)</span> changes by [<em>estimate</em>]</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What if there are other things in the model too?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Note that the interaction <code>x1:x2</code> changes how we interpret the individual coefficients for <code>x1</code> and <code>x2</code>.</p>
<p>It does <strong><em>not</em></strong> change how we interpret coefficients for other predictors that might be in our model. For variables that <strong>aren’t</strong> involved in the interaction term, these are still held constant.</p>
<p>For example, suppose we <em>also</em> had another predictor <span class="math inline">\(c_1\)</span> in our model:</p>
<pre><code>lm(y ~ c1 + x1 + x2 + x1:x2)</code></pre>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>(Intercept)</code></td>
<td>the estimated <span class="math inline">\(y\)</span> when all predictors (<span class="math inline">\(c_1\)</span>, <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>) are zero is [<em>estimate</em>]</td>
</tr>
<tr class="even">
<td><code>c1</code></td>
<td>a 1 unit increase in <span class="math inline">\(c_1\)</span> is associated with a [<em>estimate</em>] increase in <span class="math inline">\(y\)</span>, holding constant all other variables in the model (<span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>)</td>
</tr>
<tr class="odd">
<td><code>x1</code></td>
<td>holding <span class="math inline">\(c_1\)</span> constant, <strong>when <span class="math inline">\(x_2\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_1\)</span> is associated with a [<em>estimate</em>] change in <span class="math inline">\(y\)</span></td>
</tr>
<tr class="even">
<td><code>x2</code></td>
<td>holding <span class="math inline">\(c_1\)</span> constant, <strong>when <span class="math inline">\(x_1\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_2\)</span> is associated with a [<em>estimate</em>] change in <span class="math inline">\(y\)</span>.</td>
</tr>
<tr class="odd">
<td><code>x1:x2</code></td>
<td>holding <span class="math inline">\(c_1\)</span> constant, as <span class="math inline">\(x_2\)</span> increases by 1, the association between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span> changes by [<em>estimate</em>]<br><em><strong>or</strong></em><br>holding <span class="math inline">\(c_1\)</span> constant, as <span class="math inline">\(x_1\)</span> increases by 1, the association between <span class="math inline">\(x_2\)</span> and <span class="math inline">\(y\)</span> changes by [<em>estimate</em>]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><br><br></p>
<div class="panelset">
<section id="example-1-2" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-1-2">Example 1</h4>
<blockquote class="blockquote">
<p>The amount to which spending time with my partner influences my wellbeing <em>depends on</em> the quality of our relationship.</p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ptdat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_partnertime.csv"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>eg1mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> partner_time <span class="sc">*</span> relationship_qual, <span class="at">data =</span> ptdat)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(eg1mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ partner_time * relationship_qual, data = ptdat)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.5592 -0.5559  0.1243  0.8884  3.2944 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    14.413160   2.192467   6.574 1.75e-08 ***
partner_time                   -1.405842   0.293737  -4.786 1.28e-05 ***
relationship_qual              -0.055658   0.036693  -1.517    0.135    
partner_time:relationship_qual  0.044363   0.004862   9.124 1.14e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.281 on 56 degrees of freedom
Multiple R-squared:  0.9377,    Adjusted R-squared:  0.9343 
F-statistic: 280.8 on 3 and 56 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>For someone who spends 0 hours with their partner, and who has a relationship quality score of 0, their estimated wellbeing is 14.41.<br>
</li>
<li>For someone who has a relationship quality score of 0, every hour spent with their partner is associated with a -1.41 change in wellbeing.<br>
</li>
<li>For someone who spends 0 hours with their partner, an increase of 1 in the relationship quality is associated with a -0.06 change in wellbeing.<br>
</li>
<li>For every 1 increase in relationship quality, an extra hour spent with their partner is associated with an <em>additional</em> 0.04 change in wellbeing.</li>
</ul>
</section>
<section id="example-2-2" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-2-2">Example 2</h4>
<blockquote class="blockquote">
<p>The influence of air-pollution on cognitive functioning <em>depends on</em> your genetic status.</p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>airpol <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_airpol.csv"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>eg2mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(mmse <span class="sc">~</span> aqpi <span class="sc">*</span> apoe4, <span class="at">data =</span> airpol)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(eg2mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mmse ~ aqpi * apoe4, data = airpol)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8225 -1.0241  0.2269  0.9554  3.8932 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   28.128929   0.642991  43.747  &lt; 2e-16 ***
aqpi          -0.016474   0.002930  -5.623 6.18e-07 ***
apoe4pos      -3.297908   0.904448  -3.646 0.000584 ***
aqpi:apoe4pos -0.014635   0.004405  -3.322 0.001578 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.674 on 56 degrees of freedom
Multiple R-squared:  0.8344,    Adjusted R-squared:  0.8255 
F-statistic: 94.06 on 3 and 56 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>For people who are APOE4 negative (the reference level, see <a href="11_mlr.html#multiple-categories-multiple-regression" target="_blank">Chapter 11 #multiple-categories-multiple-regression</a>), living where the Air Quality Pollution Index is 0 (no pollution), the estimated score on the MMSE (mini mental state exam) is 28.13.<br>
</li>
<li>For people who are APOE4 negative, a 1 unit increase in air pollution is associated with a -0.02 change in MMSE scores.<br>
</li>
<li>For people living with 0 air pollution, being APOE4 positive is associated with -3.3 lower MMSE scores compared to APOE4 negative</li>
<li>Compared to APOE4 negative, being APOE4 positive is associated with -0.01 greater decrease in MMSE scores for every 1 increase in air pollution.</li>
</ul>
</section>
<section id="example-3-2" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-3-2">Example 3</h4>
<blockquote class="blockquote">
<p>The influence of being anonymous on childrens’ greedy behaviours <em>depends on</em> if they are alone or part of a group.</p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_candy.csv"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>eg3mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(candybars <span class="sc">~</span> anonymity <span class="sc">*</span> asgroup, <span class="at">data =</span> candy)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(eg3mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = candybars ~ anonymity * asgroup, data = candy)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.9000 -0.3636  0.0000  0.9444  1.9444 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                         10.0556     0.2236  44.974  &lt; 2e-16 ***
anonymityidentifiable               -2.0556     0.3047  -6.746 9.08e-09 ***
asgroupgroup                         3.8444     0.3741  10.276 1.69e-14 ***
anonymityidentifiable:asgroupgroup  -4.4808     0.5144  -8.711 5.31e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9486 on 56 degrees of freedom
Multiple R-squared:  0.8548,    Adjusted R-squared:  0.847 
F-statistic: 109.9 on 3 and 56 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>An anonymous child trick or treating alone is estimated to take 10 candybars.</li>
<li>When trick or treating alone, compared to an anonymous child, an identifiable child is estimated to take 2 fewer candybars.<br>
</li>
<li>When anonymous, compared to trick or treating alone, children who are part of a group are estimated to take 3.8 more candybars.<br>
</li>
<li>The difference between identifiable and anonymous children’s candybar taking is 4 fewer when children are trick or treating in a group than when they are alone.</li>
</ul>
</section>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="visualisation" class="level1">
<h1>Visualisation</h1>
<p>We have seen lots of 3-dimensional plots above to try and help in building our intuition about how we model an interaction. However, we typically don’t really want to visualise models like this (in part because our models often have more than 2 predictors, and so have more than 3 dimensions).</p>
<p>What we therefore need to do is find ways to represent these relationships in 2-dimensional plots. This is slightly different depending on the type of variables we are dealing with.</p>
<ul>
<li>For a continuous <span class="math inline">\(\times\)</span> categorical interaction, we can plot the association of the continuous predictor with the outcome <em>for each level</em> of the categorical variable.</li>
<li>For a continuous <span class="math inline">\(\times\)</span> continuous interaction, we can plot the association of one predictor <em>at some judiciously chosen values</em> of the other (e.g.&nbsp;at the min, mean and max, or at -1 SD, mean, and +1 SD).<br>
</li>
<li>For a categorical <span class="math inline">\(\times\)</span> categorical interaction, we can plot the various estimated group means, with optional dotted<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> lines to illustrate the non-parallelism</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional helper packages
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can make these sort of plots very easily using handy packages that are designed to make our lives easier. The <em>big</em> downsides are that reliance on these packages will a) make it harder to customise plots, b) make it harder to troubleshoot when things go wrong, and c) stop us from having to <em>think</em> (and thinking is always good!).</p>
<p><strong>Use with caution:</strong></p>
<ul>
<li>From the <strong>sjPlot</strong> package: <code>plot_model(model, type = "int")</code> or <code>plot_model(model, type = "eff", terms = c("x1","x2"))</code><br>
</li>
<li>From the <strong>interactions</strong> package: <code>interact_plot(model, pred = "x1", modx = "x2")</code>, and <code>cat_plot()</code> for categorical interactions.</li>
</ul>
</div>
</div>
</div>
<div class="panelset">
<section id="example-1-3" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-1-3">Example 1</h4>
<blockquote class="blockquote">
<p>The amount to which spending time with my partner influences my wellbeing <em>depends on</em> the quality of our relationship.</p>
</blockquote>
<p>Plotting continuous by continuous interactions requires choosing a set of values for one of our predictors, at which we plot the slope of the other.</p>
<p>Here, we could choose to plot the slope of <code>wellbeing ~ partner_time</code> for the mean <code>relationship_qual</code>, and for 1 SD above and below that mean.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ptdat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_partnertime.csv"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>eg1mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> partner_time <span class="sc">*</span> relationship_qual, <span class="at">data =</span> ptdat)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># plot data</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>plotdat <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">partner_time =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">13</span>, <span class="co">#min to max of sample</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">relationship_qual =</span> <span class="fu">c</span>(</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(ptdat<span class="sc">$</span>relationship_qual)<span class="sc">-</span><span class="fu">sd</span>(ptdat<span class="sc">$</span>relationship_qual),</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(ptdat<span class="sc">$</span>relationship_qual),</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(ptdat<span class="sc">$</span>relationship_qual)<span class="sc">+</span><span class="fu">sd</span>(ptdat<span class="sc">$</span>relationship_qual)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(eg1mod, <span class="at">newdata =</span> plotdat, <span class="at">interval=</span><span class="st">"confidence"</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>partner_time, <span class="at">y=</span>.fitted, </span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">col=</span>relationship_qual,</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">group=</span>relationship_qual))<span class="sc">+</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> ptdat,<span class="fu">aes</span>(<span class="at">y=</span>wellbeing))<span class="sc">+</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>.lower,<span class="at">ymax=</span>.upper,<span class="at">fill=</span>relationship_qual),</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha=</span>.<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_interactions_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<!-- ::: {.callout-tip collapse="true"} -->
<!-- #### optional helper packages -->
<!-- The interactions package defaults to showing the y~x1 relationship when x2 is at -1 SD below the mean, at the mean, and +1 SD above the mean.   -->
<!-- ```{r} -->
<!-- library(interactions) -->
<!-- interact_plot(eg1mod, pred = "partner_time", modx = "relationship_qual", interval = TRUE) -->
<!-- ``` -->
<!-- The __sjPlot__ package can do this too, but wil default to showing it at the min and max of the other predictor.   -->
<!-- ```{r} -->
<!-- library(sjPlot) -->
<!-- plot_model(eg1mod, type="int") -->
<!-- ``` -->
<!-- We can change these manually. For instance, to make `plot_model` show the association when relationship quality is zero, when it is 50, and when it is 100, we could use:  -->
<!-- ```{r} -->
<!-- #| eval: false -->
<!-- plot_model(eg1mod, type = "eff", terms=c("partner_time","relationship_qual [0, 50, 100]")) -->
<!-- ``` -->
<!-- ::: -->
</section>
<section id="example-2-3" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-2-3">Example 2</h4>
<blockquote class="blockquote">
<p>The influence of air-pollution on cognitive functioning <em>depends on</em> your genetic status.</p>
</blockquote>
<p>This is the most straightforward type of interaction to visualise, as there are only a set number of values that one of the variables can take, meaning only a finite number of lines we need to draw:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>airpol <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_airpol.csv"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>eg2mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(mmse <span class="sc">~</span> aqpi <span class="sc">*</span> apoe4, <span class="at">data =</span> airpol)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># plot data</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>plotdat <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">aqpi =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">500</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">apoe4 =</span> <span class="fu">c</span>(<span class="st">"neg"</span>,<span class="st">"pos"</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(eg2mod, <span class="at">newdata =</span> plotdat, <span class="at">interval=</span><span class="st">"confidence"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>aqpi, <span class="at">y =</span> .fitted, </span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> apoe4, <span class="at">fill =</span> apoe4)) <span class="sc">+</span> </span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> airpol, <span class="fu">aes</span>(<span class="at">y =</span> mmse), <span class="at">alpha=</span>.<span class="dv">3</span>, <span class="at">size=</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>.lower,<span class="at">ymax=</span>.upper), <span class="at">alpha=</span>.<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_interactions_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<!-- ::: {.callout-tip collapse="true"} -->
<!-- #### optional helper packages -->
<!-- ```{r} -->
<!-- p1 <- sjPlot::plot_model(eg2mod, type = "int") -->
<!-- p2 <- interactions::interact_plot(eg2mod, pred = "aqpi", modx = "apoe4", interval = TRUE) -->
<!-- p1 / p2 -->
<!-- ``` -->
<!-- ::: -->
</section>
<section id="example-3-3" class="level4 panel">
<h4 class="anchored" data-anchor-id="example-3-3">Example 3</h4>
<blockquote class="blockquote">
<p>The influence of being anonymous on childrens’ greedy behaviours <em>depends on</em> if they are alone or part of a group.</p>
</blockquote>
<p>For these types of interactions (between categorical variables), plotting the estimates from our model is best done as our set of estimated group means.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_candy.csv"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>eg3mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(candybars <span class="sc">~</span> anonymity <span class="sc">*</span> asgroup, <span class="at">data =</span> candy)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># plot data</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>plotdat <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">anonymity =</span> <span class="fu">c</span>(<span class="st">"anonymous"</span>,<span class="st">"identifiable"</span>),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">asgroup =</span> <span class="fu">c</span>(<span class="st">"alone"</span>,<span class="st">"group"</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(eg3mod, <span class="at">newdata=</span>plotdat, <span class="at">interval=</span><span class="st">"confidence"</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> anonymity, <span class="at">col =</span> asgroup)) <span class="sc">+</span> </span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data =</span> candy, <span class="fu">aes</span>(<span class="at">y =</span> candybars),</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> .<span class="dv">3</span>, <span class="at">size =</span> <span class="dv">3</span>,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>              <span class="at">height =</span> <span class="dv">0</span>, <span class="at">width =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">y=</span>.fitted, <span class="at">ymin=</span>.lower, <span class="at">ymax=</span>.upper),</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>                  <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span>.<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_interactions_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<!-- ::: {.callout-tip collapse="true"} -->
<!-- #### optional helper packages -->
<!-- ```{r} -->
<!-- p1 <- sjPlot::plot_model(eg3mod, type = "int")  -->
<!-- p2 <- interactions::cat_plot(eg3mod, pred = "anonymity", modx = "asgroup", interval = TRUE) -->
<!-- p1 / p2 -->
<!-- ``` -->
<!-- ::: -->
</section>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="getting-more-from-your-model" class="level1">
<h1>Getting more from your model</h1>
<p>Reporting on interactions is a bit like telling a story. Listing the interpretation of the coefficients is fine, but often reads a bit awkwardly. A good presentation of the results would provide the reader with the overall pattern of results, pulling out the key parts that are of interest. There are various things we can do to get out coefficients that might be of more use to us in telling our story.</p>
<section id="mean-centering" class="level2">
<h2 class="anchored" data-anchor-id="mean-centering">Mean Centering</h2>
<p>By mean centering a continuous predictor, we change what “0” means. Normally, when we don’t have an interaction, this simply changes the intercept value (see <a href="13_scaling.html#centering-and-scaling-predictors" target="_blank">Chapter 13 #centering-and-scaling-predictors</a>). If we have the interaction <code>y ~ x1 + x2 + x1:x2</code>, then mean centering <code>x1</code> will make the coefficient for <code>x2</code> now represent “the association between <span class="math inline">\(x_2\)</span> and <span class="math inline">\(y\)</span> for someone at the <em>average</em> of <span class="math inline">\(x_1\)</span>”.</p>
<p>Using one of our examples from throughout this reading, we might mean-center the air-pollution so that we can consider the difference in MMSE scores between APOE4 positive and negative people <em>at the average air-pollution level</em></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>airpol <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_airpol.csv"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model with original variable</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>eg2mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(mmse <span class="sc">~</span> aqpi <span class="sc">*</span> apoe4, <span class="at">data =</span> airpol)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># model with mean centered predictor</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>eg2mod_cent <span class="ot">&lt;-</span> <span class="fu">lm</span>(mmse <span class="sc">~</span> <span class="fu">scale</span>(aqpi,<span class="at">scale=</span><span class="cn">FALSE</span>) <span class="sc">*</span> apoe4, <span class="at">data =</span> airpol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># coefficients:</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(eg2mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)          aqpi      apoe4pos aqpi:apoe4pos 
  28.12892936   -0.01647447   -3.29790816   -0.01463533 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(eg2mod_cent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        (Intercept)          scale(aqpi, scale = FALSE) 
                        25.16379896                         -0.01647447 
                           apoe4pos scale(aqpi, scale = FALSE):apoe4pos 
                        -5.93202402                         -0.01463533 </code></pre>
</div>
</div>
<p>This is because the coefficient for APOE4 compares the heights of the two lines when the other predictor is zero. So if we change what “zero” represents, we can change what that estimates. In the model plots below, we can see that <em>the model doesn’t change</em>, it is just extracting different information (it is the distance to move from the blue dot to the red dot):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_interactions_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="relevelling-factors" class="level2">
<h2 class="anchored" data-anchor-id="relevelling-factors">Relevelling Factors</h2>
<p>Another thing that can be useful (especially when working with categorical variables with lots of levels) is to make sure your variables are <code>factors</code> in R, and to set a useful reference level. Typically, the reference level is what we think of as “normal”, e.g.&nbsp;if we have 3 groups: Placebo, Drug A, and Drug B, then we might compare each drug to the placebo condition, because that’s comparable to most people (i.e.&nbsp;who aren’t taking the drug).</p>
<p>For example, when we have two categorical variables:</p>
<ul>
<li>anonymity = “anonymous” vs “identifiable”</li>
<li>asgroup = “alone” vs “group”</li>
</ul>
<p>Then the default is to take the alphabetical ordering. We can change the ordering using functions that “relevel” a factor. Note, this only works if the variable is <em>already</em> a <code>factor</code> in R (see <a href="03_measurement.html#categorical" target="_blank">Chapter 3 #categorical</a> for a reminder of ‘factors’).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/usmr_candy.csv"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># make both predictors 'factors'</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  candy <span class="sc">%&gt;%</span> </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">anonymity =</span> <span class="fu">factor</span>(anonymity),</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">asgroup =</span> <span class="fu">factor</span>(asgroup)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once they are factors, we can see the default levels:</p>
<div class="columns">
<div class="column" style="width:47.5%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(candy<span class="sc">$</span>anonymity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "anonymous"    "identifiable"</code></pre>
</div>
</div>
</div><div class="column" style="width:5%;">
<!-- empty column to create gap -->
</div><div class="column" style="width:47.5%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(candy<span class="sc">$</span>asgroup)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "alone" "group"</code></pre>
</div>
</div>
</div>
</div>
<p>This is the original model, with the default levels:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>eg3mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(candybars <span class="sc">~</span> anonymity <span class="sc">*</span> asgroup, <span class="at">data =</span> candy)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(eg3mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       (Intercept)              anonymityidentifiable 
                         10.055556                          -2.055556 
                      asgroupgroup anonymityidentifiable:asgroupgroup 
                          3.844444                          -4.480808 </code></pre>
</div>
</div>
<p>Let’s relevel anonymity to have “identifiable” as the first level, and then refit the model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  candy <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">anonymity =</span> <span class="fu">fct_relevel</span>(anonymity, <span class="st">"identifiable"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>eg3mod_rel <span class="ot">&lt;-</span> <span class="fu">lm</span>(candybars <span class="sc">~</span> anonymity <span class="sc">*</span> asgroup, <span class="at">data =</span> candy)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(eg3mod_rel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    (Intercept)              anonymityanonymous 
                      8.0000000                       2.0555556 
                   asgroupgroup anonymityanonymous:asgroupgroup 
                     -0.6363636                       4.4808081 </code></pre>
</div>
</div>
<p>Again, the model doesn’t change, we are simply extracting different bits from it:</p>
<div class="panelset">
<section id="reference-level-anonymous" class="level4 panel">
<h4 class="anchored" data-anchor-id="reference-level-anonymous">reference level = “anonymous”</h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_interactions_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="reference-level-identifiable" class="level4 panel">
<h4 class="anchored" data-anchor-id="reference-level-identifiable">reference level = “identifiable”</h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_interactions_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</div>
<!-- :::sticky -->
<!-- __Mapping model estimates to model plots__   -->
<!-- To help with interpretation of the estimated coefficients from a model, a very useful exercise is to try and map them to what we see in our model plots (as seen above).   -->
<!-- As we've talked about already - as models get more complex, there is a very important distinction to make between plotting the data and plotting the model estimates.   -->
<!-- Whereas previously we could plot a simple regression `lm(y~x)` by plotting the _data_ and adding `geom_smooth(method=lm)`, now that we are working with multiple regression in order to visualise our results we should think of it as plotting the _model_ (and we can add the data if desired).   -->
<!-- ::: -->
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Optional: Interactions and Sum Contrasts
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>When we have categorical predictors, our choice of contrasts coding changes the bits that we’re getting our of our model.</p>
<p>Suppose we have a 2x2 design (condition A and B, in groups 1 and 2):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sumplot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sumplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15_interactions_files/figure-html/fig-sumplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sumplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Categorical x Categorical Interaction plot
</figcaption>
</figure>
</div>
</div>
</div>
<p>When we are using the default contrasts coding (treatment - see <a href="14_catpred.html#contrasts" target="_blank">Chapter 14 #contrasts</a>) in R, then our coefficients for the individual predictors represent moving between the dots in <a href="#fig-sumplot" class="quarto-xref">Figure&nbsp;7</a>.</p>
<pre><code>Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            1.9098     0.1759  10.855  &lt; 2e-16 ***
conditionB             1.1841     0.2488   4.759 5.65e-06 ***
grouping2             -1.6508     0.2488  -6.635 1.09e-09 ***
conditionB:grouping2  -2.1627     0.3519  -6.146 1.15e-08 ***
---</code></pre>
<ul>
<li>The intercept is the red circle in <a href="#fig-sumplot" class="quarto-xref">Figure&nbsp;7</a>.<br>
</li>
<li>The coefficient for condition is the difference between the red circle and the red triangle in <a href="#fig-sumplot" class="quarto-xref">Figure&nbsp;7</a>.<br>
</li>
<li>The coefficient for grouping is the difference between the red circle and the blue circle in <a href="#fig-sumplot" class="quarto-xref">Figure&nbsp;7</a>.<br>
</li>
<li>The interaction coefficient is the difference from the slope of the red line to the slope of the blue line.</li>
</ul>
<p>However, when we change to using sum contrasts, we’re switching where zero is in our model. So if we change to sum contrasts (here we’ve changed <strong>both</strong> predictors to using sum contrasts), then we end up estimating the effect of each predictor averaged across the other.</p>
<pre><code>Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           1.13577    0.08796  12.912  &lt; 2e-16 ***
conditionB            0.05141    0.08796   0.584     0.56    
grouping2            -1.36607    0.08796 -15.530  &lt; 2e-16 ***
conditionB:grouping2 -0.54066    0.08796  -6.146 1.15e-08 ***
---</code></pre>
<ul>
<li>The intercept is the grey X in <a href="#fig-sumplot2" class="quarto-xref">Figure&nbsp;8</a>.<br>
</li>
<li>The coefficient for condition is the difference between the grey X and the grey triangle in <a href="#fig-sumplot2" class="quarto-xref">Figure&nbsp;8</a>.<br>
</li>
<li>The coefficient for grouping is the difference between the grey X and the blue line in <a href="#fig-sumplot2" class="quarto-xref">Figure&nbsp;8</a>.<br>
</li>
<li>The interaction coefficient is the difference from the slope of the grey line to slope of the blue line.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sumplot2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sumplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15_interactions_files/figure-html/fig-sumplot2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sumplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Visualisation of sum-contrasts for categorical x categorical interaction plot
</figcaption>
</figure>
</div>
</div>
</div>
<p>It can get quite confusing when we start switching up the contrasts, but it’s all just because we’re changing what “zero” means, and what “moving 1” means:</p>
<div class="panelset">
<section id="treatment-contrasts" class="level4 panel">
<h4 class="anchored" data-anchor-id="treatment-contrasts">Treatment contrasts</h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_interactions_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sum-contrasts" class="level4 panel">
<h4 class="anchored" data-anchor-id="sum-contrasts">Sum contrasts</h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_interactions_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Optional Extra: Getting non-linear
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You might be noticing that when we start talking about our regression surface “twisting” (e.g.&nbsp;in <a href="#fig-i.contcont" class="quarto-xref">Figure&nbsp;4</a>), we’re starting to see curves in our model.</p>
<p>We can model <em>curves</em> in a “linear” model!?</p>
<p>An interaction does in a sense introduce non-linearity to our thinking, because there we no longer think of a linear effect of <span class="math inline">\(x_1\)</span> (it “depends on” <span class="math inline">\(x_2\)</span>). This a little bit of a trick, because ultimately our model is still linear - we are estimating our outcome <span class="math inline">\(y\)</span> as the <em>linear combination</em> of a set of predictors. In the model <span class="math inline">\(y = b_0 + b_1 \cdot x_1 + b_2 \cdot x_2 + b_3 \cdot x_1 \cdot x_2\)</span>, the adjustment that we make <span class="math inline">\(b_3\)</span> to each of the coefficients <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> is a constant.</p>
<p>We can even exploit this to model more clearly “non-linear” associations, such as the age and height example below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-nonlin" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nonlin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15_interactions_files/figure-html/fig-nonlin-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nonlin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Two linear models, one with a quadratic term (right)
</figcaption>
</figure>
</div>
</div>
</div>
<p>We will cover this a lot more in the multivariate stats course, so don’t worry too much about it right now.<br>
However, it’s useful as a means of seeing how we can extend linear models to fit these sort of relationships. In the model on the right of <a href="#fig-nonlin" class="quarto-xref">Figure&nbsp;9</a>, the model returns three coefficients:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 28.09831    2.88606   9.736 4.99e-16 ***
age         18.04500    0.88602  20.366  &lt; 2e-16 ***
I(age^2)    -0.71034    0.05299 -13.406  &lt; 2e-16 ***</code></pre>
</div>
</div>
<p>It is estimating a persons’ height as:</p>
<ul>
<li>an intercept of 28.1 (the estimated height of a newborn baby of age 0)</li>
<li>plus 18.04 cm for every year of age they have</li>
<li>plus -0.71 cm for every year of age they have, squared.</li>
</ul>
<p>So for a 4 year old, the estimated height is:</p>
<p><span class="math display">\[
height = 28.1 + (18.04 \times 4) + (-0.71 \times 4^2) = 88.9
\]</span> and for a 10 year old, it is:</p>
<p><span class="math display">\[
height = 28.1 + (18.04 \times 10) + (-0.71 \times 10^2) = 138.1
\]</span> We can see how the quadratic “<span class="math inline">\(\text{age}^2\)</span> term has a larger (negative) effect as age increases (for the 4 year old it makes the estimated height <span class="math inline">\(-0.71 \times 4^2 = -11.4\)</span> lower, and for the 10 year old it makes the estimated height <span class="math inline">\(-0.71 \times 10^2 = -71\)</span> lower). This captures the plateauing of heights as children get older.</p>
</div>
</div>
</div>
<!-- # Optional: further exploration -->
<!-- ## Simple Slopes -->
<!-- we've kind of already done it visually.   -->
<!-- plot the slope of y~x1 for certain values of x2.   -->
<!-- we've done this visually, but it would be nice to get out a "is y~x1 significant when x2 = ?"   -->
<!-- ## Johnson Neyman -->


<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<div id="exercise-loading-indicator" class="exercise-loading-indicator d-none d-flex align-items-center gap-2">
<div id="exercise-loading-status" class="d-flex gap-2">

</div>
<div class="spinner-grow spinner-grow-sm">

</div>
</div>
<script type="vfs-file">
W10=
</script>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>This example comes from Ian Hajnosz, who previously tutored on USMR<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>And vice versa! It is also the adjustment we make to the slope of wellbeing with “relationship quality”, as we move 1 up in “time spent with partner”<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>This example comes from Otto Jutila, who previously tutored on USMR<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>This example comes from Tia Gong, who previously tutored on USMR<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>dotted is a good way to indicate that there is no data across that line - it is linking two categories. Martin disagrees and thinks you should never have lines<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script>



/* update total correct if #webex-total_correct exists */

update_total_correct = function() {

  console.log("webex: update total_correct");



  var t = document.getElementsByClassName("webex-total_correct");

  for (var i = 0; i < t.length; i++) {

    p = t[i].parentElement;

    var correct = p.getElementsByClassName("webex-correct").length;

    var solvemes = p.getElementsByClassName("webex-solveme").length;

    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;

    var selects = p.getElementsByClassName("webex-select").length;



    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";

  }

}



/* webex-solution button toggling function */

b_func = function() {

  console.log("webex: toggle hide");



  var cl = this.parentElement.classList;

  if (cl.contains('open')) {

    cl.remove("open");

  } else {

    cl.add("open");

  }

}



/* check answers */

check_func = function() {

  console.log("webex: check answers");



  var cl = this.parentElement.classList;

  if (cl.contains('unchecked')) {

    cl.remove("unchecked");

    this.innerHTML = "Hide Answers";

  } else {

    cl.add("unchecked");

    this.innerHTML = "Show Answers";

  }

}



/* function for checking solveme answers */

solveme_func = function(e) {

  console.log("webex: check solveme");



  var real_answers = JSON.parse(this.dataset.answer);

  var my_answer = this.value;

  var cl = this.classList;

  if (cl.contains("ignorecase")) {

    my_answer = my_answer.toLowerCase();

  }

  if (cl.contains("nospaces")) {

    my_answer = my_answer.replace(/ /g, "")

  }



  if (my_answer == "") {

    cl.remove("webex-correct");

    cl.remove("webex-incorrect");

  } else if (real_answers.includes(my_answer)) {

    cl.add("webex-correct");

    cl.remove("webex-incorrect");

  } else {

    cl.add("webex-incorrect");

    cl.remove("webex-correct");

  }



  // match numeric answers within a specified tolerance

  if(this.dataset.tol > 0){

    var tol = JSON.parse(this.dataset.tol);

    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)

    if (matches.reduce((a, b) => a + b, 0) > 0) {

      cl.add("webex-correct");

    } else {

      cl.remove("webex-correct");

    }

  }



  // added regex bit

  if (cl.contains("regex")){

    answer_regex = RegExp(real_answers.join("|"))

    if (answer_regex.test(my_answer)) {

      cl.add("webex-correct");

    }

  }



  update_total_correct();

}



/* function for checking select answers */

select_func = function(e) {

  console.log("webex: check select");



  var cl = this.classList



  /* add style */

  cl.remove("webex-incorrect");

  cl.remove("webex-correct");

  if (this.value == "answer") {

    cl.add("webex-correct");

  } else if (this.value != "blank") {

    cl.add("webex-incorrect");

  }



  update_total_correct();

}



/* function for checking radiogroups answers */

radiogroups_func = function(e) {

  console.log("webex: check radiogroups");



  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');

  var cl = checked_button.parentElement.classList;

  var labels = checked_button.parentElement.parentElement.children;



  /* get rid of styles */

  for (i = 0; i < labels.length; i++) {

    labels[i].classList.remove("webex-incorrect");

    labels[i].classList.remove("webex-correct");

  }



  /* add style */

  if (checked_button.value == "answer") {

    cl.add("webex-correct");

  } else {

    cl.add("webex-incorrect");

  }



  update_total_correct();

}



window.onload = function() {

  console.log("webex onload");

  /* set up solution buttons */

  var buttons = document.getElementsByTagName("button");



  for (var i = 0; i < buttons.length; i++) {

    if (buttons[i].parentElement.classList.contains('webex-solution')) {

      buttons[i].onclick = b_func;

    }

  }



  var check_sections = document.getElementsByClassName("webex-check");

  console.log("check:", check_sections.length);

  for (var i = 0; i < check_sections.length; i++) {

    check_sections[i].classList.add("unchecked");



    let btn = document.createElement("button");

    btn.innerHTML = "Show Answers";

    btn.classList.add("webex-check-button");

    btn.onclick = check_func;

    check_sections[i].appendChild(btn);



    let spn = document.createElement("span");

    spn.classList.add("webex-total_correct");

    check_sections[i].appendChild(spn);

  }



  /* set up webex-solveme inputs */

  var solveme = document.getElementsByClassName("webex-solveme");



  for (var i = 0; i < solveme.length; i++) {

    /* make sure input boxes don't auto-anything */

    solveme[i].setAttribute("autocomplete","off");

    solveme[i].setAttribute("autocorrect", "off");

    solveme[i].setAttribute("autocapitalize", "off");

    solveme[i].setAttribute("spellcheck", "false");

    solveme[i].value = "";



    /* adjust answer for ignorecase or nospaces */

    var cl = solveme[i].classList;

    var real_answer = solveme[i].dataset.answer;

    if (cl.contains("ignorecase")) {

      real_answer = real_answer.toLowerCase();

    }

    if (cl.contains("nospaces")) {

      real_answer = real_answer.replace(/ /g, "");

    }

    solveme[i].dataset.answer = real_answer;



    /* attach checking function */

    solveme[i].onkeyup = solveme_func;

    solveme[i].onchange = solveme_func;



    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")

  }



  /* set up radiogroups */

  var radiogroups = document.getElementsByClassName("webex-radiogroup");

  for (var i = 0; i < radiogroups.length; i++) {

    radiogroups[i].onchange = radiogroups_func;

  }



  /* set up selects */

  var selects = document.getElementsByClassName("webex-select");

  for (var i = 0; i < selects.length; i++) {

    selects[i].onchange = select_func;

    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")

  }



  update_total_correct();

}



</script>

<script>

if (window.location.href.includes('displayall')) {

  document.body.id = 'displayall';

} else {

  document.body.id = 'progressive';

}

</script>

<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<script type="module">
if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
window._ojs.paths.runtimeToDoc = "../..";
window._ojs.paths.runtimeToRoot = "../..";
window._ojs.paths.docToRoot = "";
window._ojs.selfContained = false;
window._ojs.runtime.interpretFromScriptTags();
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>