project:
  output-dir: _output

subtitle: "Univariate Statistics and Methodology using R"
author: "Martin Corley"
institute:
  - "Psychology, PPLS"
  - "University of Edinburgh"
format:
  revealjs:
    theme: [default, _theme/mystyle.scss]
    css: _theme/style.css
    slide-number: true
    preview-links: auto
    include-after-body: _theme/clean_title_page.html
    callout-appearance: simple
    code-line-numbers: false
    code-overflow: wrap
    code-annotations: hover
    code-copy: false
revealjs-plugins:
  - attribution
  - appearance
highlight-style: breeze
title-slide-attributes:
  data-background-color: "#FCBB06"
  data-background-image: _theme/img/logo.svg
  data-background-size: 25%
  data-background-position: 2% 2%
execute:
  warning: false
  echo: true

