project:
  output-dir: _output

subtitle: "Univariate Statistics and Methodology using R"
author: "Martin Corley"
institute:
  - "Psychology, PPLS"
  - "University of Edinburgh"
format:
  revealjs:
    theme: [default, theme/mystyle.scss]
    css: theme/colours.css
    slide-number: true
    preview-links: auto
    include-after-body: theme/clean_title_page.html
    callout-appearance: simple
    code-overflow: wrap
    code-annotations: hover
    code-copy: false
highlight-style: breeze
title-slide-attributes:
  data-background-color: "#FCBB06"
  data-background-image: theme/logo.svg
  data-background-size: 25%
  data-background-position: 2% 2%
execute: 
  warning: false
  echo: true


