---
title: "Survey Results"
author: uoepsy.github.io
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
require(tidyverse)
require(googlesheets4)
survdf <- read_sheet("1JacU9_yb9lt9FaHeiblZTw4vvFwLVOaCOiUIVdzmoPQ")
survdf %>% 
  select(birthdaymonth, height, eyecolour, three_words) %>%
  write.csv(.,"usmr_surveyresponse.csv",row.names = FALSE)

tibble(
  birthdaymonth = sample(tolower(format(ISOdate(2004,1:12,1),"%b")), 90, replace=T),
  height = rnorm(90, 160, 10),
  eyecolour = sample(c("brown","blue","hazel","amber","green","gray","other"), 90, replace=T, prob=c(.76,.1,.05,.05,.02, .01, .01))
) %>% write.csv(.,"usmr_surveyresponse.csv",row.names = FALSE)
```

# Where is everybody?
```{r echo=FALSE}
library(ggmap)
library(maptools)
library(maps)
survdfmap <- 
  survdf %>%
  mutate(
    lat = round(lat,1),
    lon = round(lon,1)
  ) %>% count(lat,lon)

mp <- NULL
mapWorld <- borders("world", colour="grey50", fill="grey50") # create a layer of borders
mp <- ggplot() +   mapWorld

mp <- mp+ geom_point(data = survdfmap, aes(x=lon, y=lat, size=n) ,color="blue") +
  theme_void()
mp
```

# In what month are people born?
```{r}
survdf %>% 
  ggplot(.,aes(x=birthdaymonth, fill=birthdaymonth)) +
  geom_bar() +
  scale_fill_viridis_d() + 
  theme_classic() +
  theme(legend.position = "none") +
  labs(x="- Birth Month - ")

ggsave(filename = "bmonth.png", last_plot())
```

# How tall are people?

```{r}
survdf %>% 
  ggplot(.,aes(x=height)) +
  geom_dotplot() + 
  theme_classic()

ggsave(filename = "heights.png", last_plot())
```

# What are your eye colours?  

```{r}
colvals = levels(factor(survdf$eyecolour))
survdf %>% 
  ggplot(.,aes(x=eyecolour, fill=eyecolour)) +
  geom_bar() +
  scale_fill_manual(values = colvals) + 
  theme_classic() + 
  theme(legend.position = "none")

ggsave(filename = "eyecolours.png", last_plot())
```


# Feelings about stats

```{r}
survdf %>% 
  ggplot(.,aes(x=stats, fill=stats)) +
  geom_bar() +
  theme_classic()

ggsave(filename = "stats.png", last_plot())
```

# Feelings about programming

```{r}
survdf %>% 
  ggplot(.,aes(x=programming, fill=programming)) +
  geom_bar() + 
  theme_classic()

ggsave(filename = "prog.png", last_plot())
```

# Previously used:

```{r}
survdf %>% select(starts_with("software")) %>% 
  summarise_all(~sum(!is.na(.))) %>% 
  pivot_longer(1:8, names_to="software",values_to="n") %>%
  mutate(
    software = gsub("software_","",software)
  ) %>% 
  ggplot(., aes(x = software, y = n, fill = software)) + 
  geom_col() +
  scale_fill_viridis_d() +
  theme_classic() + 
  theme(legend.position = "none") 

ggsave(filename = "software.png", last_plot())
```

# Three word descriptions

```{r}
require(tm)
require(SnowballC)
require(wordcloud)
comms <- survdf$three_words
comcorp <- Corpus(VectorSource(comms))
comcorp <-tm_map(comcorp,content_transformer(tolower))
toSpace <- content_transformer(function(x, pattern) { return (gsub(pattern, " ", x))})
comcorp <- tm_map(comcorp, toSpace, "-")
comcorp <- tm_map(comcorp, toSpace, "'")
comcorp <- tm_map(comcorp, toSpace, "’")
comcorp <- tm_map(comcorp, toSpace, '"')
comcorp <- tm_map(comcorp, removePunctuation)
comcorp <- tm_map(comcorp, removeNumbers)
comcorp <- tm_map(comcorp, removeWords, stopwords("english"))
comcorp <- tm_map(comcorp, stripWhitespace)
comcorp <- tm_map(comcorp,stemDocument)
myStopwords <- c("can", "say","one","way","use",
                     "also","howev","tell","will",
                     "much","need","take","tend","even",
                     "like","particular","rather","said",
                     "get","well","make","ask","come","end",
                     "first","two","help","often","may",
                     "might","see","someth","thing","point",
                     "post","look","right","now","think","‘ve ",
                     "‘re ","anoth","put","set","new","good",
                     "want","sure","kind","larg","yes,","day","etc",
                     "quit","sinc","attempt","lack","seen","awar",
                     "littl","ever","moreov","though","found","abl",
                     "enough","far","earli","away","achiev","draw",
                     "last","never","brief","bit","entir","brief",
                     "great","lot")
comcorp <- tm_map(comcorp, removeWords, myStopwords)
dtm <- DocumentTermMatrix(comcorp)
#collapse matrix by summing over columns
freq <- colSums(as.matrix(dtm))
#length should be total number of terms
#create sort order (descending)
ord <- order(freq,decreasing=TRUE)
#List all terms in decreasing order of freq and write to disk
d <- data.frame(word = names(freq), freq=freq)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
              max.words=200, random.order=FALSE, rot.per=0.35, 
              colors=brewer.pal(8, "Dark2"))


```

