project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!archive_2122/*"
  output-dir: ../docs/WIP/labs/

website:
  title: "USMR"
  navbar:
    left:
      - text: "Week 1"
        menu:
        - text: "Reading 1A: First look at R/RStudio"
          href: 01a_R.html
        - text: "Reading 1B: More R: Basic Data Skills"
          href: 01b_data.html
        - text: "Exercises: Intro R"
          href: 01_ex.html
      - text: "Week 2"
        menu:
        - text: "Reading 2A: Measurements & Distributions"
          href: 02a_measurement.html
        - text: "Reading 2B: Sampling & Curves"
          href: 02b_sampling.html
        - text: "Exercises: More R; Estimates & Intervals"
          href: 02_ex.html
      - text: "Week 3"
        menu: 
        - text: "Reading 3A: Foundations of Inference"
          href: 03a_inference.html
        - text: "Reading 3B: Practical Inference"
          href: 03b_inference2.html
        - text: "Exercises: "
          href: 03_ex.html
      - text: "Week 4"
        menu: 
        - text: "Exercises: Chi-Square Tests"
          href: 04_ex.html
        - text: "Reading 4A: Revisiting NHST"
          href: 04b_revistnhst.html
      - text: "Week 5"
        menu: 
        - text: "Reading 5A: Covariance & Correlation"
          href: 05a_covcor.html
        - text: "Exercises: Cov, Cor, Models"
          href: 05_ex.html
      - text: "Week 7"
        menu: 
        - text: "Reading 7A: Simple Linear Regression"
          href: 07a_slr.html
        - text: "Exercises: Simple Linear Regression & More Data Wrangling"
          href: 07_ex.html
      - text: "Week 8"
        menu: 
        - text: "Reading 8A: Multiple Linear Regression"
          href: 08a_mlr.html
        - text: "Exercises"
          href: ""
      - text: "Week 9"
        menu: 
        - text: "Reading 9A: More Regression"
          href: ""
        - text: "Exercises"
          href: ""

format:
  html:
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: "assets/toggling.html"
    number-sections: false


