{
  "hash": "74e8939db519c6dbede999744b614a1e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercises: Multiple Regression\"\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n# More monkeys \n\n\n\n\n\n\n\n\n\n\n\n:::frame\n__Data: monkeytoys.csv__  \n\nAfter their recent study investigating how age is associated with inquisitiveness in monkeys (see [Week 5 Exercises](05_ex.html#monkey-exploration){target=\"_blank\"}) our researchers have become interested in whether primates show preferences for certain types of object - are they more interested in toys with moving parts, or with soft plush toys?  \n\nThey conduct another study (Bolton, Archer, Peng, Winther & Gandolfi, 2024^[Another fake study!]) in which they gave 119 monkeys each a different toy, and recorded the amount of time each monkey spent exploring their toy. Toys were categorised as either being 'mechanical' or 'soft'. Mechanical toys had several parts that could be manipulated, while soft toys did not. They also recorded the age of each monkey, and a few further attributes of each toy (its size and colour).  \n\nThe aim of this study is to investigate the following question:  \n\n> Do monkeys have a preference between soft toys vs toys with moving parts?\n\nThe data is available at [https://uoepsy.github.io/data/monkeytoys.csv](https://uoepsy.github.io/data/monkeytoys.csv){target=\"_blank\"} and contains the variables described in @tbl-monkeytoys\n\n\n\n::: {#tbl-monkeytoys .cell layout-align=\"center\" tbl-cap='Data dictionary for monkeytoys.csv'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xcjayeqbns\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xcjayeqbns table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xcjayeqbns thead, #xcjayeqbns tbody, #xcjayeqbns tfoot, #xcjayeqbns tr, #xcjayeqbns td, #xcjayeqbns th {\n  border-style: none;\n}\n\n#xcjayeqbns p {\n  margin: 0;\n  padding: 0;\n}\n\n#xcjayeqbns .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xcjayeqbns .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xcjayeqbns .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xcjayeqbns .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xcjayeqbns .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xcjayeqbns .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xcjayeqbns .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xcjayeqbns .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xcjayeqbns .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xcjayeqbns .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xcjayeqbns .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xcjayeqbns .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xcjayeqbns .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xcjayeqbns .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xcjayeqbns .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xcjayeqbns .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xcjayeqbns .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xcjayeqbns .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xcjayeqbns .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xcjayeqbns .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xcjayeqbns .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xcjayeqbns .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xcjayeqbns .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xcjayeqbns .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xcjayeqbns .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xcjayeqbns .gt_left {\n  text-align: left;\n}\n\n#xcjayeqbns .gt_center {\n  text-align: center;\n}\n\n#xcjayeqbns .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xcjayeqbns .gt_font_normal {\n  font-weight: normal;\n}\n\n#xcjayeqbns .gt_font_bold {\n  font-weight: bold;\n}\n\n#xcjayeqbns .gt_font_italic {\n  font-style: italic;\n}\n\n#xcjayeqbns .gt_super {\n  font-size: 65%;\n}\n\n#xcjayeqbns .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xcjayeqbns .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xcjayeqbns .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xcjayeqbns .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xcjayeqbns .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xcjayeqbns .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xcjayeqbns .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xcjayeqbns .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xcjayeqbns div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Monkey Name</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age of monkey in years</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">obj_type</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Type of novel object given (mechanical / soft)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">obj_colour</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Main colour of object (red / green / blue)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">obj_size</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Size of object in cm (length of largest dimension of the object)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">exploration_time</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Time (in minutes) spent exploring the object</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nFit a simple linear model examining whether `exploration_time` depends on the type of object given to monkeys (`obj_type`).  \n\nMake a plot too if you want!  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThere's nothing new here. It's just `lm(outcome ~ predictor)`.  \n\nFor the plot, try a boxplot maybe? or even a violin plot if you're feeling adventurous!  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonkeytoys <-  read_csv(\"https://uoepsy.github.io/data/monkeytoys.csv\")\n\n\nmodel1 <- lm(exploration_time ~ obj_type, data = monkeytoys)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = exploration_time ~ obj_type, data = monkeytoys)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.5361 -2.8155  0.2639  2.7492 11.2639 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    9.2361     0.5470  16.884   <2e-16 ***\nobj_typesoft  -1.2705     0.7835  -1.622    0.108    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.272 on 117 degrees of freedom\nMultiple R-squared:  0.02198,\tAdjusted R-squared:  0.01362 \nF-statistic: 2.629 on 1 and 117 DF,  p-value: 0.1076\n```\n\n\n:::\n:::\n\n\n\n\nFrom this, we would conclude that monkeys do not significantly differ in how much time they spend exploring one type of toy over another (mechanical or soft).  \n\nLet's go wild and put a boxplot _on top of_ a violin plot!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(monkeytoys, \n       aes(x=obj_type, y=exploration_time, \n           col=obj_type)) +\n  geom_violin() + \n  geom_boxplot(alpha=.3, width=.4)\n```\n\n::: {.cell-output-display}\n![](07_ex_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\nIs the distribution of ages of the monkeys with soft toys similar to those with mechanical toys?  \n\nIs there a way you could test this? \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nWe're wanting to know if age (continuous) is different between two groups (monkeys seeing soft toys and monkeys seeing moving toys). Anyone for $t$?  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(age ~ obj_type, data = monkeytoys)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  age by obj_type\nt = 4.2966, df = 116.97, p-value = 3.605e-05\nalternative hypothesis: true difference in means between group mechanical and group soft is not equal to 0\n95 percent confidence interval:\n 2.604953 7.059829\nsample estimates:\nmean in group mechanical       mean in group soft \n                15.57377                 10.74138 \n```\n\n\n:::\n:::\n\n\n\n\n:::int\nThe average age of monkeys with the soft toys is 10.7 years (SD = 6), and the average of those with the mechanical toys is 15.6 (SD = 6.2). This difference is significant as indicated by a Welch two-sample $t$-test ($t(117)=4.3, \\, p<0.001$).  \n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\n**Discuss:** What does this mean for our model of `exploration_time`? Remember - the researchers already discovered last week that younger monkeys tend to be more inquisitive about new objects than older monkeys are.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- If older monkeys spend less time exploring novel objects\n- And our group of monkeys with mechanical toys are older than the group with soft toys. \n- Then... \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nWe have reason to believe that older monkeys spend less time exploring novel objects. We discovered this last week.  \n\nBecause our group of monkeys with mechanical toys are of a different age than the group with soft toys, surely we can't discern whether any difference in `exploration_time` between the two types of toy is because of these age differences or because of the type of toy?  \n\n<a id='Kq5SmFeASyhw1TtTYj75YA' class='gie-single' href='http://www.gettyimages.com/detail/586024350' target='_blank' style='color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;'>Embed from Getty Images</a><script>window.gie=window.gie||function(c){(gie.q=gie.q||[]).push(c)};gie(function(){gie.widgets.load({id:'Kq5SmFeASyhw1TtTYj75YA',sig:'1fKQopDLlPOpG9cuEzA7G5fZuR_u8eWzlQV2GELvt2U=',w:'511px',h:'338px',items:'586024350',caption: true ,tld:'com',is360: false })});</script><script src='//embed-cdn.gettyimages.com/widgets.js' charset='utf-8' async></script>\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\nFit a model the association between exploration time and type of object while controlling for age.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- When we add multiple predictors in to `lm()`, it can sometimes matter what order we put them in (e.g. if we want to use `anova(model)` to do a quick series of incremental model comparisons as in [7A #shortcuts-for-model-comparisons](07a_mlr.html#shortcuts-for-model-comparisons){target=\"_blank\"}). Good practice is to put the thing you're interested in (the 'focal predictor') at the end, e.g.: `lm(outcome ~ covariates + predictor-of-interest)`    \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel2 <- lm(exploration_time ~ age + obj_type, data = monkeytoys)\n\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = exploration_time ~ age + obj_type, data = monkeytoys)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.3277 -2.2886  0.3889  2.3417  8.4889 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  13.98828    1.03058  13.573  < 2e-16 ***\nage          -0.30514    0.05808  -5.253 6.86e-07 ***\nobj_typesoft -2.74512    0.76092  -3.608 0.000457 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.856 on 116 degrees of freedom\nMultiple R-squared:  0.2099,\tAdjusted R-squared:  0.1963 \nF-statistic: 15.41 on 2 and 116 DF,  p-value: 1.159e-06\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\nThe thing we're interested in here is association between `exploration_time` and `obj_type`.  \nHow does it differ between the models we've created so far, and why?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- To quickly compare several models side by side, the `tab_model()` function from the **sjPlot** package can be quite useful, e.g. `tab_model(model1, model2, ...)`.  \n- alternatively, just use `summary()` on each model.  \n\n:::\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-1' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-1', 'sol-start-1')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-1\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sjPlot)\ntab_model(model1, model2)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">exploration time</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">exploration time</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7\">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">9.24</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">8.15&nbsp;&ndash;&nbsp;10.32</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">13.99</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">11.95&nbsp;&ndash;&nbsp;16.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">obj type [soft]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;1.27</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;2.82&nbsp;&ndash;&nbsp;0.28</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.108</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;2.75</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;4.25&nbsp;&ndash;&nbsp;-1.24</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">age</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.31</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.42&nbsp;&ndash;&nbsp;-0.19</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">119</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">119</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.022 / 0.014</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.210 / 0.196</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n  \nThe coefficient for `obj_type` is much bigger when we include `age` in the model, and it is significant!  \n\nIn the model without `age`, we're just comparing the two groups. We can see this in the left hand panel of the plot below - it's the difference between the two group means.  \nWhen we include `age` in the model, the coefficient for `obj_type` represents the difference in the heights of the two lines in the right hand panel below. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(patchwork)\np1 <- ggplot(monkeytoys, aes(x=obj_type, y=exploration_time,\n             col=obj_type))+\n  geom_jitter(width=.05)+\n  stat_summary(geom=\"pointrange\", fun.data = mean_cl_normal, \n               position = position_nudge(x=.14)) +\n  labs(subtitle=\"exp_time~obj_type\")+\n  scale_y_continuous(breaks=seq(0,22,2))+\n  guides(col=\"none\")\n\np2 <- broom::augment(model2, interval=\"confidence\") |>\n  ggplot(aes(x=age, col=obj_type))+\n  geom_point(aes(y=exploration_time))+\n  geom_line(aes(y=.fitted))+\n  geom_ribbon(aes(ymin=.lower,ymax=.upper,\n                  fill=obj_type),col=NA,alpha=.2)+\n  scale_y_continuous(breaks=seq(0,22,2))+\n  labs(subtitle=\"exp_time~age+obj_type\")\n\np1 + p2 \n```\n\n::: {.cell-output-display}\n![](07_ex_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\nPlot the *model estimated* difference in exploration time for each object type.  \n\nTo do this, you'll need to create a little data frame for plotting, then give that to the `augment()` function from the **broom** package. This will then give us the model fitted value and the confidence interval, which we can plot!    \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- An example of this whole process is in [7A#model-visualisations](07a_mlr.html#model-visualisations){target=\"_blank\"}.  \n  - The example has a continuous predictor, so we plotted a line and a ribbon. An alternative for a categorical predictor might be a `geom_pointrange()`.  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\nWe've split this solution in to parts so that you can have a go at some bits without seeing it all at once.  \n\n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution Part 1 - make a dataframe</button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\nHere's our dataframe to add model estimated values to:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplotdat <- data.frame(\n  obj_type = c(\"soft\",\"mechanical\"),\n  age = mean(monkeytoys$age)\n)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-3' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution Part 2 - use broom::augment</button></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\nThis gives us our estimates and intervals:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(broom)\naugment(model2, newdata = plotdat, interval=\"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  obj_type     age .fitted .lower .upper\n  <chr>      <dbl>   <dbl>  <dbl>  <dbl>\n1 soft        13.2    7.21   6.17   8.25\n2 mechanical  13.2    9.95   8.94  11.0 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-4' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution Part 3 - into ggplot!</button></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naugment(model2, newdata = plotdat, interval=\"confidence\") |>\n  ggplot(aes(x=obj_type,y=.fitted))+\n  geom_pointrange(aes(ymin=.lower,ymax=.upper))\n```\n\n::: {.cell-output-display}\n![](07_ex_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\nAre other aspects of the toys (their size and colour) also associated with more/less exploration time?  \n\nWe can phrase this as \"do size and colour explain additional variance in exploration time?\". How might we test such a question? \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- We basically just want to add these new predictors into our model.  \n- Don't worry about interpreting the coefficients right now (we'll talk more about categorical predictors next week), but we can still test whether the inclusion of size and colour improve our model! (see [7A#model-comparisons](07a_mlr.html#model-comparisons){target=\"_blank\"}).  \n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\nThis is our current model: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel2 <- lm(exploration_time ~ age + obj_type, data = monkeytoys)\n```\n:::\n\n\n\nAnd we can add the two colour and size variables:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel3 <- lm(exploration_time ~ age + obj_type + obj_colour +\n               obj_size, data = monkeytoys)\n```\n:::\n\n\n\n\nLet's compare them:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(model2, model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: exploration_time ~ age + obj_type\nModel 2: exploration_time ~ age + obj_type + obj_colour + obj_size\n  Res.Df    RSS Df Sum of Sq      F   Pr(>F)   \n1    116 1725.2                                \n2    113 1546.7  3    178.47 4.3464 0.006148 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n:::int\nAfter accounting for differences due to age and type of object (mechanical vs soft), other features of objects - size (cm) and colour (red/green/blue) - were found to significantly explain variation in the time monkeys spent exploring those objects ($F(3,113)=4.35, \\, p=0.0061$). \n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Social Media Use\n\n\n\n\n\n\n\n\n\n:::frame\n__Data: socmedmin.csv__  \n\n> Is more social media use associated with more happiness?  \n\n77 participants completed a short online form that included a questionnaire (9 questions) to get a measure of their happiness. Information was also recorded on their age, the number of minutes per day spent using social media, and the number of hours per day spent having face-to-face interactions.\n\nThe data is available at [https://uoepsy.github.io/data/socmedmin.csv](https://uoepsy.github.io/data/socmedmin.csv){target=\"_blank\"}\n\n\n\n\n::: {#tbl-smmdict .cell layout-align=\"center\" tbl-cap='Data Dictionary: socmedmin.csv'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xtwsoarzoj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xtwsoarzoj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xtwsoarzoj thead, #xtwsoarzoj tbody, #xtwsoarzoj tfoot, #xtwsoarzoj tr, #xtwsoarzoj td, #xtwsoarzoj th {\n  border-style: none;\n}\n\n#xtwsoarzoj p {\n  margin: 0;\n  padding: 0;\n}\n\n#xtwsoarzoj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xtwsoarzoj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xtwsoarzoj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xtwsoarzoj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xtwsoarzoj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xtwsoarzoj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xtwsoarzoj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xtwsoarzoj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xtwsoarzoj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xtwsoarzoj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xtwsoarzoj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xtwsoarzoj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xtwsoarzoj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xtwsoarzoj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xtwsoarzoj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtwsoarzoj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xtwsoarzoj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xtwsoarzoj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xtwsoarzoj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtwsoarzoj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xtwsoarzoj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtwsoarzoj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xtwsoarzoj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtwsoarzoj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xtwsoarzoj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtwsoarzoj .gt_left {\n  text-align: left;\n}\n\n#xtwsoarzoj .gt_center {\n  text-align: center;\n}\n\n#xtwsoarzoj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xtwsoarzoj .gt_font_normal {\n  font-weight: normal;\n}\n\n#xtwsoarzoj .gt_font_bold {\n  font-weight: bold;\n}\n\n#xtwsoarzoj .gt_font_italic {\n  font-style: italic;\n}\n\n#xtwsoarzoj .gt_super {\n  font-size: 65%;\n}\n\n#xtwsoarzoj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xtwsoarzoj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xtwsoarzoj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xtwsoarzoj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xtwsoarzoj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xtwsoarzoj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xtwsoarzoj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xtwsoarzoj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xtwsoarzoj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Name</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Age (years)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">happy</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Happiness Score (sum of 9 likert questions each scored 1-5)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">smm</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Social Media Use (minutes per day)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">f2f</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Face-to-face interactions (hours per day)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\nRead in the data and have a look around. \n\nData often doesn't come to us in a neat format. Something here is a bit messy, so you'll need to figure out how to tidy it up.\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nIs every variable of the right type (numeric, character, factor etc)? If not, we'll probably want to convert any that aren't the type we want.  \n\nBe careful not to lose data when we convert things. Note that R cannot do this:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.numeric(\"20 minutes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n:::\n\n\n\n\nSo maybe some combination of `as.numeric()` and `gsub()` might work? (see [6A #dealing-with-character-strings](06_wt.html#dealing-with-character-strings){target=\"_blank\"}) \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-5' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  Solution Part 1 - identify the problem</button></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsmmdat <- read_csv(\"https://uoepsy.github.io/data/socmedmin.csv\")\n```\n:::\n\n\n\n\nNote that the `smm` variable seems to be a character..  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(smmdat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  name       age happy smm           f2f\n  <chr>    <dbl> <dbl> <chr>       <dbl>\n1 Brittany    26    18 100 minutes  1   \n2 Symone      16    11 55           0.5 \n3 Tiffany     35    30 95           1.5 \n4 Elberta     20    27 90           1.75\n5 Riley       29    21 60           0.75\n6 Lateefa     28    16 40           0.5 \n```\n\n\n:::\n:::\n\n\n\nwe could just convert it all to numeric by using `as.numeric()`: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.numeric(smmdat$smm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  NA  55  95  90  60  40 100  65  55  NA  NA  95  NA  85  75  70  80  55  70\n[20]  95  75  65 130  50  80  45  75  85  60  60  75 110  60 120  75  55  95  40\n[39] 105  95  45 135  75 120 100  60  85  50  35  60  55  60  75  85  55 115  45\n[58]  40  60  30  55 125  75  60 105 130  60  70 100  80  75  85  45  90  55  95\n[77]  75\n```\n\n\n:::\n:::\n\n\n\n\nNote that this has introduced some `NA` values though! We've lost some data:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum(is.na(smmdat$smm)) # NAs in original data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(as.numeric(smmdat$smm))) # NAs in numeric-converted data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n:::\n\n\n\n\nIf we look carefully, these entries that we are losing are all slightly different from the rest. They all have \" minutes\" in them, rather than just the minutes.. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsmmdat$smm[is.na(as.numeric(smmdat$smm))]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"100 minutes\" \"80 minutes\"  \"90 minutes\"  \"105 minutes\"\n```\n\n\n:::\n:::\n\n\n\n\nAnd when we ask R to make \"20 minutes\" into a number, it isn't clever enough to recognise that it is a number, so it just turns it into `NA`:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.numeric(\"20 minutes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-6' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  Solution Part 2 - figure out a fix</button></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\n\nSo we need to _first_ remove the \" minutes\" bit, and _then_ change to numeric.  \nWe can use `gsub()` to substitute \" minutes\" with \"\" (i.e. nothingness):\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngsub(\" minutes\", \"\", \"20 minutes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"20\"\n```\n\n\n:::\n:::\n\n\n\nAnd we can then turn _that_ into numbers.. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.numeric(gsub(\" minutes\", \"\", \"20 minutes\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-7' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  Solution Part 3 - implement!</button></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\n\nNow that we've figured out how to convert it, I'm just going to overwrite the `smm` variable, rather than creating a new one.  \n\n::::panelset\n:::panel\n#### base R\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsmmdat$smm <- as.numeric(gsub(\" minutes\", \"\", smmdat$smm))\n```\n:::\n\n\n\n:::\n:::panel\n#### tidyverse\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsmmdat <- smmdat |> \n  mutate(\n    smm = as.numeric(gsub(\" minutes\", \"\", smm))\n  )\n```\n:::\n\n\n\n:::\n::::\n\nOkay, now the `smm` variable is numeric, and we haven't lost any datapoints!\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(smmdat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     name                age            happy            smm        \n Length:77          Min.   :12.00   Min.   : 6.00   Min.   : 30.00  \n Class :character   1st Qu.:22.00   1st Qu.:19.00   1st Qu.: 60.00  \n Mode  :character   Median :27.00   Median :26.00   Median : 75.00  \n                    Mean   :27.09   Mean   :25.16   Mean   : 76.36  \n                    3rd Qu.:31.00   3rd Qu.:30.00   3rd Qu.: 95.00  \n                    Max.   :43.00   Max.   :47.00   Max.   :135.00  \n      f2f       \n Min.   :0.000  \n 1st Qu.:1.000  \n Median :1.500  \n Mean   :1.529  \n 3rd Qu.:2.000  \n Max.   :3.000  \n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\nSomething we haven't really come across until now is the importance of checking the _range_ (i.e. min and max) of our variables. \nThis is a good way to check for errors in the data (i.e. values that we shouldn't be able to obtain using our measurement tool).  \n\nCheck the range of the `happy` variable - does it look okay, based on the description of how it is recorded? \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- `min()`, `max()`, or even just `range()`!!  \n- If there are any observations you think have impossible values, then you could set them as NA for now (see [6A #impossible-values ](06_wt.html#impossible-values){target=\"_blank\"}).  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrange(smmdat$happy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  6 47\n```\n\n\n:::\n:::\n\n\n\nThe minimum is 6, and the maximum is 47.  \n\nBut our scores are based on the sum of 9 questions that can each score from 1 to 5. So surely that means the minimum someone could score would be 9, and the maximum they could score would be 45?  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsmmdat <- smmdat |>\n  mutate(\n    happy = ifelse(happy < 9 | happy > 45, NA, happy)\n  )\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\nFinally, we've got to a point where we can look at some descriptive statistics - e.g. mean and standard deviations for continuous variables, frequencies (counts) if there are any categorical variables.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nYou can do this the manual way, calculating it for each variable, but there are also lots of handy functions to make use of.  \n\n- `describe()` from the __psych__ package\n- `CreateTableOne()` from the __tableone__ package  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n::::panelset\n:::panel\n#### Tidyverse\n\nIn tidyverse, we could do this like:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsmmdat |> \n  summarise(\n    mean_age = mean(age),\n    sd_age = sd(age),\n    mean_happy = mean(happy, na.rm=TRUE),\n    sd_happy = sd(happy, na.rm=TRUE),\n    mean_smm = mean(smm),\n    sd_smm = sd(smm)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  mean_age sd_age mean_happy sd_happy mean_smm sd_smm\n     <dbl>  <dbl>      <dbl>    <dbl>    <dbl>  <dbl>\n1     27.1   6.62       25.1     6.71     76.4   24.5\n```\n\n\n:::\n:::\n\n\n\n\n:::\n:::panel\n#### psych::describe\n\nWe can use the `describe` function from the __psych__ package: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(psych)\ndescribe(smmdat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      vars  n  mean    sd median trimmed   mad min max range  skew kurtosis\nname*    1 77 37.90 21.81   38.0   37.87 28.17   1  75    74  0.00    -1.27\nage      2 77 27.09  6.62   27.0   27.00  7.41  12  43    31  0.11    -0.54\nhappy    3 75 25.12  6.71   26.0   25.11  7.41  11  38    27 -0.05    -0.83\nsmm      4 77 76.36 24.50   75.0   75.08 29.65  30 135   105  0.41    -0.52\nf2f      5 77  1.53  0.73    1.5    1.53  0.74   0   3     3 -0.03    -0.68\n        se\nname* 2.49\nage   0.75\nhappy 0.77\nsmm   2.79\nf2f   0.08\n```\n\n\n:::\n:::\n\n\n\n\n\n:::\n:::panel\n#### tableone\n\nThe tableone package will also be clever and give counts and percentages for categorical data like the `name` variable. However, names aren't something we really want to summarise, so it's easier just to give the function everything except the `name` variable.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tableone)\nCreateTableOne(data = smmdat |> select(-name) )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   \n                    Overall      \n  n                    77        \n  age (mean (SD))   27.09 (6.62) \n  happy (mean (SD)) 25.12 (6.71) \n  smm (mean (SD))   76.36 (24.50)\n  f2f (mean (SD))    1.53 (0.73) \n```\n\n\n:::\n:::\n\n\n\n\n:::\n::::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<!-- \n\n<div class='question-begin'>Question 11</div><div class='question-body'>\n\n -->\n<!-- Again, we're going to start with a one-predictor model.   -->\n\n<!-- Fit a simple linear regression model to address our research question (\"Is more social media use associated with more happiness?\").   -->\n\n<!-- Make a plot too.   -->\n\n<!-- What do you conclude?   -->\n\n\n<!-- ::: {.callout-tip collapse=\"true\"} -->\n<!-- #### Hints -->\n\n<!-- We're using `lm()` again.  -->\n\n<!-- To make a plot, because we just have a very simple one predictor model, we could just plot the data itself and then add `geom_smooth(method=lm)` to it to display the model.   -->\n\n\n<!-- ::: -->\n\n<!-- \n\n</div><p class=\"question-end\"></p>\n\n -->\n<!-- \n\n<div style=\"display:none;\">\n\n -->\n\n<!-- From the model below, we would conclude that more social media use is associated with more happiness. The coefficient from our model is positive (more social media = more happiness), and significantly different from zero.   -->\n\n<!-- ```{r} -->\n<!-- mod1 <- lm(happy ~ smm, smmdat) -->\n<!-- summary(mod1) -->\n<!-- ``` -->\n\n<!-- ```{r} -->\n<!-- ggplot(smmdat, aes(x=smm,y=happy))+ -->\n<!--   geom_point()+ -->\n<!--   geom_smooth(method=lm)+ -->\n<!--   labs(x=\"Social Media Usage (minutes per day)\", -->\n<!--        y=\"Happiness Score\") -->\n<!-- ``` -->\n\n<!-- \n\n</div><p class=\"solution-end\"></p>\n\n -->\n\n\n\n<div class='question-begin'>Question 12</div><div class='question-body'>\n\n\n\nFor our research question (\"Is more social media use associated with more happiness?\"), we could consider fitting the following model:  \n```\nlm(happy ~ smm, data = smmdat)\n```\n\n**But** is it not a bit more complicated than that? Surely there are lots of other things that are relevant? For instance, it's quite reasonable to assume that social media use is related to someone's age? It's also quite likely that happiness changes with age too. But that means that our coefficient of `happy ~ smm` could actually just be changes in happiness due to something else (like age)? Similarly, people who use social media might just be more sociable people (i.e. they might see more people in real life, and that might be what makes them happy).  \n\nEspecially in observational research (i.e. we aren't intervening and asking some people to use social media and others to not use it), figuring out the relevant association that we want can be incredibly tricky.  \n\nAs it happens, we _do_ have data on these participants' ages, and on the amount of time they spend having face-to-face interactions with people!  \n\nLook at how all these variables correlate with one another, and make some quick plots.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- You can give a data frame of numeric variables to `cor()` and it gives you all the correlations between pairs of variables in a \"correlation matrix\"  \n- if you want some quick pair-wise plots (not pretty, but useful!), try the `pairs.panels()` function from the __psych__ package.  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nHere is a correlation matrix. It shows the correlations between each pair of variables.  \nNote that the bit below the diagonal is the same as the bit above. The diagonal is always going to be all 1's, because a variable is always perfectly correlated with itself.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsmmdat |> \n  select(-name) |>\n  filter(!is.na(happy)) |>\n  cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              age     happy        smm         f2f\nage    1.00000000 0.4749254 -0.2426590 -0.02776556\nhappy  0.47492536 1.0000000  0.3135681  0.74264149\nsmm   -0.24265898 0.3135681  1.0000000  0.46924107\nf2f   -0.02776556 0.7426415  0.4692411  1.00000000\n```\n\n\n:::\n:::\n\n\n\n\nThe `pairs.panels()` function is a useful way to quickly explore the bivariate (two-variables) patterns in a dataset:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(psych)\nsmmdat |> \n  select(-name) |>\n  pairs.panels()\n```\n\n::: {.cell-output-display}\n![](07_ex_files/figure-html/unnamed-chunk-38-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 13</div><div class='question-body'>\n\n\nIs social media usage associated with happiness, after accounting for age and the number of face-to-face interactions?  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- This question can be answered in a couple of ways. You might be able to do some sort of model comparison, or you could look at the test of a coefficient.  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nWe could do this by fitting the model with `age` and `f2f` predicting `happy`, and then compare that to the model _also_ with `smm`:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod1 <- lm(happy ~ age + f2f, smmdat)\nmod2 <- lm(happy ~ age + f2f + smm, smmdat)\nanova(mod1, mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: happy ~ age + f2f\nModel 2: happy ~ age + f2f + smm\n  Res.Df    RSS Df Sum of Sq      F  Pr(>F)  \n1     72 674.67                              \n2     71 646.12  1    28.546 3.1368 0.08084 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nThis is testing the addition of **one** parameter (thing being estimated) to our model - the coefficient for `smm`.  \nWe can see that it is just one more parameter because the table abovw shows that the additional degrees of freedom taken up by `mod2` is 1 (the \"Df\" column, and the change in the \"Res.Df\" column).  \n\nSo we could actually just look at the test of that individual parameter, and whether it is different from zero. \nIt's the same:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = happy ~ age + f2f + smm, data = smmdat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.3208 -1.9972  0.1685  1.7089  7.5643 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -1.41597    2.10045  -0.674   0.5024    \nage          0.53031    0.05516   9.614 1.74e-14 ***\nf2f          6.42390    0.54145  11.864  < 2e-16 ***\nsmm          0.02953    0.01667   1.771   0.0808 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.017 on 71 degrees of freedom\n  (2 observations deleted due to missingness)\nMultiple R-squared:  0.8058,\tAdjusted R-squared:  0.7976 \nF-statistic: 98.23 on 3 and 71 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 14</div><div class='question-body'>\n\n\nPlot the model estimated association between social media usage and happiness.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThis follows just the same logic as we did for the monkeys!  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplotdat <- data.frame(\n  age = mean(smmdat$age), # mean age\n  f2f = mean(smmdat$f2f), # mean f2f interactions\n  smm = 0:150 # social media use from 0 to 150 mins\n)\n\naugment(mod2, newdata = plotdat, interval = \"confidence\") |>\n  ggplot(aes(x = smm, y = .fitted)) + \n  geom_line() + \n  geom_ribbon(aes(ymin = .lower, ymax = .upper), alpha=.3)+\n  labs(x = \"social media usage\\n(minutes per day)\",\n       y = \"Happiness Score\",\n       title = \"Happiness and social media usage\",\n       subtitle = \"controlling for age and IRL interactions\")\n```\n\n::: {.cell-output-display}\n![](07_ex_files/figure-html/unnamed-chunk-41-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Optional Extra</div><div class='question-body'>\n\n\n\nIn all the plots we have been making from our models, the other predictors in our model (e.g. `age` and `f2f` in this case) have been held at their mean.  \n\nWhat happens if you create a plot estimating the association between happiness and social media usage, but having `age` at 15, or 30, or 45?  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07_ex_files/figure-html/unnamed-chunk-42-1.png){fig-align='center' width=80% height=350px}\n:::\n:::\n\n\n\n\nThe **slope** doesn't change at all, but note that it moves up and down. This makes sense, because our model coefficients indicated that happiness goes up with age.  \nNote also that the uncertainty changes, and this is what we want - we have less data on people at age 45, or 15, so we are less confident in our estimates.  \n\nI'm going to use this space to show you a little trick that may come in handy. The function `expand_grid()` will take all combinations of the values you give it for each variable, and expand outwards:  \ne.g.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexpand_grid(\n  v1 = c(\"a\",\"b\"),\n  v2 = 1:4\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n  v1       v2\n  <chr> <int>\n1 a         1\n2 a         2\n3 a         3\n4 a         4\n5 b         1\n6 b         2\n7 b         3\n8 b         4\n```\n\n\n:::\n:::\n\n\n\n\nSo instead of creating lots of individual `plotdat` dataframes for each value of `age` 15, 30, and 45, we can create just one that contains all three. Then we can just deal with that in the ggplot.  \n\n::::panelset\n:::panel\n#### One-by-one  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplotdat1 <- data.frame(\n  age = 15,\n  f2f = mean(smmdat$f2f), \n  smm = 0:150 \n)\nplotdat2 <- data.frame(\n  age = 30,\n  f2f = mean(smmdat$f2f), \n  smm = 0:150 \n)\nplotdat3 <- data.frame(\n  age = 45,\n  f2f = mean(smmdat$f2f), \n  smm = 0:150 \n)\n\np1 <- augment(mod2, newdata = plotdat1, interval = \"confidence\") |>\n  ggplot(aes(x = smm, y = .fitted)) + \n  geom_line() + \n  geom_ribbon(aes(ymin = .lower, ymax = .upper), alpha=.3)+\n  ylim(5,45)\n\np2 <- augment(mod2, newdata = plotdat2, interval = \"confidence\") |>\n  ggplot(aes(x = smm, y = .fitted)) + \n  geom_line() + \n  geom_ribbon(aes(ymin = .lower, ymax = .upper), alpha=.3)+\n  ylim(5,45)\n\np3 <- augment(mod2, newdata = plotdat3, interval = \"confidence\") |>\n  ggplot(aes(x = smm, y = .fitted)) + \n  geom_line() + \n  geom_ribbon(aes(ymin = .lower, ymax = .upper), alpha=.3)+\n  ylim(5,45)\n\n# the patchwork package allows us to add plots together:\np1 + p2 + p3\n```\n\n::: {.cell-output-display}\n![](07_ex_files/figure-html/unnamed-chunk-44-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n:::\n:::panel\n#### All-in-one\n`\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplotdat <- \n  expand_grid(\n    age = c(15,30,45),\n    f2f = mean(smmdat$f2f),\n    smm = 0:150 \n  )\n\naugment(mod2, newdata = plotdat, interval = \"confidence\") |>\n  ggplot(aes(x = smm, y = .fitted)) + \n  geom_line() + \n  geom_ribbon(aes(ymin = .lower, ymax = .upper), alpha=.3) +\n  facet_wrap(~age)\n```\n\n::: {.cell-output-display}\n![](07_ex_files/figure-html/unnamed-chunk-45-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n:::\n::::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 15</div><div class='question-body'>\n\n\nHow many observations has our model been fitted to?  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nIt's not just the 77 people why have in the dataset.. \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nBecause we had those very happy and very unhappy people (`happy` variable was outside our range) that we replaced with `NA`, we have fewer bits of data to fit our model to.  \n\nThat's because `lm()` will default to something called \"listwise deletion\", which will remove any observation where any variable in the model (outcome or predictor) is missing. \n\nWe can see how many observations went into our model because we know how many residuals we have: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlength(residuals(mod2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 75\n```\n\n\n:::\n:::\n\n\n\n\nAnd we can also see it from the degrees of freedom at the bottom of the `summary()` output. We know that we have $n-k-1$ degrees of freedom (see [7A #the-f-statistic-a-joint-test](07a_mlr.html#the-f-statistic-a-joint-test){target=\"_blank\"}), and that is shown as 71 here. $k$ is the number of predictors, which we know is 3. So $n$ is 75!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mod2)\n```\n:::\n\n\n\n```\n...\nF-statistic: 98.23 on 3 and 71 DF,  p-value: < 2.2e-16\n```\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 16</div><div class='question-body'>\n\n\nCheck the assumptions of your model.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n[7B Assumptions & Diagnostics](07b_assumptdiag.html){target=\"_blank\"} shows how we can do this. We can rely on tests if we like, or we can do it visually through plots. Getting a good sense of \"what looks weird\" in these assumption plots is something that comes with time.  \n\n:::\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nHere are our plots..  \nThey don't look too bad _to me_ (you might feel differently!)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(mod2)\n```\n\n::: {.cell-output-display}\n![](07_ex_files/figure-html/unnamed-chunk-48-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# More RMarkdown/Quarto\n\n\n\n<div class='question-begin'>Question 17</div><div class='question-body'>\n\n\n\n\n1. Open a .Rmd or .qmd document, and delete all the template stuff.  \n    - Keep the code chunk at the top called \"setup\"  \n2. In the \"setup\" chunk, change it to `echo = FALSE`. This will make sure all code gets hidden from the final rendered document.  \n3. Make a new code chunk called \"analysis\", and for this chunk, set `include = FALSE`. This will make sure that the code in that chunk gets run, but does not actually produce any output.  \n4. Shove all our working analysis (below) in that 'analysis' code chunk.  \n5. Write a paragraph describing the analysis.  \n    - what type of model/analysis is being conducted?\n    - what is the outcome? the predictors? how are they smeasured?\n6. Write a paragraph highlighting the key results. Try to use inline R code. [This example](https://uoepsy.github.io/usmr/2324/misc/socmedmin.Rmd){target=\"_blank\"} may help.  \n7. In a new code chunk, create and show a plot. Make sure this code chunk is set to `include = TRUE`, because we _do_ want the output to show (leaving it blank will also work, because this is the default).  \n8. Click Knit! \n\n\n::: {.callout-note collapse=\"true\"}\n#### Study: Lie detectors\n\n\n\n\n\n\n\n\n\nLaw enforcement in some countries regularly rely on 'polygraph' tests as a form of 'lie detection'. These tests involve measuring heart rate, blood pressure, respiratory rate and sweat. However, there is very little evidence to suggest that these methods are remotely accurate in being able to determine whether or not someone is lying.  \n\nResearchers are interested in if peoples' heart rates during polygraph tests can be influenced by various pre-test strategies, including deep breathing, or closing their eyes. They recruited 142 participants (ages 22 to 64). Participants were told they were playing a game in which their task was to deceive the polygraph test, and they would receive financial rewards if they managed successfully. At the outset of the study, they completed a questionnaire which asked about their anxiety in relation to taking part. Participants then chose one of 4 strategies to prepare themselves for the test, each lasting 1 minute. These were \"do nothing\", \"deep breathing\", \"close your eyes\" or \"cough\"^[apparently coughing is a method of immediately lowering heart rate!]. The average heart rate of each participant was recorded during their test. \n\n\n\n\n\n::: {.cell layout-align=\"center\" tbl-cap='usmr_polygraph.csv data dictionary'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vqdjjwwtuv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vqdjjwwtuv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vqdjjwwtuv thead, #vqdjjwwtuv tbody, #vqdjjwwtuv tfoot, #vqdjjwwtuv tr, #vqdjjwwtuv td, #vqdjjwwtuv th {\n  border-style: none;\n}\n\n#vqdjjwwtuv p {\n  margin: 0;\n  padding: 0;\n}\n\n#vqdjjwwtuv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vqdjjwwtuv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vqdjjwwtuv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vqdjjwwtuv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vqdjjwwtuv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vqdjjwwtuv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vqdjjwwtuv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vqdjjwwtuv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vqdjjwwtuv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vqdjjwwtuv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vqdjjwwtuv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vqdjjwwtuv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vqdjjwwtuv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vqdjjwwtuv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vqdjjwwtuv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqdjjwwtuv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vqdjjwwtuv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vqdjjwwtuv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vqdjjwwtuv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqdjjwwtuv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vqdjjwwtuv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqdjjwwtuv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vqdjjwwtuv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqdjjwwtuv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqdjjwwtuv .gt_left {\n  text-align: left;\n}\n\n#vqdjjwwtuv .gt_center {\n  text-align: center;\n}\n\n#vqdjjwwtuv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vqdjjwwtuv .gt_font_normal {\n  font-weight: normal;\n}\n\n#vqdjjwwtuv .gt_font_bold {\n  font-weight: bold;\n}\n\n#vqdjjwwtuv .gt_font_italic {\n  font-style: italic;\n}\n\n#vqdjjwwtuv .gt_super {\n  font-size: 65%;\n}\n\n#vqdjjwwtuv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vqdjjwwtuv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vqdjjwwtuv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vqdjjwwtuv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vqdjjwwtuv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vqdjjwwtuv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vqdjjwwtuv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vqdjjwwtuv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vqdjjwwtuv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age of participant (years)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">anx</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Anxiety measure (Z-scored)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">strategy</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Pre-test Strategy (0 = do nothing, 1 = close eyes, 2 = cough, 3 = deep breathing)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">hr</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Average Heart Rate (bpm) during test</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n__Analysis__  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# load libraries\nlibrary(tidyverse)\nlibrary(psych)\n# read in the data\nliedf <- read_csv(\"https://uoepsy.github.io/data/usmr_polygraph.csv\")\n\n# there seems to be a 5 there.. \ntable(liedf$strategy)\n# the other variables look okay though\ndescribe(liedf)\npairs.panels(liedf)\n\n\nliedf <- liedf |> \n  filter(strategy!=5) |>\n  mutate(\n    # strategy is a factor. but currently numbers\n    # i'm going to give them better labels too.. \n    # to do this is need to tell factor() what \"levels\" to look for\n    # and then give it some \"labels\" to apply to those.\n    strategy = factor(strategy, \n                      levels = c(\"0\",\"1\",\"2\",\"3\"),\n                      labels = c(\"do nothing\", \"close eyes\",\n                                 \"cough\", \"deep breathing\")\n                      )\n  )\n\nliemod <- lm(hr ~ age + anx + strategy, data = liedf)\n\n# Does HR differ between strategies?\nanova(liemod)\n# the above is a shortcut for getting this comparison out:\nanova(\n  lm(hr ~ age + anx, data = liedf),\n  lm(hr ~ age + anx + strategy, data = liedf)\n)\n\n# i want a plot to show the HRs of different strategies.. \n# ??\n```\n:::\n\n\n\n\n\n:::\n\n\n\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n",
    "supporting": [
      "07_ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}