<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.587">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - 07A: Simple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-left')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-left')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 1</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html">
 <span class="dropdown-text">Reading 1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html">
 <span class="dropdown-text">Reading 1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 2</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html">
 <span class="dropdown-text">Reading 2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html">
 <span class="dropdown-text">Reading 2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 3</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html">
 <span class="dropdown-text">Reading 3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html">
 <span class="dropdown-text">Reading 3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html">
 <span class="dropdown-text">Exercises:</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 4</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04_ex.html">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revistnhst.html">
 <span class="dropdown-text">Reading 4A: Revisiting NHST</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 5</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li>
    <a class="dropdown-item" href="./05a_covcor.html">
 <span class="dropdown-text">Reading 5A: Covariance &amp; Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_ex.html">
 <span class="dropdown-text">Exercises: Cov, Cor, Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 7</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li>
    <a class="dropdown-item" href="./07a_slr.html">
 <span class="dropdown-text">Reading 7A: Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_ex.html">
 <span class="dropdown-text">Exercises: Simple Linear Regression &amp; More Data Wrangling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 8</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li>
    <a class="dropdown-item" href="./08a_mlr.html">
 <span class="dropdown-text">Reading 8A: Multiple Linear Regression</span></a>
  </li>  
        <li class="dropdown-header">Exercises</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 9</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li class="dropdown-header">Reading 9A: More Regression</li>
        <li class="dropdown-header">Exercises</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-research-question" id="toc-the-research-question" class="nav-link active" data-scroll-target="#the-research-question">The Research Question</a></li>
  <li><a href="#exploring-the-data" id="toc-exploring-the-data" class="nav-link" data-scroll-target="#exploring-the-data">Exploring the data</a></li>
  <li><a href="#fitting-a-linear-model" id="toc-fitting-a-linear-model" class="nav-link" data-scroll-target="#fitting-a-linear-model">Fitting a Linear Model</a></li>
  <li><a href="#interpreting-coefficients" id="toc-interpreting-coefficients" class="nav-link" data-scroll-target="#interpreting-coefficients">Interpreting coefficients</a></li>
  <li><a href="#interpreting-sigma" id="toc-interpreting-sigma" class="nav-link" data-scroll-target="#interpreting-sigma">Interpreting <span class="math inline">\(\sigma\)</span></a></li>
  <li><a href="#fitted-and-predicted-values" id="toc-fitted-and-predicted-values" class="nav-link" data-scroll-target="#fitted-and-predicted-values">Fitted and predicted values</a></li>
  <li><a href="#inference-for-regression-coefficients" id="toc-inference-for-regression-coefficients" class="nav-link" data-scroll-target="#inference-for-regression-coefficients">Inference for regression coefficients</a></li>
  <li><a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation">Model evaluation</a>
  <ul class="collapse">
  <li><a href="#partitioning-variance-rsquared" id="toc-partitioning-variance-rsquared" class="nav-link" data-scroll-target="#partitioning-variance-rsquared">Partitioning Variance: Rsquared</a></li>
  <li><a href="#testing-model-utility-f-statistic" id="toc-testing-model-utility-f-statistic" class="nav-link" data-scroll-target="#testing-model-utility-f-statistic">Testing Model Utility: <span class="math inline">\(F\)</span> Statistic</a></li>
  </ul></li>
  <li><a href="#binpred" id="toc-binpred" class="nav-link" data-scroll-target="#binpred">Binary predictors</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">07A: Simple Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>This walkthrough covers the basics of simple linear regression conducted in R.</p>
<p>Our data for this walkthrough is from an hypothetical study into income disparity for employees in a local authority. We’re interested in investigating the link between the level of education and an employee’s income. Those with more formal education seem to be better paid.</p>
<div class="frame">
<p><strong>Data: riverview.csv</strong></p>
<p>The riverview data, which come from <a href="https://methods.sagepub.com/book/applied-regression-an-introduction-second-edition">Lewis-Beck, 2015</a>, contain five attributes collected from a random sample of <span class="math inline">\(n=32\)</span> employees working for the city of Riverview, a hypothetical midwestern city in the US. The attributes include:</p>
<ul>
<li><code>education</code>: Years of formal education</li>
<li><code>income</code>: Annual income (in thousands of U.S. dollars)</li>
<li><code>seniority</code>: Years of seniority</li>
<li><code>gender</code>: Employee’s gender</li>
<li><code>male</code>: Dummy coded gender variable (0 = Female, 1 = Male)</li>
<li><code>party</code>: Political party affiliation</li>
</ul>
<p>The first six rows of the data are:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:center;"> education </th>
   <th style="text-align:center;"> income </th>
   <th style="text-align:center;"> seniority </th>
   <th style="text-align:center;"> gender </th>
   <th style="text-align:center;"> male </th>
   <th style="text-align:center;"> party </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 37.449 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> male </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> Democrat </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 26.430 </td>
   <td style="text-align:center;"> 9 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Independent </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 47.034 </td>
   <td style="text-align:center;"> 14 </td>
   <td style="text-align:center;"> male </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> Democrat </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 34.182 </td>
   <td style="text-align:center;"> 16 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Independent </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 25.479 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Republican </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 12 </td>
   <td style="text-align:center;"> 46.488 </td>
   <td style="text-align:center;"> 11 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Democrat </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The data is available at <a href="https://uoepsy.github.io/data/riverview.csv" target="_blank">https://uoepsy.github.io/data/riverview.csv.</a></p>
</div>
<p>We begin by loading the required libraries (probably just <strong>tidyverse</strong> for now), and reading in the riverview data to our R session.<br>
We’re going to name it <code>riverview</code> in our environment.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>riverview <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/riverview.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(riverview)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  education income seniority gender  male party      
      &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;      
1         8   37.4         7 male       1 Democrat   
2         8   26.4         9 female     0 Independent
3        10   47.0        14 male       1 Democrat   
4        10   34.2        16 female     0 Independent
5        10   25.5         1 female     0 Republican 
6        12   46.5        11 female     0 Democrat   </code></pre>
</div>
</div>
<section id="the-research-question" class="level1">
<h1>The Research Question</h1>
<p>Now we wouldn’t have time to interview everyone who works for the local authority so we would have to interview a sample, say 10%. We might carry out interviews and find that there is a link It is always important to keep in mind your research question. We shouldn’t simply explore all possible relationships in our dataset and then decide <em>post-hoc</em> on what is an interesting question. This would undermine the process of hypothesis testing. Because there’s always a chance we’re going to find a significant relationship in our sample even when there isn’t actually one in the population, by digging around to find any significant result we increase that chance.</p>
<p>Our research question for this walkthrough is below:</p>
<blockquote class="blockquote">
<p>Is there a relationship between education level and income?</p>
</blockquote>
<p>Note that we are not specifying a direction here.</p>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="exploring-the-data" class="level1">
<h1>Exploring the data</h1>
<div class="statbox">
<p>Probably the first port of call for almost any statistical analysis is to just explore the data and make sure that things look as you would expect them to look. We can do this visually, or numerically, using the skills we have already learned in the first half of this course.</p>
</div>
<p>Let us first visualise and describe the <strong>marginal distributions</strong> of those variables which are of interest to us. These are the distribution of each variable (employee incomes and education levels) <em>without</em> reference to the values of the other variables.</p>
<p>We could use, for example, <code>geom_density()</code> for a density plot or <code>geom_histogram()</code> for a histogram. We should look at the shape, center and spread of the distribution. Is it symmetric or skewed? Is it unimodal or bimodal? Do we notice any extreme observations?</p>
<p>We can plot the marginal distribution of employee incomes as a density curve, and add a boxplot underneath to check for the presence of outliers. The <code>width</code> of the geom_boxplot() is always quite wide, so I want to make it narrower so that we can see it at the same time as the density plot. Deciding on the exact value for the width here is just trial and error:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the patchwork library allows us to combine plots together</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> riverview, <span class="fu">aes</span>(<span class="at">x =</span> income)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">300</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Income (in thousands of U.S. dollars)"</span>, </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability density"</span>) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> riverview, <span class="fu">aes</span>(<span class="at">x =</span> education)) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Education (in years)"</span>, </span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-incomeplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-incomeplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 1: Density plot and boxplot of employee incomes and education levels</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The plots suggests that the distributions of employee incomes and education levels are both unimodal. Most of the incomes are between roughly $45,000 and $70,000, and most people have between 12 and 20 years of education. Furthermore, the boxplot does not highlight any outliers in either variable.</p>
<p>To further summarize a distribution, it is typical to compute and report numerical summary statistics such as the mean and standard deviation. One way to compute these values is to use the <code>summarise()/summarize()</code> function from the <code>tidyverse</code> library:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>riverview <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">e =</span> <span class="fu">mean</span>(income), </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_income =</span> <span class="fu">sd</span>(income),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_edu =</span> <span class="fu">mean</span>(education),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_edu =</span> <span class="fu">sd</span>(education)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
      e sd_income mean_edu sd_edu
  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
1  53.7      14.6       16   4.36</code></pre>
</div>
</div>
<div class="int">
<p>The marginal distribution of income is unimodal with a mean of approximately $53,700. There is variation in employees’ salaries (SD = $14,553).<br>
The marginal distribution of education is unimodal with a mean of 16 years. There is variation in employees’ level of education (SD = 4.4 years).</p>
</div>
<p>After we’ve looked at the marginal distributions of the variables of interest in the analysis, we typically move on to examining <em>relationships</em> between the variables.</p>
<p>We want to visualise the relationship between income and level of education among the employees in the sample, and think about <em>direction</em> of association; <em>form</em> of association (can it be summarised well with a straight line?); <em>strength</em> of association (how closely do points fall to a recognizable pattern such as a line?); <em>unusual observations</em> that do not fit the pattern of the rest of the observations and which are worth examining in more detail.</p>
<p>Because we are investigating how income varies when varying years of formal education, income here is the dependent variable (on the y-axis), and education is the independent variable (on the x-axis).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> riverview, <span class="fu">aes</span>(<span class="at">x =</span> education, <span class="at">y =</span> income)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Education (in years)"</span>, </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Income (in thousands of U.S. dollars)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/riverview-scatterplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">The relationship between employees education level and income.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="int">
<p>There is a strong positive linear relationship between education level and income for the employees in the sample. High incomes tend to be observed, on average, with more years of formal education. The scatterplot does not highlight any outliers.</p>
</div>
<p>To comment numerically on the strength of the linear association we might compute the correlation coefficient that we were introduced to in <a href="05a_covcor.html">Reading 5A</a></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>riverview <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(education, income) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          education    income
education 1.0000000 0.7947847
income    0.7947847 1.0000000</code></pre>
</div>
</div>
<p>that is, <span class="math inline">\(r_{\text{education, income}} = 0.79\)</span></p>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="fitting-a-linear-model" class="level1 page-columns page-full">
<h1>Fitting a Linear Model</h1>
<!-- :::statbox -->
<!-- **A note on notation**   -->
<!-- You will see a variety of different ways of specifying the linear model form in different resources.   -->
<!-- Some use $\beta$, some use $b$.   -->
<p>The plot created in the above highlights a linear relationship, where the data points are scattered around an underlying linear pattern with a roughly-constant spread as x varies.</p>
<p>We will try to fit a simple (one explanatory variable only) linear regression model:</p>
<p><span class="math display">\[
\begin{align}
&amp; Income = b_0 + b_1 \ Education + \epsilon \quad \\
&amp; \text{where} \\
&amp; \epsilon \sim N(0, \sigma) \text{ independently}
\end{align}
\]</span></p>

<div class="no-row-height column-margin column-container"><div class="">
<p>You will see a variety of different ways of specifying the linear model form in different resources, some use <span class="math inline">\(\beta\)</span>, some use <span class="math inline">\(b\)</span>. Sometimes you will see <span class="math inline">\(\alpha\)</span> instead of <span class="math inline">\(b_0\)</span>.</p>
</div></div><p>where “<span class="math inline">\(\epsilon \sim N(0, \sigma) \text{ independently}\)</span>” means that the errors around the line have mean zero and constant spread as x varies (we’ll read more about what this means later in this course, when we discuss the assumptions underlying regression).</p>
<div class="rtip">
<p>To fit linear models, we use the <code>lm()</code> function.<br>
The syntax of the <code>lm()</code> function is:</p>
<pre><code>[model name] &lt;- lm([response variable] ~ 1 + [explanatory variable], data = [dataframe])</code></pre>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Why ~1?</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p>The fitted model can be written as</p>
<p><span class="math display">\[
\hat y = \hat b_0 + \hat b_1 (x)
\]</span></p>
<p>The predicted values for the outcome are equal to our intercept, <span class="math inline">\(\hat b_0\)</span>, plus our slope <span class="math inline">\(\hat b_1\)</span> multiplied by the value on our explanatory variable <span class="math inline">\(x\)</span>.<br>
The intercept is a <em>constant</em>. That is, we could write it as multiplied by 1:</p>
<p><span class="math display">\[
\hat y = \color{blue}{\hat b_0}\color{black}{}(\color{green}{1}\color{black}{})\color{blue}{ + \hat b_1 }\color{black}{}(\color{green}{x}\color{black}{})
\]</span></p>
<p>When we specify the linear model in R, we include after the tilde sign <code>~</code> all the things which appear to the right of each of the <span class="math inline">\(\hat b\)</span>s (the bits in green in the equartion above). That’s why the 1 is included. It is just saying “we want the intercept, <span class="math inline">\(b_0\)</span>, to be estimated”.</p>
</div>
<p class="optional-end">
</p>
</div>
<p>Using the <code>lm()</code> function, we fit a linear model to the sample data, in which employee income is explained by education level. Typically, we assign it to a name to store it in our environment, so that we might access it later.</p>
<p>As the variables are in the <code>riverview</code> dataframe, we would write:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(income <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education, <span class="at">data =</span> riverview)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="interpreting-coefficients" class="level1">
<h1>Interpreting coefficients</h1>
<p>Now we have fitted our model, we need to understand what it can tell us. The main parts of interest are the estimates of the intercept (<span class="math inline">\(b_0\)</span>) and the slope (<span class="math inline">\(b_1\)</span>).</p>
<div class="rtip">
<p>As we assigned our linear model object to the name <code>model1</code> in R, then to obtain the estimated regression coefficients we can use it’s name in various ways and with various functions.</p>
<ul>
<li>type <code>model1</code>, i.e.&nbsp;simply invoke the name of the fitted model;</li>
<li>type <code>model1$coefficients</code>;</li>
<li>use the <code>coef(model1)</code> function;</li>
<li>use the <code>coefficients(model1)</code> function;</li>
<li>use the <code>summary(model1)</code> function and look under the “Estimate” column.</li>
</ul>
<p>The estimated parameters returned by the above methods are all equivalent. However, <code>summary()</code> returns more information and you need to look under the column “Estimate”.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   education 
  11.321379    2.651297 </code></pre>
</div>
</div>
<p>From this, we get that the fitted line is:</p>
<p><span class="math display">\[
\widehat{Income} = 11.32 + 2.65 \ Education \\
\]</span></p>
<p>We can interpret the estimated intercept as:</p>
<div class="int">
<p>The estimated average income associated with zero years of formal education is $11,321.</p>
</div>
<p>For the estimated slope we get:</p>
<div class="int">
<p>The estimated increase in average income associated with a one year increase in education is $2,651.</p>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="interpreting-sigma" class="level1 page-columns page-full">
<h1>Interpreting <span class="math inline">\(\sigma\)</span></h1>
<p>The parameter estimates from our simple linear regression model take the form of a line, representing the systematic part of our model <span class="math inline">\(b_0 + b_1 \ x\)</span>, which in our case is <span class="math inline">\(11.32 + 2.65 \ Education\)</span>. Deviations from the line are determined by the random error component <span class="math inline">\(\hat \epsilon\)</span>, or “residuals” (the red lines in <a href="#fig-slr">Figure&nbsp;2</a> below).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-slr" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-slr-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 2: Simple linear regression model, with systematic part of the model in blue and residuals in red</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The standard deviation of the errors, denoted by <span class="math inline">\(\sigma\)</span> is an important quantity to estimate because it measures how much individual data points tend to deviate above and below the regression line.</p>
<p>A small <span class="math inline">\(\sigma\)</span> indicates that the points hug the line closely and we should expect fairly accurate predictions, while a large <span class="math inline">\(\sigma\)</span> suggests that, even if we estimate the line perfectly, we can expect individual values to deviate from it by substantial amounts.</p>
<p>When we actually <strong>estimate</strong> this quantity, we might put a hat on it, and write <span class="math inline">\(\hat \sigma\)</span>. It is equal to</p>
<p><span class="math display">\[
\begin{align}
&amp; \hat \sigma = \sqrt{\frac{SS_{Residual}}{n - 2}} \\
\qquad \\
&amp; \text{where} \\
&amp; SS_{Residual} = \textrm{Sum of Squared Residuals} = \sum_{i=1}^n{(\epsilon_i)^2}
\end{align}
\]</span></p>
<p>Consider the following:</p>
<ol type="1">
<li>In fitting a linear regression model, we make the assumption that the errors around the line are normally distributed around zero (this is the <span class="math inline">\(\epsilon \sim N(0, \sigma)\)</span> bit.)<br>
</li>
<li>About 95% of values from a normal distribution fall within two standard deviations of the centre.</li>
</ol>
<p>We can obtain the estimated standard deviation of the errors (<span class="math inline">\(\hat \sigma\)</span>) from the fitted model using <code>sigma()</code> and giving it the name of our model.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>We can also look at the “Residual standard error” entry of the <code>summary(model1)</code> output. The term “Residual standard error” is a misnomer, as the help page for <code>sigma</code> says (check <code>?sigma</code>). However, it’s hard to get rid of this bad name as it has been used in too many books showing R output.</p>
</div></div><div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sigma</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.978116</code></pre>
</div>
</div>
<p>For any particular level of education, employee incomes should be distributed above and below the regression line with standard deviation estimated to be <span class="math inline">\(\hat \sigma = 8.98\)</span>. Since <span class="math inline">\(2 \hat \sigma = 2 (8.98) = 17.96\)</span>, we expect most (about 95%) of the employee incomes to be within about $18,000 from the regression line.</p>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="fitted-and-predicted-values" class="level1">
<h1>Fitted and predicted values</h1>
<div class="rtip">
<p>To compute the model-predicted values for the data in the sample we can use various functions. Again, if our model object is named “model1” in our environment, we can use:</p>
<ul>
<li><code>predict(model1)</code></li>
<li><code>fitted(model1)</code></li>
<li><code>fitted.values(model1)</code></li>
<li><code>model1$fitted.values</code></li>
</ul>
<p>For example, this will give us the estimated income (point on our regression line) for each observed value of education level.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
32.53175 32.53175 37.83435 37.83435 37.83435 43.13694 43.13694 43.13694 
       9       10       11       12       13       14       15       16 
43.13694 48.43953 48.43953 48.43953 51.09083 53.74212 53.74212 53.74212 
      17       18       19       20       21       22       23       24 
53.74212 53.74212 56.39342 59.04472 59.04472 61.69601 61.69601 64.34731 
      25       26       27       28       29       30       31       32 
64.34731 64.34731 64.34731 66.99861 66.99861 69.64990 69.64990 74.95250 </code></pre>
</div>
</div>
<p>We can also compute model-predicted values for other (unobserved) data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make a tibble/dataframe with values for the predictor:</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>education_query <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">education =</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">18</span>, <span class="dv">50</span>))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model predicted values of income, for the values of education</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># inside the "education_query" data</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model1, <span class="at">newdata =</span> education_query)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3 
 40.48564  59.04472 143.88621 </code></pre>
</div>
</div>
</div>
<p>This means we can compute the model-predicted income for someone with, for example, 1 year of education:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>education_query <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">education =</span> <span class="fu">c</span>(<span class="dv">1</span>))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model1, <span class="at">newdata =</span> education_query)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
13.97268 </code></pre>
</div>
</div>
<p>Which, given that our fitted model takes the form below, we can work out ourselves:</p>
<p><span class="math display">\[
\begin{align}
Income &amp;= 11.32 + 2.65\cdot Education \\
Income &amp;= 11.32 + 2.65\cdot 1 \\
Income &amp;= 11.32 + 2.65\\
Income &amp;= 13.97 \\
\end{align}
\]</span></p>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="inference-for-regression-coefficients" class="level1 page-columns page-full">
<h1>Inference for regression coefficients</h1>
<p>We have fitted a linear model, and we now know how we interpret our coefficients. But this is only part of the story.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sillyfig" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/slr/conv1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 3: Estimates without inference</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>To quantify the amount of uncertainty in each estimated coefficient that is due to sampling variability, we use the standard error (SE) of the coefficient. <em>Recall that a standard error gives a numerical answer to the question of how variable a statistic will be because of random sampling.</em></p>
<p>The standard errors are found in the column “Std. Error” of the <code>summary()</code> of a model:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 11.321379  6.1232350 1.848921 7.434602e-02
education    2.651297  0.3696232 7.172972 5.562116e-08</code></pre>
</div>
</div>
<p>In this example the slope, 2.651, has a standard error of 0.37. One way to envision this is as a distribution. Our best guess (mean) for the slope parameter is 2.651. The standard deviation of this distribution is 0.37, which indicates the precision (uncertainty) of our estimate.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sampbeta" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/fig-sampbeta-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 4: Sampling distribution of the slope coefficient. The distribution is approximately bell-shaped with a mean of 2.651 and a standard error of 0.37.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We can perform a test against the null hypothesis that the estimate is zero. The reference distribution in this case is a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom, where <span class="math inline">\(n\)</span> is the sample size, and our test statistic is:</p>
<p><span class="math display">\[
t = \frac{\hat b_1 - 0}{SE(\hat b_1)}
\]</span></p>
<p>This allows us to test the hypothesis that the population slope is zero — that is, that there is no linear association between income and education level in the population.</p>
<p>We don’t actually have to <strong>do</strong> anything for this, it’s all provided for us in the <code>summary()</code> of the model! The information is contained in the row corresponding to the variable “education” in the output of <code>summary()</code>, which reports the t-statistic under <code>t value</code> and the p-value under <code>Pr(&gt;|t|)</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 11.321379  6.1232350 1.848921 7.434602e-02
education    2.651297  0.3696232 7.172972 5.562116e-08</code></pre>
</div>
</div>
<div class="int">
<p>A significant association was found between level of education (i years) and income (<span class="math inline">\(t(30) = 7.173,\ p &lt; .001\)</span>, two-sided).</p>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Recall that the p-value <code>5.56e-08</code> in the <code>Pr(&gt;|t|)</code> column simply means <span class="math inline">\(5.56 \times 10^{-8}\)</span>. This is a very small value, hence we will report it as &lt;.001 following the APA guidelines.</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sillyfig2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/slr/conv2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 5: Conversations with statisticians</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="model-evaluation" class="level1 page-columns page-full">
<h1>Model evaluation</h1>
<section id="partitioning-variance-rsquared" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="partitioning-variance-rsquared">Partitioning Variance: Rsquared</h2>
<p>We might ask ourselves if the model is useful. To quantify and assess model utility, we split the total variability of the response into two terms: the variability explained by the model plus the variability left unexplained in the residuals.</p>
<p><span class="math display">\[
\begin{align}
&amp; \qquad \qquad \qquad \qquad \text{total variability in response } =  \\
&amp; \text{variability explained by model } + \text{unexplained variability in residuals}
\end{align}
\]</span></p>
<p>Each term is quantified by a sum of squares:</p>
<p><span class="math display">\[
\begin{aligned}
SS_{Total} &amp;= SS_{Model} + SS_{Residual} \\
\sum_{i=1}^n (y_i - \bar y)^2 &amp;= \sum_{i=1}^n (\hat y_i - \bar y)^2 + \sum_{i=1}^n (y_i - \hat y_i)^2 \\
\quad \\
\text{Where:} \\
&amp; y_i = \text{observed value} \\
&amp;\bar{y} = \text{mean} \\
&amp; \hat{y}_i = \text{model predicted value} \\
\end{aligned}
\]</span></p>
<div class="sticky">
<p>The <span class="math inline">\(R^2\)</span> coefficient is defined as the proportion of the total variability in the outcome variable which is explained by our model:</p>
<p><span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
</div>
<p>In our model, the <span class="math inline">\(R^2\)</span> shows us the proportion of the total variability in incomes explained by the linear relationship with education level. We can find this easily in the <code>summary()</code> of the model!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ 1 + education, data = riverview)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.809  -5.783   2.088   5.127  18.379 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  11.3214     6.1232   1.849   0.0743 .  
education     2.6513     0.3696   7.173 5.56e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.978 on 30 degrees of freedom
Multiple R-squared:  0.6317,    Adjusted R-squared:  0.6194 
F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
</div>
</div>
<p>The output of <code>summary()</code> displays the R-squared value in the following line:</p>
<pre><code>Multiple R-squared:  0.6317</code></pre>

<div class="no-row-height column-margin column-container"><div class="">
<p>For the moment, ignore “Adjusted R-squared”. We will come back to this later on.</p>
</div></div><div class="int">
<p>Approximately 63% of the total variability in employee incomes is explained by the linear association with education level.</p>
</div>
<div class="optional-begin">
<span id="opt-start-2" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-2', 'opt-start-2')"> <span class="olab">Optional - Manual calculation of R-Squared</span></span>
</div>
<div id="opt-body-2" class="optional-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>riverview_fitted <span class="ot">&lt;-</span> riverview <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">income_hat =</span> <span class="fu">predict</span>(model1),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">resid =</span> income <span class="sc">-</span> income_hat</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(riverview_fitted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  education income seniority gender  male party       income_hat  resid
      &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;
1         8   37.4         7 male       1 Democrat          32.5   4.92
2         8   26.4         9 female     0 Independent       32.5  -6.10
3        10   47.0        14 male       1 Democrat          37.8   9.20
4        10   34.2        16 female     0 Independent       37.8  -3.65
5        10   25.5         1 female     0 Republican        37.8 -12.4 
6        12   46.5        11 female     0 Democrat          43.1   3.35</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>riverview_fitted <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">SSModel =</span> <span class="fu">sum</span>( (income_hat <span class="sc">-</span> <span class="fu">mean</span>(income))<span class="sc">^</span><span class="dv">2</span> ),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">SSTotal =</span> <span class="fu">sum</span>( (income <span class="sc">-</span> <span class="fu">mean</span>(income))<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">RSquared =</span> SSModel <span class="sc">/</span> SSTotal</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  RSquared
     &lt;dbl&gt;
1    0.632</code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section>
<section id="testing-model-utility-f-statistic" class="level2">
<h2 class="anchored" data-anchor-id="testing-model-utility-f-statistic">Testing Model Utility: <span class="math inline">\(F\)</span> Statistic</h2>
<p>We can also perform a test to investigate if the model is ‘useful’ — that is, a test to see if the explanatory variable is a useful predictor of the outcome.<br>
We test the following hypotheses:</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: \text{the model is ineffective, } b_1 = 0 \\
H_1 &amp;: \text{the model is effective, } b_1 \neq 0
\end{aligned}
\]</span></p>
<div class="sticky">
<p>The relevant test-statistic is the F-statistic:</p>
<p><span class="math display">\[
\begin{split}
F = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model} / 1}{SS_{Residual} / (n-2)}
\end{split}
\]</span></p>
<p>which compares the amount of variation in the response explained by the model to the amount of variation left unexplained in the residuals.</p>
<p>The sample F-statistic is compared to an F-distribution with <span class="math inline">\(df_{1} = 1\)</span> and <span class="math inline">\(df_{2} = n - 2\)</span> degrees of freedom.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="optional-begin">
<span id="opt-start-3" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-3', 'opt-start-3')"> <span class="olab">Optional: Another formula for the F-test.</span></span>
</div>
<div id="opt-body-3" class="optional-body" style="display: none;">
<p>With some algebra we can also show that:</p>
<p><span class="math display">\[
F = \frac{R^2 / 1}{(1 - R^2) / (n - 2) } = \frac{R^2 / df_{Model}}{(1 - R^2) / df_{Residual} }
\]</span></p>
<p>Proof:</p>
<p><span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)}
= \frac{\frac{SS_{Model}}{SS_{Total}}}{\frac{SS_{Residual}}{SS_{Total}} \cdot \frac{1}{(n - 2)}}
= \frac{R^2 / 1}{(1 - R^2) / (n - 2)}
\end{aligned}
\]</span></p>
</div>
<p class="optional-end">
</p>
</div>
<p>And yet again, we can look at the output of <code>summary()</code> of our model to find this information. From the <code>summary(model1</code>), the relevant row is just below the <span class="math inline">\(R^2\)</span>, where it states:</p>
<pre><code>F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<div class="int">
<p>The overall test of model utility was significant <span class="math inline">\(F(1, 30) = 51.45, p &lt; .001\)</span>, indicating evidence against the null hypothesis that the model is ineffective (that education is not a useful predictor of income).</p>
</div>
<div class="optional-begin">
<span id="opt-start-4" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-4', 'opt-start-4')"> <span class="olab">Optional: Equivalence of t-test for the slope and model utility F-test in simple regression.</span></span>
</div>
<div id="opt-body-4" class="optional-body" style="display: none;">
<p><strong>In simple linear regression only</strong> (where we have just <strong>one</strong> predictor), the F-statistic for overall model significance is equal to the square of the t-statistic for <span class="math inline">\(H_0: b_1 = 0\)</span>.</p>
<p>You can check that the squared t-statistic is equal, up to rounding error, to the F-statistic:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)<span class="sc">$</span>fstatistic[<span class="st">'value'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   value 
51.45152 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)<span class="sc">$</span>coefficients[<span class="st">'education'</span>,<span class="st">'t value'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.172972</code></pre>
</div>
</div>
<p><span class="math display">\[
t^2 = F \\
7.173^2 = 51.452
\]</span></p>
<p>Here we will show the equivalence of the F-test for model effectiveness and t-test for the slope.</p>
<p>Recall the formula of the sum of squares due to the model. We will rewrite it in an equivalent form below:</p>
<p><span class="math display">\[
\begin{aligned}
SS_{Model} &amp;= \sum_i (\hat y_i - \bar y)^2 \\
&amp;= \sum_i (\hat b_0 + \hat b_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\bar y - \hat b_1 \bar x + \hat b_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\hat b_1 (x_i - \bar x))^2 \\
&amp;= \hat b_1^2 \sum_i (x_i - \bar x)^2
\end{aligned}
\]</span></p>
<p>The F-statistic is given by:</p>
<p><span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)}
= \frac{\hat b_1^2 \sum_i (x_i - \bar x)^2}{\hat \sigma^2}
= \frac{\hat b_1^2 }{\hat \sigma^2 / \sum_i (x_i - \bar x)^2}
\end{aligned}
\]</span></p>
<p>Now recall the formula of the t-statistic,</p>
<p><span class="math display">\[
t = \frac{\hat b_1}{SE(\hat b_1)} = \frac{\hat b_1}{\hat \sigma / \sqrt{\sum_i (x_i - \bar x)^2}}
\]</span></p>
<p>It is evident that the latter is obtained as the square root of the former.</p>
</div>
<p class="optional-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section>
</section>
<section id="binpred" class="level1">
<h1>Binary predictors</h1>
<p>Let’s suppose that instead of having measured education in years, we had data instead on “Obtained College Degree: Yes/No”. Our explanatory variable would be binary categorical (think back to our discussion of <a href="02a_measurement.html" target="_blank">types of data in Reading 2A</a>).<br>
Let us pretend that everyone with &gt;18 years of education has a college degree:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>riverview <span class="ot">&lt;-</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  riverview <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">degree =</span> <span class="fu">ifelse</span>(education <span class="sc">&gt;</span> <span class="dv">18</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We may then plot our relationship as a boxplot. If you want to see the individual points, you could always “jitter” them (right-hand plot below)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(riverview, <span class="fu">aes</span>(<span class="at">x =</span> degree, <span class="at">y =</span> income)) <span class="sc">+</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(riverview, <span class="fu">aes</span>(<span class="at">x =</span> degree, <span class="at">y =</span> income)) <span class="sc">+</span> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">height=</span><span class="dv">0</span>, <span class="at">width=</span>.<span class="dv">05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="statbox">
<p><strong>Binary predictors in linear regression</strong></p>
<p>We can include categorical predictors in a linear regression, but the interpretation of the coefficients is very specific. Whereas we talked about coefficients being interpreted as “the change in <span class="math inline">\(y\)</span> associated with a 1-unit increase in <span class="math inline">\(x\)</span>”, for categorical explanatory variables, coefficients can be considered to examine differences in group means. However, they are actually doing exactly the same thing - the model is simply translating the levels (like “Yes”/“No”) in to 0s and 1s!</p>
<p>So while we may have in our dataframe a categorical predictor like the middle column “degree”, below, what is inputted into our model is more like the third column, “isYes”.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 3
   income degree isYes
    &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt;
 1   50.0 No         0
 2   79.2 Yes        1
 3   55.8 No         0
 4   34.2 No         0
 5   55.9 No         0
 6   37.3 No         0
 7   46.5 No         0
 8   82.7 Yes        1
 9   52.5 No         0
10   56.3 Yes        1
# … with 22 more rows</code></pre>
</div>
</div>
<p>Our coefficients are just the same as before. The intercept is where our predictor equals zero, and the slope is the change in our outcome variable associated with a 1-unit change in our predictor.<br>
However, “zero” for this predictor variable now corresponds to a whole level. This is known as the “reference level”. Accordingly, the 1-unit change in our predictor (the move from “zero” to “one”) corresponds to the difference between the two levels.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07a_slr_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p> <span class="math inline">\(SS_{Total}\)</span> has <span class="math inline">\(n - 1\)</span> degrees of freedom as one degree of freedom is lost in estimating the population mean with the sample mean <span class="math inline">\(\bar{y}\)</span>. <span class="math inline">\(SS_{Residual}\)</span> has <span class="math inline">\(n - 2\)</span> degrees of freedom. There are <span class="math inline">\(n\)</span> residuals, but two degrees of freedom are lost in estimating the intercept and slope of the line used to obtain the <span class="math inline">\(\hat y_i\)</span>s. Hence, by difference, <span class="math inline">\(SS_{Model}\)</span> has <span class="math inline">\(n - 1 - (n - 2) = 1\)</span> degree of freedom.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>