<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.587">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>USMR - 08A: Multiple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-left')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-left')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>
<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">USMR</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 1</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-1">    
        <li>
    <a class="dropdown-item" href="./01a_R.html">
 <span class="dropdown-text">Reading 1A: First look at R/RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b_data.html">
 <span class="dropdown-text">Reading 1B: More R: Basic Data Skills</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01_ex.html">
 <span class="dropdown-text">Exercises: Intro R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 2</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-2">    
        <li>
    <a class="dropdown-item" href="./02a_measurement.html">
 <span class="dropdown-text">Reading 2A: Measurements &amp; Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b_sampling.html">
 <span class="dropdown-text">Reading 2B: Sampling &amp; Curves</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_ex.html">
 <span class="dropdown-text">Exercises: More R; Estimates &amp; Intervals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 3</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-3">    
        <li>
    <a class="dropdown-item" href="./03a_inference.html">
 <span class="dropdown-text">Reading 3A: Foundations of Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03b_inference2.html">
 <span class="dropdown-text">Reading 3B: Practical Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_ex.html">
 <span class="dropdown-text">Exercises:</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 4</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-4">    
        <li>
    <a class="dropdown-item" href="./04_ex.html">
 <span class="dropdown-text">Exercises: Chi-Square Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04b_revistnhst.html">
 <span class="dropdown-text">Reading 4A: Revisiting NHST</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 5</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-5">    
        <li>
    <a class="dropdown-item" href="./05a_covcor.html">
 <span class="dropdown-text">Reading 5A: Covariance &amp; Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_ex.html">
 <span class="dropdown-text">Exercises: Cov, Cor, Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-7" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 7</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-7">    
        <li>
    <a class="dropdown-item" href="./07a_slr.html">
 <span class="dropdown-text">Reading 7A: Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_ex.html">
 <span class="dropdown-text">Exercises: Simple Linear Regression &amp; More Data Wrangling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-8" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 8</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-8">    
        <li>
    <a class="dropdown-item" href="./08a_mlr.html">
 <span class="dropdown-text">Reading 8A: Multiple Linear Regression</span></a>
  </li>  
        <li class="dropdown-header">Exercises</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-week-9" role="button" data-bs-toggle="dropdown" aria-expanded="false">Week 9</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-week-9">    
        <li class="dropdown-header">Reading 9A: More Regression</li>
        <li class="dropdown-header">Exercises</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link active" data-scroll-target="#multiple-linear-regression">Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#model-specification" id="toc-model-specification" class="nav-link" data-scroll-target="#model-specification">Model Specification</a></li>
  <li><a href="#exploring-the-data" id="toc-exploring-the-data" class="nav-link" data-scroll-target="#exploring-the-data">Exploring the Data</a></li>
  <li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model">Fitting the Model</a></li>
  <li><a href="#interpreting-coefficients" id="toc-interpreting-coefficients" class="nav-link" data-scroll-target="#interpreting-coefficients">Interpreting Coefficients</a></li>
  <li><a href="#sigma" id="toc-sigma" class="nav-link" data-scroll-target="#sigma"><span class="math inline">\(\sigma\)</span></a></li>
  <li><a href="#inference" id="toc-inference" class="nav-link" data-scroll-target="#inference">Inference</a></li>
  <li><a href="#more-model-evaluation" id="toc-more-model-evaluation" class="nav-link" data-scroll-target="#more-model-evaluation">More Model Evaluation</a></li>
  </ul></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison">Model Comparison</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">08A: Multiple Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>In this reading, we move from the simple linear regression model (one outcome variable, one explanatory variable) to the <em>multiple regression model</em> (one outcome variable, multiple explanatory variables).<br>
Everything we learned about simple linear regression in <a href="07a_slr.html" target="_blank">Reading 7A</a> can be extended (with minor modification) to the multiple regression model. The key conceptual difference is that for simple linear regression we think of the distribution of errors at some fixed value of the explanatory variable, and for multiple linear regression, we think about the distribution of errors at fixed set of values for all our explanatory variables.</p>
<section id="multiple-linear-regression" class="level1">
<h1>Multiple Linear Regression</h1>
<p><strong>Model formula</strong></p>
<p>For multiple linear regression, the model formula is an extension of the one predictor (“simple”) regression model, to include any number of predictors:</p>
<p><span class="math display">\[
\begin{align}
&amp; y = b_0 \ + \ b_1 x_1 \ + \ b_2 x_2 \ + \ ... \ + b_k x_k \ + \ \epsilon \\
&amp; \quad \\
&amp; \text{where} \\
&amp; \epsilon \sim N(0, \sigma) \text{ independently}
\end{align}
\]</span></p>
<p>In the model specified above,</p>
<ul>
<li><span class="math inline">\(\mu_{y|x_1, x_2, ..., x_k} = b_0 + b_1 x + b_2 x_2 + ... b_k x_k\)</span> represents the systematic part of the model giving the mean of <span class="math inline">\(y\)</span> at each combination of values of variables <span class="math inline">\(x_1\)</span>-<span class="math inline">\(x_k\)</span>;</li>
<li><span class="math inline">\(\epsilon\)</span> represents the error (deviation) from that mean, and the errors are independent from one another.</li>
</ul>
<p><strong>Visual</strong></p>
<p>Note that for simple linear regression we talked about our model as a <em>line</em> in 2 dimensions: the systematic part <span class="math inline">\(b_0 + b_1 x\)</span> defined a line for <span class="math inline">\(\mu_y\)</span> across the possible values of <span class="math inline">\(x\)</span>, with <span class="math inline">\(\epsilon\)</span> as the random deviations from that line. But in multiple regression we have more than two variables making up our model.</p>
<p>In this particular case of three variables (one outcome + two explanatory), we can think of our model as a <em>regression surface</em> (See <a href="#fig-regsurf">Figure&nbsp;1</a>). The systematic part of our model defines the surface across a range of possible values of both <span class="math inline">\(x_1\)</span> <em>and</em> <span class="math inline">\(x_2\)</span>. Deviations from the surface are determined by the random error component, <span class="math inline">\(\hat \epsilon\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-regsurf" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08a_mlr_files/figure-html/fig-regsurf-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 1: Regression surface for y~x1+x2, from two different angles</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Don’t worry about trying to figure out how to visualise it if we had any more explanatory variables! We can only concieve of 3 spatial dimensions. One could imagine this surface changing over time, which would bring in a 4th dimension, but beyond that, it’s not worth trying!.</p>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">Research Question</h2>
<p>The data for this walkthrough is from an hypothetical study in which some reseachers are interested in the relationship between psychological wellbeing and time spent outdoors. They know that other aspects of peoples’ lifestyles such as how much social interaction they have can influence their mental well-being.</p>
<blockquote class="blockquote">
<p><strong>Research Question</strong><br>
Is there a relationship between well-being and time spent outdoors <em>after</em> taking into account the relationship between well-being and social interactions?.</p>
</blockquote>
<div class="frame">
<p><strong>Data: Wellbeing</strong></p>
<p>Researchers interviewed 32 participants, selected at random from the population of residents of Edinburgh &amp; Lothians. They used the Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br>
The researchers also asked participants to estimate the average number of hours they spend outdoors each week, the average number of social interactions they have each week (whether on-line or in-person), and whether they believe that they stick to a routine throughout the week (Yes/No).</p>
<p>The dataset is available at <a href="https://uoepsy.github.io/data/wellbeing.csv" target="_blank">https://uoepsy.github.io/data/wellbeing.csv</a> and contains five attributes:</p>
<ul>
<li><code>wellbeing</code>: Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br>
</li>
<li><code>outdoor_time</code>: Self report estimated number of hours per week spent outdoors<br>
</li>
<li><code>social_int</code>: Self report estimated number of social interactions per week (both online and in-person)</li>
<li><code>routine</code>: Binary Yes/No response to the question “Do you follow a daily routine throughout the week?”</li>
<li><code>location</code>: Location of primary residence (City, Suburb, Rural)</li>
</ul>
</div>
</section>
<section id="model-specification" class="level2">
<h2 class="anchored" data-anchor-id="model-specification">Model Specification</h2>
<p>To address the research question we are going to fit the following model:</p>
<p><span class="math display">\[
Wellbeing = b_0 \ + \ b_1 \cdot Social Interactions \ + \ b_2 \cdot Outdoor Time \ + \ \epsilon
\]</span></p>
</section>
<section id="exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data">Exploring the Data</h2>
<p>First we need to import the wellbeing data into R. We’ll give them the name <code>mwdata</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in data</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>mwdata <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/wellbeing.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, as before, we explore and describe the relevant variables and relationships.<br>
We will want to:</p>
<ul>
<li>Produce plots of the <em>marginal distributions</em> (the distributions of each variable in the analysis without reference to the other variables) of the <code>wellbeing</code>, <code>outdoor_time</code>, and <code>social_int</code> variables.</li>
<li>Produce plots of the <em>marginal relationships</em> between the outcome variable (<code>wellbeing</code>) and each of the explanatory variables.<br>
</li>
<li>Produce a correlation matrix of the variables which are to be used in the analysis, and write a short paragraph describing the relationships.</li>
</ul>
<div class="sticky">
<p><strong>Correlation matrix</strong></p>
<p>A table showing the correlation coefficients - <span class="math inline">\(r_{(x,y)}=\frac{\mathrm{cov}(x,y)}{s_xs_y}\)</span> - between variables. Each cell in the table shows the relationship between two variables. The diagonals show the correlation of a variable with itself (and are therefore always equal to 1).</p>
<p><strong>In R:</strong> We can create a correlation matrix easily by giving the <code>cor()</code> function a dataframe. If we only want to give it a certain set of columns, we can combine this with <code>select()</code>, or giving the column numbers inside <code>[]</code>.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co">#used to arrange plots</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>wellbeing_plot <span class="ot">&lt;-</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">250</span>) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Score on WEMWBS (range 14-70)"</span>, <span class="at">y =</span> <span class="st">"Probability</span><span class="sc">\n</span><span class="st">density"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>outdoortime_plot <span class="ot">&lt;-</span> </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> outdoor_time)) <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">200</span>) <span class="sc">+</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time spent outdoors per week (hours)"</span>, <span class="at">y =</span> <span class="st">"Probability</span><span class="sc">\n</span><span class="st">density"</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>social_plot <span class="ot">&lt;-</span> </span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> social_int)) <span class="sc">+</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">150</span>) <span class="sc">+</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of social interactions per week"</span>, <span class="at">y =</span> <span class="st">"Probability</span><span class="sc">\n</span><span class="st">density"</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># the "patchwork" library allows us to arrange multiple plots</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>wellbeing_plot <span class="sc">/</span> outdoortime_plot <span class="sc">/</span> social_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-marg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08a_mlr_files/figure-html/fig-marg-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 2: Marginal distribution plots of wellbeing sores, weekly hours spent outdoors, and social interactions</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="int">
<ul>
<li>The marginal distribution of scores on the WEMWBS is unimodal with a mean of approximately 43. There is variation in scores (SD = 11.7).<br>
</li>
<li>The marginal distribution of weekly hours spend outdoors is unimodal with a mean of approximately 14.8 hours. There is variation in outdoor time (SD = 6.9 hours).<br>
</li>
<li>The marginal distribution of numbers of social interactions per week is unimodal with a mean of approximately 16. There is variation in in numbers of social interactions per week (SD = 4.4).</li>
</ul>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>wellbeing_outdoor <span class="ot">&lt;-</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> outdoor_time, <span class="at">y =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time spent outdoors per week (hours)"</span>, <span class="at">y =</span> <span class="st">"Wellbeing score (WEMWBS)"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>wellbeing_social <span class="ot">&lt;-</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> social_int, <span class="at">y =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of social interactions per week"</span>, <span class="at">y =</span> <span class="st">"Wellbeing score (WEMWBS)"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>wellbeing_outdoor <span class="sc">|</span> wellbeing_social</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mwdata-mlr-rels" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08a_mlr_files/figure-html/fig-mwdata-mlr-rels-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 3: Scatterplots displaying the relationships between scores on the WEMWBS and a) weekly outdoor time (hours), and b) weekly number of social interactions</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We can either use:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correlation matrix of the first 3 columns</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(mwdata[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>or:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select only the columns we want by name, and pass this to cor()</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>mwdata <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(wellbeing, outdoor_time, social_int) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             wellbeing outdoor_time social_int
wellbeing    1.0000000    0.5815613  0.7939003
outdoor_time 0.5815613    1.0000000  0.3394469
social_int   0.7939003    0.3394469  1.0000000</code></pre>
</div>
</div>
<div class="int">
<p>There is a moderate, positive, linear relationship between weekly outdoor time and WEMWBS scores for the participants in the sample. Participants’ wellbeing scores tend to increase, on average, with the number of hours spent outdoors each week.<br>
There is a moderate, positive, linear relationship between the weekly number of social interactions and WEMWBS scores for the participants in the sample. Participants’ wellbeing scores tend to increase, on average, with the weekly number of social interactions. There is also a weak positive correlation between weekly outdoor time and the weekly number of social interactions.</p>
</div>
<p><br> Note that there is a weak correlation between our two explanatory variables (outdoor_time and social_int). We will return to how this might affect our model when later on we look at the assumptions of multiple regression.</p>
</section>
<section id="fitting-the-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model">Fitting the Model</h2>
<p>As we did for simple linear regression, we can fit our multiple regression model using the <code>lm()</code> function. We can add as many explanatory variables as we like, separating them with a <code>+</code>.</p>
<pre><code>[model name] &lt;- lm([response variable] ~ 1 + [explanatory variable 1] + [explanatory variable 2] + ... , data = [dataframe])</code></pre>
<p><span class="math display">\[
Wellbeing = b_0 \ + \ b_1 \cdot Social Interactions \ + \ b_2 \cdot Outdoor Time \ + \ \epsilon
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>wbmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int <span class="sc">+</span> outdoor_time, <span class="at">data =</span> mwdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interpreting-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-coefficients">Interpreting Coefficients</h2>
<p>The parameters of a multiple regression model are:</p>
<ul>
<li><span class="math inline">\(b_0\)</span> (The intercept);</li>
<li><span class="math inline">\(b_1\)</span> (The slope across values of <span class="math inline">\(x_1\)</span>);</li>
<li>…<br>
</li>
<li>…</li>
<li><span class="math inline">\(b_k\)</span> (The slope across values of <span class="math inline">\(x_k\)</span>);</li>
<li><span class="math inline">\(\sigma\)</span> (The standard deviation of the errors).</li>
</ul>
<p><br> You’ll hear a lot of different ways that people explain multiple regression coefficients.<br>
For the model <span class="math inline">\(y = b_0 + b_1 x_1 + b_2 x_2 + \epsilon\)</span>, the estimate <span class="math inline">\(\hat b_1\)</span> will often be reported as:</p>
<p>the increase in <span class="math inline">\(y\)</span> for a one unit increase in <span class="math inline">\(x_1\)</span> when…</p>
<ul>
<li>holding the effect of <span class="math inline">\(x_2\)</span> constant.</li>
<li>controlling for differences in <span class="math inline">\(x_2\)</span>.</li>
<li>partialling out the effects of <span class="math inline">\(x_2\)</span>.</li>
<li>holding <span class="math inline">\(x_2\)</span> equal.</li>
<li>accounting for effects of <span class="math inline">\(x_2\)</span>.</li>
</ul>
<div class="int">
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept)  5.3703775  4.3205141 1.242995 2.238259e-01
social_int   1.8034489  0.2690982 6.701825 2.369845e-07
outdoor_time 0.5923673  0.1689445 3.506284 1.499467e-03</code></pre>
</div>
</div>
<p>The coefficient 0.59 of weekly outdoor time for predicting wellbeing score says that among those with the same number of social interactions per week, those who have one additional hour of outdoor time tend to, on average, score 0.59 higher on the WEMWBS wellbeing scale. The multiple regression coefficient measures that average <em>conditional</em> relationship.</p>
</div>
<p>One by one, the parameter estimates are:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)   social_int outdoor_time 
   5.3703775    1.8034489    0.5923673 </code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\hat \b_0\)</span> = 5.37, the estimated average wellbeing score associated with zero hours of outdoor time and zero social interactions per week.<br>
</li>
<li><span class="math inline">\(\hat \b_2\)</span> = 1.8, the estimated increase in average wellbeing score associated with an additional social interaction per week (an increase of one), <em>holding weekly outdoor time constant</em> (i.e., when the remaining explanatory variables are held at the same value or are fixed).<br>
</li>
<li><span class="math inline">\(\hat \b_1\)</span> = 0.59, the estimated increase in average wellbeing score associated with one hour increase in weekly outdoor time, <em>holding the number of social interactions constant</em>.</li>
</ul>
</section>
<section id="sigma" class="level2">
<h2 class="anchored" data-anchor-id="sigma"><span class="math inline">\(\sigma\)</span></h2>
<p>Just as we had with simple linear regression, we have errors around the a line, here we have error around a 3-dimensional surface. It’s harder to visualise (but see <a href="#fig-regsurf">Figure&nbsp;1</a>), but we can still get an idea of how far away observations are from our fitted model (the surface).<br>
The estimated standard deviation of the errors is <span class="math inline">\(\hat \sigma\)</span> = 6.15. We would expect 95% of wellbeing scores to be within about 12.3 (<span class="math inline">\(2 \hat \sigma\)</span>) from the model fit.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sigma</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.148276</code></pre>
</div>
</div>
</section>
<section id="inference" class="level2">
<h2 class="anchored" data-anchor-id="inference">Inference</h2>
<p>Much like for simple linear regression, we have the tests of the coefficients being zero, which are provided in the summary:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wbmodel)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept)  5.3703775  4.3205141 1.242995 2.238259e-01
social_int   1.8034489  0.2690982 6.701825 2.369845e-07
outdoor_time 0.5923673  0.1689445 3.506284 1.499467e-03</code></pre>
</div>
</div>
<p>We can also obtain confidence intervals for our estimates (we saw confidence intervals back in <a href="02b_sampling.html" target="_blank">Reading 2B</a>. These provide a means of quantifying the uncertainty (or precision) of our estimates.</p>
<p>The function <code>confint()</code> can do this for us.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(wbmodel, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %     97.5 %
(Intercept)  -3.4660660 14.2068209
social_int    1.2530813  2.3538164
outdoor_time  0.2468371  0.9378975</code></pre>
</div>
</div>
<div class="int">
<ul>
<li>The average wellbeing score for all those with zero hours of outdoor time and zero social interactions per week is between -3.47 and 14.21.<br>
</li>
<li>When <em>holding weekly outdoor time constant</em>, each increase of one social interaction per week is associated with a difference in wellbeing scores between 1.25 and 2.35, on average.</li>
<li>When <em>holding the number of social interactions per week constant</em>, each one hour increase in weekly outdoor time is associated with a difference in wellbeing scores between 0.25 and 0.94, on average.</li>
</ul>
</div>
</section>
<section id="more-model-evaluation" class="level2">
<h2 class="anchored" data-anchor-id="more-model-evaluation">More Model Evaluation</h2>
<div class="statbox">
<p><strong>Adjusted <span class="math inline">\(R^2\)</span></strong></p>
<p>We know from our work on simple linear regression that the R-squared can be obtained as:</p>
<p><span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
<p>However, when we add more and more predictors into a multiple regression model, <span class="math inline">\(SS_{Residual}\)</span> cannot increase, and may decrease by pure chance alone, even if the predictors are unrelated to the outcome variable. Because <span class="math inline">\(SS_{Total}\)</span> is constant, the calculation <span class="math inline">\(1-\frac{SS_{Residual}}{SS_{Total}}\)</span> will increase by chance alone.</p>
<p>An alternative, the Adjusted-<span class="math inline">\(R^2\)</span>, does not necessarily increase with the addition of more explanatory variables, by including a penalty according to the number of explanatory variables in the model. It is not by itself meaningful, but can be useful in determining what predictors to include in a model.</p>
<p><span class="math display">\[
Adjusted{-}R^2=1-\frac{(1-R^2)(n-1)}{n-k-1} \\
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; n = \text{sample size} \\
&amp; k = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
<hr>
<p><strong>In R,</strong> you can view the mutiple and adjusted <span class="math inline">\(R^2\)</span> at the bottom of the output of <code>summary(&lt;modelname&gt;)</code>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mlroutputrsq" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/mlr/mlroutputrsq.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 4: Multiple regression output in R, summary.lm(). R-squared highlighted</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<div class="statbox">
<p><strong>F-ratio</strong></p>
<p>As in simple linear regression, the F-ratio is used to test the null hypothesis that <strong>all</strong> regression slopes are zero (it is just that now that we have multiple predictors, “all” is more than 1).</p>
<p><span class="math display">\[
\begin{aligned}
H_0: &amp; \text{the model is ineffective, } \\
&amp; b_1, ..., b_k = 0 \\
H_1: &amp;\text{the model is effective, } \\
&amp; \text{any of }b_1, ..., b_k \neq 0
\end{aligned}
\]</span></p>
<p>It is called the F-ratio because it is the ratio of the how much of the variation is explained by the model (per parameter) versus how much of the variation is unexplained (per remaining degrees of freedom).</p>
<p><span class="math display">\[
\begin{align}
&amp; F_{df_{model},df_{residual}} = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model}/df_{Model}}{SS_{Residual}/df_{Residual}} \\
&amp; \quad \\
&amp; \text{Where:} \\
&amp; df_{model} = k \\
&amp; df_{error} = n-k-1 \\
&amp; n = \text{sample size} \\
&amp; k  = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
<hr>
<p><strong>In R,</strong> at the bottom of the output of <code>summary(&lt;modelname&gt;)</code>, you can view the F ratio, along with an hypothesis test against the alternative hypothesis that the at least one of the coefficients <span class="math inline">\(\neq 0\)</span> (under the null hypothesis that all coefficients = 0, the ratio of explained:unexplained variance should be approximately 1):</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div id="fig-mlroutputrf" class="quarto-figure quarto-figure-left anchored">
<figure class="figure">
<p><img src="images/mlr/mlroutputf.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 5: Multiple regression output in R, summary.lm(). F statistic highlighted</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<div class="int">
<div class="cell" data-layout-align="center">

</div>
<p>Weekly social interactions and outdoor time explained 72.2% of the variance in well-being scores (adjusted <span class="math inline">\(R^2\)</span> =0.722, <span class="math inline">\(F\)</span>(2,29)=41.3, p&lt;.001)</p>
</div>
</section>
</section>
<section id="model-comparison" class="level1">
<h1>Model Comparison</h1>
<p>The F-ratio we see at the bottom of <code>summary(model)</code> is actually a comparison between two models: our model (with some explanatory variables in predicting <span class="math inline">\(y\)</span>) and <strong>the null model.</strong> In regression, the null model can be thought of as the model in which all explanatory variables have zero regression coefficients. It is also referred to as the <strong>intercept-only model</strong>, because if all predictor variable coefficients are zero, then the only we are only estimating <span class="math inline">\(y\)</span> via an intercept (which will be the mean: <span class="math inline">\(\bar y\)</span>).</p>
<p>But we don’t always have to compare our model to the null model. We can compare it to all the intermediate models which vary in the complexity, from the null model to our full model.</p>
<div class="imp">
<p>If (<em>and only if</em>) two models are <strong>nested</strong> (one model contains all the predictors of the other and is fitted to the same data), we can compare them using an <strong>incremental F-test.</strong></p>
</div>
<div class="statbox">
<p><strong>Incremental F-test</strong></p>
<p>This is a formal test of whether the additional predictors provide a better fitting model.<br>
Formally this is the test of:</p>
<ul>
<li><span class="math inline">\(H_0:\)</span> coefficients for the added/ommitted variables are all zero.</li>
<li><span class="math inline">\(H_1:\)</span> at least one of the added/ommitted variables has a coefficient that is not zero.</li>
</ul>
<div class="rtip">
<p><strong>In R,</strong> we can conduct an incremental F-test by constructing two models, and passing them to the <code>anova()</code> function: <code>anova(model1, model2)</code>.</p>
</div>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Optional: F-ratio written for model comparison</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p>The F-ratio for comparing the residual sums of squares between two models can be written as:</p>
<p><span class="math display">\[
\begin{align}
&amp; F_{(df_R-df_F),df_F} = \frac{(SSR_R-SSR_F)/(df_R-df_F)}{SSR_F / df_F} \\
&amp; \quad \\
&amp; \text{Where:} \\
&amp; SSR_R = \text{residual sums of squares for the restricted model} \\
&amp; SSR_F = \text{residual sums of squares for the full model} \\
&amp; df_R = \text{residual degrees of freedom from the restricted model} \\
&amp; df_F = \text{residual degrees of freedom from the full model} \\
\end{align}
\]</span></p>
</div>
<p class="optional-end">
</p>
</div>
<p>To fit the ‘null model’, we simply fit the model with only an intercept term, and no predictors. We can use the <code>anova()</code> function to compare this model with ours, and we will see that it matches the <span class="math inline">\(F\)</span>-statistic at the bottom of the full model output.</p>
<p>Here are both models fitted:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>null_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mwdata)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>wbmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int <span class="sc">+</span> outdoor_time, <span class="at">data =</span> mwdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And the comparison between them, a test of the reduction in residual sums of squares:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(null_model, wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: wellbeing ~ 1
Model 2: wellbeing ~ 1 + social_int + outdoor_time
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     31 4222.0                                  
2     29 1096.2  2    3125.8 41.345 3.226e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>And from our full model, we can get that same <span class="math inline">\(F\)</span>-statistic:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wbmodel)<span class="sc">$</span>fstatistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   value    numdf    dendf 
41.34465  2.00000 29.00000 </code></pre>
</div>
</div>
<p>And we can retrieve the p-value:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>fstat <span class="ot">=</span> <span class="fu">summary</span>(wbmodel)<span class="sc">$</span>fstatistic[<span class="dv">1</span>]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>df_1 <span class="ot">=</span> <span class="fu">summary</span>(wbmodel)<span class="sc">$</span>fstatistic[<span class="dv">2</span>]</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>df_2 <span class="ot">=</span> <span class="fu">summary</span>(wbmodel)<span class="sc">$</span>fstatistic[<span class="dv">3</span>]</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(fstat, df_1, df_2, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       value 
3.225549e-09 </code></pre>
</div>
</div>
<p>We can also see quickly all the F-ratios at the addition of each explanatory variable incrementally, by just using <code>anova(model)</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(wbmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: wellbeing
             Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
social_int    1 2661.03 2661.03  70.395 3.015e-09 ***
outdoor_time  1  464.73  464.73  12.294  0.001499 ** 
Residuals    29 1096.24   37.80                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This is the same as building each incremental model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>null_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mwdata)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int, <span class="at">data =</span> mwdata)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int <span class="sc">+</span> outdoor_time , <span class="at">data =</span> mwdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And comparing them in increasing complexity:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(null_model, model1, model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: wellbeing ~ 1
Model 2: wellbeing ~ 1 + social_int
Model 3: wellbeing ~ 1 + social_int + outdoor_time
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     31 4222.0                                  
2     30 1561.0  1   2661.03 70.395 3.015e-09 ***
3     29 1096.2  1    464.73 12.294  0.001499 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>TODO upto here</p>
<p><strong>Using either of the outputs from the above two lines of code, does weekly outdoor time explain a significant amount of variance in wellbeing scores over and above weekly social interactions?</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>null_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mwdata)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int, <span class="at">data =</span> mwdata)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int <span class="sc">+</span> outdoor_time , <span class="at">data =</span> mwdata)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)<span class="sc">$</span>adj.r.sq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6179536</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)<span class="sc">$</span>adj.r.sq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7224443</code></pre>
</div>
</div>
<div class="int">
<p>The model <em>with</em> outdoor time as a predictor explains 72% of the variance, and the model <em>without</em> explains 62%.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1, model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: wellbeing ~ 1 + social_int
Model 2: wellbeing ~ 1 + social_int + outdoor_time
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1     30 1561.0                                
2     29 1096.2  1    464.73 12.294 0.001499 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="int">
<p>Time spent outdoors was found to explain a significant amount of variance in wellbeing scores over and above weekly social interactions<br>
<span class="math inline">\(F\)</span>(1,29)=12.29, p&lt;.001.</p>
</div>
<div class="question-begin">
Question C4
</div>
<div class="question-body">
<p>Play around with changing the <em>order</em> of the explanatory variables in our model. This will <strong>not</strong> change the <code>summary()</code> output, but it <strong>will</strong> change the <code>anova(model)</code> output.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">+</span> social_int, <span class="at">data =</span> mwdata)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>model2a <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int <span class="sc">+</span> outdoor_time, <span class="at">data =</span> mwdata)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2a)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model2)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model2a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<p>The <code>summary()</code> output for these two models will be the same numbers, but just in a different order.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">+</span> social_int, <span class="at">data =</span> mwdata)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>model2a <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int <span class="sc">+</span> outdoor_time, <span class="at">data =</span> mwdata)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept)  5.3703775  4.3205141 1.242995 2.238259e-01
outdoor_time 0.5923673  0.1689445 3.506284 1.499467e-03
social_int   1.8034489  0.2690982 6.701825 2.369845e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2a)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept)  5.3703775  4.3205141 1.242995 2.238259e-01
social_int   1.8034489  0.2690982 6.701825 2.369845e-07
outdoor_time 0.5923673  0.1689445 3.506284 1.499467e-03</code></pre>
</div>
</div>
<p>The <code>anova()</code> output will be <em>different</em> for these two models, because it tests the <strong>incremental</strong> addition of each explanatory variable in the order in which they are inputted into the model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: wellbeing
             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
outdoor_time  1 1427.9  1427.9  37.775 1.068e-06 ***
social_int    1 1697.8  1697.8  44.914 2.370e-07 ***
Residuals    29 1096.2    37.8                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model2a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: wellbeing
             Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
social_int    1 2661.03 2661.03  70.395 3.015e-09 ***
outdoor_time  1  464.73  464.73  12.294  0.001499 ** 
Residuals    29 1096.24   37.80                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="lo">
<p>We should be careful when we conduct research and take the time to think about <em>what</em> exactly we are measuring, and <em>how.</em></p>
<p>The notion of performing the “incremental tests” that we have just seen provides a good example of when we can fall foul of “measurement error”.<br>
If you’re interested, we have written up a fun little example on incremental validity, which you can <a href="https://uoepsy.github.io/usmr/labs/zz_incrementalvalidity.html">find here.</a></p>
</div>
<div class="question-begin">
Question C5
</div>
<div class="question-body">
<p>Does the addition of routine provide significant improvement to model fit, after accounting for the effects of outdoor time and social interactions?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>We can do this with one:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">+</span> social_int <span class="sc">+</span> routine, <span class="at">data =</span> mwdata)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Or the same thing with two models:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">+</span> social_int, <span class="at">data =</span> mwdata)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">+</span> social_int <span class="sc">+</span> routine, <span class="at">data =</span> mwdata)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model2, model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>