{
  "hash": "2c895b64969fd1733ac70db7f42a756f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercises: Interactions!\"\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n\n# Processing a hangover\n\n:::frame\n__Dataset: hangover_speed.csv__  \n\n\n\n\n\n\n\n\n\nHow is hours of sleep associated with processing speed? Is this dependent upon whether or not alcohol was consumed the previous night? \n107 participants completed the Symbol Digit Modalities Task (SDMT), a measure of processing speed. Participants also recorded how many hours they had slept the previous night (to the nearest 15 mins), and whether or not they had consumed alcohol.  \n\nThe dataset is available at [https://uoepsy.github.io/data/hangover_speed.csv](https://uoepsy.github.io/data/hangover_speed.csv){target=\"_blank\"}.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"weolpswrfv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#weolpswrfv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#weolpswrfv thead, #weolpswrfv tbody, #weolpswrfv tfoot, #weolpswrfv tr, #weolpswrfv td, #weolpswrfv th {\n  border-style: none;\n}\n\n#weolpswrfv p {\n  margin: 0;\n  padding: 0;\n}\n\n#weolpswrfv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#weolpswrfv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#weolpswrfv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#weolpswrfv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#weolpswrfv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#weolpswrfv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#weolpswrfv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#weolpswrfv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#weolpswrfv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#weolpswrfv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#weolpswrfv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#weolpswrfv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#weolpswrfv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#weolpswrfv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#weolpswrfv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#weolpswrfv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#weolpswrfv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#weolpswrfv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#weolpswrfv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#weolpswrfv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#weolpswrfv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#weolpswrfv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#weolpswrfv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#weolpswrfv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#weolpswrfv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#weolpswrfv .gt_left {\n  text-align: left;\n}\n\n#weolpswrfv .gt_center {\n  text-align: center;\n}\n\n#weolpswrfv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#weolpswrfv .gt_font_normal {\n  font-weight: normal;\n}\n\n#weolpswrfv .gt_font_bold {\n  font-weight: bold;\n}\n\n#weolpswrfv .gt_font_italic {\n  font-style: italic;\n}\n\n#weolpswrfv .gt_super {\n  font-size: 65%;\n}\n\n#weolpswrfv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#weolpswrfv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#weolpswrfv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#weolpswrfv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#weolpswrfv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#weolpswrfv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#weolpswrfv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#weolpswrfv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#weolpswrfv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">hrs_sleep</td>\n<td headers=\"description\" class=\"gt_row gt_left\">hours slept the previous night (to the nearest 15 mins)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">alc</td>\n<td headers=\"description\" class=\"gt_row gt_left\">was alcohol consumed the previous evening? ('y'=yes, 'n'=no)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">sdmt</td>\n<td headers=\"description\" class=\"gt_row gt_left\">score on the Symbol Digit Modalities Task (SDMT), a measure of processing speed (range 0 to 100)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nRead in the data and provide some simple descriptives.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- What is the mean score on the SDMT, what is the variability in scores?  \n- How many people had alcohol the previous night?  \n- How many hours did people sleep on average? Did this vary between the drinkers and the non-drinkers?  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nHere's our data. Everything looks within plausible ranges for our two continuous variables `hrs_sleep` and `sdmt`. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhodat <- read_csv(\"https://uoepsy.github.io/data/hangover_speed.csv\")\n```\n:::\n\n\n\n\nWe can get the means and SDs for hours slept and the SDMT:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(psych)\ndescribe(hodat |> select(-alc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n  mean    sd median trimmed   mad   min  max range skew\nhrs_sleep    1 107  7.20  1.20   7.25    7.18  1.11  4.25 10.5  6.25 0.20\nsdmt         2 107 54.59 12.13  53.00   54.23 10.38 22.00 86.0 64.00 0.28\n          kurtosis   se\nhrs_sleep     0.07 0.12\nsdmt          0.08 1.17\n```\n\n\n:::\n:::\n\n\n\n\nWe can see that 57% of participants didn't drink, and 43% of them did:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(hodat$alc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n n  y \n61 46 \n```\n\n\n:::\n:::\n\n\n\n\nAnd it doesn't look like they differed very much in their sleep times:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhodat |> group_by(alc) |>\n  summarise(\n    slept = mean(hrs_sleep)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  alc   slept\n  <chr> <dbl>\n1 n      7.12\n2 y      7.30\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\nMake a plot of SDMT predicted by hours slept, and colour the points by whether or not the participants had drank alcohol.  \n\nCan you plot a separate `lm` line on the graph using `geom_smooth` for each group (alcohol v no alcohol)?  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- to make `geom_smooth()` fit a linear model (`lm`), remember to use `geom_smooth(method=lm)`.  \n- if you have the grouping in the `aes()`, then when you add `geom_smooth()` it should make a different one for each group!  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(hodat, aes(x = hrs_sleep, y = sdmt, col = alc)) +\n  geom_point() +\n  geom_smooth(method=lm)\n```\n\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nAdding a different `geom_smooth(method=lm)` for each group is just fitting a different model to each groups' data - i.e. a slope of `sdmt~hrs_sleep` for the drinkers and a slope for the non-drinkers.  \n\nBut we actually want to _test_ if the two slopes are different, and for that we need to create *one* model that includes the appropriate interaction term.  \n\nFit a model to examine whether the association between `hrs_sleep` and `sdmt` is different depending upon alcohol consumption.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThis is the same logic as the air-pollution & APOE-4 example in [9A #it-depends](09a_interactions.html#it-depends){target=\"_blank\"}.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod_int <- lm(sdmt ~ hrs_sleep * alc, data = hodat)\nsummary(mod_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sdmt ~ hrs_sleep * alc, data = hodat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-23.3384  -5.2919  -0.2911   6.6458  19.7389 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      3.1496     6.9631   0.452   0.6520    \nhrs_sleep        7.6499     0.9643   7.933 2.71e-12 ***\nalcy            17.7151    10.6874   1.658   0.1004    \nhrs_sleep:alcy  -3.5867     1.4593  -2.458   0.0156 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.914 on 103 degrees of freedom\nMultiple R-squared:  0.4753,\tAdjusted R-squared:   0.46 \nF-statistic:  31.1 on 3 and 103 DF,  p-value: 2.136e-14\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\nInterpret each coefficient from your model.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nOur interaction involves a continuous variable (`hrs_sleep`) and a binary variable (`alc`). An interpretation of a similar example is in [9A #interpretation](09a_interactions.html#interpretation){target=\"_blank\"}.  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mod_int)\n```\n:::\n\n\n\n```\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      3.1496     6.9631   0.452   0.6520    \nhrs_sleep        7.6499     0.9643   7.933 2.71e-12 ***\nalcy            17.7151    10.6874   1.658   0.1004    \nhrs_sleep:alcy  -3.5867     1.4593  -2.458   0.0156 *  \n---\n```\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vzjtuuzcdq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vzjtuuzcdq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vzjtuuzcdq thead, #vzjtuuzcdq tbody, #vzjtuuzcdq tfoot, #vzjtuuzcdq tr, #vzjtuuzcdq td, #vzjtuuzcdq th {\n  border-style: none;\n}\n\n#vzjtuuzcdq p {\n  margin: 0;\n  padding: 0;\n}\n\n#vzjtuuzcdq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vzjtuuzcdq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vzjtuuzcdq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vzjtuuzcdq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vzjtuuzcdq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vzjtuuzcdq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vzjtuuzcdq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vzjtuuzcdq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vzjtuuzcdq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vzjtuuzcdq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vzjtuuzcdq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vzjtuuzcdq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vzjtuuzcdq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vzjtuuzcdq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vzjtuuzcdq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vzjtuuzcdq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vzjtuuzcdq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vzjtuuzcdq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vzjtuuzcdq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vzjtuuzcdq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vzjtuuzcdq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vzjtuuzcdq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vzjtuuzcdq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vzjtuuzcdq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vzjtuuzcdq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vzjtuuzcdq .gt_left {\n  text-align: left;\n}\n\n#vzjtuuzcdq .gt_center {\n  text-align: center;\n}\n\n#vzjtuuzcdq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vzjtuuzcdq .gt_font_normal {\n  font-weight: normal;\n}\n\n#vzjtuuzcdq .gt_font_bold {\n  font-weight: bold;\n}\n\n#vzjtuuzcdq .gt_font_italic {\n  font-style: italic;\n}\n\n#vzjtuuzcdq .gt_super {\n  font-size: 65%;\n}\n\n#vzjtuuzcdq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vzjtuuzcdq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vzjtuuzcdq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vzjtuuzcdq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vzjtuuzcdq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vzjtuuzcdq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vzjtuuzcdq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vzjtuuzcdq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vzjtuuzcdq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"coefficient\">coefficient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"interpretation\">interpretation</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">3.15</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">A non-drinker who slept 0 hours is estimated to have an SDMT score of 3.1 - note this is not significantly different from zero</td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">hrs_sleep</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">7.65</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">For every additional hour slept, non-drinkers scores on SDMT are estimated to increase by 7.6</td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">alcy</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">17.72</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">drinkers who slept zero hours are estimated to have 17.7 higher scores on SDMT than non-drinkers who slept zero hours - note this is not significantly different from zero</td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">hrs_sleep:alcy</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-3.59</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">For every additional hour's sleep, drinkers scores on SDMT  increase by 3.6 *less* than they do for non-drinkers</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\nConstruct a plot of the model estimated associations between hours-slept and SDMT for drinkers and non-drinkers.  \n\nBecause we have nothing else in our model, this should end up looking exactly the same as our initial plot in Question 2!    \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nIt all follows the same logic as we have used before:  \n\n1. make a dataframe of the values of the predictors that we wish to plot across\n2. using `augment()`, add to that the predicted values of the model, and the associated confidence intervals\n3. shove it all in ggplot!  \n\nBecause we are wanting to plot across _multiple_ predictors (i.e. we want to plot across a range of `hrs_slept` __and__ both values of `alc`), try using `expand_grid()`.  \n\nPlay around with this to see what it does:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexpand_grid(\n  continuous = 1:5,\n  binary = c(\"dog\",\"cat\",\"parrot\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 2\n   continuous binary\n        <int> <chr> \n 1          1 dog   \n 2          1 cat   \n 3          1 parrot\n 4          2 dog   \n 5          2 cat   \n 6          2 parrot\n 7          3 dog   \n 8          3 cat   \n 9          3 parrot\n10          4 dog   \n11          4 cat   \n12          4 parrot\n13          5 dog   \n14          5 cat   \n15          5 parrot\n```\n\n\n:::\n:::\n\n\n\n\nIf you get stuck, a very similar example is in [9A #visualisation](09a_interactions.html#visualisation){target=\"_blank\"}.  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# plot data\nplotdat <- expand_grid(\n  hrs_sleep = 0:14,\n  alc = c(\"n\",\"y\")\n)\n# plot\nbroom::augment(mod_int, newdata = plotdat, interval=\"confidence\") |>\n  ggplot(aes(x= hrs_sleep, y = .fitted, \n             col = alc, fill = alc)) + \n  geom_line() +\n  geom_ribbon(aes(ymin=.lower,ymax=.upper), alpha=.3)\n```\n\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\nNo one in our dataset has slept zero hours, and i'm probably not interested in differences between drinkers/non-drinkers who never sleep.  \n\nRefit the model to adjust the intercept to a more meaningful value. Everyone always goes on about 8 hours of sleep being the minimum?  \n\nHow has the interpretation of your coefficient(s) changed?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nSee [9A #mean-centering](09a_interactions.html#mean-centering){target=\"_blank\"} for an example of mean-centering a predictor in the interaction. Remember that there are multiple ways to do this - you could make a new variable first, or you could do it all _inside_ the model.  \n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-1' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-1', 'sol-start-1')\">  Solution Part 1 - recentering and refitting</button></div><div class=\"solution-body\" id = \"sol-body-1\" style=\"display: none;\">\n\n\n\nIf we want to recenter our `hrs_sleep` variable on 8 hours, we could either create a new variable which is `hrs_sleep - 8` (which would therefore make everyone who slept 8 hours be given a value of `0` in the variable), or we could do it _in_ the model:  \n  \n:::panelset\n:::panel\n#### re-centering first\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhodat <- \n  hodat |>\n    mutate(\n      hrs_8 = hrs_sleep - 8\n    )\n\nmod_int2 <- lm(sdmt ~ hrs_8 * alc, data = hodat)\n```\n:::\n\n\n\n:::\n:::panel\n#### doing it all in the model\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod_int2 <- lm(sdmt ~ I(hrs_sleep-8) * alc, data = hodat)\n```\n:::\n\n\n\n\n:::\n::::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution Part 2 - interpreting coefficients</button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mod_int2)\n```\n:::\n\n\n\n```\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            64.3487     1.4206  45.297  < 2e-16 ***\nI(hrs_sleep - 8)        7.6499     0.9643   7.933 2.71e-12 ***\nalcy                  -10.9786     2.0800  -5.278 7.27e-07 ***\nI(hrs_sleep - 8):alcy  -3.5867     1.4593  -2.458   0.0156 *  \n---\n```\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jyytzjpwcf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jyytzjpwcf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jyytzjpwcf thead, #jyytzjpwcf tbody, #jyytzjpwcf tfoot, #jyytzjpwcf tr, #jyytzjpwcf td, #jyytzjpwcf th {\n  border-style: none;\n}\n\n#jyytzjpwcf p {\n  margin: 0;\n  padding: 0;\n}\n\n#jyytzjpwcf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jyytzjpwcf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jyytzjpwcf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jyytzjpwcf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jyytzjpwcf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jyytzjpwcf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jyytzjpwcf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jyytzjpwcf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jyytzjpwcf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jyytzjpwcf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jyytzjpwcf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jyytzjpwcf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jyytzjpwcf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jyytzjpwcf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jyytzjpwcf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jyytzjpwcf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jyytzjpwcf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jyytzjpwcf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jyytzjpwcf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jyytzjpwcf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jyytzjpwcf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jyytzjpwcf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jyytzjpwcf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jyytzjpwcf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jyytzjpwcf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jyytzjpwcf .gt_left {\n  text-align: left;\n}\n\n#jyytzjpwcf .gt_center {\n  text-align: center;\n}\n\n#jyytzjpwcf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jyytzjpwcf .gt_font_normal {\n  font-weight: normal;\n}\n\n#jyytzjpwcf .gt_font_bold {\n  font-weight: bold;\n}\n\n#jyytzjpwcf .gt_font_italic {\n  font-style: italic;\n}\n\n#jyytzjpwcf .gt_super {\n  font-size: 65%;\n}\n\n#jyytzjpwcf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jyytzjpwcf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jyytzjpwcf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jyytzjpwcf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jyytzjpwcf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jyytzjpwcf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jyytzjpwcf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jyytzjpwcf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jyytzjpwcf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"coefficient\">coefficient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"interpretation\">interpretation</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">64.35</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">A non-drinker who slept 8 hours is estimated to have an SDMT score of 64.3</td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">I(hrs_sleep - 8)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">7.65</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">For every additional hour slept, non-drinkers scores on SDMT are estimated to increase by 7.6</td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">alcy</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-10.98</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">drinkers who slept 8 hours are estimated to have 11 lower scores on SDMT than non-drinkers who slept 8 hours</td></tr>\n    <tr><td headers=\"coefficient\" class=\"gt_row gt_left\">I(hrs_sleep - 8):alcy</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-3.59</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">For every additional hour's sleep, drinkers scores on SDMT  increase by 3.6 *less* than they do for non-drinkers</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# The monkeys are back!  \n\n\n\n\n\n\n\n\n\n\n\n:::frame\n__Data: ctmtoys.csv__  \n\nSo far, we have analysed the data for two studies (not real!) of the inquisitive nature of monkeys. Initially ([week 5 exercises](05_ex.html#monkey-exploration){target=\"_blank\"}), Archer, Winther & Gandolfi (2024a) investigated age differences in exploration of novel objects, and found that older monkeys spend on average less time playing with a novel object than their younger counterparts (we looked at this with both with the linear effect of age in years, and by comparing adults to juveniles). Following this, in our [week 7 exercises](07_ex.html#more-monkeys){target=\"_blank\"} Bolton, Archer, Peng, Winther & Gandolfi (2024b) wanted to see if monkeys showed a preference for different _types_ of object (i.e. ones with moving parts vs ones that are soft). They found that, after accounting for differences due to age, monkeys showed a significant preference for toys with moving parts in comparison to soft toys.  \n\nThe same team of researchers are again asking for our help, and this time with a bigger study, of 107 monkeys. They are interested in whether the preference for mechanical toys over soft toys is different for different species of monkey. \nBoth the previous studies were conducted on Rhesus Macaques (a species that have adapted very well to human dominated landscapes), so this study has re-run the same experiment on 0 Capuchin monkeys, 0 Tamarin monkeys and 0 Macaques.  \n\nThe aim of this study is to investigate the following question:  \n\n> Are preferences between soft toys vs mechanical toys different for different species of monkey?  \n\nThe data is available at [https://uoepsy.github.io/data/ctmtoys.csv](https://uoepsy.github.io/data/ctmtoys.csv){target=\"_blank\"} and contains the variables described in @tbl-ctmtoys\n\n\n\n::: {#tbl-ctmtoys .cell layout-align=\"center\" tbl-cap='Data dictionary for ctmtoys.csv'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wyawbndktv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wyawbndktv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wyawbndktv thead, #wyawbndktv tbody, #wyawbndktv tfoot, #wyawbndktv tr, #wyawbndktv td, #wyawbndktv th {\n  border-style: none;\n}\n\n#wyawbndktv p {\n  margin: 0;\n  padding: 0;\n}\n\n#wyawbndktv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wyawbndktv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wyawbndktv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wyawbndktv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wyawbndktv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wyawbndktv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wyawbndktv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wyawbndktv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wyawbndktv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wyawbndktv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wyawbndktv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wyawbndktv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wyawbndktv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wyawbndktv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wyawbndktv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyawbndktv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wyawbndktv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wyawbndktv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wyawbndktv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyawbndktv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wyawbndktv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyawbndktv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wyawbndktv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyawbndktv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wyawbndktv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyawbndktv .gt_left {\n  text-align: left;\n}\n\n#wyawbndktv .gt_center {\n  text-align: center;\n}\n\n#wyawbndktv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wyawbndktv .gt_font_normal {\n  font-weight: normal;\n}\n\n#wyawbndktv .gt_font_bold {\n  font-weight: bold;\n}\n\n#wyawbndktv .gt_font_italic {\n  font-style: italic;\n}\n\n#wyawbndktv .gt_super {\n  font-size: 65%;\n}\n\n#wyawbndktv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wyawbndktv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wyawbndktv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wyawbndktv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wyawbndktv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wyawbndktv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wyawbndktv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wyawbndktv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wyawbndktv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Monkey Name</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age of monkey in years</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">species</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Species (capuchin, macaque, tamarin)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">obj_type</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Type of novel object given (mechanical / soft)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">obj_colour</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Main colour of object (red / green / blue)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">obj_size</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Size of object in cm (length of largest dimension of the object)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">exptime</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Time (in minutes) spent exploring the object</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\nAs always, begin by reading in your data and making some exploratory plots to get an idea of the distributions we're dealing with.  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nEverything looks okay in terms of our variable ranges here:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nctmtoys <- read_csv(\"https://uoepsy.github.io/data/ctmtoys.csv\")\nsummary(ctmtoys)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     name                age          species            obj_type        \n Length:216         Min.   : 1.00   Length:216         Length:216        \n Class :character   1st Qu.: 8.00   Class :character   Class :character  \n Mode  :character   Median :13.00   Mode  :character   Mode  :character  \n                    Mean   :12.92                                        \n                    3rd Qu.:18.00                                        \n                    Max.   :25.00                                        \n  obj_colour           obj_size        exptime     \n Length:216         Min.   : 5.00   Min.   : 4.20  \n Class :character   1st Qu.:36.00   1st Qu.:11.00  \n Mode  :character   Median :49.00   Median :13.45  \n                    Mean   :49.06   Mean   :13.66  \n                    3rd Qu.:62.25   3rd Qu.:16.75  \n                    Max.   :94.00   Max.   :25.10  \n```\n\n\n:::\n:::\n\n\n\n\nLet's shove it in `pairs.panels`:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nctmtoys |> \n  select(age, obj_size, exptime) |>\n  psych::pairs.panels()\n```\n\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nAnd let's tabulate `obj_type` and `species`: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nctmtoys |>\n  select(obj_type, species) |>\n  table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            species\nobj_type     capuchin macaque tamarin\n  mechanical       33      43      32\n  soft             36      33      39\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\nTry making some initial exploratory plots of the relationships in the data that are relevant to the research question.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nWe're wanting to plot `exploration_time` and `obj_type` here, but we're also wanting to show it for each species.  This means we'll need things like colours, facets, etc.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-3' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\nFrom initial exploration - it looks like capuchins are generally spending more time playing with the objects (of both types).  \nThe slight preference for mechanical toys seems to be present Capuchins and Macaques, but it's less clear in the Tamarins.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(ctmtoys, aes(x = obj_type, y = exptime, \n                    col = obj_type)) +\n  geom_violin() + \n  geom_jitter(width=.2, alpha=.4) + \n  facet_wrap(~species)\n```\n\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\nAll of this is just initial speculation, however - we haven't considered lots of things such as the distributions of ages between the species, or whether they all saw objects of similar sizes and colours. These things could make these plots appear to show relationships that are actually driven by other things. They could also make these plots hide relationships that are present once these things are controlled for.  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\nFit an appropriate model to address the research question.  \nThink about what we already know from previous studies - we'll likely want to control for age and for other aspects of objects like size and colour.  \n\nThen think about the specific research question and what is needed to test it.  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodelmonkey <- lm(exptime ~ age + obj_size + obj_colour +\n                obj_type * species, data = ctmtoys)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\nNow that you've fitted your model, test the interaction to get an overall answer to \"Do species differ in their preference for different types of object?\"  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThink about how the question is worded - there's no \"how\"/\"what\" etc, it's just \"*are* there differences?\" (this is just the same as we did last week, and in [8B #testing-group-differences](08b_catpred.html#testing-group-differences){target=\"_blank\"} - try a model comparison?).  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nLet's compare a reduced model _without_ the interaction to our model _with_ the interaction:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodelmonkey0 <- lm(exptime ~ age + obj_size + obj_colour +\n                obj_type + species, data = ctmtoys)\n\nanova(modelmonkey0, modelmonkey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: exptime ~ age + obj_size + obj_colour + obj_type + species\nModel 2: exptime ~ age + obj_size + obj_colour + obj_type * species\n  Res.Df    RSS Df Sum of Sq      F  Pr(>F)  \n1    208 2339.2                              \n2    206 2257.0  2    82.136 3.7483 0.02518 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\nAlternatively, we could use the shortcut and just give one model to `anova()` and take a look at the last line. They should be the same:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(modelmonkey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: exptime\n                  Df  Sum Sq Mean Sq F value    Pr(>F)    \nage                1  293.67  293.67 26.8034 5.340e-07 ***\nobj_size           1    0.42    0.42  0.0381   0.84546    \nobj_colour         2    8.91    4.46  0.4067   0.66636    \nobj_type           1  177.27  177.27 16.1798 8.085e-05 ***\nspecies            2  892.98  446.49 40.7517 1.225e-15 ***\nobj_type:species   2   82.14   41.07  3.7483   0.02518 *  \nResiduals        206 2257.02   10.96                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n:::int\nSpecies significantly differed in the extent to which exploration time varied between different types of object ($F(2, 206)=3.75, p=0.0252$).  \n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 11</div><div class='question-body'>\n\n\nWe're almost always going to want to know __how__ species differ in their preferences for different types of object (if they do differ).  \n\nTo get this information, we can just look at the model coefficients.  \nTake a look at the interaction coefficients - notice anything that _appears to_ contradict the previous question?  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-4' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(modelmonkey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = exptime ~ age + obj_size + obj_colour + obj_type * \n    species, data = ctmtoys)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-8.959 -2.348 -0.045  2.015  9.745 \n\nCoefficients:\n                            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                 19.33098    1.03529  18.672  < 2e-16 ***\nage                         -0.16464    0.03961  -4.157 4.73e-05 ***\nobj_size                     0.01122    0.01252   0.896   0.3712    \nobj_colourgreen             -0.14963    0.55815  -0.268   0.7889    \nobj_colourred               -0.19467    0.55887  -0.348   0.7279    \nobj_typesoft                -1.96193    0.80839  -2.427   0.0161 *  \nspeciesmacaque              -3.90720    0.77012  -5.073 8.70e-07 ***\nspeciestamarin              -5.08712    0.82839  -6.141 4.16e-09 ***\nobj_typesoft:speciesmacaque -1.51124    1.11855  -1.351   0.1782    \nobj_typesoft:speciestamarin  1.53986    1.15128   1.338   0.1825    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.31 on 206 degrees of freedom\nMultiple R-squared:  0.392,\tAdjusted R-squared:  0.3655 \nF-statistic: 14.76 on 9 and 206 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nIn our model coefficients, both interaction terms are non-significant.  \nBut we just said before that in the previous question that there _is_ an interaction (we got our F test for it).  \n\nThe coefficients above are telling us that, compared to the reference species (capuchins), neither macaques nor tamarins show significant differences in their preference for mechanical toys vs soft toys.  \n\nBut while macaques and tamarins may not be different from capuchins, it is entirely possible that macaques and tamarins could be different _from each other_?  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 12</div><div class='question-body'>\n\n\nModel coefficients are always relative to some reference point (i.e. capuchins with mechanical toys).  \n\n1. Change the reference point to Macaques with soft toys.  \n2. Refit the model.\n3. Interpret the coefficients.  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-5' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\nWe always get to choose which level we want as a reference. Sometimes, this will be easy because on level represents the norm/status quo. In this context, Macaques is possibly a more useful reference, given that the study description earlier mentioned the previous studies were conducted on Macaques.   \n\nRe-levelling `obj_type` to have \"soft\" as the reference won't make much difference - it will just swap the signs of the coefficients (comparing mechanical to soft, as opposed to comparing soft to mechanical).  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nctmtoys <- \n  ctmtoys |>\n  mutate(\n    species = fct_relevel(species, \"macaque\"),\n    obj_type = fct_relevel(obj_type, \"soft\")\n  )\n\nlm(exptime ~ age + obj_size + obj_colour +\n                obj_type * species, data = ctmtoys) |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = exptime ~ age + obj_size + obj_colour + obj_type * \n    species, data = ctmtoys)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-8.959 -2.348 -0.045  2.015  9.745 \n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                        11.95061    1.01699  11.751  < 2e-16 ***\nage                                -0.16464    0.03961  -4.157 4.73e-05 ***\nobj_size                            0.01122    0.01252   0.896  0.37122    \nobj_colourgreen                    -0.14963    0.55815  -0.268  0.78890    \nobj_colourred                      -0.19467    0.55887  -0.348  0.72794    \nobj_typemechanical                  3.47317    0.76957   4.513 1.07e-05 ***\nspeciescapuchin                     5.41843    0.80728   6.712 1.83e-10 ***\nspeciestamarin                      1.87117    0.80555   2.323  0.02116 *  \nobj_typemechanical:speciescapuchin -1.51124    1.11855  -1.351  0.17816    \nobj_typemechanical:speciestamarin  -3.05110    1.11480  -2.737  0.00674 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.31 on 206 degrees of freedom\nMultiple R-squared:  0.392,\tAdjusted R-squared:  0.3655 \nF-statistic: 14.76 on 9 and 206 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThese coefficients show us that Macaques tend to spend 3.5 more minutes playing with mechanical toys than soft toys, and that Capuchins do not significantly differ in this respect, but Tamarins do. Relative to Macaques, Tamarins spend 3.05 less additional time with mechanical toys compared to soft toys.  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 13</div><div class='question-body'>\n\n\nThe interpretation of interaction coefficients tends to be quite confusing, and invariably it helps to tie these to a visualisation. We're going to do it manually here, because it's a very useful learning exercise. \n\nBelow are our coefficients of interest from the model, when the reference level for `obj_type` is \"soft\" and for `species` is \"macaque\".  \n```\n...\nobj_typemechanical                  3.47317    0.76957   4.513 1.07e-05 ***\nspeciescapuchin                     5.41843    0.80728   6.712 1.83e-10 ***\nspeciestamarin                      1.87117    0.80555   2.323  0.02116 *  \nobj_typemechanical:speciescapuchin -1.51124    1.11855  -1.351  0.17816    \nobj_typemechanical:speciestamarin  -3.05110    1.11480  -2.737  0.00674 ** \n```\n\nGrab a piece of paper, and draw the points for each species & obj_type combination, relative to the reference point.  \nStart with the plot below:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-6' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  Solution Part 1 - coefficient: obj_typemechanical</button></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\n\nThe coefficient \"obj_typemechanical\" tells us the difference between soft and mechanical toys _when species is zero_ - i.e., when it is at the reference level (macaques).  \n\nSo we know that macaques spend 3.5 more minutes with mechanical toys compared to soft toys:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-7' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  Solution Part 2 - coefficient: speciescapuchin</button></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\n\nThe coefficient \"speciescapuchin\" tells us the difference between capuchins and macaques, _when obj_type is zero_ - i.e., when it is at the reference level (soft).  \n\nSo we know that capuchins spend 5.4 more minutes with soft toys compared to macaques with soft toys:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-8' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-8', 'sol-start-8')\">  Solution Part 3 - coefficient: speciestamarin</button></div><div class=\"solution-body\" id = \"sol-body-8\" style=\"display: none;\">\n\n\n\nThe coefficient \"speciestamarin\" tells us the difference between tamarins and macaques, _when obj_type is zero_ - i.e., when it is at the reference level (soft).  \n\nSo we know that tamarins spend 1.9 more minutes with soft toys compared to macaques with soft toys:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-9' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-9', 'sol-start-9')\">  Solution Part 4 - coefficient: obj_typemechanical:speciescapuchin</button></div><div class=\"solution-body\" id = \"sol-body-9\" style=\"display: none;\">\n\n\n\nThe coefficient \"obj_typemechanical:speciescapuchin\" tells us the difference between capuchins and macaques' soft-vs-mechanical differences.  \ni.e. when moving from macaques to capuchins, the soft-to-mechanical difference changes by this much.  \n\nSo we know that whereas macaques spend 3.5 more minutes with mechanical toys compared to soft toys, for capuchins this is 1.5 minutes less.  \nSo rather than going up 3.5, we go up $3.5-1.5=2$.  \n\nHowever, this is non-significant. So the difference could easily just be 0 - i.e. they could increase by the same 3.5 minutes as Macaques do. So we know that the uncertainty here should also capture as if Capuchins and Macaques have the same increases from soft to mechanical.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-34-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-10' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-10', 'sol-start-10')\">  Solution Part 5 - coefficient: obj_typemechanical:speciestamarin</button></div><div class=\"solution-body\" id = \"sol-body-10\" style=\"display: none;\">\n\n\n\nThe coefficient \"obj_typemechanical:speciestamarin\" tells us the difference between tamarins and macaques' soft-vs-mechanical differences.  \ni.e. when moving from macaques to tamarins, the soft-to-mechanical difference changes by this much.  \n\nSo we know that whereas macaques spend 3.5 more minutes with mechanical toys compared to soft toys, for tamarins this is 3.05 minutes less.  \nSo rather than going up 3.5, we go up $3.5-3.05=0.45$:    \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-35-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 14</div><div class='question-body'>\n\n\nOkay, now let's make a plot in R.  \n\nTry running this code in pieces to see what each bit does, and then running it all at once to get the plot.  \n\nDoes it match with what you sketched in the previous question?  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effects)\neffect(\"obj_type*species\",modelmonkey) |>\n  as.data.frame() |>\n  mutate(\n    obj_type = fct_relevel(factor(obj_type), \"soft\")\n  ) |>\n  ggplot(aes(x=obj_type, y=fit, col=species)) +\n  geom_pointrange(aes(ymin=lower,ymax=upper))\n```\n:::\n\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n#### Why use the effects package?  \n\nUp to now, when we've been plotting our associations of interest we've been choosing to construct our plots at the mean of our other predictors.  \n\nHowever, in our current monkey model, we've also got a categorical covariate (`obj_colour`) in our model. What should we do with that?\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplotdat <- expand_grid(\n  age = mean(ctmtoys$age),\n  obj_size = mean(ctmtoys$obj_size),\n  obj_colour = ???\n  obj_type = c(\"soft\",\"mechanical\"), # of interest\n  species = c(\"macaque\",\"capuchin\",\"tamarin\") # of interest\n)\n```\n:::\n\n\n\n\nWe could:\n\na) choose just one colour to plot it at\nb) make separate plots to  each colour\nc) plot the association of interest holding the colours at their proportions\n\nTo achieve a) or b), we can use the strategy we have been using already (make a little dataframe, use `augment` etc).  \n\nHowever, to achieve c), it is easiest to use something like the `effect()` function from the __effects__ package. This will also come in handy next semester, as we will use it for plotting effects from more complex models.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effects)\neffect(\"obj_type*species\",modelmonkey) |>\n  as.data.frame() |>\n  mutate(\n    obj_type = fct_relevel(factor(obj_type), \"soft\")\n  ) |>\n  ggplot(aes(x=obj_type, y=fit, col=species)) +\n  geom_pointrange(aes(ymin=lower,ymax=upper))\n```\n\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-38-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Teamwork and Communication\n\n:::frame\n__Dataset: teamprod.csv__  \n\nA company has recently decided to move towards having more structured team-based projects for its employees, rather than giving individual projects. They want better understanding what makes teams work well together. Specifically, they want to know whether the amount of communication in a team is associated with better quality work, and if this is different depending upon the teams' 'collective efficacy' (their belief in their ability to do the work)?   \n\nThey have collected data on 80 teams. Prior to starting the projects, each team completed a questionnaire measuring 'collective efficacy' (the teams' belief in their ability to succeed at their project), and 'collective experience' (a measure of how much relevant experience the team has). At the end of the projects, each team's work was rated across various measures (timeliness, quality, relevance etc) to provide a metric of 'work quality'. In addition, information was gathered on the volume of each teams' communication (via the company's workspace chat platform). \n\nThe data is available at [https://uoepsy.github.io/data/teamqual.csv](https://uoepsy.github.io/data/teamqual.csv){target=\"_blank\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jtialxhwzr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jtialxhwzr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jtialxhwzr thead, #jtialxhwzr tbody, #jtialxhwzr tfoot, #jtialxhwzr tr, #jtialxhwzr td, #jtialxhwzr th {\n  border-style: none;\n}\n\n#jtialxhwzr p {\n  margin: 0;\n  padding: 0;\n}\n\n#jtialxhwzr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jtialxhwzr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jtialxhwzr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jtialxhwzr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jtialxhwzr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jtialxhwzr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jtialxhwzr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jtialxhwzr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jtialxhwzr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jtialxhwzr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jtialxhwzr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jtialxhwzr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jtialxhwzr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jtialxhwzr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jtialxhwzr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jtialxhwzr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jtialxhwzr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jtialxhwzr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jtialxhwzr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jtialxhwzr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jtialxhwzr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jtialxhwzr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jtialxhwzr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jtialxhwzr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jtialxhwzr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jtialxhwzr .gt_left {\n  text-align: left;\n}\n\n#jtialxhwzr .gt_center {\n  text-align: center;\n}\n\n#jtialxhwzr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jtialxhwzr .gt_font_normal {\n  font-weight: normal;\n}\n\n#jtialxhwzr .gt_font_bold {\n  font-weight: bold;\n}\n\n#jtialxhwzr .gt_font_italic {\n  font-style: italic;\n}\n\n#jtialxhwzr .gt_super {\n  font-size: 65%;\n}\n\n#jtialxhwzr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jtialxhwzr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jtialxhwzr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jtialxhwzr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jtialxhwzr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jtialxhwzr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jtialxhwzr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jtialxhwzr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jtialxhwzr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">team_id</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Team ID</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">commvol</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Volume of communication (avg messages per day)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">exp</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Prior experience (Z-scored)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">colleff</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Collective Efficacy measure of team's belief in ability to succeed (range 0 - 70)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">work_qual</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Work Quality measure (metric based on timeliness, quality, relevance etc). Ranges 0 to Infinity</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n:::\n\n\n\n\n<div class='question-begin'>Question 15</div><div class='question-body'>\n\n\nBelow, we have provided a regression table, a plot, and a written paragraph.  \n\nThere are _lots_ of mistakes in the writing (both mismatching numbers _and_ errors in interpretation). Note down as many errors as you can find.  \nFeel free to read in the data yourself to play around.  \n\n::::panelset\n:::panel\n#### Table\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"4\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">work qual</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">std. Error</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Statistic</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;25.29</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">15.21</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;1.66</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.100</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">exp</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.87</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.42</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.674</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">commvol</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.69</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.45</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">6.04</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">colleff</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.60</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.44</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">3.63</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">commvol × colleff</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.04</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.01</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;2.63</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.010</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"4\">80</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">0.603 / 0.582</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n:::\n:::panel\n#### Plot\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_ex_files/figure-html/unnamed-chunk-41-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n:::\n:::panel\n#### Writing\n\nWork quality was modelled using multiple regression. Team experience (Z-scored), Communication volume (messages per day) and Collective efficacy (Z-scored) were included as predictors, along with the interaction between communication and collective efficacy. The model explained 80% of the variance in work-quality scores. More experienced teams were found to produce significantly better quality work ($\\beta=0.82, t(74)=0.4, p>.05$). Volume of communication was significantly associated with work quality ($\\beta=2.68, t(75)=6.17, p<.001$), suggesting that teams that communicate more produced better quality work. Collective efficacy was also significantly associated with work quality ($\\beta=1.59, t(75)=3.64, p<.001$), indicating that better quality work will be produced by a team that has collective efficacy (compared to those that do not). A significant interaction ($\\beta=-0.03, t=2.68, p < .09$) was found between volume of communication and collective efficacy, suggesting that these two predictors are related. Overall these results suggest that for teams that have more collective efficacy, communication is more important in producing quality work.  \n\n:::\n::::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "09_ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}