---
title: "Untitled"
author: "uoepsy.github.io"
date: "12/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glue)
library(tidyverse)
library(knitr)
```

```{r}


lecs = list.files("lectures", ".html", full.names=T)
labs = list.files("labs", ".html", full.names=T)

data.frame(
  Week = 0:11,
  Lecture = c(
    glue("[Welcome]({lecs[2]})"),
    glue("[Introductions and throwing dice]({lecs[3]})"),
    glue("[Measurement and Distributions]({lecs[6]})"),
    glue("[Testing Statistical Hypotheses]({lecs[7]})"),
    glue("[More Tests]({lecs[8]})"),
    glue("[Correlations]({lecs[9]})"),
    glue("Break Week!"),
    glue("[The Linear Model]({lecs[10]})"),
    glue("[The Linear Model (ctd)]({lecs[11]})"),
    glue("[Scaling, Contrasts, Interactions]({lecs[12]})"),
    glue("[The Generalized Linear Model]({lecs[13]})"),
    glue("[Some Kind of End to the Course]({lecs[5]})")
  ),
  Workbook = c(
    glue("[Getting Started with R & RStudio]({labs[1]})"),
    glue("[Categorical Data]({labs[2]})"),
    glue("[Numeric Data]({labs[3]})"),
    glue("[Hypothesis Testing]({labs[4]})"),
    glue("[More Tests]({labs[5]})"),
    glue("[Cov, Cor, Functions & Models]({labs[6]})"),
    glue("--"),
    glue("[Messy Data]({labs[7]})"),
    glue("[Linear Regression]({labs[8]})"),
    glue("[More Linear Regression]({labs[10]})"),
    glue("[GLM!]({labs[11]})"),
    glue("[Writing Up]({labs[12]})")
  )
) %>% kable()


```

