project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
  output-dir: ../docs2/labs

website:
  title: "USMR"
  navbar:
    left:
      - text: "Week 1"
        menu:
        - text: "Chapter 1: First look at R/RStudio"
          href: 01_R.html
        - text: "Chapter 2: More R: Basic Data Skills"
          href: 02_data.html
        - text: "Exercises"
          href: ex01.html
      - text: "Week 2"
        menu:
        - text: "Chapter 3: Measurements & Distributions"
          href: 03_measurement.html
        - text: "Chapter 4: Sampling & Curves"
          href: 04_sampling.html
        - text: "Exercises"
          href: ex02.html
      - text: "Week 3"
        menu: 
        - text: "Chapter 5: Foundations of Inference"
          href: 05_inference.html
        - text: "Chapter 6: Practical Inference"
          href: 06_inference2.html


format:
  html:
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: "assets/toggling.html"
    number-sections: false


