---
title: "Week 2 exercises"
reference-location: margin
citation-location: margin
---

```{r setup, include=FALSE}
source('assets/setup.R')
library(xaringanExtra)
xaringanExtra::use_panelset()
```

# Data manipulation & visualisation

:::frame
In the last couple of years during welcome week, we have asked students of the statistics courses in the Psychology department to fill out a little survey. Anonymised data are available at https://uoepsy.github.io/data/surveydata_allcourse.csv. 
:::



:::qq
create new variable in the dataset which indicates whether people are > 6 foot (182cm).
:::
:::column-margin
mutate(), remember to assign `mydata <- mydata %>% mutate(...)`
:::
  
:::qq
what percentage of respondents are >=6foot?
:::
:::column-margin
table / sum(table)
:::

:::qq
how many of USMR students in `r paste0(as.numeric(substr(Sys.Date(),1,4)),"/",as.numeric(substr(Sys.Date(),3,4))+1)` are born in the same month as you? 
:::
:::column-margin
filter() then either select |> table, or count
:::

:::qq
calculate the mean and sd of heights of all respondents
can you do this using the tidyverse syntax?
:::
:::column-margin
mean(), sd(). summarise?  
na.rm = T
:::

:::qq
plot the distribution of heights of all respondents
:::
:::column-margin
ggplot
:::

:::qq
calculate the mean and standard deviation of heights for students for each course 
:::
:::column-margin
group_by summarise
:::

:::qq
plot the distributions of heights for each course. 
:::
:::column-margin
colour or facet
:::

:::qq
What proportion of respondents are taller than you?  
:::
:::column-margin
remember that we can sum() a condition as a quick way of counting.   
`sum(surveydata$birthmonth == "Jan")` adds up all the TRUE responses.  
:::


# Estimates & Intervals

:::qq
Suppose we are interested in the average life-satisfaction rating of MSc students at Edinburgh University.  

We only asked this question to students in USMR in `r paste0(as.numeric(substr(Sys.Date(),1,4)),"/",as.numeric(substr(Sys.Date(),3,4))+1)`, so to make things easier, let's create a subset of the dataset which includes only those students. 
:::
:::column-margin
`filter(..., ... )`
:::

:::qq
For the USMR students in `r paste0(as.numeric(substr(Sys.Date(),1,4)),"/",as.numeric(substr(Sys.Date(),3,4))+1)`, calculate the following: 

- mean life satisfaction rating
- standard deviation of life satisfaction ratings
- number of respondents who completed life satisfaction rating

:::
:::column-margin

:::

:::qq
Using your answers to the previous question, construct a 95% confidence interval for the mean life satisfaction rating.  

Why might it be a _bad_ idea to use this as an estimate of the average life-satisfaction rating of all MSc students at Edinburgh University?  
:::
:::column-margin
think about who makes up the sample (e.g. usmr students)
:::

