{
  "hash": "1b992f36ff9d1566e38bec4542a727a5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercises: Scaling | Categorical Predictors\"\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n\n# Pictures of a Brain\n\n:::frame\n__neuronews.csv__  \n\n\n\n\n\n\n\n\n\nThis dataset is from a study^[not a real one, but inspired very loosely by [this one](https://bpspsychub.onlinelibrary.wiley.com/doi/full/10.1111/bjep.12162){target=\"_blank\"}] looking at the influence of presenting scientific news with different pictures on how believable readers interpret the news.  \n\n120 participants took part in the study. Participation involved reading a short article about some research in neuroscience, and then rating how credible they found the research. Participants were randomly placed into one of three conditions, in which the article was presented a) in text alone, b) with a picture of a brain, or c) with a picture of a brain and a fancy looking (but unrelated to the research) graph. They rated credibility using a sliding scale from 0 to 100, with higher values indicating more credibility.  \n\nThe data is available at [https://uoepsy.github.io/data/usmr_neuronews.csv](https://uoepsy.github.io/data/usmr_neuronews.csv){target=\"_blank\"}.  \n\n\n\n\n::: {.cell layout-align=\"center\" tbl-cap='usmr_neuronews.csv data dictionary'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lbampyrlcu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lbampyrlcu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lbampyrlcu thead, #lbampyrlcu tbody, #lbampyrlcu tfoot, #lbampyrlcu tr, #lbampyrlcu td, #lbampyrlcu th {\n  border-style: none;\n}\n\n#lbampyrlcu p {\n  margin: 0;\n  padding: 0;\n}\n\n#lbampyrlcu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lbampyrlcu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lbampyrlcu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lbampyrlcu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lbampyrlcu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lbampyrlcu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lbampyrlcu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lbampyrlcu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lbampyrlcu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lbampyrlcu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lbampyrlcu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lbampyrlcu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lbampyrlcu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lbampyrlcu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lbampyrlcu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lbampyrlcu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lbampyrlcu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lbampyrlcu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lbampyrlcu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lbampyrlcu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lbampyrlcu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lbampyrlcu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lbampyrlcu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lbampyrlcu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lbampyrlcu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lbampyrlcu .gt_left {\n  text-align: left;\n}\n\n#lbampyrlcu .gt_center {\n  text-align: center;\n}\n\n#lbampyrlcu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lbampyrlcu .gt_font_normal {\n  font-weight: normal;\n}\n\n#lbampyrlcu .gt_font_bold {\n  font-weight: bold;\n}\n\n#lbampyrlcu .gt_font_italic {\n  font-style: italic;\n}\n\n#lbampyrlcu .gt_super {\n  font-size: 65%;\n}\n\n#lbampyrlcu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lbampyrlcu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lbampyrlcu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lbampyrlcu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lbampyrlcu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lbampyrlcu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lbampyrlcu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lbampyrlcu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lbampyrlcu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">pid</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant ID</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Name</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">condition</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Condition (text-only / text+brain / text+brain+graph)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">credibility</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Credibility rating (0-100)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nRead in the data and take a look around (this is almost always the first thing to do!)  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnndat <- read_csv(\"https://uoepsy.github.io/data/usmr_neuronews.csv\")\n\nhist(nndat$credibility)\n```\n\n::: {.cell-output-display}\n![](08_ex_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=80%}\n:::\n\n```{.r .cell-code}\n# geom jitter is a way of randomly 'jittering' points so that the don't overlap\n# i want them to be the right height, so no jitter in height, but i'll give them a little width jitter\nggplot(nndat, aes(x=condition,y=credibility)) +\n   geom_jitter(height = 0, width = .2)\n```\n\n::: {.cell-output-display}\n![](08_ex_files/figure-html/unnamed-chunk-4-2.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\nFit a model examining whether credibility of the research article differs between conditions.  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod1 <- lm(credibility ~ condition, data = nndat)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nDo conditions differ in credibility ratings?  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThis is an overall question, not asking about differences between specific levels. You can find a way to test this question either at the bottom of the `summary()` output, or by comparing it with a model without condition differences in it (see [8B #testing-group-differences](08b_catpred.html#testing-group-differences){target=\"_blank\"}).  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nWe can either do this as a model comparison:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod0 <- lm(credibility ~ 1, data = nndat)\nanova(mod0, mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: credibility ~ 1\nModel 2: credibility ~ condition\n  Res.Df   RSS Df Sum of Sq      F  Pr(>F)  \n1    119 12820                              \n2    117 12146  2    674.03 3.2464 0.04245 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nand this info is also at the bottom of the summary, because we just have one predictor in the model\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mod1)\n```\n:::\n\n\n\n```\nF-statistic: 3.246 on 2 and 117 DF,  p-value: 0.04245\n```\n\n:::int\nConditions significantly differed in credibility ratings $F(2,117) = 3.25, p = .0425$\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\n__How__ do groups differ?  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nNote that this is a subtly different question to the previous one. It will require us to look at something that tests between specific groups ([8B #testing-differences-between-specific-groups](08b_catpred.html#testing-differences-between-specific-groups){target=\"_blank\"}).  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = credibility ~ condition, data = nndat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-26.4476  -6.6086  -0.3778   6.5657  26.8589 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                 59.663      1.611  37.035   <2e-16 ***\nconditiontext+brain          4.909      2.278   2.155   0.0332 *  \nconditiontext+brain+graph    5.138      2.278   2.255   0.0260 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.19 on 117 degrees of freedom\nMultiple R-squared:  0.05258,\tAdjusted R-squared:  0.03638 \nF-statistic: 3.246 on 2 and 117 DF,  p-value: 0.04245\n```\n\n\n:::\n:::\n\n\n\n\n:::int\nCompared to when presented in text-only, conditions where the article was presented alongside a picture of a brain, or alongside both a brain-picture and a graph, resulted in higher average credibility ratings. Including a picture of a brain was associated with a 4.91 increase in credibility over the text-only article ($b = 4.91$, $t(117)=2.15$, $p=0.033$), and including both a brain-picture and a graph was associated with a 5.14 higher average credibility rating ($b = 5.14$, $t(117)=2.26$, $p=0.026$).  \n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\nLet's prove something to ourselves.  \nBecause we have no other predictors in the model, it should be possible to see how the coefficients from our model map exactly to the group means.  \n\nCalculate the mean credibility for each condition, and compare with your model coefficients.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nTo calculate group means, we can use `group_by()` and `summarise()`! \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-1' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-1', 'sol-start-1')\">  Solution Part 1 - calculate group means</button></div><div class=\"solution-body\" id = \"sol-body-1\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnndat |> \n  group_by(condition) |>\n  summarise(\n    meancred = mean(credibility)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  condition        meancred\n  <chr>               <dbl>\n1 text+brain           64.6\n2 text+brain+graph     64.8\n3 text-only            59.7\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution Part 2 - compare to the coefficients</button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\nHere are our model coefficients:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              (Intercept)       conditiontext+brain conditiontext+brain+graph \n                59.662662                  4.909058                  5.138197 \n```\n\n\n:::\n:::\n\n\n\n\nAnd here are our means:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnndat |> \n  group_by(condition) |>\n  summarise(\n    meancred = mean(credibility)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  condition        meancred\n  <chr>               <dbl>\n1 text+brain           64.6\n2 text+brain+graph     64.8\n3 text-only            59.7\n```\n\n\n:::\n:::\n\n\n\n\nWe can see that the intercept is the mean of the `text-only` group.  \n\nThe next coefficient - named \"conditiontext+brain\" is the difference from the `text-only` group to the `text+brain` group.  \n\nThe final coefficient - named \"conditiontext+brain+graph\" is the difference from the `text-only` group to the `text+brain+graph` group.  \n\nSo this means we can get to our group means by using:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(mod1)[c(1,2)] |> sum() # the mean of text+brain\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64.57172\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(mod1)[c(1,3)] |> sum() # the mean of text+brain+graph\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64.80086\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Detectorists\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\nWe saw this study briefly at the end of last week and we're going to continue where we left off.  \n\nBelow is the description of the study, and the code that we had given you to clean the data and fit a model that assessed whether different strategies (e.g. breathing, closing eyes) were associated with changes in heart rate during a lie-detection test. The model also accounts for differences in heart rates due to age and pre-test anxiety.  \n\nRun the code given below to ensure that we are all at the same place.  \n\n::: {.callout-note collapse=\"true\"}\n#### Study: Lie detectors\n\n\n\n\n\n\n\n\n\nLaw enforcement in some countries regularly rely on 'polygraph' tests as a form of 'lie detection'. These tests involve measuring heart rate, blood pressure, respiratory rate and sweat. However, there is very little evidence to suggest that these methods are remotely accurate in being able to determine whether or not someone is lying.  \n\nResearchers are interested in if peoples' heart rates during polygraph tests can be influenced by various pre-test strategies, including deep breathing, or closing their eyes. They recruited 142 participants (ages 22 to 64). Participants were told they were playing a game in which their task was to deceive the polygraph test, and they would receive financial rewards if they managed successfully. At the outset of the study, they completed a questionnaire which asked about their anxiety in relation to taking part. Participants then chose one of 4 strategies to prepare themselves for the test, each lasting 1 minute. These were \"do nothing\", \"deep breathing\", \"close your eyes\" or \"cough\"^[apparently coughing is a method of immediately lowering heart rate!]. The average heart rate of each participant was recorded during their test. \n\n\n\n\n::: {.cell layout-align=\"center\" tbl-cap='usmr_polygraph.csv data dictionary'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vqdjjwwtuv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vqdjjwwtuv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vqdjjwwtuv thead, #vqdjjwwtuv tbody, #vqdjjwwtuv tfoot, #vqdjjwwtuv tr, #vqdjjwwtuv td, #vqdjjwwtuv th {\n  border-style: none;\n}\n\n#vqdjjwwtuv p {\n  margin: 0;\n  padding: 0;\n}\n\n#vqdjjwwtuv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vqdjjwwtuv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vqdjjwwtuv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vqdjjwwtuv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vqdjjwwtuv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vqdjjwwtuv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vqdjjwwtuv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vqdjjwwtuv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vqdjjwwtuv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vqdjjwwtuv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vqdjjwwtuv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vqdjjwwtuv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vqdjjwwtuv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vqdjjwwtuv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vqdjjwwtuv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqdjjwwtuv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vqdjjwwtuv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vqdjjwwtuv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vqdjjwwtuv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqdjjwwtuv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vqdjjwwtuv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqdjjwwtuv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vqdjjwwtuv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqdjjwwtuv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vqdjjwwtuv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqdjjwwtuv .gt_left {\n  text-align: left;\n}\n\n#vqdjjwwtuv .gt_center {\n  text-align: center;\n}\n\n#vqdjjwwtuv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vqdjjwwtuv .gt_font_normal {\n  font-weight: normal;\n}\n\n#vqdjjwwtuv .gt_font_bold {\n  font-weight: bold;\n}\n\n#vqdjjwwtuv .gt_font_italic {\n  font-style: italic;\n}\n\n#vqdjjwwtuv .gt_super {\n  font-size: 65%;\n}\n\n#vqdjjwwtuv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vqdjjwwtuv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vqdjjwwtuv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vqdjjwwtuv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vqdjjwwtuv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vqdjjwwtuv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vqdjjwwtuv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vqdjjwwtuv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vqdjjwwtuv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age of participant (years)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">anx</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Anxiety measure (Z-scored)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">strategy</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Pre-test Strategy (0 = do nothing, 1 = close eyes, 2 = cough, 3 = deep breathing)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">hr</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Average Heart Rate (bpm) during test</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n__Analysis__  \n\nExpand the code box below to see some analysis!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# load libraries\nlibrary(tidyverse)\nlibrary(psych)\n# read in the data\nliedf <- read_csv(\"https://uoepsy.github.io/data/usmr_polygraph.csv\")\n\n# there seems to be a 5 there.. \ntable(liedf$strategy)\n# the other variables look okay though\ndescribe(liedf)\npairs.panels(liedf)\n\nliedf <- liedf |> \n  filter(strategy!=5) |>\n  mutate(\n    # strategy is a factor. but currently numbers\n    # i'm going to give them better labels too.. \n    # to do this is need to tell factor() what \"levels\" to look for\n    # and then give it some \"labels\" to apply to those.\n    strategy = factor(strategy, \n                      levels = c(\"0\",\"1\",\"2\",\"3\"),\n                      labels = c(\"do nothing\", \"close eyes\",\n                                 \"cough\", \"deep breathing\")\n                      )\n  )\n\nliemod <- lm(hr ~ age + anx + strategy, data = liedf)\n\n# Does HR differ between strategies?\nanova(liemod)\n# the above is a shortcut for getting this comparison out:\nanova(\n  lm(hr ~ age + anx, data = liedf),\n  lm(hr ~ age + anx + strategy, data = liedf)\n)\n```\n:::\n\n\n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n\n\n\n\n\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\nOur model includes a predictor with 4 levels (the 4 different strategies).  \n\nThis means we will have 3 coefficients pertaining to this predictor. Take a look at them. Write a brief sentence explaining what each one represents.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nWe're still all using R's defaults ([8B #treatment-contrasts-the-default](08b_catpred.html#treatment-contrasts-the-default){target=\"_blank\"}), so these follow the logic we have seen already above. \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(liemod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           (Intercept)                    age                    anx \n            45.5463008              0.2923910              2.9474446 \n    strategyclose eyes          strategycough strategydeep breathing \n            -0.8836002             -3.9818287             -5.8436306 \n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"crkjeetixm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#crkjeetixm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#crkjeetixm thead, #crkjeetixm tbody, #crkjeetixm tfoot, #crkjeetixm tr, #crkjeetixm td, #crkjeetixm th {\n  border-style: none;\n}\n\n#crkjeetixm p {\n  margin: 0;\n  padding: 0;\n}\n\n#crkjeetixm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#crkjeetixm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#crkjeetixm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#crkjeetixm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#crkjeetixm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#crkjeetixm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#crkjeetixm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#crkjeetixm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#crkjeetixm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#crkjeetixm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#crkjeetixm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#crkjeetixm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#crkjeetixm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#crkjeetixm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#crkjeetixm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#crkjeetixm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#crkjeetixm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#crkjeetixm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#crkjeetixm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#crkjeetixm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#crkjeetixm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#crkjeetixm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#crkjeetixm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#crkjeetixm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#crkjeetixm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#crkjeetixm .gt_left {\n  text-align: left;\n}\n\n#crkjeetixm .gt_center {\n  text-align: center;\n}\n\n#crkjeetixm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#crkjeetixm .gt_font_normal {\n  font-weight: normal;\n}\n\n#crkjeetixm .gt_font_bold {\n  font-weight: bold;\n}\n\n#crkjeetixm .gt_font_italic {\n  font-style: italic;\n}\n\n#crkjeetixm .gt_super {\n  font-size: 65%;\n}\n\n#crkjeetixm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#crkjeetixm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#crkjeetixm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#crkjeetixm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#crkjeetixm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#crkjeetixm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#crkjeetixm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#crkjeetixm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#crkjeetixm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"interpretation\">interpretation</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">45.55</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated HR for someone age 0, anxiety 0 (the mean), who 'does nothing' prior to the test</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.29</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated change in HR for an additional year of age, holding constant anxiety and strategy</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">anx</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">2.95</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated change in HR for an additional SD of anxiety, holding constant age and strategy</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">strategyclose eyes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-0.88</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated difference in HR between 'doing nothing' strategy and 'close eyes' strategy, holding constant age and anxiety</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">strategycough</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-3.98</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated difference in HR between 'doing nothing' strategy and 'cough' strategy, holding constant age and anxiety</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">strategydeep breathing</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-5.84</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated difference in HR between 'doing nothing' strategy and 'deep breathing' strategy, holding constant age and anxiety</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\nCalculate the mean heart rate for each strategy group.  \nDo they match to our model coefficients?  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-3' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nliedf |> \n  group_by(strategy) |>\n  summarise(\n    meanHR = mean(hr)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  strategy       meanHR\n  <fct>           <dbl>\n1 do nothing       54.2\n2 close eyes       55.7\n3 cough            54.1\n4 deep breathing   55.0\n```\n\n\n:::\n:::\n\n\n\n\nThey don't match! For instance, in our group means above the 'close eyes' strategy has a _higher_ average heart rate than the 'do nothing' strategy. But that's not what our model coefficients said - they said the opposite! \n\nWhy is this? It's because we have other things in our model, so these model estimated differences are now \"holding age and anxiety constant\". \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\nAt the end last week's exercises, we wanted you to make a plot of the model estimated differences in heart rates between the strategies.  \n\nChances are that you followed the logic of 1) create a little plotting data frame, 2) use `augment()` from the broom package, and 3) shove it into ggplot.  \n\nYou may have ended up with something like this:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nplotdat <- data.frame(\n  age = mean(liedf$age),\n  anx = mean(liedf$anx),\n  strategy = unique(liedf$strategy)\n)\nbroom::augment(liemod, \n               newdata=plotdat, \n               interval=\"confidence\") |>\n  ggplot(aes(x=strategy,y=.fitted, col=strategy))+\n  geom_pointrange(aes(ymin=.lower,ymax=.upper)) +\n  guides(col=\"none\")\n```\n\n::: {.cell-output-display}\n![](08_ex_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=80% height=300px}\n:::\n:::\n\n\n\n\nThese plots are great, but they don't really show the underlying spread of the data. They make it seem like _everybody_ in the 'do nothing' strategy will have a heart rate between 56 and 59bpm. But that interval is where we expect the _mean_ to be, not where we expect the individuals scores to be.  \n\nCan you add the original raw datapoints to the plot, to present a better picture?  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThis is tricky, and we haven't actually seen it anywhere in the readings or lectures.  \nThe thing that we're giving to ggplot (the output of the `augment` function) doesn't have the data in it.  \nWith ggplot we can actually pull in data from different sources:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data1, aes(x=x,y=y)) + \n  geom_point() +\n  geom_point(data = data2, aes(x=x,y=newy))\n```\n:::\n\n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-4' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\nSo here was our nice plot:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplotdat <- data.frame(\n  age = mean(liedf$age),\n  anx = mean(liedf$anx),\n  strategy = unique(liedf$strategy)\n)\nbroom::augment(liemod, \n               newdata=plotdat, \n               interval=\"confidence\") |>\n  ggplot(aes(x=strategy,y=.fitted, col=strategy))+\n  geom_pointrange(aes(ymin=.lower,ymax=.upper)) +\n  guides(col=\"none\")\n```\n\n::: {.cell-output-display}\n![](08_ex_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nWe want to add to that the original data.. but all that original data is in a different dataset!  \n\nHowever, that doesn't mean we can't use it.  \n\nLet's try to add points for all our heart rates, and we'll tell `geom_point()` to look in our original dataset.  \n\nThe thing we need to be careful with is that our original dataset doesn't have anything called `.fitted` in it, which is currently on our y-axis. So we need to specify the y we want it to use (in this case, the `hr` variable)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbroom::augment(liemod, \n               newdata=plotdat, \n               interval=\"confidence\") |>\n  ggplot(aes(x=strategy,y=.fitted, col=strategy))+\n  geom_pointrange(aes(ymin=.lower,ymax=.upper)) +\n  guides(col=\"none\") +\n  geom_point(data = liedf, aes(y = hr))\n```\n\n::: {.cell-output-display}\n![](08_ex_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nOkay, the data is on there.. now we just need to make it look nice. My instinct here is to jitter again.\nI'm also going to make the plots black, and a little transparent, so that we can still see the means.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbroom::augment(liemod, \n               newdata=plotdat, \n               interval=\"confidence\") |>\n  ggplot(aes(x=strategy,y=.fitted, col=strategy))+\n  geom_pointrange(aes(ymin=.lower,ymax=.upper)) +\n  guides(col=\"none\") +\n  geom_jitter(data = liedf, aes(y = hr), width = .2, height = 0,\n              col = \"black\", alpha = .3)\n```\n\n::: {.cell-output-display}\n![](08_ex_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nThis is just _one_ way to better visualise our findings.  \n\nIf you're feeling adventurous, try: \n\n- a violin plot to show the distributions, rather than jittered points\n- what happens when you put `position = position_nudge(x=.3)` inside the `geom_pointrange()`?  \n- what happens if you add `coord_flip()` to the plot?  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Job Satisfaction, Guaranteed\n\n:::frame\n__jobsatpred.csv__  \n\nA company is worried about employee turnover, and they are trying to figure out what are the main aspects of work life that predict their employees' job satisfaction. 86 of their employees complete a questionnaire that leads to a 'job satisfaction score', that can range between 6 to 30 (higher scores indicate more satisfaction).     \n\nThe company then linked their responses on the questionnaire with various bits of information they could get from their human resources department, as seen in @tbl-jobsatdict.  \n\nThe data are available at [https://uoepsy.github.io/data/usmr_jobsatpred.csv](https://uoepsy.github.io/data/usmr_jobsatpred.csv){target=\"_blank\"}.  \n\n\n\n\n::: {#tbl-jobsatdict .cell layout-align=\"center\" tbl-cap='usmr_jobsatpred.csv data dictionary'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lxcxwmmxpd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lxcxwmmxpd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lxcxwmmxpd thead, #lxcxwmmxpd tbody, #lxcxwmmxpd tfoot, #lxcxwmmxpd tr, #lxcxwmmxpd td, #lxcxwmmxpd th {\n  border-style: none;\n}\n\n#lxcxwmmxpd p {\n  margin: 0;\n  padding: 0;\n}\n\n#lxcxwmmxpd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lxcxwmmxpd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lxcxwmmxpd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lxcxwmmxpd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lxcxwmmxpd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lxcxwmmxpd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lxcxwmmxpd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lxcxwmmxpd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lxcxwmmxpd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lxcxwmmxpd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lxcxwmmxpd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lxcxwmmxpd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lxcxwmmxpd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lxcxwmmxpd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lxcxwmmxpd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lxcxwmmxpd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lxcxwmmxpd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lxcxwmmxpd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lxcxwmmxpd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lxcxwmmxpd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lxcxwmmxpd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lxcxwmmxpd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lxcxwmmxpd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lxcxwmmxpd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lxcxwmmxpd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lxcxwmmxpd .gt_left {\n  text-align: left;\n}\n\n#lxcxwmmxpd .gt_center {\n  text-align: center;\n}\n\n#lxcxwmmxpd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lxcxwmmxpd .gt_font_normal {\n  font-weight: normal;\n}\n\n#lxcxwmmxpd .gt_font_bold {\n  font-weight: bold;\n}\n\n#lxcxwmmxpd .gt_font_italic {\n  font-style: italic;\n}\n\n#lxcxwmmxpd .gt_super {\n  font-size: 65%;\n}\n\n#lxcxwmmxpd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lxcxwmmxpd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lxcxwmmxpd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lxcxwmmxpd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lxcxwmmxpd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lxcxwmmxpd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lxcxwmmxpd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lxcxwmmxpd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lxcxwmmxpd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Employee Surname</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">commute</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Distance (km) to employee residence (note, records have used a comma in place of a decimal point)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">hrs_worked</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Hours worked in previous week</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">team_size</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Size of the team in which the employee works</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">remote</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Whether the employee works in the office or remotely (0 = office, 1 = remote)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">salary_band</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Salary band of employee (range 1 to 10, with those on band 10 earning the most)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">jobsat</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Job Satisfaction Score (sum of 6 questions each scored on 1-5 likert scale)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\nRead in the data. Look around, do any cleaning that might be needed.\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-5' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  Solution Part 1 - identifying problems</button></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\njsdat <- read_csv(\"https://uoepsy.github.io/data/usmr_jobsatpred.csv\")\n```\n:::\n\n\n\nJust looking at the top of the data, I already know that `commute` is a problem..  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(jsdat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  name          commute hrs_worked team_size remote salary_band jobsat\n  <chr>         <chr>        <dbl>     <dbl>  <dbl>       <dbl>  <dbl>\n1 Sayavong      44,1            28         6      0           3     22\n2 Herman        1,0             60         2      0           2     14\n3 el-Nour       2,6             10         6      0           6     25\n4 Barnes Saputo 0,4             46         4      0           9     27\n5 Laurents      3,0             24         4      1           1     12\n6 Lawton        5,3             42         1      0           2     17\n```\n\n\n:::\n:::\n\n\n\n\nThe summary shows us a few other things..\n\n- `remote` has a max of 2, but it should be 0s and 1s, because it's a binary variable according to our data dictionary.  \n- `jobsat` should surely be between 6 and 30 (this is that idea of 6 questions where you score between 1 and 6 means your minimum should be 6, and maximum should be 30). Here we have a min of 0 and a max of 31 so something's amiss there.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(jsdat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     name             commute            hrs_worked      team_size    \n Length:93          Length:93          Min.   : 3.00   Min.   :0.000  \n Class :character   Class :character   1st Qu.:24.00   1st Qu.:2.000  \n Mode  :character   Mode  :character   Median :32.00   Median :3.000  \n                                       Mean   :31.99   Mean   :3.269  \n                                       3rd Qu.:41.00   3rd Qu.:4.000  \n                                       Max.   :65.00   Max.   :7.000  \n     remote        salary_band        jobsat     \n Min.   :0.0000   Min.   :1.000   Min.   : 0.00  \n 1st Qu.:0.0000   1st Qu.:2.000   1st Qu.:16.00  \n Median :0.0000   Median :3.000   Median :19.00  \n Mean   :0.1935   Mean   :3.602   Mean   :19.11  \n 3rd Qu.:0.0000   3rd Qu.:5.000   3rd Qu.:23.00  \n Max.   :2.0000   Max.   :9.000   Max.   :31.00  \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-6' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  Solution Part 2 - figuring out fixes</button></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\n\nVariables are all appropriate types apart from `commute`.  \nIf we're being good, we should probably also set `remote` to be a factor as it is two distinct categories.  \n\nFor the commute variable, we need to first (prior to making it a numeric variable), replace all the commas with a point - \".\". We can do this using `gsub()`.  \n\nFor the remote variable, we know it only has two possible levels - 0 and 1. However, we saw earlier that there was a 2 in there as well. But there's only one of them, so it's probably a typo or something.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum(df$remote==2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\n\nWe should probably replace that with an NA as it is an impossible value, and we have no idea whether it is supposed to be a 0 or a 1.  \nAs it happens, by giving the `factor()` function only the levels we want to keep, it will replace any others with `NA`s.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfactor(c(\"dog\",\"cat\",\"parrot\"), levels=c(\"dog\",\"cat\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] dog  cat  <NA>\nLevels: dog cat\n```\n\n\n:::\n:::\n\n\n\n\nWe also noted that the `jobsat` variable had some values that were $<6$ and $>30$. \nWe can replace those with NAs as well, using that handy `ifelse()` function!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- c(1,16,50,72)\n# if x is less than 10 or x is less than 70, give me an NA, \n# otherwise give me the value of x\nifelse(x<10 | x>70, NA, x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA 16 50 NA\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-7' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  Solution Part 3 - implementing</button></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\n\nLet's do this bit of cleaning all in one mutate:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\njsdat <- \n  jsdat |> \n    mutate(\n      commute = as.numeric(gsub(\",\",\".\",commute)),\n      remote = factor(remote, levels = c(\"0\",\"1\"),\n                      labels = c(\"office\",\"remote\")),\n      jobsat = ifelse(jobsat < 6 | jobsat > 30, NA, jobsat)\n    )\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 11</div><div class='question-body'>\n\n\nExplore! Make some quick plots and calculate some quick descriptives.  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tableone)\nCreateTableOne(data = jsdat |> select(-name))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         \n                          Overall      \n  n                          93        \n  commute (mean (SD))      4.20 (4.88) \n  hrs_worked (mean (SD))  31.99 (13.37)\n  team_size (mean (SD))    3.27 (1.68) \n  remote = remote (%)        16 (17.4) \n  salary_band (mean (SD))  3.60 (2.42) \n  jobsat (mean (SD))      19.40 (4.40) \n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(psych)\npairs.panels(jsdat)\n```\n\n::: {.cell-output-display}\n![](08_ex_files/figure-html/unnamed-chunk-35-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nIt looks like `commute` has a __big__ outlier!! \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmax(jsdat$commute)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 44.1\n```\n\n\n:::\n:::\n\n\n\nIt's not impossible though (44 km commute?), it's just quite different.. chances are this may come out as an influential datapoint in our model, but I have no obvious reason to exclude this observation just because they live far away! \n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 12</div><div class='question-body'>\n\n\nFit a model to examine the independent associations between job satisfaction and all of the aspects of working patterns collected by the company.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nWe want to look at the independent associations, so we want a multiple regression model.  \nWe don't really have any theoretical order in which to put the predictors in our model. However, this mainly matters when we use `anova(model)` - if we are just going to look at the coefficients (which is what we will be doing), then we can put them in any order for now. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\njsmod <- lm(jobsat ~ commute + hrs_worked + team_size + remote + salary_band, jsdat)\nsummary(jsmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = jobsat ~ commute + hrs_worked + team_size + remote + \n    salary_band, data = jsdat)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-5.245 -1.188 -0.010  1.402  3.862 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  14.65369    0.87424  16.762  < 2e-16 ***\ncommute       0.07175    0.04469   1.605 0.112201    \nhrs_worked   -0.06424    0.01627  -3.948 0.000165 ***\nteam_size     0.43577    0.13337   3.267 0.001579 ** \nremoteremote -2.09258    0.58744  -3.562 0.000612 ***\nsalary_band   1.52322    0.09385  16.231  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.042 on 83 degrees of freedom\n  (4 observations deleted due to missingness)\nMultiple R-squared:  0.7982,\tAdjusted R-squared:  0.786 \nF-statistic: 65.64 on 5 and 83 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 13</div><div class='question-body'>\n\n\nCheck the assumption plots from the model. Remember we had that employee who was commuting quite far - are they exerting too much influence on our model?  \nIf so, maybe refit the model without them.  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nWe can see below that there is that one very influential observation (see bottom right plot). It's almost 6 times more than the next most influential one.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(jsmod, which=c(1:4))\n```\n\n::: {.cell-output-display}\n![](08_ex_files/figure-html/unnamed-chunk-38-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nWe can see from the plots that it is row 1 in the data, and below we confirm this:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(influence.measures(jsmod))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPotentially influential observations of\n\t lm(formula = jobsat ~ commute + hrs_worked + team_size + remote +      salary_band, data = jsdat) :\n\n   dfb.1_ dfb.cmmt dfb.hrs_ dfb.tm_s dfb.rmtr dfb.slr_ dffit   cov.r   cook.d\n1   0.37  -1.88_*  -0.01    -0.01     0.00    -0.03    -1.94_*  3.73_*  0.63 \n39 -0.05  -0.01     0.05     0.03    -0.01     0.04     0.07    1.23_*  0.00 \n51  0.23  -0.06    -0.04    -0.10    -0.66    -0.38    -0.79    0.75_*  0.10 \n76 -0.16   0.06    -0.01     0.33     0.07    -0.23    -0.56    0.67_*  0.05 \n79 -0.14  -0.15     0.44    -0.24     0.13    -0.14    -0.64    0.78_*  0.07 \n   hat    \n1   0.74_*\n39  0.13  \n51  0.09  \n76  0.04  \n79  0.07  \n```\n\n\n:::\n:::\n\n\n\n\nWe'll refit the model without that observation:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\njsmod1 <- lm(jobsat ~ commute + hrs_worked + \n               team_size + remote + salary_band, \n             data = jsdat[-1,])\n```\n:::\n\n\n\nAnd check again. These look much better in terms of influencers. The main assumption plots don't look _terrible_, but they're not perfect (but then nothing ever is!).  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(jsmod1, which=c(1:4))\n```\n\n::: {.cell-output-display}\n![](08_ex_files/figure-html/unnamed-chunk-41-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 14</div><div class='question-body'>\n\n\nNow fit a second model, in which the predictors are standardised (those that can be).  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- You can either standardise just the predictors, or standardise both predictors and outcome (see [8A #standardised-coefficients](08a_scaling.html#standardised-coefficients){target=\"_blank\"}).\n- If you've excluded some data in the model from the previous question, you should exclude them here too.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\njsmodZ <- lm(scale(jobsat) ~ scale(commute) + scale(hrs_worked) + \n               scale(team_size) + remote + scale(salary_band), \n             data = jsdat[-1,])\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 15</div><div class='question-body'>\n\n\nLooking at the standardised coefficients, which looks to have the biggest impact on employees' job satisfaction?  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nSalary has a big positive impact.\nThen remote working (negative impact)\nThen hours worked (negative impact)\nThen team size (positive)\nThen commuting distance (positive, but non-significant)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(jsmodZ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = scale(jobsat) ~ scale(commute) + scale(hrs_worked) + \n    scale(team_size) + remote + scale(salary_band), data = jsdat[-1, \n    ])\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.15723 -0.23466  0.03139  0.36020  0.89447 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         0.09466    0.05422   1.746 0.084589 .  \nscale(commute)      0.08950    0.04901   1.826 0.071441 .  \nscale(hrs_worked)  -0.19522    0.04948  -3.945 0.000167 ***\nscale(team_size)    0.16464    0.05008   3.287 0.001490 ** \nremoteremote       -0.47368    0.13289  -3.564 0.000611 ***\nscale(salary_band)  0.84099    0.05163  16.288  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4618 on 82 degrees of freedom\n  (4 observations deleted due to missingness)\nMultiple R-squared:  0.8006,\tAdjusted R-squared:  0.7884 \nF-statistic: 65.85 on 5 and 82 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 16</div><div class='question-body'>\n\n\nThe company can't afford to pay employees anymore, and they are committed to letting staff work remotely. \nWhat would you suggest they do to improve job satisfaction?  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nYou might argue here that because `hrs_worked` has the next biggest effect, we should suggest the company reduces the working hours.  \n\nThe standardised coefficients are telling us that:  \n\n- a person who works 1 SD hours more is .19 SD lower on job satisfaction\n- a person in a team 1 SD bigger is .16 SD higher on job satisfaction  \n\nSo what _are_ the standard deviations of `hrs_worked` and of `team_size`? Are they even worth comparing?  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsd(jsdat$hrs_worked)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.37299\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(jsdat$team_size)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.675526\n```\n\n\n:::\n:::\n\n\n\n\nSo what our standardised coefficients are really saying is:\n\n- a person works 13.4 hours more is .19 SD lower on job satisfaction\n- a person in a team 1.67 people bigger is .16 SD higher on job satisfaction  \n\nYou could easily argue from this that a much easier way the company could improve job satisfaction is to make team sizes a bit bigger - rather than letting people work 13 hours less than they currently do! \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n\n",
    "supporting": [
      "08_ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}